### ISSUE TITLE
[Feature Request] New system-wide events "OnBeforeAssistEdit" and "OnAfterAssistEdit"

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/AL#1008]
Unfortunately, there are always cases in the standard system where you have to intervene in the AssistEdit. This can be done both before and after. Therefore, it would be good if there were the same events that existed during validation. 

Perhaps the names "OnBeforeAssistEdit" and "OnAfterAssistEdit" would make sense.

**Comment by esbenk** [comment]
"enhancement","suggestion" means that we have added it as a feature on our backlog that we may introduce in the future. This means processed for now, but not ignored. 

We are aware that we still have areas/functionality the new extension model doesn't support yet. The OnAssistEdit trigger is just one of these areas. We don't have unlimited resources and have to prioritize our work.

This is not application events, but system triggers, and hence not something that the application teams can "just" add like the many other application event-requests. It is a different set of resources that add application events, than those working on the platform. 

The OnAssistEdit trigger is a bit problematic, because what you what is to replace functionality. You don't what just to display an extra page before or after. Allowing that would mean that two extensions could /would be incompatible if they both want to override the same. We know we need a model for this, but it is a bit more work that just raising an event.

**Comment by jensmpmsft** [comment]
As Esben writes, then then the current trigger OnAssistEdit does not lend itself well to extending. Relying on subscribers to adhere to the Handled pattern is somewhat fragile - and it does not really allow 'extending' the functionality and leads to the problem you mention about 'who' is winning.

We have put it on our backlog for future functionality, but we currently do not know when we will get to this one

**Comment by LFlamme** [comment]
Is there a plan when this will be done? We have a lot of cases where we can´t get all of out code out of Pages because we miss an AssistEdit event. Would it be a solution if we request those as normal Event Requests? In that case we would get our code out of the pages and you can work on a solution?

Thanks in advance

**Comment by qutreson** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. as mentioned in the discussions above, this issue appears to require additional grooming of the expected behavior and would require changes across multiple areas of our product (compiler, runtime, etc.). We recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there. We are constantly monitoring top ideas and will consider them for a future release.
