### ISSUE TITLE
Inconsistent syntax highlighting of record members

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/AL#101]
The syntax highlighting of record members seems to be a bit inconsistent:

![image](https://cloud.githubusercontent.com/assets/1166791/23261906/dfd8a668-f9d8-11e6-88a2-b5c75ff003b8.png)

Why are Modify and TestField highlighted differently in this example?

I guess Code is highlighted differently because it is also a datatype, but I feel like IntelliSense should be able to distinguish the two from one another.

All the default Color Schemes provide the same result.

**Comment by esbenk** [comment]
Modify is a new keywords used in extensions and testfield is a datatype.

You are completely right that IntellseSense should (and can) be able to distinguish between them, but the problem is that VsCode doesn't currently support syntax-highlighting based on symbolic information. It only supports TextMate language specification, which is more simplistic. More information here[http://code.visualstudio.com/docs/customization/colorizer](http://code.visualstudio.com/docs/customization/colorizer)

The AL TextMate is found the extension directory in <extensionfolder>/syntaxes/alsyntax.tmLanguage

**Comment by IvoMol** [comment]
I do not know the meaning new words, but suggestion only:
If word "modify" will be new in extensions, use fully different word, like "change" or "update".
If word "testfield" will be new datatype, use as datatype word "fieldtest".

Not colors, but keywords duplication will be confusing.

**Comment by kaspermoerch** [comment]
@esbenk According to the linked documentation (if I'm reading it right) - shouldn't datatypes be listed as "storage.type" instead of "keyword.other"? Or does that not change anything?

**Comment by esbenk** [comment]
The problem is that they are a type or a keyword, depending on context. The VsCode colorizer can only have them in one category. If VsCode at some points supports colorization based on symbolic information we will be able to have different colorization in different contexts.
