### ISSUE TITLE
Request: UrlEncode

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1042]
We use System.Web.HttpUtility.UrlEncode(string) to urlencode text for some web calls. 

Is there an alternative in AL? 

If there is not, could we get one? 

Thanks!

**Comment by Gallimathias** [comment]
Not that I know of.

You could use the JavaScript variant encodeURIComponent () as long as there is nothing else. The result is identical with WebUtilitiy.UrlEncode.

As a little hint by the way, it is better to use WebUtilitiy.UrlEncode instead of HttpUtility.UrlEncode because the latter is only for. NET under 4.5.

**Comment by StanislawStempin** [comment]
You can use COD10.UrlEncode

**Comment by strophanthus** [comment]
Awesome, we will give that a try. Thanks
