### ISSUE TITLE
The type or method 'Object' cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1049]
The virtual table 'Object' isn't usable anymore in AL.
This can be a problem fe report selections.
What should be used in replace, 'AllObjWithCaption' table like NAV uses in table 77 Report Selections?

**Comment by dennisfrostlander** [comment]
If you can use AllObjWithCaption or AllObj for your scenario, that would be great. 
Certain internal tables have been blocked for Extension development, since those are primarily targeted for AppSource.

If you absolutely need to use the blocked table, you could still set `"target"` property to `"Internal"` in `app.json`, but this is typically not desirable.

**Comment by SirBETE** [comment]
@dennisfrostlander 
Thanks!
