### ISSUE TITLE
Will the conversion tool handle optionstring conversion?

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1058]
Apologies for the duplicate, I was asked to make a new one. 

During the discussion it was discovered this is specifically not converting when it is a fieldref variable. 

fieldref.optionstring is not being converted to fieldref.optionmembers. 

Of course this causes fieldref.optionstring to show up as an issue in VS Code and has to be changed manually. 

Will this be handled by the txt2al tool?

**Comment by esbenk** [comment]
No. The txt2al is today not parsing the actual AL source, meaning that we don't have semantic model for that part of the source. 

The OptionString method/property is still working, but the new name is OptionMember. The new name is to align with the fact that option outcomes are a list of identifiers and not a string.

The issue is only a warning. Functionality is still there.

**Comment by strophanthus** [comment]
Please answer whether this will never be handled or if it may be eventually.

**Comment by esbenk** [comment]
We have no plans for changing OptionString to OptionMembers during the conversion process, but the code with OptionString will still work, but just issue a warning.

**Comment by strophanthus** [comment]
Okay, thanks for the answer
