### ISSUE TITLE
AutoIncrement not updating

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1079]
Start with a table with an autoincrement key
```
table id MyTable
{

    fields
    {
        field(1;MyField;Integer)
        {
            AutoIncrement=true;
        }
    }

    keys
    {
        key(PK;MyField)
        {
            Clustered = true;
        }
    }
    
    var
        myInt : Integer;

    trigger OnInsert();
    begin
    end;

    trigger OnModify();
    begin
    end;

    trigger OnDelete();
    begin
    end;

    trigger OnRename();
    begin
    end;

}
```

Build 
Publish
Install

Now change that field to not autoincrement

```
table id MyTable
{

    fields
    {
        field(1;MyField;Integer)
        {
            AutoIncrement=false;
        }
    }

    keys
    {
        key(PK;MyField)
        {
            Clustered = true;
        }
    }
    
    var
        myInt : Integer;

    trigger OnInsert();
    begin
    end;

    trigger OnModify();
    begin
    end;

    trigger OnDelete();
    begin
    end;

    trigger OnRename();
    begin
    end;

}
```

Rebuild 
Uninstall old
Unpublish old
Publish new
Install new

Navigate to a page for this table and attempt to enter a value in the field that was once set to autoincrement (or populate it in oninsert, either way)

There will be an error, the same you would get if autoincrement was set to true (as it was initially): 
"The following SQL error was unexpected:Cannot insert explicit value for identity column in table 'Company$MyTable' when IDENTITY_INSERT is set to OFF. 

Identity properties for a key that was never set to autoincrement: 
![image](https://user-images.githubusercontent.com/32313731/33784198-280020ca-dc1d-11e7-807b-f1b2ab2489a7.png)

Identity properties for this field that does not appear to be changing: 
![image](https://user-images.githubusercontent.com/32313731/33784173-12a2cd90-dc1d-11e7-8143-069fa2f94299.png)

**Comment by HunterFeltman-MSFT** [comment]
When going though the steps of managing your extension (publish, unpublish, etc). Are you using VSCode to do this, or the 'client' or manually doing it via cmdlets?

Extensions V2 also have a new 'sync' step involved in their management where the sql schema is actualy modified. This step is normally handled automatically via the VSCode F5 'publish' commands so you shouldn't have to deal with it in simple development.
 
Normally, if you were doing this manually, you would just be able to sync your new extension and have any new schema elements added (new tables, new fields), however, your example is considered to be a breaking schema change (which is not allowed) and so requires a complete removal of the original schema before the new one can be created.

To do this, you would use the Sync-NavApp cmdlet with the 'Clean' mode specified.

` Sync-NavApp -ServerInstance <instance> -Name <name of app> -Mode Clean` 

The 'clean' mode of the sync cmd will go through and remove any schema elements of the target extension (tables, table extensions). Note that this means **complete data loss**.

I'm assuming that between your 2 examples, you did not bump the version number in the app.json for the extension. Since the old version would still be 'synced' (It is not 'unsynced' upon unpublish) the platform would think that the new package is also 'in sync' and allow you do things like install.
This would lead to the error you've shown where your metadata says AutoIncrement=false, but SQL says AutoIncrement=true

**Comment by strophanthus** [comment]
Hey Hunter. 

I am using VS code to build the extension and powershell to publish and install. 

I have also used F5 in VS code to go in to debugging and the same behavior is seen. 

I have synced the tenant and the app, and neither have helped. 

I did not try the clean switch, but it meaning a complete data loss is definitely not ideal. Our app is already live in appsource, the v2 extension deleting user data is not something we can do. 

The version number did not change in the json for these different cases. Can you explain that portion more?

**Comment by strophanthus** [comment]
Okay had some time to think about this more, and to try changing the version number, 

That did allow the schema changes to persist, which is great. However this is not the most convenient for the development stage. It's preferable to be able to test incrementally and this can lead to situations where table changes are made that need to be tested right away.  Changing the version number in order to test these changes is not ideal behavior.  

I understand only applying table changes when the version changes in live situations, and of course updates will (should) have new version numbers. 

To allow for both, could we have something like a development switch/flag?

**Comment by HunterFeltman-MSFT** [comment]
Right, so in development when strictly using VSCode to handle the publish/sync/install of your extensions (F5 or Ctrl + F5 for no debug) then a **Sync 'clean' should already be happening**. 
As such, this allows you to do things like make breaking schema changes without bumping the version number and redeploy (F5). Since the data in the extension tables is deleted, it would be simple to verify it's happening by F5-ing, entering in some data, then re-F5-ing and asserting that the data is gone.

It is surprising to hear that you are experiencing different behavior from VSCode, unless I'm misunderstanding your comment?

Having a 'switch' for this kind of 'do not auto-clean' is akin to asks that pertain to 'upgrade' testing, see issues: #722 & #62

**Comment by strophanthus** [comment]
What I mean to say is using F5 to debug also did not apply the schema changes. The data is being removed, but the table changes did not showing up. I could get around that by changing the version.

**Comment by HunterFeltman-MSFT** [comment]
I don't seem to be able to repro this scenario with VSCode, can you relay what version of the AL extension you are using? Or what preview you are on? (Oct, Nov, etc?)

**Comment by strophanthus** [comment]
Since this has gone a little off topic, to recap: The autoincrement property on a key being changed is not going through for us unless the version number is changed, which is not preferred during development. This is happening when using F5 and when using the powershell scripts while using CTP17 dvd with extension 0.12.15245. 

I'm attempting to get the latest preview (19590) to check there, the azure vm has had some trouble with the automated setup though so I haven't had a chance yet. 

Data preservation during development is being covered in those other issues, as you mentioned.

**Comment by strophanthus** [comment]
Okay, have now had a chance to test this on the latest preview and it does not seem to be an issue there. 

I'll check when we get a newer dvd to see if it could be related to using our own nav service, db, etc. But given the results today and the other tickets already existing for data preservation this issue appears to no longer be an issue.

**Comment by HunterFeltman-MSFT** [comment]
Awesome, thanks for double checking against latest.
