### ISSUE TITLE
TryFunction not working or present?

### ISSUE THREAD

**Issue by megel** [Microsoft/AL#1137]
In the post https://github.com/Microsoft/AL/issues/270 I found a closed question about the TryFunction attribute.

Now the december release is available and I try the following code:
 
```javascript
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin        
        // Test the TryFunction
        if not TryFunctionTest then 
          Message('TryFunction got the error')
        else
          Message('no Error');
    end;
        
    [TryFunction]
    local procedure TryFunctionTest(): Boolean;    
    var Stm: InStream;
        Txt: Text;
    begin
        // this should raise an error :)
        Stm.ReadText(Txt, 500);
        exit(True);
    end;
}
```

The result is not handled as expected:
![grafik](https://user-images.githubusercontent.com/15800069/33830692-7476df66-de75-11e7-83d6-5957394db41c.png)

What would be the right way, to use the concept of Try-Functions?

**Comment by kalberes** [comment]
It is on our backlog, but nothing has been worked on yet to replace it, given that its primary usage scenario was AL based .net exception handling.

**Comment by NKarolak** [comment]
My personal "primary usage scenario" is to run various TESTFIELDs on many  (customized) document lines at runtime. Failed lines are marked in red for faster recognition, restoring to standard as soon as the user has fixed the line data. The code called by the TryFunction is also used when trying to release the document --> throw the actual error message. 
In order to use repeatable code with and without error message, the TryFunction is very useful.

**Comment by markbrummel** [comment]
Tried to use it today to catch an error on the new Json types. Would be nice if this worked.

**Comment by megel** [comment]
@StanislawStempin what is the current status? 
Will we get TryFunctions or not?
If yes - when can we expect the TryFunctions?

**Comment by StanislawStempin** [comment]
We are currently working on it. TryFunctions will ship in the next major release of Business Central in Fall 2018.

**Comment by StanislawStempin** [comment]
TryFunctions shipped with Business Central Fall 2018. Please let us know if you encounter scenarios in which it doesn't behave as it used to.

**Comment by svwfr** [comment]
Will this also work for NAV2018, coding in Extension v2.0?
I am current on build: 0.12.28462 and have hard time to figure out the statement for adding [TryFynction] to my procedure. Is there any excamples to review?

**Comment by svwfr** [comment]
Hi, am current on build 0.12.28462 and try to use the [TryFunction]. I have entrede the try procedure similar to Megel's example: [TryFunction] local procedure TryAsciiExportSalesHeader().
The issue happens when i call my procedure within a IF-THEN: if TryAsciiExportSalesHeader then begin. VSC markes it With "problems" With statement: Cannot implicitly convert type 'None' to 'Boolean' [AL0122]

**Comment by StanislawStempin** [comment]
@svwfr, this is not supported in NAV 2018

**Comment by svwfr** [comment]
Now I have tried the [TryFunction] with the NAV2018 CU14 (build 27667), AL Language 0.13.82793  (Compiler version 0.13.1.17259) and supricly no compilation error as I explored with AL Language 0.12.28462.  Is it supported for NAV2018 now?

Though, it does not work as intended as the orginial error is breaking the the code sequence and not my local code after call the TRY function. I did the same test within C/SIDE with success, as my local message was returned and not the orginial error-message.

The call I hoped to do a "try" for was: 
Customer.CheckBlockedCustOnDoc(Customer,SalesHeader."Document Type",true,true);
