### ISSUE TITLE
Customer "shoe size" extension seems incomplete.

### ISSUE THREAD

**Issue by mcerdeira** [Microsoft/AL#118]
I'm going through the examples here: C:\DEMO\New Developer Experience\Samples
In the example "CustomerTableExtension" I can see the new field "Shoe size", but this code unit never gets executed:

```C#
codeunit 70050040 CreateCustomer
{
    trigger OnRun();
    var
        r : record Customer;
    begin
        if not r.HasShoeSize() then
            r.ShoeSize :=  42;  
    end;
}
```
And is a bit confusing.
A more complete example can be found here:
[Example](https://msdn.microsoft.com/en-us/dynamics-nav/newdev-table-ext-object)
Where the table extension uses the HasShoeSize() method.

**Comment by esbenk** [comment]
You are absolutely right. The code never gets executed. The sample was included to show how the fields from the tableextension are available on a record of type Customer.

Currently the samples are mostly displaying the modern syntax and new features rather than being actual polished extensions.

It is our plan to add more extension samples in the future.
