### ISSUE TITLE
Cloud not download symbol NAV 2018

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/AL#1186]
Hi,
I installed NAV 2018 NA in my local database.
Updated Visual Studio Code 1.18.1 and AL Language 0.11.14434

my launch.json 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://localhost",
            "port": 9049,
            "serverInstance": "DynamicsNAV110",
            "authentication": "Windows",
            "startupObjectId": 22
        }
    ]
}

my app.json looks like this
{
  "id": "375efc6f-8ede-45c0-857b-b9392a0d53e1",
  "name": "NAV2018",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

The error looks like this
[2017-12-13 02:20:10.97] Using reference symbols cache path: c:\Users\TestLab\Documents\AL\NAV2018\.alpackages
[2017-12-13 02:25:18.81] Sending request to http://localhost:9049/DynamicsNAV110/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0
[2017-12-13 02:25:18.81] Sending request to http://localhost:9049/DynamicsNAV110/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0
[2017-12-13 02:25:26.08] The request for path /DynamicsNAV110/dev/packages?publisher=Microsoft&appName=Application&versionText=11.0.0.0 failed with code InternalServerError. Reason: One or more errors occurred.
[2017-12-13 02:25:26.08] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.

is there any setting, I am missing in the NAV server configuration or in .json file.

**Comment by peikba** [comment]
Are you sure that the port is correct?

Normally it is 7049.
Check your service tier setup.

Also name must always be same as server

"name": "localhost",
"server": "http://localhost",

**Comment by anwar0206** [comment]
Hi @peikba @kalberes , 
The port was 9049, I configured it back to 7049 in the service configuration.
I changed the settings of "name":"localhost"
Restarted the NAV service and tried downloading the symbols again.

But symbols are not downloaded.

I tried installing the AL Extension provided with the NAV 2018 setup.
Below is the screen shot for your reference.
![image](https://user-images.githubusercontent.com/17919266/33955985-492ebd96-e00b-11e7-967d-72324d7068f2.png)
![image](https://user-images.githubusercontent.com/17919266/33956106-99f5672a-e00b-11e7-904a-085755469c17.png)
![image](https://user-images.githubusercontent.com/17919266/33956202-d75ea84c-e00b-11e7-8393-22b8486cc761.png)

The Firewall is Turned off and NAV Service is running and is accessible by RTC.

**Comment by HunterFeltman-MSFT** [comment]
Your message is now responding back with 'Package Not Found' instead of a connection/server error. 
VSCode downloads the symbol packages from the target NST, but they must first be published to that NST. Could you check that the application & system symbols are published? This can be accomplished with a cmdlet:  
`Get-NavAppInfo -ServerInstance DynamicsNAV110 -SymbolsOnly`

You 'should' see at least 2 results, one for 'Application' and one for 'System'

**Comment by HunterFeltman-MSFT** [comment]
If need be, you can get the latest symbols packages from the [December Preview](https://blogs.msdn.microsoft.com/nav/2017/12/06/nav-development-preview-december-update/). use VSCode on the preview to download the symbols packages and then just copy them locally.

**Comment by anwar0206** [comment]
Hi @HunterFeltman-MSFT ,

After executing the above cmdlet, I din't got any result back.

I had tried the following website for generating the symbols
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side

**Comment by HunterFeltman-MSFT** [comment]
The 'C\SIDE-By-side' should have at least given you the 'application' symbols if you ran:
`finsql.exe Command=generatesymbolreference, Database=”<Your Database>”, ServerName=<Your server>`
@kalberes for some insight there

That you received no results back from the cmdlet query suggests that you do not yet have symbols published to your NST, which would explain why VSCode cannot find them. 

If the new C\SIDE command isn't working, see if you can't take the other route of copying them off of the December Preview

**Comment by peikba** [comment]
Are You using this procedure?
- Ctrl+shift+P
- AL:Download Symbols

/Peik

Sendt fra min iPad

**Comment by anwar0206** [comment]
Yes, @peikba I am going through same process of Ctrl+Shift+P and AL:Download Symbols

**Comment by kalberes** [comment]
In order to work with extensions you need two type of symbols.
a. System symbols, these are system tables, virtual tables, etc symbol references.
b. Application symbols. These are references to application objects defined in your own base application.

You generate the application symbols for your own database using the finsql command above. 
Unfortunately we have only published the system and application symbols in the Cronus Database.  
You need these symbols to be published to your own database.
For the current NAv 2018 release you need the Cronus application symbols to be published to your own database, even-though if you have symbols generated from C/SIDE for your own application objects the cronus based application symbols will not be used. 
All this will be fixed in Nav 2018 CU1 where the system symbols will be part of the installation dvd as an app file. The Cronus application symbols will not be needed for your own custom database starting from CU1.
Do as @HunterFeltman-MSFT  suggests to get them from the December release Or create an extension based on a server that connects to cronus,  and get the symbols for this extension. Afterwards go to where they were downloaded and publish both the application(cronus) and system symbols apps to your own database. 
Publish-NAVApp -ServerInstance [Instance] -Path [Path to symbol file]-PackageType SymbolsOnly  
Symbols are downloaded to the "al.packageCachePath" settings in VSCode. It should be part of your own settings.json.

**Comment by anwar0206** [comment]
Hi @kalberes 

I am bit lost in achieving what @HunterFeltman-MSFT suggested. 

Not able to get al.packageCachePath.

New December Preview VM is made. I was able to connect the Preview VM's Visual Studio Code with the preview database and download the symbol in the VM'

I the folder .alpackages and pasted it in my local machine AL Project folder.

Just for making it double sure. The database which I was connecting is standard 2018 NA database.

**Comment by HunterFeltman-MSFT** [comment]
@anwar0206 Kalberes was speaking to a special setting in VSCode that dictates where the symbol packages are downloaded to when you use the 'AL:Download Symbols' command.

This special setting can be specified by you in a special file recognized by VSCode called 'settings.json' which must be located in your .vscode folder.
i.e the following folder structure
```
ALProjectFolder\
   <your al source files>
   app.json
   .vscode\
      launch.json
      **settings.json**
```

You are not required to create this settings.json file, nor specify this special setting. The 'default' value for this is: '<ALProjectFolder>\.alpackages'
Meaning that if you had never encountered this problem then when you executed the 'AL: Download Symbols' command you would have seen this folder get created and the 2 .app files placed there.

From your description of steps, it looks like you did exactly what I was asking for.
This should mean that now you have a project structure that looks like
```
ALProjectFolder\
   <your al source files>
   app.json
   .vscode\
      launch.json
   .alpackages\
      Microsoft_Application_*.app  // These are the application symbols (Typical DB objects you see in C\SIDE)
      Microsoft_System_*.app // These are the system symbols (System tables, special AL functions, virtual tables etc etc)
```

If this is true, then you should be ok to COMPILE an AL project in VSCode. However, you aren't yet ready to PUBLISH your extension to the server (i.e. F5-ish commands won't work yet) and this is Kalberes' second point.
Not only do the symbols need to be available 'locally' on the file system for VSCode, but you also need to 'publish' them to your server. Based on the images and folder structure above is correct, you would need to execute the following cmdlets:
```
Publish-NAVApp -ServerInstance DynamicsNAV110 -Path <ALProjectFolder>\.alpacakges\Microsoft_Application_<version>.app -PackageType SymbolsOnly
Publish-NAVApp -ServerInstance DynamicsNAV110 -Path <ALProjectFolder>\.alpacakges\Microsoft_System_<version>.app -PackageType SymbolsOnly`

```
This will publish the symbol packages to your server and thereby allow it to successfully compile your extension if you use the F5-ish commands from VSCode.

You can again check to make sure that they are published correctly by executing the following:
`Get-NavAppInfo -ServerInstance DynamicsNAV110 -SymbolsOnly`

I hope this helps to clear up confusion, let me know if I've made it worse.

**Comment by anwar0206** [comment]
Thanks, @HunterFeltman-MSFT @kalberes,

After following your suggestion, was able to download the symbols in Visual Studio code.
