### ISSUE TITLE
Suggestion: Get Request Page Parameters in CurrReport

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/AL#1252]
Hello Microsoft Team,

I have the question whether it is possible to get the "Request Page Parameters" in a current report.

It would help a lot of people to integrate an Archive System. Because actually it is not possible without a lot of programming to get the same view (when the user select some settings like for example "Show Internal Information") from the print and the pdf view. Your "Task Scheduler" is nearly working like this. But we cannot get the Request Page Parameters incl. the filters as a XML.

![actually](https://user-images.githubusercontent.com/34306673/34158160-a0999d54-e4c4-11e7-9dc1-c56e30429bf9.png)

![getrequestparameters](https://user-images.githubusercontent.com/34306673/34158159-a08260f8-e4c4-11e7-9ff9-45038faec8f5.png)

**Comment by thpeder** [comment]
We currently have no plans to implement it but thanks for the suggestion, we will add it to our long-term backlog.

**Comment by ashishsharmanavtech** [comment]
Any update on this? Is it implemented yet?

**Comment by thpeder** [comment]
Hi! 
It is unfortunately not implemented.
This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
