### ISSUE TITLE
Expose CopyDefaultDimToDefaultDim on PAG542

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1256]
I am wanting to add a new master table. To get it integrated with dimensions, it was the old fashioned way to create a function on PAG542 (Default Dimensions-Multiple) called SetMultiMasterTable (with MasterTable being the name of the new master table).

How do I do this the modern way?

I would like to apply the Discovery Pattern to the OnOpenPage trigger of PAG542, but then my code needs to call the function CopyDefaultDimToDefaultDim on PAG542, which is local.

So either change CopyDefaultDimToDefaultDim to global, dear MS, or tell me how I could achieve this differfently (and maybe even better).

(was first reported on yammer: [https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1003482268])

**Comment by JesperSchulz** [comment]
Consider it done! I will expose CopyDefaultDimToDefaultDim.

**Comment by lvanvugt** [comment]
Beng. Hoppa. Speed of light. Thanx, Jesper.

**Comment by lvanvugt** [comment]
Hey guys,

Build 20348 (CU 2) does not have this fix. So why close it?

**Comment by StanislawStempin** [comment]
This GitHub repo is related to the latest Developer preview releases and not strictly to NAV 2018 CUs (although we do take the input from here to proactively backport fixes to NAV 2018). 
This particular fix was released in the February Update of Dev Preview and therefore the issue is being closed. 

This FAQ entry should probably be expanded to include event requests as well, in general we only add them to the latest builds since they can be added manually On-Prem:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018
