### ISSUE TITLE
Suggestion : Change GoTo Definition

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1294]
GoTo Definition is not working the same as in C/Side

F12 takes you to the local variables, where you have to use a few keyboard shortcuts to move to the actual record and hit F12 again.

![image](https://user-images.githubusercontent.com/7205122/34300537-d53e8036-e728-11e7-97bf-f51b897b9563.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @markbrummel 
As I have written in another reply, this is the expected behaviour. AL vscode extension is not meant to be a direct replica of CSIDE. What is your expected behavior? Pressing f12 on a usage of a local variable takes you to its definition and then pressing f12 on the object reference in the variable definition takes you to that objects definition.

**Comment by markbrummel** [comment]
But... but...

Don't you slightly agree that this is counter productive? I have to press F12, then I have to arrow right and then F12 again.

I know where the variable is declared. It's a local unless it has to be global.

Can you discuss this in the team and please reconsider?

**Comment by bwdeleeuw** [comment]
How about when you press F12 anywhere on a variable definition line it goes to the object definition? That way we can still get to the variable definition, but by pressing F12 twice, we can get to the object?

**Comment by markbrummel** [comment]
I would be fine with that.

**Comment by DominikDitoIvosevic** [comment]
You can expect this to be available soon. Pressing f12 for the second time takes you to the definition of the original object
