### ISSUE TITLE
Problem with EventSubscriber

### ISSUE THREAD

**Issue by geraldbeaulieu877** [Microsoft/AL#1321]
[EventSubscriber(ObjectType::Codeunit, 40, 'OnAfterLoginStart', '', false, false)]
local procedure TestLogginStart();
begin
  Message('test');
end;

I have a error message  ErrorOriginalMethodNotFound in Event Subscription 
list Page: Event Subscriptions (9510)

So the Event Type is set to Business rather Integration.

**Comment by thpeder** [comment]
The problem is that the casing of the name doesn't match so it doesn't find the event.
If you remove the name of the event completely and invoke Intellisense (ctrl + space) then it will suggest the events with the correct casing.

Like this:
Note: The ^ symbol is just for indicating where you place the cursor when invoking intellisense. It should not go into the code.
[EventSubscriber(ObjectType::Codeunit, 40, ^, '', false, false)]

**Comment by geraldbeaulieu877** [comment]
Effectively it's my mistake, I write the event rather use the intellisense.  Thanks.
