### ISSUE TITLE
AL0444 and AL0445 compile errors on Reports

### ISSUE THREAD

**Issue by gudrunleos** [Microsoft/AL#1351]
Since yesterdays upgrade (Image navdocker.azurecr.io/dynamics-nav:11.0.19943.0-finus AL compiler 0.14.16095) we are getting compile errors on Reports.
Those are 

> error AL0444:  Malformed Word report layout at location 'Report\Layout\Mywordlayoutdocument.docx'.

and

> error AL0445: The file 'Report\Layout\Mywordlayoutdocument.docx' is opened in another application. Close the application to be able to compile.

The Report .al file has properties:
report 50101 MyReport
{
	DefaultLayout=Word;
	WordMergeDataItem=HeadingDataItem;
	WordLayout='Report\Layout\MyWordLayoutDocument.docx';
...

Any suggestions?

**Comment by DominikDitoIvosevic** [comment]
Hi @gudrunleos . We have introduced a new feature where you can use the AL extension to synchronize your word and rdlc layouts with the AL report data sets. This feature is very new and while we have tested it against our own report layouts, it is a fact that the rich ecosystem of our partners will have many more reports and will have hit some new edge cases.

The AL444 error is when there is something wrong with the Word file which is being used and AL445 error is for when you have opened the Word file in Microsoft Office Word while trying to build the extension.
There is a known issue for AL445 which has been fixed in the build 19995 (you have 19943). Please try obtaining a newer build and retry. I'm afraid you will not be able to publish a report on the version you are at.

I will add more details to the error message so that it is possible to easier find the issue with the files.
Could you maybe post here the report and the accompanying word file so that we could debug?

**Comment by MikeGlue** [comment]
Can't seem to find a newer build available. Can we get one published via Collaborate so that we can publish our extensions with reports?

**Comment by gudrunleos** [comment]
On the latest build this looks a bit better.  Most of my reports are compiling and building without an error. 
Two reports needed some work though:

- The first one I compiled without the wordlayout property in the .al code and imported the layout in the client, allowing client to update it. Ran it there - another update needed, then it ran ok.  From there I could export the layout and reactivate the wordlayout property of the report.

- The other one does not compile at all with the wordlayout property but I can import the layout in the clinent (no upgrade needed) and run it there without problems but I'm not able to set the wordlayout property again.

I hope this helps, attached is the report that does not compile (error AL0444: Malformed Word report layout at location 'Report\Layout\70014010-InvoiceSlipIS.docx'.) and the necessary files.

Guðrún.

[reportstuff.zip](https://github.com/Microsoft/AL/files/1614972/reportstuff.zip)

**Comment by DominikDitoIvosevic** [comment]
Hi @gudrunleos .
I have identified the issue and it should be fixed soon. The issue was happening when having dataitems which didn't have any dataitems or columns inside of them.
A workaround for now is to have something like this `TempColumn` just to avoid the crash before the fix is in.


        dataitem(AssemblyLine;"Posted Assembly Line")
        {
          DataItemTableView=SORTING("Document No.","Line No.");
          UseTemporary=true;

          column(TempColumn;'tempstring') {
            
          }
        }

**Comment by gudrunleos** [comment]
hi.
I added dummy columns to 2 data Items in this report and that didn't change anything for me - still got the compile error.

To complete this part of my V1->V2 migration I created a new .docx layout for the report. 
g.

**Comment by DominikDitoIvosevic** [comment]
I'm not sure I completely understand your mitigation. Are you saying that for the report which you pasted here, you deleted the docx and generated a new one and didn't even need to add the columns to the "AssemblyLine" and "ShipmentLine" data items and it builds for you without issues (note that you need to build twice to be sure)?
Because there definitely is an issue which is being fixed where if you have data items without columns inside, we get an issue during building.

**Comment by gudrunleos** [comment]
What I did was this.
Remove the Wordlayout definition of the .al file and deploy the extension.
Us the client to create a new word layout for the report via custom report layouts, and export the .docx
Edit the .docx to match the old one (mostly with copy-paste).
Use the new .docx to replace the old one in the layout folder
Reinsert the Wordlayout definition and deploy again.
Attached is the new layout document. Feel free to do any experiments on it :)
[70014010-InvoiceSlipIS.zip](https://github.com/Microsoft/AL/files/1622235/70014010-InvoiceSlipIS.zip)

**Comment by gudrunleos** [comment]
I've just upgraded my docker image to build 20186 (finus).

After that I can not run any of my four invoice / Cr. memo document reports, note that the first deployment of the extension in the new build results in modified Word layout .docx files.

This is the same report as above plus three more but this time my workaround does not work.

> The SourceExpr for report control 'InvoiceDiscountAmount_VATAmountLine' is not valid. The following error occurred: The supplied field number '32' cannot be found in the 'Tax Amount Line' table.

my best,
Guðrún.

**Comment by gudrunleos** [comment]
closing this since the initial problem is solved - new issue #1474 needs resolution.
