### ISSUE TITLE
Labels in reports cannot be entered in multilanguage

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#1355]
As I see it, there are no way to enter a label in a report in multi language.

![image](https://user-images.githubusercontent.com/33752561/34648699-0f75465e-f39f-11e7-83fa-ad8fb90dcfef.png)

Am I missing sometining?

/Peik

**Comment by srenders** [comment]
Hi Peik,

Very good question. I had to figure it out too and came to this solution:
![labels](https://user-images.githubusercontent.com/17511254/34651865-b8407ace-f3d6-11e7-8fba-28a320cb3399.png)

/Steven

**Comment by peikba** [comment]
Thanks Steven,

 

That makes sense 😊

 

That is not the way the txt2al.exe translates it.

 

Med venlig hilsen / Best Regards

Peik Bech-Andersen
Senior Consultant, Lead MCT
Mobile: +45 28 92 91 11

**Comment by DominikDitoIvosevic** [comment]
Hi @peikba and @srenders .
It is true that txt2al does not translate it to the other syntax if you only had one language because we are moving away from being able to use multiple languages in source code. This has been discussed in other issues as well. For now you can use the multilanguage syntax but we encourage you to start using xliff translation files for managing multiple translations.

**Comment by DominikDitoIvosevic** [comment]
I think this issue is resolved. If you have more issues or questions, please open a new issue
