### ISSUE TITLE
XLIFF and InstructionalTextML

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#1386]
The XLIFF documentation (https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-work-with-translation-files) talks about replacing CaptionML and ToolTipML with XLIFF text (and indicates that the NAV object should only use Caption and ToolTip). However, InstructionalTextML does not have a companion InstructionalText property. How should this be handled? You can find this property on a page group, and it is used in wizards natively.

**Comment by DominikDitoIvosevic** [comment]
@jcooper01 are you sure there is no "InstructionalText" counterpart? I can see it both in pages, request pages and page groups.
Could you please paste code where you can get InstructionalTextML working but InstructionalText is reporting an error?

**Comment by jcooper01** [comment]
Sorry - I should have been more clear. I meant in the C/AL development environment. That's where we develop and then use Txt2AL to generate the AL for each release (as we support multiple NAV versions in addition to Tenerife).
![image](https://user-images.githubusercontent.com/19348055/34774462-681c721a-f5dd-11e7-827b-092f355f4a7a.png)

**Comment by DominikDitoIvosevic** [comment]
An important thing to note here is that the "Caption" property in CSIDE is not the same "Caption" property in AL extension. There is no way to use these new label properties in CSIDE since CSIDE can't generate xliff files and hence there is no use for them. If you try using txt2al to convert from CSIDE then your CaptionML property will get converted to Caption if it only has 1 language specified and CaptionML if it has multiple languages specified. 

I understand this might create some confusion at first but we didn't want to introduce new names for these properties in AL. 

There is a plan to add to txt2al to export CaptionML properties with multiple languages to label syntax and generate xliff files for other languages but we don't have a timeline which we can share right now.

**Comment by DominikDitoIvosevic** [comment]
I'm not sure but I think this issue is resolved. If you have more questions please open a new issue
