### ISSUE TITLE
No Intellisense in TableExtension OnAfterValidate

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#1410]
It seems that intellisense does not understand this construction. (Which is an awesome construction)

![image](https://user-images.githubusercontent.com/7205122/34867302-7c730654-f734-11e7-82a0-7804d3831d97.png)

**Comment by markbrummel** [comment]
Publishing gives this error. But the (pre)compiler sais there are no "Problems"

![image](https://user-images.githubusercontent.com/7205122/34868601-310815b0-f739-11e7-8e20-2ca7a6c58323.png)

**Comment by markbrummel** [comment]
Hi, it turns out it was a symbol issue. I regenerated my symbols and the stuff works.

I can't help having the feeling that the whole "generate your own symbols" thing is still a bit wobbly..

**Comment by kalberes** [comment]
What do you mean? Have you worked in C/SIDE and side by side VsCode?
If you worked in C/SIDE have you started C/SIDE that it generates symbols automatically and thus what you only need is download them?

**Comment by markbrummel** [comment]
It's an error logging issue. Sometimes stuff works, and then it does not. It's not reliable and you spend a lot of time running SQL Server Profiler to see what it is doing and where it goes wrong.

There is no good documentation on what happens in the dark caves. There is a step that happens when you start up C/Side with the parameter but there is also something that happens when you download the symbols.

On top of that we have a database without one programming license that covers all objects. This is a legacy problem that I will try to solve asap.

It would be cool if someone from Microsoft would write a very detailed blog about symbols and what happens when you execute certain optoins.

**Comment by kalberes** [comment]
I can tell you briefly.  The command generate symbol reference is similar to the UI flag, it just does it for all.
Happy path scenario:
a. From your changed application object in C/SIDE we generate symbol references when you compile the object. These are JSON fragments and are stored in a new field in the object metadata table. Generating symbols require that your code is in a compilable state, since internally in C/SIDE we create a state of the application object before creating the JSON fragment  that resembles your output of the export format with the  ExportToNewSyntax flag.
b. The server if started with the option EnableSymbolLoadingAtServerStartup is creating an aggregated cache that is a projection of the aggregated symbol reference JSON file that you would download. The server is also listening to changes on the object metadata table. If it is a change for updating the aggregated symbol reference cache it will do it.
c. When you download symbols this aggregated projection is mapped into a downloadable, versioned package format and stored in your alpackages folder.
When this happens the vscode language server (the AL extension) code will trigger an update on the current workspace folder's project references. This means that the compiler should be able to bind(resolve) the new symbols you have added in C/SIDE.

**Comment by markbrummel** [comment]
Thanks, this helps a bit. I will look what is in the new field in the metadata table to see if I can do some troubleshooting.

When for whatever reason the symbols are not generated it's super hard to figure out what went wrong.

**Comment by kalberes** [comment]
If you use the command then the errors are in an error file. And as you know the C/SIDE's command's way the standard in/out is returned immediately thus you have to wait and see the navcommandresult.txt, unless you specified your own log file.
In the UI it should be part of the compilation message. Worst case it could be a cryptic one, like Internal Error x in Module y. Even though I have not yet encountered a scenario that would do that. Being C/SIDE I cannot 100% claim that it would not hit it.  But this is not the first time you would see an error like this. Isn't it?
