### ISSUE TITLE
Cannot Add the same 'Control' multiple times

### ISSUE THREAD

**Issue by yukonn** [Microsoft/AL#1430]
I got "Cannot Add the same 'Control' multiple times" when I trying to test AL. Specially "Name" is same but usage is different. I am not sure is it limitation or bug?

![cann](https://user-images.githubusercontent.com/14740258/35037163-a580fc50-fbb1-11e7-9f48-f467c930807a.png)

**Comment by qutreson** [comment]
Names should be unique by design. If we were allowing having the same names and an other page extension wanted to insert something after "Address Map", we wouldn't know if we should refer to the field or the group. Here, you should just rename one of them and use the caption property to have the right display.

**Comment by qutreson** [comment]
Probably the error message is a bit misleading here since, the problem is not that you are adding the same control multiple times (since they are obviously different), but that the two controls have the same name. We will improve the error message.

**Comment by yukonn** [comment]
Thanks for detail explanation. Please improve the error message.
