### ISSUE TITLE
HttpClient and TLS compatibility

### ISSUE THREAD

**Issue by IgorPcelnikov** [Microsoft/AL#147]
Hello,
how can we define TLS1.2 (force) when using HttpClient request (new REST API)?
In .NET we can call static function SecurityPointManager.SecurityProtocol(3072) to switch from standard 1.0 to 1.2 (3072 is 1.2).

Thanks

**Comment by atoader** [comment]
There is currently no way of enforcing which Security Protocol the HttpClient uses.

**Comment by IgorPcelnikov** [comment]
Hello,
yes, this is necessary for solution to work. Any date on adding this?

Igor

**Comment by atoader** [comment]
Hi Igor! Sorry for the delay. I've been trying to find a workaround for you until we get to work on this. At the moment, we are working very hard on polishing the experience and fixing compiler issues. It might take a while until we manage to implement this. 

I suggest creating a separate service (maybe an Azure Function) where you can have full access to the SecurityPointManager, set the version you need, do any processing that requires .NET and return the final result to your extension.

**Comment by ajkauffmann** [comment]
What's the current status of this issue? 

According to the documentation, TLS1.2 is the default security level in .Net 4.6. Does this mean you are currently using .Net 4.5?

Changing to TLS1.2 in .Net 4.5 is just a matter of calling 
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

It would really be appreciated if this option can be added quickly, it would save a lot of work because we can then implement integration directly with AL code instead of creating Azure functions.
