### ISSUE TITLE
New Integration Event in Codeunit 12

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/AL#1484]
Raised from here in codeunit 12 (Line 4208)
![event-codeunit12](https://user-images.githubusercontent.com/22604702/35292101-625fe200-0067-11e8-8915-6e100cfd6994.png)

**Comment by SergioKelly** [comment]
Hi Stanislaw,
We cannot find the event. Do you know what version of NAV did you include it?

![nav version](https://user-images.githubusercontent.com/22604702/38515327-65ba46b4-3c23-11e8-9b1e-29492e962c92.png)

**Comment by StanislawStempin** [comment]
It was included in the February 2018 Developer Preview release which means that it is currently available in Business Central. To get this event for NAV 2018 you can either log a support request or add it manually (because you have the guarantee that the event will be present in the latest official codebase).
Please see the FAQ section about NAV 2018 issues.
