### ISSUE TITLE
New Integration Event codeunit 5802

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/AL#1485]
Integration Event codeunit 5802 line No. 186
![event-codeunit 5802](https://user-images.githubusercontent.com/22604702/35294891-93a065a8-006f-11e8-8241-0349dc3dfe81.png)

**Comment by SergioKelly** [comment]
Hi Stanislaw,
 We cannot find the event. Do you know what version of NAV did you include it?

![nav version](https://user-images.githubusercontent.com/22604702/38515437-cab7eca6-3c23-11e8-903b-897c71a4dcd2.png)

**Comment by StanislawStempin** [comment]
It was included in the February 2018 Developer Preview release which means that it is currently available in Business Central. To get this event for NAV 2018 you can either log a support request or add it manually (because you have the guarantee that the event will be present in the latest official codebase).
Please see the FAQ section about NAV 2018 issues.
