### ISSUE TITLE
Beter support for creating subscribers

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/AL#149]
Please point us to a different/better way if there is one... Else please consider better IntelliSense: 

At the moment when we want to subscribe to an event we need to do everything manually:
- First You need to know the names of all publishers a given object may have. There should at least be IntelliSense here to support the developer  
- Then when You have selected a publisher You will have to know which parameters the publisher provides. Again help is mandatory. Right now we have to wirite a subscriber in the old Dev to then retype the stuff to the new Dev.

**Comment by StanislawStempin** [comment]
You should be able to see a full list of publishers for a given object using Intellisense. 
For the second issue we are planning to add a 'code action' to provide a default subscriber signature with all valid parameters.

**Comment by DanielGoehler** [comment]
Ctrl+Space seams not working in the October Update.

**Comment by DanielGoehler** [comment]
Creating an EventSubscriber seems pretty rough right now. It would be nice to have some IntelliSence on the Object Id, or even better the option to use the Object Name, which would be more consistence with the rest of the AL-Syntax.

**Comment by MikeGlue** [comment]
I have used the following syntax with success instead of using the objects IDs, but I do wish that there was intellisense on the event names.

database::"Sales Header"
page::"Customer Card"

**Comment by StanislawStempin** [comment]
Could you please log a new issue for the specific Intellisense bug? Can you provide a detailed repro? Checking on the latest build we do get event name suggestions:
![capture](https://user-images.githubusercontent.com/23653165/31652936-2496d26e-b321-11e7-8859-4b2cc9fecbcb.PNG)

**Comment by jaspreet997** [comment]
For now, Do we need to manually enter procedure parameters for a event subscriber? I cannot find any documentation for this

**Comment by DanielGoehler** [comment]
@StanislawStempin: I started with the *teventsub* Template, which currently has no procedure, because as @jaspreet997 pointed out, I'm also don't know the procedure parameters from that event. In that case the IntelliSense seems not to work.

It would be nice and more intuitive to have a more guided process here. E.g. the way in the old development environment is pretty good.

New case for that?

**Comment by StanislawStempin** [comment]
Thanks. No need for a new case, better support for creating subscribers is tracked by this one and we are aware that this is an important scenario. We will provide updates on this issue once we are closer to implementing the solution.

**Comment by Koubek** [comment]
Intellisense works correctly when **Object ID** is being entered explicitly:
![image](https://user-images.githubusercontent.com/24265973/32410754-8b92f5e6-c1c8-11e7-9435-df4334f4a8d7.png)

Intellisense does not work when object ID is being transformed, eg: `Database::"Table Name`:
![image](https://user-images.githubusercontent.com/24265973/32410766-cb21a2de-c1c8-11e7-89fe-afb6fa7b96c2.png)

The first approach is wrong, it goes against all NAV best practices.

**Comment by DanielGoehler** [comment]
Hi @StanislawStempin,

in **Februar Update** if you using the **teventsub**-Template, you still have to remove the Apostrophes (') of **EventName** to get the IntelliSense List of published Events. Furthermore it would be nice to be able to see the Publisher Event Definition or even better to be able to add the parameters to the procedure below.

**Comment by StanislawStempin** [comment]
For now, we will see what we can do to improve the snippet. 
The overall usability improvement of subscribing to events is still on our backlog.

**Comment by qutreson** [comment]
We did some work on improving the snippets and Intellisense around event subscribers (for both the attribute arguments and the method parameters - see examples below). It is now working for trigger events, integration and business events. In case of business and integration events, the suggestion of the method parameters is made based on the attributes of the event publisher in order to know if the global variables and/or the sender should also be suggested. 

Here is what it looks like to subscribe to an integration event when using the snippets:
![eventsubscriberintellisensedemo](https://user-images.githubusercontent.com/31541422/36895891-dd413d68-1e10-11e8-8514-15401d9008a7.gif)

Here is what it looks when writing the event subscriber from scratch:
![eventsubscriberintellisensedemowithoutsnippet](https://user-images.githubusercontent.com/31541422/36895930-fd00d118-1e10-11e8-8eca-3047db6770d9.gif)

Also, after our changes, the problem of the quotes does not seem to reproduce anymore.
![eventsubscribersnippetquotes](https://user-images.githubusercontent.com/31541422/36895935-0331caec-1e11-11e8-9f91-7457855efad2.gif)

I hope this helps!
