### ISSUE TITLE
How to remove a field from a V2 extension

### ISSUE THREAD

**Issue by kvaldik** [microsoft/AL#1499]
I have a nice extension deployed and running. Now I remove a field from a table in the extension and deploy it again through F5 in VS Code. The schemaUpdateMode is set to Synchronize and I get the following error:

`Table 70014003 :: Unsupported field change. Field:MovedToDrawerEntry; Change:Remove`

Can I somehow specify in the upgrade code that this field is to be removed? Couldn't find anything about it in the [documentation](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-upgrading-extensions).

A related question, when the schemaUpdateMode is set to Synchronize, is the same logic run as if I would publish, install and run the NAVAppDataUpgrade commands in powershell?

**Comment by thpeder** [comment]
Hi @kvaldik,

When you publish from VSCode with schemaUpdateMode Synchronize then it does not run your upgrade code.

If you don't care about the data entered into your new table(extension)s then you can change it to recreate and publish again.
If you do want to keep your data, then you need to use the Powershell command for doing an upgrade as specified in the documentation you linked to.

**Comment by kvaldik** [comment]
Hi @thpeder.

Thanks for your quick response. VS Code not running my upgrade code does make since I'm usually pushing the same version every single time. Although it might be a nice feature to be able to have the upgrade code run as well, but that is another topic.

My main question is still how to remove a field from a V2 extension. That is, what code do I put in my upgrade code to inform the system that this field should indeed be removed.

Even if use the powershell commands I still get the same error when I try to sync the new version of my app (with the removed field).

**Comment by HunterFeltman-MSFT** [comment]
Currently, there is no 'deprecated schema' story for extensions, meaning that when you are _upgrading_ from one extension version to the next, you are not allowed to make any breaking SQL schema changes. (Note - we don't enforce breaking code/page/etc changes, just tables/tableextensions)

In production, this currently means that once you have published/sync/installed an extension onto a service, then all of the tables and fields therein must be forever backwards compatible for that service and any tenants/tenant DB that are using the extension.

The only way to introduce actual breaking changes, currently, is to completely remove ALL VERSIONS of an extension and all associated schema elements from a service (i.e. drop all of the data). Obviously this is usually not something you want to do for extensions in production, and thus the backwards compat restriction mentioned prior.

This hard data dump, however, is not a problem during development of your initial version of an extension as you determine what you want from a schema perspective. 

To reiterate thpeder's instructions 
To do this in VSCode: you need to specify the: "schemaUpdateMode" : "Recreate" in the launch.json file of your project. The 'recreate' mode was the original mode of operation for the ALExtension and will the do the said 'complete removal and drop of schema' when you use the F5/deploy scenario.
 
To do this from powershell: you first need to use the Sync-NavApp cmdlet and use the 'Clean' mode 

`Sync-NavApp -ServerInstance <instance name> -Path <path to .app> -Tenant <tenant> -Mode Clean ` 

Again, this mode will go through ALL VERSIONS of the provided extension specified from the database of the targeted tenant and remove the schema elements that came from the extension (i.e. drop all of the data). This leaves your tenant in a 'clean' state where this is no schema 'history' to consider, so any version you sync afterwards is considered 'new'.

So to briefly recap -- You 'can' remove your field but it will be at the cost of any/all data in your extension. This is fine for initial development scenarios, but probably not ok in production and thus you'll have to work out a 'backwards compatibility' story for your schema elements. 

As to the question about running upgrade code, the restriction in the server today is that upgrade only occurs when moving from an old version to a new one. There is no path to run upgrade code without a version change. You can then write upgrade code that moves data from the 'old' pseudo-deprecated field to a new one, you just have to live the old field 'sticking around'. (For now at least)

**Comment by kvaldik** [comment]
Hi @HunterFeltman-MSFT.

Thanks for an extensive answer! Our app is exclusively on D365 so completely removing all app versions is out of the question for us. From now on we have to be backwards compatible. Which is ok, I guess, but I hope the ability to perform breaking SQL schema changes will be added. Is that anywhere on the roadmap?

We have removed fields/tables in the past when developing in V1 without any troubles. Some tables were only used as temporary and we no longer needed them.

In any case, when we figure out that a field or table is no longer required it kind of sucks to have to keep it in our solution. Making the code dirtier than it needs to be.

**Comment by DanielGoehler** [comment]
I think @kvaldik is right. The more changes you made to you solution the messier you solution gets...

**Comment by HunterFeltman-MSFT** [comment]
Right, it is a little unfortunate for new code at the moment. 
This is a consequence of the 'SharedSchema' mode of database layout whereby multiple tenants (which could technically be using different 'versions' of a given extension) can exist on the same database. This puts a hard 'lower limit' the level of backwards compatibility for a given database (must be compatible with the lowest version synchronized).

A true deprecation story is most definitely in our backlog and 'on the roadmap'.

**Comment by pjanfred** [comment]
Are there any workarounds to force the field deletion? - with PowerShell e.g. 

I would like to keep the other data of the app.

**Comment by reiniroosh** [comment]
This is not really very clear from the documentation:
"..if a field is removed then the table data cannot be synchronized and you have to ... **write an upgrade codeunit**"
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing

However, it seems like regardless if you write an upgrade codeunit or not, you will have recreate the data if a field is removed.

**Comment by gregoral** [comment]
Field removal from a tableextension is very poorly documented and most probably not working.
The documentation suggests an upgrade code unit, but does not clearly point out how to trigger the upgrade process.
None of the MS exaple extensions ( PayPal, MSWallet, SalesAndInventoryForecast, ...) show how this should be done.
Ms is more or less forcing parters to move to extensions, so I guess you should at the very least document in detail how are we supposed to hadle this scenarios as well.

**Comment by ThomasBrodkorb** [comment]
We found a solution (hack) to remove fields from extensions (2.0) for NAV2018 and BC on Premise:
This hack is not guaranteed to work under all circumstances and should be USED WITH CARE:

Following situation in a customization extension:

You created some fields in one table (lets say in Customer).
Then you create some additional fields in another table (let's say Contact).
You did not consider that creating a Customer from a Contact calls a TRANSFERFIELDS, which crashes terribly, because the field numbers and types don't match.

Now you seem to be screwed as removing fields is not supported for "synchronize" action.
Your extension contains hundreds of fields in dozens of tables and RECREATE is not an option, as long as you can avoid it.

All you need to do is to create a RapidStart Config Package (or an XMLport) which saves the data of your custom fields in that one table where you want to remove the field (if you need to keep any data from that table).

You open the SQL Server Management studio and run the following script:


drop table [<COMPANYNAME>$<TABLENAME>$<APPID>]
delete from [dbo].[$ndo$navappschemasnapshot] where appid = '<APPID>' and tableid = <TABLEID>

after this ran, NAV/BC does not know anymore about that tableextension alltogether and will "create" it when publish next time.

Now reimport the data for the remaining fields

E voila!!!

There is an enhancement to these procedures which lets you keep the data without RapidStart or XmlPort:

Instead of dropping the table [<COMPANYNAME>$<TABLENAME>$<APPID>], rename it to something like
[<COMPANYNAME>$<TABLENAME>$<APPID>.Save]
Do the same for all keys inside the table:
[<COMPANYNAME>$<TABLENAME>$<APPID>$0] to [<COMPANYNAME>$<TABLENAME>$<APPID>$0.Save]
still run the 

delete from [dbo].[$ndo$navappschemasnapshot] where appid = '<APPID>' and tableid = <TABLEID>

query

After this, publish your new package which contains that table extension with less fields or different field IDs.

Now you have two different tables in the database, the one you saved and the new one created.

Delete the just created new table [<COMPANYNAME>$<TABLENAME>$<APPID>]
Rename the SAVE table back:
[<COMPANYNAME>$<TABLENAME>$<APPID>.Save] to [<COMPANYNAME>$<TABLENAME>$<APPID>]
Rename the keys back.

When you just had to change field IDs, you are now done. If you have removed fields from the table extension, remove the same field from the table in SQL Server as well.

Happy hacking!!!!

**Comment by HunterFeltman-MSFT** [comment]
As @ThomasBrodkorb said, the solution that is offered above to 'workaround' the restriction of backwards compatibility in V2 extensions (i.e. no field removal allowed between versions) should be used with EXTREME care. Adjusting the contents of tables managed by the service platform such as [$ndo$navappschemasnapshot] is not recommended as doing such can put things like extensions into an unrecoverable state.

As an alternative to this method above, you could also perform what I call 'The Dependency Hop'.
In this case, you create a 2nd extension (let's call it DepHop v1) as form of 'temporary storage' for all of the data that you wish to save from your original extension. 
You make the original extension a dependency of DepHop v1 and, upon install, port over all of the aforementioned data into DepHop's tables.

You create a new version of DepHop that looks much the same as v1, but remove the dependency on the original extension and upgrade DepHop v1 to DepHop v2.

You are now free to remove DepHop v1 + the original extension and can sync -mode clean the original one as well since all of the data is stored in DepHop.

Now you can put on your 'new' version of the original extension without the fields you wished to remove. At this point you can either put a dependency on DepHop v2 from this new version of the original and port the data back into your tables, or you could create DepHop v3 (with a dependency on the new version of the original extension) and port the data back in upgrade code.

Visual/Steps:
Original - ExtOrig v1 (we want to remove schema elements from here)
1. ExtOrig v1 <-- DepHop v1 (Create DepHop v1 with dependency and copy over data you care about)
2. Upgrade to DepHop v2 (No dependency on ExtOrig v1)
3. Uninstall/Sync Clean/Unpublish ExtOrig v1
4. Publish/Sync/Install ExtOrig v2 (now with fewer fields!)
5. ExtOrig v2 <-- DepHop v3 (Create DepHop v3 with dependency on ExtOrig v2 and port data back)


Obviously this 'workaround' has a few more gymnastics to run through but it avoids the possibility of making manual SQL query mistakes. You can cut a few steps out if you are ok with using DepHop v2 as a replacement for you original extension (there will be no need to port data 'back').

I should note that this solution will also work in the SaaS/Cloud Business Central offering, but you are restricted to the 'shortcut' mentioned above as you are not allowed to perform recreate/clean operations in those scenarios. (I.e. DepHop v2 has to be used as your new extension)

**Comment by esbenk** [comment]
This is support from 2019 Spring release as documented [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing)

**Comment by kvaldik** [comment]
> This is support from 2019 Spring release as documented [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing)

Actually @esbenk, as much as I love the new `ForceSync schemaUpdateMode` it does not apply to deployed extensions, such as the ones in App Store. But as @HunterFeltman-MSFT it is on the backlog and road map so I'm confident you're still working on it even though this issue has been closed.

Just wanted to point out that you're not out of the woods yet :)

**Comment by esbenk** [comment]
You are absolutely right that this applies to development and on-premise. The solution for the cloud is to go through the ObsoleteState = Pending to Remove and upgrade into a new field in the case of a wrong type. 

This process is not changing for the SaaS offering any time soon. The deprecation story for the cloud and AppSource is about marking fields as Obsolete and may include transitioning data to other field in the case of a field type change.

**Comment by kvaldik** [comment]
I did not know about `ObsoleteState`, that is a great addition.

But now that I think about it I see that it might be difficult to allow us to, for example, remove a field or a table (in SaaS), since we'll always have the reference to it in the upgrade code. Difficult but not entirely impossible I guess. If we include the upgrade code all the way to something like version 1.99 and then in version 2.00 drop all of the upgrade code and deprecated fields / tables. It would then have to be a prerequisite to update to version 1.99 prior to updating to version 2.00, making sure all of the upgrade code is run.

As you say, this is something that isn't happening any time soon, but is it still on the table? Being a neat freak I would enjoy clearing out those unused fields and tables :)

**Comment by Mr-Pingu** [comment]
`Length of the table field name must not exceed 30 characters. Longer field names are prone to cause SQL errors. This warning will become an error in a future release.`


I have this, currently we deployed an extension with a table extension on Sales and Receivables setup. However this fieldname is too long, this is a warning so no trouble for now...

 But when it becomes an error how do I remove this field without losing data? This field is not important as we recreated the field with shorter name and transferred data ages ago to this new field. But still left with this field sitting there in code and no-way to remove it... 
Hope it won't become an error before deletion is resolved

**Comment by mirzaahsanbaig12** [comment]
I have deployed extension on business central cloud. I have the requirement to increase field size. I have done "schemaUpdateMode" : "Recreate" and publish the app. But when i upload the extension on production environment, error says unsupported field change. I dont care about any data that exist in production. I need to increase field in size in production

**Comment by dnpb** [comment]
Increasing a field size should not be a breaking change. You should post the exact error.
