### ISSUE TITLE
VS code not seeing application objects?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#1506]
I hope someone can help me out. Trying to build the sample HelloWorld extension per the Microsoft getting started documentation. 

This is what I did:

* Installed a local NAV 2018 NA instance from installation media
* Opened the Microsoft Dynamics NAV Server and under "development", I enabled "developer service enpoint" and "enable loading application symbol references at server startup. Port 7049 - restarted the NAV server
* I installed VS Code
* Installed "AL Language" VS code addin (0.11.14434)
* went back to VS Code and created a new AL project via ALT-A + ALT-L
* modified the launch.json file so it knows to download the objects from a local instance (server: http://localhost, serverInstance: DynamicsNAV110, authentication: Windows, port 7049)
* exit VS code and re-open the AL project that I created
* VS code prompts me to download the symbols. I download them. downloaded contents in .alpackages is Microsoft_Application_11.0.19394.0.app and Microsoft_System_11.0.12925.0.app

the HelloWorld.al that VS Code created is a demo page extension that extends "Customer List", "Customer List" is red-underlined (suggesting that VS code isn't finding the Customer List object.

ctrl-shift-b to build the extension, and VS Code is reporting back this error:

The target Page "Customer List" for the extension object is not found

VS Code intellisense appears to see some objects but not others (intellisence works for things like "NAV App" table, but application objects such as "Customer" table, "Customer List" page aren't found). 

It seems that VS code is finding the system objects but not the application ones. 

What am I doing wrong?

Restarting VS code doesn't help

The build of NAV 2018 I'm using is 11.0.19394

**Comment by thpeder** [comment]
Hi @CanuckNav74,

We recommend that instead of installing the version from the marketplace you instead install the .vsix you will find on the installation media since you are running Nav 2018 and not against the sandbox or any of the other developer previews. 
Make sure you only have one version of the AL language extension installed in VSCode. 
If ever in doubt about which version to use see our [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#which-version-of-the-al-language-extension-should-i-use)

Inside VSCode you will find a folder named .alpackage this is were we store the symbol files which tells the compiler in VSCode which objects are in the database. 
My guess would be that if you take a look at the Microsoft_Application_11.0.19394.0.app in that folder then the file size is only a few kilobytes, which would indicate it doesn't contain symbol information for all the objects.

You can try disable "enable loading application symbol references at server startup", restart the server and in VSCode invoke the command "AL: Download Symbols" 
but I suspect that you might need to recompile your symbol file by following the steps in here [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)

If non of this works then you should contact support instead, as this Github repository is meant for questions about the developer previews.

**Comment by CanuckNav74** [comment]
Thank you for the helpful feedback @thpeder !

I uninstalled the "AL Language" extention that was previously installed from the marketplace and in it's place, installed the ALLanguage.vsix found in the "ModernDev\program files\Microsoft Dynamics NAV\110\Modern Development Environment" folder on the install media. Upon re-opening my AL Project folder, it no longer complained of unknown dependencies.

I didn't need to disable "enable loading application symbol references at server startup" via the NAV Server admin tool, nor did I need to recompile the symbol file (FYI the Microsoft_Application_11.0.19394.0.app that VS code downloaded previously was 3,852 KB in size). Is that a typical size for the NAV 2018 application symbols?

FYI - I was unable to install the vsix by double clicking on it (it resulted in an error). I had to install the vsix from command line (e.g. code --install-extension path_to_vsix).
