### ISSUE TITLE
AL: mitigating object ID and field ID # and name conflicts? best practices?

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#1514]
I noticed when creating a new AL project in VS code, the helloworld.al file that VS code generates contains the following warning comments at the top of the file:

`// Remember that object names and IDs should be unique across all extensions.`

Say a customer installs two extensions - one from from vendor A and another from vendor B. They have no relation to eachother. What if there is a conflict in the names and numbers between these extensions? Does that mean that the extension from vendor B won't install?

It's entirely possible for two completely unrelated extensions to have object name and number conflicts.

How can this risk be mitigated? Seems that each extension ISV should have their own object ID range reseved to them (if so, what range would these numbers reside in and how does one go about securing their own reserved object range?) and furthermore, should any object names and field names in an extension have an ISV prefix? e.g. if the name of the ISV is "CONTOSO" would it not be a good practice to prefix any object and field names with that prefix?

By default, the "idRange" in the AL project's app.json is 50100 to 50149? Is this even sufficient?

e.g. Table name **"Foo"** becomes **"CONSOSO Foo"** (table caption can still be "Foo")

**Comment by Gallimathias** [comment]
Currently AL works according to the principle last man standing. So yes, there are ID and name conflicts and the result is a crash.

I'll give you a few issues here where the topic has already been discussed and suggestions for improvement have been made.

#154 #82 #652 #365 

Yes, actually own number ranges and complex names are the most practicable way. In the long term, however, I see it as only a workaround.

**Comment by fvet** [comment]
Following the AppSource recommendations, I've added our prefix to all of our custom fields in NAV tables. I noticed few things:

- The prefix uses 4 extra charachters (3 + space), meaning we need to be more inventive and thus often have abbreviated / cryptic field names. Are there any plans to enlarge the maximum field name length?
- When ugrading in the past, we often got issues because NAV added new standard fields (e.g. GLN), triggering us to remove customizations and use standard NAV fields instead (which is good). Using the prefix approach, it will be more difficult to be automatically alerted on possible new duplicate field usages (since name conflicts would no longer occur). Example : in case NAV would add Ship-to Address.'GLN' field, it would not conflict with our customized 'XXX GLN' field. 
- For the IntelliSense, you need to type the prefix ... (unless you use the suffix approach)

**Comment by dennisfrostlander** [comment]
@CanuckNav74 Yes, the best practice to avoid conflicts is to use dedicated ID range for object IDs and prefixes for object names.
@fvet I agree that that this is not ideal, however this is how the Nav platform and the licensing around it is designed. By the way, intellisense is triggered on any substring of an object name, so you don't have to start typing with a prefix ;)
