### ISSUE TITLE
Translation File (.xlf) file updating when we are creating the package.

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#1531]
Hi,

We have changed the app.json file to create a .xlf file for translations when we have done Ctrl + Shift + B then a file is created for translations.

Now we have updated the file with translations in target and again done Ctrl + Shift +B to include the translations but now it is recreating the file and the changes we have done for the target are gone.

Please suggest us how we can include our translations in .app file ?

Thanks & Regards
Varun Reddy

**Comment by Gallimathias** [comment]
The xliff file will be created every time you build a new build and will be automatically integrated into the. app file.

In order to handle the xliff files correctly, it is not recommended to edit the generated file but to use it as a template. Most tools work with it. Copy the file for each language you want to target, name it accordingly and edit the copy, never edit the original.

See the translation from the [example](https://github.com/Microsoft/AL/tree/master/samples/GetAddressService/Translations) folder. The "Get Address Service. g. xlf" is the automatically generated file. The "de. xlf" the german translation and the "en. xlf" the english translation.

**Comment by Gallimathias** [comment]
Complementary: CU1 Nav2018 uses al version 0.12.15898

**Comment by bachii1010** [comment]
Hi Gallimathias,

Thanks for the Update.

This works.
