### ISSUE TITLE
Optimization of XLIFF format, wishes and suggestions from the point of view of translators

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1532]
I have to add a few wishes and suggestions about the XLIFF format used by Dynamics NAV, which is known to replace all ML texts.

1. the format itself is well suited for direct distribution to translation agencies. You don't have to convert all the texts into a readable format like before.

2. if you use several identical texts in an object, e. g. in text constants, now labels, these are not cumulated in XLIFF, but added individually. That doesn't make any sense. Why is a text added more than once when it is used several times? Couldn't this be simplified by saving only DISTINCT in this file?

3. naming: That is a very big criticism, which I have already heard several times. The created names simply don't make any sense. Even the specified object IDs do not exist. Much more, some other values seem to be inserted into the key. Why not use the real object names and IDs, or let the user decide for himself what the key of the text is. This would also make it possible to implement point 2.

4. creation only when creating packages. Why is there no separate menu option for creating the XLF file to update only it. So far, you always have to compile the complete extension.

5. preparation of new languages or revision. If you are working on an extension, there are always cases where new texts are added or existing changes occur. If you create a new file anyway. Couldn't you then prepare the existing other languages XLF files accordingly? So add new strings, and delete deleted ones? Then the files would all be synchronized. Otherwise, it is very difficult to work out the differences.

These are some of the points I took up and wanted to pass on. Maybe one or two points are also interesting for others here. Please send me further feedback.

**Comment by SirBETE** [comment]
To add to this:

6. There is no indication about the fieldtype. A boolean "Post" is a noun, and can have a different translation as the action "Post", which is a verb.

7.  When generating the translation file, one file is created for the ENU language with the original fieldnames. The captions aren't written. 
For example: a field called "SONo" can have a caption of "Sales Order No.". This caption should be included in the file as the new value.

8. With 7 in mind: Filled in captions for other (not-ENU) languages aren't automatically generated in a new file for that language. You would have to retranslate every caption, even when the majority was correctly translated in C/AL.

9. TooltipML, InstructionML, TextConst and labels aren't included in the translation file.
This is a known issue, and MS is working on it. (Just adding it for completion.)

**Comment by DominikDitoIvosevic** [comment]
I will try to address your issues:

1. I'm not sure what the question is
2. It's hard to say when using the same word in 2 places really is the identical thing. Maybe the translation changes depending on the context. That's why we keep things separate.
3. The generated hashes for the IDs are a result of some tools having issues when the ID is too long. We would have to have the ID contain 3 names to make sure the ID is unique: The name of the application object, name of the containing control and the name of the control itself. This, together with the types of each of the symbols can take up to about 400 characters which could cause issues.
4. Right now we try to have one action which updates everything. This makes sure nothing is stale when you build the extension. I understand you might want to update just the generated translation file or the report layout, this command is something we have on our backlog.
5. This is not as simple feature as it may seem. This would require us to consume all the existing xliff files in the extension and do the diffing and updating and removing. While we do not have the feature right now we do have it on our long term backlog.
6. This is a good suggestion. I might start adding the type of the field as well.
7. @SirBETE are you talking about table fields? I can see that once you specify a caption it is used in the translation file instead of the field name. Could you try using a newer version of the compiler and check if it's still happening and then open a separate issue for it?
8. We are misssing a feature to generate xliff files for other languages when doing txt2al. It requires a significant amount of effort so we haven't done it yet but we have it on the backlog.
9. ToolTipML, InstructionML, textcost and old report labels are not included in the xliff files. You need to change them to the new syntax to have them included in the xliff files. Please take a look at the https://docs.microsoft.com/en-gb/dynamics-nav/developer/devenv-work-with-translation-files to better understand.

**Comment by FSharpCSharp** [comment]
@DominikDitoIvosevic 
Thank you for the answers from the Microsoft team. I would like to make a few comments on certain points, because I do not quite understand the choices here:

To point 2:
If a string is used twice, the user should be able to decide for himself whether it is the same string. Couldn't it be made configurable? So far, we have not really had the problem that in different contexts, the same text had a different meaning. I just find it rather clumsy to say that this is not the case.

Point 3:
The given IDs don't make any sense at all! What does a translation agency care about the Method ID or another ID there? If at least the method name were used here. In everyday life, these strings are not to be used by anyone. 

To point 5:
I am well aware that this is not an easy requirement. But it would greatly simplify the handling of such files. And from the user's point of view, this makes sense. The previous solution is not really acceptable.

To point 8:
I believe that this would not be as bad as it is described. This would presuppose, however, that this would require optimizations in XLIFF format. With the IDs and fields you are currently only in your own way. Why is it not possible to reconsider the whole behaviour of this file?

From my point of view, the user-friendliness is a little bit too short here. Essential points that would make it easier for end users and developers are almost exclusively blocked in this case on the grounds that this would not be easy to implement. User friendliness is never easy to implement, but as it runs so far it is just a little bit 1. confusing and 2. not always useful. In addition, the XLF files created cannot be compared easily. This means that if I received a language from the translation agency, for example, I would have to compare the files in order to determine the differences.

**Comment by DominikDitoIvosevic** [comment]
@FSharpCSharp 

2. We are aware of advanced features of xliff format and have it on our backlog but we can't give you a timeline right now

3. As I said, the IDs were put there because of limitations of existing tooling. We are looking into placing the names there directly.

5. This is on our long term backlog and we are having discussions about the right approach

8. This story is not finished. There are many areas to improve. Right now we got up until here but we plan on adding more features.

I appreciate your questions as they give us more insight into what is important for our users. I hope that you understand that we still need to prioritize things and hence cannot give all features at once.

**Comment by vytjak** [comment]
Just to add a comment on point 2) Identical texts from objects added as separate entries:
 - in our experience, there are quite a few cases where the translation of the same text is different based on the context. So this is not a theoretical, but an actual real world scenario. Having identical texts as different entries in the translation file is the proper approach.
 - grouping the text instances which should be translated the same way is a nice idea, but maybe this should be handled by the translation tool and not NAV source. Such grouping would be, again, language dependent.

**Comment by FSharpCSharp** [comment]
@vytjak @DominikDitoIvosevic 
Of course, it can happen that a text has different meanings in different contexts. However, this has not yet been the case with all our modules. We checked our code base with the help of translation exports, and it turned out that we always had the same translations for our languages (in our case, German and English) for the same texts. We only had 2 - 3 cases in a module with about 1000 texts. For this reason, this is the exception rather than the rule for us. I cannot therefore judge how it is with other languages. That is why, by default, my proposal was to carry out a grouping and, in special cases, to make a distinction when there really is another meaning. But anyway, our translation agency beats the hell out of us with this XLIFF file because it is meaningless. You can't write a comment everywhere, because our office used to only go by the key. Various colleagues have already said the same thing to us, and I have been asked to pass on this criticism. It does not, therefore, represent my personal opinion, but rather summarises points of different views on this subject. Everyone sees the subject differently. Actually, I only wanted to start a discussion, because the status as it is so far anything but comfortable, be it for the developer or the full-time translator.

**Comment by LauraNicolas** [comment]
I have another suggestion: on-the-fly (or on-the-code) translations
It will help for those developers that do the translations themselves, and are not going to give it to an agency.

I just created a request here: https://github.com/Microsoft/AL/issues/1702

Salut!
Laura Nicolàs
