### ISSUE TITLE
Load order in the extension manager

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#154]
I thought it especially in terms of compatibility of several extensions and the basic application is useful to define a load order.

We already know the principle of various modification managers from computer games. When adding a new modification, I can specify in which order the computer game loads the modifications.

Without this extension, I have the fear that it would otherwise be forever or later, too often to collide between different extensions.

**Comment by StanislawStempin** [comment]
In case of extensions with dependencies the load order will be determined by the dependency graph. 

There can still be non-related extensions that will cause some conflicting effects like Page Field being moved by multiple extensions or the same property modified. We are still looking at the best approach to resolve these kinds of situations.

**Comment by pborring** [comment]
I am going to close this rather old feedback item. Load order is based on dependency graph, as well as currently on appId on the same level (but code should not assume this, as that can change in the future). There are currently no plans to allow for specifying a specific load order, which would also be difficult to manage, as there will surely be conflicting wishes across extensions. Thus this is not in the plans. Since the beginning of extensions, there has been the thought of a single "last-mile extension", which would a partner to override all other contributions in a specific tenant (as that extension would be guaranteed to load last). That approach would also allow for more properties to be extensible, as there is no race condition risk when loaded last. This has not yet been prioritized though. I propose opening an idea on http://aka.ms/bcideas to track this instead if desire to push for it.

**Comment by Gallimathias** [comment]
@pborring I find it sad when my ideas are simply closed because some of them have been added to the project over time.

However, I do not have the muse to transfer this to this other platform as I have left the Navision world in the meantime.

**Comment by pborring** [comment]
@Gallimathias I do not think we are closing all you items, and it seems fair to close items that we are not planning to address. Even if you have left the Navision world in the meantime, others might pursue this on Ideas though.
