### ISSUE TITLE
Drag and drop fields on pages, reports, xmlports and queries

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1542]
All the people I have showing the _modern development experience_ to are quite enthusiastic about it. However, the major drawback they all point at one way or another, is they cumbersomeness of adding a multitude of fields to pages, reports, xmlports and queries.
Were we had the field menu feature in C/SIDE, there is no comparable one in VSCode. Even the in-client designer does not allow to put more than one field at a time (unless there is a trick I do not know about).

So please, provide all those enthusiast with a feature like this.

**Comment by DennisReinecke** [comment]
I was thinking the same when I started to work with VSCode. I was putting to write an VSCode Extension  on my "To-Do-List". After some weeks working without i wouldn't use this functionality anymore, because its much faster to write the code with snippets and autocompletion.

**Comment by lvanvugt** [comment]
Dennis, for me the same, but having been a teacher/trainer for ages, I know each individual has other ways working, other preferences. And VSCode is advertised as a client supporting efficient and effective productivity for each user.
Having drag and drop will contribute to that for many of our peers.

**Comment by anzwdev** [comment]
Adding fields to pages with intellisense is fine, but I am missing page wizards as they allow me to build list and card prototypes quickly. For me it is a bit easier and faster to remove a few fields than to add most of them to an empty page. That's why I've created a context menu functions that create list and card pages form a table node in my "AL Code Outline" extension. 

![screen-pagewizard](https://user-images.githubusercontent.com/24944969/35735072-3ef87ad2-081b-11e8-8940-10caa3898bba.png)

It would be nice if al language server could expose some custom language protocol messages to get more detailed information about current document symbols. This would allow us to create commands that could quickly generate bigger fragments of code instead of typing them manually.

**Comment by ryancairnsy** [comment]
@anzwdev your extension is brilliant! I just discovered it and it will save me a LOT of time creating list pages quickly for large tables. Thanks!

**Comment by lvanvugt** [comment]
> 
> 
> @anzwdev your extension is brilliant! I just discovered it and it will save me a LOT of time creating list pages quickly for large tables. Thanks!

I fully agree.

**Comment by pborring** [comment]
This is an old, but still valid suggestion. Many have used partner VSC extension including above in the meantime. If you still feel for this, post a new entry this to our Ideas forum at https://aka.ms/bcideas to allow others to vote on it.
