### ISSUE TITLE
Expose PurchaseLine.UpdateVATOnLines()

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#1572]
In table 39 Purchase Line the function "UpdateVATOnLines" has the FunctionVisibility set to "Internal", which means we cannot do a documents Extension. Sales Line has the equivalent function set to external 

Please expose the UpdateVATOnLines()-Function from PurchaseLine.

**Comment by JesperSchulz** [comment]
The function was exposed in the middle of January. You should see the change in the most recent Docker image.

**Comment by JulianTillmann** [comment]
I'm sorry, but I pulled the last microsoft/dynamics-nav:2018-de docker Image yesterday and right now I'm getting 

![error](https://user-images.githubusercontent.com/35929603/36018850-86a23a6e-0d7d-11e8-9759-9f9bfaabab8e.png)

**Comment by JesperSchulz** [comment]
Sorry, got interrupted. Here's the reason why you don't see the change: We do not update NAV2018. NAV2018 only gets hotfixes and regulatory features through cumulative updates. If you want the latest and greatest code, you need to get the latest Tenerife build from Collaborate. There you will find this change.

**Comment by JulianTillmann** [comment]
So NAV2018 is a complete dead end? What are the cumulative updates for? 

How do I get "the latest Tenerife build from Collaborate"? What's the dockerpull-request there?

**Comment by JesperSchulz** [comment]
NAV2018 is not a "complete dead end", no. But it IS a released on-prem version and hence doesn't receive the latest non-crucial code improvements and new features. It only receives hotfixes and regulatory features, which has always been the process for our released versions. That is what the CUs are for.
Our SaaS solution does not build upon NAV2018, but rather "Tenerife", which is hence the version you should work on for extension development. Let me get back to you the question about how you get your hands on that version!

**Comment by freddydk** [comment]
This is not any different from earlier releases.
After shipping NAV 2017, we have shipped monthly Cummulative updates for NAV 2017 with bug fixes.
Same thing with NAV 2018, we do not want to backport fixes, which might disrupt customers who will be using latest CUs.
In order to get newest bits (pre-release Tenerife builds) you will have to be in the Ready! or the Go! program, then you will have access to newer builds from Tenerife.
If you are not in any of these programs, you can also wait approx. 1 week after which we will ship another public developer preview, which probably contains a number of the things you are waiting for.

**Comment by JulianTillmann** [comment]
I would argue, that this is not a new Feature but rather Fixing an oversight. The same function has been exposed on the sales side, but, as it happens so often with NAV releases, the purchase side is forgotten :-/  Without this function we cannot use our document Reports in Extensions for NAV2018. It is also a minor fix, just changing a property, I don't quite see how this would "disrupt" anyone. 

We are not in the Go! or Ready! program an Tenerife is not available in Germany, but you're telling us to get going on developing extensions. We would really like to, please help us do exactly that ;-)

**Comment by freddydk** [comment]
Ready! program should also be available in Germany for partners working on extensions for Dynamics 365 Tenerife.
reg. this fix - it was not categorized as a bug with a request for hotfix and you will find that there are probably other things that have been overlooked - we are working on those.
You can request a hotfix, but I don't think you would get it. Primarily because there is a good workaround.
When working with NAV 2018 you have the option to do code customization and fix the bug yourself in order to continue your extension development. That would be the fastest way to get around this IMO.

**Comment by JulianTillmann** [comment]
okay, we'll think about how to proceed. 

will this at least be fixed in NAV2018 R2?

**Comment by freddydk** [comment]
Yes

**Comment by JulianTillmann** [comment]
okay, thanks for all the info

**Comment by JulianTillmann** [comment]
Just FYI: 
The Salesperson/Purchaser Primary Key Field "Code" was Extended from 10 to 20 characters in CU02 for NAV2018. 

![salespers](https://user-images.githubusercontent.com/35929603/37076200-d9dbe01a-21d5-11e8-8d44-c87f261e1b4b.jpg)


I would argue this is neither a  hotfixes nor a regulatory Feature and is way more disrupting than a newly exposed function for a crucial part of how NAV handles VAT-Calculation.

**Comment by JesperSchulz** [comment]
The change you are highlighting is a little peculiar, as I cannot find it anywhere in our history. The change to code 20 was made in the beginning of 2017 and hence should have been part of the 2018 version from the beginning. And from what I can see, TAB13 was indeed released with code 20 and has not been modified since the official release (at least the W1 version) – but your screenshot shows differently, so I’m not entirely sure what’s up and down here. Bottom line though would be, that if we indeed released it with code 10, it was a mistake and hence had to be set to code 20 again, as reducing field length is a breaking change. But you are of course right, that normally such change would not qualify for a HF, even though increasing field length isn’t considered a breaking change.

**Comment by JulianTillmann** [comment]
Did you mean "NAV2017" with "in the beginning of 2017"? Because up to & including NAV.10.0.19831.DE the Salesperson Code is Code10. 

But that's not the question I had: why should extending a Code length not be a "breaking Change" in a CU? Any customization we do with this field has the potential of not working if anybody creates a new salesperson with more than 10 characters. 

And if that's not a breaking Change, how is Setting the "FunctionVisibility" property of one function to external or "extending" this a breaking Change you cannot backtrack to a CU for on prem?

**Comment by JesperSchulz** [comment]
No, I did not mean NAV2017 :) We made the change in January 2017 and it hence should have been in the 2018 release. Again, not sure what happened there, as I cannot see it ever being code 10. But never mind…
Your point is of course valid. Now, even increasing field lengths are breaking changes for you. Our (current) definition of breaking change is if there is potential data loss, which there only is when you reduce field length, remove a field or the like. Increasing it, does not lead to data loss or will lead to compilation issues and hence currently isn’t considered breaking. That will have to change, I recon.
Anyway, from what I can see, we did not mean to ever release it as code 10, which is why it’s now code 20. It’s an unfortunate change, but it was necessary in order not to break things internally.
Thanks for bringing it up and we will of course try not to make too many changes of this nature going forward.

**Comment by JulianTillmann** [comment]
I don't want to argue with you, but this is very confusing to me. January 2017 is not the Point of a Major release, that would have been either December 2017 for NAV2018 or October 2016 for NAV2016. So this must have been a cumulative update, which one is irrelevant in my opinion. ;-) 

And I still don't  get what's the difference between exposing a function and Change the datalength of a field.

**Comment by JesperSchulz** [comment]
No need to argue, no :-) Unfortunately I cannot give you an answer to why we made that change, as I simply cannot find it anywhere. That annoys me a little, as I’d love to give you the justification for why we made that change. That is where January 2017 comes in, which is the date since when the field was supposed to be code 20. That change wasn’t backported to any on-prem release, as we shouldn’t do that (to which you agree, I understand ;-)). But since then we did have our Madeira/Tenerife/D365 releases and we do want to keep those two versions in sync. Hence we had to fix the mistake if we somehow shipped with code 10 again.

About exposing a function: It sounds like there’s a little misunderstanding here, now that I read all comments again. Exposing a function is by no means a breaking change! You can request exposing functions any time and we’ll be happy to do it. You just cannot make that request for NAV2018 in this repo, as this is only for non-released versions. If you request a function expose here, we cannot automatically backport it to already released versions. Changes to already released versions need to go through the official channels, just like any other hotfix request, as we have certain processes in place (such as documenting the changes in KB articles etc.) which we have to follow. If you need a function expose to be backported, please create a support ticket and we WILL happily merge the change back to NAV2018. Sorry if there has been some confusion here.

**Comment by JulianTillmann** [comment]
okay, now I understand thanks for Clearing that up. I thought this would be the support channel for all Things "AL" since it's in the Name. 

Then I'll go through Partner source to get my Exposition :)
