### ISSUE TITLE
Custom Layout with Extension Report

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/AL#1584]
When using a Report from Extension 2.0 the Custom Layout functionality doesn't work. 

Repro Steps
- Create a New AL-Projekt
- Add a Report with RDLC-Layout 
- Add the Report.Run() to a Page
- Publish App
- Run Report from Page -> It works 

- Go to custom Layouts & create a new Layout for this Report
- Change the RDLC-Layout & Import it back
- Set Report Layout to Custom Layout
- Run Report from Page -> you get an empty Page

![layout](https://user-images.githubusercontent.com/35929603/36020423-e7ae732c-0d82-11e8-8a57-fc1d66d25e42.png)

I've  added my AL-Project & the Changed Layout

[R50100_Pink.zip](https://github.com/Microsoft/AL/files/1710361/R50100_Pink.zip)
[ReportTest.zip](https://github.com/Microsoft/AL/files/1710360/ReportTest.zip)

**Comment by dennisfrostlander** [comment]
Could you check the errors in the Event Viewer? When I try the attached report, I get this:
> definition of the report '' is invalid. ---> Microsoft.ReportingServices.ReportProcessing.ReportPublishingException: The Value expression for the text box ‘CustNo’ refers to the field ‘CustNo’.  Report item expressions can only refer to fields within the current dataset scope or, if inside an aggregate, the specified dataset scope. Letters in the names of fields must use the correct case.

So it seems like rdlc was not generated correctly.

**Comment by JulianTillmann** [comment]
The Report was working fine, then I exported the rdlc from custom Layouts, Changed the Color and re-imported it. I also did this with several other Reports.

If there's a Problem in rldc it seems to be generated from the custom Layouts ex- or Import.

**Comment by dennisfrostlander** [comment]
The problem is the following:
- The rdlc file contains a dataset field CustNo, and on line 100 this field is used:
```<Value>=Fields!CustNo.Value</Value>```
- The AL report no longer contains the CustNo column - now it's called ColumnName.
- When you press Ctrl+Shift+B in VSCode, the rdlc dataset is updated with new column names, but the usages of old columns are not cleaned up. This way the rdlc file becomes invalid.

I think this might be by design, @DominikDitoIvosevic can confirm for sure. It is not an easy thing to rename all field usages in the report when AL report definition is modified.

**Comment by DominikDitoIvosevic** [comment]
Yes. This is correct. Since we removed IDs it is no longer possible to rename fields since we do not know that the column added is the same as the column removed just with a different name. The simplest thing to do would be to open the rdl file in visual studio code or notepad and find and replace the old field name with the new one.

Now you will have to be more careful with renaming columns or have to do the renaming in the rdl file yourself. We have tried finding a solution now that there is no way to lock down a name with the ID but we did not find an optimal solution yet.

**Comment by JulianTillmann** [comment]
You mean this diff? 
<img width="921" alt="diff" src="https://user-images.githubusercontent.com/35929603/36099225-13984522-1002-11e8-8d1b-d0965eeb0797.png">

as I said, I just exported the custom layout, changed the Color and re-imported it. How can it be "by design" if this renames my columns and breaks the Report? 

[rdlcs.zip](https://github.com/Microsoft/AL/files/1716428/rdlcs.zip)

**Comment by DominikDitoIvosevic** [comment]
What is the name of your column in AL? Is it "ColumnName"?

**Comment by JulianTillmann** [comment]
I attached both rdlc-files in my previous post. It's the "REP50100.rdlc" or the left in the diff-screenshot.

**Comment by DominikDitoIvosevic** [comment]
Each rdlc file has it's accompanying AL file where the report and it's dataset is defined in the AL language. I'm asking you about the contents of the AL file and the name of the report column there.

**Comment by JulianTillmann** [comment]
I had attached the complete AL Project in my first post, but here you are. 

<img width="287" alt="al" src="https://user-images.githubusercontent.com/35929603/36099986-e7172362-1004-11e8-8839-f80fa53148f7.png">

[ReportTest.zip](https://github.com/Microsoft/AL/files/1716472/ReportTest.zip)

**Comment by DominikDitoIvosevic** [comment]
As you can see, the column name is "ColumnName" and the feature which has been introduced is to update the RDLC file to reflect the names in it's data set. If you were to rename the column name from "ColumnName" to "CustNo" your issue would go away

**Comment by JulianTillmann** [comment]
I'm sorry but again: 
- I created the Report in AL and it sort of worked, an empty page with the caption. 
- I changed the layout in "custom Layouts" and now I get no page at all. 

I also tried this with several other Reports as well, could you please try out me Repro steps and verify this behaviour.

**Comment by dennisfrostlander** [comment]
Hi @JulianTillmann,

Since this is not a trivial report column rename scenario, it's important to understand here the exact order of steps happening.

Before we do that, there is one important report runtime behavior we need to keep in mind. In AL report (or in the old reports object) there is a definition of all report columns - column names, types, binding to source data, etc. In the RDLC file, column names from AL report are stored in the DataSet XML node.
When a column name is changed in AL report, the new DataSet definition is automatically stored in RDLC, however, the usages of these columns are _not_ updated. This is something that the user has to do himself (and had to do in the past as well). This is the non-trivial work item that I mentioned before.

Now let's have a close look at your repro.
First thing to notice is that the attached project is already in a "half-renamed" state. In the RDLC file, the dataset still contains CustNo column, but in AL report, the column is already renamed to ColumnName.
So if I follow the repro steps precisely, I cannot run either of the attached reports in step 5 (neither pink nor the other one), because they are already invalid. 

What I assume might have happened is something like this:
- You had a column called CustNo and everything was working
- You have exported the custom RDLC layout with CustNo column
- In the meantime, the report column was renamed CustNo -> ColumnName, and AL report was updated on the server
- You have imported the RDLC layout with the old schema. At this point in time, the dataset in the RDLC was automatically updated and this made the report invalid. This is what you have showed in the diff in one of the previous comments.

If my assumptions are incorrect, please feel free to correct me where I am wrong, I had to improvise a little.
I think the main thing to remember is that usages of renamed fields in the reports have to be updated manually, with care. It would certainly be very helpful if this worked automatically, however, this is not something that can be easily done.

**Comment by JulianTillmann** [comment]
Hi @dennisfrostlander, 

I added a test-Project to help, but you seem hung up about this particular example. I've reproduced this behaviour five times myself with any Kind of AL-Projects. I first encountered this with a projected we converted with the TXT2AL-Exe. 

Please check any AL-Report-Extension with Custom Layouts. Does this work in your Scenario or do you get an empty page like this: 

<img width="958" alt="empty" src="https://user-images.githubusercontent.com/35929603/36102785-ae93aa16-100d-11e8-8f1c-ac225a1de5e6.png">

And : why does the custom layout do a rename anyway? How are we supposed to support this if it changes our column names?

**Comment by DominikDitoIvosevic** [comment]
Are you sure you have the same AL report as you have in CSIDE? It is not enough just to create a new report object in AL and link some RDLC to it. The AL report has to have the correct dataset so that the server knows which data to fill in. As I understand, you just create a new report and add the correct tables and fields but your names for them are incorrect. Then your data set gets updated to be invalid. The new names you specified in your AL code are not the same as the names you used to have in CSIDE. 
You named your columns in your AL dataset differently than they used to be so the server is complaining that it doesn't know which column you are referring to.

Change you AL code to:


```
report 50100 TestReport
{
    dataset
    {
        dataitem(Customer; Customer)
        {
            column(CustNo; "No.")
            {
                
            }
        }
    }
}
```

**Comment by dennisfrostlander** [comment]
I certainly did check the scenario that you described for a completely new report. And it works just fine.

The only scenario in which I get a blank page just like yours is when I:
- Create rdlc custom layout with columnA
- Update Report.al and rename columnA to columnB
- Do not update any usages in rdlc file and run the report with the custom layout.

I focused on this scenario because this is exactly what your test project contains, otherwise I cannot reproduce the blank page.

The Import of custom layout renames the dataset in the RDLC so that it matches the latest dataset definition in the AL report object. This is the old nav feature and there is even a special action for doing exactly this - Custom Reports Layout -> Actions -> Update Layout.

A rename is done only to match the column names in the RDLC file and in the AL report. If these names don't match, none of the report logic in the AL file will work... We certainly don't rename columns for no reason :)

**Comment by JulianTillmann** [comment]
Okay, I started from scratch and now it's working. Now I'm really confused. 

Could you maybe Point me in the right direction for my actual Project? Attached are three files 
- the .al file
- the "original" rdlc-definition
- the custom layout rdlc-definition "HotPink" 
[Project.zip](https://github.com/Microsoft/AL/files/1719299/Project.zip)

I do see, that we've renamed a dataitem "Labels" to "LabelLoop" in the al-file, because of an naming restriction with AL. But my original rdlc layout with the wrong dataitem Name works and the changed one with the correct dataitem Name doesn't? 

Also the export/Import added a new field
        <Field Name="ContinuedLbl">
          <DataField>ContinuedLbl</DataField>
        </Field>

Can you please explain, what is Happening here?

**Comment by DominikDitoIvosevic** [comment]
Hi @JulianTillmann . 

1. Becaused you renamed a field in your report from Labels to LabelLoop, the usages in the RDLC are now disconnected. You need to rename the field in the RDLC as well. Simply find-and-replace `!Labels.` with `!LabelsLoop.` in the RDLC file and it should be fine.
2. Alsom I can see that you have a column in your AL report called ContinuedLbl so that's why it was added to the RDLC data set as well. It's how this is supposed to work

**Comment by JulianTillmann** [comment]
Hi @DominikDitoIvosevic , 

thanks a lot, now it's working. Sorry for being so pernickety with this subject. 

But developing rdlc Reports has already been difficult enough. To add another layer of inconsistency we Need to watch out for is the wrong way to go in my opinion. Please put your heads together and find a solution that makes it as easy as possible to do developing for rdlc in AL as well. 

Thanks again for your Patience & have a nice day :)
