### ISSUE TITLE
Deploy error: An unsupported key change was detected.

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1595]
Full error:

> TableExtension 50118 :: An unsupported key change was detected. Keys cannot be changed, removed, or reordered. New keys can only be added to the end of the list.

Context (find attached the AL project [DeactivateCustomer.zip](https://github.com/Microsoft/AL/files/1719961/DeactivateCustomer.zip)):

1. TableExtension on table 18 (Customer), being field 50000 called _Inactive_.
1.  One PageExtension for page 21 (Customer Card) showing this new field and adding a new action _Toggle Inactive_ to check or uncheck the field
1. One PageExtension  for page 22 (Customer List) adding a new action _Toggle Inactive_ to check or uncheck the field

Now let's add a _key_ to the TableExtension, called **MyKey** based on the field added to the TableExtension object:

1. key(MyKey;Inactive).
2. Build and deploy the solution (F5), verify with MSSMS that the index has been created on the TableExtension.

Steps to reproduce error:

1. Uninstall and unpublish the extension
1. Update the TableExtension object by removing the keys section (and thus remove the just created key).
1. Build and deploy the solution (F5)

Now the error occurs.

Note that uninstalling and unpublishing the extension will not solve the issue. No way I can build and deploy the solution (F5) anew. The error keeps on occurring. Even removing the TableExtension SQL table (using f.e. MSSMS) will not solve it.

The only way I was able to get it working again, was deleting the database and restoring an older backup.

Note: this happened on NAV 2018 CU 2 (build 20348).

**Comment by HunterFeltman-MSFT** [comment]
See issues: #1499 & #1198 & #905 
Extensions V2 do not support destructive schema changes across synchronized versions, as you have discovered. A deprecation story is still in our backlog.

The issue is appearing because the platform does not remove the schema elements coming from an extension just because you have uninstalled/unpublished it. You must also perform the 'Sync Clean' step manually if you are going to remove the extension with cmdlets yourself instead of letting VSCode handle some of this for you.

In brief, after uninstalling your extension, execute the following:
`Sync-NavApp -Name <name of extension> -Version <Version of extension> -Tenant <Tenant name> -Mode Clean
`

This will remove all the schema elements across **all versions** of the extension (i.e. it removes all of the old data) making your database 'clean' from the perspective of this extension.

The next time you have to deploy your package (F5 scenario & the like), there will be no 'prior' schema to consider/compare against and all 'changes' will be considered 'new'. This is effectively what you did to workaround the issue, excepting that it is only within the context of the schema elements from the extension, not the entire database.

I will re-iterate that the 'clean' mode will remove schema elements from **all versions** of the targeted extension and is only meant to be used during:
 A) Development scenarios where rapid initial schema changes are required
 B) 'Scorch the earth' scenarios where you are 'completely' done with an extension and want to remove every last trace of it from your service.

**Comment by lvanvugt** [comment]
Thanx for your elaboration. Is this on the backlog for v3?

**Comment by HunterFeltman-MSFT** [comment]
I can't give you anything specific date/releasewise except to say that 'deprecation' is definitely a priority feature for extensions and is something we have been thinking about.
