### ISSUE TITLE
[Function Expose] Expose function GetCaptionClass on TAB37, TAB111, TAB113, TAB115

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/AL#1635]
```
LOCAL GetCaptionClass(FieldNumber : Integer) : Text[80]
GetHeader;
CASE FieldNumber OF
  FIELDNO("No."):
    EXIT(STRSUBSTNO('3,%1',GetFieldCaption(FieldNumber)));
  ELSE BEGIN
    IF SalesInvoiceHeader."Prices Including VAT" THEN
      EXIT('2,1,' + GetFieldCaption(FieldNumber));
    EXIT('2,0,' + GetFieldCaption(FieldNumber));
  END
END;
```

**Comment by JesperSchulz** [comment]
I've received a Little push back on this request, seeing that there is no good reason why this function couldn't be reimplemented (even in a simpler form). By exposing this function, we're now making it a lot harder if we ever want to refactor this function...
Nontheless, this function isn't a likely refactoring candidate, which is why I'm exposing all GetCaptionClass functions on all tables :-)
Fix coming up in a future release!

**Comment by SirBETE** [comment]
Ty for being awesome! :D
