### ISSUE TITLE
Use function result as input for page control properties?

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#1644]
In many cases, the appearance of page controls (e.g. actions) is based on some predefined conditions. Since the controls (actions) are are often copied on various pages (list, card, ...), we put the condition to control the behaviour into a function on the source table. Result is that we have to define a variable, get the function return value in a variable (in the OnAfterGetRecord) and assign the variable to the control property. This is fine, if we need to colorize an entire line (= applying the conditions on various controls). But couldn't it be simplified if we only needed to apply this to one action only?

Is there a drawback in immediately assigning a function result into the property value? For example on an Action, set the property: 

`Visible = Rec.HasSourceDocument;`

The compiler does allow this, but running the code gives an error 'The identifier HasSourceDocument could not be found'.

**Comment by StanislawStempin** [comment]
The problem is that these are client-side expressions. They are evaluated in the client based on the data that was already sent to it and at that point in time we cannot execute additional AL code.

I will mark it as a suggestion for future improvement. We will see what can be done, we might be able to generate synthetic variables that get evaluated just before data is sent to the client.

**Comment by fvet** [comment]
If this is not on the short-term roadmap to be supported, can you please integrate a compiler check to prevent assigning functions to the Editable (or other) property? The compiler successfully compiles, but running the page in the webclient, still result in a 'weird' error ...

> The identifier 'pxxxRec' could not be found.

Cause:

`Editable = IsModifyAllowed(); // Where IsModifyAllowed is a function`
