### ISSUE TITLE
Add support for HashSet

### ISSUE THREAD

**Issue by joandrsn** [microsoft/AL#1668]
Currently we have support for List and for Dictionary.

It would be nice if we had support for HashSet.

HashSet is only a value storage and it does that well.

A HashSet is fast at storing and fast at reading.

So lets say I want to create a list of distinct customers, from running through the customer ledger using a list i would do:
```
var
    myList: List of [Code[10]];
begin
    if not mylist.Contains(CustomerNo) then
      myList.Add(CustomerNo);
end;
```
We could mistreat the dictionary data structre and input dummy values instead of the actual value, but readability is worse.
```
var
    dict: Dictionary of [Code[10], Integer];
begin
    dict.Set(CustomerNo, 1); //1 is used as a dummy value
end;
```

I would like to use a HashSet like this:
```
var
    set: HashSet of [Code[10]];
begin
    set.Set(CustomerNo);
end;
```

There are multiple more data structures which have each their own advantage.

A list of data structures and their complexity can be found here http://bigocheatsheet.com/

**Comment by StanislawStempin** [comment]
Support for HashSet is on our long term backlog. We scoped it out for now due to the fact that the scenarios can be covered by a Dictionary (although at the cost of poorer readability and higher memory consumption)

**Comment by atoader** [comment]
If you think this suggestion should be considered for a future release of Business Central, please open an idea on https://aka.ms/BusinessCentralideas.

We are working on consolidating feedback to the [Dynamics 365 Business Central Ideas forum](https://aka.ms/BusinessCentralideas) so that members of the community can easily find relevant suggestions and show their support through votes. We're constantly monitoring top ideas and will consider them for a future release.
