### ISSUE TITLE
Temporary records cause modification of real records in events

### ISSUE THREAD

**Issue by yuliia-biloklokova** [Microsoft/AL#1671]
There are 2 issues related to usage of temporary records.
In standard events:
1) Not all events have check "if Record.IsTemporary  then exit". Example Codeunit 1637 Office Document Handler:
UnlinkOfficeDocumentOnAfterDeleteSalesHeader(VAR Rec : Record "Sales Header";RunTrigger : Boolean)
(has DELETEALL inside).
2) If you pass variable as a copy (without VAR) record is not temporary anymore and "if Record.IsTemporary  then exit" doesn't work. Example Codeunit 6721 Booking Manager:
LOCAL CanHandleHeader(SalesHeader : Record "Sales Header") : Boolean

That's why function like this:
 trigger OnAction();
                    ```
var
                        SalesHeader: Record "Sales Header";
                        SalesHeaderTemp: Record "Sales Header" temporary;                  
                    begin
                        SalesHeader.SetRange("Document Type",SalesHeader."Document Type"::Quote);
                        SalesHeader.FindFirst;
                        SalesHeaderTemp := SalesHeader;
                        SalesHeaderTemp.Insert;
                        SalesHeaderTemp.Delete;                     
                        page.RunModal(Page::"Item List");
                    end;
```

Returns error:
Microsoft Dynamics NAV
---------------------------
The following C/AL functions are limited during write transactions because one or more tables will be locked. Form.RunModal is not allowed in write transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed. Report.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'Report.RunModal(...,FALSE)' is allowed. XmlPort.RunModal is allowed in write transactions only if 'RequestForm = FALSE'. For example, 'XmlPort.RunModal(...,FALSE)' is allowed. Use the COMMIT function to save the changes before this call, or structure the code differently.
---------------------------
OK
---------------------------

**Comment by StanislawStempin** [comment]
Thanks for reporting this. Regarding 1 and 2 it does seem like a problem and I will mark this issue as an application bug.

Regarding your last example it doesn't seem to have anything to do with "temporary" flag being lost when assigning variables. If I run the same code as yours but only using the SalesHeaderTemp the same error still occurs.

Whereas the following code correctly produces Yes, No, Yes messages:
```
SalesHeader.FindFirst;
message(Format(SalesHeaderTemp.IsTemporary()));
message(Format(SalesHeader.IsTemporary()));
SalesHeaderTemp:= SalesHeader;
message(Format(SalesHeaderTemp.IsTemporary()));
```

**Comment by tonioknuth** [comment]
This seems like a pretty major problem to me. If I understand this correctly,  this fundamentally means that I can not control the interactions of my temporary records with the real records in the database. Meaning even if the "if Record.IsTemporary then exit" is at some point added throughout the subscribers in the standard code, there still could be some third party extension that does not think of this. To me this means that I can not use temporary tables at all, as I can never be sure of the implications somewhere else in the system. 

I see two possible solutions: 

1. We are able to set a flag on temporary tables, preventing them from triggering events

2. The pattern in the subscriber is opt-in, rather than opt-out, meaning developers that know what their are doing can opt into their code being run on events published by temporary tables, rather than the other way around.

Are any of these solutions feasible in your eyes ?

**Comment by StanislawStempin** [comment]
We are leaning towards not triggering event subscribers for temporary records by default and then allowing event subscribers to explicitly opt-in if they actually do want to handle temp records.

**Comment by jglathe** [comment]
In C/AL, all code that is executed on temporary tables must be explicitly written for it. Is there a use case where event handling on real and temporary records makes sense? Opt-in appears the way to go, IMO. On another note, if temporary tables create events, the runtime needs to handle them anyway. I would expect situations where this sheer amount of event generation / "handling" (mostly ingnoring them) has effects on performance.
