### ISSUE TITLE
Data considerations when converting an existing C/AL modification to an AL Extension

### ISSUE THREAD

**Issue by SaroAynedjian** [Microsoft/AL#1689]
I am in the process of converting an existing C/AL modification in NAV 2018 to an extension for a client. 
I'm wondering if anyone has experience with such situations and how to handle the data conversion/transfer. 
Would I be able to use the same object / field IDs in the AL extension as the existing modification? if not, what is the best way to handle transferring the data from the old classic tables to the AL extension tables?

**Comment by LauraNicolas** [comment]
Hello @SaroAynedjian 

I just did the same for a client. I was updating from NAV2009R2 Classic, to NAV2018 100% extensions. We kept the same field names, but not the same IDs because we have refactored the code a bit.

Those are the steps I took:

1. In NAV2009 I moved the data of the 50K fields to Temp tables, as the standard Upgrade Toolkit does
2. In NAV2018 I imported the Cronus fob file. After sync all data in fields 50K where lost.
3. I created an "Upgrade Toolkit extension" for my data. 
    I had to generate symbols from the C/SIDE environment to acces the temp tables.
    The UpgApp depended on my other customized-apps, to acces the new field.

The Upgrade extension is basically a codeunit that moves the data from the Temp tables, to the app tableextensions.
Per each temp table, I created this code:

if UpgTable.FindSet then
  AppTable.GET(UpgTable."Primary key");
  TablaStd.Field1 := UpgTable.Field1;
  TablaStd.Field2 := UpgTable.Field2;
  TablaStd.Field3 := UpgTable.Field3;
  [...]
  TablaStd.Modify;
until UpgTable.Next = 0;


4. After running the codeunit per each company (from PowerShell), I installed the Upg App and I deleted all the temp tables.


I don't know if there is a better approach. This is just how I did it. I hope it helps.

Salut!
Laura Nicolàs

**Comment by SaroAynedjian** [comment]
Thank you so much for your input Laura, 
I was hoping there would be some way to preserve the same object and field numbers, but I think the data will need to be ported over. Thanks!

**Comment by LauraNicolas** [comment]
- If you created a field from C/SIDE, it was added to the existing table in SQL.
- If you create a field from an extensions, it creates a new table.

The extensions SQL table structure is quite different from what we used to have in C/SIDE, so temp tables are needed to move data around.

Salut!
Laura Nicolàs

**Comment by StanislawStempin** [comment]
The approach that @LauraNicolas described above is currently the only way to do it.
