### ISSUE TITLE
Caption doesn't show in Dyn365 sandbox

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1692]
Appears that the translation-feature doesn't work (anymore) on a D365 sandbox: I'm using the latest docker image "microsoft/dynamics-nav:devpreview-finus"

Situation:
- We enabled the translation feature
- We use labels in our notification
![image](https://user-images.githubusercontent.com/12088142/36720188-2deb3936-1b9f-11e8-9e63-3b3f43ce46ae.png)
used in:
![image](https://user-images.githubusercontent.com/12088142/36720221-45ce23ce-1b9f-11e8-871c-dfb44ab8cf7e.png)
Also we have a wizard, where we have our label for the assisted setup.  But many (not all) captions nor labels show up empty.  The notification is not shown in this case (probably because it has an empty message), and pages are like:
![image](https://user-images.githubusercontent.com/12088142/36720403-dc10f7bc-1b9f-11e8-8df8-f68632de7f93.png)
and the wizard:
![image](https://user-images.githubusercontent.com/12088142/36720429-fad791c4-1b9f-11e8-831b-df058106c6f1.png)

Just for the record:
- All ApplicationAreas are in place!
- We tested it on the previous release (D365 sandbox), and that did work!
- We tested with all the "user experiences"

When you use the "old" "CaptionML" property, it does show, like:
![image](https://user-images.githubusercontent.com/12088142/36720540-478be11e-1ba0-11e8-8372-07d5e4b87bb4.png)
does show:
![image](https://user-images.githubusercontent.com/12088142/36720593-67eb66e6-1ba0-11e8-9fa1-8b7158f84702.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @waldo1001 . We are working on a new feature where if the label text differs from the translation item source (this means that the source string changed in the source code since the translation file was last updated) then we ignore that translation item. This was a requested feature to make sure you aren't using outdated source strings by accident (if you change the source string you want to update the translations as well). I'm working on adding warnings for the cases when this is happening. Could you check if this might be causing your behavior? Otherwise, could you please give us some kind of repro so that we can investigate?

**Comment by ajkauffmann** [comment]
Same issue here. Some observations:

- Only happens with feature TranslationFile enabled in app.json.
- When translation file is generated during publish it is ok. But when you publish a second time (with no changes at all), then the labels become empty.
- Labels are also empty van you first build (with Ctrl+Shift+B) and then publish.
- Removing the .xlf file helps, it gets recreated and labels appear again. But only one time.

**Comment by DominikDitoIvosevic** [comment]
Just to make sure we are on the same page:
* Are you sure you renamed the xliff file which was generated and now you are adding translations to the renamed file and not the one which was generated? The one which is generated gets emptied on each build so that one is only for reference.

**Comment by ajkauffmann** [comment]
No, I did not rename the xliff file at all. The most simple flow is like this:

- Enable TranslationFile feature
- Create a label or caption
- Publish the app (xliff is generated, captions are displayed fine)
- Publish the app without any change, now the captions are gone

**Comment by DominikDitoIvosevic** [comment]
Could you please check that you have the build 20643 or later? What is your current version?

**Comment by ajkauffmann** [comment]
Current version is Feb preview, build 20723

![image](https://user-images.githubusercontent.com/19155831/36849233-c2988c3a-1d63-11e8-8d35-2acd190bc057.png)

**Comment by DominikDitoIvosevic** [comment]
@waldo1001 @ajkauffmann I'm afraid I'm stuck right now as I cannot repro your issue. Could you please make a zip of an extension which demonstrates this issue? I tried but it simply works for me.

Also, there is a chance you're issue was fixed in the mean time. Could you please try getting a more recent build? 20723 is now 2 weeks old and I made some fixes in the mean time. Could you try with a 20937 or newer?

**Comment by ajkauffmann** [comment]
@DominikDitoIvosevic tested again with build 20901. That works like expected, so it seems the issue has been solved along the road.

**Comment by DominikDitoIvosevic** [comment]
I suppose this was fixed then. I'll close it and if you guys still experience issues please open a new issue
