### ISSUE TITLE
Declare Codeunit 60 "Sales-Calc. Discount".CalculateWithSalesHeader as [External]

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/AL#1709]
Codeunit 60 "Sales-Calc. Discount"
[AL] The type or method 'CalculateWithSalesHeader' cannot be used for 'Extension' development.

Was mention here already #569 - but still not available in CU 2

Thank you.

**Comment by JesperSchulz** [comment]
This GitHub repo is related to the latest Developer preview releases, not to NAV 2018 CUs (although we do take the input from here to proactively backport fixes to NAV 2018).
This particular fix was released in the February Update of Dev Preview and therefore https://github.com/Microsoft/AL/issues/569 has been closed.

This FAQ entry should probably be expanded to include event requests as well. In general we only add them to the latest builds since they can be added manually On-Prem:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018.
