### ISSUE TITLE
Function call to "Config. Package Management" (CU8611) - ApplyPackage not supported

### ISSUE THREAD

**Issue by ClintonSaunders** [Microsoft/AL#1724]
When trying to call the above function using code as follows:
"var:
      LocalConfigPackage : Record "Config. Package";
      ConfigPackageTable : Record "Config. Package Table";
      ConfigPackageMgt : Codeunit "Config. Package Management";

ConfigPackageMgt.ApplyPackage(LocalConfigPackage,ConfigPackageTable,true);"

Problem is reported - "The type or method 'ApplyPackage' cannot be used for 'Extension' development."

I tried calling a few other functions in Codeunit 8611 with the same result...

I hope this can be sorted soon.... this is the ONLY line in my entire extension (replication management) that I cannot convert from Ext 1.0 to Ext 2.0!

Clinton Saunders

**Comment by MikeGlue** [comment]
You may need to rework that code a bit to use the new stream-based functions.

I had similar code and I replaced with something like this:

var
   TempConfigSetupSystemRapidStart: Record "Config. Setup" temporary;
   TempBlob: Record TempBlob;
   ConfigPackageImport: Codeunit "Config. Package - Import";
   ErrorCount: Integer;
begin
  ConfigPackageImport.ImportRapidStartPackageStream(TempBlob, TempConfigSetupSystemRapidStart);
  ErrorCount := TempConfigSetupSystemRapidStart.ApplyPackages;

**Comment by ClintonSaunders** [comment]
ApplyPackage in CU 8611 is not a stream based function, so I don't think your scenario is the same thing. However, using the ApplyPackages function in Table Config. Setup does work. I think the reason is that function ApplyPackage in CU 8611 has the property "FunctionVisibility" set to Internal, whereas the function "ApplyPackages" in the table "Config. Setup" has the same property set to External.... it looks like you cant call functions in the base code that have the "FunctionVisibility" set to "Internal"...?

**Comment by JesperSchulz** [comment]
The function was exposed mid-December, meaning you should be able to use the function by now in recent preview builds. If you'd like to get the change backported to NAV2018, please create a support ticket, as we cannot backport based on requests in this repo. Thank you!

**Comment by JesperSchulz** [comment]
Here is the related issue, which was resolved: https://github.com/Microsoft/AL/issues/1415

**Comment by ClintonSaunders** [comment]
Hi Jesper,

Thanks you. I just want to understand the backporting to NAV 2018, and understand the process with regards to fixes made in this environment, and how they find their way into the NAV 2018 / Dynamics 365 software? Surely, its an automatic process that does not require a support ticket to be raised on the NAV side? Sorry to ask - just want to understand...

**Comment by JesperSchulz** [comment]
We have a short section about this in our FAQ: https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018.
The short answer is, that there is no automatic process for backporting the fixes addressed through this forum to already released versions. Fixes made in this forum will only be released with upcoming releases. If the fix is critical, you can at any time create a support ticket and we _will_ backport it. Otherwise, you are of course free to backport any application changes made in the latest preview / release to any released product! I hope that clarifies things a little? Else please let me know and I'll try to elaborate :-)
