### ISSUE TITLE
XmlPort doesn't recognize if same name is given to the Textelement and field of the Table

### ISSUE THREAD

**Issue by Chris-Dsilva** [microsoft/AL#1748]
My Xmlport uses XMLport which has a field named Type of datatype Option also I've declared Type as a Textelement but the system only recognizes the Field Type(Option String) not the Textelement.
I'm using NAV 2018 CU 2 version NA

![textelement](https://user-images.githubusercontent.com/24870777/37074086-e4b20b98-21f0-11e8-9835-4f320cca0b53.png)
![xmlport option](https://user-images.githubusercontent.com/24870777/37074090-ea667a92-21f0-11e8-9688-54cf6625ee9c.png)
![type](https://user-images.githubusercontent.com/24870777/37074215-af34c3b0-21f1-11e8-8aee-a2707f6bff7c.JPG)

**Comment by DominikDitoIvosevic** [comment]
@Chris-Dsilva I can't see the whole code which is relevant so I can't know what exactly is the issue but my first guess would be that the shadowing of the option variable is causing issues. The best way to go around this is to use a slightly modified name for the textelement and the issue would be solved.

If you think there is something incorrect with what the compiler does, please provide us more of the code so that we can see what is going on. The best would be to write a small example demonstrating the issue

**Comment by Chris-Dsilva** [comment]
attaching herewith the XMLport

[XMLport 50003 - CF_InsuranceScheduleImport.zip](https://github.com/Microsoft/AL/files/1788406/XMLport.50003.-.CF_InsuranceScheduleImport.zip)

**Comment by DominikDitoIvosevic** [comment]
Hi @Chris-Dsilva . Due to the fact that https://en.wikipedia.org/wiki/Variable_shadowing happens, you cannot right now access both variables. Your best approach would be to name your variables more descriptively so that their names don't clash. We could introduce mechanisms to be explicit which one of these 2 you want to use but it is not a high priority right now
