### ISSUE TITLE
Question: Loading extension with same ID but different name via VSC

### ISSUE THREAD

**Issue by Quivelus** [microsoft/AL#1761]
Hi,

When loading an extension via Visual Studio Code (Ctrl+F5 = "Start Without Debugging") that has the same ID (a GUID in app.json), but a different name (!), the previously loaded extension with the same ID is overwritten. I now GUIDs should be unique, but you never know of course. Even the version doesn't matter in this case. As I read in another post, deploying using VSC cleans up the extension first. Maybe that explains things as this could be done based on the ID (GUID). Nevertheless a warning or so might be in place when deploying an extension using VSC with the same ID but different name. What are your thoughts?

Regards,
Quiv

**Comment by atoader** [comment]
Hi @Quivelus ! How did you come to have another extension with the same GUID? What is happening is that the Guid is the main component of the extension's identity. If you use the `AL Go!` command, you will get a new Guid and the chance of collision is extremely low. 
We also need to consider that deploying an extension with the same Guid but a different name also happens when you are renaming an extension and this will happen with a higher probability than generating a clashing Guid.

**Comment by Quivelus** [comment]
Hi, I was just testing around with two copies of the same project. That's when I noticed the behaviour. I know chances of creating (not copying :-)) the same GUID is very small. For me no problem, but I was just thinking a warning might be in place, as the copied project name and version were different.

**Comment by pborring** [comment]
I am going to close this old feedback item. In version 2021 Wave 2 (v19) we have added support for renaming extensions, this implies name (and publisher) is not used on runtime/deploy, only appId and version. For now name and publisher are still required in VS Code project/app dependencies though.
