### ISSUE TITLE
"target" in app.json

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#1763]
Can anyone explain what the target-property is used for in the app.json?

![image](https://user-images.githubusercontent.com/12088142/37198389-6fdffb7e-237e-11e8-8667-8e2e25c7a5ad.png)

**Comment by thpeder** [comment]
Hi @waldo1001,
You can read more about the app.json and the launch.json files [here.](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-json-files#appjson-file).

It is used to control how much of the API is available. Keep it as Extension unless you know you will only publish it to an on-prem instance then you can change it to Internal and get the full API, because by setting it to Internal means that you will not be able to publish it to AppSource.

**Comment by waldo1001** [comment]
I get that Internal part, and I can understand the personalization part - but what is the "solution"?

**Comment by thpeder** [comment]
Personalization is used for personalization apps which only allows for moving things around, changing the visibility of things and stuff like that, but no code can be include or adding new tables or changes like that.
Solution isn't used for anything.

**Comment by waldo1001** [comment]
Subquestion - is the "personalization" app dependent on all the extensions?  Meaning: is it going to create the same dependencies (and dependency-problems) as the inclient visual designer?

**Comment by thpeder** [comment]
Dependencies for personalizations are not handled the same way as they are for extensions, so no, they do not have the same dependency-problems and since personalization is UI only, if the target of a personalization is not found that specific change is ignored while the other changes are still applied.

At this time the personalization target is only intended to be used internally by the designer for personalizations.

**Comment by atoader** [comment]
HI @waldo1001 ! May I close this issue?

**Comment by waldo1001** [comment]
yep! :-)
