### ISSUE TITLE
[External] T113 GetSalesShptLines / T115 GetReturnRcptLines

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#1793]
Can you please put following functions to 'External'?

- T113 GetSalesShptLines  : to retrieve the Sales Shipment Lines linked to a Sales Invoice Line
- T115 GetReturnRcptLines : to retrieve the Sales Return Receipt Lines linked to a Sales Cr. Memo Line

**Comment by JesperSchulz** [comment]
Thank you for reporting the issue. I've recieved the following reply from one of our developers. If you do not agree with the reply, please re-open this issue.
-----------
The function GetReturnRcptLines is a local function created with the purpose of aggregating all receipt lines into a temporary record. We do not foresee a need to have access to such a temporary record except in the case where we use it locally. That's why we have decided not to fix this request.

Having said that, it should be straight-forward to get the return receipt lines by creating a custom function that does the following:
1. Filtering on the value entry via the EXTERNAL FilterPstdDocLineValueEntries function
2. Get the Item Ledger Entry from the value entry
3. From the item ledger entry, get to the return receipt document/ document line.
