### ISSUE TITLE
Subscribing to events with many parameters is a tedious job

### ISSUE THREAD

**Issue by joandrsn** [Microsoft/AL#1799]
If I subscibe to the event `OnBeforeFormatAddress` on `Codeunit Format Address` I get to type 20 parameters manually (of which 2 needs to include `var`).

In C/AL, these are autogenerated when I chose which event to subscribe to.
Is there any way to autogenerate this?

The way I'm currently doing it, is by going to definition of the event, but in the definition, `var` is not listed, so I have to remember which of the 20 parameters that are `var`

**Comment by StanislawStempin** [comment]
This is addressed in the upcoming update. Please see #149 for more details

**Comment by joandrsn** [comment]
Cool stuff, I searched but couldn't find anything.

**Comment by gudrunleos** [comment]
#149 only applies to the event subscriber, not the procedure itself, right?
The key thing here is what happens when in C/AL you accepted to overwrite the signature:
![image](https://user-images.githubusercontent.com/24827406/37511856-3815a052-28f8-11e8-9437-4bfa473d76d3.png)

Can we expect something simular in AL?
