### ISSUE TITLE
Error compiling dynamic control expression

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/AL#1800]
Boolean expression using option types in a page field causes the following error when the page is opened:  

> Error compiling dynamic control expression: 'TestOption <> TestOption :: Option1' at index '25'. The error is: End of expression expected..

This is in the 11.0.21063.0-finca build. 

Sample project: 
[HelloWorld.zip](https://github.com/Microsoft/AL/files/1816626/HelloWorld.zip)

I did not test to see if any boolean expression in that property causes the same thing. 

*I did see that this is also occurring for the ShowMandatory property

**Comment by DominikDitoIvosevic** [comment]
Hi @strophanthus . This is a regression from fixing https://github.com/Microsoft/AL/issues/937
I have the fix so it should be available very soon on the dev preview. The issue is with option constant in the client expression. A workaround could be to store the constant in a variable and compare that instead. Or wait a few days

**Comment by strophanthus** [comment]
Thanks @DominikDitoIvosevic !
