### ISSUE TITLE
On-Prem Improvements

### ISSUE THREAD

**Issue by bwdeleeuw** [Microsoft/AL#1806]
Now that NAV 2018 R2 is no longer going to be released, what is the strategy for releasing new features to on-prem?

**Comment by SirBETE** [comment]
Have asked the same in a MS support case:
Issue Definition: 
Is it possible to implement all improvements of tenerife (events requested) into NAV 2018 CU 3 and sent us the fob so we can import it into the Classic dev env?

Scope Agreement: 
The case is considered as resolved when we clarified if events from Tenerife can be backported to NAV 2018 CU3.

This is unfortunately not possible since the Event Nomination is PER VERSION / RELEASE. 
Since from release to release the application might change, the request to for event nomination are assigned PER VERSION. 

If you is in need to develop an Extension V.2 with NAV 2018 and need to have some event created you would need to request them efficiently by providing a business need and which event the want to be nominated with detailed description and we will have to nominate this changes to the development team.

Conversation still ongoing (will update with more info)

**Comment by StanislawStempin** [comment]
While NAV2018 R2 was not released there will be a Fall 2018 On-Premise release and a 6-monthly release cadence afterwards. So all improvements done in the current Business Central releases will make their way into On-Premise.

For more acute needs you can request the Events through regular support channel for NAV 2018. However, if you requested an event that was implemented in latest Business Central you can then safely add the exact same event in your Nav 2018 instance and you will know that this events is part of the standard codebase going forward.

**Comment by SirBETE** [comment]
What I question myself now is:
Why do we need to ask the NAV support guys to implement the events/fixes/changes we request here, if they will be included in the Fall 2018 On-Premise release?
If all improvements will be included in half a year time, why not include them directly and release them with every NAV CU?
We ask them, you create them in BC and give them through to the NAV team.
I wouldn't mind to wait another month if they will only be included in NAV the CU after BC gets them (offically).

**Comment by StanislawStempin** [comment]
@SirBETE - we are in discussion with the support team to see if we can optimize the process. 
From technical perspective the next On-Premise release is the same code branch in which we are doing the fixes right now so there is no additional work required. 
On the other hand to include fixes in the already released version requires re-implementing the same fix in a branch that diverged from the main branch in November 2017. That is why it requires an explicit request and approval process, we simply do not have capacity to do all fixes for all released versions. 

However, I fully understand the overhead from your side of having to log the same issue twice and we will see if we can fix that part.

**Comment by SirBETE** [comment]
Ahha Thank you Stanislaw.
Now I understand it :)
