### ISSUE TITLE
Error when Fields are added in the User Table

### ISSUE THREAD

**Issue by Chris-Dsilva** [Microsoft/AL#1810]
I've added three fields in the User table as an extension and created a Extesnion page for it as well. Whenenver I open the RTC error is thrown as below.
I'm using NAV 2018 CU 3 NA version.
![issue1](https://user-images.githubusercontent.com/24870777/37582658-07520806-2b74-11e8-97ae-b1780f09cad9.JPG)

attaching My Extension table and Page as well.
[Pictures.zip](https://github.com/Microsoft/AL/files/1824057/Pictures.zip)

**Comment by fvet** [comment]
Isn’t the User Setup table meant to be used for these cases?

**Comment by sgiordy** [comment]
Seems similar to my previous issue #1581

**Comment by HunterFeltman-MSFT** [comment]
Unfortunately there is no support for extending system tables with V2 extensions. The bug here is that you were able to get this far (compile + sync).

This restriction is because the Server (who owns these tables) can/does bypass user code when performing CRUD operations over the table data. The consequence of this is that you may end up with inconsistent data in your table extensions, especially so if you rely on triggers/events to fire.
