### ISSUE TITLE
[Off-Topic] Backport fix to NAV 2018

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/AL#1815]
Hello,

I've opened some issues that have been marked as "solved" but one of them was rejected because affects only NAV 2018 RTC. Other users here have their issues rejected for the same reason; other users again reclaim about solved fixes in NAV Cumulative Update, but the answer is: "there is no backport about these fixes, please open a support request through Partner Central".

Are you sure that you are doing the right thing?

Are you aware that most of the bugfix here are done by experienced partners with NAV 2018 version?

**If you don't backport the same fixes also in NAV Cumulative Update through this GitHub repository, will be soon no more interest by anyone in contributing this cause.**

Because we all aware that the future is D365BC but for now we are giving away our expertize to you, and you have to respect our time.

S.

**Comment by kalberes** [comment]
Hi,
We have a Customer Support & Service team with Escalation Engineers in charge of verifying and delegating request for hotfix issues to us on released NAV products. And a Sustained Engineering team providing hotfixes or delegating the issues to us if it is reproducible on the current release. 
We cannot just backport whatever we want even if it makes perfect sense. Things have to follow certain processes, validations, documentations etc.
This is why for the released Nav 2018 all issues have to go through the CSS team as it has been done on all other releases starting from NAV 3.70.

**Comment by sgiordy** [comment]
@kalberes I don't ask for a raw backport of all fixes to NAV 2018. I demand that the time that is spent here, is used also for NAV 2018. You can't  require from us to open issue here and also in Partner Central, following two different cases, two different support team. It does'nt have any sense.

See these issues for example: #1654, #1478, #1342
Are all platform issues, not application issues. Serious issues that affects client and development behaviour.
I hope that your **Customer Support & Service team with Escalation Engineers** will monitor and backport ASAP these fixes.

S.

**Comment by SirBETE** [comment]
#1806

**Comment by sgiordy** [comment]
#1650

**Comment by sgiordy** [comment]
#1286

**Comment by bwdeleeuw** [comment]
@dtacconi 

Your premise is that, because of the yearly release schedule of NAV, we should not expect new functionality before the new version is released. However, because of the introduction of Business Central, we are now seeing monthly releases of not just hotfixes, but also new functionality to the product. The problem here is that Business Central on-line gets monthly upgrades, even though there are only relatively few using that variant. Meanwhile, on-prem (current NAV 2018), has to wait 12 months to get upgrades, even though there are millions of users using on-prem versions of NAV. Now I'm not advocating monthly upgrades, but quarterly or bi-annually would be a better situation. Before this latest announcement, there would have been a release of NAV 2018 R2 this spring, which would have alleviated some of the hurt, but now that that is cancelled, we are once again having to wait a full year before we can use the new functionality. 

I think the channel has a hard time understanding why Microsoft is choosing to neglect their large and established customer base in this manner. I know I have difficulty explaining that to my customers. They feel that Microsoft insists on trying to push their customers to the cloud, as they have tried to with CRM, and with Office 365. The market is just not ready for it, and will start looking for alternatives, and Microsoft ends up having to scramble to release an on-prem version for their products, as they have done with CRM and Office. 

Having said that, I am not opposed to the cloud, and we use cloud extensively as a company. Our customers however, mainly large equipment manufacturers and job shops, have deliberately located themselves in areas where labor is cheap, and internet infrastructure is problematic, and they have no choice but to implement a on-prem solution.

**Comment by sgiordy** [comment]
Ciao @dtacconi 

please do not misunderstand my requests. I'm absolutely aware about D365BC, NAV 2018 and product lifecycle. I don't have any problem with cloud or on-premises version.

But I want to strongly report that now the expertise that allows you to improve D365BC come from NAV 2018 and from some partners like us that started with the new development environment.

What we have to do with new projects? Obviously we started to develop in new mode!
What we have to do with existing customers that we want to migrate to D365BC? Obviously we started to convert the code!

Waiting for D365BC, what we have to do with these bugs? Have you followed the issues? Error with user preferences, error with decimal fields, error publishing app, error with report...

You think that us can work in this way?

**I have no problem opening the same issues in Partner Central if you guarantee me that these issue will be considered. Because the last time that I've opened an issue in PC your colleagues wasted my time asking tons of proof, screenshots, demo database... with few or nothing result.** 

I think that will be more productive that one of your infinite human resources monitors this repository and reports and elects some issues to be backported.

Thank you
S.

**Comment by StanislawStempin** [comment]
Thank you for the feedback. We are aware of the differences in the GitHub support process for preview releases vs regular support process for the released versions. We are discussing what we can do to streamline the process of opening and auto-accepting support cases when a corresponding GitHub issue has been already accepted/fixed by us (product development team).

I would also like to say that we greatly appreciate all the product feedback that you and other partners are providing through GitHub. This is very helpful for us in the development of the latest version but it also helps uncover critical issues in the released version and we are committed to fixing these as well.

**Comment by sgiordy** [comment]
#1978

**Comment by sgiordy** [comment]
#1260

**Comment by sgiordy** [comment]
Today I have opened many **Request For Hotfix** into Partner Source, one RFH for every GitHub issue. If is not a problem please maintain alive this issue so it's more easy to track the requests. I have opened RFH only for platform related issues; for function expose and event request we are autonomous modifying the standard code. Thank you.

**Comment by dtacconi** [comment]
@GreatScott000 you must open a Support Request through the typical support channel (PartnerSource). CSS Engineer will evaluate your repro steps and if marked as an issue to be mitigated, CSS Engineer will escalate this request as RFH (Request For Hotfix). Give it a spin, bud :-)

**Comment by GreatScott000** [comment]
Okay but why do I have to use a paid support incident for a beta tool?

**Comment by dtacconi** [comment]
@GreatScott000 if CSS Engineer evaluate that this is an issue that needs to be amended then you will not be charged nor decremented of any Support Request. This is how Support Request channel works since decades :-)

**Comment by sgiordy** [comment]
Thank you @dtacconi 
#1650 and #1286 has been backported to NAV 2018 CU5

**Comment by sgiordy** [comment]
Many thanks to @dtacconi 

#1654 
#1478 
#1342 
#1978 
#1260

Will be backported in the upcoming NAV 2018 CU6.
