### ISSUE TITLE
Translation still not working

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/AL#1837]
Related to this one: https://github.com/Microsoft/AL/issues/1734
Also related to this one: https://github.com/Microsoft/AL/issues/1692

I'm now using build 21063, with AL 0.15.18566, the very latest build I could find.

I have my app.json set up for translation:
![image](https://user-images.githubusercontent.com/23434319/37734617-f815073a-2d08-11e8-9274-14c095fb4a74.png)

My workspace has a translation file:
![image](https://user-images.githubusercontent.com/23434319/37734636-01d51e72-2d09-11e8-99bc-f960b8bae1ea.png)

The captions are showing up in my dev instance, and also when I publish/install the app file in a separate container, but when I submit the app file it is rejected because they claim that there is no translation file. I'm obviously doing something wrong, but I think I am following all the instructions for the translation files. Am I missing something?

**Comment by TheDenSter** [comment]
Related question: is there a way for me to verify what is in the app file, so I can check it for the necessary translation file before it is submitted?

**Comment by MikeGlue** [comment]
I had this same issue for our app when we submitted. The reply I got back from Microsoft was that the auto-generated XLF file cannot be accepted as it does not contain the <target> tags that a full XLF file would normally contain. As they told me, the generated file should only be used as a source file not a target file, which is confusing since they recently added the source-language tag in the header of the file.

I've not had the chance to blog it yet, but what I did was take that auto-generated file, copy it (and rename to something like <appName>.en-US.xlf) and then open it in the Microsoft Multilingual Toolkit and translate it from en-US to en-US, which sounds weird, but the result of that is an XLF file that has the proper <source> and <target> tags in it and will be accepted by the AppSource validation team.

You can get the toolkit at the link below, and if you go through the process of hooking it up to a text translator service in Azure, then you can use the tool to generate the XLFs in any language!
https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit

**Comment by TheDenSter** [comment]
Ah alright now we're getting somewhere, I was actually told that the auto generated xlf file was acceptable for en-US and that I did not need to create one specifically for that language. 

Thanks Mike that's something I can try.

**Comment by DominikDitoIvosevic** [comment]
This issue has to do with the process of submitting the app and not with the development environment. At one point there was a request to add "target-language" to the generated file but that doesn't change anything with the compilation itself, it's just a cosmetic change. The restriction about having to submit specific set of translated files should not be discussed here. Please contact people related to submitting apps.

One thing to note:
The file generated by the compiler is a compiler output, not a file of your extension. It is not used during the compilation. If you want to use it in some shape or form you have to rename/copy it. It is merely a way to get the source translation items for your translation process.


The reason why the generated translation file doesn’t specify `<target>` in each of the translation items is because you cannot translate in this file since it’s overwritten on each run.
A simple thing to do (if someone doesn’t want to do proofreading or something else is to simply copy the file and just do a regex repace (below). Just use these expressions in vscode.

`(<source>([^<]*)</source>)`

`$1\n\t\t\t\t\t<target>$2</target>`

**Comment by TheDenSter** [comment]
I'm a little bit offended by your comment there. Here's a screenshot of the email where Microsoft tells me that the auto generated file is what they need
![image](https://user-images.githubusercontent.com/23434319/37790302-5a64a246-2dc3-11e8-9523-024ea6ec6901.png)
I can see it in my workspace, yet they are telling me it is not in the app file. How is that not about the compiler? How else can I interpret that except that something is wrong with the process of creating the app file? 

The documentation should be more specific about that the compiler will ignore translation files that do not have those target tags. Nobody ever said anything about those tags to me until today.

This has absolutely nothing to do with the submission process.

**Comment by MikeGlue** [comment]
I agree 100% with Daniel here. I was also quite surprised when our solution failed because of the "missing" en-US file. I don't quite understand why an auto-generated file that contains the tag of "target-language=en-US" does not actually conform to a usable file. Since the source = target in this scenario, why can't the compiler just add both the source and target tags throughout the file? I could still then take that file and change the target language and translate the file to override the existing en-US translations. 

If I was only publishing my app for the en-US language don't you think it would make sense that since the source language is already en-US, I shouldn't have to do any "translating"?

**Comment by TheDenSter** [comment]
That regex replace though, that is really cool :)

**Comment by TheDenSter** [comment]
Update: I used the regex replace and regenerated the app file and sent it to the validation guy, and again he says the translation file is not in there.

**Comment by MikeGlue** [comment]
I had to copy and rename the auto-generated file to <app name>.en-US.xlf before they would accept it. So, my submitted solution actually had 2 XLF files. One being the auto-generated one as-is, and the other being the copy that has the target tags in it and the new naming. Hope that helps!

**Comment by TheDenSter** [comment]
Another update: using the multilingual tool ended up being the magic bullet.

The only difference that I can tell is an attribute of the target node called 'state' that is set to "translated". Other than that, both versions of the xlf files are identical.

By the way, the translation folder in the app file does not include the standard g.xlf file, so that is definitely ignored somehow.

**Comment by DominikDitoIvosevic** [comment]
So the most important thing to note is that we generate the .g file for **you** and the compiler does not use it so it wont be visible in the package. If you change it's content it doesn't matter. What's important is to copy the file and give the copied file **some other name**. People usually go with `MyExtension.en-US.xlf`. 

The generate file is good enough buy you have to **give it another name**

**Comment by TheDenSter** [comment]
I DID copy/rename the g.xlf file (the OP, although my screenshot only shows the standard file so maybe that's why you think I didn't) and **it did not work**. Having a copy of the generated file was NOT good enough, it was ignored by the app building process.

I DID add the target nodes with your regex replace (my first update) and **it did not work**. Having the target nodes in there was not good enough, the file was ignored by the app building process.

What finally did work was the file created by the multilingual tool. I sent you both xlf files by email.

**Comment by TheDenSter** [comment]
Yes the app was submitted with the final translation file. Did you get my email and take a look at those files? I never heard back from you

**Comment by StanislawStempin** [comment]
Closing this issue as it got solved in an offline mail thread.
