### ISSUE TITLE
Question: Where to find a list of all events available for subscription

### ISSUE THREAD

**Issue by chris-amco** [Microsoft/AL#1838]
It's a really basic question and I'm sure I've missed something, but I can't seem to find a way to obtain a list of all objects than the events they publish, either through the VS Code AL addin or powershell applet.

Thanks in advance.
Chris

**Comment by qutreson** [comment]
Hi @chris-amco, when looking for the available events in an object, you can:
- use Go-To-Definition (F12) on the object you want in order to see which events are declared
- or, you can use Intellisense in order to have some suggestions after you have filled in the object type and the object ID 

We recently made some improvements on the latter scenario which will be available in the next update (see issues #149 and #1534).

**Comment by chris-amco** [comment]
Thank you. Is there a way to browse through a list of all the objects, so that I can select one and press F12?
For now, I've installed [AL Code Outline](https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline#overview), which lets me browse the object list and view the object definitions.

**Comment by qutreson** [comment]
For now, the AL extension does not provide a way to browse through the list of all the objects, but it is something we have on our backlog.
