### ISSUE TITLE
Ambiguous object reference

### ISSUE THREAD

**Issue by NavBitsAndBytes** [Microsoft/AL#184]
Are we allowed to access any system tables? Any time I try I get the same error:

The following example results in the error below:

page 70000000 "Test Page"
{
  Editable=false;
  PageType=List;
  SourceTable=Field;
  ...
}

'Reference to object field is ambiguous. Make sure you are not referencing packages containing objects with the same names.'

**Comment by kalberes** [comment]
Hi 
You should not be able access the Field virtual table for Extension development, since it may be crossing tenant boundaries. But you should get a clear error message on that. Something like 'The type or method 'Field' cannot be used for 'Extension' development.'
What you see here is probably a bug. Somewhere else. The compiler gets confused on using the Field keyword in a property binding context.

**Comment by atoader** [comment]
@NavBitsAndBytes This is a bug. We've fixed and it should ship in the May update.
