### ISSUE TITLE
ApplicationArea: How to create new setups

### ISSUE THREAD

**Issue by LauraNicolas** [Microsoft/AL#1841]
Hello,

I am developing an extension and assigning my own ApplicationArea to controls. I am following this documentation: https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-extending-application-areas

The "Application Area Setup" table contains the following fields in its primary key:
- Company Name
- Profile ID
- User ID

I understand then that I can use different applications areas per diferents companies, profiles or even per user.

My question is: **where is the setup done**?

We only have page 9179 Application Area, but it is not editable. I cannot find any other place where I can setup applications areas per user. 

Thanks for your feedback.

Salut!
Laura Nicolàs

**Comment by qutreson** [comment]
Hi @LauraNicolas,
For now, we only provide the ability to set application areas per company. We don't support it directly for users and for profiles and currently don't have any plans on making it available. 
The management of application areas is made in the Codeunit 1 (Application Management), this is where the application areas are set per session at logon. When a user logs on, this codeunit is read and gives the server the list of application area to enable for the current session. If you want to have a behavior dedicated per profile and user, you should investigate this codeunit and modify it in order to enable the scenarios you mentioned.

**Comment by LauraNicolas** [comment]
Thanks @qutreson ,

I guess this could be a topic for an extension .-)


To me, being able to assign ApplicationAreas per user solves (or could be used to solve) an important issue: **_Permissions per role/user_.**

Right now, if you assign a write permission to the Item table to a warehouse employee, he/she can change anything, also postings groups. Someone could argue that warehouse employees should not be able to modify accounting-related information. And they are probrarbly right.

With AppAreas, this problem can be solved. I can easily hide certain fields, based on peoples role.
I would rather be able to choose if it has to be hidden, or just not editable, but it is better than nothing.

Salut!
Laura Nicolàs
