### ISSUE TITLE
License range invalid with the new version?

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#1856]
With the newly released version of Dynamics 365 BC, the area to be developed from our license no longer works. In February it was possible to publish objects in this number range without any problems. But now this is no longer possible. Instead, development must take place in the 50000 range.

We were assigned this number range for publication on the AppSource. Do we need to re-download the license, or activate anything that allows us to continue working in this number range?

`error PTE0001: TableExtension 'Test' has an ID of [701?????]. It must be between 50000 and 50099.`

**Comment by tfenster** [comment]
I am seeing the same, but only if I enable the PerTenantExtensionCop code analyzer. If I remove that, it works fine for me

**Comment by FSharpCSharp** [comment]
@tfenster Thanks for the advice! The function I had indeed active, and that has led to the behavior. Is that a mistake, or is that the way it's supposed to be?

**Comment by tfenster** [comment]
@FSharpCSharp My guess would be that it's not checking the idRange in app.json and therefore is a bug, but then I have absolutely no internal knowledge on this and might very well be wrong. Let's wait for @kalberes and @StanislawStempin, they only have this for less than a day

**Comment by ajkauffmann** [comment]
I think there are two issues:
1) Do not use AppSourceCop and PerTenantExtensionCop together
2) Error message is wrong, it actually checks if your object is between 50000 and 99999.

**Comment by kalberes** [comment]
It is a bug.

**Comment by kine** [comment]
I think it is same like that it is testing field IDs in my own table and is forcing them to be "50000" to "50099" when using CodeCop.

**Comment by FSharpCSharp** [comment]
That's good to know it's just a bug. I was afraid that something had changed in the licensing model and I had not noticed it. I am reassured that this problem affects others.

**Comment by StanislawStempin** [comment]
As you might have noticed the error is originating not from the compiler itself by from a static code analyzer. In this case PerTenantCop. That analyzer should be enabled only if your project is meant to be a per tenant extension i.e. tenant customization. These can only be done in the 50K-99K range. (The error message was indeed wrong as it should say 50000-99999 and that will be fixed in the next update).
CodeCop also performs additional ID checks for table extension fields. They have to be in the idRange specified in app.json. This is to avoid field ID conflicts between different extensions.

**Comment by tfenster** [comment]
@StanislawStempin Why can't we use our license range in per tenant customizations?

**Comment by ajkauffmann** [comment]
@tfenster I think you can use your own license range?

**Comment by tfenster** [comment]
@ajkauffmann I interpreted @StanislawStempin message that we can't?

> That analyzer should be enabled only if your project is meant to be a per tenant extension i.e. tenant customization. These can only be done in the 50K-99K range.

**Comment by StanislawStempin** [comment]
As far as I understand this is because tenant customizations should be owned by the customer and the customer themself or another partner should be able to take over the customizations. If they were done in a proprietary range then it wouldn't be possible. 
Which other range would you use for one-off tenant customizations? 1-60M is meant for repeatable ISV solutions (practically for Business Central that means AppSource) and 70-75m is meant for AppSource apps only.

**Comment by tfenster** [comment]
@StanislawStempin Not sure how much of a typical scenario that is but we have a quite big vertical and can't add everything a customer wants to our "standard". Therefore we have a dedicated team working on individualization who create specific stuff for individual customers but also maintain those objects if we deliver new releases of our vertical and legally it is our IP. Therefore we are using our ISV range for those objects as well. That has worked very well for the last couple of years (and really not so well while we still were using 50.000-range objects), so we'd like to bring that mode of delivering individual objects to BC as well.

Makes sense?

**Comment by StanislawStempin** [comment]
Makes sense. I brought it up with the team responsible for this area and will update the thread once I hear more.

**Comment by larswestman** [comment]
@StanislawStempin  Do we have any news on this topic?

**Comment by StanislawStempin** [comment]
This is still under consideration. Any changes to this approach will be communicated in Directions licensing sessions and/or official Microsoft blogs. I will close the issue here.
