### ISSUE TITLE
Code Analysis and Hidden Rules

### ISSUE THREAD

**Issue by ShadowXVII** [Microsoft/AL#1867]
A rule with an action of "hidden" still shows in the Problems list within Visual Studio Code.
I'd only expect to see Error | Warning | Info and their associated icons.

```
        {
            "id": "AA0008",
            "action": "Hidden"
        }
```

![image](https://user-images.githubusercontent.com/446329/37941852-0e53f256-31bc-11e8-9b12-d142f8152faa.png)

:white_check_mark: It doesn't appear in Output/Compiler as an error.
:white_check_mark: It doesn't show hidden rule violations underlined in the Code view.

AL Language version 0.15.18771.

**Comment by qutreson** [comment]
Hi @ShadowXVII, did you try to recompile and reload the window? 
This is needed because the AL extension does not detect changes on the rulesets until you do so (see the **Limitations** section in [Using the Code Analysis Tools with the Ruleset](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool-with-rule-set)).

**Comment by ShadowXVII** [comment]
Hi @Qutreson, yes followed that gotcha. I tested by making the rules "error" instead of "hidden", save, compile, reload, and their icon changed.

**Comment by qutreson** [comment]
I think I misunderstood your message at first, sorry. When using the action `Hidden`, the diagnostics still shows in the Problems list, it is by design. If you don't want to see it there, you should use the action `None` instead.

**Comment by ShadowXVII** [comment]
Hmm. I thought I tried None too. I'll try again.

**Comment by ShadowXVII** [comment]
Ah, None was the first one I tried (thinking it'd do what I needed) but didn't have the "save > build > reload" process down pat to test.

Perhaps the documentation should clarify the actual behaviour of Hidden and None.

Thanks!
