### ISSUE TITLE
[Question] Default Tiles List view in WebClient

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/AL#1875]
The customer List shows tiles as default. I want to do the same with my own List Page; but i have yet to find the property for this.
What am I missing?

**Comment by StanislawStempin** [comment]
Hi,

There is no such property because the platform automatically determines the best possible starting view mode of the list. However, users can change their preferred mode at any time and this is remembered on that device even the next time they sign in.

On desktops (browser, Win10 app), the staring mode of a list is determined by the presence of thumbnails. If the source table has a ***brick*** field group defined which includes a field of datatype Media, and a percentage of the records on the screen have image thumbnails, then the list will initially be displayed as tiles. 

See this doc from Dynamics NAV 2018 for reference, although it doesn't mention the detailed algorithm that the platform applies to determine starting mode, since that cannot be explicitly set by developers: https://docs.microsoft.com/en-us/dynamics-nav/how-to--display-data-as-bricks
