### ISSUE TITLE
Transfer Order Direct Post Error

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/AL#1876]
When posting from a Transfer Order with Direct Transfer and  Inventory Setup of Location Mandatory you get an error requiring "New location Code must have a value".  This is in NAV2018 CU2

![image](https://user-images.githubusercontent.com/32099690/38071125-63085710-32d4-11e8-84e8-5f9ad0394d51.png)

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
