### ISSUE TITLE
Txt2AL --Rename Suggestion

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#1909]
It would be nice if the --Rename parameter of txt2al had some options.  My personal preference is to have my AL files be just the name of object (e.g. My Table.al) and not the object ID object name (e.g. Table 50000 - My Table.al).  And it would be nice to have the modifications (PageExtensions, TableExtension e.g. Modification  - Customer List(Page 22).al) to be just just simplified too (e.g. Customer List Ext.al).

I am sure others have other thoughts on what options might be useful.

For now, I am probably just going to use Powershell to script the names I want.

**Comment by MikeGlue** [comment]
I believe that the tool names the files based on the best practices that Microsoft is trying to layout for developers to follow:
https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode

Now, with that being said, I'm not the biggest fan of putting the object numbers into the file name. The table and page extension file naming to me is difficult to understand without knowing what each object number is. I agree with you that something like "Customer Card Extension.al" to me is a much better format.

**Comment by lvanvugt** [comment]
I think it's great to support different flavors.
At the moment mine is like this (am still somewhat experimenting):

- TABid_TabelName.al

- TEXid_OriginalTableNameExt.al

- PAGid_PageName.al

- PEXid_OriginalPageNameExt.al

- CODid_CodeunitName.al

- ... etc ...

I started using only the object names in the file name, and found it exposing to little info on the outside, partly because I prefer to have all the .al files at root level not using sub-folders.
In a way you could say I am close to what is suggest on https://docs.microsoft.com/en-us/dynamics-nav/compliance/apptest-bestpracticesforalcode.

**Comment by StanislawStempin** [comment]
We are currently not planning to add more variety to the converted tool. However, there are already 3rd party VS Code extensions out there that can do file renaming, for example: https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension
I think right now it renames the same as txt2al but this is a good area for more 3rd party contributions.
