### ISSUE TITLE
Unable to browse the web service url in browser

### ISSUE THREAD

**Issue by srinivasdes** [Microsoft/AL#1922]
Hi,

We unable to browse the web service url in browser. Giving the error {"message":"Unauthorized"}

We noticed our sandbox environment has upgraded to new business central environment and soap url format is different from the old

Current AL version is 0.15.18771

PFA

Can anyone please help me what i am missing. and is there any documentation regarding web service changes?

Thanks

![4d74e974](https://user-images.githubusercontent.com/35101458/38325830-c9786cd2-3861-11e8-8acf-ee524f1f51c4.PNG)

**Comment by dennisfrostlander** [comment]
https://api.businesscentral.dynamics.com cannot be accessed from the browser.
This REST API is meant to be used programmatically, specifically an Authorization HTTP header must be sent with the Bearer JWT access token or Basic credentials.

On the server itself, I don't think there have been any changes related to web services.

Are you able to access the web services in code? If not, could you provide the error details that you get in your program?

**Comment by naveenpinnama** [comment]
Looks like the soap urls or changed to rest api. Are the old soap urls with port number still supported in BC??

**Comment by dennisfrostlander** [comment]
Yes, old SOAP urls are still supported, but it is encouraged to switch to the new https://api.businesscentral.dynamics.com urls.

**Comment by naveenpinnama** [comment]
Thanks Dennis. Any idea until when the old SOAP urls will be supported?
Are the new APIs Soap or rest based and will both page and codeunit services supported?

**Comment by StanislawStempin** [comment]
Could you give us some examples of URLs which were SOAP based before and now became REST API based?

**Comment by naveenpinnama** [comment]
Hi 

Looks like in Business central the Soap services URL format is changed from NAV Soap services URL to REST API.

IN BC: Are webservices soap based or rest based? Because the authentication method is changed and Dennis in earlier post mentioned these are REST API. 
SOAP URL
https://api.businesscentral.dynamics.com/v1.0/5db49010-0f87-4ff9-98f9-a0b33a40e46a/sandbox/WS/CRONUS%20USA%2C%20Inc./Page/Chart_of_Accounts

SOAP URL
IN NAV 2018 or old D365 Finance and Operation.
https://tenantname.financials.dynamics.com:7047/MS/WS/CRONUS%20US/Page/Chart_of_Accounts?tenant=tenantname.financials.dynamics.com

We are not able to add BC urls in .net web or service reference. I was able to open with postman tool.

Thanks

**Comment by StanislawStempin** [comment]
Closing, since #1933 continues the thread.

**Comment by Bhawan-Bhangu** [comment]
I'm getting the same issue. I get unauthorized error.Should I be the admin?
