### ISSUE TITLE
CodeCop warns about using parenthesis but gives an error when I do

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#1939]
Using property Page of a page part, I get the warning from CodeCop to use parenthesis:

![image](https://user-images.githubusercontent.com/19155831/38393340-c88fe574-392a-11e8-9cb3-f4d67cabf2fe.png)

But when I do that, I get an error message that I use the property Page as a function:

![image](https://user-images.githubusercontent.com/19155831/38393365-d9192a22-392a-11e8-8754-99725a4bf2cb.png)

In general, I'm not happy with the many, many places that are treated by CodeCop as a function while it is not really a function. For example RecRef.Number. Is that a function? Not to me, but CodeCop advises to use parenthesis.

**Comment by qutreson** [comment]
Hi @ajkauffmann, the error with Page seen as a method has already been reported in #1861 and has been fixed in our code base. Concerning RecRef.Number, even if it can look like the concept of property in some other languages, this is actually a procedure in AL, so it should be used with parenthesis if no arguments are specified.
