### ISSUE TITLE
AL Formatter: convert all uppercasing

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#1957]
Please make the AL Formatter change the casing to the right one:

- for system functions: upper camel casing
- for AL keywords: lower casing
- ... and maybe some others I am missing

So when you type system functions or AL keywords in whatever casing it will not be corrected by the AL Formatter.
In C/SIDE this would be done when closing and reopening an object in design mode and opening the C/AL Editor (or based o whatever trigger).

**Comment by StanislawStempin** [comment]
This is similar to #1923 
We will most likely not fix the formatter itself but rather the txt2al conversion tool.

**Comment by lvanvugt** [comment]
> ... so it's primarily an issue of the converted legacy code.

Disagree, Stan. If I am typing without using Intellisense it will not be corrected. Take "if". I am not using Intellisense for that. So if I type IF it will not corrected.

**Comment by StanislawStempin** [comment]
We have fixed the C/SIDE ExportToNewSyntax to convert all the keywords to lowercase as well as to convert all system function calls to CamelCase.
We are currently not planning to change the formatter to fix the wrong casing as this is outside of the scope of the formatter and since Intellisense suggests the correct casing, usage of uppercase should decrease over time.
On top of that there are 3rd party extensions that fix the casing, and it will also be possible to implement CodeCop rule that checks for it.
