### ISSUE TITLE
Suggestion: AL Symbol Menu

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#1958]
Indeed Intellisense is a great feature, not in the least its context sensitivity. However, it's often still an overload of terms in the drop down list that's not logically (except for alphabetically) ordered.
The C/AL Symbol Menu does present the various methods and fields in a categorized way, so that you have an overview of related things.
So the suggestions is to provide, next to Intellisense a categorized display of terms (functions, keywords, fields and properties) to make the developers works much easier.

Note that with properties in the Intellisense drop down there's even a vaster amount of terms shown.

**Comment by StanislawStempin** [comment]
This is to a large degree controlled by VS Code. The compiler provides a list of symbols fitting the given context and we can only control the icon of the symbol, sort order, display text and the actual insertion text. 
We will see what we can do to provide more information in line with your suggestion.

**Comment by JavierFuentes** [comment]
I agree with @lvanvugt, 
when developing with Object Designer in the traditional way, developers know __the context__ in which we are at all times making our changes and we have all the possibilities in sight and within our reach ... __with the new paradigm of programming in Visual Studio Code, this has been completely lost__ ...

Would not it have been more logical to improve the Object Designer so that all customizations could continue to be done in a similar way but stored in the DB separately?

The only thing that should be done is to protect the standard code so as not to allow it to be modified but to continue being able to read everything it does to know where to fit our code using the subscriptions to events ...

Once this is achieved, the next thing is that you could export the DIFF of the modified objects directly and automatically in AL format in order to have the changes in a repository version ...

**Comment by thpeder** [comment]
Hi, Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
