### ISSUE TITLE
No intellisense for objectID and Event Name in Events Subscribing codeunit.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#1989]
In VScode , when we subscribe some events from any of standard object (Page etc.). Then there is no suggestion list show for selecting the appropriate event. How can we know that what events were exposed with this object in base?
It is possible to check what events exposed, with help of C/AL environment going to any of function property.

Let suppose I only knows object name as in VScode its only shows objects name. Then there is no suggestion after typing Object Name.
![image](https://user-images.githubusercontent.com/33481576/38610796-8c968068-3d9f-11e8-9127-ff056a58038f.png)
 Next, Somehow I managed with object ID as I am working with NAV since last 3 years. Then how I know about events Name?
![image](https://user-images.githubusercontent.com/33481576/38610908-e666ca26-3d9f-11e8-9125-0badf13caf1f.png)

Correct me, if I m wrong.

**Comment by qutreson** [comment]
Hi @SUD-D365, we made some work to improve the experience around EventSubscribers (see #149 and #1534).

Also in order to reference the publishing object by name and not by ID, you have to use `Database::Customer`. Once you have provided the type of object you are looking for, intellisense will suggest you the object names. Note that for tables, you have to use `Database::`.
