### ISSUE TITLE
Database consistency with extensions

### ISSUE THREAD

**Issue by sgiordy** [microsoft/AL#2081]
Hello

imagine this scenario:
- an extension add financial features to a database
- one of this features is an additional ledger table
- the extension is temporarily uninstalled and next reinstalled
- RESULT: the database is inconsistent

It's obvious that installing/uninstalling the extensions is an administrative task, but which are the recommendations to keep the database consistent? Will be there a "maintenance mode"? Will be possible to declare some extensions as mandatory, so if these are missing the database will not start?

Thank you
S.

**Comment by HunterFeltman-MSFT** [comment]
Hey @sgiordy 

Let me try to take a first crack at your questions:

Due to the fundamental nature of extension to be 'disabled' when they are uninstalled, the platform takes limited action upon reinstall to help with data consistency problem. For the large part, this responsibly falls on the code within the extension to satisfy it's own state.

Here's what happens from a platform perspective with respect data in schema elements:
1. Added Full tables
    - Nothing, data here is left 'as is' upon reinstall and is entirely within the responsibility of the extension code to ensure state

2. Added Table Extensions
    - Primary key based sync. Upon reinstall the platform analyzes table extension and the tables that they extend and then updates the relevant table extension SQL table so that it 'matches' the base table.
I.E. If the base table is missing rows with primary keys that the extension has, then the row is deleted from the extension. Similarly, if the base table contains rows with primary keys that the extension is missing, then the row is inserted (with default values) into the extension.

It is then after this 'clean up' that the extension install/upgrade code is executed and it the responsibility of this code to ensure that the database is left in an acceptable/consistent state.

Extensions have neither a concept of a 'maintenance mode' nor a way to declare themselves as 'mandatory', and these things are not currently planned to be incorporated into the platform.

These notions should be accomplished by understanding between the extension developer and the administrator installing the extension as to the proper/expected usage of the extension. Modifying or adding critical core features (such as ledger) should be made very apparent to those who would use the extension. 
Ideally, extensions should be developed such that temporary uninstallation and base application usage is handled. If not then at the very least administrators should be informed, via documentation, agreements, big flashing warnings, etc, of these/any special considerations surrounding the extension.

**Comment by sgiordy** [comment]
Hi @HunterFeltman-MSFT 

thank you for reply. I agree with your considerations:

> These notions should be accomplished by understanding between the extension developer and the administrator installing the extension as to the proper/expected usage of the extension. Modifying or adding critical core features (such as ledger) should be made very apparent to those who would use the extension.

but we come from NAV where Client UI and Development Environment are clearly separated. Now from the "Extensions" page is very easy from everyone (ok ok with right permissions) to uninstall an app.

Extensions will become the new way to develop for us and some apps will be critical. 

I hope you consider this request as a suggestion for a future release:

- Every app has an unique GUID
- A system table can store which GUID are mandatory and the minimum version accepted
- If the app is not installed, the application server refuse client connections until the system administrator does not resolve the issue via PowerShell or maintenance page

S.

**Comment by sgiordy** [comment]
I found RequiredExtensions property in BC V15 "Wave 2"

**Comment by atoader** [comment]
Thank you for closing the issue @sgiordy ! You are right, that property can be used to configure the system to prevent the uninstallation of a set of extensions.
