### ISSUE TITLE
Extensibility of Control Actions

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/AL#2087]
Download symbols doesn`t add control actions of cuegroups. So it isn't possible to change the (visible) property of this controle actions.

some back-ground info: for an app I have to modify the report:"Aged Accounts Receivable". So I have copied this report and applied the code changes. Next steps is to set visible property to false for all page and controle actions calling the original nav report. Then added a controle / page actions which will call my copy report. 
Report:"Aged Accounts Receivable" is called from a control action in Page:9025:"Small Business Report Catalog"

**Comment by qutreson** [comment]
Hi @Pieterheinevdm, the actions contained in cue groups are actually downloaded with the symbols, the source symbol viewer (Go-To-Definition) was just not handling them. We fixed it so that they are now displayed in source pages.

![image](https://user-images.githubusercontent.com/31541422/39617585-8d8fbe9c-4f80-11e8-92fc-3b3608a09320.png)

Concerning the modification of actions in cue groups, this scenario is currently not supported by the compiler and by the platform. It is something we consider enabling in the future, but we don't have a time estimation for it yet. 

We will keep this thread for tracking the cue action extensibility topic.

**Comment by thpeder** [comment]
Hi,
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
