### ISSUE TITLE
Obsolete field and the command line compiler

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/AL#2092]
If I have an extension depending on a tablefield which is marked as Obsolete (Pending), I get that as a Problem in VS Code. However the command line compiler alc is creating the .app file anyway.

For SourceControl Integration, it would be good, if it'd fail also with the command line compiler.

**Comment by qutreson** [comment]
Hi @janhofmann24, using a field with ' Pending' state only results in a warning in VS Code and not in an error, so you should be able to create the .app file anyway (except if you have some ruleset or analyzers that are reporting an error for it).
The alc compiler from command line and VS Code should be returning the same errors and warnings. However, you need to verify that both have the same settings in order to get the same result. You can know more about the alc compiler by running `alc.exe -help`.

**Comment by qutreson** [comment]
@janhofmann24, I am still not sure I understand what the issue is here.

When using a table field which has the property `Obsolete` set to:
- `Pending` a Warning diagnostic is generated in the compiler and the .app can still be created,
- `Obsolete` an Error diagnostic is generated in the compiler and the .app can no longer be created as it is an error to use an obsolete field. 

You can see it in VS Code here:
![image](https://user-images.githubusercontent.com/31541422/39564253-bfb587d0-4eb3-11e8-9e10-3bebff358d79.png)
```
Microsoft (R) AL Compiler version 0.15.0.0
Copyright (C) Microsoft Corporation. All rights reserved

c:\Users\qutreson\Documents\AL\EmptyPage\obsolete.al(29,37): warning AL0432: Field 'PendingField' is marked for removal. Reason: Not needed anymore, so will be removed.
c:\Users\qutreson\Documents\AL\EmptyPage\obsolete.al(31,37): error AL0433: Field 'RemovedField' is removed. Reason: Not needed anymore, so is removed.
Error: The package could not be created.
```

I get similar results when using it in PS:
```
alc.exe -Project:"C:\Users\qutreson\Documents\AL\Project1" -PackageCachePath:"C:\Users\qutreson\Documents\AL\Project1\.alpackages"

Microsoft (R) AL Compiler version 0.15.0.0
Copyright (C) Microsoft Corporation. All rights reserved

C:\Users\qutreson\Documents\AL\EmptyPage\obsolete.al(29,37): warning AL0432: Field 'PendingField' is marked for removal. Reason: Not needed anymore, so will be removed.
C:\Users\qutreson\Documents\AL\EmptyPage\obsolete.al(31,37): error AL0433: Field 'RemovedField' is removed. Reason: Not needed anymore, so is removed.
```

Even if the alc.exe does not explicitly tell in the console log if the creation of the package succeeded or not, the .app package does not get created in both cases as there is an error in the project.
