### ISSUE TITLE
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/AL#2123]
Using BCSandbox 21229. AL objects were created from C/SIDE using Convert-ModifiedObjectsToAL from navcontainerhelper.
For several days I was able to work normally in VSCode, fixing numerous issues. Then we added our required prefixes to fields and tables, replaced files with streams, deleted some .NET functions which were not required for the app etc. and started a new project.

Now, when I try to a compile the 209 objects, this comes up:
Microsoft (R) AL Compiler version 0.15.18771
error AL0999: Internal error: 'One or more errors occurred', Stack trace=unknown
Error: The package could not be created

Before this the Pre-Compiler shows no problems at all, but that is extremely fluctuating. Can be anything between 0 and 45, the latter number appears to be correct, so there are some things which need to fixed but these are not indicated anymore.
Sometimes when I click on an object in the left pane, the issues suddenly show up for that object.
When I click into the object to fix the first one, all issues suddenly disappear again even though they are still there.

I've tried 
- using the VSIX from the container 15.18771
- using the VSIX from marketplace , also 15.18771 (after uninstalling I also deleted all extension files in the user directory) 
- Switching codelens off/on
- running VSCode as administrator
- changing locale from 'de' to 'en'

So far nothing has helped.

**Comment by kalberes** [comment]
When you say the app won't compile are you trying to compile with Ctrl Shift B, or you are trying to publish with Ctrl F5, or F5. Is it the latter that produces the error? What was not clear for me whether you are trying to publish against a BC sandbox tenant, or a docker based server? If the latter you may have more info in the server eventviewer logs.

**Comment by Kowa63** [comment]
> are you trying to compile with Ctrl Shift B, or you are trying to publish with Ctrl F5, or F5.
Yes, Ctrl+Shift+B. Ctrl+F5 and F5 also yield the same error.
The pre-compiler states "No problems in the workspace" and the attempt to compile with Ctrl+Shift+B leads to error AL0999.
Technically the setup works for small sample projects using my environment and the same container. I have one snippet app with only 5 objects which I can compile and publish instantly to the database in the container.

**Comment by dennisfrostlander** [comment]
Thank you for finding the root cause! We really appreciate your time on this.
We are definitely fixing this issue and at the same time improving the error reporting for this scenario.

**Comment by ajkauffmann** [comment]
One extra comment: this line with ValuesAllowed comes originally from C/AL code and was converted with Txt2AL. So I suggest you also look at the converter to avoid future problems with this property.

**Comment by Kowa63** [comment]
@ajkauffmann, who happened to conduct a workshop this week with some of my co-workers found the cause, I didn't. 
The converter indeed is also buggy here, the field delimiters were missing altogether after the conversion, probably due to the first allowed value being blank.

**Comment by dennisfrostlander** [comment]
Hi @Kowa63, in your example `ValuesAllowed = ',ABC,DEF'`, what are you using as the data type for the field? Is it an option or a text/code?

**Comment by Kowa63** [comment]
Hi @dennisfrostlander, it is a Code [4] field, the real values are these SEPA mandate codes:
`ValuesAllowed = ',FRST,RCUR,FNAL,OOFF';`

**Comment by dennisfrostlander** [comment]
Hmm, but in this case, wouldn't it be easier to use an Option type instead of Code[4]?

The reason I am asking is because we also have the issue with converting the ValuesAllowed property using txt2al tool, as @ajkauffmann has mentioned. Namely, if ValuesAllowed is used on a text/code field, then quoting could be wrong as you have experienced - text/code has to be quoted with single quotes, options - with double quotes.

However, using ValuesAllowed with a text/code field does not seem to be the common case, and investment into putting the correct quotes is (surprisingly) high, so we are considering not to fix the quoting conversion issue.
 
From the user perspective, doesn't it feel a little strange when you are presented with a free-text input field, but then it turns out that you are allowed to type only ABC or DEF? 

P.S. If you still want to keep the text field, then `',FRST,RCUR,FNAL,OOFF'` does not seem to be right. This would mean that the user has to type literally the whole string. To separate the values, you'd have to put `'FRST', 'RCUR'`, etc (this also has some issues in the new compiler, which are being addressed). 

And speaking about the first empty value, could you let me know how you did it in C/SIDE? Was it just `;FRST;RCUR;FNAL;OOFF`? I can't make C/SIDE to allow me the empty field value... If I touch a field, then I can't leave it empty and need to choose one of non-empty values.

**Comment by Kowa63** [comment]
Hi @dennisfrostlander, 
the values in this field are usually assigned via other code bits or coupled to data being entered in other fields, not entered manually by the user. The ValuesAllowed property is mainly a precaution prevent false data being assigned from other functions.

Of course you could use an option field here as well, but it was programmed that way years ago when SEPA was introduced and has been in active use since then. Millions of payment files have been produced that way. In one payment run you may need to produce up to 4 payment files, each with a separate SEPA mandate sequence type. All of this would need to be refactored.

Apart from this, ValuesAllowed may be used for all kinds of purposes too, so issues like this can come up at any time and the converter should cope with these.

When the object is exported from C/SIDE the line looks like this
`ValuesAllowed=["";FRST;RCUR;FNAL;OOFF]`
and directly in C/SIDE like this
`"";FRST;RCUR;FNAL;OOFF`

**Comment by dennisfrostlander** [comment]
Thanks for the explanation.

Just to clarify, when we say _issues like this_ this most certainly does not mean a compiler crash like you have experienced, giving you no clue what to do next. Assuming the crash is fixed, the result of the "wrong" txt2al conversion will either be an AL file with a compilation error or with a commented out ValuesAllowed property with a TODO above. This way it will require a one-time clear effort on upgrading the code to V2. Just wanted to clarify that.

Nevertheless, let me maybe open a new issue on the txt2al conversion of code/text fields to keep the feedback separately from the crash.
