### ISSUE TITLE
AL HttpContent type should detect format of contents and set header Content-Type accordingly

### ISSUE THREAD

**Issue by quadfin** [microsoft/AL#2142]
When creating a POST message with JSON content you have to set the Content-Type with this cumbersome code
        httpContent.WriteFrom(jsonText);  // write some json into the httpContent object
        httpContent.GetHeaders(httpHeaders);  // replace the Content-Type header 'cuz its wrong
        if (httpHeaders.Contains('Content-Type') and httpHeaders.Remove('Content-Type')) then
          httpHeaders.Add('Content-Type', 'application/json');

Would be nice if httpContent detected the format of its contents and auto-managed headers

**Comment by DominikDitoIvosevic** [comment]
The reason why we did the interface like this is because we wanted to keep things as simple as possible. You can always write your own 2-3 helper methods for these scenarios and all it costs you is 2 minutes of your development time. We will consider improving these scenarios for the future but it's not a priority right now.

**Comment by thpeder** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
