### ISSUE TITLE
How to use camera features without .Net?

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/AL#215]
We are using the device camera in our extension. Is there a solution coming that will allow us to do that, since the current solution uses a .Net library?

**Comment by StanislawStempin** [comment]
This functionality is not supported yet due to removal of .NET interop. It will be enabled in the future after we add back support for client add-ins that do not rely on .NET.

**Comment by unnur** [comment]
We are using this as well - do you know when this is planned to be supported?

**Comment by MikeGlue** [comment]
Now that javascript addins are supported, any update on the timeline for using the built-in NAV addins?

**Comment by StanislawStempin** [comment]
We are actively working on WebPageViewer and Camera. They should be available publicly in December Update.

**Comment by dennisfrostlander** [comment]
@MikeGlue @unnur 
For the camera support, would it be an acceptable solution to have an intermediate generic page which would take the picture and provide the result stream/blob back to the caller? 
Kind of C/AL wrapper, but using a page instead of a codeunit. The calling code could call RunModal and the page can request a picture on page open and close itself when the picture is ready. 
This way it should take the same number of clicks to obtain a picture from the camera, and the remaining inconvenience would be an extra page being displayed...

**Comment by MikeGlue** [comment]
That sounds like a viable solution I think. As you said though, as long as the number of clicks doesn't increase so that it remains easy to use.

**Comment by unnur** [comment]
Sounds like a good solution to us.
