### ISSUE TITLE
Special Characters in names of parameters in EventSubscriber

### ISSUE THREAD

**Issue by HBerndV** [Microsoft/AL#2173]
There is a bug with special characters like **äöü** in names of parameters in EventPublisher/EventSubscriber using Extension V2.0.
For example:
    [EventSubscriber(ObjectType::Codeunit, 71080, 'OnPublishOneParam', '', false, false)]
     procedure OnPublishOneParam(var **ParamWithä** : Boolean);

causes “ErrorParameterMismatch” in the event subscriber overview and the event is not active.

We are using CU3.

**Comment by thpeder** [comment]
Hi @HBerndV,
I created a small example and it works for me.
Could you explain some more about your setup?
Where are the event defined?
```
codeunit 50110 MyCodeunit
{
    [IntegrationEvent(true,true)]
    procedure PlainProcedure(var ParamWithäöü : Boolean)
    begin
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::MyCodeunit, 'PlainProcedure', '', false, false)]
    local procedure PlainProcedureSub(var ParamWithäöü: Boolean)
    begin
        Message('Hit!');
    end;
}
```

**Comment by MBGWS** [comment]
Hi @thpeder , 

you have to define the Event in the base app

Create a new Codeunit in the Dev. Env. that publishes two Events, on with german umlaut, one without

Codeunit 50000 in Dev. Env. NAV 2018 CU 5
OnRun()
lParam := TRUE;
OnPublishNextParam(lParam);
OnPublishOneParamCodeunit50902(lParam);
MESSAGE('done');

[External] [BusinessEvent] OnPublishOneParamCodeunit50902(VAR ParamWithä : Boolean)
[External] [BusinessEvent] OnPublishNextParam(VAR pParamä : Boolean)

Then define in AL a Codeunit that subcribes both Events


codeunit 50103 CodeunitWithEvent
{
    EventSubscriberInstance=StaticAutomatic;

    trigger OnRun();
    begin

    end;

    [EventSubscriber(ObjectType::Codeunit, 50902, 'OnPublishOneParamCodeunit50902', '', true, true)]
    procedure MyProcedure(var ParamWithä : Boolean)
    var
        myInt : Integer;
    begin    
        message('Param ist: ' + format(ParamWithä));
    end;


    [EventSubscriber(ObjectType::Codeunit, 50902, 'OnPublishNextParam', '', true, true)]
    procedure MyProcedure2(var pParam : Boolean)
    var
        myInt : Integer;
    begin    
        message('Next Param ist: ' + format(pParam));
    end;
}

You will see that only the Event without Umlaut is executed.
If you delete the umlaut in the Name then both Events are thrown

So the Problem is that AL does not execute Event with umlaut in the Parameter names

@Gallimathias: This are Unicode applications. Unicode support all special chars like german umlaut or danish umlaut or polish umlaut etc.
It is not NAV 2009 anymore

**Comment by Gallimathias** [comment]
@MBGWS Nav2009 - Nav2018 are more than dead to me. Of course your text is unicode but umlauts or special characters are just a bad style because they are not neutral. I'm in favour of more enforce clean code to AL (see phyton or Kottlin for indentations and so on). But that is offtopic and should not be discussed here. Sorry ^^

**Comment by thpeder** [comment]
Hi @HBerndV,
I found the root cause of the issue. The problem is that the produced output from CSide is different from what the new compiler generates for these characters and because of that the server fails to find the parameter.
We are not going to fix it, but the characters works for AL to AL events.
