### ISSUE TITLE
Signing app leads to "This file format cannot be signed because it is not recognized" error

### ISSUE THREAD

**Issue by kine** [Microsoft/AL#2208]
Hello all,
wanted to sign the app with the signtool on my server during the CI/CD, but still getting "This file format cannot be signed because it is not recognized" even when the Install-NAVSipCryptoProviderFromNavContainer was used. Signing on my desktop works. 

What I installed on the server>
1) VS 2017 community - Windows 10 SDK (10.0.16299.0) for UWP: C#, VB, JS
2) Used the Install-NAVSipCryptoProviderFromNavContainer for container based on microsoft/bcsandbox image
3) Tried to do signtool.exe to sign the app.

Getting this in cmd>
```
C:\Windows\system32>SignTool sign /f \\devel\templates\build\NVRCodeSigning.p12 /p ****** /t http://timestamp.verisign.com/scripts/timestamp.dll "filename"
Done Adding Additional Store
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: filename

Number of errors: 1
```
What could be wrong in this?

**Comment by StanislawStempin** [comment]
I have only seen this error in cases where the correct navsip.dll was not installed. Can you make sure that the only navsip.dll on your build machine is the one coming from NAV 2018 or later?

**Comment by DaveBoehmPBSI** [comment]
![2018-05-30 1](https://user-images.githubusercontent.com/26011175/40737368-2923a3fc-6406-11e8-9821-d5082b4437ec.png)
I'm getting the exact same issue within a docker that I've installed in my Azure account.  I'm trying to keep this as simple as possible, so I have signtool.exe, my code signing certificate, and my .app all in the same folder.  I created this VM and installed this docker image in April, 2018. 

C:\Users\vmadmin\Documents>signtool sign /t http://timestamp.verisign.com/scripts/timestamp.dll "C:\Users\vmadmin\Documents\Professional Business Software, Inc._247 TimeTracker_11.0.0.1.app"
Done Adding Additional Store
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: C:\Users\vmadmin\Documents\Professional Business Software, Inc._247 TimeTracker_11.0.0.1.app

Number of errors: 1

**Comment by DaveBoehmPBSI** [comment]
As an update, I installed the latest version of NAV on my own computer, and code signing worked without a problem.  On my computer it works, in the Azure docker image it doesn't.  Just something to be aware of...

**Comment by chavansachin20** [comment]
As @StanislawStempin  stated in his comment, this is due to NavSip.dll, its **correct**. 

@kine , as you are using docker and signing file from you local machine, you are facing this issue. 

I have done below and issue is resolved. 

**Solution** : 

1. Try to copy file from docker image to your machine.
- C:\Windows\System32\NavSip.dll
- C:\Windows\syswow64\NavSip.dll

2. Once copied to your local machine under below path for respective DLL , 
- C:\Windows\System32\NavSip.dll
- C:\Windows\syswow64\NavSip.dll

3. Run powershell command again.
