### ISSUE TITLE
Sales Quote page not available as page extension?

### ISSUE THREAD

**Issue by ligo77** [Microsoft/AL#2252]
I'm trying extend the Sales Quote Page, but it's not available in VSCode when I try to create a page extension. The Sales Quote Subform is available but not the header.

Running NAV2018 CU3.

**Comment by thpeder** [comment]
Hi @ligo77,

It sounds like your symbol file doesn't contain the page.
Are you doing hybrid development with C/SIDE and VS Code? [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side)

**Comment by thpeder** [comment]
Are you using the VSIX that came with the product?
What is the page id and name that your are missing?
Is it only a problem when extending the page or are you not able to create a variable of that page?

**Comment by ligo77** [comment]
Yes, I'm using the VSIX that came with the installation. The page id is 41. No, I'm not able to create a variable of that page either. Sames issue there....

**Comment by thpeder** [comment]
I can't seem to reproduce your problem. Could you give it a try on the latest CU and check if your issue is fixed there.

**Comment by StanislawStempin** [comment]
Just to make sure, could you please recompile page 41 in C/SIDE using the generatesymbolreference=yes flag? Then restart NST, delete your local symbol .app file from VS Code and re-download from the server. 

Typically if there are single objects missing it is because of recompiling objects in C/SIDE without the symbol generation flag or because global symbol generation was interrupted before it finished. A blog post from our support team explains in more details how to make sure one has the correct symbols:
https://blogs.msdn.microsoft.com/nav/2018/01/16/generate-symbols-in-a-modern-development-environment-with-microsoft-dynamics-nav-2018/

**Comment by ligo77** [comment]
Yes, this finally did the trick! Recompiled the page and made sure that the generate symbol flag was on (thought it was but no....) Thank you @thpeder and @StanislawStempin for your time and effort!
