### ISSUE TITLE
Error when publishing app file. Paging file is too small.

### ISSUE THREAD

**Issue by NicolaiEsbensen** [Microsoft/AL#2265]
On occasions we get an error when publishing.

[2018-05-16 09:12:09.49] Sending request to http://w1:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
[2018-05-16 09:13:26.88] The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: error CS0010: Unexpected fatal error -- 'The paging file is too small for this operation to complete. '

If we try a couple of times the operation succeeds. Is there anything to do about this, increase the pagefile, however that is done? 

I'm running on a docker container running the latest preview.

**Comment by tfenster** [comment]
Seems like your container is running out of disk space. Can you check and see if the container host has enough free space?

**Comment by NicolaiEsbensen** [comment]
@tfenster the host har 250 GB available. That should be plenty, but my question is if there is any settings for the container or the NAV service that needs to be adjusted?

**Comment by tfenster** [comment]
The first error indicates a memory problem. That might be caused by the container not having enough RAM. Is your container host running on Windows 10?  Because there you automatically have a memory restriction as the container is running in what's called hyper-v isolation mode. If you are running on Windows Server, then the question is of you are using docker run or a cmdlet from navcontainerhelper? Depending on your parameters you still might have a memory restriction

The second error indicates a storage / disk space problem. The container should be able to use whatever your host has, so that is a bit strange. Again, is your container host Win 10 or Windows Server?

**Comment by NicolaiEsbensen** [comment]
@tfenster  currently running on a windows 10, using navcontainerhelper, which gives the container 3GB. Tried to increase the memory hoping that it would affect the swapping, but it seems like it's only possible on creation of the containers for windows images.

**Comment by tfenster** [comment]
yes, memory restrictions can only be set when the container starts. Side note: If you didn't set 3GB manually, I think the default is 4GB (see [here](https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-NavContainer.ps1#L301-L307))

**Comment by Pieterheinevdm** [comment]
restarting the container fixed this problem for me.
