### ISSUE TITLE
External deployment is not enabled

### ISSUE THREAD

**Issue by Phfo** [Microsoft/AL#2310]
Upload and deploy extension from menu on BC sandbox message : External deployment is not enabled. Please contact you system administrator. 

How to enable external deployment ?

**Comment by HunterFeltman-MSFT** [comment]
External deployment is by design not allowed a Sandbox tenant in BC by design.
Deployment of extensions on a sandbox is meant to be done via VS Code to allow you to test out/develop your extension in a BC-like environment. 

The external deployment feature is not meant to be used as a method of 'trying out' your extension, but rather as a means of deploying a 'final' product to a live tenant. Once you have finished with the development cycle for your extension, you will need to log into the live production tenant and upload your package from there.

Note: the upload process runs the same 'validation' as can be run from the compiler locally by setting up the PerTenantExtensionCop AL Code Analyzer. 
E.g. adding the following to your settings:
```
"al.codeAnalyzers": [
        "${PerTenantExtensionCop}"
    ]
```

**Comment by DaveBoehmPBSI** [comment]
I am using object numbers in the 50250 to 50300 series in my app.  I ran into this "External deployment not allowed" error message when I tried to upload the app from within the docker image in my azure account.

When I try to deploy the app from within VS Code by using Ctrl-F5, I get the following error message:

The request for path /nav/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Your program license does not allow you to publish 'PBSI TT Activation Code Info'.

The same thing happens if I don't specify a "SchemaUpdateMode" (meaning I go with the default of "synchronize".

O.K., so I can't upload the extension from within the docker NAV, and I can't use the upload process from within VS Code.  Between "External deployment is not enabled" and "Your program license does not allow" it seems like you folks at Microsoft have created a real mess.

I sincerely hope I'm missing something here, but I'm basically stuck.  Any ideas?
![2018-06-01 4](https://user-images.githubusercontent.com/26011175/40861906-66e09294-65b0-11e8-9c36-53432efc0b7c.png)

**Comment by StanislawStempin** [comment]
You can deploy code in the range you mentioned in multiple ways:
- Online Sandbox by using Ctrl + F5 from VS Code
- Docker sandbox by uploading your partner license and then using Ctrl + F5 from VS Code
- Online Production tenant by using Upload functionality on Extension Mgmt page

**Comment by megel** [comment]
What is the future / planed behavior for the PROD On-Prem Installation?

How can we enable the "External Deplyment"?

![image](https://user-images.githubusercontent.com/15800069/43850050-2f917e4a-9b37-11e8-88d6-3f26b0b6c056.png)

I use docker sandbox-master with our partner License.

![image](https://user-images.githubusercontent.com/15800069/43850198-901da266-9b37-11e8-989e-c7d1a7d0f2b3.png)

**Comment by StanislawStempin** [comment]
For On-Prem things will work as they used to. You should use the Publish-NavApp powershell cmdlet.

**Comment by chavansachin20** [comment]
Publish-NavApp powershell is useful only if you want install own app. if you want to install other app, D365 login is mandate.
