### ISSUE TITLE
Question about hiding/replacing fields/action buttons in AL

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#2341]
Sometime we need to replace standard fields/buttons with our own implementation. Currently we follow the next pattern:
```
modify(StandardNavField)
{
            Visible = false;
            Enabled = false;            
}
AddAfter(StandardNavField)
{
            field(CustomField;CustomFieldExpression)
            {
                ApplicationArea = Empire;
            }
}
```
Downside of this solution is, when the end user goes into page customization, they still can see the StandardNavField and put it back on the page... Often this field has the same caption as the modified (CustomField).

I tried following solution which work as a charm, but I want to verify if there's any risk on this for the (near) future...
```
modify(StandardNavField)
{
            ApplicationArea = EmpireDisabled;
}
AddAfter(StandardNavField)
{
            field(CustomField;CustomFieldExpression)
            {
                ApplicationArea = Empire;
            }
}
```
Solution above will hide the field from the page, and the field is also not available anymore when the end-user tries to customize the page.

Please let me know your opinion on this...

**Comment by grobyns** [comment]
Hi Ron,

This should work for now but I would still add the visible/enabled properties as well.

I'm a bit in doubt if you should use a real or a fake application area. If you use a real area, you risk someone turning it on (by accident) but if you use a fake one and we introduce some kind of validation on the application area property then we'd break your extension.
I think either risk is quite low though so you should be fine.

br/Gert

**Comment by kdldk** [comment]
Hi, Gert and Ron

I do something like.
I Extende page 507 with a new action.

![image](https://user-images.githubusercontent.com/39760364/41230631-cd7ffe72-6d80-11e8-8f4c-d3641d2de460.png)

At the Classic client there are two problems

1) Std NAV Action Btn is still there
2) My new Action Btn is not placed right ?

![image](https://user-images.githubusercontent.com/39760364/41230778-591aaffe-6d81-11e8-963f-8977e44ee40b.png)


NAV 2018 CU5
AL Language 0.12.20065

**Comment by grobyns** [comment]
Hi,

- the old button is moved to a new group 'Make' by configuration. You would have to update the configurations to change that. You could try setting a new application area to see if that removes it. Once the group is empty it should also disappear.
- Your new button is placed where you told it to be placed, under Process. You can't move it to the Make group in code since that group is created in configuration.


one final observation:
Please consider what would happen if every extension removed the action and put in their own. Would we end up with multiple 'Create Order' actions? Which one would the customer use?
I know we are not yet where we want to be with extendibility of the app code so please help us make it more extendible by letting us know where you need help. If you always replace the actions completely then we won't know what places need more extendibility options.

Cheers,
Gert

**Comment by kdldk** [comment]
Hi, Gert 
In my Case, I have to make a workaround. I need a event [https://github.com/Microsoft/AL/issues/2540]. I have to use a different no-series.

BR, Kjeld

**Comment by grobyns** [comment]
Closing this issue as I think the questions raised have been answered.
