### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by alvarotellez** [Microsoft/AL#2352]
Hello! Ive a question about versioning. In C/Side we have a column in the development environment called "Version List". Has vs code some possibility of use it or something similar?

Thanks!

**Comment by thpeder** [comment]
Hi @alvarotellez,
In AL you can't version the individual objects only the entire app, which is specified in the app.json file.

**Comment by alvarotellez** [comment]
Thanks @thpeder Ive just seen if you export a standard object by powershell, this object has his version like a comment.

![version nav 2018](https://user-images.githubusercontent.com/22259440/40541774-84599318-601d-11e8-8688-d054dabbe1bc.png)

I will use this.

**Comment by MikeGlue** [comment]
Just my opinion, but you should move away from trying to version tag each individual file. Unlike C/SIDE, in AL you can't deliver individual files so why bother trying to version at that level? As was previously stated, there is a version in the app.json file and that version number applies to the entire app, simply because you can only ever build and deliver the entire app as a whole.

**Comment by alvarotellez** [comment]
@MikeGlue I will use the app.json!!! Thanks by your opinion! :) 

Best regards!
