### ISSUE TITLE
GoTo Definition -> Standard NAV Objects

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#237]
One of the challenges when working with VSCode is that there is no GoToDefinition for Standard NAV objects.

This will throw us back 10 years into stone age, but more important, it will have a high cost on getting new developers up and running with the tool.

For me this is not that much of an issue because I know most of the NAV code inside out but we are doing this to attract a new generation of developers.
![gotodefinition](https://cloud.githubusercontent.com/assets/7205122/26274734/c4fc8060-3d50-11e7-8570-51617a708525.png)

**Comment by esbenk** [comment]
We are aware of this and we know that insights in the base app is key to understanding NAV. We are planning to address this with the new development tools, but don't have a timeframe for it.

**Comment by CarlOhlsson** [comment]
Me and colleague just downloaded NAV 2018 and are trying out VSCode and came across this as-well. "Go to Definition" only shows the structure of the core object (fields, key, triggers) but not the code itself. 

- Is it intended not to show the code or have we missed something?
- If it is being worked on, do you have a time frame?

**Comment by esbenk** [comment]
This is feature is not implemented yet. Getting to the full source will only be for object written in AL, for objects written in C/SIDE we wont support it.

**Comment by CarlOhlsson** [comment]
Alright if i understand you correct this feature is not implemented at this time but when it is it will only support viewing objects that is written in AL and not C/SIDE.

So for NAV 2018 we can still go to the old development environment to look at the source code (C/SIDE) for standard objects. However since the old development environment will be removed in later versions this will not be possible in the future. Now i have the same question as _markbrummel_ initially asked. How are we as developers supposed to learn how the standard objects work in order to build extensions that work together with the standard code?

Since i'm one of the "new generation developers" that markbrummel mentioned i rely a lot on being able to read the standard code. Not being able to do so is a big problem for me and also my senior colleagues.

**Comment by esbenk** [comment]
Being able to see the source code of our application is an important way of learning what to change/extend. 

Currently the base-app is still written in C/AL using C/SIDE. In the future we will develop everything in AL. When we have fully moved to AL, you will be able GoTo definition into base-objects as well. 

This doesn't mean that you can't view the source. We will still continue to make the source available, the complete move to AL will just make it possible to build even better navigation/discoverability between symbols/source.

For future OnPremise development you will still be able to change/customize everything - if the extension model isn't sufficient. The only change is that the development tools will then be AL + VsCode and not C/AL + C/SIDE. Being able to do so will of course still require access to standard
objects.

I hope that this answers your question and removes any worries about source code visibility for standard objects.

**Comment by CarlOhlsson** [comment]
Thank you for a very good answer, we have been worried about that some of our customers solutions can't be moved to extensions. Good to hear that OnPremise still allows us to customize outside the scope of extensions.

**Comment by lvanvugt** [comment]
Good to read that has been addressed already. This is typically a thing all people attending my workshops are asking about.

**Comment by StanislawStempin** [comment]
The Go To Definition feature for base app C/AL objects has been implemented as of June 2018 preview. Please see the blog post for more details:
https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/
