### ISSUE TITLE
Role Center "How To"

### ISSUE THREAD

**Issue by 420tech** [Microsoft/AL#2372]
New to Dynamics and new to AL. Where can I find code snippets for adding a Role? I want to add menu items to the home screen.

Thanks,

**Comment by qutreson** [comment]
Hi @420tech, in AL in order to add a new RoleCenter, you need to declare a new page object with the property `PageType = RoleCenter;`. 

You can read more about how to use RoleCenters here: [Designing Role Centers](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers), and about page objects here: [Pages Overview](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-pages-Overview).

**Comment by 420tech** [comment]
Thanks! 

I wrote this code:

page 50101 MyRoleCenter
{
    PageType = RoleCenter;
    SourceTable = "My Customer";
    layout
    {
        area(Content)
        {
            field(Name;Name)
            {
                ApplicationArea = "All";
            }
        }
    }

}

It doesn't show up on the Home screen - which is what I am trying to make happen. What am I missing? I see the links you sent - just haven't seen a working example. Thanks!

**Comment by qutreson** [comment]
If you want to add a field to a Role Center, you should use a page extension in order to modify the existing Role Center page: [Page Extension Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object).

**Comment by StanislawStempin** [comment]
See if these help (these links are from the Wiki here on AL GitHub)

https://docs.microsoft.com/da-dk/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane
https://github.com/Microsoft/AL/issues/669
