### ISSUE TITLE
Access to global var from table-/page-extensions

### ISSUE THREAD

**Issue by kdldk** [Microsoft/AL#2421]
Hi,
I'm trying to extend Table 37 with additional fields. I expected that I could have access to all global variables and all Procedure on the table 

I am using NAV 2018 Version (11.0.21836) and VSCode Version 1.22.2 (AL Language 0.12.20065)

![image](https://user-images.githubusercontent.com/39760364/40710074-f83d2d3e-63f7-11e8-8dae-66ddf795968d.png)

**Comment by rdiazbla** [comment]
Hi,
I have similiar problema.
I add a new procedure in a tableextension because the original procedure is internal and I not have acces to global variables defines in the table. Why?

![tableextension](https://user-images.githubusercontent.com/40169037/41229856-ddefe73e-6d7d-11e8-8def-fe96fd3143bc.png)

**Comment by Gallimathias** [comment]
This definitely belongs to #593 and a little bit to #153

**Comment by StanislawStempin** [comment]
Closing as duplicate of #593
