### ISSUE TITLE
Problem with RunPageLink for "Change Log Entries": Field type Text is not convertible to field type Option

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#2445]
I get the error messages `Field type Text is not convertible to field type Option` and `The property value '"Table No."=CONST(36),"Primary Key Field 1 Value"=FIELD("Document Type"),"Primary Key Field 2 Value"=FIELD("No.")' on property 'RunPageLink' is not valid.` for an action to **Change Log Entries** of that document. This Action work in C/SIDE and was converted via **txt2al**.
```
pageextension 50000 pageextension50000 extends "Sales Return Order" 
{
    actions
    {
        addafter(Print)
        {            
            action("Change Log Entries")
            {
                Caption = 'Change Log Entries';
                Image = ChangeLog;
                RunObject = Page "Change Log Entries";
                RunPageLink = "Table No."=CONST(36),
                              "Primary Key Field 1 Value"=FIELD("Document Type"),
                              "Primary Key Field 2 Value"=FIELD("No.");
                RunPageView = SORTING("Table No.","Primary Key Field 1 Value")
                              ORDER(Descending);
            }
        }
    }
}
```

**Comment by dNsl9r** [comment]
I've got the same problem when converting with txt2al. Trying to open a page where all fields are declared as they should be declared.

**Comment by srinivasGangadhara** [comment]
Hi 

i have same issue with change log entries, we have any update about the issue?
![image](https://user-images.githubusercontent.com/29703512/46791753-6b43e900-cd5f-11e8-8a2d-1533e87125d6.png)
![image](https://user-images.githubusercontent.com/29703512/46791771-726af700-cd5f-11e8-8b6d-d231e6f55955.png)

thanks!

srinivas

**Comment by srinivasGangadhara** [comment]
@qutreson  any Update about issue?

**Comment by qutreson** [comment]
Hi @srinivasGangadhara, sorry for the delay, I will work on it today and I will keep you updated!

**Comment by srinivasGangadhara** [comment]
Please check the below screenshot of C/SIDE,
![image](https://user-images.githubusercontent.com/29703512/47995206-8c0f1c80-e11a-11e8-88e8-b7052613deb6.png)


From C/SIDE of Client am able click the action and i can able to see filters if the fields Text Fields.
![image](https://user-images.githubusercontent.com/29703512/47995278-c5e02300-e11a-11e8-975a-5f5f1cf1ca72.png)

Please let me know further.

regrads
srinivas

**Comment by qutreson** [comment]
This is what I have in C/SIDE:
![image](https://user-images.githubusercontent.com/31541422/47996305-640ec180-e0f8-11e8-8fec-e4ca068fd721.png)

And this is how the action is rendered in the web client:
![image](https://user-images.githubusercontent.com/31541422/47996379-9e785e80-e0f8-11e8-954d-d0cba2ba912b.png)

As you can see it is greyed out and it cannot be used. Is it different for you?

**Comment by srinivasGangadhara** [comment]
Yes It is same for me But in Business Central if you write same SubPage link then we are facing issue 
![image](https://user-images.githubusercontent.com/29703512/47997461-e3fd5180-e121-11e8-9549-76d910153dc6.png)

Please check the Above image, the Primary key Field 1 value is Text and filtering with Field "Document Type " is Required.

Can you help on this.

regards,
srinivas

**Comment by qutreson** [comment]
I was wondering if this action does work at all. The diagnostics created by the AL compiler is correct here as we should not allow converting a text ("Primary Key Field 1 Value") into an option ("Document Type"). 
This was previously possible in C/SIDE probably due to some missing validation, but it should not have been allowed. 

Do you know if this action was working when created from C/SIDE and if it is still working now? If it is not working, then the diagnostic from the compiler should not be relaxed as it means that the server cannot handle it anyway.

In any case, I think your RunPageLink should probably be rewritten in order to use only text or only option fields (for instance by introducing a new field on the tables used) and avoid having this conversion from text to option.

**Comment by qutreson** [comment]
Closing the issue as the compiler diagnostic is valid and it seems to be solvable by re-writing the extension code.

**Comment by bjarkihall** [comment]
@qutreson What about Enum -> Option/Integer?
There's no way of using `Enum.AsInteger` or a variable/procedure in `RunPageLink` which causes an unsolvable AL0603 warning since Enums can't be casted in the TableFilter.
I'm fixing it for now as an OnAction trigger which runs Page.RunModal but I thought I'd let you know in this ticket, this issue might've been reported on another type of property but I couldn't find it.
