### ISSUE TITLE
"Licensing issue" combined with not being able to upload an extension has caused a real mess

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [Microsoft/AL#2449]
![2018-06-01 4](https://user-images.githubusercontent.com/26011175/40862365-e3590a3a-65b1-11e8-92c4-227a2ca3194f.png)
I am using the April 2018 docker, deployed to my Azure sandbox.

I am using object numbers in the 50250 to 50300 series in my app. I ran into this "External deployment not allowed" error message when I tried to upload the app from within the docker image in my Azure account.  I researched it here on GitHub, and the answer was basically "we don't allow you to upload extensions to the sandbox from the extensions page in a NAV" sandbox.

When I try to deploy the app from within VS Code by using Ctrl-F5, I get the following error message:

The request for path /nav/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Your program license does not allow you to publish 'PBSI TT Activation Code Info'.

The same thing happens if I don't specify a "SchemaUpdateMode" (meaning I go with the default of "synchronize".

O.K., so I can't upload the extension from within the NAV docker, and I can't use the upload process from within VS Code. Between "External deployment is not enabled" and "Your program license does not allow" it seems like you folks at Microsoft have created a classic example of a bureaucratic mess.

I sincerely hope I'm missing something here, but I'm basically stuck. Any ideas?

**Comment by StanislawStempin** [comment]
The licensing system combined with the multiple development environments that we offer can be it fact somewhat confusing at times. Let me try to shed more light on the topic.

In the Online environments (hosted by Microsoft) the license is not a concern since Microsoft handles that on the backend. You should be able to do all development (on the Sandbox) and publishing (on the Prod environment) that you described above without running into any license issues. 

However, on Docker you need to use your partner development license for any real development. By default Docker environments ship with the Demo license that only allows development in the 50100-50150 range.

Regarding the "Upload Extension" - this is funcionality dedicated only to the online Production environment and performs the upload of tenant customization into Microsoft infrastructure. On Docker environments you can achieve the same outcome by using Ctrl-F5 from VS Code or Publish-NavApp from powershell command line.

Specifically for your situation the steps to take would be:
1. Upload your partner license into the NST hosted in Docker
2. Use Ctrl-F5 from VS Code or Publish-NavApp for publishing your app
