### ISSUE TITLE
tfieldboolean snippet missing?

### ISSUE THREAD

**Issue by ajansari** [Microsoft/AL#2458]
While watching the "[How do I add a field in an extension](https://www.youtube.com/watch?v=q00zPWT7e34)" video (Microsoft Dynamics 365's YouTube channel), I notice that Daniel uses the "tfieldboolean" snippet. 

I have AL Language build 0.15.18771 installed in Visual Studio Code, and while I have some other tfield___ snippets, I don't have the one for Boolean. Has it been removed, or am I doing something wrong?

Thanks!
AJ

**Comment by qutreson** [comment]
Hi @ajansari, we have refactored our snippets some time ago in order to fit with [VS Code guidelines](https://code.visualstudio.com/docs/editor/userdefinedsnippets). When using the snippet `tfield` you can now choose the type of field you want as shown below:

![boolsnippet](https://user-images.githubusercontent.com/31541422/40964816-5970060e-68ac-11e8-9605-d4d5b27355ce.gif)

**Comment by ajansari** [comment]
Ah, interesting. Thank you for that information!

Does that mean we will soon be losing the some of the other tfield___ snippets that are still visible (like tfieldcode, tfieldoption, tfieldtext, etc.)? It seems inconsistent to have some but lose the others.

**Comment by qutreson** [comment]
We are now using the `tfield`snippet for all the field types that does not require additional information (Integer, Blob, Boolean). The other ones like Text or Code are left as individual snippet because you have to specify also the length. Same thing for options where you need to specify the option members.

**Comment by ajansari** [comment]
That makes sense. Thank you for explaining.
