### ISSUE TITLE
How can we handle field property changes ,key changes in standard table 

### ISSUE THREAD

**Issue by Deepakalle123** [Microsoft/AL#2459]
error i am getting-//Unsupported feature: Change TableRelation on ""Account No."(Field 5)". Please convert manually

**Comment by SirBETE** [comment]
In order to let the MS guys help you quicker, perhaps you can:
- Use the header of the issue for giving it a title (your old title was good)
- Use the body of the issue to describe it (the extra text you added when you changed your title belongs here)
- Along with extra info about what you want to do
- Please include AL and NAV/BC version

For more info about adding/changing keys in the base application, see #730

**Comment by Deepakalle123** [comment]
Hi,
AL Version- 1.22.1
NAV - 2018

**Comment by kalberes** [comment]
Did you get this through running the txt2al after you have exported your objects with the exporttonewsytax?

**Comment by Deepakalle123** [comment]
Hi - Yes  also i have exported my Object with ExportToNewSyntax.

**Comment by qutreson** [comment]
Hi @Deepakalle123, you are getting this warning this warning because your delta file contains some changes which are not allowed in AL (like modifying the TableRelation of a field or modifying/removing the keys of a table). In your case, you should add a new field with your table relation in your table and use this one instead.

**Comment by Deepakalle123** [comment]
Yes I agreed , It means you are saying, need to add the replica of the standard field in custom Ids and define the changed table relation properties against that.

In future is there any planning to extend the field properties of Standard field? actually it will be required for converting older version of NAV to Business Central or NAV2018 (with cloud ready architecture)

**Comment by qutreson** [comment]
It is possible to change some properties of table fields from extensions, but not all of them (like the property TableRelation for instance). The txt2al converts the property that can be modified from extensions into AL code and converts the ones that cannot be modified into code comments (like the one you got here).

**Comment by Deepakalle123** [comment]
Is there any link or details of field properties that will get handle from extension.

**Comment by qutreson** [comment]
I don't think we have documentation with an exhaustive list of the property that are modifiable. But, you can get access to it by declaring a small table extension in AL modifying a field and triggering IntelliSense. 
```
tableextension 50100 MyExtension extends Customer
{
    fields
    {
        modify(Name)
        {
            // trigger IntelliSense here.
        }
    }
}
```
Intellisense will suggest only the properties that you can modify. All the ones that do not appear cannot be used so would be exported as warnings by the txt2al.

**Comment by Deepakalle123** [comment]
ok noted Thanks 👍
