### ISSUE TITLE
resource ids are repeated, all resource ids in input file should be unique

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#2516]
AL Compiler version 0.15.18771
Platform Version 12.0.21812

We sent request to LCS for translation and we got below response.

![image](https://user-images.githubusercontent.com/23735402/41150086-ce9c2d92-6b2a-11e8-834c-ef6b53e8b3bb.png)

[Duplicate Resource Ids.txt](https://github.com/Microsoft/AL/files/2083781/Duplicate.Resource.Ids.txt)

**Comment by pmohanakrishna** [comment]
@DominikDitoIvosevic what is resource id in translation file?
can we manually fix them? what impact it will have if we fix manually and generate file next time?

**Comment by DominikDitoIvosevic** [comment]
Resource IDs are IDs of each translation item. Each translation item should only be related to one label and the reverse should hold as well. Could you please find out which 2 labels have identical IDs and paste them here so that I can investigate why this happens? A workaround is to rename one of them

**Comment by pmohanakrishna** [comment]
Do you mean Table 3971694684 - Property 2879900210 is resource id in below screenshot?

our translation file has 111169 lines. is there any way to identify duplicates without manual check?

![image](https://user-images.githubusercontent.com/23735402/41713371-8d103b3a-756a-11e8-9219-394f1bfe49f7.png)

**Comment by pmohanakrishna** [comment]
@DominikDitoIvosevic I think I found. are these the ones?

![image](https://user-images.githubusercontent.com/23735402/41722738-f9e96436-7586-11e8-86f4-26d9498b0d09.png)

**Comment by DominikDitoIvosevic** [comment]
Am I correct that these are labels on triggers on fields on a table? This is a known issue which we fixed in master but didn't want to backport yet to not break backwards compatibility as the IDs have to have additional 4th value for differentiation. 

The workaround for you is to rename the labels so that they don't have the same name. I was also told it is general practice to have all labels as global variables on the object which would also avoid these issues.

**Comment by DominikDitoIvosevic** [comment]
The IDs have to be exactly the same as the compiler would generate them.

**1. Change the name of the labels in your AL code so that they are different
2. Generate a new xliff file
3. See the new ID values
4. Apply them in your xliff file.**

If you change the ID to a new value without renaming the label you will simply disconnect them and the compiler wont use that translation.

**Comment by mr-sala** [comment]
I have the same problem.
Is this going to be fixed in the future? do you know when it will be?
Or we have to change our labels manually in order to fix it?
Thanks!!

**Comment by thpeder** [comment]
Hi @mr-sala 
What version are you using since it should be fixed in the developer preview and in Business Central now.

**Comment by mr-sala** [comment]
hi @thpeder 
I'm using
AL Extension Version: 0.12.25327
Server Version: 11.0.23019 (NAV 2018 CU7)

**Comment by thpeder** [comment]
The fix wasn't backported to Nav2018, so you will have to use the workaround that Dominik wrote, namely to rename the label variable.
