### ISSUE TITLE
Latest Docker Image

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/AL#2524]
When was the latest docker image published?  I just went to pull the latest and it says I have the current image but it is 6 weeks old.  It shows as Build 21812
I used this command: `docker pull microsoft/bcsandbox`

**Comment by freddydk** [comment]
microsoft/bcsandbox will give you latest minor release.
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
There has been several small fixes in between and those are also available, but we only tag the minor release as latest in order to avoid that people have to pull new images every day.
Next minor update is due any day - will check monday
