### ISSUE TITLE
Extension fields on system tables

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#2559]
It is actually possible to create extension fields to system tables like the Object table.
This can be done even if the Target has been set to Extension in the app.json file.

Is that a bug?

**Comment by qutreson** [comment]
Hi @peikba,

It shouldn't be possible to extend system tables when using `"target": "Extension"`. When trying to extend the system table Object with `"target": "Extension"`, I am getting the following error:

![image](https://user-images.githubusercontent.com/31541422/41290191-5d77ae82-6e4c-11e8-87b8-459dac63b0ca.png)

Can you share with us some repro steps that you followed in order to be able to extend the Object table? Which version of the server and of the AL extension are you using?

**Comment by peikba** [comment]
Hi 

I did it with the target: Extension in my app.json file.
![image](https://user-images.githubusercontent.com/33752561/41291876-1ec9bf86-6e51-11e8-9d90-5dff016940d3.png)

And the tableextension:
![image](https://user-images.githubusercontent.com/33752561/41291910-39e588ae-6e51-11e8-968b-294c905296c1.png)

I'm running the NAV 2018 CU6 VSIX 0.12.17091

It uploads nicely :)

![image](https://user-images.githubusercontent.com/33752561/41292053-b180ebd8-6e51-11e8-8789-5cb61732cf76.png)

**Comment by thpeder** [comment]
It will not be backported to Nav 2018, but the next version in the market place will have that check.
