### ISSUE TITLE
How choose server during publishing?

### ISSUE THREAD

**Issue by IvoMol** [Microsoft/AL#2578]
I have defined more server configurations in launch.json and trying create and test one application against different NAV environments (older NAV 2018 installed locally, current NAV 2018 in Docker, W1 database, country database, etc.) at the same time.
If I want AL: Download symbols, dialog for selection server appears and I can select a server. Works fine.
But if I want AL: Publish (anyway), there is no option to choose a server and application is published to any server (first?, last used?).

Question: how select server configuration during publishing?
Suggestion: if more servers is defined in launch.json, dialog "Please choose the server" appears during publishing, as well as when downloading symbols.

Using AL extension 0.12.17091 and working with NAV 2018 (not BC).

**Comment by dennisfrostlander** [comment]
Hi @IvoMol,

You can choose the server in the VScode Debug tab:
![image](https://user-images.githubusercontent.com/16953692/41337266-0f89c914-6eef-11e8-8254-6f779fb93390.png)

P.S. We had to add a server selection dropdown for downloading symbols because previously there was no way to access the active debug configuration programmatically. However, VSCode did add such a possibility recently, so for the future we are considering to re-use the active configuration for more cases - such as downloading symbols.

**Comment by IvoMol** [comment]
I did not see the connection here (debugg tab - AL publish).
It is so, it works and is it enough.
Thank you for tip!
