### ISSUE TITLE
Cannot add factbox into page extension because some Anchors are not found in the target page

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2584]
BC Version: 13.0.22070.0-nl
AL Extension Version: 0.15.14407
VS Code Version: 1.24.0

Steps to repro:
- Create page extension for page 26 - Vendor Card
- This is from standard page 26;
![standard page 26](https://user-images.githubusercontent.com/29372522/41351781-bc11734e-6f17-11e8-850b-ba0629940fd9.jpg)

1) Try to add a Factbox page part as the first part in the FactBoxArea Container:
![anchornotfound](https://user-images.githubusercontent.com/29372522/41351601-28b4b368-6f17-11e8-82f2-d4f615c524a3.jpg)

2) Try to add a new factbox after "Vendor Picture" factbox:
![vendor picture anchor not found](https://user-images.githubusercontent.com/29372522/41352362-934da296-6f19-11e8-8a50-25d02185af7c.jpg)

3) As you can see, some anchors are found, ex "Attached Documents":
![attached documents anchor found](https://user-images.githubusercontent.com/29372522/41352451-ceb7a8d6-6f19-11e8-8a98-78f8155c2bab.jpg)

**Comment by qutreson** [comment]
Hi @andreilungu, 

1. When trying to add a page part first in the fact box area, you should use the following code:
```
pageextension 50100 MyExtension extends "Vendor Card"
{
    layout
    {
        addfirst(FactBoxes)
        {
            part(MyPagePart; "Vendor Details FactBox")
            {

            }
        }
    }
}
```
In AL, Areas do not have a name and you should reference them by directly using their subtype. IntelliSense also suggest them for you if needed.

2. The page part 'Vendor Picture' can be found under the name Control82. IntelliSense and the on hover display are showing it as you can see below: 
 
![image](https://user-images.githubusercontent.com/31541422/41356241-c445ad62-6f23-11e8-9648-8d067bceb704.png)

![image](https://user-images.githubusercontent.com/31541422/41356179-9c29518a-6f23-11e8-8c76-b506f2e0c2d4.png)

This happens because the 'Vendor Picture' does not have its name property set, so its name is default as Control82 in your symbol package. For 'Attached Documents', the name property is specified which is why you can find it under this name in AL. 

When you have a doubt about some missing anchors in the AL symbols, you can go to definition (F12) on the object and then have a look at the list of all elements it contains:
![image](https://user-images.githubusercontent.com/31541422/41356624-903bd9b4-6f24-11e8-8e98-b2470420599c.png)

**Comment by andreilungu** [comment]
Thanks, it is clear now !
