### ISSUE TITLE
Download Symbols error when importing Standard/Modified objects

### ISSUE THREAD

**Issue by andreilungu** [Microsoft/AL#2666]
In build 13.0.22621.0-nl, when creating page extensions we get stuck in an error when trying to download symbols in a specific situation.

Example of the error:
The request for path /nav/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0 failed with code 422. Reason: The expression name 'ActionVisible' can only appear once in the page 'General Journal'.
[2018-06-20 16:19:52.08] Could not download reference symbols. Please ensure that:

Detailed steps to reproduce the error can be found in this Word document:
[Repro Download Symbols issue.docx](https://github.com/Microsoft/AL/files/2119820/Repro.Download.Symbols.issue.docx)

Here you can find also sample files used in the repro steps:
[Objects used.zip](https://github.com/Microsoft/AL/files/2119827/Objects.used.zip)

Could you please check why this error appears ? In the current situation the only workaround to fix this is to recreate the container every time we import standard/modified objects and this is very time consuming.

_In an older build this issue was not present, we started to have it since upgrading to version 13.0.22621.0-nl_

Thanks,
Andrei Lungu

**Comment by thpeder** [comment]
Hi @andreilungu,
We discovered that if you have a base page with a global variable that is used in properties like Visible, and you then create a page extension on the same object with a global variable of the same name as the mentioned variable which also gets used in a property like Visible, then the page would throw an error once you visited the page in the client.
In order to avoid that from happening at runtime, we made two changes which went in one after the other and I think your version only contains the first change.
1. The server now checks for this problem, so you don't need to visit every page for finding said problem. (That is the error you are seeing)
2. The compiler will generate different code which should never allow this to happen again.

I tried on the latest version and couldn't reproduce your problem. Could you give it a try as well.

Thanks,
Thomas
