### ISSUE TITLE
Global variable is blank

### ISSUE THREAD

**Issue by MoallaMehdi** [Microsoft/AL#2697]
Hi,
I'm trying to create a new extension to modify the way of posting in the codeunit 80. The objective is to add a new general ledger entry each time i post a Sales invoice + Add the same value on the customer entry.
I created a new procedure and tried to make the same approch as it is done for the PostCustomerEntry (CU 80). 
The parameters of my new functions are:
- SalesHeader,
- TotalSalesLine,
- TotalSalesLineLCY,
- GenJnlLineDocType,
- GenJnlLineDocNo,
- GenJnlLineExtDocNo,
- SrcCode
I want to place my new procedure to be suscribed to the event : OnAfterPostGLAndCustomer.
Here i face an issue : Some of the parameters are not part of the IntegrationEvent OnAfterPostGLAndCustomer (GenJnlLineDocNo , GenJnlLineExtDocNo and GenJnlLineDocType). 
So i create a new procedure that suscribe to the event OnBeforePostCustomerEntry to get the missing values and use them when calling my new function;

![image](https://user-images.githubusercontent.com/39623117/41774325-216e326c-7617-11e8-85b6-fa1cf640d383.png)

When i debug my code, the new global variables of my codeunit are filled on the step 1 but they become blanks on the step 2!

Any help!

**Comment by rdebath** [comment]
Event subscribers are pure functions so a new instance of the codeunit they are in is created at each individual invocation.

The only moderately nice workaround is to store your state information into one of the arguments that the event gives you (typically a ByVar record). Those two don't have a common record so you're left with the nasty choice of using a single instance codeunit.

I suggest you request OnBeforePostCustomerEntry is modified so that the SalesHeader is passed ByRef.

**Comment by MoallaMehdi** [comment]
What do you by "the SalesHeader is passed ByRef".
Thanks!

**Comment by MoallaMehdi** [comment]
Many Thanks!
