### ISSUE TITLE
Test automation execution is not running in the order

### ISSUE THREAD

**Issue by srinivasbanny** [Microsoft/AL#2711]
Hi,
I created new test codeunit with 10 test functions 
lets say the order of test functions are
Example:
1.Run
 2.createsalesorder
3.createpurchaseorder
4.createpurchaseinvoice
5.Createpurchasecreditmemo
but the order when i run from the test tool its coming in different order
like
1.Run
2.createpurchaseinvoice
3.createpurchaseorder
4.createsalesorder
5.createsalesinvoice

The question why i am asking is the order has dependency to it . so i have to follow the same order as i mentioned as above .Please suggest do i need to do anything else or i missed anything ?

**Comment by pzentner** [comment]
@srinivasbanny technically, you should not have dependencies between the different test functions, meaning that each test function should ideally prepare the full context it needs to execute successfully. However, if you really need a specific order, I would suggest that you name the functions alphabetically, because that's how they are executed, at least from what I have seen. So, you then could possibly call your functions:
1_createsalesorder
2_createpurchaseorder
3_createpurchaseinvoice
4_createpurchasecreditmeno

and then they should run in the order that you need them. 

But to make it work right, for instance, if you would need a sales order created for the "createpurchaseorder" to run properly, you should create a sales order in the initial setup for the "createpurchaseorder" function. Or you have different functions that test the individual process (create purchase order, create sales order, etc.) and then one test function that tests the process and calls the functions all together in the right order.

**Comment by thpeder** [comment]
Hi @srinivasbanny,

The order of the tests is today defined by the procedure Id, which you can't control. That is a bug and we will fix that.
Thanks for reporting the issue.

**Comment by srinivasbanny** [comment]
@thpeder  thanks for the update. for the time being how do we define the functions in orders .can you suggest what can be done ?

**Comment by thpeder** [comment]
@srinivasbanny

The Id of the procedure is a hash value from its name, return type, and parameters, so you could get lucky by changing the name until you hit the expected order.
A better option is probably to divide your tests into multiple codeunits.

**Comment by srinivasbanny** [comment]
@thpeder the problem is i have a dependency to some of the test functions so i cant create them individually

**Comment by salgiza** [comment]
@srinivasbanny A possible solution would be for you to declare the current methods as local, and create Test Functions that call the local methods as required. Ex.

    function CreatePurchaseOrderTest()
    begin
    createpurchaseorder;
    end;

    function CreatePurchaseInvoiceTest()
    begin
    createpurchaseorder;
    createpurchaseinvoice;
    end;

That way you can be sure that the code is executed in the proper order, and you can also handle errors a bit better (if _createpurchaseorder_, there's no need to execute _createpurchaseinvoice_, as that would throw an error that might be misleading).
