### ISSUE TITLE
Object table - Field Name - OemText (same as issue #764)

### ISSUE THREAD

**Issue by Phfo** [Microsoft/AL#2723]
![image](https://user-images.githubusercontent.com/24912240/41900899-fb7a461a-792f-11e8-8d0e-c56044980b61.png)
but now on al extension 0.12.20065

**Comment by qutreson** [comment]
@Phfo, does this issue reproduce with the latest extension from marketplace?
According to #764, this was fixed with the January update (version: 0.13.1586). So, not sure the fixe made it into the version you are using.

**Comment by Phfo** [comment]
Oh now I see, it's probably not yet been backported to 2018 in the meantime ?

**Comment by qutreson** [comment]
We are fixing bugs on the main branch, but we are not backporting all bug fixes by default to former branches. You can read more about how releases are made in [AL Developer Previews, multiple releases, and GitHub](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/) and in our [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions).

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
