### ISSUE TITLE
The logic behind the XLF trans-unit IDs 

### ISSUE THREAD

**Issue by pjanfred** [Microsoft/AL#2725]
Hello,

can someone explain the logic behind the XLF trans-unit IDs in the language files?

_Example:_
**Page 4190260208 - Control 2445482498 - Property 2879900210**
`<trans-unit id="Page 4190260208 - Control 2445482498 - Property 2879900210" maxWidth="999" size-unit="char" translate="yes" xml:space="preserve">
          <source>General</source>
          <note from="Developer" annotates="general" priority="2" />
          <note from="Xliff Generator" annotates="general" priority="3">Page - Control</note>
        </trans-unit>`

**Comment by DominikDitoIvosevic** [comment]
The IDs contain hashed versions of names of those symbols. The reasoning was to restrict the total ID size because some translation toolings break when IDs are over 200-300 characters. You can find the unhashed version of symbol names in the note element of each translation unit in the latest versions of the compiler.


        <trans-unit id="Table 196709268 - Field 415504711 - Method 2126772001 - NamedType 1514930695" size-unit="char" translate="yes" xml:space="preserve">
          <source>My nested trigger value</source>
          <note from="Developer" annotates="general" priority="2"></note>
          <note from="Xliff Generator" annotates="general" priority="3">Table TestTable - Field Id - Trigger OnValidate - NamedType trigVar</note>
        </trans-unit>

**Comment by pjanfred** [comment]
Thank you very much. This was very helpful.
