### ISSUE TITLE
Unexpected CRK exception when using TestPage with Role Center

### ISSUE THREAD

**Issue by kine** [microsoft/AL#2735]
Hello,
as part of my test I want to test if my new action was added to role center. Thus I defined TestPage "Order Processor Role Center" in my test, called the Trap function and run the page. Result is:
![image](https://user-images.githubusercontent.com/110221/41921570-73071658-7963-11e8-80ec-1e8412582918.png)
Code:

```
        OrderProcessorRCTP.Trap();
        Page.RUN(Page::"Order Processor Role Center");
```

al-0.16.21713
insider bcsandbox:latest

**Comment by dennisfrostlander** [comment]
This seems to be a problem in the client, which occurs also when using C/SIDE.

**Comment by pborring** [comment]
TestClient does not support role center pages, because role centers cannot have running C/AL code and some of the internal structures required by TestClient are not instantiated.

If you would like to push for added support, please add an entry on Ideas https://aka.ms/bcideas and other partners can vote for it as well.

**Comment by qutreson** [comment]
Closing this issue as was marked as by-design and suggested to log it on BC Ideas.
