### ISSUE TITLE
Question about versionlist in BC (bcsandbox-master)

### ISSUE THREAD

**Issue by RonKoppelaar** [Microsoft/AL#2794]
For quite some time the versionlist in the BC sandboxes was left empty. Today I created a new container (Build: 13.0.23121), and discovered the VersionList was set again.
What will be the logic for setting the VersionList and object date in the future for this branch?
Will it also include buildnumbers like we have with the cumulative updates in the past?
Is there any documentation regarding this process?

**Comment by ndpatel0074u** [comment]
If i am not wrong,
Version list should/will be the Build Version of you app.json.

**Comment by StanislawStempin** [comment]
You should in general not rely on the VersionList, we reserve the right to change the contents of that field without notice and it is going away in AL anyway. You should be able to obtain necessary version numbers from Tenant Management codeunit.

**Comment by rdebath** [comment]
@StanislawStempin, Nope, there is Zero chance of codeunit 417 being a reliable replacement for the "Version List" property. It looks like Codeunit 9015 "Application System Constants" will give you one version number for all the objects as well as what looks like a replacement for Codeunit 417 based on the new virtual codeunits. But Codeunit 417 only gives the version of the "NavTenantSettingsHelper" DLL which has no fixed relationship to the C/AL code version and is a trivial error away from being the wrong version for the executables.

Even for Cu9015, one version number for all the objects doesn't even support Microsoft's versions of the application code (as opposed to the "platform version") because you have multiple regional versions and each region has it's own independently changing code.

As for on-prem even though the existing "Version List"s are not the best possible, but, they are quite usable unlike numbers buried in random codeunits. What's more, often the most useful feature of the "Version List" property is that it is trivially readable directly in the SQL database (Object table codeunit 1 "Version List" field ... Sigh, okay, Codeunit 9015 too).

MS/AL code isn't making "Version List" go away, it has never supported it, full stop. This is Okay because you are trying to make the GUID and version number of the Extension provide exactly the same facility. That is a list of version tag (GUID) and version number for each normal Nav object. For applications limited enough (or unintegrated enough) that they can be converted to extensions this is sufficient. The real version control can be done outside Nav.

As for applications that are still impossible to make into Extensions or applications that _will_ conflict (eg anything that uses "Invoice Post. Buffer"."Additional Grouping Identifier") reliable per object version tags are a necessary first step to doing fast and safe upgrades.

Having written all that, I'm not sure that's what you meant.

For any branch that's not a mirror of a release I wouldn't expect the "Version List" to have anything reliable. It would be nice if it did (and we manage to do it internally, for the most part), but you have to do true merges at high rates of change and that's always been annoying with Nav.

Some parts of this read like I'm against extensions. I love that you're officially supporting the old NSC hooks patterns and adding to them in terms of the field and control merging and the rest. But, IMO, limiting to just this is not going to work, for exactly the same reason that merges cannot always be done automatically.

**Comment by StanislawStempin** [comment]
I should clarify that my comment was targeted at the cloud version of the product. The whole base application will always have all objects on the same version. Therefore it does make sense to use just one version number that is obtained through COD417.GetApplicationVersion(). 
In the On-Premise Fall release nothing will change and VersionList can be used as before.
