### ISSUE TITLE
How do I add a ribbon tab to Page Extension...

### ISSUE THREAD

**Issue by fibbert** [Microsoft/AL#2830]
Forgive me if this is asked and answered ... but for the life of me I can't find the answer.

I am trying to add an action to page 463 Jobs Setup. I can't figure out where to anchor my action.  I prefer to add a new tab for it - but I can't anchor it to the existing ribbon either.

The addfirst and addlast require an anchor to define where to add the field.  I have tried &manage, manage, general, &general, etc...

I want to add it to the Actions Ribbon (which has not been created on this page) and promote it.  Is there a primer on this? I am finding this particular area of page design/extension very hard to figure out (mental block).  This was my last attempt ... also failing.

> actions
>     {
>         addfirst("Actions")
>             {
>             group(Sabre)
>                 {
>                     action("Edit User Fields")
>                     {
>                         CaptionML = ENU='Setup ETO User Fields',
>                                     ENC='Setup ETO User Fields';
>                         Image = Setup;

**Comment by qutreson** [comment]
Hi @fibbert, if you want to add an action in the Actions ribbon, you need to use the application area `Processing` as an anchor.

You can find an example on how to relate the action area names and the ribbons tab here: [Adding Actions to a Page - Example](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-actions-to-a-page#example).

**Comment by fibbert** [comment]
Hi @qutreson 

When I do that I get an error on the area(Processing) 

d:\Development\Sabre\Sabre ETO\pgxJobsSetup.al(54,9): error AL0104: Syntax error, '}' expected

This is a PageExtension.  Does that make a difference?

-Rob

**Comment by qutreson** [comment]
@fibbert, the full syntax in order to add an action in the Actions tab is as follows:
```
pageextension 50100 CustomerListExt extends "Customer Card"
{
    actions
    {
        // Add first in General in the Actions tab
        addfirst(Processing)
        {            
            action(MyNewAction)
            {
                ApplicationArea = All;

                trigger OnAction()
                begin
                    Message('My new action');
                end;
            }
        }
    }
}
```

**Result**:
![image](https://user-images.githubusercontent.com/31541422/42498843-9092625c-842d-11e8-9428-ebde50520e92.png)

The keyword `area` is used to declare an area in the `layout` or `actions` section of a new page that you are creating. If you want to add an action or a field from an existing page, you have to use one of the keywords `addfirst, addast, addafter, addbefore` in order to specify where place this new action/field in the existing page. You can read more about page extensions here: [Page Extension Object](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object).
