### ISSUE TITLE
Codeunit ApplicationManagement is missing

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/AL#2847]
Hi All,
I`m pull bcinsider.azurecr.io/bcsandbox-master  last version (13.0.23231.0-W1). 
Cannot found codeunit ApplicationManagement. Please support me
Thanks

**Comment by grobyns** [comment]
Hi,

Codeunit 1 ApplicationManagement has been removed. Did you get the error because you were trying to subscribe to an event in or call a function on codeunit 1 or something else?


I am working on documentation which will include a mapping of where to find the functions/events now that codeunit 1 is not there anymore.


br/Gert

**Comment by grobyns** [comment]
Hi,

I'm closing the issue as there has been reply for a few days. Please let me know if you encounter more issues.

br/Gert
