### ISSUE TITLE
Function Expose C1290: SendRequestToWebService

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/AL#2849]
Is there a reason why Codeunit 1290 SOAP Web Service Request Mgt. has several methods marked as `[External]`, but `SendRequestToWebService`, the very core function of it, is not?

**Comment by hemisphera** [comment]
BTW: The same goes for the other methods therein:

- `GetResponseContent`
- `ProcessFaultResponse`

**Comment by StanislawStempin** [comment]
The underlying functions use System.Net namespace which we do not want to allow in AL. All http network communication should go through the new native AL types since we need to control these at the platform level. 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-restapi-overview

**Comment by hemisphera** [comment]
I understand and I am ok with that.

But then why bother exposing anything at all inside this Codeunit? It's misleading. It looks like an oversight right now. At this point it's better to expose nothing at all so that we developers don't start thinking it should be.

One problem remains though: as long as you don't natively support SOAP I am stuck with custom implementations of constructing SOAP envelopes and parsing result XMLs. Not a really great experience.
