### ISSUE TITLE
Request: Let the SaveAsExcel call return to the MergeDocument procedure instead of throwing an exception

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/AL#2854]
Dear team,

Please see issue #2017 for some background information.

Using the `REPORT.SAVEASEXCEL` function in combination with a report with a Word layout (or just any other than RDLC) will currently throw an exception from the mentioned dll before returning to the `MergeDocument` procedure in code-unit 1.

Instead of throwing an exception that is out of the developers hands, my suggestion is to let the call return to the `MergeDocument` and let a proper message be shown from that function (so that it is also clear to the user in the web client). Then, you can also allow developers to hook into this using the `OnBeforeMergeDocument` (see issue #2161) so that instead of an error, a custom implementation can be used in case a report is saved to excel.

Hope everything is clear! Any feedback on the request in this issue is welcome as well!

**Comment by kalberes** [comment]
Actually looking in more details this seem to be a bug.
**if (not Report.SaveToExcel(.... should not throw.**

This is your ask. Isn't it?

**Comment by rvanbekkum** [comment]
The issue is that when you run the `REPORT.SAVEASEXCEL` function with an RDLC layout, then everything is fine, but when the report in question uses a Word layout, then an exception is thrown as shown in issue #2017. 

In the same issue a note was made by @jensmpmsft that, _by design_, saving a report with Word Layout to Excel is not supported.
I think it is fine that this is not supported, but I think that rather than throwing an exception that does not become visible to the (web-client) user, it would be better to let the method (that was called internally) return to the application in the `MergeDocument` procedure in code-unit 1 (just like any of the other `REPORT.SAVEAS...` functions), where this case is handled (by default, at least) with an informative error message.

I hope this clarifies the request for this issue. If you have any questions or feedback though, please let me know!

**Comment by kalberes** [comment]
Hi
This code should throw an exception _Report.SaveToExcel_ and it will not be fixed in the near future.
But this one should not throw IMO _if (not Report.SaveToExcel_ this is why I have marked it as  a bug.
Does that satisfy your request.

**Comment by rvanbekkum** [comment]
Yes, I do partially agree, it would be fine if the `REPORT.SAVEASEXCEL` function would give an error.
I think that the call `NOT REPORT.SAVEASEXCEL` still giving the exception is due to the same issue, being that the exception is thrown from the `SaveAsExcel` method from the dedicated dll.
Therefore the request is to not throw an exception from the method, but instead let the process continue and get back to the `MergeDocument` procedure in code-unit 1 where a check for this case (i.e., saving to Excel) could be done, for example, adding the following:
```
...

IF ReportAction = ReportAction::SaveAsExcel THEN
  ERROR(NotSupportedErr);

...
```

What are your thoughts on this?

**Comment by kalberes** [comment]
Hi unfortunately there i no more codeunit 1. @grobyns is the above possible to be fixed from what codeunit 1 has been replaced with?
Regardless there is a bug there since we are breaking the AL method call contract. If an AL method is encompassed in an IF statement then no exceptions should be thrown but an error message.

**Comment by grobyns** [comment]
Hi all,

It took me a while to understand the solution suggested here so let me try and see if i got it right:

Currently, when you run (in code) a report with SAVEASEXCEL, an exception will be thrown (at the end of report execution) IF the report was using a Word layout.
The suggestion is to not throw the exception but an 'error'. This would mean that if the call was made as IF SAVEASEXCEL, the code would swallow the 'error' and let the call continue to MergeDocument (where there could then be a nice message in a c/al ERROR call instead).

did I get that right?

I don't see why the removal of Codeunit 1 or the change to events would change this solution, it should work just the same as before. The code would continue to the new MergeDocument event in Codeunit 2000000005 and call the MergeDocument subscriber in Codeunit 44 which in turn will call the MergeWordLayout method in Codeunit 9651 where there is indeed an event called OnBeforeMergeDocument.

It can of course be a bit confusing if this 'feature' gets abused. You call SAVEASEXCEL and now potentially get a Word doc or a Pdf or something else. It could be anything since the OnBeforeMergeDocument can put whatever it wants into the stream and that's what the user will get.

anywho, I see no blockers from the codeunit 1 removal.

Cheers,
Gert

**Comment by rvanbekkum** [comment]
Hi @grobyns,

> Currently, when you run (in code) a report with SAVEASEXCEL, an exception will be thrown (at the end of report execution) IF the report was using a Word layout.
The suggestion is to not throw the exception but an 'error'. This would mean that if the call was made as IF SAVEASEXCEL, the code would swallow the 'error' and let the call continue to MergeDocument (where there could then be a nice message in a c/al ERROR call instead).
> did I get that right?

Yes.

> I don't see why the removal of Codeunit 1 or the change to events would change this solution, it should work just the same as before. The code would continue to the new MergeDocument event in Codeunit 2000000005 and call the MergeDocument subscriber in Codeunit 44 which in turn will call the MergeWordLayout method in Codeunit 9651 where there is indeed an event called OnBeforeMergeDocument.

Agreed. I understand the implementation has recently been moved to codeunit 44.

> It can of course be a bit confusing if this 'feature' gets abused. You call SAVEASEXCEL and now potentially get a Word doc or a Pdf or something else. It could be anything since the OnBeforeMergeDocument can put whatever it wants into the stream and that's what the user will get.

Yes, I agree, this should obviously not be abused in such a way (of course, the same holds for any event publisher in the application, which should be handled with care). This of course doesn't exclude that there are more sensible reasons to subscribe to the event. 
Therefore, the last part of my suggestion was just a small addition, boiling down to that it would be good to have the report execution reach this event as well before cancelling the process in the `MergeDocument` procedure.

@kalberes Does this provide you with sufficient information to look into this issue?

Thank you in advance!

Kind regards,
Rob

**Comment by kalberes** [comment]
I can look at why the server throws in case that it should not throw. The rest is out of my jurisdiction.

**Comment by StanislawStempin** [comment]
The issue has been fixed. The code will no longer throw an exception if the return value is used.
