### ISSUE TITLE
Creating a new item with Reordering Policy and Fixed Reorder Qty triggers a purchase planning, even without a demand

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#2859]
If I create a new Item with Reordering Policy and Fixed Reorder Qty  
Then I set the Reorder Qty to 25 and Reorder Point = 0
Running the planning it suggests a purchase of 25 pcs, even if there are no demands.

Changing the reorder point to -1 (which was the workaround in the older versions) does the same.

I believe that, if there are no demands and the Reorder Point is zero, the purchase should not be triggered.

**Comment by ChethanT** [comment]
This is "by design" reordering policies based on reorder point expect are designed to support "ad-hoc" demands, means they are supporting inventory on some level
If you want planning engine to be triggered by demand - then you should consider Lot-to-lot policy (or order).

===
For bugs in the application please log via: https://mbs2.microsoft.com/support/newstart.aspx 
Ideas and feature requests for application functionality should be logged through: https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1 

Regards
Chethan Thopaiah
Software Development Engineer, Microsoft
