### ISSUE TITLE
"al.enableCodeAnalysis" issue with object id

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/AL#2883]
Hi,
I have ID range specified in app.json from 70150321 to 70151320 and create a codeunit with ID 70150336
change "al.enableCodeAnalysis" to true - VSCode detects an error: Codeunit 'TEST' has an ID of [70150336]. It must be between 50000 and 99999.
Change ID to 50000 - VSCode detects an error: The application object identifier '50000' is not valid. It must be within the allowed range '70150321' - '70151320'.
AL version 0.16.19969
"NAV" version: 12.2.22932.23097

**Comment by thpeder** [comment]
Hi @AndriusAndrulevicius,
It is because you haven't specified which analyzers to run, so it defaults to all of them and AppSourceCop and PerTenantExtensionCop have conflicting rules for ID ranges.
![image](https://user-images.githubusercontent.com/24276180/42684999-1512d26c-8692-11e8-8c46-4c29970c4f6e.png)

Read more about it here: [Using the Code Analysis Tool](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool)

**Comment by SUD-D365** [comment]
Hi @AndriusAndrulevicius , I think codeAnalyzers **AppSourceCop** will work for you.
Give it to a try.

**Comment by ndpatel0074u** [comment]
@AndriusAndrulevicius  If you are trying to deploy this package on NAV 2018, then you will have to check that developer licence with Object range permissions is uploaded or not.
