### ISSUE TITLE
No cache entry group object was found 

### ISSUE THREAD

**Issue by minamelika** [Microsoft/AL#2936]
Hi!
could you please help me investigate why i'm not able to publish any extension, even "Hello World" to sandbox. it was ok and i tried to clean the sandbox, since i did a lot of tests, so i "reset" it, after that i'm stuck with the following error every time i publish extension: 

[2018-07-18 09:41:37.31] Sending request to https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize

[2018-07-18 09:41:46.40] The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: No cache entry group object was found -- Type:Query; Id:1850; Group:25

**Comment by devkitt** [comment]
Issue seems to be resolved as of this morning. I was able to publish after changing nothing.

**Comment by MikeGlue** [comment]
I'm getting this issue in my local container. Running BC image 13.0.23500.0-us. Any resolution to this?

**Comment by devkitt** [comment]
For me, it just started working again. I didn't do anything differently.
Took over a week and didn't see/hear anything on how this might have been
resolved. Sorry I can't be of more assistance.

**Comment by cmrudolph-msft** [comment]
We did see this once in the online sandbox and a restart fixed it (internal temporary state).

@MikeGlue - does restarting the NST in your container affect things?

We will try to get to the root cause regardless, but this might help in the meantime.

**Comment by rishiaurrishabh** [comment]
I found the reason for this issue, there is an extension provided by Microsoft for "Sales And Inventory Forecast", it is using this range of object which is causing the issue.
Once you Uninstall and Unpublish them from your sandbox then your Package will be Published without any Issue.
Please let me know if this works for anyone because I saw this range of object used by this extension in metadata table sometime back. So to me the issue is causing because of this extension.

Thanks!

**Comment by miljance** [comment]
Hi,

Deinstallation of Sales And Inventory Forecast did the trick for me!

**Comment by rishiaurrishabh** [comment]
Good to hear that ! :)

**Comment by kavila02** [comment]
I had the same problem. I was running a sandbox environment in Docker and I just restarted Docker and that solved my issue.
