### ISSUE TITLE
CU99000792 - CreateProdOrder is blocked for extension development

### ISSUE THREAD

**Issue by graknol** [Microsoft/AL#2941]
The CU99000792 is critical for automatically creating production orders from sales lines. Currently it is flagged as unsafe, but I couldn't quite see why. This functionality is critical for one of our clients.

- AL Extension Version: 
![bilde](https://user-images.githubusercontent.com/1364029/42923680-13273bde-8b27-11e8-93c1-0a0d0950fa23.png)

- Server Version: NO Dynamics NAV 11.0 (23019)

```al
procedure Foo(S: Record "Sales Line")
var
    C: Codeunit "Create Prod. Order from Sale";
begin
    C.CreateProdOrder(S, ...); <-- This function is blocked.
end;
```

Thanks in advance.

**Comment by qutreson** [comment]
Hi @graknol, the method CreateProdOrder has been made external some time ago, see issue #1710. I don't get any error when using it our latest master as you can see below.
![image](https://user-images.githubusercontent.com/31541422/42929903-b711725a-8b3b-11e8-82e0-397123c4e682.png)
In order to have access to it, you should either upgrade to a newer version of the extension and of the compiler or contact customer support in order for the function-expose issue to be backported to the version you are using (see [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#will-features-from-the-latest-dynamics-365-releases-be-back-ported-to-nav-2018)).

**Comment by graknol** [comment]
Hi @qutreson, I'm so sorry, I thought I'd searched well enough through the issues. Thanks a lot though, it's not really a problem right now since the client's running NAV 2018 On-Premise, but it was just a concern for later upgradeability down the line to BC365.

But since that's solved I'll close this issue 😄.
