### ISSUE TITLE
Installing an extension error

### ISSUE THREAD

**Issue by armela1981** [Microsoft/AL#2977]
I have created an extension.
I tested it in my test environment (running on Docker) and all works well.
I package it.
Went to the install it on my BC 365 running on the cloud and it fails with the following error.

Package validation failed due to the following error(s): (1,13): error PTE0004: Table '50098' is missing a matching permission set.
(1,13): error PTE0004: Table '50099' is missing a matching permission set. - Job Id : c712f7d9-989f-4b47-82e0-1bed9221f3a6

Any ideas ?
Thanks

**Comment by rishiaurrishabh** [comment]
you have to create an xml file and define all table objects there with a Role :
![image](https://user-images.githubusercontent.com/39942971/43057122-d66f2096-8e5d-11e8-8ace-08158e4f909d.png)

In the above Image RoleID is the role in which you want to add your Extension table objects, ObjectType as 0 means TableData and 1 on rest of the Tag means Yes.

you can either create it manually or you can also Export this same xml by running **Export-NAVAppPermissionSet** command on powershell and then you can import same into your project in .vsCode folder then AL will automatically consider that as an permission set file and create Roles and permission accordingly.

Note : You are not getting those error on your Al Package because your code analysis is disabled in visual studio code.you can enable it by going to File-->Prefrences-->Setting and type al.enableCodeAnalysis and make it true.
![image](https://user-images.githubusercontent.com/39942971/43057271-d4784596-8e5e-11e8-8fff-064348282329.png)

Once your permission set are defined and you publish this package you will notice on the output window there is a message showing that : 
info **AL1027: The file at location '<FileName>' matches the definition for 'PermissionSet'.**

**Comment by ajkauffmann** [comment]
With the June developer preview, you can also generate the permission set file with VS Code or export them directly from the client. See https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/ for more info (scroll down to Permission Set Creation).

**Comment by armela1981** [comment]
I also have a questions.
Sorry new to this and it is a fast moving subject. As soon as I think I got a handle on this, new functionality is coming out.
So I was looking the link on the Developer June Update. None of the stuff is available on my local setup.
I don;t see the option to export permission sets, nor do I see an AL Command of "Generate Permission Sets".
How are you guys staying up to date and updating your local environments ?
Sorry, too many questions today.

**Comment by StanislawStempin** [comment]
The original question seems to have been addressed. As to your last question about search there was a known bug in our service. It is being rolled out to all tenants and should be available to all tenants by the end of next week. 
If you want to make sure you're running on the latest version you can Reset your sandbox and it will get recreated on the latest bits.

**Comment by armela1981** [comment]
Thank you for your reply.
Quick question when you say "Reset Sandbox" are you referring to running the "CreateBCSandbox" on the Windows Powershell ISE ?
Want to make sure I am understanding that correctly.

**Comment by armela1981** [comment]
Hello everyone.
So there was an update rolled out on 7/29 but that did not address the Search issue.
I did the following to update my Sandbox which runs on Docker.
1.   Created a PS1 file from our Live tenant.
2.  Run the  above file on the on the Windows Powershell ISE 
3. The environment was reset and new environment created.
4. Open Visual Studio. F5 on my project to deploy to Sandbox Web.
5. Search is not working.

Any ideas ?? What am I doing wrong or did the roll out not address the search issue ?
Also in the system information I have different versions between databases.
1. Live Tenant has 12.2.(23241).
2. IN my new sandbox that I created above I have 12.2.(23097)

**Comment by armela1981** [comment]
Thank you for your reply.
I already checked all of that, but was told on the above post that there was a bug that was going to fix the search button.

**Comment by rishiaurrishabh** [comment]
Ok , Normally I don't see any trouble showing a page on Menusuite, will it be possible to show paste the snippet of that page here?

**Comment by armela1981** [comment]
Yep. Here it is

page 50098 "Objects Custom View"
{
    Caption = 'Objects_List';
    Editable = false;
    PageType = List;
    SourceTable = AllObj;
    UsageCategory = Lists;
    ApplicationArea = ALL;
    SourceTableView = SORTING("Object ID")
                      ORDER(Ascending)
                      WHERE("Object Type" = filter(Table));
                            

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field("Object Type";"Object Type")
                {
                    ApplicationArea = all;
                    Caption = 'Type';
                    ToolTip = 'Specifies the object type.';
                    Visible = true;
                }
                field("Object ID";"Object ID")
                {
                    ApplicationArea = All;
                    Caption = 'ID';
                    ToolTip = 'Specifies the object ID.';
                }
                field("Object Name";"Object Name")
                {
                    ApplicationArea = All;
                    Caption = 'Name';
                    DrillDown = false;
                    ToolTip = 'Specifies the name of the object.';
                }
                field(COMPANYNAME;COMPANYNAME)
                {
                    ApplicationArea = Basic,Suite;
                    Caption = 'Company Name';
                }
                field(noofrec;noofrec)
                {
                    ApplicationArea = All;
                    Caption = 'Number of Records';
                }
            }
        }
    }

    actions
    {
    }

    trigger OnAfterGetRecord()
    var
        
    begin
        


        Clear(recrefvar);
        recrefvar.OPEN("Object ID");
        

        noofrec:=recrefvar.COUNT;
    end;

    var
        ExtensionName: Text;
        recrefvar: RecordRef;
        noofrec: Integer;
}

**Comment by armela1981** [comment]
I thought permission sets  XMLports were for tables only and not pages. Are you saying that I need to define those for pages as well ???
Thank you.

**Comment by rishiaurrishabh** [comment]
No, I mention that for some other issue, the way I see it is that your are trying to show a virtual table on menu suite which NAV is not allowing.
if you put that as a statrup page then it is visible on BC but it doesn't work if you want it on menu suite, not sure if its a bug because if you try to do similar thing on rtc of sandbox env. then also it is just showing the page but list view is not visible for that page.
I recommend you to use temporary table and fill it with AllObj table at the time of opening the page.
rest other things are fine the page, I changed the table name with customer and the page works on BC.

Thanks!

**Comment by StanislawStempin** [comment]
Which version of the server and AL Language are you using?  

To refresh your online Sandbox to the latest version please go to to Sandox Management page on the production tenant and click Reset. This should result in provisioning Sandbox on version 12.3 on which you can retry the search problem.

**Comment by armela1981** [comment]
Thanks for the reply.
How can I tell which version of the AL Languange I am using ? I am on Visual Studio and on the extensions Section I see AL Language 0.16.19969.
How can I tell which server am I using ?  I am running my Sandbox on Docker.
As far as refreshing the sandbox, I don't see an option on the Manage screen for Sandbox to refresh.
I see "Manage your Dynamics 365 instances" and I only see the production environment. I created a PS1 from Production and I am using that for my Sandbox running on Docker.
I also re-installed my app in production after the update and the Search is still not working.
Is there any documentation anywhere to guide me through the refresh of sandbox. Maybe I am not doing this right ?
I am assuming the updates automatically get installed in the live tenant.
