### ISSUE TITLE
File APIs are not available in Extensions V2. What to do? - How I can use Exists function?

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/AL#2981]
I check the wiki and I don't find the answer I would like to know how we can check If the file exist before open it?

**Comment by salgiza** [comment]
Are you developing for Business Central (hosted) or for NAV2018 (on-premise). 

If it's the former, you don't have access to the filesystem. In order to create a file, use a TempBlob record, write to it, and then download it to the users's computer using DownloadFromStream (in Codeunit 419).

If it's the later, add "target": "Internal" to the app.json, so that the AL environment knows you can use all methods in NAV, including those that access the filesystem.

**Comment by sssolammm** [comment]
Thanks for the answer @salgiza know I understand the reason, Im using Business Central hosted.
