### ISSUE TITLE
[Function expose] Codeunit 397 Mail - CreateMessage & AttachFile

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/AL#3046]
In Codeunit 397 the function CreateMessage and the function AttachFile should be external. Thanks.

**Comment by IhorHandziuk** [comment]
Thank you for your request. Procedure CreateMessage will be external in the next release. Regarding AttachFiles: now we are putting a big effort into replacing files with streams in the entire application (so we don't want this particular procedure to be used in the cloud). 
If your particular use-case doesn't strictly require fetching the file from a filesystem, please, use other approaches. Otherwise, please, wait until we will finish our effort with streams in the future.
