### ISSUE TITLE
Missing symbols for XML Port

### ISSUE THREAD

**Issue by freyrdanielsson** [Microsoft/AL#3074]
- AL Extension Version: 0.12.17091

- Server Version: IS Dynamics NAV 11.0 (22292)

I am trying to test an extension application, here called: **Dependency** by creating a Unit Test app, here called **Unit test**.

The Unit test has a dependency on the Dependency app:
![issue1](https://user-images.githubusercontent.com/32617790/43412370-875bdf5c-941c-11e8-9c16-e4cbf089563f.PNG)

After downloading symbols in the Unit test app, the AL Object Viewer shows that the unit test app now has access to the Codeunit 50100 - Utils.al as expected.
![issue2](https://user-images.githubusercontent.com/32617790/43412953-39c93454-941e-11e8-922e-e5d3d8e6cfcd.PNG)

But the XMLport 50100 - XmlPort Example.al is not available.
![issue3](https://user-images.githubusercontent.com/32617790/43412914-1bdb2a7e-941e-11e8-93b7-87cb3e0db947.PNG)

I am able to use the XMLport 50100 - XmlPort Example.al in the Dependency app, where it is created, but it is unavailable in the Unit test app.

![issue4](https://user-images.githubusercontent.com/32617790/43413111-9f82d368-941e-11e8-8a17-55c92ea9e80d.PNG)
There is no error in the in the Dependency app, but in the Unit test I am getting:
[AL] XmlPort 'XmlPort Example' is missing

Is this an expected behaviour, and if so, is there a way of getting access to the XML Port object in the Dependancy app?

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Developer Preview release. If the problem reproduces on the latest preview version we will look further into it. Otherwise please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
