### ISSUE TITLE
Improvement for color coding of keywords

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#308]
When you use a variable name with the same name as a keyword, like a type, it will be colored.
![image](https://user-images.githubusercontent.com/19155831/27457362-c604faaa-57a4-11e7-95cd-99f889d789a4.png)

With this modification in the alsyntax.tmlanguage file, the coloring will only be done for keywords found after a colon or colon + space
![image](https://user-images.githubusercontent.com/19155831/27457410-ef1508a4-57a4-11e7-811f-3bfcca7ba1a2.png)

`\b(?i:(Action|Array...`

is changed to:

`\b(?i:(?<=:|:\s)(Action|Array...`

Here is the result with this modification applied:
![image](https://user-images.githubusercontent.com/19155831/27457424-fcfd7ab4-57a4-11e7-83d0-17a327ae96c2.png)

**Comment by StanislawStempin** [comment]
We looked more into it but the problem is that types appear in more contexts than just variable declaration (for example they are used in Field declarations). Regular expressions can be used to get proper coloring in most of these contexts but they will still miss some. 
For example, invoking static methods on types:
StaticType.Run();
StaticType should be properly colored in that context as well but this can be only detected semantically. As long as VS Code relies on regexp for coloring we cannot handle this situation properly.

Therefore, we prefer that variables named the same as types get incorrectly colored rather than missing some of the valid type coloring cases.
