### ISSUE TITLE
Cannot extend a table with Autoincrement

### ISSUE THREAD

**Issue by cherabomb** [Microsoft/AL#3113]
Running NAV 2018 CU4 OnPremise (11.0.21441.0)

Summary: An AL extension on a table with an AutoIncrement Key causes the entire NAV application to fatally crash OnInsert to the table. 

The C/AL table we extended had a composite key, Contact No. + Entry No., and Entry No. was set to autoIncrement. After publishing an extension to the table, we were unable to insert records into it any more. We were unable to debug the issue because it would not break into any error. Both Windows and Web clients simply crashed fatally - the web client saying something like, "Oops, that didn't work."

After uninstalling the extension the insert on the table worked again. We removed the AutoIncrement on Entry No. in the C/AL table and redeployed the extension, and the error no longer occured.

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel and provide all necessary details to reproduce the problem.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
