### ISSUE TITLE
Suggestion: Native support for common Azure functionality

### ISSUE THREAD

**Issue by erikrijn** [microsoft/AL#316]
Would it be possible to get native support for common azure functionality?
I've always used the C# api's for blob storage and documentdb (cosmos db), which made it really easy to integrate. Of course, they all have REST api's as well but having native support makes it much easier.
I would suggest blob storage, cosmos db for multi region document storage and Azure Fucntions for moving .NET vars to Azure.

**Comment by StanislawStempin** [comment]
The overall theme of closer integration with Azure functionality is on our backlog. We do not have any concrete timeline yet.

**Comment by erikrijn** [comment]
Thanks for the info. I think for now the most important one is blob storage, as we don't have access to a file system anymore. It's a nice cross-selling opportunity for Microsoft as well ;)
Do you have a public backlog? I don't want to keep bothering you with suggestions that are already in consideration.

**Comment by pborring** [comment]
These integrations mainly belong to the System app, and since the filing of this suggestion 6 years ago, a number of modules have been added, including Blob Storage. For more, see  https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-system-application-overview

Partners can also contribute more functionality to that.

Thus closing this entry
