### ISSUE TITLE
How can I install a new language next to the current language in Business Central?

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/AL#3192]

**Comment by sorenfriisalexandersen** [comment]
Could you elaborate on this question?
Are you trying to add a language that has not previously been part of Business Central and build a translation app?

**Comment by Chingyz** [comment]
Thank you for your response.

Currently I am working in a BC-nl (the Netherlands) image,  the fieldcaptions are translated to Dutch automatically.
How can I retrieve the fieldcaptions for other languages as well in the Dutch version?
Is this possible or do I have to change fieldcaptionreferences to labels?

**Comment by ShadowXVII** [comment]
To extend this question, what would be the best way to implement a multilingual version of Business Central? Will localizations become extensions?

**Comment by sorenfriisalexandersen** [comment]
We are planning to make localizations into extensions. Though long term, since this is a large effort.

Please see this information regarding translations: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translation-and-localization-apps
