### ISSUE TITLE
Automation data type

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3250]
Hi guys,
I would like to know how to use the automation data type in Visual Studio Code or is it not possible to use?

**Comment by StanislawStempin** [comment]
We do not plan to support Automation data type going forward.

**Comment by malue19** [comment]
Ok and how should I create my variables of data type automation from C/SIDE now in Visual Studio Code, when there is no support for it? Is there an alternative? Another data type which has a similar behaviour?

**Comment by StanislawStempin** [comment]
The Automation data type would not work in the Web Client anyway. If your solution targets On-Premise and Windows Client only then your only option is to continue using C/SIDE. 
But overall I would recommend to start thinking about how to migrate the solution to an approach that will work in AL in the future since C/SIDE will be retired at some point.
