### ISSUE TITLE
License check when publish - error

### ISSUE THREAD

**Issue by svwfr** [Microsoft/AL#3309]
Hi, 
When I publish an app to NAV2018, the compiler does a license check to see if the app use objects that is not assigned to the customer licenses. This flaw has a work around by upload the developer licenses before publishing and then reload the customer licenses. This work around demands to restart the service and throw out all active sessions. 
If you not succeed with update your app by publishing because of error of the license, the original app is first removed before the error occurs. So suddenly the customer does not have the solution at all.
Why is this object-id-check done only when publishing, as the solution accepts extended object ids when first installed?
I know this issue was addressed earlier, but had none hit when search it up again. That's why I open this as a new Issue.

**Comment by thpeder** [comment]
HI @svwfr,

It sounds like you are publishing your app to the customers running system from VSCode, but the recommended way of updating extensions for production systems is to use the Powershell command since that also allow to run upgrade and have multiple versions of the same extension published, and in general more fine grain control of what happens.
You can also use [runtime packages](https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-creating-runtime-packages) to avoid the licenses check when publishing the extension at your customers system.

**Comment by svwfr** [comment]
Thanks for answer, I'll check out Runtime packages, as was new for me.
