### ISSUE TITLE
Assisted Setup / Business Setup Deletes ALL existing G/L Accounts

### ISSUE THREAD

**Issue by peikba** [Microsoft/AL#3375]
Running the Assisted Setup: Business Setup in an existing company, I created a Excel template.
Here I added: 
 - One new G/L account
 - One New Customer
 - One new Vendor 
 - One new Item

After implementing the template, the customer, the vendor and the Item were added to the tables.

However, the Chart of Accounts looked like this: 
![image](https://user-images.githubusercontent.com/33752561/44298247-c917ff80-a2df-11e8-9d64-0b90dded4135.png)

All entries are still there but the G/L accounts are deleted.
![image](https://user-images.githubusercontent.com/33752561/44298255-e1881a00-a2df-11e8-8b17-14e738d4464f.png)

I don't think,  that was the intended result :)

Thank you Rikke Levin from C2IT for the tip.

**Comment by StanislawStempin** [comment]
This issue is not related to AL or Development Tools. 
Please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
