### ISSUE TITLE
Convert C/AL to AL with finsql and txt2al 

### ISSUE THREAD

**Issue by malue19** [Microsoft/AL#3439]
Hey guys, I am trying to convert standard objects from C/SIDE to VSC. Therefore I found a video, where is described, how to do this:

[https://www.youtube.com/watch?v=HCaooHKxBrM](https://www.youtube.com/watch?v=HCaooHKxBrM)

Unfortunately I get an error, when I exectue the written script. The command finsql.exe and txt2al are written wrong or could not be found.

`finsql.exe Command=ExportToNewSyntax, File="D:\CAL\fornav.txt, Database="Demo Database NAV (11-0)", ServerName=.\NAVDEMO ,Filter=Type=table;ID=231,`

`pause`

`txt2al --source=D:\CAL\ --target=D:\AL\ --rename --type --extensionStartId 50100`

`pause`

**Comment by thpeder** [comment]
Hi @malue19,
If you are using Powershell then you need to remove the spaces between the commas and have the filter in quotes, otherwise in the command prompt it should work just fine:
`finsql.exe Command=ExportToNewSyntax,File="D:\CAL\fornav.txt,Database="Demo Database NAV (11-0)",ServerName=.\NAVDEMO,Filter="Type=table;ID=231"`
If you still can't get it to work then you can add `LogFile=C:\finsql.log` and get a more detailed log.

**Comment by malue19** [comment]
Hi @thpeder, 
thank youn for your help. So that were my mistakes^^ but after running your statement I do not get the file called fornav.txt 
I changed also from D to C, to look for the file on my desktop, but it did not appear.

**Comment by Joriek** [comment]
@malue19 
You forgot a " at the end of your file path.

finsql.exe Command=ExportToNewSyntax,File="D:\CAL\fornav.txt",Database="Demo Database NAV (11-0)",ServerName=.\NAVDEMO,Filter="Type=table;ID=231"

After that you have to execute the following command (from your client installation directory)

txt2al --source="D:\CAL\" --target="D:\CAL\NewDir\"

**Comment by malue19** [comment]
Hi @thpeder ,
now it works^^

**Comment by thpeder** [comment]
What did the logfile tell you?
Are the rest of the parameters correct? is your database actually called that?
