### ISSUE TITLE
How to view the report dataset on web client?

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#3471]
Hi there,

Got a question: IS there a way to view the report dataset on Web Client? Like we can with _About This Report_ feature on the Windows Client.

**Comment by ashik-ivor** [comment]
By viewing the URL, we can get some of the information's current page and current reports.

**Comment by kalberes** [comment]
According to the owning team:
This is not possible on the web client due to the architecture differences on the web and win. This applies to the About This Page feature, too.

**Comment by lvanvugt** [comment]
> This is not possible on the web client due to the architecture differences on the web and win. This applies to the About This Page feature, too.

Clear, so this issue becomes a feature request, as developers do need this to be able to check the result of their development.

**Comment by kalberes** [comment]
More answers from the owning team:
We are currently not supporting About this Page/Report feature in the web client. We are planning to add this functionality in the short term.

**Comment by lvanvugt** [comment]
Understood. Could you than add the tag **Enhancement** to this issue? Thanx.

**Comment by StanislawStempin** [comment]
Since this is mostly client functionality I will close it here and let's track it through the existing suggestion on Ideas page (which is at the moment top voted suggestion):
https://experience.dynamics.com/ideas/idea/?ideaid=f25c48b9-5578-e811-9cca-0003ff68ec32

I'm not sure if it contains About This Report but it's worth mentioning that in the comment.
