### ISSUE TITLE
Translation XLIF is not used after renaming objects

### ISSUE THREAD

**Issue by Walwode** [Microsoft/AL#3487]
hi, i have checked for any XLIF problems, but found only posts about the how the xlif file itself is wrong and the target was missing, etc.

My problem is, that even i have changed my language (and region) to "DEU", nothing in my app is translated. The Txt2AL created two files, "translation-de-DE.xlf" and "translation-en-US.xlf". I have than fixed all compile errors and updated the object names (with [F2]). My app is total in english (the base app is correctly in german).

I have than added the feature TranslationFile to app.json and created a new translation.g.xlf [Link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files)). I have removed almost all of the content, to check, and left only a page caption and two field captions. This one is now working. The only thing that is changed is the trans-unit id and note (there you can see the object renaming)

Left side = working, Right side = not working
![image](https://user-images.githubusercontent.com/33229214/44781018-9ee9fb80-ab83-11e8-97ea-81fd696193fc.png)

What else could be the problem? I don't want to retranslate 2,500 objects including fields and actions...

PS: I have had on only de-DE xlf file in the directory when compiling the app

**Comment by esbenk** [comment]
The object rename is problem. The trans-unit id-attribute is a path the uses element-name hashes to identify the target element. We chose to use name-hashes because of a length restriction for the id.

By renaming the object, all trans-unit-id’s for that object is changed. We have a note for text that contains the name. Given that you have the old and new name, you could write a script to fix the problem.

We will try find a good way to handle the object rename scenario.

**Comment by Walwode** [comment]
thank you for the information.
I thought the new caption feature would help us to work faster and easier with the translations. I expected the XLIF file to contain the translation of a caption, like in a translation memory, wherever it is used inside the solution. That would give me the opportunity to make only once the translation and reuse that caption all over the app.

What exactly is the purpose of the new caption feature?

Disadvantages
- it takes longer to make a translation (i can't make is just in time of development, i need to post-process it with an external application)
- it's not compatible with rename
- won't help with the problem of translation multiple occurances differently

Advantage?

**Comment by Walwode** [comment]
How would you create such a script to copy the new hashes? The XlifGenerator xml node does contain the new object name. So i can't go by finding the "old" translation node.
The only thing i can image is to search for the caption translation in the migrated file and fill all occurences of the same source in the new file. But i'm not sure if i'm loosing any other information by this :(

**Comment by esbenk** [comment]
Separating code and translatable text is an advantage when you use external translators. You can ship of an .xliff file to a translation agency. Xliff is a standard used by most translation agencies. We have had many request for that separation.

Externalizing translations requires a way of identifying the translation target (field, caption, tooltip, ...) and that must be a path (e.g. you can have a field with the same name on two tables). The drawback of this is of course that if the identifying path changes (e.g. rename) it will show up as a new text for translation. It this particular case it can be argued that we could use the objects ids as the first part of the path, but we are trying to prepare for an id-less future in as many areas as possible and it will just change the problem to a renumbering problem.

Translating multiple occurences differently are some cases what you want. You would normally use a translation tool to track that kind of information. This is also the reason for .xliff being a verbose format that can contain additional information about a text.

I agree that xliff gives most benefits when using external translators. We are considering if we can support a more simpler in-house translation in a better way.

To solve the problem at hand, you will need a mapping between e.g. "Table 4029029196" and "Table 3015245791" and update that part of the trans-unit id. In order to establish that you need the mapping between old and new object name. We can't see the old name during compilation.
Dependent on the amount of object renames, you have two different options:

1. If it is a small number of files, you can manually establish the mapping by looking at "Xliff Generator" note in both files and do a search and replace.
2. For a larger number of renames, provides that you create the object old -> new map, you can script your way out it by reading both files to construct the name -> id map for each and then create id -> id map.

**Comment by Walwode** [comment]
I understand the importance of separating the translation from the source code. Yes, that was possible in C/SIDE by the Translation Export/Import, we even used it for new languages. Yet, you need a "scripter" to handle the new XLIF files. Therefore you made it more complex and more time consuming. I'm exited to see, how our operations team (who are not scripters, but pure C/AL developers) will handle with the upcomming problems. So far i don't see much of a difference, but using a more common standard of translation file, with the fallback of more complexity and time for usage.

**Comment by StanislawStempin** [comment]
Translation memory will not become part of the compiler. It is a job for the translation tool.
Having said that, we will add compilation warnings if we detect translation units that are out of sync with the source code or out of sync between languages.

**Comment by JavierFuentes** [comment]
I do not get the translations into Spanish (es-ES) of either a new Page based on a new Table or a new field on a standard table.

My infrastructure is on an OnPremise instance of Business Central.

In my case, the ID that is generated automatically does not change if I delete the .XLF file and regenerate it again by activating `"features": ["TranslationFile"]` in `app.json` but for more tests I do, when uploading the extension I only can see the names in English ... not even restarting the instance or the web server is solved.

I have also tried to download the source code of the deployment by pressing F7 in Visual Studio but it seems that the language files are not downloaded (only .AL does) so I can not know if there is something wrong in the metadata that the server has. 

__Is it expected that the .XLF will also be downloaded when pressing F7 on VSCode?__

However, if I manually download the .ZIP of the extension, the Translations folder with the 2 files is there and when I compare its contents with the files I upload are identical ...

I Attach here both .XLIFF files...
[translations.zip](https://github.com/Microsoft/AL/files/2592196/translations.zip)


Any idea what the problem may be?

**Comment by JavierFuentes** [comment]
By the way, CaptionML on the page does not solve my problem either ...

`CaptionML = ENU = 'My First Table List Page', ESN = 'Mi Primera Página';`
