### ISSUE TITLE
ShowCaption not working?

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#3495]
Based on the Customer Statistics page I did build my own Statistics page in a NAV 2018 extension. For each group in the fixedlayout group I also set the ShowCaption property to false. But it doesn't seem to work . The caption is shown anyway. In web client and windows client.
Having no access at the moment to D365 BC I cannot check it there, but it surely is a bug in NAV 2018 CU6 and CU8.
The property does work on field controls in normal page (group) s.

Anyone else experienced the same and/or can check on BC?

**Comment by StanislawStempin** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
