### ISSUE TITLE
[Question] Code behind current screens

### ISSUE THREAD

**Issue by James-French** [Microsoft/AL#3676]
- AL Extension Version:  0.16.19669

- Server Version:  12.2

Hello All, I hope I have done everything correctly, I've read the readme, but am unsure if this is the correct way to ask a question. The question I have is, is there any way to see the code that makes up something (Object, page, extension etc) in Business Central? For example, I am trying to replicate the Special Sales / Discounts screens from Items but it would be very useful if I could peek at the code behind any given thing, as I still have a lot to learn! Attaching a picture of the screen with the view existing prices/discounts and the ribbon where you link to the card to define them.
![items pricing_discounts](https://user-images.githubusercontent.com/43038583/45428166-a96dc000-b66e-11e8-9f1f-846b326f3e48.png)

**Comment by thpeder** [comment]
Hi @James-French,
In VSCode if you place you cursor on the page ID or name in a variable declaration for instance, then you can use Go-To Definition (F12 or right mouse click) which will get the source code for the object.
That works great for AL objects, but if you want to see the current pages in the product that are not made as AL objects then I would recommend you to get a docker container with the sandbox in, because with that you have access to the previous development environment that can open objects in the database made with the previous C/AL format.

If you don't want to learn that tool then you can also extract the objects from the database in the docker container and convert it to the new format, but that still has a few bugs.

To create the docker container you should look into navcontainerhelper, it is a Powershell module that helps you set it up.

**Comment by James-French** [comment]
Thank you! Go-To definition has worked wonders for me. I will keep the docker container stuff in mind for the future as well.
