### ISSUE TITLE
Ribbon overlaps with Content Header on worksheet page type with DeleteAllowed/InsertAllowed false

### ISSUE THREAD

**Issue by spapke** [Microsoft/AL#3715]
On a Worksheet type page with DeleteAllowed/InsertAllowed false, the ribbon will overlap with the content header. This results in the search and designer icons overlapping the close icon in the upper right corner of the page.

![image](https://user-images.githubusercontent.com/29461382/45500792-81a15980-b74d-11e8-801b-53ebed0fb54b.png)

AL Extension Version: 0.16.19969

Server Version: US Dynamics NAV 11.0 (23572)

Page Properties:
page <id> <name>
{
    DeleteAllowed = false;
    InsertAllowed = false;
    LinksAllowed = false;
    PageType = Worksheet;

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
