### ISSUE TITLE
The extension 'xxx' is making a request to external service.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#3720]
we are importing some branding logos to one of our app pages using HttpClient Binary downloads.

it was not prompting any screen earlier but now it is showing below screen. is there anyway to hide this also automatically make it allow always..

![image](https://user-images.githubusercontent.com/23735402/45546238-5cd6e000-b83a-11e8-870c-753abb73a823.png)

**Comment by atoader** [comment]
Hi! Documentation about this feature will be out soon. You can change the setting by going to Extension Management and selecting Configure for your extension.

**Comment by pmohanakrishna** [comment]
I didn't find any Configure option in extension management page in RC2. (is it for changing the selection?)

what about handling thru in code?

**Comment by atoader** [comment]
You will not see the option at the moment because we are waiting for a new license. You can change the setting by inserting a record in the Nav App Setting table 2B + 1 for your extension. You should only do this if you are sure that your extension will work fine in both a sandbox and production. You can also take advantage of the procedures on the Tenant Management codeunit to get information about the environment your extension is running in.

**Comment by pmohanakrishna** [comment]
right now, getting below error while trying to install.

You do not have the following permissions on TableData NAV App Setting: Insert.

**Comment by atoader** [comment]
Ok. Now you've hit issue #3612 . We are working on pushing a license update out. We are in the process of testing the latest bits. Can you try to not use the HttpClient during the installation of your extension?

**Comment by pmohanakrishna** [comment]
Does it work for both existing and new customers (new table insertion)? do we have to provide any extra permission inside object like for Ledger Entries?

**Comment by atoader** [comment]
@pmohanakrishna I am not sure I understand. Could you please provide more information? (Please keep in mind that I am working on the compiler so I have limited knowledge when it comes to the application)
