### ISSUE TITLE
Make Preview Downloadable/Installable

### ISSUE THREAD

**Issue by markbrummel** [Microsoft/AL#373]
The only reason I create a VM on azure is to then download the .\NAVDVD and .\Demo to my PC and do a local install.

The azure VM's are bugy to deploy and if you forget to turn them off, expensive.

Can you put the bits somewhere to download? Even partnersource would be acceptable. ;-)

**Comment by ajkauffmann** [comment]
I guess we have to wait for the VS Code extension to become publicly available.

There are some other options though:

Option 1: use a cheaper VM (you need to create your own template, fairly easy)
Option 2: download the whole VM harddisk and create a Hyper-V VM (download takes a while)
Option 3: use docker (attend the session about that at Directions / NAVTechDays)

**Comment by markbrummel** [comment]
Thanks for trying to answer my question but I hope you are not offended if it is a Microsoft answer I am looking for.

I don't think we have to wait until it is publicly available. I am already running everything local for several months.

**Comment by ajkauffmann** [comment]
Just trying to help, I have used the first two options myself and played with option 3.

Of course it is possible to install local, it's just not the official method because it is still a beta product. The official method would be, in my opinion, to have it available as a VS Code extension.

No offense at all...

**Comment by markbrummel** [comment]
I know you are trying to help.

The compiler already is a VS Code extension, it is just not yet downloadable like CRS's. The compiler is included in the .\Demo folder and the PowerShell script installs it. To update your existing system you need to first manually uninstall the extension.

All extremely easy to do by hand, just a few steps.

**Comment by ajkauffmann** [comment]
Sure, I now the procedure. Like you, I just don't like it to manually install it every time an update comes out. That's why I use a my own Azure template with a (slightly) cheaper VM and a PowerShell script to create, start and stop it (which is just a click away). Put the code on GitHub and you can just throw away and recreate a new machine in a breeze. That's for the time being of course.

**Comment by waldo1001** [comment]
I seem to remember a post (didn't find it though) where @StanislawStempin mentioned Microsoft was working on a new way to distribute updates.. specifically stating that setting up a new VM wouldn't be necessary.
But again - didn't find it. So if not, it must have been a dream that I obviously share with you ;-).

**Comment by StanislawStempin** [comment]
Closing the thread based on two new ways that we distribute the bits:
- Docker images
- VS Marketplace for the VSIX + Online Sandbox for the runtime
