### ISSUE TITLE
Error while installing NAV app

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/AL#3737]
Hey Guys, 
I receive the following error while trying to install NAVapp: 
_Install-NAVApp : The value "0" can't be evaluated into type Date._
Any advice how ti find the source of the problem?

Steps
```
C:\WINDOWS\system32> Unpublish-NAVApp -ServerInstance DynamicsNAV110 -Name ALProject5
C:\WINDOWS\system32> Publish-NAVApp -ServerInstance DynamicsNAV110 -Path "C:\Users\gps\Documents\AL\AL
Project5\Default publisher_ALProject5_1.0.0.0.app" -SkipVerification
C:\WINDOWS\system32> Sync-NAVApp -ServerInstance DynamicsNAV110 -Name ALProject5
WARNING: Cannot synchronize the extension ALProject5 because it is already synchronized.
C:\WINDOWS\system32> Install-NAVApp -ServerInstance DynamicsNAV110 -Name ALProject5
Install-NAVApp
```

Error:

```
Install-NAVApp : The value "0" can't be evaluated into type Date.
At line:1 char:1
+ Install-NAVApp -ServerInstance DynamicsNAV110 -Name ALProject5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Install-NAVApp], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$DynamicsNAV110/default,Microsoft.Dynamics.N
   av.Apps.Management.Cmdlets.InstallNavApp

```

- AL Extension Version: 
Tried to compile package with two AL versions
0.12.17720
0.16.19969

- Server Version: 
11.0.21441

Best Regards, 
Gintautas

**Comment by ashik-ivor** [comment]
I suppose, somewhere date value is being assigned and thus you are facing this issue. 
Instead of 0, you can add "0D".

**Comment by gintuoklis** [comment]
Well, I'm afraid it's not so simple. If i would have a case like you describe, let's say line like this:

`TransferJournalLine2."Posting Date" := 0;`

I would receive compiler error: 
_"Cannot implicitly convert type 'Integer' to 'Date'"_

Now, I have no compilation errors at all and mistake occurs only when installing extension.

**Comment by StanislawStempin** [comment]
I apologize for the delayed reply, someone should have provided the following feedback before:

This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by gintuoklis** [comment]
Hey Stanislaw,
I get the same error while publishing extensions using the latest BC version. 
So coming back to my question: how can i find out which object is causing it? Why it's not caught by the VS Code compiler?

Server Version: 13.0.24623
AL Language Extension version:   2.0.48254

**Comment by gregoral** [comment]
Hi gintuoklis,
we had a similar issue, where the source of the error wasn't in the error package.

I would suggest, to find the issue with divide & conquer technique.
Remove objects from extension until the error goes away.

We had over 200 objects in our extension, over 10 developers, ...
I was able to find the object in under 10 minutes.

00. backup all code

1. remove 50% of objects ( start with pages, reports, ... )
2. compile and test by installing
3. repeat steps 1 & 2 until problem is found

When you find the root couse please open a new issue or otherwise share the info.

**Comment by gintuoklis** [comment]
Hey All, 
We managed to find the cause of it. Root cause of it is usage of CONST(0D) within SourceTableView. This systax is totally ok on old C/AL. replacing CONST with FILTER all works fine.

Here we have multiple issues:

- If it illegal syntax, it should be caught by AL language extension on VS Code.
- Error occurs only when publishing. Error message is a bit different in the new version, but still does not give any clue which object it's related. Why is so hard to add object ID to the error message?
_The request for path /bc130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Unexpected value 'Date' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.ConstantValueTypeDiscriminator'_
- After discovering this issue, managed to find the same bug on the issue list. It's #3072 reported in July. I know you guys  are busy, but it's already October

Here's the code snippet
`page 50100 CustomItemList
{
    Caption = 'Test Page';
    DeleteAllowed = false;
    InsertAllowed = false;
    ModifyAllowed = false;
    PageType = Document;
    SourceTable = "Item";
    SourceTableView = WHERE ("Date Created" = CONST (0D));

    layout
    {
        area(content)
        {
            group(General)
            {
                Caption = 'General';
                field("No."; "No.")
                {
                    Editable = false;
                }
            }
        }
    }
}`
