### ISSUE TITLE
How to access base object global variables in extensions?

### ISSUE THREAD

**Issue by nareshbandariD365** [Microsoft/AL#3761]
- AL Extension Version: 

- Server Version:

**Comment by SirBETE** [comment]
Not
Or you get errors like `'CustPriceGr' is inaccessible due to its protection level`, when I try to do something with the global variables `CustPriceGr` in TAB7002 SalesPrices.

You can ask for publishers that pass the globals you need through as a parameter (by VAR).
Or you declare new variables and ignore the ones in the base application.

**Comment by SirBETE** [comment]
Plus when using your own variable you are losing the context of the original one.

So try asking for new publishers or to add your needed variable to existing publishers?
(Check in latest BC version for which publisher and where a new one should come and here on git hub if they aren't already requested.)
Or refactor your code/method/functionality so you aren't depending on it.
