### ISSUE TITLE
Unable to use the StartupScript Control Add-In

### ISSUE THREAD

**Issue by louagej** [Microsoft/AL#3785]
- AL Extension Version: 0.16.19965

- Server Version: 11.0.24232.0-W1

```javascript
StartupScript = 'scripts/start.js';
...
var controlAddIn, nameDiv, phoneDiv, emailDiv;
controlAddIn = $("#controlAddIn");
nameDiv = $("<div />", { id: "nameDiv" });
phoneDiv = $("<div />", { id: "phoneDiv" });
emailDiv = $("<div />", { id: "emailDiv" }); 

controlAddIn.append(nameDiv);
controlAddIn.append(phoneDiv);
controlAddIn.append(emailDiv);

window.GetCustomerInfo = function(custInfo)
{
  nameDiv.html("Name: " + custInfo.name);
  phoneDiv.html("Phone: " + custInfo.phone);
  emailDiv.html("E-mail: " + custInfo.email);
}
```
GetCustomerInfo is available in my controladdin file
```AL
procedure GetCustomerInfo(custInfo: JsonObject);
```
![image](https://user-images.githubusercontent.com/7229592/45769360-aca11700-bc3f-11e8-8063-0d48672b3e52.png)

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by louagej** [comment]
@StanislawStempin ,
16 days ago this was the latest release
Nothing has changed since then, I still have the same problem.

**Comment by thpeder** [comment]
Hi @louagej,
The errors you are seeing is not related to AL, they are coming from the Javascript extension in VScode, which states that it can't find a member with the name $.
