### ISSUE TITLE
Debugger: How to set a watch on a field

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#3813]
In NAV 2018 it seems not possible to set a watch on a field of a record variable. Or am doing something wrong?
What ever I do, the watch always says _Not available_.

SO this is on NAV 2018. Due to technical issues I cannot check it this very moment on D365BC. Curious whether it does work there. The various preview update announcement do not mention anything on this topic anyway.

**Comment by lvanvugt** [comment]
Today I experienced it somewhat different. It does work, but apparently not for the Rec variable. Is that right?

**Comment by kalberes** [comment]
It works for me. Just add rec, or a rec.<field value> to the watch.

![image](https://user-images.githubusercontent.com/12760483/45917570-671c5e00-be7a-11e8-900a-dc57930636ce.png)

**Comment by lvanvugt** [comment]
@kalberes , I guess this is on D365BC?

**Comment by kalberes** [comment]
As far as I know it should work on NAv 2018 too.

**Comment by BartPermentier** [comment]
table."field name" works for me v2.0.42188. 
However you need to type it in the watch list like some sort of caveman... 
I hope they plan to bring back r-click -> add to watch for record variables.

**Comment by tfenster** [comment]
While in a debug session you can mark an expression -> right click -> Add to watch

![image](https://user-images.githubusercontent.com/15346084/46067773-ea3dfc80-c177-11e8-8d30-055090147920.png)

**Comment by lvanvugt** [comment]
> While in a debug session you can mark an expression -> right click -> Add to watch
Yep, used that one too. But still have issues with (implicit references to) Rec variable.

**Comment by tfenster** [comment]
Ok, that probably will need to happen in the AL extension as we can't expect VS Code to understand how that works :)

**Comment by pborring** [comment]
Hi Luc (@lvanvugt), this old entry was tagged at some point as a suggestion due to the lacking intellisense in the watch window and became stale as only bugs are actively tracked in this AL GitHub. We have not yet added support for intellisense in watch window, but added it to the debug output pane in 2023 release wave 2. 
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/get-intellisense-adding-variables-visual-studio-code-al-debugger-console

I don't believe there is an idea tracking intellisense in watch window, so I would suggest creating that on https://aka.ms/bcideas to allow other partners to vote on that.

I will close this issue given it is mainly question/suggestion and old, but if you still have issues on BC, then please log a new issue on that in this AL GitHub with some repro steps. 

Cheers
