### ISSUE TITLE
OnBeforeTestRun/OnAfterTestRun are not raised (in NAV 2018)

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/AL#3820]
Reading https://github.com/Microsoft/AL/issues/971 this issue appears to have been reported before release of NAV 2018. Unfortunately it was only fixed months later. I guess it has never made it into any CU of NAV 2018.

I would like to apply for a down port to NAV 2018 of the fix in D365BC.

**Justification**
Run tests with own test runner with TestIsolation set to Function. Standard Test Runner runs TestIsolation Codeunit.

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
