### ISSUE TITLE
Attach Debugger to running Session

### ISSUE THREAD

**Issue by megel** [microsoft/AL#3824]
How can I attach the VS-Code Debugger to a running session in Business Central?

How-to achieve these tasks in VS Code / Business Central:
* open "Session List"
* select specific Session
* start debugger with "Break on Error"

**Comment by kalberes** [comment]
The first two are in our backlog list. The last one has already been supported since the June docker releases.
See here: https://blogs.msdn.microsoft.com/nav/2018/06/25/developer-preview-june-2018-update/

**Comment by megel** [comment]
@kalberes,  sorry - you are right I forgot the 3rd option is still available since june :)

**Comment by atoader** [comment]
It is not possible at the moment to select a running session, but it is possible to break on the next session: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-attach-debug-next
We are looking into enhancing the debugging experience in the future.

**Comment by boych83** [comment]
Is there any option to set breakpoint and debug-next, if you don't have source files in vscode?
e.g. just with "AL Go! project" with attach configuration in launch.json ?

**Comment by kalberes** [comment]
If you set the breakOnError or breakOnReadWrite then it should be possible to attach and break.

**Comment by boych83** [comment]
Ok, this is working fine. 
What about setting additional breakpoints when you don't have a source code? 

First you attach on break. Then, if this gets you to the right object you can set additional breakpoints on that object. Later on you can debugging with launch request (not attached) and break on that newly added breakpoints.
Otherwise you need to download symbols and run "Go to definition" on object browser and set breakpoints through ".dal" files.

**Comment by kalberes** [comment]
Breakpoints for physical AL files should be persisted. I think this is also true for breakpoints set in a dal file.

**Comment by EmilDamsbo** [comment]
This was addressed in Release 2023 Wave 1. You can read more about it here:
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave1/smb/dynamics365-business-central/attach-al-debugger-active-session-or-next-session-specific-user
