### ISSUE TITLE
[Bug] Page without SourceTable

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#3910]
Hi,

I have a page without SourceTable.
Now i want to Subscribe to OnOpenPageTrigger. This trigger passes a variable of Type Record 0.
So when i want to save the Subscriber it tells me that tabledata 0 does not exist.
![image](https://user-images.githubusercontent.com/41729653/46288785-38436d80-c587-11e8-9e11-f80f9ad7b04b.png)

My solution for now is to create a new Publisher myself, that doesn´t pass an empty Record, but this wont work once we hit the cloud. So it would be nice to have a solution for that.

I guess the same will be for the other trigger passing Rec.

_Thanks_

**Comment by mr-sala** [comment]
I've done a test and when you create the subscriber you get a message asking if you want to overwrite the signature of the function.
If you answer "no", then it compiles.
I've done a test and the problem is it doesn't execute the code in the subscriber unless the page has sourcetable.

So, I guess this doesn't solve your problem...

**Comment by LFlamme** [comment]
Yeah... but thanks for trying. Even if it worked, It would have solved this issue but not If u use for example the OnQueryClosePageEvet and you want to be able to use the AllowClose : Boolean parameter.

**Comment by StanislawStempin** [comment]
This forum is only for AL and VS Code development issues, for C/SIDE issues please use the regular support channel.
