### ISSUE TITLE
AL : Control add-in not found

### ISSUE THREAD

**Issue by sathyanarayanan23** [Microsoft/AL#3956]
- AL Extension Version: V2.0

- Server Version: NAV2018CU6
Hi,
Am trying to Create a control add-in in my local environment which works in the parent Database, but when i use the app file in the dependency portion of the child database, symbols are not downloading, i tried pasting the app file right in the al packages cache folder, which allowed me to use the control add-ins. but when i publish the page in the child database, system throws error saying control add-in not found.
error AL1024: A package with publisher 'CETAS', name 'ALDemo', and a version compatible with '1.0.0.1' could not be loaded.
GoogleMapCardPart.al(11,33): error AL0417: Control add-in 'ControlAddinTest1' not found

{
  "id": "498f9a74-2e72-4f32-ae95-e93a60b8cdf3",
  "name": "ALDependencyDemo",
  "publisher": "CIT",
  "brief": "",
  "description": "",
  "version": "1.0.0.1",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [
    {
      "appId": "d1948c51-77bd-4417-a7b8-b76065a419f4",
      "name": "ALDemo",
      "publisher": "CETAS",
      "version": "1.0.0.1"
    }    
  ],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 60000,
    "to": 69999
  }
}

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by StanislawStempin** [comment]
BTW, you're using wrong version of AL Language extension.  
Version 2.0 is meant only for Business Central and not for NAV. For Nav 2018 you need to use the AL Language from the product DVD (0.12.XXX)
