### ISSUE TITLE
Missing Permission-set warnings / errrors

### ISSUE THREAD

**Issue by gregoral** [Microsoft/AL#3963]
Apps must include PermissionSet file for publishing on AppSource.
But we are unable to test permission set file errrors.

1. If we use the cronus license file then we cannot even install our extension.
2. If we do use our license file then we get no errors even if we don't have required permissions in our app.

So either the extension cannot be installed or the extension can be istalled, but the missing permissions cannot be detected because then they are in our dev license file.

We need a way to:
a) get permission-set file warnings
b) have the ability to test with cronus ( or some other test ) license file

**Comment by pzentner** [comment]
Are you trying to test user specific permission issues? Because this should still be possible, if you setup the test users (look at "Setup-NavContainerTestUsers", for instance, for NavContainerHelper with docker). You basically have to test this with a "standard BC user" and not with a super user that was created as the admin. Those test users have the same permission sets and entitlements that normal BC users have, so you can reproduce any issues that would come up with your permission set in your app.

**Comment by StanislawStempin** [comment]
I confirm the above answer. You need to test with a non-super user.
You of course need a license that allows everything that you are trying to grant permissions for and we have no plans of changing that.
