### ISSUE TITLE
RDL crash

### ISSUE THREAD

**Issue by MoallaMehdi** [Microsoft/AL#4026]
Hi, 

With a new RDL report, when adding the "ExecutionTime" / Page No / User ID fields in the report header, NAV crashes every time we run the report!

How can we debug the RDL report ?

NAV 2018 CU 7
AL : 1.26.1

Thanks,

**Comment by StanislawStempin** [comment]
This forum is dedicated only to supporting the latest Business Central Developer Preview release. If you can reproduce the problem on the latest preview version we will be happy to look further into it. Otherwise could you please contact the regular support channel.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
