### ISSUE TITLE
suggestion: cloud printing capabilities

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/AL#4059]
Considering that the on-prem windows client is going to be retired (so I'm told) in the next 12-24 months, I think it would be prudent that the BC developer team introduce some kind of cloud printing capabilities into Business Central (both oncloud and onprem).

Refer to this link:
https://docs.microsoft.com/en-ca/dynamics365/business-central/ui-specify-printer-selection-reports

The above link is obviously tailored for web client environments. 

For reference, my BC sancbox is a local docker image. This is what I tested so far. 

- I can currently utilize printer selections in the BC Windows client with success.
- I then ran the same report from the web client. printer selections were ignored and instead I was presented with a PDF preview of the report (could that be because it's a docker environment? would a fully installed on-prem environment behave the same way?). 
- I haven't tried scheduling a report print yet. 

Considering that the Windows Client is eventually going to be killed off, this concerns me greatly how it will affect any code that utilizes printer selections, specially processes that involve unattended/scheduled  printing and/or printing to unorthodox page sizes (e.g. labels), and I'm starting to have second thoughts on writing any code that involves utilizing printer selections. We have legacy customers interested in migrating to OnCloud and they may see this as a roadblock. 

I suggest that Microsoft add a new "Cloud Printers" area into Business Central. It could serve as a master list of user-defined cloud printers available for that tenant. Make it so it's capable of interfacing with all the major players via printer web services (e.g. providers that come to mind include google print, HP e-print, Microsoft Hybrid Cloud Print). 

From there, refactor the printer selections table and form to utilize these cloud printers. 

If a user and/or report has a printer selection to a cloud printer when report.print(...) is called, then print to that cloud printer and skip the web client PDF preview completely. 

Thoughts?

**Comment by StanislawStempin** [comment]
This and others gaps as compared to the win client are among the reasons why the win client will not be replaced before 12-24 months. This particular topic is being discussed in more details on Yammer and we are aware of the need.
Since it is not directly related to AL or dev tools I will close the issue here and encourage you to continue the discussion on Yammer:
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1119439189&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=Printing
