### ISSUE TITLE
Getting error while installing a PowerBI report App on a BC instance.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/AL#4064]
Hi All,

I am trying to install a **PowerBi** report App on my BC instance. But after selecting the app on **app.powerbi.com** I am getting an error on installing of the app.
Below is the error screenshot.
![screenshot 49](https://user-images.githubusercontent.com/33481576/47079531-61b8f600-d223-11e8-9cf7-8d54375e3c99.png)

**Comment by StanislawStempin** [comment]
Since this is not directly related to AL or developer tools I would encourage you to contact Support or seek help from one of the following communities:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
