### ISSUE TITLE
SchemaUpdateMode=synchronize failed with code 422. Reason: Specified part does not exist in the package.

### ISSUE THREAD

**Issue by davmac777** [Microsoft/AL#4099]
Press F5 to sync to my local database. Had been working.
now get this error:
SchemaUpdateMode=synchronize failed with code 422. Reason: Specified part does not exist in the package.

output has these lines:
End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\Agent\_work\41\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**To Reproduce**
Steps and/or AL code to reproduce the behavior: Problem is I don't know where to look from the error message
1. Go to '...' I have attached my last 3 changed files since my last successful update.
I did get an invalid table extension number first f=which was already in use. I changed it and then received the above error.

**Expected behavior**
A clear and concise description of what you expected to happen. **expected it to publish**

**Screenshots**

**Versions:**

 - AL Langauge: 0.12.17720

 - Business Central:  (NAV 2018 CU4) on premise

**Comment by StanislawStempin** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
