### ISSUE TITLE
Translations for Profile objects

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL#4105]
We have an app available in multiple regions and thus multiple languages. Most of the system can be translated with xliff files, but Profiles cannot, leading to English named Role Centers in the Role Centers list even for countries where English is not generally understood.

Suggestion:
- Add the Description property from Profile objects to the g.xlf file
- On App install: Use the translated caption for the primary language to populate the Description field in the Profile table.

**Comment by MiePlougstrup** [comment]
The same problem applies to the Permission Set (XML RoleID and RoleName), where translations are not possible.
Should I open a new issue for this?

**Comment by MarcelNL** [comment]
Is there already a timeline for this issue?

**Comment by atoader** [comment]
@MiePlougstrup the initial issue will be fixed in the 2019 Wave 2 release of Business Central. You post your suggestion for translating permission sets to https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. Implementing this requires a cross-team effort and posting it on BC Ideas increases the likelihood that it will gain the priority that it needs to be implemented.
