### ISSUE TITLE
Use the Value of a Variable on a Page - Leaving no Footprints

### ISSUE THREAD

**Issue by ashishsharmanav** [Microsoft/AL#4110]
Is it possible if you can update publisher events created by standard triggers on all pages, example : OnOpenPage, OnAfterGetRecord, OnQueryClosePage, with IncludeSender as Yes and GlobalVarAccess as Yes. As this will help us avoid creating new publisher events to access global variable and page properties on an extended page. We can access the triggers events in any other subscriber function with Page and Global Variables for any updation.

**Comment by SCreanor** [comment]
I didn't see this before I logged a suggestion on the ALAppExtensions site. See this link: [https://github.com/Microsoft/ALAppExtensions/issues/307](url)

As you suggest, this is the only way to avoid enormous amounts of events being required to gain access to standard Global Vars and page properties. Without these events, it is very difficult to extend pages for even simple things.

**Comment by SCreanor** [comment]
The issue was moved to the development team here:
[https://github.com/Microsoft/AL/issues/4250#issuecomment-440981547](url)

Basically they don't foresee ever doing what we have requested, and propose a different solution which is not as useful and requires a complete refactor of the base app so we won't see any change on this for a long time.

**Comment by ashishsharmanav** [comment]
Got it. No scope of change for now. Thanks. #4250
