### ISSUE TITLE
Export Employee Payments

### ISSUE THREAD

**Issue by radovandokic** [Microsoft/AL#4130]
Hi all,

When you create lines in Payment Journal, with action Suggest Employee Payment, and run Export, this error appears:

![image](https://user-images.githubusercontent.com/34686682/47647747-382f9100-db78-11e8-98be-6b066c064dfd.png)

Printing checks works well, but doing electronics payment does not.

I am using MS D365 BC version 13.0.25267

Thanks,
Radovan

**Comment by JohanStenberg100** [comment]
Hi @radovandokic, this issue is not related to the AL development tools. If you disagree, please re-open this issue with more information.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)
