### ISSUE TITLE
Error Code 442: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use

### ISSUE THREAD

**Issue by wingsrutherford** [Microsoft/AL#4189]
After I changed extensions's version number, below error was shown. May I know what properties need to configure?

[2018-11-13 17:05:53.28] Sending request to http://localhost:7049/BC130/dev/apps?SchemaUpdateMode=synchronize
[2018-11-13 17:05:53.50] The request for path /BC130/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: 
Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use.

Thank you!

**Comment by qutreson** [comment]
Hi @wingsrutherford, can you try running [Get-NavAppInfo](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps) to see if it you have multiple versions of your extension installed on the server? 
If it is the case, can you try using the [powershell](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/?view=businesscentral-ps) in order to uninstall and unpublish the version of the extension that you are not currently working with?

**Comment by wingsrutherford** [comment]
Hi @qutreson, I ran Get-NavAppInfo to list all the published extensions, and unpublished the version of the extension that is no longer in use, then the error gone. Thanks for your help!
