### ISSUE TITLE
InitValue for Enums

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#4192]
Hi,

I found out that the property "InitValue" does not work for Enums. Since the Enums are supposed to replace the Options, it would be nice if i could use the property.

thanks

**Comment by esbenk** [comment]
Please test on latest update. Otherwise provide more detailed repro steps.

**Comment by LFlamme** [comment]
Tested with Al language 2.0.48254 and latest BCOnPrem Version(Docker).
I have a base-app in wich i create the enum "testenum2".
Then i got an app with dependencie on that first app. In that app i have a Enumextension.
In that second app in a tableextension i got the following:

tableextension 50201 "tableextension50101" extends "MCI Setup"
{
    fields
    {
        field(50000;enumtest;Enum testenum2)
        {
            InitValue = testenum2::d;
        }
    }
}

I get the Error: 
**The property 'InitValue' can only be set if the property 'Type' is set with any of the values of :'BigInteger,Boolean,Code,Date,DateFormula,DateTime,Decimal,Integer,Option,Text,Time,TextConst'**

**Comment by esbenk** [comment]
The bug is in the fall release.  You need a newer version of the compiler and platform. 

The syntax is slightly different 

InitValue = d;

It is fixed in the first update and you can already test it in the docker image 
bcinsider.azurecr.io/bcsandbox that is available through collaborate. More information on docker images [here](https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/)

**Comment by LFlamme** [comment]
Ok, Thanks :)
