### ISSUE TITLE
Official folder and naming conventions for Extension projects 

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#4224]
I would like there to be a folder structure and an official naming convention for projects based on Extensions.

To do so, it would be ideal for the VSCode Palette commands to generate the files following that official name convention and place them in the correct folder according to their Type ...

A "double extension" nomenclature could be used as in Angular CLI such as:

`. \ 01_table \ My Table - 50000.table.al`
`. \ 01_tableExt \ Customer Ext - 50000_18.tableext.al`
`. \ 02_page \ My Page - 50000.page.al`
`. \ 02_pageExt \ Customer List Ext - 50000_22.pageext.al`
...

The separation of the Ext Objects from the "new ones" would be in order to have a better control of what numbering is still available in the License.

__In VSCode, each type of object could also be represented with a different icon.__

Finally, `txt2al.exe` should use the same naming and folder convention when convert old CAL files to new AL files...

Ideally, all standard objects should be listed in VSCode left Explorer pane as "virtual files" where we can see-only the standard code to be in-context while programming... each .page.al object could indent all its .pageext.al extension files and so on like Visual Studio does with .cs files for example...

**Comment by JavierFuentes** [comment]
Hi again,
after install __Material Icon Theme VSCode extension__ and a litle hacky, the result is like this image:

![image](https://user-images.githubusercontent.com/5801847/48677084-f3dc5300-eb6f-11e8-8ad8-d64b5c9cee66.png)

![image](https://user-images.githubusercontent.com/5801847/48677193-36525f80-eb71-11e8-84a8-3c724c93e11a.png)

In this case, I have given more importance to order objects by their name than by their id

When there is an __official Icon Theme for AL Language__ it should match file naming convention.

**Comment by pborring** [comment]
We have no plans for prescribe, enforce or auto-create a certain folder structure in AL projects, leaving that to developer/partner desires. E.g., in the show example, folder are by object type - another approach could be by functional sub area. However, since this issue was logged we have Outline View, AL Explorer and Namespace support, all removing the need to sort in folders by object type or area (namespace).

If desirable, there are some community VSIX add-ins that allow managing folder though.

Thus closing this ask as won't fix.
