### ISSUE TITLE
Dude: Numbering range numbers for Testing objects and procedure for automatic Testing

### ISSUE THREAD

**Issue by JavierFuentes** [Microsoft/AL#4231]
Hello, our infrastructure is Business Central OnPremise and we would like to know if there is a special range of numbers for testing objects that our license includes by default and that does not occupy the numbering we need for our business objects.

If not, could you tell us how we can test on OnPremise QA Server (with our customizations for extensions and semi-real data) all our developments in Business Central OnPremise before sending each change to an OnPremise PROD server.

Another question we have is whether or not the Test Objects should be within the same Extension project in which all our customizations are ...

The last one is how to automate the execution of those tests and avoid a deployment in case any of them gives Error.

Could you explain how to proceed, please?

**Comment by StanislawStempin** [comment]
There is no special range for test objects as far as I'm aware. Don't you have access to the full 50K-99K range with your developer license and could use that one?
Since this forum no longer accepts general questions you'd need to go to one of the community forums for further help:

To get help please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
