### ISSUE TITLE
API Query for Table 2000000038 AllObj throws 500

### ISSUE THREAD

**Issue by nboettcher** [Microsoft/AL#4248]
I am attempting to get a listing of all objects in my Business Central instance. I have created a new Query with QueryType = API for table 2000000038 AllObj. The code compiles and the extension publishes and installs. When I call the API endpoint, it returns a 500 with message": "Object reference not set to an instance of an object."

Query AL:
query xxxxxx "xx_Objects"
{
    Caption = 'Objects Listing';
    QueryType = API;
    APIPublisher = 'xxx';
    APIGroup = 'xxx';
    APIVersion = 'v1.0';
    EntityName = 'obj';
    EntitySetName = 'obj';

    elements
    {
        dataitem(AllObj; AllObj)
        {
            column(Object_ID; "Object ID")
            {
            }
            column(Object_Type; "Object Type")
            {
            }
            column(Object_Name; "Object Name")
            {
            }
        }
    }
}

 - AL Langauge: 2.0.48254
 - Business Central: US Dynamics NAV 13.0 (25432)

**Comment by nboettcher** [comment]
@JohanStenberg100  do you have an ETA on a fix for this?

**Comment by JohanStenberg100** [comment]
Hi @nboettcher! This is actively being worked on, however I can't provide you with an ETA as of now.

**Comment by nboettcher** [comment]
Thanks @JohanStenberg100 . Do you have any workarounds for this? Other APIs or Tables I could call to get the objects?

**Comment by JohanStenberg100** [comment]
Hi again @nboettcher, not on the top of my head. As I stated before this is being actively worked on. Thanks

**Comment by JohanStenberg100** [comment]
Hi again @nboettcher, I have an update for you. Using virtual tables as data sources for queries is not supported by C/SIDE and we will block it in AL as well, because we don't support it internally. You'll have to work around this. If you have a valid business scenario you can try to explain it here in the issue here and we can discuss it and see if we should add this functionality in the future.

**Comment by nboettcher** [comment]
Thanks for the feedback @JohanStenberg100. The main business problem I am trying to solve is I need a complete list of objects within a D365BC environment (With Object ID, Type and Name). Our extension is used to analyze security in Business Central and therefore I need a base list of all objects in the environment which can be assigned security. I have tried to create Query extensions for the Object table, AllObj, and AllObjWithCaption and they all fail to work.

**Comment by JohanStenberg100** [comment]
Hi again @nboettcher, we will not start to allow this functionality I'm afraid. That said, I've asked around and I have some propositions you can work with:

- Since you are creating a query of type API, can you instead directly query the underlying SQL table?
- Perhaps you can synchronize the virtual table to a "materialized" table, and then query that table?
- Can you stay fully inside business central and do all your logic there? And avoid the API query all together?

**Comment by JohanStenberg100** [comment]
Hi again @nboettcher, we will continue to have this as a runtime issue. It turns out the effort needed to fix this bug is quite large, it will be treated as part of our migration story from C/SIDE to AL and VS code. Thanks for your understanding.
