### ISSUE TITLE
Hyperlink Functionality is Missing

### ISSUE THREAD

**Issue by Anna-Gudimova** [Microsoft/AL#4253]
Hello Dynamics NAV Team,

My client needs Hyperlinks added to Sales Invoices and potentially Customers, both card and list pages.
Normally we do it through page customization feature in regular NAV:
![image](https://user-images.githubusercontent.com/10453174/48926077-5f2f6900-ee7f-11e8-82c2-d318a50e36c1.png)
However, I see no way to do the same in Business Central.

I found this post:
https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-add-link-to-record

Article instructions say:
"Choose the Links action to open the Links pages that shows all the current links that are added to the record."
I can find no such action on pages.

Can you please point out where this action is located and how to navigate to it? 

If the functionality is not there yet please let me know when this feature will be added.

Thanks,
Anna

**Comment by StanislawStempin** [comment]
Could you please contact the regular support channel since this doesn't seem related to AL/Dev tools. 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
