### ISSUE TITLE
Things to improve an text2AL

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/AL#4270]
Hi,

I have converted quiet a few Objects to AL using Text2AL.
I noticed a few things that could be improved.
1. When converting Flowfields, the Calcformula is set as first Property in AL. The compiler needs the Fieldclass to be before the calcformula. By now i have to move hte Fieldclass for all FlowFields.

2. A lot of Times the quotation marks(") are missing and need to be placed afterwards. Example: Sales Line.Item No.  -> this will be an Error in AL. It needs to be "Sales Line"."Item No."

3. In Calcformula where we use Const(yes) oder const(no). This is not accepted in AL. I needs to be Const(true) and Const(false).

**Comment by kalberes** [comment]
Which versions are we talking about? Have you run finsql with the ExportToNewSyntax prior calling txt2al?

**Comment by LFlamme** [comment]
Hi,

I use the NavContainerhelper since i work with Docker. Its Version 0.4.1.2. 
I use the command: Convert-ModifiedObjectsToAl -containerName NAVBConPremEXT -openFolder 

As far as I know this one exports into the new Syntax. If thats not correct, please tell me how to do next time.

**Comment by kalberes** [comment]
CAn you provide a txt file that would produce the issue?

**Comment by LFlamme** [comment]
[TAB5137552.TXT](https://github.com/Microsoft/AL/files/2638599/TAB5137552.TXT)
Thats one file from folder delta-newsyntax, where i had the problem in AL.

**Comment by atoader** [comment]
Hi @LFlamme ! I have converted the sample you have provided and it compiles fine with the AL language extension that is available in the marketplace.
1. We convert the properties in the order they appear in the TXT file. We reorder the properties in the order that is expected by the compiler because the Txt2Al tool does not have this knowledge. 

2. Can you provide an example where the quotation marks are missing? I would need the input TXT before export to new syntax, the one in the new (TXT) syntax, and the one in AL.

3. We automatically convert YES/NO from TXT to true/false in AL. If this is not done, please provide a repro.

Make sure you are using the latest version of the Txt2Al tool. We do not backport any fixes we do to this tool.

**Comment by LFlamme** [comment]
HI, so i updated my NAVContainerhelper today and tried again. Problem solved :) Convert will finish with much fever Errors, the one i get are not related to any issue with Text2AL.

Sorry for bothering

**Comment by atoader** [comment]
Hi @LFlamme make sure you use the latest developer preview. We are converting and building the entire base application and all the localizations so everything should go without problems in most cases.
