### ISSUE TITLE
Error when using RecordRef.LockTable(true, true)

### ISSUE THREAD

**Issue by DBiernat** [Microsoft/AL#4271]
After using the LockTable() procedure on a RecordRef variable with the wait parameter set to true and successfully publishing the app to the server the following error message appears:

The request to lock the "table name" table with a wait parameter of FALSE is not supported.

To reproduce the error just use the following code:

recRef.GetTable(rec);
recRef.LockTable(true);

I think no error message should be displayed, right?

I'm using the following versions:

- AL Language: 2.0.48245
- Business Central: W1 13.1 (25341)

**Comment by AndreyKorepanov** [comment]
Hi @DBiernat, thank you for reporting the issue.
I am trying to reproduce the bug, it does not seem to be reproducible. It looks like the updated extension (with LockTable(TRUE) call) has not been successfully published for some reasons and Business Central runs the previous version (containing LockTable(FALSE) call). To make sure that you run the actual version you can try the following steps: 
- Uninstall/Unpublish your extension from Business Central using Extension Management Page (Click Light Bulb and type Extension Management).
- Remove *.app file from the project in VS Code (it is generated automatically when you build the project).
- Press F5 to run it normally.
Hopefully it helps and please let us know if the issue is still there.
