### ISSUE TITLE
IncludeSender Event Publisher on a Pages don't work correctly

### ISSUE THREAD

**Issue by Spycoclown** [Microsoft/AL#4286]
**Describe the bug**
I have created an publisher on a page with IncludeSender = true and then i wanted to subscribe on it only with the sender. Regardless how I set up the sender parameter.

i always get the error: **ErrorSenderParameterIsWrongType**

the problem comes only if the publisher is in a page and i use the sender.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
![image](https://user-images.githubusercontent.com/7090519/49211872-dce3ff00-f3c0-11e8-9306-4542aea04e48.png)

The publisher:
![image](https://user-images.githubusercontent.com/7090519/49212275-ec177c80-f3c1-11e8-8254-287e65a941ef.png)
![image](https://user-images.githubusercontent.com/7090519/49212302-ffc2e300-f3c1-11e8-849c-564a823dec56.png)

**Expected behavior**
On Close Incoming Document should come the Message "Test"

**Versions:**

 - AL Langauge: 0.12.17091

 - Business Central: 11.0.22292

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
