### ISSUE TITLE
Extension disapears after Service Tier restart

### ISSUE THREAD

**Issue by sbuescher** [Microsoft/AL#4331]
After restarting the service tier, one extension is uninstalled and unpublished. In our case it happens if the extensions are dependend.

**Comment by Tharangac** [comment]
This happened to our Sandbox last Friday as well.

**Comment by BartPermentier** [comment]
We also have this issue for *some* customers and *some extensions*. Dit not find a link between them except that they all use NAV2018 onPrem.

**Comment by sbuescher** [comment]
Hi @atoader, yes I can reproduce this consistently. 

After restarting the servicetier I can republish an reinstall the Extension via VS Code.

I'm using NAV 2018.

**Comment by BartPermentier** [comment]
@kalberes NAV2018 CU11, nothing special in eventlog.
I asked my team again and apparently they don't have the uninstalling issue anymore in NAV2018 CU11 (we were at CU5 before).

We do however still have the issue of pages not appearing in the search menu for both the Windowsclient as the WebClient.(Just like if you would forget Application Area).
The extremely weird part of the issue is that if we take the code and apply it to our own local environment/docker or even at another customer we have no issue and the pages appear fine...

Maybe a setting somewhere or cache that can be cleaned?

Here is part of one page:
`page 50001 "UPA1 Production Nesting List"
{
    
    PageType = List;
    SourceTable = "UPA1 Production Nesting";
    Caption = 'Production Nesting List';
    ApplicationArea = All;
    UsageCategory = Lists;
    CardPageId = "UPA Production Nesting Card";
    
    layout
    {
        area(content)
        {
            Repeater(General)
            {
                Caption = 'General';
                field("Code";Code)
                {
                    ApplicationArea = All;
                    Tooltip = 'ToolTip: Code';
                }
               
            }
        }
    }
}`

**Comment by kalberes** [comment]
.Does the search issue also appear on NAV 2018? We have a fix on the issue that should be available on CU 12 for NAv 18.

**Comment by sbuescher** [comment]
Thanks for the help!
