### ISSUE TITLE
Need download link for language pack for Business Central CU 01 on premise

### ISSUE THREAD

**Issue by sainath654** [Microsoft/AL#4335]
Hello All

Do any one know where to download the language pack for the business central. I need German language pack for business central CU 01.

Thanks in Advance.

**Comment by sainath654** [comment]
Yes we have separate database for Germany but i need German language in NA database.

**Comment by atoader** [comment]
I am not sure I understand. Is it correct that you have an NA(North American) database and you want the German translations for it?

**Comment by sainath654** [comment]
Yes Correct.

**Comment by atoader** [comment]
@sainath654 as far as I am aware, we do not provide such a language pack. The NA application has a different set of application objects. The text used in these application objects has only been translated to the languages that are supported in the different countries of NA: MX, US, CA. 
It might be that there are other ways to achieve your goal. Please use one of the following resources: 
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This issue is not related to the latest release of the development preview so I will close it.

**Comment by kim-song** [comment]
How can we add new available language in Business Central?
![my-setting](https://user-images.githubusercontent.com/44225271/71303177-9906d200-23e7-11ea-918e-ffcd4856c5ed.png)
