### ISSUE TITLE
How to extend the Item Charge Assignment for Purchase.

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#434]
I need to extend the Item Charge Assignment for Purchase. Currently it only supports Amount and Equally.
I need to add Weight and Volume.
How would you extend this with the current design?

Currently I would need to modify the Question to the user in SuggestAssgnt:
Selection := STRMENU(Text000,2); // Modify the Text000 to include the new options.
Then I would have to modify the function SuggestAssgnt2 and add additional functionality to distribute based on the new methods. It's very common that our customers wants to distribute this way based on freight bills they receive or containers.

**Comment by RafaelKoch** [comment]
@StanislawStempin : something to get rid of :-)

This has been bothering me for a while now too; there is STRMENU in quite a couple of places in the system. I think those are really some anachronism from the bad old days of the classic client when you dutifully had to push a set of 1-3 buttons on a card that hid almost every functionality it contained. Small wonder there were shortcuts to common things like "post" which then gave you another set of choices... really a menu after the menu.

Since RTC I guess most or all STRMENUs could have been done away with because the menu ribbons can offer the same (or better) navigation. 
Since extending a STRMENU would actually require a way to extend inside a function AND within given strings (which will likely never work) or a way to override a function (which Microsoft sadly is reluctant to offer) I would suggest to throw the STRMENU out. 

In this case here I would go for extending the page to have two more distinct actions that will suggest both assignment options.

**Comment by johndcollins** [comment]
I completely agree with you. 
Another area we keep changing for our customers is the Post STRMENU. They want more options for changing the Posing Date etc.
I didn't want to add more menu's to the page because  1. they can still click the old menu, 2. with the tooltips MS is limiting the amount of menus we can have on a page. Don't want to run out.

**Comment by RafaelKoch** [comment]
as far as i know the problem with too many actions/tooltips does not apply to a page extension because this is actually a new object with a clean slate buffer-wise :-)

**Comment by johndcollins** [comment]
That would be great if that's the case.

**Comment by johndcollins** [comment]
So I tried to go down the route of adding Actions to Page 5805. Unfortunately the way the page is designed this doesn't seem possible. The page uses local variables that are not accessible to my extension page so I cannot call my own AssignItemCharge funtion.
I hope this will be addressed somehow. Right now it seems the extension (Tables and Pages) are just disconnected for some of the more advanced modifications.

**Comment by esbenk** [comment]
We have an ongoing effort to make the application code more extensible. I can you can imagine this is not a small task and it will take some time.

As a part of that process we are also looking at existing code patterns that should be rewritten for extensibility. The scenario solved with the StrMenu() pattern is clearly something that we should provide extensibility for.

It will take us some time to rewrite the application code for extensibility. We are working on it, but please be patient. Input like that describes common scenarios like this are very welcome. It helps us identify code patterns that we should provide extensibility for.

@RafaelKoch You are right. The current problem with too many actions/tooltips are related to how C/SIDE stores the objects. Since page extensions are stored outside the original object, you can add more actions to "full" C/SIDE pages.

**Comment by johndcollins** [comment]
@esbenk you guys have done a great job so far. I've converted my module to an app 95% with the current version with some workarounds. I have 2 issues that are currently not possible.

**Comment by AlexanderYakunin** [comment]
We've added options to allocate Item Charges by Weight and Volume, see latest code for SuggestAssgnt2 in Codeunit 5805, it should solve this problem. Same done for Sales part. You can use this method in extensions.

[External] SuggestAssgnt2(PurchLine : Record "Purchase Line";TotalQtyToAssign : Decimal;TotalAmtToAssign : Decimal;Selection : Integer)
PurchHeader.GET(PurchLine."Document Type",PurchLine."Document No.");

IF NOT Currency.GET(PurchHeader."Currency Code") THEN
  Currency.InitRoundingPrecision;

ItemChargeAssgntPurch.SETRANGE("Document Type",PurchLine."Document Type");
ItemChargeAssgntPurch.SETRANGE("Document No.",PurchLine."Document No.");
ItemChargeAssgntPurch.SETRANGE("Document Line No.",PurchLine."Line No.");
IF ItemChargeAssgntPurch.FINDFIRST THEN
  CASE Selection OF
    1:
      AssignEqually(ItemChargeAssgntPurch,Currency,TotalQtyToAssign,TotalAmtToAssign);
    2:
      AssignByAmount(ItemChargeAssgntPurch,Currency,PurchHeader,TotalQtyToAssign,TotalAmtToAssign);
    3:
      AssignByWeight(ItemChargeAssgntPurch,Currency,TotalQtyToAssign);
    4:
      AssignByVolume(ItemChargeAssgntPurch,Currency,TotalQtyToAssign);
  END;

**Comment by StanislawStempin** [comment]
Marking this issue as completed. Please file a new issue if you are still blocked.

**Comment by averied** [comment]
in what version of NAV do we have this modified Codeunit 5805 with options to allocate Item Charges by Weight and Volume? Can we download from partnersource?

**Comment by AlexanderYakunin** [comment]
Yes, you can download NAV 2018 with this change in codeunit 5805
