### ISSUE TITLE
Unable to launch the extension to the server

### ISSUE THREAD

**Issue by dhyaneekd** [Microsoft/AL#4401]
Whenever i am trying to code for a particular file all it does it gives me an error on the app.json file i tried a lot of tings sometimes it work most of the times it doesnt works. I am also adding some screen shots so that you may get an idea what actual is the issue that i am facing
![github](https://user-images.githubusercontent.com/45871506/50371765-32d64c00-05e7-11e9-9ff2-fae3c25e5ac2.png)
![github 2](https://user-images.githubusercontent.com/45871506/50371768-35d13c80-05e7-11e9-8f1d-87d01014854f.png)

the one is the error and if i click on it so it directly take me to the app.json and it neither shows the error that i can clearify and change so that everything works out.

**Comment by thpeder** [comment]
Hi @dhyaneekd,
In order to see the error make sure to update to the latest version of VSCode; 1.30.1 as of writing this.
We have a bug in the extension when it comes to clearing the debug console, so you will keep seeing old messages until you clear the console. See the image below for how to do that.
![image](https://user-images.githubusercontent.com/24276180/50372963-11219880-05d8-11e9-9c38-863cbe1cef5d.png)

Once you have the error feel free to return with that if you are not able to resolve the issue yourself.

**Comment by thpeder** [comment]
I can't identify the problem from the information you have provided us with so far.

1) What is the error in the debug console?
2) Which version of the AL Language extension are you using?
3) What is the version of the server you are trying to publish to?

**Comment by dhyaneekd** [comment]
Hi Thomas,
 It was really great to hear from you, I came to the result of the major
issue and hence i also came to know why actually it was creating an error.

The whole story was that there were already a lot of extensions available
on the Cloud and hence when it was trying to get publish the error was
genuine as the other extensions also had some same ID's . I tried to launch
the VS code once i finished the uninstall process of the extensions from
the server and it did worked.

Thanks a lot once again

Regards
Kapil Dhyani
