### ISSUE TITLE
TestPage field method Caption gives an error when deploying extension

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/AL#4440]
I am getting the following error when deploying my automated test extension:

> Non-invocable member 'Microsoft.Dynamics.Nav.Runtime.NavTestField.ALCaption' cannot be used like a method.

This is the helper function using the Caption method:

```
local procedure VerifyNoIsPopulatedOnSeminar(var SeminarCard: TestPage SeminarCard)
begin
Assert.IsTrue(SeminarCard."No.".Value <> '', StrSubstNo(FieldOnTableErr, SeminarCard."No.".Caption(), SeminarCard.Caption()));
end;
```

The TestPage method Caption itself does not throw an error. No red wrinckle underneath or an error when buidling the extension.

**Comment by atoader** [comment]
Hi @lvanvugt ! We've fixed this bug a few months ago. What version of BC are you using? Are you on the latest CU for that version?

**Comment by lvanvugt** [comment]
D365BC, build 26413 (CU02, right?)

Did you test it yourself?

**Comment by atoader** [comment]
@lvanvugt we fixed the bug in master which corresponds to the next major release of the product. 
By default, any issue that is reported through GitHub will only be fixed in master and, only if the customer requests it, in the current major release. Requests for backporting to older versions must go through CSS.
We are working on backporting the fix to the current release branch. You should see it in the next CU.

**Comment by lvanvugt** [comment]
Clear. And great you picked it up for current release. Thanx.

**Comment by lvanvugt** [comment]
> You should see it in the next CU.

When will that be? Still waiting for it.

**Comment by plagijat** [comment]
Same issue here with W1 13.4 (28874) OnPrem.

**Comment by AndreyKorepanov** [comment]
The bug is fixed: 
W1 master: Application Build 28874, Platform Build 28871 (CU 04)
W1 13.4: Application Build 29483, Platform Build 29358 (CU 05)
