### ISSUE TITLE
Bug on Role Center part alignment

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#4471]
Hi,
I got an issue with Role Center parts alignment. Layout looks like this in AL:
![image](https://user-images.githubusercontent.com/39334704/51246741-c1927a80-1993-11e9-9e3b-f17be2c13142.png)

When I run BC every part becomes a column:
![image](https://user-images.githubusercontent.com/39334704/51246928-49788480-1994-11e9-844a-34059b40d6b1.png)

 What I need is that Groups would be a column and Parts would be rows in the columns (Groups). Does anyone else has the same issue?

**Comment by JohanStenberg100** [comment]
Hi, this issue is not fitting our guidelines for this repository. I suggest you post this question to one of the following resources to get help on AL extension development issues:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Using these resources will assist you in getting help from other AL developers. Thanks!
