### ISSUE TITLE
Role Center Bug

### ISSUE THREAD

**Issue by linasostreika** [Microsoft/AL#4496]
Hi all,

I have created Role Center on my extension. When my browser is not maximized on the full screen, Role Center looks OK:
![image](https://user-images.githubusercontent.com/39334704/51531395-fc8a2780-1e45-11e9-8844-fd484fc6a54f.png)
but once I maximize the browser for full screen I got this:
![image](https://user-images.githubusercontent.com/39334704/51531444-1fb4d700-1e46-11e9-900b-c95727ef26b2.png)
Whats is the problem? My Role center code is here:
![image](https://user-images.githubusercontent.com/39334704/51531523-5ab70a80-1e46-11e9-9409-969847f1b1bf.png)

**Comment by JohanStenberg100** [comment]
Hi, this issue seems like a general BC issue and not related to AL in particular. I will therefore close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. You can also try one of these forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Thanks!
