### ISSUE TITLE
HttpClient Send stopped working after update to 13.3.27233.0-US

### ISSUE THREAD

**Issue by ivan-synfnl** [Microsoft/AL#4499]
Hi,

I noticed that none of mine web service calls work after I installed extension to newer container running on image microsoft/bcsandbox:us-ltsc2019 (version 13.3.27233.0-US).

Installation of the app stopped working because of the installation code in upgrade codeunit that was failing to reach out to external API. In this call HttpResponseMessage.IsBlockedByEnvironment() was true. I understand the need to completely block API calls in certain environments but I need the way to get past this without removing this feature from installation logic.

Also, even after removing this API call in app installation I'm getting failures with other API calls where IsBlockedByEnvironment() is not true and calls are not coming from installation codeunit but from regular business logic. HttpClient.Send() is always returning false without any meaningful response or error in normal parts of the app. HttpResponseMessage.Content() is not even initialized but the HttpStatusCode() is 200?

I checked all the external services and I can confirm that they are working. Even when I had failures because of bad URL or authentication I was getting meaningful feedback, but in this case I'm not getting anything, 

Do you know why this has started happening?

**Comment by JohanStenberg100** [comment]
Hi, this issue seems like a general BC issue and not related to AL in particular. I will therefore close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. You can also try one of these forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
