### ISSUE TITLE
[AL0185, AL0280] 'Data Classification Mgt.' is missing

### ISSUE THREAD

**Issue by Hornsyld** [Microsoft/AL#4500]
The extension I am trying to publish is a Microsoft extension with some changes to it. We have published/installed it only multiply NAV2018, but there is 1 NAV database/instance it wont get publish to.
Trying to publish the code with powershell script
publish-NAVApp -ServerInstance $NAVServerInstance -Path $AppPathAndFilename -SkipVerification
gives the following message:

publish-NAVApp : Extension compilation failed
Source/install/COD91898.C5Install.al(20,32): error AL0185: Codeunit 'Data Classification Mgt.' is missing
Source/general/dashboard/COD91870.C5MigrDashboardMgt.al(118,80): error AL0280: The event 'OnMigrationCompleted' is not found in the target
At line:1 char:1
+ publish-NAVApp -ServerInstance $NAVServerInstance -Path $AppPathAndFilename -Ski ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Dynam...s.PublishNavApp:PublishNavApp) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp

I have tried to sync -NAVapp with this powershell.
Sync-NAVApp -ServerInstance $NAVServerInstance -Name $AppName

I have used the GenerateSymbolReference=yes command and recompiled every object.

The error message when publishing is saying it cant find til OnMigrationCompleted, but the function
[IntegrationEvent] OnMigrationCompleted(DataMigrationStatus : Record "Data Migration Status") is existing on our test envoirment and the target envoirment for installing.
Codeunit Data Classification Mgt. is also existing.

NAV2018CU7 with following info.
NavAppInfo:
Id            : f336ee87-3fe1-4c37-915c-0cd1b93abc79
Name          : Test
Version       : 11.0.20348.0
Publisher     : Microsoft
ExtensionType : ModernDev

Id            : 6d817132-2031-48bc-9e53-c8b05f4d0cad
Name          : Application
Version       : 11.0.20348.0
Publisher     : Microsoft
ExtensionType : ModernDev

Id            : 8874ed3a-0643-4247-9ced-7a7002f7135d
Name          : System
Version       : 11.0.12925.0
Publisher     : Microsoft
ExtensionType : ModernDev

The extension is installed on many others NAV's and also NAV with same build, just have a issue with this publish.

**Comment by JohanStenberg100** [comment]
Hi, this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)general NAVissue and not related to AL in particular. As I understand it, you are not publishing any extension. I will therefore close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. You can also try one of these forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

I'll close this issue now, please re-open it if you can provide a consistent repro in the latest BC version. Thanks!
