### ISSUE TITLE
I'm new to AL programming

### ISSUE THREAD

**Issue by lawrencegrey** [Microsoft/AL#4518]
How do I call column from a table (Replenish) to be display on an existing page with Assembly Lines?  

I am adding the vendor no (from another table) to the Assembly Line List.

**Comment by JohanStenberg100** [comment]
Hi, this issue is not fitting our guidelines for this repository. I suggest you post this question to one of the following resources to get help on AL extension development issues:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Using these resources will assist you in getting help from other AL developers. Thanks!
