### ISSUE TITLE
Issue with the Permission Set

### ISSUE THREAD

**Issue by himalpatel81** [Microsoft/AL#4519]
I've created an extension to have action on Customer Card. I've also created a table and accessing it on Customer Card. I've exported the permission set with required permission. 

When any user who doesn't belong to that permission set, it gives the error that "You do not have the following permissions on Table Data [ID] Read Page Edit-Customer Card has to close". When the user has access to the permission set then it works fine. 

So Does it require to have all the users to be part of this permission set ? Is there any way to avoid the error if the user is not part of the given permission set ?

Thanks,
Himal

**Comment by JohanStenberg100** [comment]
Hi, this issue seems like a general BC issue and not related to AL in particular. I will therefore close this issue and suggest that you open up a support ticket with Microsoft or a local partner. Then you can get help regarding your specific tenant and desired configuration. You can also try one of these forums:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Thanks!
