### ISSUE TITLE
NAV2018: Using functions for OData webservice in Visual Studio Code

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/AL#4522]
@JohanStenberg100. I have asked the question below in issue 'Using functions for OData webservice in Visual Studio Code'.
The answer was to use the property [ServiceEnabled], although this is not available for AL in NAV2018, therefore my question remains unanswered.

At the moment, at least in my experience, it seems AL code is meant for Development for Business Central only, and C/AL would be better for NAV2018. As the needed functionality that is possible in C/AL and not in AL, only is available for Business Central.

Does anyone know a solution for my problem below?
Thank you in advance.

https://github.com/Microsoft/AL/issues/4498 
"I am trying to make a function in a page as a webservice as described in this link:
https://docs.microsoft.com/en-us/dynamics-nav/walkthrough-creating-and-interacting-odata-v4-bound-action

Unfortunately the property 'External' is not availabe in NAV2018.

Other options I considered are:

Creating the page in the Development Environment, but I would rather keep everything in an extenions.
Creating a custom table, which triggers the function in an Insert or Modify trigger.
Will external functions ever be available in AL, if not what would be the best way to handle this?"

**Comment by JohanStenberg100** [comment]
Hi @Chingyz, this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel. 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. For more details please read: 

* [https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/)
* [https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do)
