### ISSUE TITLE
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown Error: The package could not be created.

### ISSUE THREAD

**Issue by kavila02** [Microsoft/AL#4575]
error AL0999: Internal error: 'One or more errors occurred.', Stack trace=unknown
Error: The package could not be created.

After the January 2019 Update, I am not able to run my extension. I get the error mentioned above with no other context. Nothing was changed in the code besides having to remove the schemaModeUpdate property in launch.json after the update.

![image](https://user-images.githubusercontent.com/42249333/52435464-ec2daa00-2adf-11e9-8360-d9501c32a1d7.png)

**Comment by qutreson** [comment]
Hi @kavila02, this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
