### ISSUE TITLE
Some action menus can not be extended

### ISSUE THREAD

**Issue by salgiza** [Microsoft/AL#4607]
There are several pages (lots, in fact) that have action menus that actually seem to come from data stored in the Profile Metadata table.

This is a big problem, because there is no way to extend any of those pages in a way that allows us to add actions to those menus. From a UX perspective, this is a very big problem: I've found myself currently adding a new option that is related *specifically* to the actions in one of those menus... and have had to add it in a new unrelated "Process" menu, because there is no other way to do it.

I'm not sure whether to call this a bug or a feature request, but I think that something should be done so that we can extend all menus in a page action bar, using AL.

P.S. We have a related ongoing conversation about this in Yammer:
https://www.yammer.com/dynamicsnavdev/threads/1235750900?trk_event=com_thread_click&allow_app_redirect=1

**Comment by Bleika** [comment]
I second this request all the way...

For OnPrem customizations we need to be able to control these menus:
A part from being able to add more Actions to them, some standard MenuItems/Actions may not be relevant to the Customer (in the most extreme cases, they might even be potentially harmful if executed) so we also must be able to substitute them by other more suitable Actions. 

While we don't know whether this is a bug or intentional design, it should be stated that we fully understand that this should not be possible for an App. 
If it's a design decision, maybe it could be linked to Target=Internal?

**Comment by atoader** [comment]
Hi! We were discussing this problem yesterday in the team. Mike will follow up on the Yammer thread and collect feedback from you. We are working closely with his team on finding a solution for this. If it is OK with you, I will close this issue so that we can focus the discussion in one place.
