### ISSUE TITLE
Request for .Net class

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/AL#461]
Can we get the .Net class XslTransform and related added as a AL class please?

**Comment by StanislawStempin** [comment]
We are currently not planning to provide that functionality natively in AL. The reason is that we aim at providing enough capabilities in AL to allow seamless call outs to other services (which often includes XML handling) but we are not aiming at handling all the specialized XML processing scenarios. Please consider handling it within an Azure Function or similar service and call it from AL.

**Comment by johndcollins** [comment]
I currently have functionality that takes a xsl template and generates a html based on xml port data. Why can't this class be added. It's not any different from adding the XML Document class.

**Comment by StanislawStempin** [comment]
This sounds like a good candidate for being implemented as an Azure Function and consumed from AL. 

In terms of implementing it in the AL language - we need to draw a line somewhere not to go into full re-implementation of .NET libraries. XSLT processing is not one of the core tasks that we are targeting.
