### ISSUE TITLE
Reopen issue "CASE statement around Field Type #1365" as not solved yet.

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/AL#4613]
This issue with the field types still exists in NAV2018 CU14.

Please confirm that the issue still exists and when it will be solved.
![fieldtypemismatch](https://user-images.githubusercontent.com/21098126/52856750-89fb2780-3125-11e9-9188-3d9556a439ee.png)

**Comment by thpeder** [comment]
Hi @ThomasBrodkorb,

This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
