### ISSUE TITLE
Error in adding field to DropDown fieldgroups

### ISSUE THREAD

**Issue by mongarajat** [Microsoft/AL#4643]
Hi Team,

I am using AL Language version 2.1.79379 and getting the error in adding fields to DropDown fieldgroups.
Please refer to the attached screenshot for the same and revert.

Regards,
Rajat Monga

![image](https://user-images.githubusercontent.com/47864473/53188335-1bd5c980-362b-11e9-914b-732805e394fb.png)

**Comment by thpeder** [comment]
Hi @mongarajat,

I think the issue is that the symbol file you have is built with an older version of the compiler which didn't store all the FieldGroups since they were not needed.
The compiler in Nav 2018 doesn't support this feature so you need a newer server and once you have that then download symbols again and it should work.
If you are working against our online sandboxes then downloading symbol again should solve your issue.

**Comment by mongarajat** [comment]
Thanks, I have checked on Online Sandbox and it works.
