### ISSUE TITLE
RequestFilterHeading translation does not work

### ISSUE THREAD

**Issue by MiePlougstrup** [Microsoft/AL#4647]
**Describe the bug**
In any Report then RequestFilterHeading is not translated in client, though it is translated in the xlf-file.

**To Reproduce**
Create a report, use the RequestFilterHeading on the dataitem.
Create translation-file, and translate the heading.
Run the report in the client.

**Expected behavior**
I expect the heading to be translated.

**Screenshots**
RequestPage and About this page:
![2019-02-22_11h53_27](https://user-images.githubusercontent.com/14122139/53243528-7103f080-36a8-11e9-9b95-2b6ce1b391b5.png)

AL code and translation in VS Code:
![2019-02-22_13h49_24](https://user-images.githubusercontent.com/14122139/53243588-ae687e00-36a8-11e9-923f-1ef922d06a6f.png)

**Versions:**

 - AL Langauge: 0.13.82793

 - Dynamics NAV 2018: 11.0.27667.0

**Comment by kalberes** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
