### ISSUE TITLE
How to access CAL Customized object from AL ?

### ISSUE THREAD

**Issue by TharunMuthu** [microsoft/AL#4663]
Hi All,
**How to access CAL Customized objects from AL ? Especially while migration time trying to move all data from CAL in to AL  !**
Note:
I already generated Symbol using  
**finsql.exe Command=generatesymbolreference, Database="2015 to BS Upgrade", ServerName=localhost**
and got output from navcommandresult.txt (from folder C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\130\RoleTailored Client) with successfully but still i cannot able to access CAL Customized objects from AL !!!

Can you help me!!

**Comment by thpeder** [comment]
Hi @TharunMuthu,

I guess you followed the instructions in the docs: [Running C/SIDE and AL Side-by-Side](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side) and enabled it on the server.
Check if you have another set of Application symbols published to your server by running [Get-NAVAppInfo -SymbolsOnly](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappinfo?view=businesscentral-ps), if so then remove them by running [Unpublish-NAVApp](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/unpublish-navapp?view=businesscentral-ps)
After that redownload the symbols in VSCode and make sure your don't have multiple versions of the application package in your package cache path since it will take the one with the highest version.
