### ISSUE TITLE
Is Subgrouping supported in Menusuite in Extension V2? 

### ISSUE THREAD

**Issue by Rachit14** [microsoft/AL#4674]
Hi,

We have a customer requirement where we need to arrange pages in Business Central in Subgroups. Customer was able to put the pages in subgroups and could define the hierarchy structure. Is it possible to achieve the same using Extensions V2? As per our understanding only UsageCategory property is available which arranges the menu in flat menu structure.

**Comment by kalberes** [comment]
yes that is correct. Only the UsageCategory is available for now.

**Comment by Rachit14** [comment]
Thanks for informing @kalberes . Could we expect this feature in near future?

**Comment by mikebcMSFT** [comment]
Hi @Rachit14 , we have no current plans to provide subgrouping. I recommend that you post your idea to https://aka.ms/bcideas so that others can vote for your it. If it gains enough momentum, we will certainly consider it for a future release. If you do post your idea, please clarify where you would like to see subgrouping (eg. would this be in the matching results when searching for pages and reports? or would it be in the navigation menu?)

There are already some ideas which may be related to your request, such as this one:
https://experience.dynamics.com/ideas/idea/?ideaid=96d178ec-b7b7-e811-a8eb-0003ff688d55

**Comment by Rachit14** [comment]
Thanks @mikebcMSFT for this insightful information.
