### ISSUE TITLE
Filter Pane is not available when a page is run with page.run or page.runmodal in webclient

### ISSUE THREAD

**Issue by AlainKrikilion** [Microsoft/AL#4719]
**Describe the bug**
When running a page using Page.Run(Page::"....") or Page.RunModal(Page::"...."), I don't see the icon for the Filter Pane. If I run the page using the page ID in the URL or if I search for the page, the Filter Pane Icon is there.

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a new page with an action. On triggering the action put the following code:
trigger ….
begin
  Page.Run(Page::"Warehouse Shipment List"); // or RunModal
end;
2. Publish and run your new page and hit the action to run the action. The Warehouse shipments page pops up WITHOUT the Filter Pane. Clicking on a field, I can "filter on this value", but this is not good enough.

3. If you search for "Warehouse Shipments" and run the page like this, the Filter Pane is there.

**Expected behavior**
Running a page using Run.Page or Run.PageModal, I expect to see the Filter Pane. I have the need to do some filtering.

**Screenshots**
This is how it should be:
![image](https://user-images.githubusercontent.com/48512185/54268419-0fca9100-4573-11e9-8bbc-b74f405aded3.png)

This is how it is:
![image](https://user-images.githubusercontent.com/48512185/54268491-35579a80-4573-11e9-819a-b33308c54969.png)

**Versions:**

 - AL Langauge: 2.1.79379

 - Business Central:GB Dynamics NAV 13.3 (27233)

**Comment by thpeder** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by AlainKrikilion** [comment]
I downloaded the latest build to create a docker environment. The problem persists.
