### ISSUE TITLE
The type or method related to File Management cannot be used for Extension development

### ISSUE THREAD

**Issue by jigneshdhandhanav** [Microsoft/AL#4721]
We are developing one extension. we got the error as per below error.

**File Management Codeunit**
The type or method ServerTempFileName cannot be used for Extension development 
The type or method DownloadToFile cannot be used for Extension development

**File Variable**
The type or method CREATE cannot be used for Extension development
The type or method CREATEOUTSTREAM cannot be used for Extension development
The type or method CLOSE cannot be used for Extension development
The type or method COPY cannot be used for Extension development
The type or method ERASE cannot be used for Extension development

what should we do to proceed further.

Thank you.

**Comment by rvanbekkum** [comment]
Functions that use the file system cannot be used in extensions with "target" set to "Extension" in the app.json file of your project.

Therefore, I think you'll have two options:
* If you are developing for on-premise and are sure you want to use functions that access the server file system, then you should set "target" to "Internal" in your app.json file. This will allow you to use these functions that would normally give you these error messages in VSCode.
* Use streams and/or blobs instead of files/filepaths.

**Comment by dNsl9r** [comment]
Follow the ideas of @rvanbekkum plus:

ReThink why you are using the methods, what are you trying to accomplish?
Maybe you can solve the issues by redesigning your solution at this point..

**Comment by thpeder** [comment]
This repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
