### ISSUE TITLE
report like "Customer - Payment Receipt" cannot find under the client but exist in the Dev Environment

### ISSUE THREAD

**Issue by acdennisw** [Microsoft/AL#4728]
**Is your feature request related to a problem? Please describe.**
I cannot find the report "Customer - Payment Receipt" Report ID (211) in BC. However, I find the report is located in the development environment and the report can be run from there.

**Describe the solution you'd like**
add the report to the menu Suite so user can access

**Describe alternatives you've considered**
create a new report based on this one thus it can be shown in the client. However, this is not efficient as there are many reports that missing.

**Additional context**
![image](https://user-images.githubusercontent.com/45580181/54390697-07f02580-4708-11e9-8b3c-e59ee2262a72.png)

**Comment by madearipermadi** [comment]
If i am not wrong . For this, usually you need to setup the "Cust. Receipt Report ID" at Gen. Journal Template for "SALES",  it will then print the payment receipt upon posting the journal.

**Comment by acdennisw** [comment]
Hi,
there should be an option for user to reprint if payment receipt / cash receipt was posted as the report should be reprintable to check what invoices were applied to the payment.

**Comment by thpeder** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
