### ISSUE TITLE
not able to use Assembly BOM field of Item Card page in pageextension object

### ISSUE THREAD

**Issue by pmohanakrishna** [microsoft/AL#4755]
**Describe the bug**
Not able to use Assembly BOM field of Item Card page in Pageextension object

**To Reproduce**
Steps and/or AL code to reproduce the behavior:
1. Create a pageextension object like below and field is not shown even it is available in standard page level

![image](https://user-images.githubusercontent.com/23735402/54681815-53089f00-4b33-11e9-8c6a-70ecca4e181e.png)

**Expected behavior**
we should be able to use the field when available in page level

**Versions:**

 - AL Langauge: 3.0.106655

 - Business Central: 
it seems system info page is not available in new version

![image](https://user-images.githubusercontent.com/23735402/54682232-5a7c7800-4b34-11e9-945a-de88ca31e8f9.png)

**Comment by pmohanakrishna** [comment]
@thpeder any update on this?

**Comment by atoader** [comment]
Hi @pmohanakrishna ! In preparation for the conversion of the base application from C/AL to AL, we had to change the algorithm we used for assigning names to controls without names. This is one of the controls that was affected by this change. The new name of the control is Control8. 
You can go to the definition of the page and see the controls that are available on that page. 

I suggest you use addlast or addfirst instead of addafter to make your code more resilient to this kind of changes.
