### ISSUE TITLE
NAV 2018 CU8 - Missing member error when subscribing to event

### ISSUE THREAD

**Issue by MarkusWinBI** [Microsoft/AL#4757]
I am trying to subscibe to Event OnBeforeUpdateUnitPrice from Table 37 - Sales Line

Definition in C/AL is
LOCAL [IntegrationEvent] OnBeforeUpdateUnitPrice(VAR SalesLine : Record "Sales Line";xSalesLine : Record "Sales Line";CalledByFieldNo : Integer;CurrFieldNo : Integer;VAR **Handled** : Boolean)

In AL I am subscribing to it via:
[EventSubscriber(ObjectType::Table, 37, 'OnBeforeUpdateUnitPrice', '', true, true)]
    local procedure ModifySalesPrice(VAR SalesLine : Record "Sales Line"; xSalesLine : Record "Sales Line" ; CalledByFieldNo : Integer; VAR **Handled**: Boolean)

The result is a compiler error
{
	"code": "AL0282",
	"severity": 8,
	"message": "The member referenced by event subscriber 'ModifySalesPrice' parameter 'Handled' is not found.",
	"source": "AL"	
}

**Comment by madearipermadi** [comment]
Is this "Handled" is new parameter which you have added at the Integration Event  ?
If that is the case , you need to generate symbol first and then download symbol again so it will recognized your new parameter.

Details :  
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side

**Comment by MarkusWinBI** [comment]
> 
> 
> Is this "Handled" is new parameter which you have added at the Integration Event ?
> If that is the case , you need to generate symbol first and then download symbol again so it will recognized your new parameter.
> 
> Details :
> https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side

Hi madearipermadi,
no this is a standard NAV parameter coming with this event.
Regards
Markus

**Comment by thpeder** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
