### ISSUE TITLE
New Extension Publish to  BC prompt message "An extension with same App ID and version has already been uploaded."

### ISSUE THREAD

**Issue by Tonygithub17** [microsoft/AL#4760]
I having issue when i publish my extension to BC  Production Environment. This Extension i never publish before why system will prompt me the following message ?

"An extension with same App ID and version has already been uploaded. Resolve and deploy again."

![image](https://user-images.githubusercontent.com/34825577/54727552-622f3180-4bb3-11e9-8df9-a67e8945d4e9.png)

**Comment by tomasevicstefan** [comment]
Did you try to change id (GUID) property from app.json file?

**Comment by Tonygithub17** [comment]
> Did you try to change id (GUID) property from app.json file?

No. This is new extension created. And also first time publish in this instance.

**Comment by ShaylaG-MSFT** [comment]
It appears that this extension has been published on multiple other tenants. If you've recompiled the extension package since you uploaded it to the other tenant, the new extension package will have a different Package ID than the original package that was uploaded. Our system requires that any per-tenant extensions with the same AppId/Version also have the same Package ID, regardless of which tenant(s) it's published to. This is required so that we don't manage to publish the "same" extension twice (base on AppId/Version) to a service with different metadata in each. 

Your options are to (1) make sure to use the exact same package when publishing to multiple tenants or (2) change the AppId, Name, or Version to maintain uniqueness across tenants. Option 2 is the recommended approach. 

Check out the "Important" section in this documentation: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization)
