### ISSUE TITLE
Error CS0019: Operator '>' cannot be applied to operands of type 'string' and 'string'

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/AL#4763]
Has anyone faced with similar errors while trying to publish extension to server?

![1](https://user-images.githubusercontent.com/31925856/54743943-e8ed0a00-4bc5-11e9-888d-51249852c85e.png)

I'm looking now in codeunits and can't find where I compare strings with operands <,>,<=

**Comment by thpeder** [comment]
This issue is fixed in the developer preview and will be part of a future release.

This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

You can open Support Request to CSS through PartnerSource portal to get it backported.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
