### ISSUE TITLE
Table Relation Recipient Bank Account

### ISSUE THREAD

**Issue by martinhocosta88** [microsoft/AL#4767]
I've tried for the first time to modify a table relation so I've been testing the following in new development:

On Payment Journal the "recipient bank account" should not load the bank accounts from the "vendor no." but the bank accounts from the "Factoring vendor no." if its filled which is a specific field related with vendor table.

So I've changed the default table relation from the field "recipient bank account" to this:

![image](https://user-images.githubusercontent.com/13696679/54764833-64fc4780-4bf0-11e9-8e47-94d7de7af121.png)

In Yellow are my changes to the standard relation.

Since the behaviour is the same as the standard, my question is: Do the standard relations overwrite changes on already existing relations?

**Comment by atoader** [comment]
Hi @martinhocosta88 ! We've updated the documentation for this feature: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tablerelation-property  . I think this part answers your question: **The combined table relation is evaluated top-down. That means that the first unconditional relation will prevail, meaning that you cannot change an existing TableRelation from Customer to Item, since the original table relation is unconditional.**

**Comment by atoader** [comment]
@JonasPatto we do not have any immediate plans to support this scenario. You can go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. If the idea gathers sufficient support, it will increase the chances that we will consider this for a future release.
