### ISSUE TITLE
Could not attach cookies with HttpClient object

### ISSUE THREAD

**Issue by clagoa** [microsoft/AL#4800]
**Describe the bug**
Is not posible to make HttpRequest that need to attach a Cookie. I'm trying to make some web service calls that need to attach a cookie with the Http Post call. As HttpClient object has no any property to access to the request cookies, I'm passing the cookie as [the header 'Cookie'](https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Cookie), but It's not working as expected. I tested the same use case with Postman and Python and when you attach the 'Cookie' header you get the same result that if you attach a Cookie. 

I tested it with a mock server and the header 'Cookie' was sent but not the Cookie part.

**To Reproduce**
I attach an screenshot with a sample code in AL.

**Expected behavior**
The 'Cookie' header should has the same efect as attach a Cookie with the request.

**Screenshots**
Thats my code:
![image](https://user-images.githubusercontent.com/1621652/55311855-51f53d00-5464-11e9-94f4-6f6a31af869c.png)

The same use case work if you test it with Postman.
![get_request_digest_postman](https://user-images.githubusercontent.com/1621652/55247085-03b72280-5247-11e9-83b4-8b35503a4d59.PNG)

**Versions:**
 - AL Langauge: 2.1.109895
 - Business Central: 13.0.26198

Thanks in advance

**Comment by thpeder** [comment]
Hi @clagoa,
The httpclient doesn't provide any extra help for working with cookies, so you will need to read the spec for how cookies are written in the headers.
If you want this feature in a later version then please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) with your request.

**Comment by clagoa** [comment]
Hello @thpeder ,

Maybe I did not explain myself well, but writing cookies as a HTTP Header is exactly what I'm trying to do. I'm passing the cookies as the 'Cookie' header following the [rfc6265 spec](https://tools.ietf.org/html/rfc6265#section-5.4).

To give you more context, what I'm trying to do is to upload a file to Sharepoint, and to authenticate,  I need to complete 3 steps:
- Get the Security Token which is an HTTP POST call and I get it done without problems
- Get the Access Cookies which is another HTTP POST call and I also get it correctly. The cookies are extracted from the 'Set-Cookie' header sent by the server in the response
- Obtain the Request Digest which is an HTTP POST call that need to attach the cookies received in the previous step.

It is in this last step where I have the problem. I'm including the cookies that I must pass in the request as the 'Cookie' header, but the authentication fails exactly as if no header was sent.

I can complete this auth sequence in different environments (python, postman and javascript) and the procedure is always the same and works correctly. But it does not work from BC.

Can you confirm me that HttpClient object in BC supports the 'Cookie' header?

**Comment by ichladil** [comment]
Hi @clagoa ,
I have run across the same issue now. 
The root cause is likely in the underlying HttpClient in .NET. The following links explain that Cookie header is overriden by default from HttpClientHandler:
* https://d-fens.ch/2016/12/27/howto-set-cookie-header-on-defaultrequestheaders-of-httpclient/
* https://stackoverflow.com/questions/12373738/how-do-i-set-a-cookie-on-httpclients-httprequestmessage

Unfortunately we do not have the HttpClientHandler in our hands in BC and so we have no way of using HttpClient with cookies from AL without using some .NET or Azure Functions or former Web Request and similar libraries.

@thpeder - HttpClient actually actively throws our cookies headers away (see those links above). If there can be done anything on AL HttpClient implementation side to make ALL the headers pass it would help us. 

Thanks!

**Comment by clagoa** [comment]
Hi @ichladil,

Thanks for delving into this topic. I hope the BC team could give some solution to our needs soon, there are many Web Services that need the use of cookies.

**Comment by thpeder** [comment]
Hi,
I haven't investigated what can be done to keep all the cookie headers as well, but we have cookie support on our backlog, but to be honest we have some other features that are higher on the list at the moment, so I do not know when support for it will be implemented.
I would advice you to add it to [Ideas](http://aka.ms/bcideas) since it is easier for us to know where to invest our effort by looking there.

**Comment by jcooper01** [comment]
We are being impacted by this as well. We don't need cookie handling, per se. We just need to be able to set the "Cookie" HTTP header. @thpeder could you please re-open this issue? Again, we just need the HttpClient to not discard the Cookie header. We can handle the cookies ourselves. Some web services require a Cookie header value and we are not able to send it.

**Comment by DanielGoehler** [comment]
Hi @atoader, 
I added the [Idea](https://experience.dynamics.com/ideas/idea/?ideaid=6e80f42d-8b43-ea11-b698-0003ff68dcf8). 

How fast can you add the following two lines to your .NET Wrapper Platform Codebase? 
```
var handler = new HttpClientHandler { UseCookies = false };
using (var client = new HttpClient(handler))
```
It is blocker for two AppSource Apps and when I look above others have the same problem.

**Comment by georgii01** [comment]
The issue still exists.

**Comment by pri-kise** [comment]
For some multi-step authentications we get it to work by using the same httpclient for all of the requests, since the cookie remains in the instance of the HttpClient.
At least for some scenarios this did help us.
