### ISSUE TITLE
Business Charts

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/AL#481]
Hi,

I noticed that Business Charts are not possible in AL.  
- the "external" property has not been set.  
- But also because it's .Net Interop (part).
- And .. it uses control events (which are now blanked during conversion).

What is the scope of this?

**Comment by StanislawStempin** [comment]
It is on the backlog but we don't have a timeframe yet.

**Comment by dennisfrostlander** [comment]
@waldo1001 @jimmymcp
So the business charts are mostly handled via table 485 (Business Chart Buffer), which internally uses .net's System.Data.DataTable and BusinessChart.BusinessChartData. 

An easy way out of this situation is to allow new control add-ins to be passed as an argument to record 485, which will do its magic. 

But the question - do you have any scenarios where you handle the BusinessChartData in your code instead of using table 485? If so, would it be possible to encapsulate this logic in C/AL open library as a .net wrapper?
