### ISSUE TITLE
Specify browser path and command line parameters

### ISSUE THREAD

**Issue by papillon** [microsoft/AL#4826]
**Is your feature request related to a problem? Please describe.**
Like probably most developers, I have multiple browsers on my machine and multiple AAD accounts for various BC SaaS tenants. When launching the browser, and in agreement with Murphy's Law, the AL extension usually calls the wrong browser with the wrong AAD account currently logged in. 

**Describe the solution you'd like**
I would like to specify the command line parameters similar to how it's done in Visual Studio. This would not only allow me to select the browser to launch, but also which profile the browser should use and thus authenticate me against AAD.

Example:
In launch.json:

"launchBrowserCommand": "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "launchBrowserArguments": "--profile-directory="Tenant XYZ""

**Comment by JohanStenberg100** [comment]
Hi @papillon, thanks for filing this issue. We already have support for, in your VS Code settings, `al.browser` and `al.incognito`. These two allow you to choose which browser to launch and furthermore you can start each window in incognito mode. So you can always log into the correct AAD account. I will however treat your issue as a suggestion, since I think we will need something like this in the future.

**Comment by nndobrev** [comment]
Hi! Thank you for your suggestion. We are working on focusing the activity in this repository on addressing issues related to the AL development tools. 
As this issue appears to require changes across multiple areas of our product, we recommend that you post this on our Ideas forum at aka.ms/BCIdeas, or vote up the idea if its already there.
We are constantly monitoring top ideas and will consider them for a future release.
