### ISSUE TITLE
app.json Target property

### ISSUE THREAD

**Issue by RickTweede** [Microsoft/AL#4850]
With the relaxed rules that are coming with allow source code modifications (to ease ISVs into AL) can we get a third Target added to the app.json to control this.
**Extension**: forces you down the cloud route on extensions only - perfect
**Internal**: allows all of the on prem interaction we need also good - i assume this will then allow us to modify standard objects (i.e. table 36...) -  can this be made (or left as it is today - so that you CANNOT edit any standard objects)
**ISV**: add a 3rd option "ISV" which allows you to do everything as the internal plus modify standard objects.

This way we can still force our dev teams to produce extensions for on premise soltuions and not have the same issues we have with upgrades we have today of having to compare and merge all of the modified standard objects.

ty

**Comment by thpeder** [comment]
Hi @RickTweede,
AL does not allow you to do code modification, ie. in one extension change the code inside a procedure that is defined in another extension.
With the move to AL you will have the base application not in C/AL but in AL for and that code you can change like you are used.

If this issue is a suggestion to provide Code modifications on other extensions, then please go to [https://aka.ms/bcideas](https://aka.ms/bcideas)

**Comment by RickTweede** [comment]
so which is is as you've said you can't and you can make mods.. "AL does not allow you to do code modification" can't and  " base application not in C/AL but in AL for and that code you can change like you are used" can.
This is not a "Can i make mods today...." it's a "can we add something to stop/enforce people from making mods in AL to the standard objects once the base is in AL"

**Comment by thpeder** [comment]
For On-premise installation you will have access to all the source code of the base application written in AL as an extension. You can then open these source code files, make your changes to the files and publish your version of the base application instead of the one we provided.
What is not possible is to have the base application as one extension and make separate extensions that does code modifications.

**Comment by RickTweede** [comment]
I think you are missing the point of the requested future functionality - i don't need to know what is possible / not possible - i was suggesting that something get introduced as to force people using on prem installs to ONLY be allowed to build extensions (as per internal property today) and NOT modify any of the standard objects. If this restriction is not there developers are just going to modify the standard objects as well/instead of building extensions and upgrades have the sames issues as they have for the past 20 years.

**Comment by PooyaKharamesh** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
