### ISSUE TITLE
VS Code - "Go to 'Object' Definition" vs "Go to 'Variable Declaration' definition"

### ISSUE THREAD

**Issue by fvet** [Microsoft/AL#4908]
When developing in C/SIDE, the 'Go to Definition' on variables with a complex datatype (pages, tables, codeunits, ...) always opened the 'object'. It didn't point to the variable declaration (globals / locals)

Working in AL with the 'Go to Definition' always navigates / points to the variable declaration first, from where we need to click a second time on the datatype to actually open the object / file.

Is there any option is VSCode (or by means of a 3rd party extension) to allow direct navigation / Go to 'object' definition, the same way it was implemented in C/AL?

recCustomer : Record Customer;
recMyISVTable: Record "MY ISV Table"
...
recCustomer.MODIFY; >> Alternative would be appreciated to open the 'Customer' table when 
right-clicking on the recCustomer.
recMyISVTable.whatever; >> Alternative would be appreciated to open the 'MY ISV Table' table when right-clicking on the recMyISVTable.

**Comment by qutreson** [comment]
Hi @fvet, this behavior is by design. Goes to definition moves you to the variable declaration first and from there you can see the actual object declaration.

Considering introducing a new command to go to the object declaration like C/SIDE was doing, you should look on https://aka.ms/BusinessCentralideas if something similar is already logged and vote for it, or log a new idea there if was not. We're monitoring top Ideas and will consider them for a future release.

**Comment by fvet** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=ec9e4af6-f060-e911-b047-0003ff68a0b2
