### ISSUE TITLE
Is there any way to upgrade business central tenant manually?

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/AL#4917]
Hi Team,

One of our customer is waiting for their Business Central production tenant to get update. Their Sandbox is receiving upgrade but there is no upgrade available for Business Central production environment.
Is there any way we can update tenant manually or any way we can check when upgrade is going to be available for Business Central production.

Best Regards,

**Comment by pmohanakrishna** [comment]
if the latest product is already available in appsource then they just have to uninstall app and install again from appsource.

**Comment by JohanStenberg100** [comment]
Hi, this issue seems like a general BC issue and not related to AL in particular. As I understand it, you are not publishing any extension. I will therefore close this issue and suggest that you open up a support ticket with Microsoft.

I assume you are talking about BC updates and not an app update. Are you referring to an app update, follow @pmohanakrishna's advice.

Thanks,

Johan

**Comment by anuj-inecta** [comment]
Thanks @JohanStenberg100, yes i was talking about general BC issue.
Also, @pmohanakrishna , thanks for advice.
