### ISSUE TITLE
How to show existing field in Business Central?

### ISSUE THREAD

**Issue by hydhart** [Microsoft/AL#4918]
Hi, 
how do I show existing field yet the field is not on the list on the show columns?
![image](https://user-images.githubusercontent.com/41423177/56558288-5e366b00-65c8-11e9-980a-3555e6415045.png)

for example there's field "Fax No." .
is there any way to do this without using extension?

**Comment by pmohanakrishna** [comment]
you have to use Designer functionality in sandbox and add the field to page. it will create an extension in extension management page. download the extension and create app and upload to production tenant.

**Comment by hydhart** [comment]
so everything i need to add an extension have to go through sandbox environment, and then i have to upload it manually to production?

**Comment by qutreson** [comment]
Hi @hydhart, you need to create an extension in order to add existing table fields to a page. If you want to avoid using VS Code for that, using the Designer, as mentioned above, is the way to go. 

This said, this repository no longer handles general questions and is only dedicated to bug reports and feature suggestions for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
