### ISSUE TITLE
Byte[] to PDF

### ISSUE THREAD

**Issue by FSchneiderYav** [Microsoft/AL#4919]
Hello,
I've created a in C# a String with a Byte[] of a PDF
378068704549465510105232483211198106104073100101110116105116121411010111010011198106105332483211198106104065100111981014110101110100111981061056324832111981061060601047701051081161011143247701089711610168101991111001011047761011101031161043255...
Now I want to convert this string back to a PDF.
```
procedure CreatePDF()
var
  lTempBlob: Record TempBlob temporary;
  lstmoStream: OutStream;
  lcuFileMgt: Codeunit "File Management";
  i: Integer;
  lText: Text;
begin
  lText := GetString();
  lTempBlob.Insert();
  lTempBlob.Blob.CreateOutStream(lstmoStream);
  for i := 1 to StrLen(lText) do begin
    lstmoStream.write(GetBit(lText[i]));
  end;
  gTempBlob.CalcFields(Blob);
  lcuFileMgt.BLOBExport(lTempBlob, 'BlobToPDF.pdf', true);
end;
```

The function creates now a PDF, but I can't open it.

**Versions:**
 - AL Language: 3.0.107312
 - Business Central: 14.0.29487.0

**Comment by JohanStenberg100** [comment]
Hi, this issue is not fitting our guidelines for this repository. Your example is using custom procedures whose source code is not shown in your question. You'll have better luck posting this question to one of the following resources to get help on AL extension development issues:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Using these resources will assist you in getting help from other AL developers. Thanks!
