### ISSUE TITLE
Assigning enum value based on GetFilter

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL#4948]
Code like Evaulate(MyTable.MyEnum, MyTable2.GetFilter(MyEnum)) does not work in any other language then ENU.

This kind of coding works with C/AL but with AL it doesn't find the enum value (error message says OptionValue btw) based on the return value from GetFilter.

AL version 3.0.121490
Runtime: 3.0

**Comment by PooyaKharamesh** [comment]
would you please send us a package that reproes the issue?

/Pooya

**Comment by larswestman** [comment]
Here's a project with an enum where the ENU caption differs from the value so it will give you an error even when using ENU as language. The error will be raised in HelloWorld.al when you run page 22.

[EnumError.zip](https://github.com/Microsoft/AL/files/3141836/EnumError.zip)

**Comment by larswestman** [comment]
I guess this is related.

![image](https://user-images.githubusercontent.com/43792551/57253292-aafd5580-704e-11e9-90af-0cfdc3d77c74.png)

The new record does not get the enum value "Source Type" populated based on the filter the same way as the column "Source No."

**Comment by larswestman** [comment]
Have you been able to look at this @PooyaKharamesh ?

**Comment by larswestman** [comment]
And some more on the topic of enums and filtering

This does not work (it should):

`SetFilter("Source Type", '%1|%2', "Source Type", "Source Type"::" ");`

But this works:

`BookingRule.SetFilter("Source Type", '%1|%2', "Source Type" + 0, 0);`

**Comment by kevindstanley1988** [comment]
I have a related issue, where I am forced to try to use GETFILTER because Enums don't work as expected. When you have an enum type field in a table, and on a page you have an action that uses RunPageView utilizing that enum field the enum value is not maintained.
`RunObject = Page "YourPage"`
`RunPageView = WHERE ("Field2Enum" = CONST ("An Enum Value")`

The subpage does not maintain the enum value when you create a new record in the page that opens from the action if you click 'New' to create a new record. This is different from how optionstrings work in this same situation. I do not believe this behavior is expected and is a bug.

**Comment by kine** [comment]
Related to: https://github.com/microsoft/AL/issues/4698

**Comment by esbenk** [comment]
Fixed in the 2019 Wave 2 release and backported 2019 Wave 1 version 14.6
