### ISSUE TITLE
Page Extension Caption & AdditionalSearchTerms Issue

### ISSUE THREAD

**Issue by mpopelka** [microsoft/AL#4954]
**Describe the bug**
Modifying a page Caption or adding AdditionalSearchTerms does not appear in the Tell Me search. This issue is related to existing issues #4569 & #4907. I am inquiring about an expected timeline for either of these issues to be resolved.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create Page Extension.
2. Modify Caption or add AddtionalSearchTerms.
3. In BC Web Client search for new caption or search terms.

**Expected behavior**
Tell Me shows caption change or populates the additional search terms.

**Versions:**
 - AL Language: 3.0.126610
 - Business Central: US Dynamics NAV 13.5 (31813)

**Comment by PooyaKharamesh** [comment]
Thank you for reporting this issue. This is a problem that we are aware of and that we have on our backlog. We will use this issue to track this problem on Github.

/Pooya

**Comment by mpopelka** [comment]
Is there a timeline though for when this issue will moved from your backlog to active or anticipated time it will be resolved? I have client work that is dependent on this issue being fixed.

**Comment by SUD-D365** [comment]
Hi,

I am also facing same issue. Modified Page caption is not showing in **Tell Me** search window.
Is there any update on this?

Thanks

**Comment by pborring** [comment]
This is fixed in 2019 Wave 2 (v15 ) CU1 - translation and AdditionalSearchTerms works for pageextensions.

Note that XLIFF translations take precedence if present (as applied after metadata flattening of extension contributions), so if doing a pageextension of a base object like Vendor, you need to provide the caption in XLIFF and not as a Caption property in the pageextension object. Also, if multiple extensions change the caption property or XLIFF translation, the last loaded extension "wins".
