### ISSUE TITLE
How to get Web Service Key for current user

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/AL#496]
Codeunit 9801 Identity Management has functions to create and get web service keys. Those functions are not exposed for Extensions v2.

What if an app needs to create or get the web service key for the current user? The scenario would be that an app creates a web service and need to access that from outside. The only way is to ask the user to create a web service key with on the User Card and copy paste it. That's not a user friendly process.

Would it be possible to add functions to Codeunit Identity Management like 'CreateWebServicesKeyCurrentUser' and 'GetWebServicesKeyCurrentUser' and expose them for Extensions v2?

**Comment by SBalslev** [comment]
Hi Arend-Jan, 
Great question - and I'm not going to answer it ;) but I do want to understand it so I hope you can help me.

Could you share some scenario where you would want the web service key and not use an OAuth flow for Extensions v2?

**Comment by ajkauffmann** [comment]
The scenario would be a to have an app create a web service and a key without bothering the user.
Why not use OAuth? Well... just because it's quite new and I didn't have it on my mind as the way to go.
To be clear: are you referring to this? https://msdn.microsoft.com/en-us/library/mt634540(v=nav.90).aspx

**Comment by ajkauffmann** [comment]
Hmmm... reading more closely through that article now. You need to have information from Azure (App ID URI / AAD Tenant ID) that is for sure not accessible when you set up an application that needs to access D365 web services. So I guess we need a walk through for D365 as well. Is that already available?

**Comment by SBalslev** [comment]
It all depends on what you want to do :)

The link is correct but you don't need to know the aad tenant id, just auth against the common endpoint as you want the backend (extension backend service) to work for all tenants not just one.

So you need an app in an AAD tenant (ex. extension owner AAD tenant) maked as multitenant (so it can be access by other tenants) and setup to require Financials permissions.
Then you can use that to get access to a customer tenant web service.

We don't support OAuth 2 scopes yet but you can use "normal" OAuth 1 based on resources.

Not really the place for POC but I did do a small one - try it on http://financials.mydemo.dk
Took the code from https://dev.office.com/code-samples-detail/2306 and modified it a bit - it's a pure clientside app so all code is there for your enjoyment :)

**Comment by kvaldik** [comment]
Hi Arend-Jan,
Did you get OAuth to work on D365, did you find any instructions on it?

Is the Identity Management codeunit completely off the table? We have built a payment app that we invoke from our D365 extension using URI. Included in the URI is a link to a D365 web service, the username and password (web service access key). The payment app collects the payment and posts the results to D365 through the provided web service.

It would be a lot nicer to be able to do this using the web service access key instead of having to implement the OAuth functionality in our payment app. The user experience is also better when there is no need enter the credentials in our app.
