### ISSUE TITLE
Issue in deploying extension on PRODUCTION.

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#4967]
Hi,
I am getting below error while uploading .app on production environment.
**There was an internal error validating the tenant, please try again. Job id:'a9976826-18b4-463d-93f7-4e9fc2e5be8d'**

Business central version

CA Dynamics NAV 13.5 (31813)

Kindest regards

Adding one more screenshot.
![image](https://user-images.githubusercontent.com/33481576/57767314-ad367280-7726-11e9-98b9-311df07a93c3.png)

**Comment by JohanStenberg100** [comment]
Hi @SUD-D365! We can't help you with this issue here. We only accept issues regarding the tooling itself. You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

Thanks,

Johan
