### ISSUE TITLE
The call is ambiguous between the following methods or properties: 'foo()' and 'foo()'

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/AL#4997]
**Bug Description**
We receive the following error message while trying to run function that has identical name on two different extensions.

`The call is ambiguous between the following methods or properties: 'foo()' and 'foo()'`

**To Reproduce**

1. Make Extension1
```
pageextension 50110 CustomerListExt extends "Customer List"
{
    procedure foo()
    begin

    end;

}
```

2. Make Extension2

```
pageextension 50111 CustomerListExt2 extends "Customer List"
{
    procedure foo()
    begin

    end;
}
```

3. Make Extension3 which depends on Extension1 and Extension2
```
pageextension 50112 CustomerListExt3 extends "Customer List"
{
    trigger OnOpenPage();
    begin
        foo();
    end;
}
```

**Expected behavior**
Here we created these extensions and control the naming, but if we have 3rd parties extensions, it might lead to some drama. In my view this is the gap in AL design. Design should prevent you from doing this or support it. Developer might one to execute both functions from both extensions:

```
pageextension 50112 CustomerListExt3 extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Extension1.foo();
        Extension2.foo();
    end;
}
```

 - AL Language: 3.0.126610
 - Business Central: on prem CU3

Gintautas

**Comment by esbenk** [comment]
Right now this is by design. 

We are planing to make the closest symbol (in this example Foo() in your own extension will be found before the Foo() in the base). This will prevent adding a method to the base to break compilation of an extension to the table/page. That is expected to be in the October release.

This will not solve your case though. We will probably also support qualification in future as well. We don't have a timeline yet.

**Comment by qutreson** [comment]
The AppSourceCop will also provide validation about it in the future, see #5255 
Using affixes is a way to significantly decrease the likelihood of facing this kind of issues.
