### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/AL#5009]
Hi All,

I am facing an error while uploading an .app file on a Cloud Sandbox environment.
Its seems a dependency error. 
Can anyone suggest any solution, since i uploaded all the dependency first and then trying to upload this .app file.

Below is the error.

Deployment failed. Errors: App ID : 7e996381-60d3-403c-b420-b60e7eab9b5c Message : { Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for ResponsibilityPage Extension by NetsmartzLLC 1.0.0.2. } - Job Id : 31b5f229-f9f2-4cdd-aeee-0590265ebbab

Below is extension upload summary for which current .app file is giving error.
![image](https://user-images.githubusercontent.com/33481576/58427011-f1792980-80bb-11e9-8931-9c839371ec18.png)

**Comment by tomasevicstefan** [comment]
Can you share with us app.json file of that extension?

**Comment by ShaylaG-MSFT** [comment]
This problem occurs when a newer version of the dependency (in this case "ResponsibilityPage Extension") has been synchronized on the tenant database, **but is no longer published.** It appears that version 1.0.0.3 of "ResponsibilityPage Extension" was published as a developer extension and then unpublished later. Therefore, we detect that the synchronized version of the dependency is v1.0.0.3. Since v1.0.0.3 is no longer published, you'll get this error "Cannot synchronize the extension because no synchronized extension could be found to satisfy the dependency definition for ResponsibilityPage Extension by NetsmartzLLC **1.0.0.2.**" Even though v1.0.0.2 satisfies the dependency, it is not technically considered the "synchronized" version. 

We are working on making a change to the platform logic to consider ALL published versions of the dependency, rather than only the "highest sync'd version". The new logic would detect that there is a published/sync'd version that is greater than or equal to v1.0.0.2. In the meantime, you can mitigate this issue by **ensuring that the "highest sync'd version" is _published_ on the server.** 


**Mitigation**: Deploy "ResponsibilityPage Extension" v1.0.0.4 and then retry the Deploy operation for the dependent extension.

**Comment by SUD-D365** [comment]
Hi @ShaylaG-MSFT ,

Thanks for your prompt revert.
I tried your suggested solution, but now the dependent extension giving error for another dependency extension, like below. Although it has been deployed successfully on Cloud sandbox without any problem. Problem seems related to Table Change, but i am not able to find which table change i have done in this extension and how to recover that.
![image](https://user-images.githubusercontent.com/33481576/58722438-0c69d780-83f5-11e9-9113-9f4b6a6d39d8.png)
 
Please help me out.

**Comment by ShaylaG-MSFT** [comment]
Back on April 24th, you deployed version 1.0.0.0 of the extension that you are currently trying to upload. (It was deployed as a developer extension via VS Code). That version of the extension contained a Table Extension called "AssemblyLineExt" which extended base Table 901 "Assemble Line". In your latest version of the extension, you must have removed this table extension. 

The easiest mitigation for this is to follow these steps:
1. Deploy the latest version of your extension using VS Code. Make sure to set the "schemaUpdateMode" to "Recreate" or "ForceSync" in the Launch.json. **This will get the schema to synchronize correctly and remove any database schema associated with the missing Table Extension**. Here's documentation around the difference between Recreate and ForceSync: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-retaining-data-after-publishing 
2. Uninstall and unpublish the extension so that this developer extension doesn't interfere with your upload attempt. 
3. Try to upload the extension as a Per-tenant extension again.

**Comment by SUD-D365** [comment]
Hi @ShaylaG-MSFT 

Thanks for your help!!
But, it solved after creating a new sandbox and uploading all apps on that sanbox.
