### ISSUE TITLE
BUG - The data is not correctly saved

### ISSUE THREAD

**Issue by JuditNavarro** [microsoft/AL#5109]
Hello AL-team!

Nowadays, I'm working with dockers, using a container of the image mcr.microsoft.com/businesscentral/onprem:es-ltsc2019 and using its Business Central web client. 
Doing some tests, I was trying to change some data in the field of a table, and I found something strange. 

I'll show an example for my explanation: 
When I go to an standard object, for example, "Items":
![image](https://user-images.githubusercontent.com/44970454/60659829-45f78d80-9e4e-11e9-9197-2592c8f64653.png)

If I open an "item card"...
![image](https://user-images.githubusercontent.com/44970454/60661834-bbfdf380-9e52-11e9-9496-4fa62172fd66.png)

...and I edit one field (in this case, "Description" field), the auto-save works and says that it saved the changes, and you can see that it changes it in the title of the card too, BUT, if you see in the data of the table, the change is not done:
![image](https://user-images.githubusercontent.com/44970454/60663001-df766d80-9e55-11e9-88d2-78ecc4fb9d01.png)

If you go out of the page, and open again the Item card, NOW is when you can see that the change is correctly done in the table 
![image](https://user-images.githubusercontent.com/44970454/60663059-1187cf80-9e56-11e9-96fd-22d9c979fdff.png)
![image](https://user-images.githubusercontent.com/44970454/60663103-2cf2da80-9e56-11e9-86d1-ccf0947b53bb.png)

I think that this is problably a bug, because It doesn't seem logical that the changes of your data won't be correctly saved if you don't go out of the current page, isn't it? 

So, if you make a change of your data, and close the tab of your browser without going out of the page, the change will not be correctly done and saved.

Just in case, my actual symbols' version are: 
![image](https://user-images.githubusercontent.com/44970454/60663591-90c9d300-9e57-11e9-9840-9eadc52d70c2.png)

**Comment by chrischbo** [comment]
Seems that the data is stored correctly just the Page Inspector isn't updated at this moment. Close Page Inspector and reopen it. Data is now correctly updated

**Comment by JuditNavarro** [comment]
Well, when I did the tests, I conected to the database too to see if the data is updating or not in the table, and the field in there did the same behavior than the Page Inspector, so that's why I thought it's a bug...

To connect to the database and inspect it, I used the IPAddress of the container, and the autentication's data that I use in there.

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. Database updates due to the page change are not covered by this repository. We suggest that you open a support case to ensure that all Business Central users benefit from your catch as soon as possible.  

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
