### ISSUE TITLE
Snippet for page part doesnt fill applicationarea property

### ISSUE THREAD

**Issue by frivadulla** [microsoft/AL#5124]
**Describe the bug**
I think that title is clear enough. While you are creating pages, parts are not filled with the ApplicationArea property, and the subpages are not shown. I think this should be solved in order to avoid errors.

**Versions:**

 - AL Language: 3.0.145991

**Comment by atoader** [comment]
Thanks, @frivadulla ! We'll fix this in the next major release of the extension.

**Comment by NKarolak** [comment]
> I see no warning or error, as is done when ApplicationArea is missing on a page field.

The rule is already enforced. Is either the [AppSource Cop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0062-useapplicationareaproperty) or [PTE Cop](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop-pte0008-useapplicationareaproperty) really active?

**Comment by qutreson** [comment]
We will add the ApplicationArea to the snippet for the next release because the property is there for the page field snippet, but on the part snippet. However, when enabling AppSourceCop or PTECop, you should be receive a warning that the ApplicationArea must be filled in.

![image](https://github.com/microsoft/AL/assets/31541422/1e79b603-752e-4d4c-a4d6-0294da3b4417)

Note that from version 11.0, we are also using the ApplicationArea defined on the page level as a default for the application area of controls/actions which do not explicitly specify one. Since most items are addressed already, I am closing this issue already.
