### ISSUE TITLE
Action Button Promoted Visible

### ISSUE THREAD

**Issue by MeFrancois** [microsoft/AL#5156]
Hi,
I would like to hide the 'Post' button from page Service Lines (5905).
I did the following code:

        modify(Post)
        {
            Visible = false;
            Promoted = false;
            Enabled = false;
            CaptionML = ENU = 'Obsolete', FRB = 'Obsolete', NLB = 'Obsolete';
        }

The button in the Tab is hidden.
But the promoted button is still visible.
How is possible to hide the promoted button?

![image](https://user-images.githubusercontent.com/53210976/61690912-b0ec0400-ad2a-11e9-8ba8-88c1c4738a5b.png)

**Versions:**
 - AL Language: 3.0.152816

 - Business Central:VErsion BE Dynamics NAV 14.0 14.0.29530.0

**Comment by BartPermentier** [comment]
Hey,

I ran into this issue a lot of times. Since you are using the windowsclient you can use configuration mode to quickly hide the action for a bunch of users.
https://docs.microsoft.com/en-us/dynamics-nav/how-to-open-microsoft-dynamics-nav-in-configuration-mode
Hiding fields and actions has always been a bit wonky in the Windowsclient and I don't think it's high on their backlog since they will retire the client in 2 months :)
Hope it helps!

**Comment by atoader** [comment]
Hi! In the last months, we've been working hard on adding new features that increase your productivity and on improving the quality of the tools. Unfortunately, this meant that we were not able to follow up on as many GitHub issues as we have liked.
Is this issue still a problem for you? Can you provide a sample project to reproduce the issue? Does it reproduce on the Wave 2 2019 release?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
