### ISSUE TITLE
DotNet type casting

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/AL#5166]
- AL Extension Version: 3.0.152816

Hi,

I have a piece of code that I would like to verify: in "before AL" this worked fine now it does no longer.

I have a function that gets values from a dotnet dictonary to a dotnet List [it is NOT the AL default types!]. I get the following Error:

Argument 1: cannot convert from 'DotNet "System.Collections.Generic.Dictionary`2+ValueCollection"' to 'DotNet "System.Collections.Generic.List<System.Object>"'

This was fine in old solutions. And I do have the need for it as the default List and Dictionary are to "stiff" while ours (and yes we are onPrem) handles dynamic types.

a similar thing happens with this:
Argument 1: cannot convert from 'DotNet "System.Collections.Generic.Dictionary`2+KeyCollection"' to 'DotNet "System.Collections.Generic.List<System.Object>"'

Any advice or idea why this is no longer supported?

**Comment by KristofKlein** [comment]
This now also needs to be extended with following:
in the old days we could references dotnet enums with the actual value represented by an integer. as an example:
Newtonsoft.Json.DateTimeZoneHandling - this is an enum with value 0..3. with C/AL we could in our code simply use this: so myNewtonsoftDateTimeZoneHandling := 0; and that's it. This does no longer work. This makes stuff quite hard. It also does not allow to use an AL Enum as input...

**Comment by atoader** [comment]
Hi! In your first case, the only reason it worked was because C/SIDE lost type information at some point in the chain and at runtime, the methods you called were available. As you can see: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.valuecollection?view=netframework-4.8
ValueCollection does not extend List<Object> so a direct conversion is not possible. 

Yes, this change is breaking, as compared to C/SIDE, but it will prevent bugs in the long run. If you were to call a method that is only available on List<Object> but not on the types implemented by ValueCollection, you would have received a runtime error.

For the second case, I have written the following snippet:
```
dotnet
{
    assembly(Newtonsoft.Json)
    {
        type(Newtonsoft.Json.DateTimeZoneHandling) { }
    }
}

codeunit 50100 MyCodeunit
{
    trigger OnRun()
    var
        x: Dotnet DateTimeZoneHandling;
        i: Integer;
    begin
        x := i;
        x := 0;
        x := x."Local";
        x := x.Unspecified;
    end;

    var
        myInt: Integer;
}
```
Assigning an integer to a .NET enum works. Assinging an AL enum to a .NET enum will not work, but we have a set of APIs in the pipeline that will allow for performing an explicit conversion.
