### ISSUE TITLE
File Management - AddStreamToZipStream

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/AL#5178]
**Describe the bug**
I have to add to a zip stream some HTML files (for e-invoice) that are a merge between the XML and the XSL. Anyway if I download the HTML without compressing it will render the characters correctly:

![image](https://user-images.githubusercontent.com/36199751/62636130-4695af00-b939-11e9-8d72-53d9acfce852.png)

but if I compress it and then download it the characters are not rendered correctly:

![image](https://user-images.githubusercontent.com/36199751/62636229-6cbb4f00-b939-11e9-8712-0d94f7f057e6.png)

This is due to an encoding difference, I suppose the first is UTF-8 and the other ANSI

Now, to avoid these errors I've changed the procedure from this (look to the encoding):
`StreamReader := StreamReader.StreamReader(StreamToAdd,Encoding.Default);`
to this
`StreamReader := StreamReader.StreamReader(StreamToAdd,Encoding.UTF8);`
I don't think that it is the best way to solve this but it will be better if we could choose the encoding to use (maybe by adding the encoding to the parameters of the function)

**Versions:**

 - AL Language: 4.0.158692

 - Business Central: BC 140 RTM with IT Localization

**Comment by atoader** [comment]
@stefanoPrimo what type is the StreamReader that you are using for this?

**Comment by stefanoPrimo** [comment]
Hi, @atoader 
I'm not using any stream reader. 
in my extension I've written down these lines:
```
Clear(is);
TempBlob.Blob.CreateInStream(is, TextEncoding::UTF8);
FileManagement.AddStreamToZipStream(ZipOS, is, FileName);
            
Clear(is);
Archive.Blob.CreateInStream(is, TextEncoding::UTF8);
FileName := 'Invoices.zip';
DownloadFromStream(is, 'Download XML', '', 'ZIP Files (*.zip)|*.zip', FileName);
```
where the variables TempBlob and Archive are like this: `Archive: record TempBlob Temporary;`
The problem is in the standard function `AddStreamToZipStream` in the codeunit `FileManagement`

**Comment by atoader** [comment]
Thanks @stefanoPrimo ! I will forward this issue to our application team.

**Comment by dcenic** [comment]
This is fixed in the upcoming release Business Central 15. In this release, the data compression methods are moved from File Management codeunit into Data Compression codeunit.
The method that adds an entry to the zip archive - DataCompression.AddEntry(StreamToAdd: InStream; PathInArchive: Text), no longer uses StreamReader to read the stream and StreamWriter to write it to the archive. It simply does CopyStream, and it is therefore independent of the original encoding of the stream to add. It will just copy the stream bytes into the archive entry.
