### ISSUE TITLE
Client crashes on click to navigate to subpage

### ISSUE THREAD

**Issue by angela2389** [microsoft/AL#5207]
The client crashes when clicking on a field to redirect to a subpage. 
This happened on Page: No. Series (456, List), if you click on the field "Starting No.". 
![image](https://user-images.githubusercontent.com/18716238/63331137-5350d480-c335-11e9-8f3e-4c24c33129d0.png)

Error:

> Something went wrong.
> An error has occurred
> Date and time (UTC): Tue, 20 Aug 2019 08:11:37 GMT
> Azure AD tenant: common
> Environment: Sandbox
> Operation: eb65d8c5-0689-4939-b0c3-6688c948d333_

**Versions:**

 - AL Language: 4.0.158692

 - Business Central: 15.0.34855.0

**Comment by atoader** [comment]
Hi! This repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open file a bug in Collaborate so that this issue gets redirected to the appropriate team. I've notified the team about this bug, but they might need additional information which can only be acquired through collaborate.
