### ISSUE TITLE
Client crashes on deleting line

### ISSUE THREAD

**Issue by angela2389** [microsoft/AL#5208]
**Describe the bug**
When clicking on an delete action within a page (tried on multiple pages) the client crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/18716238/63334427-ae85c580-c33b-11e9-9453-dd4b7359b6cf.png)
![image](https://user-images.githubusercontent.com/18716238/63334560-f4428e00-c33b-11e9-94cc-1e5d6d3a9441.png)

**Error:**
> Something went wrong.
> An error has occurred
> Date and time (UTC): Tue, 20 Aug 2019 09:16:46 GMT
> Azure AD tenant: common
> Environment: Sandbox
> Operation: b38d09ef-148c-4d98-8a1c-25143098c855
> Go back home

**Versions:**

 - AL Language: 4.0.158692

 - Business Central: 15.0.34855.0

**Comment by atoader** [comment]
Hi! This repository is only for issues related to the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open file a bug in Collaborate so that this issue gets redirected to the appropriate team. I've notified the team about this bug, but they might need additional information which can only be acquired through collaborate.
