### ISSUE TITLE
Enable Timestamp on table extension

### ISSUE THREAD

**Issue by zuhadmahmood** [microsoft/AL#5212]
Hi Sir,
I am using the business central cloud sandbox .The AL is not allowing to enable Timestamp on table extension. Is there any other way to enable it? 
 
![image](https://user-images.githubusercontent.com/15164880/63430729-bd9d6e00-c436-11e9-92ca-59d1255d28c8.png)

App.json  :
![image](https://user-images.githubusercontent.com/15164880/63430843-081eea80-c437-11e9-8dce-8eaf2957c33d.png)

Thanks,

Zuhad Mahmood

**Comment by atoader** [comment]
The SqlTimestamp property can only be set once per table in the runtime. This means that it can only be set by the main table, not by the table extension. At the moment, this is by design.
Changing this will require a cross-team effort. Please consider posting this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
