### ISSUE TITLE
Cannot sign runtime app file generated from 14.X versions

### ISSUE THREAD

**Issue by spapke** [microsoft/AL#5254]
After generating a runtime app file from a 14.X version in a docker container, I am unable to digitally sign the generated runtime app. This has been observed for on prem versions 14.0.29537.0-na and 14.1.32615.0-na. When attempting to sign the runtime app file in either the docker container or locally using SignTool I get the error, "SignTool Error: This file format cannot be signed because it is not recognized."

It should be noted that the non-runtime app file can be signed.

**To Reproduce**
1. Create a new docker container running a BC 14.X version.
2. Publish a .app file to NAV in the container.
3. Generate the runtime app file in the container.
4. Attempt to sign the generated runtime app file.

**Expected behavior**
Runtime app files can be digitally signed.

**Versions:**
BC on prem
14.0.29537.0-na
14.1.32615.0-na

**Comment by spapke** [comment]
@thpeder Is there a workaround until this ships? What update will this be fixed in? What was the issue that caused this?

**Comment by thpeder** [comment]
To answer your questions in order.
1) No there is no workaround. You simply can't sign runtime packages and publish a signed runtime package. The only option is to not sign them.
2) 14.6, I don't know when that will be released.
3) We changed runtime packages so you can't just open them with an archiving program, in doing that we broke the format the signing library worked with, so we needed to find another fix to still maintain both properties.

The fix is in our docker images from build 36036, so please have a try with that and tell us if you run into some other issue with it, Thanks.

**Comment by spapke** [comment]
Thank you for the clarification!
