### ISSUE TITLE
[AA0175] ISEMPTY is not an appropriate substitute.

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#5328]
**Describe the bug**
The new V4 warning `"warning AA0175: Variable 'TimesheetLedger' queries the database in 'CreditInvoice' but does not use the queried record. Only find or get record if you need to access the values. Consider using ISEMPTY."` is generally very good but is occasionally being triggered when there isn't a reasonable replacement.

**To Reproduce**
Use a `FindFirst` to trigger an error with all the filters described correctly in the error message.

``` AL Code to reproduce the issue ```
```
            if TimesheetLedger.IsEmpty then
                TimesheetLedger.FindFirst;
```

**Expected behavior**
This piece of code definitely uses features of the `FindFirst` function that `IsEmpty` cannot replicate so the warning should not appear.

**Screenshots**

**5. Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.182565
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by atoader** [comment]
Hi @rdebath ! We have looked at this case and we think that a warning should be reported. The pattern above could be used to throw an error and terminate execution, but the intent of code is not clear even to a human reader.
We plan to add support for suppressing specific instances of diagnostics in the future so that you can suppress instances that you understand, but for the moment, we will mark this as a "Won't fix".
