### ISSUE TITLE
General Journal Show Fewer Columns Error

### ISSUE THREAD

**Issue by goetudose** [microsoft/AL#5336]
When is used button "Show Fewer Columns" from "General Journal" and it's selected and batch who has Bal Account Type Bank Account and has complete Currency Code then it appear the bellow error.
![image](https://user-images.githubusercontent.com/35959288/66376662-d3e89480-e9b8-11e9-917d-f8e8db47c827.png)

It seems in the function SetDataForSimpleModeOnOpen variable CurrentCurrencyCode is cleared whitch generate the error.

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
