### ISSUE TITLE
Missing events in various places (posting)

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#534]
During the development of the extension, we have noticed a number of places where events are missing in the standard booking process. Without these, it is not possible to implement certain functionalities. Specifically, this involves the following:

- Codeunit 366 - OnBefore and OnAfter Exchange Acc. G/L Journal Line.
- Codeunit 12 - OnAfterRunWithCheck
- Codeunit 12 - OnBeforeExecuteCode Function (to check and modify Gen. Journal Line)
- Codeunit 12 - OnAfterGLFinishPosting -> Gen. Journal Line missing parameter
- Codeunit 12 - OnBeforeContinuePosting
- Codeunit 13 - OnBeforeUpdateAndDeleteLines
- Codeunit 17 - OnBeforeReverse
- Codeunit 17 - OnBeforeCreateReversedEntry
- Codeunit 17 - OnBeforeCreateCustLedgEntry
- Codeunit 17 - OnBeforeCreateVendLedgEntry
- Codeunit 17 - OnBeforeCreateDtldCustLedgEntry
- Codeunit 17 - OnBeforeCreateDtldVendLedgEntry
- Codeunit 80 - OnBeforePostGLAndCustomer
- Codeunit 80 - OnAfterPostingBalancingEntry
- Codeunit 80 - OnAfterPostInvoicePostBufferLine
- Codeunit 90 - OnBeforePostGLAndVendor
- Codeunit 90 - OnAfterPostingBalancingEntry
- Codeunit 90 - OnAfterInsertPostedHeaders
- Codeunit 225 - OnBeforeGenJnlApply
- Codeunit 225 - OnAfterGenJnlApply
- Codeunit 226 - OnBeforeCustPostApplyCustLedgEntry
- Codeunit 226 - OnAfterCustPostApplyCustLedgEntry
- Codeunit 227 - OnBeforeVendPostApplyVendLedgEntry
- Codeunit 227 - OnAfterVendPostApplyVendLedgEntry
- Codeunit 367 - OnBeforeVoidApply
- Codeunit 367 - OnAfterVoidApply
- Codeunit 367 - OnBeforeFinancialVoidCheck
- Codeunit 367 - OnAfterFinancialVoidCheck
- Codeunit 426 - OnBeforeCalcRemainingPmtDisc
- Codeunit 426 - OnAfterCalcRemainingPmtDisc
- Codeunit 426 - OnBeforeCheckCalcPmtDisc
- Codeunit 426 - OnAfterCheckCalcPmtDisc
- Codeunit 432 - OnBeforeGenJnlPostLineFinally
- Codeunit 432 - OnAfterGenJnlPostLineFinally
- Codeunit 442 - OnBeforeSalesPostPrepayments
- Codeunit 442 - OnAfterSalesPostPrepayments
- Codeunit 442 - OnBeforePostBalancingEntry
- Codeunit 442 - OnAfterPostBalancingEntry
- Codeunit 444 - OnBeforePurchasePostPrepayments
- Codeunit 444 - OnAfterPurchasePostPrepayments
- Codeunit 444 - OnBeforePostBalancingEntry
- Codeunit 444 - OnAfterPostBalancingEntry
- Codeunit 5988 - OnBeforePostDocumentLines
- Codeunit 5988 - OnAfterPostDocumentLines
- Codeunit 5988 - OnBeforePostCustLedgEntry
- Codeunit 5988 - OnAfterPostCustLedgEntry
- Codeunit 5988 - OnBeforePostBalancingEntry
- Codeunit 5988 - OnAfterPostBalancingEntry

These events are very important to get control over the posting process. Many of the codeunits did not even have a single event!

And yet another question. How do you find out by event, whether it is the posting preview, or a real posting? Is there already a solution for this?

**Comment by fvet** [comment]
Some extra event-request candidates:

- Codeunit 1509 - Notification Entry Dispatcher - **OnAfterGetTargetRecRef** (in case we're able to provide new option values for the 'Type' field)
- Codeunit 1510 - Notification Management - **OnAfterGetActionTextFor** (in case we're able to provide new option values for the 'Type' field)
- Codeunit 1510 - Notification Management - **OnBeforeGetDocumentTypeAndNumber** (with a 'Handled' parameter) or **OnAfterGetDocumentTypeAndNumber** (supposing the ELSE part of the case structure is changed from FIELD(3) to FIELD(1), since my table doesn't have a field 3 ...)

My goal with the above was to create a 'Notification Entry' of type 'New Record' when a new record in my custom table was created. Although I couldn't get the URL for the notification working, since it did not contain the filter in the URL to open the page. So either I would add 

```
IF NOT RecRef.HASFILTER THEN
    RecRef.SETRECFILTER;
```

on the code below (codeunit 1509), either adding custom 'Type' values should be supported to customize the 'Nofication' framework.

![image](https://user-images.githubusercontent.com/25268332/30035587-1e71f31e-91ac-11e7-843a-446b9591ee5c.png)

**Comment by AlexanderYakunin** [comment]
Request for posting events is absolutely valid, we are actively working to add more events here. Some of events from your list have been already implemented, remaining suggestions will be processed in few weeks.

**Comment by AlexanderYakunin** [comment]
Implementation completed, please check next update

**Comment by FSharpCSharp** [comment]
@StanislawStempin 
As I see the events were postponed to November. I was just wondering why none of the events are included in the October update released yesterday.

**Comment by warloa** [comment]
Are you able to say if in the fix will be any events in the jobs posting (i.e. CU 1012)?
Especially missing onBeforePostJobLedgerEntry and onAfterPostJobLedgerEntry
