### ISSUE TITLE
"Find all references" for local variables

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#535]
The function "search all references" is indeed very useful for global variables and also functions. Would it also be possible to make these available to the local variables? Thus you could very quickly jump to the place of use.

**Comment by esbenk** [comment]
It is implemented for local variables (and parameters). Just do "Shift+F12" on top of the name. Do you have an example of this not working?

**Comment by FSharpCSharp** [comment]
OK, then I have expressed myself wrong. The text "X references" is missing from the local variables. This would quickly reveal how often a local variable is used and which are not used anywhere.

**Comment by esbenk** [comment]
We decided against that, because it will often expand screen area used by the variable declarations to much, with limited value.

The plan is to provide some additional code analysis, for things like unused variables etc. 

There is some experimental code analysis with some test rules (style, deadcode, unused variables/parameters). It is very experimental, but you can try it by adding

    "al.enableCodeAnalysis": true

to the settings file.

**Comment by FSharpCSharp** [comment]
Thank you for this information. I have added the option mentioned in the settings. Since there are really very many examinations thereby making sense, such as overflow check and indentation errors. Very good work!

**Comment by esbenk** [comment]
It is still very experimental and work in progress. The long term plan is to add many checks here and productize it.

**Comment by pzentner** [comment]
oh I like it. wouldn't have found that without reading this issue. nice job!
