### ISSUE TITLE
The target Table "XXXX" for the extension object is not found

### ISSUE THREAD

**Issue by jhanvillasin** [microsoft/AL#5384]
**Describe the bug**
Hi I'm a newbie in extensions. I'm having a trouble when creating extension to Purchase line. every time I pres F5 it gives me an error. please see image below. 
![image](https://user-images.githubusercontent.com/56950300/67456427-461cd280-f663-11e9-88bf-bbba86904446.png)

I already Uninstall and Install the AL language. I have the newest version of AL language. Weird part is if I type Purchase Header Or Purchase Line it shows in the intellisense and it has no red lines under. I have the the runttime 3.0 

**Versions:**

 - AL Language: 

 - Business Central:

**Comment by qutreson** [comment]
Hi @jhanvillasin, it seems that your local symbol cache that is being used by VS Code  (see in your VS Code settings, "al.packageCachePath", or by default ".alpackages" at the root of your extension) is not in sync with the symbols on the server that you are targeting. Please try to clear it and to re-download symbols from your server.

Also, if that does not fix your issue, please state the version of the AL extension and of Business Central that you are using as required in our template for Github issues.

**Comment by jhanvillasin** [comment]
hello @qutreson  As walk through the settings. the package cache path is set to ./.alpackages. 
![image](https://user-images.githubusercontent.com/56950300/67462038-59cf3580-f671-11e9-8e81-394b850295f0.png)



Now, Its showing the red line under Purchase header and Purchase line.

**Comment by qutreson** [comment]
Now, you are working against the same reference symbols in VS Code than in your server, which is why you also have the error in VS Code now. It looks like the table does not exist in the reference symbols. Are you using C/SIDE and AL side-by-side? In that case did you follow all the steps as described here? https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side. 

This said, this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
