### ISSUE TITLE
Business Central Sandbox Publish problem

### ISSUE THREAD

**Issue by 48010** [microsoft/AL#5399]
When I publish an extension from Visual Studio Code to Sandbox enviroment I get no error but the extensions does not publish

Debugger Console does not shoot any error:
![image](https://user-images.githubusercontent.com/44604388/67687206-41745900-f998-11e9-9b0b-d32b4f85d92b.png)

VS Version: 1.39.2
AL Language: 4.0
Business Central: 14.0

**Comment by kalberes** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 
If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.
You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by ashikivor** [comment]
In the VS Code, View > Command Palette >  type : Clear Credentials. 
Restart VS Code and then try publishing again :)

**Comment by 48010** [comment]
Thank you ashikivor, I have cleared credentials several times.

**Comment by ashikivor** [comment]
Then, you should open reset your Sandbox environment and try publishing the package again. 

Go to Production > Search 'Sandbox' > Click on the reset button.

**Comment by 48010** [comment]
Thank you very much. 

But If I Reset Sandbox enviroment, will I lose the data introduced in that enviroment? Actually we have introduced many data such as configurations and data for trainings and we can not lose it.

**Comment by ashikivor** [comment]
I do not think there is any other option.
