### ISSUE TITLE
"Error AS0051: The property 'contextSensitiveHelpUrl' must be specified" cannot be suppressed by ruleSet

### ISSUE THREAD

**Issue by mivtf** [microsoft/AL#5440]
"Error AS0051: The property 'contextSensitiveHelpUrl' must be specified" cannot be suppressed by ignoreRuleSet.json. This makes it impossible to build for Release2.0 with current VSIX198182

**To Reproduce**
Build attached project with VSIX4.0.198182

**Expected behavior**
The error AS0051 was expected to be supressed, and expected to be able to build/deploy with no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/46669432/68603196-22052200-04a8-11ea-9805-a3e6f51af082.png)

**Versions:**
VSIX4.0.198182

[business-central-contextSensitiveHelpUrl -demo.zip](https://github.com/microsoft/AL/files/3832245/business-central-contextSensitiveHelpUrl.-demo.zip)

**Comment by atoader** [comment]
What happens if you rename your ruleset file to "ignore.ruleset.json" ? The ".ruleset.json" extension is the one supported by the compiler.

**Comment by atoader** [comment]
[business-central-contextSensitiveHelpUrl -demo.zip](https://github.com/microsoft/AL/files/3832504/business-central-contextSensitiveHelpUrl.-demo.zip)
I've updated the sample and it works for me.

**Comment by mivtf** [comment]
@atoader
Thank you for your feedback. I did some additional testing using the modified project you provided, and got things working. You can close this issue, thank you.

However, renaming the ruleset file was not what solved the issue -- adding the missing "al.ruleSetPath" to settings.json is what did the trick. The naming of the ruleSet file could be anything as long as this setting was added.  Conversely, naming the ruleSet file "ignore.ruleset.json" without adding the "al.ruleSetPath" did not work.

Very(!) strangely *some* rules works with the "old" (and accordingly to you incorrect) filename AND without the "al.ruleSetPath" being set. For example "AA0139: Possible overflow" can be supressed this way. Other (newer?) rules requires the "al.ruleSetPath" to be set.

**Comment by atoader** [comment]
The "al.ruleSetPath" setting is documented in the following docs:
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool-with-rule-set
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

Naming the file "*.ruleset.json" will enable intellisense and snippets so that you don't have to guess the syntax.
You are right. It is quite strange that some diagnostics disappeared even with the incorrect ruleset path.
