### ISSUE TITLE
Text type does not accept method invocations on constants

### ISSUE THREAD

**Issue by vjekob** [Microsoft/AL#547]
Invoking text methods only works on variables, not on text constants or literals.

Here's an example:

    local procedure DoesNotWork();
    var
        b: Boolean;
    begin
        // Invoking on a literal/constant, fails
        // Could be by design
        b := 'test'.Contains('e');
    end;

    local procedure ThisDoesntWorkEither();
    var
        b: Boolean;
        c: TextConst ENU='Test';
    begin
        // Invoking on a constant, fails
        // This should work
        b := c.Contains('e');
    end;

    local procedure Works();
    var
        t: Text;
        b: Boolean;
    begin
        t := 'test';
        // Of course this works :)
        b := t.Contains('e');
    end;

Is this by design? In many languages this is allowed (C#, JavaScript, ...)

My stance is:

- Invoking on a literal (e.g. 'test'.Contains) may be by design, and maybe is not really necessary, even though it can be very useful (e.g. 'SomeConstantOfWhateverMeaning'.Contains(SomeParameter))
- Invoking on a declared text constant should by all means work. Text constants should be fully of type text

**Comment by StanislawStempin** [comment]
We scoped out support for calling methods on text literals due to low value of this feature. If there is high need for it we will consider it for future backlog.

Regarding support for TextConst - it is a Multilanguage property and AL is no longer locale specific. The behavior of t.Contains('e') would either have to be fixed to work on the first language specified in the TextConst or to provide developer and API for selecting the language. We are in favor of treating TextConst as a display-only text which should not be operated on in AL code (other than replacing placeholders) but we are open to feedback on that topic.
