### ISSUE TITLE
Initialization of Secret Names failed.

### ISSUE THREAD

**Issue by brooksca** [microsoft/AL#5470]
**Describe the bug**
I named a procedure "ClearAll" on a page object that hid the native ClearAll procedure. The only error that I got was during runtime and said: "Initialization of Secret Names failed", however, the error was transient. Granted, naming a procedure this was not a great idea in the first place, however, a more intelligible error message would have saved me several hours.

**To Reproduce**
Steps and to reproduce the behavior:
1. Name a procedure using one of the reserved AL words: https://docs.microsoft.com/en-us/dynamics-nav/c-al-reserved-words. 
2. Run.

``` 
procedure ClearAll() begin
...
end; 
```

**Expected behavior**
For a syntax related error, I would have expected the compiler to raise an error instead of not seeing an error until runtime. Also, the error message could be more concise by using clearer wording rather than "Secret Names" and including the keyword that has been used in err would also be greatly helpful. An error message such as, "An object has been named using a reserved AL keyword. Please use a different name. Object: "ClearAll()".".

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2266064/69094377-3c964880-0a1e-11ea-9646-6857aa2996c7.png)

**5. Versions:**
 - AL Language: 4.0.176004
 - Business Central: Platform 15.0.36510.0 + Application 15.0.36560.0

**Comment by atoader** [comment]
Hi! I think you summed up very well what happened. Your procedure hid the built-in one and whenever you called ClearAll, you were calling your method instead of the built-in one. We cannot emit an error whenever this happens because it would mean that:
a) Code that already has methods that hide built-in methods would stop compiling
b) We could not introduce a new built-in method without potentially breaking existing code.

At the moment, the behavior you experienced is the intended one, but we will consider whether we can emit warnings or build a static analysis rules that warns about this.

**Comment by atoader** [comment]
As a side note, I could not find that error message anywhere in our code base.

**Comment by atoader** [comment]
Could you please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. It will help us prioritize this improvement against other features suggested for the product.

**Comment by AbsolutelyFreeWeb** [comment]
The customer statement report 1316 gives the same exact error message (at least in BC15)

**Comment by atoader** [comment]
As far as i can understand from the provided information, this issue is not related to the development tools.
