### ISSUE TITLE
Txt2AL Error

### ISSUE THREAD

**Issue by lloydb-insys** [microsoft/AL#5488]
I'm upgrading from BC Spring 2019 (version 14) to Wave 2 (version 15). I'm working through the steps in the "Code Conversion from C/AL to AL" here:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/devenv-code-conversion

When i get to **Task 5: Convert the C/AL TXT files to AL** 
I run txt2al:
"txt2al --source=C:\export2al\baseapplication --target=C:\export2al\baseapplication\al --injectDotNetAddIns --dotNetAddInsPackage=C:\export2al\dotnet\mydotnet.al --dotNetTypePrefix=BC"

It runs for a while and then I get this error:
![image](https://user-images.githubusercontent.com/58181091/69554047-cd14e180-0f66-11ea-8b81-dd699b4e109b.png)

Anybody know how to get past this?

**Comment by atoader** [comment]
Hi! What version of Txt2Al are you using?

**Comment by lloydb-insys** [comment]
14.0.3457.0

**Comment by lloydb-insys** [comment]
I figured out it's the multi-language captions in the objects. I had to use the Remove-NAVApplicationObjectLanguage cmdlet to get past this error.

**Comment by atoader** [comment]
Can you provide a sample to reproduce the issue?

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by SteveKrisjanovsD365** [comment]
I just experienced this too. The culprit is the menusuites (BC13.2 onprem). 

MEN1053.TXT, MEN1061.TXT, and MEN1080.TXT all have hex code x14 in our BC13 database.

Personally I think this issue should be reopened:

* txt2al doesn't have a -verbose switch to identify which .TXT file it can't convert when it fails(I had to use notepad++ to hunt it down)
* why did Export-NAVApplicationObject export a file with bad data?
* why is txt2al.exe even processing menusuite objects?
