### ISSUE TITLE
mandatoryAffixes in AppSourceCop seems to be checking Obsolete fields also

### ISSUE THREAD

**Issue by pmohanakrishna** [microsoft/AL#5510]
**Describe the bug**
mandatoryAffixes in AppSourceCop seems to be checking Obsolete fields also

**To Reproduce**
Steps and to reproduce the behavior:

``` AL Code to reproduce the issue ```
Create field without affixes set in mandatoryAffixes in AppSourceCop.
make the field Obsolete = removed

error AS0011: The identifier 'Gen. Prod. Posting Group' must have at least one of the mandatory affixes 'BUG'.

**Expected behavior**
Compiler should exclude obsoleted fields and objects

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.194000

 - Business Central: (Platform 15.0.37865.38374 + Application 15.1.37881.38420

**Comment by PooyaKharamesh** [comment]
Thank you for reporting this issue. This is a problem that we are aware of and the fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 38136 and VS Code Extension Version 5.0.200428.
If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo
For more details on code branches and docker images please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
