### ISSUE TITLE
Need to support DEBUGGER.ENABLESQLTRACE method

### ISSUE THREAD

**Issue by Rama-M** [microsoft/AL#5537]
In AL Language need to support DEBUGGER.ENABLESQLTRACE to read the SQL Tracing setting and to set the SQL Tracing as in C/AL code.  This is a very important debugging command to expose the application user to SQL Environment.  At lease this should be enabled for on-Prem environment.

See attachment for more detail of the error we get.

**Comment by atoader** [comment]
Hi! The attachment you mentioned is missing. I am not sure I understand the problem you are facing. Could you clarify?

**Comment by Rama-M** [comment]
Hi Alex,

My request is to support DEBUGGER.ENABLESQLTRACE method in AL code.

I have to say a lot of things are missing compared to C/AL. Other notable missing show stopper features are not able to create new index on standard table against standard fields, not able to create new SIFT on standard table on fields leading our NAV business almost stop selling BC wave 2 update. Please fix it. For goodness sake.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by atoader** [comment]
I checked and the method is available in AL. Did you mean that you want it to be enabled for Cloud development? If yes, we will evaluate if it is safe to expose this method or if there are alternatives. Have you considered using the SQL tracing available in the debugger window?

For the other show stopper features, the only way you could achieve those in C/AL was by performing a code customization, that is still possible. If you are referring to the ability of adding new indexes via table extensions, please vote it up on BCIdeas so that it gets put in scope for the next release.

As stated on the first page of this repository, its main purpose is to track issues regarding the AL compiler and the Developer Tools for the latest developer preview environment for Dynamics 365 Business Central.

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
