### ISSUE TITLE
How do I use ISNULL?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#554]
What is the new way to use ISNULL?

```
IF ISNULL(XMLAttribute) THEN
  EXIT(FALSE);
```

**Comment by atoader** [comment]
There shouldn't be a need to use ISNULL. ISNULL only makes sense when doing .NET interop because some methods might return NULL to mean that the result is non-existent.
For the new, AL-native XML types, all the methods follow the standard AL method for reporting errors/failure to return a result. 
For example:
SelectSingleNode('path_to_node', resultNode)

will return false if the method does not find anything. If you check the return value, there is no point in checking if the resultNode is null.
