### ISSUE TITLE
Extension for Security Filtering Business Central 14 

### ISSUE THREAD

**Issue by pearljo** [microsoft/AL#5564]
**Describe the bug**
When I use security filter in field "Code" in table "No. Series", I get error "A security filter has been applied to table No. Series. You cannot access records that are outside that filter" when create new Sales Order. 

I debug and it break on code below in function "CheckNumberSeries" (codeunit 1400) :
IF RecVariant.ISRECORD AND (NoSeriesCode <> '') AND NoSeries.GET(NoSeriesCode) THEN BEGIN

In NAV, I will add code like below.
NoSeries.SecurityFiltering := SecurityFilter::Ignored; //my additional code
IF RecVariant.ISRECORD AND (NoSeriesCode <> '') AND NoSeries.GET(NoSeriesCode) THEN BEGIN
..

How to do this using extension with AL Code in Business Central?
In extension, I cannot add code 
Please help. 
Thank you.

**To Reproduce**
Steps and to reproduce the behavior:
1. Go to Permission
2. In table No. Series, add security filter on field "Code" (for example : 101-A..101-Z)
3. Create No. Series Code (for example : 100-SO, 101-SO, 102-SO)
3. Create new Sales Order (error "A security filter has been applied to table No. Series. You cannot access records that are outside that filter")

``` AL Code to reproduce the issue ```

**Expected behavior**
I can create new Sales Order without any error.

**Screenshots**

**5. Versions:**

 - AL Language: 4.0.209944

 - Business Central: 14.0.36457

**Comment by atoader** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
