### ISSUE TITLE
Length of the table key name must not exceed 28 characters. Longer key names are prone to cause SQL errors. This warning will become an error in a future release.

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/AL#5635]
Hi,
I have an extension with this warning, hen I upload the PTE Extension on the Business Central on the cloud (Sandbox).

This key have the ObsoleteState = Removed, but the extension management show already this warning.

Will I have some problem in future ?

Version: IT Business Central 15.2 (Platform 15.0.39461.40328 + Application 15.2.39060.0)

Thank you,
Roberto.

**Comment by atoader** [comment]
Hi! You might have problems if your users use a very long company name.

You are getting this warning because keys are still created although they are marked as ObsoleteState = Removed. We have it on our backlog to allow removing obsolete schema elements completely, but I cannot provide an ETA at this point in time.

**Comment by atoader** [comment]
I am closing this issue because it appears that it has been resolved. Please open a new issue if you believe this has not been resolved and reference the current issue.
