### ISSUE TITLE
The type or method xxx cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/AL#564]
we need below functions.

Codeunit 8611 - InsertPackageField, ApplyPackage, RecordError

Codeunit 419 - UploadFile (or any alternative?)

table 1234 - LoadData

system - error handling - CLEARLASTERROR?

**Comment by dkorinets** [comment]
Also have similar issues:

The type or method 'Object' cannot be used for 'Extension' development.

**Comment by pmohanakrishna** [comment]
Please add these also
Codeunit 1004 - FromPurchaseLineToJnlLine
Tab 36 - IsApprovedForPostingBatch
Codeunit 1535 : PrePostApprovalCheckPurch

**Comment by StanislawStempin** [comment]
Reply to the first post:
Codeunit 8611 - see RapidStart issue #211 
Codeunit 419 - we cannot enable UploadFile, see if you can use UploadFromStream
Table 1234 - LoadData - this function is not safe since it allows reading from server filesystem
ClearLastError will be available in September Update

Second post:
See #519

Third post:
Accepted for making External

**Comment by dkorinets** [comment]
Our scenario assumed to get(rear) info (Name fields\Captions fields\Types fields\ Relation table inf ) from Objects table. 
Advice please how we can solve it in SaaS scenario?

**Comment by dkorinets** [comment]
The procedures is required for our extension:
local) SalesPost : Codeunit "Sales-Post"
[AL] The type or method 'GetSalesLines' cannot be used for 'Extension' development.
[AL] The type or method 'SumSalesLinesTemp' cannot be used for 'Extension' development.

SalesPriceCalcMgt : Codeunit "Sales Price Calc. Mgt."
[AL] The type or method 'FindSalesLinePrice' cannot be used for 'Extension' development.

SalesCalcDiscount : Codeunit "Sales-Calc. Discount"
[AL] The type or method 'CalculateWithSalesHeader' cannot be used for 'Extension' development.

SalesPostPrepmt : Codeunit "Sales-Post Prepayments"
[AL] The type or method 'SumPrepmt' cannot be used for 'Extension' development.

CustInvDisc : Record "Cust. Invoice Disc."
[AL] The type or method 'GetRec' cannot be used for 'Extension' development.

CopyDocMgt : Codeunit "Copy Document Mgt."
[AL] The type or method 'CopySalesInvLinesToDoc' cannot be used for 'Extension' development.

BusChartBuf : Record "Business Chart Buffer"
[AL] The type or method 'GetXValueAsDate' cannot be used for 'Extension' development.

BusChartBuf : Record "Business Chart Buffer"
[AL] The type or method 'AddMeasure' cannot be used for 'Extension' development.
[AL] The type or method 'AddPeriods' cannot be used for 'Extension' development.
[AL] The type or method 'SetValueByIndex' cannot be used for 'Extension' development.

HttpWebRequestMgtGlobal : Codeunit "Http Web Request Mgt."
[AL] The type or method 'Initialize' cannot be used for 'Extension' development.
[AL] The type or method 'SetMethod' cannot be used for 'Extension' development.
[AL] The type or method 'AddHeader' cannot be used for 'Extension' development.

**Comment by AmolSalvi** [comment]
Hello
Kindly expose the functions from File Management and Config Package Management as it is used for assisted setups creation.

Amol

**Comment by StanislawStempin** [comment]
@AmolSalvi - these two areas need redesign and are tracked by other existing issues.

The following functions will be unblocked:
Codeunit 1004 - FromPurchaseLineToJnlLine
Tab 36 - IsApprovedForPostingBatch
Codeunit 1535 : PrePostApprovalCheckPurch

In general please log separate issues instead of adding comments to an existing issue because we might be in the process of addressing the original request and miss any things added in the meanwhile.

**Comment by AmolSalvi** [comment]
@StanislawStempin  Thank you .Will create new thread for the same.
