### ISSUE TITLE
Run code analysis in the Azure DevOps Pull Request

### ISSUE THREAD

**Issue by Lazys** [microsoft/AL#5667]
Hi,
it would be great if I could run code analysis (using the same tools which are in the VS Code - CodeCop etc.) for the AL in the azure dev ops pull request.

Sth similar to the SonarQube (https://www.sonarqube.org/azure-devops-integration/?gclid=CjwKCAiAp5nyBRABEiwApTwjXui4QujPbU0ppwJM5OramFWkD3tGhDw56CuNwhCPH32I_GKOt38fnhoCZ9kQAvD_BwE).

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.52365.0 and VS Code Extension Version 11.0.741964. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by Lazys** [comment]
Any tips how your fix corresponds to the my suggestion? What problem exactly it resolves and how I can use this to achieve goal - run code cops in the Azure DevOps Pull Request? I'm quite newbe in this area.

**Comment by nndobrev** [comment]
@Lazys 

You can add a powershell script to your pipeline definition where to call to alc.exe with `/analyzer:` argument. It should be something like this:

`alc.exe /packagecachepath:"C:\Temp\.alpackages" /project:"C:\Temp\" /out:"C:\Temp\testPackage.app" /fullpaths /analyzer:"C:\Users\[your username]\.vscode\extensions\ms-dynamics-smb.al-6.1.359074\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll","C:\Users\[your username]\.vscode\extensions\ms-dynamics-smb.al-6.1.359074\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll","C:\Users\[your username]\.vscode\extensions\ms-dynamics-smb.al-6.1.359074\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll"`

As you can see `/analyzer:` argument accepts a string of paths to the different dlls of the analyzers of choice separated by comma.

**Comment by Lazys** [comment]
@nndobrev thanks.
