### ISSUE TITLE
Filter page using fields of other tables

### ISSUE THREAD

**Issue by AlvaroMig** [microsoft/AL#5685]
Is there any option to filter a page list using a field or data from another table? For example, can I do something to get items with a specific work center in the routing?

**Comment by nicolassaleron** [comment]
Hello,
You cannot do that in the client.

By developping an extension, you can do this with queries (and then expose query result in a page) or by overloading the [OnFindRecord and OnNextRecord](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-page-and-action-triggers) triggers on page. Please note this last capability can lead to very bad performances.

**Comment by AlvaroMig** [comment]
> Hello,
> You cannot do that in the client.
> 
> By developping an extension, you can do this with queries (and then expose query result in a page) or by overloading the [OnFindRecord and OnNextRecord](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-page-and-action-triggers) triggers on page. Please note this last capability can lead to very bad performances.

Thanks, I will do a query to get it if there is no option to do this in filters.

**Comment by qutreson** [comment]
Closing as this issue seems to have been answered. Please note that this repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
