### ISSUE TITLE
Provide warning on flowfield assignments

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5702]
**Title**
Provide warning on flowfield assignment

**Description**
Often it is not clear if a field is a flowfield or a normal field. When coding, developers might (wrongfully) assign a value to a flowfield, which is not supported (in 99% of the cases, except for the old C/AL hack to update the inventory entries when updating the item inventory flowfield > not sure if this is still supported)

**Reason for the rule**
Developers are often wrongfully assigning values to fields and expect the field to contain the value, although the field is a flowfield, thus not containing the value assigned. They make wrong expectations about the field not being a normal field and only find out later via debugging the field is a flowfield.

**Bad code sample**
Customer Name > fieldclass "Flowfield"
"Customer Name" := 'value';

**Good code sample**
Customer Name > fieldclass "Flowfield"
// "Customer Name" := 'value'; // Not supported

**Good and bad practices for fixing the rule**
Good practice : Remove the flowfield assignment

**Comment by EmilDamsbo** [comment]
Assigning to a flowfield on a record is sometimes a conscious choice, because the value assigned to the flowfield is persisted as part of the record in memory, but will not be committed to memory. We tried to introduce this warning internally, but it was not well-received so we are not planning to generate a warning for flowfield assignment.
