### ISSUE TITLE
Processing of message 'textDocument/hover' failed with error: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by yannstlo** [microsoft/AL#5759]
**Describe the bug**
Debugger stops working... it hangs

**To Reproduce**
Steps and to reproduce the behavior:
I'm running Business Central v13 and AL Language 2.1.106653
I put a stop in my code and when the stop hits, if I press F11 to step to next line, the debugger stops working and the page I was working on shows "Working on it..." 

``` AL Code to reproduce the issue ```

**Expected behavior**
regular debugging

**Screenshots**

**5. Versions:**

 - AL Language: 2.1.106653

 - Business Central: US Dynamics NAV 13.0 (24630)

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
