### ISSUE TITLE
dotnet issues onPrem since update to AL .5.0.254558

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/AL#5761]
**Describe the bug**
Working code with AL extensions 4.0. does no longer work with AL extension 5.0.
Code in question. dotnet assembly definition and usage.

**To Reproduce**
Steps and to reproduce the behavior:
1. use mentioned AL extensions . AL:Go - Version 4.0 
2. change your setting to use the probingpath 
`    "al.assemblyProbingPaths": [
        "./.netpackages",
        "c:/windows/assembly/"
    ]`
3. add a dotnet object with the following content:

```
dotnet
{
    assembly("System")
    {
        Version = '4.0.0.0';
        Culture = 'neutral';
        PublicKeyToken = 'b77a5c561934e089';

        // will not work
        type("System.Collections.Queue"; "Queue") { }
        type("System.Convert"; "SystemConvert") { }

        // will work
        type("System.Security.Cryptography.X509Certificates.StoreName"; "StoreName") { }

    }
}
```

**Expected behavior**
The System is able to find the assemblies and use them.

**5. Versions:**

 - AL Language: 5.0.254558

**Comment by atoader** [comment]
Hi! There are a few things at play here:
1. System.Collections.Queue is not in the System assembly https://docs.microsoft.com/en-us/dotnet/api/system.collections.queue?view=netframework-4.8
2. It used to work in older versions of the VSIX due to a but in the .NET Interop system implementation when the compiler was running on the .NET Framework
3. The bug might still be there if you "al.useLegacyRuntime":true and restart your enlistment. If that works, keep in mind that the legacy runtime is about 2-3 times slower than the new one.

Considering that the assembly is not part of System, at least not according to the public docs, I would recommend fixing the code.

**Comment by KristofKlein** [comment]
That's interesting! so you moved away from the old .Net framework? Isn't that worth to mention somewhere?! :D 
Apart from that: it was just an example on the things we have problems with. the list is a bit longer... i will check those if they are also not (any)longer part of the assembly we used to use.

I have tested with "al.useLegacyRuntime":true - this "fixes" all the errors we got! Time to do some homework (literally). Thanks for the quick answer! 
Will this introduce some compatibility problems with using al 5.0 against newer BCs (v.16) v5 apps vs older BC (v3, v4 ?) or is it just for VS Code? So when the App gets published - v15 was happy to compile and run it - will v16 now fail as it will not be able to handle the assemblies? do I need to set BC v16 also in "legacy" mode?

**Comment by KristofKlein** [comment]
booomer  - I was to fast - it did not help :/

all those do not work:
`
        type("System.Collections.Queue"; "Queue") { }
        type("System.Convert"; "SystemConvert") { }
        type("System.DateTime"; "SystemDateTime") { }
        type("System.Environment"; "Environment") { }
        type("System.Text.UTF8Encoding"; "UTF8Encoding") { }
        type("System.AppDomain"; "AppDomain") { }
        type("System.Net.ICredentials"; "ICredentials") { }
        type("System.Reflection.Assembly"; "Assembly") { }
        type("System.Object"; "Object") { }
        type("System.Collections.Generic.IList`1"; "IList_Of_T") { }
        type("System.Collections.Generic.ICollection`1"; "ICollection_Of_T") { }
        type("System.Nullable`1"; "Nullable_Of_T") { }
        type("System.Collections.Generic.List`1"; "List_of_T") { }
        type("System.Collections.Generic.Dictionary`2"; "Dictionary_Of_T_U") { }
        type("System.Collections.Generic.IEnumerable`1"; "IEnumerable_Of_T") { }
        type("System.Collections.Generic.KeyValuePair`2"; "KeyValuePair_Of_T_U") { }
`

**Comment by KristofKlein** [comment]
Moving them to the assembly mscorlib helped! (while legacy is enabled...) 

turning it off seems also to work but no I get "ambiguous" references. Wasn't that allowed in the past to have the same reference and name...so this is no longer ok it seems ...

**Comment by atoader** [comment]
What do you mean by ambiguous reference?

**Comment by KristofKlein** [comment]
like this guy here:
 type("System.Environment"; "Environment") { }  that is in our extensions dotnet.al but it is also part of SystemApplications dotnet.al ...

**Comment by atoader** [comment]
Hi Kristof! Coming back after a long vacation: can you provide a self-contained project that we can use to reproduce this problem? Maybe there's something else on top of the transition from .NET Framework to .NET Core.

**Comment by KristofKlein** [comment]
Hi Alex,

i will try and let you know.

**Comment by JeremyVyska** [comment]
In case anyone else like me ends up here and is super confused at what the resolution is, you have to know what parts are for what assemblies.

For example, if you are using OnPrem and DotNet to generate files, and your older code has a batch of types like:

    assembly(System)
    {
        type(System.IO.File; FTPFileStream) { }
        type(System.IO.FileStream; RealFileStream) { }
        type(System.Text.Encoding; dotEncoding) { }
    }

Then those, despite the name, don't go under the `assembly(System)`.  You would instead reference them like `assembly(mscorlib)`.

This can be a little challenging for a novice to sort out, since Microsoft's site on System.IO says the assembly is "System.Runtime" (which does not work here) but almost every 3rd party reference site gives more clarity as to the proper 'assembly' name.

Your dotnet wrapper can have multiple assembly nodes, so a wrapper like this is perfectly valid:

    dotnet
    {
        assembly(System)
        {
            type(System.Net.FtpWebRequest; FTPRequest) { }
            type(System.Net.FtpWebResponse; FTPResponse) { }
            type(System.Net.NetworkCredential; Credentials) { }
            type(System.Net.FtpStatusCode; StatusCode) { }
            type(System.Text.RegularExpressions.Regex; dotRegex) { }
        }
        assembly(mscorlib)
        {
            type(System.IO.Stream; ResponseStream) { }
            type(System.IO.StreamWriter; dotStreamWriter) { }
            type(System.IO.File; FTPFileStream) { }
            type(System.IO.FileStream; RealFileStream) { }
            type(System.Text.Encoding; dotEncoding) { }
            type(System.Collections.ArrayList; FilesList) { }
        }
    }
