### ISSUE TITLE
LineStart still an issue in 14CU10

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/AL#5780]
See issues #3947, #4460, #4914 
This is still NOT fixed. It has been 17 months said you fixed it.  When will we get the fix?  It certainly hasn't been made available in the recent builds.

**Comment by KristofKlein** [comment]
I can confirm that. it is NOT fixed.

**Comment by qutreson** [comment]
@GreatScott000 @KristofKlein can you post here the txt files that you are using in order to reproduce this issue?

If you are seeing it in page extensions or table extensions objects, as mentioned in #4460, the fix was done in the Compare-NavApplicationObject command. Your delta files should then already not have modifications reported on the LineStart attribute. If they still have it, can you try to regenerate them before running the txt2al and tell me whether that fixes your issue?

**Comment by qutreson** [comment]
Looking back at the sample provided on #4460, it looks like the LineStart attribute is preserved when the method also has another attribute set (like external/internal or integration)

**Comment by JuricaB** [comment]
@qutreson Microsoft.Dynamics.Nav.Model.Tools, of which Compare-NAVApplicationObject is a member, have not been available in Dynamics 365 BC since 14.x. This was (if I am not mistaken) using commands available in finsql.exe, which no longer ships with BC. Can you please explain how we should be using it on 15.x - I may have missed something?

**Comment by qutreson** [comment]
I have backported the fix to 14.x, so it should be available with the next CU.
