### ISSUE TITLE
CodeCop Rule: AL0432 Action 'ApplyTemplate' is marked for removal. Reason: This functionality will be replaced by other templates.. Tag: 16.0.AL(AL0432)

### ISSUE THREAD

**Issue by RoieSantos** [microsoft/AL#5799]
**Describe the bug**
We are currently updating our extension to BC16 in the ${CodeCop} declared under code analyzer it is showing multiple warnings. Below is one "AL0432 Action 'ApplyTemplate' is marked for removal. Reason: This functionality will be replaced by other templates

**To Reproduce**
1. AL Language extension is installed (5.0.254558)
2. Create a page extension of standard page "Vendor Card" (26)
3. Modify the existing action "Apply Template"
4. A warning says "Action Apply Template is marked for removal will appear."

Screenshots
![image](https://user-images.githubusercontent.com/63336107/79084816-3f9d2700-7d79-11ea-84de-3d982909ade9.png)
also a same warning shown on modifying page 21 (part) "PriceAndLineDisc"
![image](https://user-images.githubusercontent.com/63336107/79084864-8c80fd80-7d79-11ea-9f8b-cf9b15e98701.png)

**Versions:**
AL Language 5.0.254558
Business Central : 16.0.11209.0 (Preview)

**Comment by qutreson** [comment]
Hi @RoieSantos, the warning AL0432 is a compiler diagnostic and is not reported by CodeCop.  You can see it because the diagnostic starts with AL**** and not with AA****. This diagnostic means that the extension publishing the elements that you are modifying have marked those for removal, meaning that they will be removed in a later version of the extension. This warning is then informing you about future changes so that you can update your extension before elements actually get removed. There does not seem to be any issue here.

**Comment by dyepri** [comment]
Just got here to report the same issue for Sales Price table.
