### ISSUE TITLE
 AS0004: changing the enum in table fields

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#5818]
**Title**
We cannot change a field from one Enum to another, even if changing a field from Option to Enum is possible.

**Description**
This problem comes from the fact that we have several enums in our apps that did not exist in BC 15. Now BC 16 has new standard enums that match ours.
I think there is no reason to prevent from moving field type from Enum A to Enum B. It does not cause database schema modificationand if a mapping is required during the upgrade, this is the responsability of the app maker.

This example illustrates the problem:
In V15:

```
table 50000 "My Sales  Package"
{
   fields
   {
      //...
      field(1; "Document Type"; Enum "My Sales Document Type") { }
      field(2; "Document No."; Code[20]) { }
      field(3; "Package No."; Code[20]) { }
      //...
   }
}
```

In V16 :
```
table 50000 "My Sales  Package"
{
   fields
   {
      //...
      field(1; "Document Type"; Enum "Sales Document Type") { } //This causes an error regarding AS0004
      field(2; "Document No."; Code[20]) { }
      field(3; "Package No."; Code[20]) { }
      //...
   }
}
```

The con of this rule is: if it is kept like this and we want to align apps with standard enums in the future, we will not only have to deprecate field but also tables if the field is part of the key.

**Reason for the rule**
./.

**Bad code sample**
./.

**Good code sample**
./.

**Good and bad practices for fixing the rule**
A good thing would be to warn the developer if the enum has been changed, but should not be a blocking error.

**Remarks**
./.

**Comment by qutreson** [comment]
Hi @nicolassaleron, the reason for not allowing conversions from one Enum to another is that it can break dependent extensions.

For instance, let's imagine that you have an extension that looks like this one:
```
table 50100 MyTable
{
    fields
    {
        field(1; MyField; Enum OriginalEnum) { }
    }
}

enum 50100 OriginalEnum
{
    value(0; MyValue) { }
}
```

And another extension takes a dependency on your extension to define this code:
```
codeunit 50100 MyCodeunit
{
    procedure MyProcedure()
    var
        r: Record MyTable;
    begin
        r.MyField := Enum::OriginalEnum::MyValue;
    end;
}
```

If in the next version of your extension, you change the definition of `MyField` to be `field(1; MyField; Enum NewEnum) { }`, then the depending extension will have a compilation error: `Cannot implicitly convert type 'Enum OriginalEnum' to 'Enum NewEnum' (AL0122)`.

Now, if the table is marked as Internal, we should allow this kind of changes.

We will keep this issue open to collect additional feedback about this kind of scenario as for now the only solution would be to deprecated the field (and in some cases the table, if it is part of the key), implement upgrade logic, etc, which can be an expensive task.

**Comment by nicolassaleron** [comment]
Ok, get it and it makes sense, even if I would prefer to let the ISVs communicate with customers or VARs about that kind of change.

About that, how can we know which AppSourceCop rule is really enabled for App Source validation?

I have the feeling that [all rules](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop) (even if they are marked as Error by default) are not blocking. This is for example the case, I think, for AS0031: and I am pretty glad this is not enforced for now :)

**Comment by qutreson** [comment]
We are now validating against all the rules which have their Default Severity set to Error in the documentation that you mentioned. Not sure why AS0031 was not validated in your case...

**Comment by nicolassaleron** [comment]
Preventing extending a field size is now forbidden too?

```
error AS0004: Field 'Table Caption' has changed type from 'Text[30]' to 'Text[249]'. Type changes are not allowed.
```

**Comment by nicolassaleron** [comment]
> Hi @nicolassaleron, the reason for not allowing conversions from one Enum to another is that it can break dependent extensions.
> 
> For instance, let's imagine that you have an extension that looks like this one:
> 
> ```
> table 50100 MyTable
> {
>     fields
>     {
>         field(1; MyField; Enum OriginalEnum) { }
>     }
> }
> 
> enum 50100 OriginalEnum
> {
>     value(0; MyValue) { }
> }
> ```
> 
> And another extension takes a dependency on your extension to define this code:
> 
> ```
> codeunit 50100 MyCodeunit
> {
>     procedure MyProcedure()
>     var
>         r: Record MyTable;
>     begin
>         r.MyField := Enum::OriginalEnum::MyValue;
>     end;
> }
> ```
> 
> If in the next version of your extension, you change the definition of `MyField` to be `field(1; MyField; Enum NewEnum) { }`, then the depending extension will have a compilation error: `Cannot implicitly convert type 'Enum OriginalEnum' to 'Enum NewEnum' (AL0122)`.
> 
> Now, if the table is marked as Internal, we should allow this kind of changes.
> 
> We will keep this issue open to collect additional feedback about this kind of scenario as for now the only solution would be to deprecated the field (and in some cases the table, if it is part of the key), implement upgrade logic, etc, which can be an expensive task.

The idea is good but the reality is different.

Let me expose the following example (completely different from the original subject but it illustrates my point):

* In BC15, we have the Report 730 "Copy Item" that raises the event OnAfterCopyItem.
* In BC16, Report 730 "Copy Item" is marked as ObsoleteState = Pending because it is replaced by Page 729 "Copy Item" (+ Codeunit 730 "Copy Item" and the event OnAfterCopyItem).

The idea is perfect, the report is still there and a new page is smoothly replacing it. So the code upgrade is running nicely and you think the customer is happy.

The reality is a bit different.

Actually, the report Copy Item is no more available in the UI by default, already replaced by the page Copy Item.
The consequence is that the event Report::"Copy Item"::OnAfterCopyItem is never called because there no relay to this event in Codeunit::"Copy Item"::OnAfterCopyItem for backwards compatibility.

So the upgrade goes smoothly but the breaking change has been sneakly introduced.
I would have prefer a compilation error.

You can argue that this is a mistake and it should have been handled differently. I am afraid that developers will prefer to introduce sneaky breaking changes than handling the backwards compatibility.
And for that, there is no way to do a static code analysis.

**Comment by atoader** [comment]
You have a good point that static code analysis cannot find all types of breaking changes, but the purpose of these rules is to detect issues that would break dependencies on top from compiling, the rest, is left to the application developer.
Dmitry Chadayev posted this on Yammer with regards to breaking changes and the rationale for checking these for AppSource
<<<
Business Central online is a multi tenant service. Multiple tenant environments (tenant databases) are running against a single application database. Apps, both Microsoft and AppSource, are published into that application database and installed by the customers in their environments. 
When you make a new app version available - some customers uptake it sooner, some later ( https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-manage-apps ). So *both versions* of your app must be published in the same application database *side by side*. Same with all other app versions you upload between our major releases. If you’re making changes which cannot coexist with the previous versions of your app - your new app version cannot be published into our service and therefore it is rejected. We follow the same rules for the 1st party apps (it is really hard as our app is huge, but we make a huge effort to ensure that) - minor versions and hotfix versions of our apps must be backwards compatible. 

Hence you need to take care of the schema and other “public API” elements, which can be referenced by others, to make sure they can coexist with each other on the same service. For example, you need instead of removing or renaming, you need to mark the elements you want to change as obsolete (but keep them as they are) add new elements with the new properties and add upgrade code to move the data if needed. In Wave 1 2020 release we added ability to assign obsolete state to many different objects and elements ( https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-obsoletestate-property), not only schema elements, also we added an option to add obsolete tags for easier tracking of such changes (https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/dynamics365-business-central/obsolete-tag-url-properties ) 

When we ship a Major version of BC, we upgrade all our customers to the new nodes, running on the new application database, we are also pulling the latest (major) versions of AppSource apps into these nodes. In this case there are no “old” apps installed in our nodes and you get a chance to get rid of some of the changes you marked as obsolete in the minor versions and hotfixes. However at this point it is not yet possible to delete obsolete schema elements, like tables or fields, so they have to stay even in major versions, until that feature is available. 
Bottomline - backwards compatibility between different versions of our apps is extremely important in the online service. 
>>>

**Comment by atoader** [comment]
I will close this issue as we believe changing the rule to allow replacing enums would break consumers.
