### ISSUE TITLE
Functions with parameters of type List are not exposed in SOAP codeunit webservices

### ISSUE THREAD

**Issue by jhoek** [microsoft/AL#5825]
**Describe the bug**
When exposing a codeunit as a SOAP webservice, functions that have parameters of type List are not available to callers, without any form of warning.

**To Reproduce**
Steps and to reproduce the behavior:
1. In AL, create a codeunit with a function that has a parameter of type `List of [{SomePrimitiveDataType}]`. 
1. Publish and install the app. 
1. In the `Web Services` page, publish the codeunit from the earlier step.
1. Click the SOAP url and notice that your function is not present in the WSDL.

**Expected behavior**
This situation cannot be detected at compile time - the compiler is, of course, unaware that users may later publish the codeunit in question as a web service. The earliest point in time where the system could warn users is when they check the Publish checkbox in the Web Services page. Now that I think about it, however, web services can also (should!) be published using an xml file that is included in the app. What might work is a warning when the web service is installed by the platform. 

Otherwise, the only natural place to warn developers about this limitation might be in the AL documentation. 

**5. Versions:**

 - AL Language: 5.0.254558
 - Business Central: Version: Platform 14.0.38650.0 + Application 38658 (NL Business Central 14.8)

**Comment by bjarkihall** [comment]
Yeah, we've always been stuck with primitive data types like Text, Int, Decimal, Boolean and I think possibly Datetimes?

You can see the structure of the web services in the wsdl file for soap and edmx file for odata, the types assigned for the parameters are usually just string, int and boolean - you can create a custom EDM type for Odata (only on prem) but I haven't experimented with wsdl much.

What surprises me is that **Json Types**, XML types, List and Dictionary aren't supported, but how would you distinct between which one to use, e.g. between JsonObject and Dictionary and JsonArray and List?
Other complex types like Variants, arrays, InStream, Records, RecRefs, FieldRefs, Codeunits and specific BC functionality can't be exposed because, how would you even assign values to them?

I'd assume the most extendable and generic way for now would be to accept a Text and convert it in the web service function to e.g. a list before you'd pass it to your desired procedure.

If you have something simple you could do:
List -> string with a unique separator -> WebService -> List := arg.Split(separator)

Your variable can be formatted/encoded to Json or Xml (or even base64) string before calling the WS, which just acts as a proxy that decodes the Text and passes it on.

There are three ways of doing this I can think of right away in the WS procedures:
1. Use a single proxy for decoding and a case of to forward it to the correct procedure.
  Cons: Needs to manually add procedure names to cases.
2. Make all of your procedures accept Text only and use a utility converter function in the start of each of them.
  Cons: Your procedures can only accept primitive types as parameters and you must remember to convert the argument for each procedure.
3. Create two versions of each function, one for the WS which formats it and passes it on to the other which can accept complex types.
  Cons: You end up with two versions of each procedure which is repetative and possibly error-prone.

I don't think I've seen this documented though and I'd really like this feature to be extended, since plain string, number and boolean are quite limiting.

Here are relevant blog posts, even though they are both oriented towards odata:
https://www.kauffmann.nl/2020/03/05/codeunit-apis-in-business-central/
https://vjeko.com/2019/03/01/using-complex-types-with-custom-apis/

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
