### ISSUE TITLE
Member name 'OnAfterGetCurrRecord' is only allowed on triggers. This warning will become an error in a future release.

### ISSUE THREAD

**Issue by eque2al** [microsoft/AL#5831]
BC160 (16.0.0.0):

![image](https://user-images.githubusercontent.com/57717503/80114896-01bfb000-857c-11ea-8004-37231d13c0e1.png)

In the ApplyCustomerEntries.Page.al file the OnAfterGetCurrRecord trigger is used and triggers the warning detailed in the Subject line of this message.  We use a version of this page in our solution and are getting the same error .. can this be solved in standard product pls and the solution provided to us?

**Comment by thpeder** [comment]
Hi @eque2al,
The piece of code you are showing there I can't get to reproduce the warning, and even when I tried to compile the page you are referring to I still didn't get the warning.
The warning catches situations where a procedure is named the same as a trigger, but since this is a trigger it is fine.

Could you please provide the version of the VSCode language extension you are using
and a small project that reproduces the issue with the VSCode language extension from the marketplace.

Thanks,
Thomas

**Comment by eque2al** [comment]
Ah thanks for that explaination, I didn't realise but our 'copy' of your code was using a procedure named 'OnAfterGetCurrRecord' in a Page object .. I've renamed it and solved this so **thank you very much!!**
