### ISSUE TITLE
error during publish from VS CODE to Sandbox: the request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: ForceHandleTrackingEvent failed to acquire a lock

### ISSUE THREAD

**Issue by sami3187** [microsoft/AL#5844]
<img width="739" alt="e5" src="https://user-images.githubusercontent.com/64240684/80496396-bbaf8580-899b-11ea-90ac-b4acc035a7c5.PNG">

For NAV 2018 issues please contact regular support channels. 
This repo is dedicated only to the latest Business Central Developer Preview releases.

!!!Please, Please, Please!!! - Read the FAQ before posting:
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions
Many questions are already answered and it will save time both for you and for us.
-->

- AL Extension Version: 

- Server Version:

**Comment by atoader** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
