### ISSUE TITLE
AL0604 - warning AL0604:  Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'.

### ISSUE THREAD

**Issue by DBiernat** [microsoft/AL#5916]
**Describe the bug**
Warning AL0604 is displayed for TableRelations on a page field. For table field TableRelations no warning is displayed.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new docker container from "bcinsider.azurecr.io/bcsandbox-master"
2. Create a table and a page implementing a field table relation
3. Build the app

```
TableRelation = Table."No." where("No. Filter" = field("No."));
 ```

**Expected behavior**
No warning should be displayed or there must be a way to specify Rec for the filter.

```
Example: TableRelation = Table."No." where("No. Filter" = Rec."No.");
```

**Versions:**
 - AL Language: 6.0.277481
 - Business Central: Version: W1 17.0 (Platform 16.0.13337.0 + Application 17.0.13415.0)

**Comment by DavidFeldhoff** [comment]
I'm using the v6.0.297106 of the AL Extension and experienced that there's no warning anymore on a page field, but if I add the `#pragma implicitwith disable` to the page object, then there's an error on the TableRelation that (in this case the "No.") could not be found.
Example without pragma (everything's fine):
![image](https://user-images.githubusercontent.com/53570297/86885517-b25a3c00-c0f5-11ea-8bfb-3ab75bb274bf.png)

Example with pragma (two errors):
![image](https://user-images.githubusercontent.com/53570297/86885561-c9992980-c0f5-11ea-80f4-dabd0831d3f8.png)

**Comment by qutreson** [comment]
This issue has been fixed in our latest developer previews for AL extension with a version higher than 6.0.310192.

This scenario does not report a warning about the implicit with anymore:
![image](https://user-images.githubusercontent.com/31541422/92486267-2bf0d200-f1ec-11ea-8e63-d95067fb7230.png)

Disabling the implicit with with a pragma also does not trigger compiler errors anymore:
![image](https://user-images.githubusercontent.com/31541422/92486249-25faf100-f1ec-11ea-9f3f-29a3e3ed2abd.png)
