### ISSUE TITLE
Exclude objects from receiving auto-generated translations

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#5917]
**Describe the bug**
When working with the TranslationFile / GenerateCaptions features, AL extension adds trans-units for objects / fields with missing captions. We have lots of objects that don't require translations (temporary upgrade / buffer tables, argument tables, internal tables, ...) We'd like to be able to either tag the table / object with a new 'UseCaptions'  = No property to exclude the object from the translation updates / checks, either to have a 'ExcludeTranslations.json' file where we can list objects to be excluded.

**5. Versions:**

 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/83054095-21059d80-a052-11ea-9caa-3a21bbaa6f58.png)

**Comment by salgiza** [comment]
Wouldn't the Locked attribute do that?

    value(0; "")
    {
        Caption = '', Locked = true;
    }

That tags the xliff translation element with the translate="no" attribute, so that it is ignored by any translation tool that you might use (we use webtranslateit and it certainly excludes all elements with that attribute).

I mean, I know that it is not exactly what you are asking for, but we use it just for that (internal tables, things that don't require captions), and it has certainly solved that need for us.

**Comment by dtkb** [comment]
That should do it, but it looks like extremely tedious busywork/spam. :-P Excluding whole objects from translation would be far easier/tidier.

**Comment by salgiza** [comment]
@dtkb Hehehe, totally true! I just though I should mention the Locked option because I must admit we didn't found out about it until a few months ago 😅 (when we had a similar problem).

P.S. Inspired by your comment, but totally unrelated to this ticket, I've just posted this idea: https://experience.dynamics.com/ideas/idea/?ideaid=8121da28-99a1-ea11-8b71-0003ff68c1c1
