### ISSUE TITLE
Date filters in views are translated and won't work in other languages

### ISSUE THREAD

**Issue by MaxymeC** [microsoft/AL#5923]
**Describe the bug**
When I add a view to a page through a page customization, I want to set a date filter on e.g. "Posting Date"'s field. Works well, but when the users use another language (french in this case), filter dosen't work cause it does not recognize the day character for the filter.

**To Reproduce**
Steps and to reproduce the behavior:
1. Set the your tenant language to : French (Canada)
2. Open concerned view on the page customized.

``` AL Code to reproduce the issue ```

pagecustomization "Fin. Sales Order List" customizes "Sales Order List"
{
    views
    {
        addfirst
        {
            view("Batch Invoicing - Sales Orders")
            {
                Filters = where ("Posting Date" = filter ('..t-1d');
            }
        }
    }
}

**Expected behavior**
The view to work on at least both english and french.

**Screenshots**

**5. Versions:**
 - AL Language: 3.0.172401
 - Business Central: Platform 14.0.36457.0 + Application 35602 (US Business Central 14.4)

Any suggestions ?

**Comment by atoader** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
