### ISSUE TITLE
How to customize a form that contains fields from ChargeLogic Payments extension in Business Central 14 On Premise

### ISSUE THREAD

**Issue by tlbakken** [microsoft/AL#5927]
Hi,

I am trying to modify the sales invoice form in a Business Central 14 On Premise system that has ChargeLogic Payments installed as an extension. My sales invoice modification needs to use a field from the ChargeLogics extension. I have added the .app files in the dependency's section of the app.json file and added the two .app packages into the .alpackages folder. The field is visible for me to reference. However when I try to download symbols (or debug) I receive an error that the app is not installed. I am using a DOCKER Image which does not have the ChargeLogic apps installed. Because it is a Sandbox I cannot upload the extension. I cannot debug or test because the ChargeLogic apps are not installed in my sandbox and I am not aware of how to install them.

**Error:**
[2020-05-29 08:46:20.24] Sending request to http://iss14:7049/NAV/dev/packages?publisher=ChargeLogic%2C LLC&appName=ChargeLogic Base&versionText=1.1.1.0
[2020-05-29 08:46:20.24] Sending request to http://iss14:7049/NAV/dev/packages?publisher=ChargeLogic%2C LLC&appName=ChargeLogic Payments&versionText=4.0.12.0
[2020-05-29 08:46:20.35] The request for path /NAV/dev/packages?publisher=ChargeLogic%2C%20LLC&appName=ChargeLogic%20Base&versionText=1.1.1.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2020-05-29 08:46:20.39] The request for path /NAV/dev/packages?publisher=ChargeLogic%2C%20LLC&appName=ChargeLogic%20Payments&versionText=4.0.12.0 failed with code NotFound. Reason: No published package matches the provided arguments. 

If I try to publish **any** app to the sandbox image I receive an error that the package contains corrupted data.

**app.json file:**
 "dependencies": [
    {
      "appId": "4714e6b7-6fde-4a8b-9c39-c2da3f239396",
      "publisher": "ChargeLogic, LLC",
      "name": "ChargeLogic Base",
      "version": "1.1.1.0"
    },
    {
      "appId": "0f30fcab-5ea0-4345-ba83-a32015759fbe",
      "publisher": "ChargeLogic, LLC",
      "name": "ChargeLogic Payments",
      "version": "4.0.12.0"
    }
  ],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",

**Comment by atoader** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
