### ISSUE TITLE
Fields are not displayed on a card page in the mobile client

### ISSUE THREAD

**Issue by btaylor-xtivia** [microsoft/AL#5971]
**Describe the bug**
In the mobile client, when selecting a record from a list page that has a CardPageID property set to the card page name, the fields on the card page do not display. 

**To Reproduce**
Create a card page and list page for customers. Set the CardPageID on the list page to the name of the card page.

``` AL Code to reproduce the issue ```
CardPageID = "My Customer Card"

**Expected behavior**
AL compiler should produce an error if CardPageID is not a valid page object ID.

**5. Versions:**
 - AL Language:  5.0.288712
 - Business Central: 16.1.12629.12805

**Comment by dtkb** [comment]
Your desriptions make it unclear what's the problem. You can enter anything as `CardPageID` and it'll compile but not open a page? It'll open the right page but not display any data? It lets you specify a page for a different table but doesn't complain at compile or run time?

**Comment by btaylor-xtivia** [comment]
The problem is that if I put CardPageID = "My Customer Card" on my list page, it compiles just fine and displays correctly on the web client, but none of the fields on the card page are displayed on the mobile client.

If CardPageID is updated to the object ID of the card page, mobile will display the page correctly.

**Comment by dtkb** [comment]
Huh, that seems like a very strange one.

But then, this bit of the original report is different/irrelevant, is that right?

>  AL compiler should produce an error if CardPageID is not a valid page object ID.

It should accept either the name or the ID, and the name should be preferred. From what you've said, you've tried both, and both are valid, but mobile fails for the name.

You haven't shown that you can give it a page that doesn't exist (or is a typo, etc.) and it not compile, so that seems not to be occurring or related.

**Comment by atoader** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by AndreyKorepanov** [comment]
Hi @btaylor-xtivia, thank you for reporting the issue. As it is not reproducible for web client (I tried it OnPrem), but only for mobile client, the issue is not related to the AL language or dev environment. Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal.
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Thank you!
