### ISSUE TITLE
Translations for page actions not working when booked marked to Role Center

### ISSUE THREAD

**Issue by joningi98** [microsoft/AL#5991]
**Describe the bug**
When bookmarking a page action to Role Center the translation does not show

**To Reproduce**
1. Change the language (any other than English), in my case Icelandic
2. Go to any standard page action 
3. Bookmark it
4. Got to Role Center and find the page action

**Screenshots**
This page action is a report but this also happens with other actions that are in the base application
I´m using the "Cost Acctg. Analysis" (Translated as:  "GREINING Á KOSTN.BÓKH.") action and bookmarking it.
![image](https://user-images.githubusercontent.com/42949613/85860793-d5f4bc80-b7ae-11ea-8e2d-ca86720e9e5a.png)

The action shows up with this name in actions in Role Center
![image](https://user-images.githubusercontent.com/42949613/85861062-44397f00-b7af-11ea-8151-95a3e00499cb.png)

**Version**
Version: Business Central 16.0 (Platform 16.0.11240.12076 + Application 16.0.11240.12076)

**Comment by qutreson** [comment]
@joningi98 this issue is similar to #5846. We had an issue capturing the captions of report bookmarks for other languages than English. This has been fixed in our latest developer previews and in version 16.2. 

I am closing this issue as this Github repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. If you can reproduce this issue on the latest Business Central Developer preview version, please log a new issue containing the version number for the platform you tested it with.
