### ISSUE TITLE
FieldType::Enum does not exist?

### ISSUE THREAD

**Issue by hougaard** [microsoft/AL#5998]
The FieldType datatype is missing an option for Enum fields.

**Comment by esbenk** [comment]
Since the underlying runtime class in the same, (most) code that tests for Option would work unchanged. This is important when we switch convert existing Options to Enums. 

We are considering a an IsEnum property on the FieldRef if you need to distinguish.

Is it a specific scenario you are trying to solve?

**Comment by bjarkihall** [comment]
@esbenk Variants also don't have IsEnum: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/variant/variant-data-type

**Comment by navdotnetreqs** [comment]
This is still relevant. Why are you closing issues without handling them?
