### ISSUE TITLE
File Management is an ambiguous reference

### ISSUE THREAD

**Issue by adejsy** [microsoft/AL#6001]
**Describe the bug**
The AL parser seems to have serious issues where there are a large number of AL files invloved. We have converted our ISV solution and we have quite a few compilation issues to fix, breaking changes etc. We see many errors raised whereby it states, for example "File Management is an ambiguous reference between File Management defined by the extension ISV Solution and File Management defined by the Base App...'

The issue though is that we are using the Base App, we have not tried to replace the Base App and File Management codeunit only is in the Base App and definitely not in our AL files of our ISV solution.

**To Reproduce**
I imagine if you have a nice compiling AL solution with no volume of errors to fix then the AL parser does not have a meltdown and this error would not be raised.

If we change the variable declarations to say Codeunit 419 then this seems to fix the problem, but then we are left with unreadable code and object numbers everywhere.

**Expected behavior**
Simply the parser should not be raising this error, or, if it is, it should be helping us find out why it thinks that...

**Screenshots**
Error described above.

**5. Versions:**
 - AL Language: v5.0.288712
 - Business Central: Business Central On Prem docker container. Version 16. Microsoft_Base Application_16.0.11240.12076.app. Microsoft_System Application_16.0.11240.12076.app. Microsoft_System_16.0.11233.12061.app

**Comment by qutreson** [comment]
@adejsy, for additional context about this issue, did you just convert your extension from C/AL to AL? Does your project have other errors like AL0198? It looks similar to this issue: #745, where due to some invalid syntax, the parser starts considering variable declarations as object declarations (where the object ID is missing, if the object requires an ID).

**Comment by adejsy** [comment]
@qutreson - yes we have converted our ISV solution from C/AL to AL and now we are tackling breaking changes etc and things that, well, we just need to change right :)

It looks like the issue is very similar to issue #745 that you have highlighted - thank you for that. Is there a way I can find out where potentially the parser is getting its logic from? I note that in issue #745 it talks about deleting symbols to find via a subsequent "Go to definition"...

**Comment by qutreson** [comment]
The parser gets lost when some unexpected syntax keywords are declared (for instance, by having a controladdin or a field keyword in a page layout - the examples from the issue #745). When this happens, the AL compiler will report an error AL0198, with an error message similar to `Expected one of the application object keywords (...)`. From this point the parser will ignore everything until finding an object declaration, but it might mistakenly consider a variable declaration `var codeunit: Codeunit FileManagement` has a declaration that is missing an object ID (in this case you would get a diagnostic AL0114 with a message `Syntax error, integer literal expected.`).  This will also lead to a diagnostic specifying that the object is already declared (AL0197). If the object is referenced, the compiler would then consider it as an ambiguous reference.

From this, a strategy would be to:
- to fix diagnostics in the converted files starting from the top of the file
- fix the diagnostics AL0198 (and eventually, AL0197) before investigating more the ambiguous references

What is mentioned in #745 is that you can try to use Go-To-Definition in order to locate where are the object declaration seen by  the compiler. Removing temporarily the reference packages (in the symbol package cache, usually .alpackages folder), might help in some case, but I haven't tried it myself. Another alternative is to use a text search for the object type + object name and see whether there are errors AL0198 in the same file.

**Comment by qutreson** [comment]
I hope the explanation will help. I will close this issue as we already added to our backlog to improve the parser recovery, when #745 was reported.

**Comment by adejsy** [comment]
> I hope the explanation will help. I will close this issue as we already added to our backlog to improve the parser recovery, when #745 was reported.

Thank you. Very helpful.

**Comment by danielonsombi** [comment]
The error seems to be a bit confusing and one can actually spend hours trying to figure it out. #745 seems to address the error. Thanks for pointing it out.
