### ISSUE TITLE
Progress bar indicator not showing

### ISSUE THREAD

**Issue by MaartenGerritsen** [microsoft/AL#6010]
**Describe the bug**
The Dialog datatype seems to ignore the UPDATE of a percentage bar indicator.

**To Reproduce**
Steps and to reproduce the behavior:
Create a report like:

report 50100 "Progress Bar TEST"
{
    Caption = 'Demo Contract Billing Simulation';
    ProcessingOnly = true;
    ShowPrintStatus = false;

    dataset
    {
    }

        trigger OnPostReport()
        var
            i: Integer;
            Window: Dialog;
        begin
            Window.OPEN('Processing\#1##################\@2@@@@@@@@@@@@@');
            for i := 1 to 100 do begin
                Sleep(100);
                Window.Update(1, ROUND(i / 100 * 10000, 1));
                Window.Update(2, ROUND(i / 100 * 10000, 1));
            end;
            Window.Close();
            message('Ready');
        end;
    }
}

**Expected behavior**
2 bars: 1 with percentage of done, and 1 with a number
But only the number is shown, not the percentage bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/25688441/86618493-4f638a80-bfb9-11ea-8ec5-bbdc88784f2e.png)

**5. Versions:**

 - AL Language: v5.0.288712

 - Business Central: Version: W1 16.2 (Platform 16.0.13402.0 + Application 16.2.13449.0)

**Comment by NKarolak** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-open-method

>  Note
> 
> With the Dynamics NAV Client connected to Business Central, you can use @ characters instead of # characters for the String parameter to display the value as percentage and a progress indicator. The percentage value that is displayed is the percentage of the variable value from 0 to 9999. **This is not supported in the Business Central Web client.**

**Comment by MaartenGerritsen** [comment]
Thanks Natalie, But does this mean it is not an issue and is not in the backlog: will this be solved in a future release?

**Comment by NKarolak** [comment]
It is on Microsoft to answer this :-) I could only guess.

**Comment by MaartenGerritsen** [comment]
I did a quick search in the base app code on '@.*@@@@'. And there are still many. So I guess this will still have some value in the future ;).

**Comment by qutreson** [comment]
Thank you @NKarolak for your investigation and your answer. 

@MaartenGerritsen, the decision on whether to fix it or to consider it as by-design (because this limitation is publicly documented) would have to be done by the team owning this area/feature.

We suggest that you open a support case or file a bug in Collaborate. To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
