### ISSUE TITLE
Finding 2 files.

### ISSUE THREAD

**Issue by MathiasHusum** [microsoft/AL#6011]
**Describe the bug**
Upon creating a new table, editing it, and then saving it, 2 files are found.
**To Reproduce**
Steps and to reproduce the behavior:
1. Create a new Table file.
2. Edit file.
3. Save file.

``` AL Code to reproduce the issue ```

**Expected behavior**
Only 1 file is created, edited and saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/21789071/86753679-8e88ee80-c040-11ea-9b8c-875a17f9b9b4.png)
![image](https://user-images.githubusercontent.com/21789071/86753894-be37f680-c040-11ea-913a-b56f21c03e78.png)

**5. Versions:**

 - AL Language: 3.0.193882

 - Business Central: 14.9

**Comment by MathiasHusum** [comment]
![image](https://user-images.githubusercontent.com/21789071/86761201-158c9580-c046-11ea-83ac-4ee103a0de8e.png)
Adding screenshot of table folder.

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
