### ISSUE TITLE
Publishing code modified base app runs into error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by hbaehren** [microsoft/AL#6025]
**Describe the bug**
We are developing a rather large (~18.000 AL objects with many dotNet Addins) code modified base app. The compilation from Visual Studio code with Ctrl+Shift+B runs successfully. We have created a local Database including NAV-Server with only the system tables. We are able to compile and publish a code modified base app which only includes the Microsoft AL files on that local NAV-Server successfully. When trying to publish our code modified base app with 

`Publish-NAVApp -ServerInstance NAV -Path "C:\VisualStudioCodeProjects\ALTest\Axians Infoma_newsystem_1.0.0.0.app" -SkipVerification -Verbose`

the command runs for approximately 20 minutes and runs into the following error:
`Publish-NAVApp : Object reference not set to an instance of an object.
`
During the running of the command the process Microsoft.Dynamics.Nav.Server utilizes all available free RAM (approx. 24GB).

In the event log there are the following two errors:

1. MicrosoftDynamicsNavServer$NAV
`Server instance: NAV
Category: Extensions
ClientSessionId: 37620e61-72d4-4701-b421-6e88978a3f3d
ClientActivityId: 394ad171-1a5f-4852-9e7b-345d74c3b69d
ServerSessionUniqueId: 2101b895-c3ca-4242-bc8a-d625c2be531d
ServerActivityId: eb66b1bb-1d6c-4140-9ed1-e9850ca9daaf
EventTime: 07/10/2020 12:46:34
Message Object reference not set to an instance of an object.
ProcessId: 19496
Tag: 00001YW
ThreadId: 17
CounterInformation: `

2. Microsoft.Dynamics.Nav.Management.dll
`Type: System.InvalidOperationException
Message: Object reference not set to an instance of an object.
HResult: -2146233079
`

**To Reproduce**
1. Create modified base app
2. Create local Database and NAV-Server which has only the Microsoft System Objects
3. Try to publish the App on the local NAV-Server with `  Publish-NAVApp -ServerInstance NAV -Path "C:\VisualStudioCodeProjects\ALTest\Axians Infoma_newsystem_1.0.0.0.app" -SkipVerification -Verbose`

**Expected behavior**
It should be possible to publish our code modified base app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22095707/87157407-82aa6000-c2be-11ea-8afb-e154bb829e3a.png)
![image](https://user-images.githubusercontent.com/22095707/87157472-9786f380-c2be-11ea-8d97-a71300a2e939.png)
![image](https://user-images.githubusercontent.com/22095707/87157489-a372b580-c2be-11ea-80fc-e105023189b1.png)

**5. Versions:**
 - AL Language: 5.0.288712
 - Business Central: 14.0.32600

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
