### ISSUE TITLE
🛑🛑🛑Please contact customer support🛑🛑🛑

### ISSUE THREAD

**Issue by nagatake9i4** [microsoft/AL#6033]
[Error]
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: The extension could not be deployed because it is already deployed as a global application or a per tenant application.

 [Procedure]
1.  Upload the extension in the BC environment (sandbox).
 2. Local App file "NGTTEST_TEST001_1.0.0.12.app". and deploy.
 3. See if the extension is already installed.Run AL Publish
 4. The above error occurs

After that, a series of "Uninstall" and "Unpublish" is performed repeatedly, and the result is publish was successful.

I can't find the cause of this error.

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
