### ISSUE TITLE
error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '14.0.0.0' could not be loaded.

### ISSUE THREAD

**Issue by NedimYami** [microsoft/AL#6052]
**Describe the bug**
Hello,
I have upgrade Nav 2018 database to Business Central Spring 2019 onPrem.
I followed the process steps as below link for data upgrade. And data upgrade was finished succesfully.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data

I want to adding extension to my onprem Buciness Central Spring 19 database.
But I publish the app cause of error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '14.0.0.0' could not be loaded.
I could download symbol.(and also task 14 complated succesfully of the data upgrade steps)

**Screenshots**
![image](https://user-images.githubusercontent.com/42783080/88373075-d7120d00-cd9f-11ea-978c-fabdb36fbbbb.png)

you can see my appinfos as below. 
![image](https://user-images.githubusercontent.com/42783080/88373130-ee50fa80-cd9f-11ea-98d1-ecda825082bb.png)

app.json
![image](https://user-images.githubusercontent.com/42783080/88373212-180a2180-cda0-11ea-9ba0-84080aaa3075.png)

**5. Versions:**
Instaled Al Language 5.0.288712.

![image](https://user-images.githubusercontent.com/42783080/88373287-42f47580-cda0-11ea-9736-761cd02ee32b.png)

Business Central Spring 2019 14.0:
14.0.29537/29530

**Comment by atoader** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
