### ISSUE TITLE
The debugger options cannot be used for this server - Business Central

### ISSUE THREAD

**Issue by DavidRRA** [microsoft/AL#6087]
I was developing a project on VS Code for a Sandbox environment and it was working fine, and I could publish the solution.
However, today I tried to republish the solution again, and I got the following error: "The debugger options cannot be used for this server.". 
I already restarted VC Code, and clear the Cache but it didn't work.  I would appreciate if you could help me in finding a solution for this issue. 
Thank you !
![VS Code Issue](https://user-images.githubusercontent.com/69816437/90431777-2aba0280-e08f-11ea-8b89-c61fb4118130.png)

**Comment by babak2000ir** [comment]
I'm having the same issue, yesterday evening (Around 9pm-10pm GMT), my sandbox environment didn't react to debugging, it couldn't hit my debug breakpoints. It was working few minutes before that, I was in the middle of some development.

Since then I tried restarting and reinstalling VSCode, Also dropped all my sandboxes and created them again, I tries UK and US Databases. I'm getting the same error:

![image](https://user-images.githubusercontent.com/16867577/90436480-aa17f800-e0c8-11ea-8f46-91ba79c587a3.png)

here is my app.json

![image](https://user-images.githubusercontent.com/16867577/90436582-d7fd3c80-e0c8-11ea-99ca-ca872dd02717.png)

**Comment by achecac** [comment]
Hi, I have same issue since 18h GMT.
AL v5.0.312966
Versión: ES Business Central 16.4 (Plataforma 16.0.14648.15420 + Aplicación 16.4.14693.15090)

Publish **without** debugging works fine.

**Comment by NKarolak** [comment]
It is clearly related to the AL language version 5.0.312966. 
To work around, downgrade to 5.0.311667.

**Comment by atoader** [comment]
We are investigating this issue. We'll update the thread once we know more.

**Comment by charlespockert** [comment]
Same here - the only clue I had is that someone posted on a forum somewhere that the issue was due to the fact the AL tools version didn't match the version on the server.

Still took most of the day of tearing my hair out/trying on a different machine before I resolved!

**Comment by atoader** [comment]
A new version of the extension was released that solved this issue. Thank you very much for your patience and for raising the issue here!

**Comment by DavidRRA** [comment]
Fantastic, it is now solved, thank you!
