### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by boomerama** [microsoft/AL#6091]
**Describe the bug**
VSCode gets the Errormessage while Mouseover a Function -> 'Index was outside the bounds of the array.'

**To Reproduce**
Steps and to reproduce the behavior:
1. Mouseover a Function, For example ""Sales Invoice Subform"

``` AL Code to reproduce the issue ```

**Expected behavior**
Go to show the reference

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36401349/90670376-b57a3900-e218-11ea-9606-55a02427eac0.png)

**5. Versions:**

 - AL Language:  5.0.320540

 - Business Central: 
Version: DE Business Central 15.2 (Platform 15.0.38951.0 + Application 15.2.39040.0)

**Comment by atoader** [comment]
Can you provide a fully contained project to reproduce the issue and indicate the line where we should hover over?

**Comment by qutreson** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

Please note that this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
