### ISSUE TITLE
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=ignore failed with code UnprocessableEntity. Reason: The extension could not be deployed because it is already deployed as a global application or a per tenant application.

### ISSUE THREAD

**Issue by abrarShaikh273** [microsoft/AL#6105]
**Describe the bug**
I made couple of changes in my existing extension which was published correctly.

I made couple of changes (No schema changes) and tried to deploy again and get this error:

The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=ignore failed with code UnprocessableEntity. Reason: The extension could not be deployed because it is already deployed as a global application or a per tenant application.

**To Reproduce**
Steps and to reproduce the behavior:
1. Ctrl+F5

**Expected behavior**
Need to publish on sandbox environemnt

**Screenshots**

![image](https://user-images.githubusercontent.com/57489444/91340871-4f545f80-e79e-11ea-99ef-2796284affe8.png)

**5. Versions:**

 - AL Language: v5.0.320540

 - Business Central:16.4.14693.15090

**Comment by thpeder** [comment]
HI @abrarShaikh273,
Since this isn't an issue with the devs tools per say, but is one with our online offering.
We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.  
Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
