### ISSUE TITLE
The record xxx should be modified before saving to the database. (AA0214 / TransferFields)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6114]
**Describe the bug**
When modifyng a record solely via TransferFields, the AA00214 is raised while not expected.

**To Reproduce**

Create following function and add it to the customer card page

```
local procedure RefreshAndModifyRecord(DoModify: Boolean)
    var
        Customer: Record "Customer";
    begin
        if Customer.Get(Rec."Customer No.") then begin
                Customer.TransferFields(Rec); // record is modified here
                Customer.Modify(); // AA0214 is raised on this line
            end;
```
**Expected behavior**
In the above scenario, Customer record is modified via the transferfields and AA0214 rule should thus not be raised.

**5. Versions:**
 - AL Language: 

![image](https://user-images.githubusercontent.com/25268332/91690548-6d3b0f00-eb66-11ea-82b8-4d634b1dad30.png)

**Comment by PaulIvan** [comment]
I am closing this issue because it has been resolved in the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24994 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
