### ISSUE TITLE
When I unpublish app all tables still exist in SQL database

### ISSUE THREAD

**Issue by dkatson** [Microsoft/AL#612]
Is it a bug or feature?
When I

- press Ctrl+F5
- fill data in my extension
- go to : Extension management
- Uninstall my extension
- Unpublish my extension
- go to VS Code and press Ctrl+F5 once again, all data that I inputted before - exist!

I found this is because when I uninstall and unpublish my extension, tables from SQL database are not deleted.

**Comment by StanislawStempin** [comment]
This is by design for now. In the future there will me more control over what happens to data related to an extension both during development and at runtime.

**Comment by cmrudolph-msft** [comment]
Per a colleague, this is fixed for the next update. The VS Code flow will clean up the old schema on the next publish operation if the app was manually unpublished since. 

It is also possible to use Sync-NavApp with the Clean mode from PowerShell to remove all schema at any time. The "sync clean" action is not available through the extension management page right now.
