### ISSUE TITLE
[Question] What ways are there to decrease the time it takes for apps to publish?

### ISSUE THREAD

**Issue by PieterJacob** [microsoft/AL#6128]
Experts,

We noticed that the time it takes for app to publish increases when there are multiple dependencies towards the app itself.
For our base app it takes now more than 10 minutes to publish. 

So we are wondering, what ways are there to minimize the time it takes for apps to publish? Or at least some insight about what increases the time for an app to publish.

**Comment by bjarkihall** [comment]
Performance of your hardware, network but also the number of AL objects (size of the bundle).
[Rapid Application Development](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rad-publishing) (RAD) decreases the publishing time **after** you've done a full publish at least 1 time but as the documentation describes, it's a bit unstable and they recommend doing full publish regularly in between.

You can't publish/republish a selection from file explorer (e.g. 1 folder or 1 file) like what happened on compilation in C/SIDE, you can't ignore specific folders (like e.g. a node_modules folder, if you have a web application in your solution or a big folder with static assets) to aid the compiler - it just traverses every folder recursively.

There's little you can do about the Base app size itself, since you just get it straight from MS but it has been their goal to componentize it into smaller pieces but I'm not sure if it even solves [the problem](https://experience.dynamics.com/ideas/idea/?ideaid=a37cf0d0-2105-ea11-b862-0003ff68edfa) since deployment failures aren't gracefully handled last time I checked - [this ](https://experience.dynamics.com/ideas/idea/?ideaid=eeb1501b-5bf1-e811-a140-0003ff689cda) explains dependency handling of uninstalling/installing extensions in a multiroot workspace, which came in 2019w2, but [this](https://experience.dynamics.com/ideas/idea/?ideaid=b526b6ee-5022-ea11-8454-0003ff689d2b) describes the issue you have when it doesn't go the typical happy-path (gracefully handle failed publish). Some people work around this by creating [powershell scripts](https://www.waldo.be/2020/05/12/multi-root-workspaces-in-vscode-for-al-development-episode-2/) that handle publishing all extensions in a multi-root workspace.

The publishing time has been improving over the last months, but I'm curious how Microsoft handles AL development internally, since these publishing times are generally pretty time-consuming.

**Comment by qutreson** [comment]
We are also providing some guidelines about how to Optimize Visual Studio Code for AL Development in [our online documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-optimize-visual-studio-code). You can also set `"al.incrementalBuild": true` in your settings.json. The following issue seems related too #5768.

Please also have a look at our Ideas forum at https://aka.ms/BusinessCentralideas, to create or upvote suggestions about performance improvements. This will help us allocate time and resources for improving this scenario.
