### ISSUE TITLE
extending extensions and embedded app

### ISSUE THREAD

**Issue by rtwcolumbus** [microsoft/AL#6137]
**Describe the bug**
We are using v15 (cu 03) on prem installation

We have an embedded app (mega app from our supplier) on which we have built a set of "standard" extension apps(STD). (all working fine no issues) - for a customer we have then built them a specific extension app (PARTNER) that extends our standard app (in this case added extra fields to the sales header table) - and is all working. The customer is now building their own extension app (CST) which is dependent upon all of the above apps - the symbols download fine and from vscode you can see and use the fields created in STD and PARTNER apps, the app CST app compiles and builds without issue - HOWEVER when you try to publish (either F5 in vscode or via powershell) we get an error if you reference any of the PARTNER added fields (either in AL code (i.e. a trigger of procedure), by adding a PARTNER field to a page or a report... all yield the below error when trying to publish... 

Publish-NAVApp : Extension compilation failed
error AL1024: A package with publisher 'Partner Name', name 'Customer Apps Name', and a version compatible with '15.0.3.5' 
could not be loaded. Sequence contains no elements
Objects/Page%20Extensions/PAGE50001.My%20Sales%20Order.al(18,41): error AL0118: The name '"Freight Vendor No"' does not exist in the 
current context
At C:\Apps\install.ps1:78 char:5
+     Publish-NAVApp -Path $appFile -ServerInstance $nst -SkipVerificat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Pub 
   lishNavApp

In the above '"Freight Vendor No." is a field added by the PARTNER app to the sales header table and we are simply trying to drop it on the sales order page (via the CST app).

Have tried re-downloading symbols, restarts... 

**To Reproduce**
Unable to replicate without the embedded the STND, PARTNER, and CST apps

``` AL Code to reproduce the issue ```
**Code from PARTNER**
```
tableextension 50026 "My Sales Header" extends "Sales Header"
{
    fields
    {
        field(50023; "Freight Vendor No"; Code[20])
        {
            DataClassification = SystemMetadata;
            Caption = 'Freight Vendor No.';
            TableRelation = Vendor."No.";   
	}
    }
}
```

**Code from CST**
```
pageextension 50101 "My Sales Order" extends "Sales Order"
{
    layout
    {
        addlast(General)
        {
            field("FrghtVendNum"; "Freight Vendor No") { ApplicationArea = All; }
        }
    }
}
```

**Expected behavior**
to be able to reference and using fields from all depended extensions

**Screenshots**
n/a

**5. Versions:**
 - AL Language:  v5.0.329509

 - Business Central: NA Business Central 15.3 / _ApplicationBuild_ (Platform 15.0.40073.40791 + Application 15.2.39040.0)

Any suggestions as to what the issue could be / where to look for more detailed info ect... are much appreciated

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
