### ISSUE TITLE
AL Compilation Error AL0460

### ISSUE THREAD

**Issue by MarkusWinBI** [microsoft/AL#6144]
**Describe the bug**
When extending a page with a page extension I get error from compiler
{
	"resource": "...src/pageextension/...PurchOrdSub.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL0460",
	"severity": 8,
	"message": "Client-side events are supported only on pages and page extensions.",
	"source": "AL",
}

when using a dotnet variable
        [RunOnClient]
        [WithEvents]
        Camera: DotNet UT_CameraProvider;

On new Pages everything is fine.

**To Reproduce**
create a page extension and try to add a variable of type DotNet with "RunOnClient" property.

**Expected behavior**
Client-side events are supported on page extensions as well as on pages

**5. Versions:**
 - AL Language: 3.0.150570
 - Business Central: Application 42648
Platform Build 42627

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

**Comment by MarkusWinBI** [comment]
@qutreson I would do if you would not have shut down your partner portal on March 2019. 

But I found an article where to find the new portals. 
https://blogs.partner.microsoft.com/mpn-apac/partnersource-customersource-technical-support-entry-decommissioning/
