### ISSUE TITLE
BC14 CU11 App Install Error

### ISSUE THREAD

**Issue by dipakpatel2505** [microsoft/AL#6146]
I am facing issue when I  try to install Suretax app on BC14 CU11.

I am able to install app on Cronus BC14 CU11 Database but I am getting error as shown in below snapshot when I tried to install on Customer Database. 

I have already generated symbol for all objects and resolved compilation error. Any help is appriciated.

Note: Customer Database is upgraded from 2009 R2 to BC 14 CU11.

[1Error.txt](https://github.com/microsoft/AL/files/5232511/1Error.txt)

**Comment by dipakpatel2505** [comment]
Is it correct place to post this issue? Please provide link if it is not correct.

**Comment by qutreson** [comment]
Hi @dipakpatel2505, the issue here is that you are missing the system symbols in your database. `error AL1024: A package with publisher 'Microsoft', name 'System', and a version compatible with '14.0.0.0' could not be loaded. Symbols for the requested app System by Microsoft 14.0.0.0 could not be found in the database`. The other errors about the missing tables are just a consequence from that. You should publish the system symbols on your server as -Symbols only first. See example 4 in the documentation of [Publish-NavApp](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/publish-navapp?view=businesscentral-ps-16#examples).

This said, this repository, this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel. You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do

In case you want to ask a question to the community, you can also refer to one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
