### ISSUE TITLE
g.xlf contents move on irrelevant object changes

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6157]
This is my original issue: https://twitter.com/KarolakNatalie/status/1308039564859256833?s=20
I don't want to start again a discussion about whether the g.xlf should be part of repository, or not. 
I'd just like to know, whether it is known to Microsoft, that the g.xlf content is not created consistently? Is that intended, can it be avoided? Thanks

**Describe the bug**
If the g.xlf file is controlled by git, it is obvious that on translation-irrelvant object changes, parts are moved inside the file, back and forth. The content is updated more often than it should.

**To Reproduce**
Steps and to reproduce the behavior:
1. In your repository of an arbitrary app, create the AL package and commit all changes in Git.
2. If the g.xlf is not yet part of your repository, add it to Git.
2. In an already existing page field of your choice, add (only as one example of an irrelevant change) `Visible = true;`
3. Create a package or publish your app and control what changes git has logged in the g.xlf. The field block has been moved. The block content however is exactly the same as before (as expected).

**Expected behavior**
The g.xlf should be updated only on relevant object changes (new or renamed controls, for example). Parts should not move on irrelvant object changes.

**Versions:**
 - AL Language: 6.0.324421 (but the issue is already much older)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21368 and VS Code Extension Version 7.0.404359. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
