### ISSUE TITLE
Enable specifying objects by name in properties like SourceTableView, CalcFormula, etc.

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6163]
**Describe the bug**

When setting up `SourceTableView`s, `TableRelation`s, and so on - that relate to other tables by table IDs (or, far less frequently, specify codeunit IDs to run, etc.) - we still have to use the raw integer ID, which is ugly, opaque, error-prone, and incompatible with what I hear is the plan by MS to get rid of object IDs entirely (eventually!).

**To Reproduce**

Try to make a page that shows `Custom Report Selection`s for `Customer`s only.

You have to enter it like so:

    SourceTable = "Custom Report Selection";
    SourceTableView = where("Source Type" = const(18));

**Expected behavior**

Ideally, we should be able to specify the table ID via its name in the `Database::` namespace or similar, like we can in actual AL code:

    SourceTable = "Custom Report Selection";
    SourceTableView = where("Source Type" = const(Database::Customer));

Please consider making this possible in all such `where()` expressions, and for all object types. Thanks!

**Screenshots*

N/A

**5. Versions:**

 - AL Language: 5.0.335750
 - Business Central: 16.5.15897.16808

**Comment by thloke** [comment]
Thanks for the suggestion. Because this is an improvement and not a bug, it will gain more traction on BCIdeas, since that is where we look at for new features. Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by dtkb** [comment]
=> https://experience.dynamics.com/ideas/idea/?ideaid=3c20fb10-3802-eb11-b5d9-0003ff68e671
