### ISSUE TITLE
Error downloading symbols for 16.5 system app

### ISSUE THREAD

**Issue by davmac1** [microsoft/AL#6168]
Cloud client was recently upgraded to 16.5
I get this error downloading symbols:
The request for path /v2.0/Sandbox2/dev/packages?publisher=Microsoft&appName=System&versionText=16.5.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2020-09-27 17:55:09.79] The following dependencies will be queried for propagated dependencies:

[2020-09-27 17:55:09.79] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

I read a solution from a year ago to unpublish and republish the system app.
Since this is a cloud customer - isn't this handled already when Microsoft upgrades their own apps?

**Comment by qutreson** [comment]
The versioning used for Microsoft extensions like the Base Application and the one used by the platform (and the System symbols) is different. The platform version corresponding to 16.5 is 16.0.15884.0 and not 16.5.0.0.0, which is why not symbols are found matching the specified version.

Note that, when downloading symbols and when publishing your extension, the highest version available for the tenant is always returned, so you could also specify 16.0.0.0 and it would always pick up the latest version.
