### ISSUE TITLE
ShowCaption does not work properly on Groups ConfirmationDialog

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#6169]
**Describe the bug**
The property 
```al
ShowCaption = false;
```
does not work as expected on Pages of Type `ConfirmationDialog`
**To Reproduce**
Create a Page of Type `ConfirmationDialog` and open this page with `RunModal`.
If you set the top group to `ShowCaption = false;` the caption area is still shown. 
![image](https://user-images.githubusercontent.com/56249171/94420188-16841d80-0184-11eb-870a-43a20f4ad77c.png)
On normal Cards this works as expected.

```al
page 50000 "Get Input"
{
Caption = 'Get Input';
PageType = ConfirmationDialog;
UsageCategory = None;
SourceTable = "Salesperson/Purchaser";

layout
{
    area(Content)
    {
        group(General)
        {
            ShowCaption = false;
            field("Input Field"; InputField)
            {
                ApplicationArea = All;
                Caption = 'Input Field';
                ShowMandatory = true;
            }

        }
        group(Values)
        {
            ShowCaption = false;
            group("Current Values")
            {
                Caption = 'Current Values';
                field("Old Value"; Name)
                {
                    ApplicationArea = All;
                    Editable = false;
                }
            }
            group("New Values")
            {
                Caption = 'New Values';
                field("New Value 1"; NewValue)
                {
                    ApplicationArea = All;
                    Caption = 'New Value 1';
                    Editable = false;
                }
            }
        }
    }
var
    InputField: Text;
    NewValue: Text;
}

```

**Expected behavior**
The Group should be shown withouth the header row to open the inner group.

**Screenshots**
![image](https://user-images.githubusercontent.com/56249171/94419249-c6f12200-0182-11eb-96d5-91f40674f13d.png)

**5. Versions:**

 - AL Language: 

 - Business Central:
Version: Plattform 14.0.44656.0 + Application 44663 (DE Business Central 14.17)

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
