### ISSUE TITLE
Codeunit 5790 Procedure QtyAvailabletoPromise is missing the AvailableToPromise on IsHandled

### ISSUE THREAD

**Issue by thatnavguy** [microsoft/AL#6173]
**Describe the bug**
Under Codeunit 5790 Available to Promise, there is a procedure called QtyAvailabletoPromise that returns a decimal value.
There is an event handler called OnBeforeQtyAvailableToPromise with parameter IsHandled.

The IsHandled logic returns no decimal.

//original
If IsHandled then
  exit;

//should be
If IsHandled then
  exit(AvailableToPromise);

If we don't return the AvailableToPromise, there is no point calling it before the procedure.

**To Reproduce**

**Expected behavior**
There should be a way to return our own calculated AvailableToPromise when we call OnBeforeQtyAvailableToPromise. Otherwise, I don't see the point of doing event subscription to OnBeforeQtyAvailableToPromise.

**Screenshots**
![2020-09-29_090039](https://user-images.githubusercontent.com/72045245/94480101-4b4eae00-0232-11eb-8051-539ab77822fe.jpg)

**5. Versions:**
Business Central: 16.5

**Comment by thloke** [comment]
Hi! Let's get the issue to a team who will fix and backport it, as this repository is only for issues related to the AL compiler and developer tools of the latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case, since this is a bug about our application code and not the AL development experience itself.

To open a support case, you can: 

- Open a support request to CSS through the PartnerSource portal  

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
