### ISSUE TITLE
Missing 'Intelligent Cloud Migration'-apps in Sandbox Container 

### ISSUE THREAD

**Issue by bvbeek** [microsoft/AL#6193]
Missing two apps in c:\extensions\ in the docker container NL (17.0.16993.0):
- Microsoft_Intelligent Cloud Base_*.app
- Microsoft_Business Central Intelligent Cloud_*.app

We use these app to migration from OnPrem to SaaS.
```
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1457-generic
10.0.17763.1457-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.17763.1457-generic
Disabling Health Check (always report healthy)
Creating Container BP-BacPac-39-2505-NL
Version: 17.0.16993.0-NL
Style: sandbox
Multitenant: Yes
Platform: 17.0.16974.0
Generic Tag: 0.1.0.21
Container OS Version: 10.0.17763.1457 (ltsc2019)
Host OS Version: 10.0.17763.1432 (ltsc2019)
```

C:\extensions> dir :
![image](https://user-images.githubusercontent.com/28626283/94915215-c3c0a380-04ac-11eb-9574-f3312f710961.png)

**Comment by kalberes** [comment]
Wrong  recipients. @freddydk may know more.

**Comment by freddydk** [comment]
I can see that these to apps indeed are not included in the artifacts for 17.0
Will check why, stay tuned.

**Comment by bvbeek** [comment]
Hi Freddy, any news from there ;) ?

**Comment by RCORELLA** [comment]
In Saas version (not only in docker) doesn't appear this option.
Any news about this?  Official documentation says we can upgrade from two last versions, but now it is not possible.

Tks,
Roberto

**Comment by RCORELLA** [comment]
@lassekilperkm.  Thanks for your answer.   The matter is I have the apps installed:

![image](https://user-images.githubusercontent.com/23438653/95955263-d9af5c00-0dfc-11eb-80ac-f96522c20a3f.png)

But trying to replicate from an On-premis BC 15 is not possible because only show "Dynamics 365 Business Central":

![image](https://user-images.githubusercontent.com/23438653/95955454-209d5180-0dfd-11eb-8a86-00bc39252686.png)
In last version (BC16), you can choose between "Dynamics 365 BC" (current version) or "Dynamics 365 BC Previous version"

![image](https://user-images.githubusercontent.com/23438653/95955660-7a9e1700-0dfd-11eb-8f6b-9468fdc59a61.png)

Then, if you try to migrate to the cloud a version bc15 on premise, you will receive an error:

![image](https://user-images.githubusercontent.com/23438653/95955898-d4064600-0dfd-11eb-89b2-da20e7d39919.png)

Sorry because it is in Spanish:
"The local Business Central version must be in the same main version in the online tenant"

But, according with the MS docs you can connect with the Intelligent Cloud, current version + two previous major versions:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud

I think there is a bug with this.

Thanks for your help.

Roberto

**Comment by lassekilperkm** [comment]
@RCORELLA the documentation states that an upgrade to Business Central 17 is required before you can start the Cloud Data Migration.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/migrate-business-central-on-premises

**Comment by RCORELLA** [comment]
It is incoherent.  In the same date, we have two oficial information that are contradictory.  In one says we can migrate onpremis BC15, 16 and 17.  In the other, only BC17.  

Someone can clear this point...

**Comment by dmc-dk** [comment]
Hi everybody, 
Let me clarify this. 

1. Cloud Migration apps are not needed to be installed in the on-prem environment in order to migrate data, they are only needed in the online environment. All you need on-prem is your SQL database and the self-hosted runtime environment. Therefore it does not appear that the migration apps are required on the Docker and in the artifacts. If you believe they are required, please let us know how you intend to use them in Docker. 

2. We indeed do not YET support migration from previous versions of BC to v.17. As in previous releases, this support typically comes with one of the following minor updates. We are actively working on this, so expect it to be available soon. In the meantime you can indeed only migrate from v.17 to v.17.

**Comment by RCORELLA** [comment]
Thanks Dmitry,

The point 1, I had it clear.
Regards the point 1, we wait then the next minor version. 

Roberto

**Comment by yabela-bft** [comment]
Hi @lassekilperkm have you managed to sort out this issue, please? 

![95886407-d5dcf480-0d7e-11eb-92e9-ca9ba355347b](https://user-images.githubusercontent.com/57131067/97555534-87636300-19d8-11eb-9f5e-c42796fdddd5.png)

We have been trying to replicate to a SaaS prod environment via Assisted Setup and we're getting the same error for both on-prem SQL and Azure SQL! Business Central On-Prem is version 17 too. 

Any tips to solve this, please? Thanks!
