### ISSUE TITLE
VS Code does not display all warnings

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#6198]
**Describe the bug**
VS Code is not able to display all warnings, although there would be only a few to find. (I am aware, that per file there is a limit of 100 - but this is not touched.)

I was correcting warning AA0008 (missing parenthesis after a method). 
VS Code displayed a lot occurrencies, but apperently not all, like the one in the following screenshot:
![image](https://user-images.githubusercontent.com/34504100/95088612-7437dd00-0723-11eb-9dd7-c051ad8da52c.png).
I've tried multiple times to restart VS Code / Reload Window. Some code lines will simply never be warned about.

This is **not** an issue of the code analyzer rule itself - my pipline running the same settings does throw all warnings correctly on app compile.
I am **not** using pragmas in the affected files.

**To Reproduce**
I cannot provide simple demo code; just my whole app on request.

My current settings.json contains
```
    "al.enableCodeAnalysis": true,
    "al.backgroundCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"
    ],
```

**5. Versions:**

 - AL Language: 6.1.344970

**Comment by kalberes** [comment]
What if you build your project with Ctrl Shift B. Does it appear then?

**Comment by NKarolak** [comment]
Good point, let me check tomorrow.

**Comment by NKarolak** [comment]
Yes, when building the package, all warnings are shown as Output, but still not under Problems. What does that mean?

**Comment by kalberes** [comment]
We have one more settings(I guess undocumented, but important). Similar to the 100 diagnostics per file (that is also undocumented as far as I know).
If you have a project larger than 50 files than our diagnostics will only emit something we call partial diagnostics. Partial diagnostics will ignore code analysis based diagnostics, since they are very expensive in our current and (original) design.

We have a slice hanging around for quite some time now to enhance how our code analysis framework works. We still have not had time to get to it. But I hope, we will soon.
I know, we should document these important settings. I will ask around see if we could. Maybe we could also expose them, that you can change them, similar as we have exposed the delayAfterLastDocumentChange and similar.

**Comment by NKarolak** [comment]
Thanks Kálmán.

1. So what would be your current suggestion for me? To always rely on the Output window, until the setting is exposed by you?
2. Can you please confirm (again) that it is really depending on the number of files, not on the total file size? I'd like to twitter about it.

**Comment by kalberes** [comment]
1. For now yes. That is the current design if you have large projects.
2. I will list here all our diagnostics creation options.
a. There are a maximum 100 diagnostics shown per file
b. If a project contains more than 50 documents then will not show code analysis diagnostics based on background compilation tracking (in other words almost as you type).
c. There are two public options to control  how often the diagnostic queue is processed.
   i. DelayAfterLastDocumentChange: Specifies the number of milliseconds to wait after the last buffer changes before getting document diagnostics
 ii. DelayAfterLastProjectChange:Specifies the number of milliseconds to wait after the last buffer changes before getting complete diagnostics

3. No it is by design.

**Comment by NKarolak** [comment]
Thanks a lot for your detailed explanation!

**Comment by NKarolak** [comment]
Oh, I forgot to mention something relevant for point 4:
After a fresh clone of my repository, my colleague removed a `()` from my already corrected file, and the warning AA00008 was not shown (as visible in the screenshot of my initial post, btw). Is that still the bug you were relating to? I could still share my repository with you.

**Comment by kalberes** [comment]
If you have removed the () then the code analysis diagnostic should kick in. But since you probably have more then 50 files that wil not be show. Thus we send back all kind of diagnostics but that do not contain anything about the missing (). Vsode would consider that as gone.

**Comment by NKarolak** [comment]
Then why, when I opened the project before the first correction, why DID the compiler show lots of other AA0008 warnings, even within the same file? As I understood you, none should have been shown from the very beginning.

**Comment by kalberes** [comment]
The compiler will show code analysis errors until its internal buffer handling for a  workspace reaches 50 files. Then it will stop.
