### ISSUE TITLE
Will custom javascript Control Add-In be possible in Extensions V2

### ISSUE THREAD

**Issue by ChrisBoltrics** [Microsoft/AL#620]
Will creating a control Add-In like:
https://msdn.microsoft.com/en-us/library/dn182584(v=nav.90).aspx
Be possible in V2 extensions

How, at the moment you create a dll you place in the add-in folder and import de .js as .zip.

Can anyone tell me if and how this will work with Extensions V2?

I saw:
https://github.com/Microsoft/AL/issues/475
But this issue wasn't clear about this.

**Comment by Gallimathias** [comment]
For security reasons, there will be. NET Addins and Interops only on-premise. 

We are currently working on Javascript Addins.

You can find a summary here: #475 #276 #146 #364 #478 #512 

And you Find it a Answer on the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#how-to-use-control-add-ins-the-al-language)
>JavaScript control add-ins are not yet available. We are working on a new approach that doesn't rely on .NET interface as the AL - JavaScript interop specification. It should be available around November Update timeframe.
SaaS:
.NET control add-ins will not be available since the web client cannot execute .NET code.
On-Premise:
.NET control add-ins will be available in the future. No timelime at this point.

**Comment by StanislawStempin** [comment]
This feature is still under development. We will publish more details with the October Update.
