### ISSUE TITLE
AppSourceCop

### ISSUE THREAD

**Issue by tinfister** [microsoft/AL#6209]
**Describe the bug**
We are preparing our App for AppSource.

I've added this line to AppSouceCop.json file
{
  "mandatoryPrefix": "EVE",
  "supportedCountries": ["HR"]
}

And we get this warning in Problems window

	"code": "AS0056",
	"severity": 4,
	"message": "The code 'HR' is not a valid ISO 3166-1 alpha-2 code for a country supported by the product.",

HR is ISO code for Croatia https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

and documentation states that Croatia is supported https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations

How should I solve this?

``` AL Code to reproduce the issue ```

**Expected behavior**
Not to give warning for HR country code

**Screenshots**
![image](https://user-images.githubusercontent.com/29481795/95587615-90e55500-0a42-11eb-9938-9fb8218109cd.png)

**5. Versions:**

 - AL Language: I'm using AL version 6.0.3444420

 - Business Central:

**Comment by kalberes** [comment]
Bug, and there are a few others that are missing.

**Comment by qutreson** [comment]
This is a bug, the list of supported countries is defined here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations

**Comment by bc-ghost** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 19004 and VS Code Extension Version 7.0.370598. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
