### ISSUE TITLE
protected variables declared in one page extension not accessible from another page extension

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/AL#6235]
**Describe the bug**
It appears that protected global variables are only accessible from pageextensions/tableextensions when those protected variables are declared on a page or table. If the protected variables are declared in a page extension, those protected global vars are not accessible from any page extensions from a child app that extend the same page. This nullifies the usefulness of protected variables for modularized applications (> 1 app)

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a multi-root workspace in VS Code with two apps. Call app1 "parentapp" and app2 "childapp". In "childapp", add a dependency in the app.json that it requires "parentapp". 
2. In both apps, extend the Customer List page. 
3. In parent app's customer list pageextension declare a protected boolean variable called "foo"
4. In the child app's customer list pageextension, write some code to access the protected variable foo. 

VS Code will flag the line as an error in the child app because the variable "foo" is inaccessible due to its protection level. 

**Expected behavior**
global protected variables declared  in a parent tablextension/pageextension should be accessible to any child tableextensions/pageextensions in the dependancy graph that extend the same page/table. If a child pagextension can call a parent pageextension's global procedure, why should global protected variables declared in a page extension be off-limits?

Is this error by design? If so, why? If protected variables are not allowed to be declared in a tableextension/pageextension, the AL compiler should flag the declaration as an error at design time.

**5. Versions:**
 - AL Language: 6.1.352568
 - Business Central: NA Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.2.13779.0)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25250 and VS Code Extension Version 8.0.458471. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
