### ISSUE TITLE
AL0605 is reported twice per line ("Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'.")

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6241]
**Describe the bug**
The title says it all!

**To Reproduce**
Put some fields on a page without `Rec.` prepended to the field name.

**Expected behavior**
One warning per line!

**Screenshots**
![image](https://user-images.githubusercontent.com/63455896/96868092-77da9c00-1465-11eb-9050-250544dbdc1d.png)

**5. Versions:**
 - AL Language: 6.1.352568

**Comment by PooyaKharamesh** [comment]
I couldnt reproduce the issue on the latest AL extension. 
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
