### ISSUE TITLE
Business Central throws error when installing extension that contains Label protected variables

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/AL#6242]
**Describe the bug**
Visual Studio code will compile a tableextension/pageextension that has Label global variables defined as protected, but BC will throw an error when installing the extension.

**To Reproduce**
Create an app in VS code with a pageextension containing one or more protected Label variables. The app will compile and publish, but when installing/upgrading the app, an error will be thrown like the following (in the error below, I have a Label named text50000):

```
A call to Microsoft.Dynamics.Nav.Runtime.Apps.NavAppALInstaller.ALInstallNavApp failed with this message: C:\ProgramData\Microsoft\Microsoft Dynamics NAV\160\Server\MicrosoftDynamicsNavServer$BC16-NA-MT-Sandbox\apps\metadata\3\73\73233CA2AF2B77DDCC4821DD2FAAF45E1061DFAC18769E44DA55FB1DC96D421B.cs(44,21): error CS0176: Member 'PageExtension9087225.text50000' cannot be accessed with an instance reference; qualify it with a type name instead
```

**Expected behavior**
If protected labels are forbidden by design when declared in a tableextension / pageextension, VS code shuld catch it at compile time. 

However, I can also see use cases where BC should allow protected variables (i.e. mitigate redundant constant declarations further down in the app dependancy graph). Unfortunately, it seems that protected variables cannot be declared in a tableextension / pageextension as per this semi-related github issue I opened yesterday:

https://github.com/microsoft/AL/issues/6235

**5. Versions:**
 - AL Language: 6.1.352568
 - Business Central: NA Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.2.13779.0)

**Comment by PooyaKharamesh** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
