### ISSUE TITLE
Using AL Language v0.14.17461 with NAV 2018 

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/AL#6259]
**Describe the bug**
Addding the node  "features": ["TranslationFile"] to the app.json file creates error when running F5 from Visual Studio Code

**To Reproduce**
Steps and to reproduce the behavior:
1. Create AL project with AL:GO! 
2. Create docker for NAV 2018 the norwegian version. The artifact used is '11.0.21836'
3. Create label and use it in as the message 
``` AL Code to reproduce the issue ```
pageextension 50100 CustomerListExt extends "Customer List"
{ var
    messageTxt : label 'App published: Hello world';
    trigger OnOpenPage();
    begin
        Message(messageTxt);
    end;
}
**Expected behavior**
Error in Debug Console
The request for path /nav/xxx/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Value cannot be null.
Parameter name: value

**Screenshots**

**5. Versions:**

 - AL Language: v0.14.17461 

 - Business Central: NO Dynamics NAV 11.0 (21836)

**Comment by PooyaKharamesh** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.

 If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
