### ISSUE TITLE
AA0228 Wrong Warning "The local method 'My-Event' is declared but never used."

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#6271]
**Describe the bug**
I get the warning 
>  The local method 'My-Event' is declared but never used.

from the **CodeCop** although the method is used. I guess is does not get this right because of the quotes.

**To Reproduce**
``` 
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        "My-Event"(Rec);
    end;

    [IntegrationEvent(true, false)]
    local procedure "My-Event"(Customer: Record Customer)
    begin
    end;
} 
```

**Comment by DanielGoehler** [comment]
Hi @qutreson, when will this get fixed?

**Comment by qutreson** [comment]
Hi @DanielGoehler, I can reproduce this issue, but I cannot provide any ETA on when this will be addressed. As a mitigation, you can use [rulesets](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools) to suppress this diagnostic in general or [directives](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning) in order to suppress this specific instance

**Comment by DanielGoehler** [comment]
Hi @qutreson, when will this get fixed?

**Comment by qutreson** [comment]
@PaulIvan can you provide an ETA on this fix?

**Comment by db-bc** [comment]
related to "quoting" causing bugs:
* https://github.com/microsoft/AL/issues/6207
* https://github.com/microsoft/AL/issues/6662

**Comment by mazhelez** [comment]
Thanks for reporting this issue. Sorry we haven’t completed it yet, but we’ve had to prioritize elsewhere. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks for your patience.

Going forward we will not track progress on CodeCop issues here on GitHub. Hence, we are closing this issue.
