### ISSUE TITLE
ALC output to the logfile with /errorlog produces bad JSON

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6314]
**Describe the bug**
ALC has an argument `/errorlog` that allows us to make ALC emit all diagnostics to this file as a JSON. This JSON however in certain cases is not valid JSON as it does not always escape characters like `"`. 

There might be other cases, but one I have noticed is the rule `AW0011`. In this case the value of `title` is `"Add PromotedOnly="true" to some ...`. Note that the double-quotes on `true` are not escaped and this causes the JSON to be invalid. the field `fullMessage` contains a similar message. In this case however, the double quotes are correctly escaped.

**To Reproduce**
Steps and to reproduce the behavior:
1. Open any project
1. Create a page an create a single action, make it promoted. This causes the rule AW0011 to trigger.
1. Run ALC.exe with the /errorlog parameter and specify a file.
1. The produced JSON is invalid.

``` AL Code to reproduce the issue ```

**Expected behavior**
The JSON file should be valid and reserved characters correctly escaped.

**Screenshots**

**5. Versions:**
 - AL Language: 6.1.362735
 - Business Central: 7.1

**Comment by DavidFeldhoff** [comment]
I experienced the same with AW0011. 
But AL0685 has another issue. There the fullMessage-property contains a line break which isn't allowed as well.
![image](https://user-images.githubusercontent.com/53570297/120482862-d7146d80-c3b1-11eb-9c61-8a7856c4c981.png)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26786 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
