### ISSUE TITLE
Extra key in system tabel: Field

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/AL#6318]
In code we need to loop through the active (normal) fields in an table.

for example:
var
   Field: Record "Field";
begin
   Field.SetRange(TableNo, x);
   Field.SetRange(Enabled, true);
   Field.SetRange(ObsoleteState, Field.ObsoleteState::No);
   Field.SetRange(Class, Field.Class::Normal);
end;

can there be a key added for these fields in the field table?

or can the codecop rule .AL(AA0210) be suppressed for table:Field?

**Comment by dtkb** [comment]
can suppress via `#pragma rule disable`/`restore` in the meantime

tbh I usually turn off this warning because it's simply absurd to imagine that everything we might ever filter on in code should have a key created for it; some things are filtered so rarely that it's not worth the write/storage overhead to maintain infrequently used keys.

**Comment by PhDuck** [comment]
If the rule is to ensure there is good SQL indexes for the things AL code is querying, then the table "Field" should be exempted since it is virtual and it therefore doesn't map directly to SQL.
I would suspect that all virtual tables should be ignored by this rule.

**Comment by EmilDamsbo** [comment]
The same issue is tracked and accepted in #6959, closing this.
