### ISSUE TITLE
Missing method Keys() in HttpHeaders data type

### ISSUE THREAD

**Issue by Drakonian** [microsoft/AL#6319]
**Describe the bug**
1.Looks like the important method for HttpHeaders data type is missed, it is "Keys", this method should return a list of keys for current HttpHeaders. This is important for reading each header key/value.

2.Strange, why existing method **GetValues** from **HttpHeaders** returns **array** of values instead of **list** of values.

You can see example below:

``` 
procedure HttpHeadersLoop()
    var
        httpResponseMessage: HttpResponseMessage;
        contentHeaders: HttpHeaders;
        ListOfKeys: list of [text];
        ListOfValues: list of [Text];
        HeaderKey: text;
    begin
        contentHeaders := httpResponseMessage.Headers;

        //Should return list of keys for current HttpHeaders
        ListOfKeys := contentHeaders.Keys();

        foreach HeaderKey in ListOfKeys do begin
            //read each httpheader key
            //function GetValues should return List of Values, not array
            contentHeaders.GetValues(HeaderKey, ListOfValues);
        end;

    end;
 ```

 - Business Central: Any version of BC
 - AL Language: v6.1.362735

**Comment by bjarkihall** [comment]
Hi, is there any way I can get the key-value pairs of HttpHeaders in AL?

The AL type has this API:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-data-type

Which seems to wrap the equivalent DotNet type:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders?view=net-5.0

But there's no alternative to the **GetEnumerator** method, which would normally enable us to inspect which headers are in the HttpHeaders collection, which is important for diagnosing responses.

Trying to use foreach to inspect if there's a valid type for a foreach yields this message:
_"A ‘foreach’ statement can only be used with an expression of an enumerable type."_

Trying to implicitly cast the headers to another type like Dictionary yields this:
_"Cannot implicitly convert type 'HttpHeaders' to 'Dictionary of [Text, Text]' ._

Is there a utility codeunit in the BaseApp or some method available that I haven't thought of?
The only way to get this information seems to be by using some kind of DotNet interopability hack, which isn't supported in the cloud.
Is it planned to provide Keys/Values methods for this data type like Lists/Dictionaries have?

**Comment by dtkb** [comment]
I would guess it is planned, since the `bug` label was added.

Currently, there's no way to get the keys, and the way to get the values looks broken (it takes an `Array` of unspecified dimension, which is not a thing that exists in AL, so you can't declare one to pass it!), and I would agree that both need fixing.

**Comment by f4n0** [comment]
any news on this topic? 
in order to workaround the arrays, it can be used list/dictionary right?

**Comment by bjarkihall** [comment]
You can do something like this (this is designed to return empty string even on errors but you can handle it as you like):

```al
procedure GetHeader(h: HttpHeaders; k: Text) t: Text
begin
    if TryGetHeader(h, k, t) then;
end;

[TryFunction]
local procedure TryGetHeader(h: HttpHeaders; k: Text; var t: Text)
var
    a: array[1] of Text;
begin
    // Note, it's not possible yet to receive a List of all headers (https://github.com/microsoft/AL/issues/6319)
    if not h.Contains(k) then
        exit;
    if not h.GetValues(k, a) then
        exit;
    t := a[1];
end;
```

But it assumes that you know which keys should be present (which you don't when you're trying to e.g. log a response).
It also assumes that the key only has 1 value, but sometimes a key can have multiple values, according to the DotNet implementation. Can't we just get the values as they are actually defined in the HTTP request/response - if they are comma-separated we can just split it ourselves, right? Even JsonObject would suffice if it needs to remain a certain structure that's supported by AL.

And the following remains:
1) There's still no way for you to get the **Keys** of HttpHeaders.
2) The GetValues API should enable you to use a list - or at least a way to **Count** the values and retrieve a value of some **Index**.
3) I think the only workarounds are by passing the HttpHeaders to a custom DLL and extracting the NameValueCollection into something you can read when you return it to AL - this would not work OnPrem since it requires DotNet interop in AL.

Can this please be addressed or can we at least know what's preventing this from being fixed?
I know it would make sense to implement something like a NameValueCollection in AL but I think the HttpHeaders wrapper can manage with a simple Dictionary/List interface until/if collections (or nested Dictionaries/Lists) ever finds their way to the language.

**Comment by Drakonian** [comment]
Any updates?)

**Comment by kine** [comment]
I support this issue. Right now I am trying to call some AWS services and I need to create correct authorization signature for the request, which includes headers attached to the request. I am unable to correctly enumerate them, nor get their values in some normal manner (not by using fixed array for unlimited array parameter). Most of our  work today is integrating BC with external systems and the whole HTTP "framework" is critical in this. We need to have the support on these "glitches".

Thanks for any progress on this.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 29165 and VS Code Extension Version 3.0.107312. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
