### ISSUE TITLE
Automatic ToString call-up

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#634]
If you enter an integer or similar in messages and errors etc. a ToString should be called automatically in the background. Analog to a console. WriteLine (a);

You should not need a FORMAT

![wihoutformat](https://user-images.githubusercontent.com/16351673/30158256-fab142ca-93c4-11e7-9d3a-81e19c2b82ca.PNG)

![format test](https://user-images.githubusercontent.com/16351673/30158268-026c82b8-93c5-11e7-87fc-ae2e7cde07e6.PNG)

**Comment by kaspermoerch** [comment]
You can skip the `Format` if you do like this:

`Message('This is my value: %1',MyInteger);`

**Comment by SirBETE** [comment]
It is also usefull to add support for tables.
When calling ToString on a table, the ToString function would convert the primary key fields caption and values into a string.

example:
`message(SalesHeader);`
Should give
`'Document Type: Order, No.: SO00001'`

Perhaps adding support for overloading it, so we could add other fields to it.
Instead of showing the "Entry No." on the "Cust. Ledger Entry", we could show the "Document Type" and "Document No.".

**Comment by kalberes** [comment]
![image](https://user-images.githubusercontent.com/12760483/195414895-ffbdc1ad-c28b-4410-ac36-9044b4c0dddc.png)
