### ISSUE TITLE
Issue with Report Preview

### ISSUE THREAD

**Issue by maheshroyal3334** [microsoft/AL#6343]
**Describe the bug**
Getting an error while running a report Error message "An error occurred while trying to display the report" 

Facing this error for all Standard and Custom reports in web client. But in windows client its is executing.

Version: BC14 CU12, OnPrem and Servers are configured on Azure

**To Reproduce**
:
1. Go to -- 
1. Purchase Orders
2. Print
3. Click Preview 
'
**Expected behavior**
A report need to be printed.
But Getting an error  like below,

**Screenshots**
![Report Error](https://user-images.githubusercontent.com/75490003/101192984-e2484400-3681-11eb-9230-1ccd238703e7.JPG)

**Comment by thpeder** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

For more details please read:
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
