### ISSUE TITLE
AS0092 Warning: please don't throw it

### ISSUE THREAD

**Issue by demiliani** [microsoft/AL#6358]
AL Language Extension version 6.1.381232 with AppSourceCop analyzer enabled now signals a new AS0092 warning related to the missing applicationInsightKey property in app.json.
This should not be a warning, because this option is totally free to use or not for ISVs.

**Comment by Drakonian** [comment]
I agree. It is strange that this is a warning...

**Comment by qutreson** [comment]
This is reported as a warning because we want to emphasize that using app insights to gather telemetry from extensions is a good practice that helps troubleshooting a broad range of issues, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/telemetry-overview. As it is a warning, it won't fail your AppSource submission when not specified. If you do no see any value in this rule, you can use a ruleset to suppress it in your development environments/pipelines: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-rule-set-syntax-for-code-analysis-tools

**Comment by aipungggi** [comment]
It is a bit deceptive as it should be an Info at least not a Warning and the message says "**must** specificy" which is not true.
