### ISSUE TITLE
Invoking AL from control add-in does not work if there is a Message call during system initialization

### ISSUE THREAD

**Issue by vjekob** [microsoft/AL#6370]
# Symptoms

If there is a `Message` call inside an `OnAfterInitialization` event subscriber, any control add-ins on the page that was loading won't call AL during `InvokeExtensibilityMethod` invocations.

# More info

I've created a repo that illustrates the problems with minimum code. The `README.md` file there explains the entire setup and how to repeat:
https://github.com/vjekob/bc170ctrladdinbug

**Comment by vjekob** [comment]
I don't mean to be rude, but did anyone even take a look at this? This has been a very breaking change for our customers.

**Comment by jehelles** [comment]
I am investigating the issue, but is not clear to me from the bug report what version this used to work in?

**Comment by vjekob** [comment]
> I am investigating the issue, but is not clear to me from the bug report what version this used to work in?

It's BC170, Business Central 2020 Release Wave 2 Update.

**Comment by atoader** [comment]
I think Jesper's question is: did this work in any version of Business Central before 17.0?

**Comment by vjekob** [comment]
Yes :) It was broken in BC 17.0.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21747 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by vjekob** [comment]
Thanks, Jesper and the team!
