### ISSUE TITLE
Support surrounding selected text with parenthesis

### ISSUE THREAD

**Issue by jwikman** [microsoft/AL#6377]
**Describe the bug**
When you have selected text in VSCode and enters a parenthesis '(' you would expect the selected text to be surrounded with '(' and ')' as it does with other languages in VSCode.

This becomes very annoying when you are switching between different languages in VSCode.

The same functionality could be added for [ and {, but that is not as common scenario.
This is implemented for " and ', so I would assume it would be quite easy to add ({[ to this?

**To Reproduce**
Steps and to reproduce the behavior:
1. Write any AL code in VSCode
2. Select the the AL code ("MyDec > 0" in the sample below)
3. Press (
4. Now your selected text is overwritten with (

``` if MyDec > 0 then ```
becomes 
``` if ( then ```
instead of the expected result
``` if (MyDec > 0) then ```

**Expected behavior**
The text that is selected when pressing ( should be surrounded with ( and ). 

**5. Versions:**

 - AL Language: 
v6.1.381323

**Comment by jwikman** [comment]
@atoader please make sure that someone implement this little feature that gets me cursing every time I discover that it's not yet implemented, ie. when I overwrite my condition with a (. 

This is a very small thing to implement, just add 
```
        ["(", ")"],
        ["[", "]"],
        ["{", "}"]
```
to the surroundingPairs array in al.configuration.json.

Right now I'm patching this myself. Just to have happier life when hacking AL ;-)

**Comment by kalberes** [comment]
Ok, I will add it. Thanks for the fix.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22407 and VS Code Extension Version 7.0.420929. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
