### ISSUE TITLE
Multiple Report objects can refer to / update the same Layout, causing error/race/unpredictable updates

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#6401]
**Describe the bug**
If multiple AL Report objects specify the same `RDLCLayout` (and presumably `WordLayout`, although I didn't test that myself), it seems to be a coin-flip whether

* we get an error that the RDL file is already 'opened by another application' (presumably another instance of the compiler)
* the build succeeds, but who knows which one of them actually 'wins' and has its updates applied when the dust settles!

This is obviously wrong; such a condition of a layout specified in more than one object should be an error.

**To Reproduce**
Make 2 reports, give them the same `Layout` but different `columns` or other properties that would manifest in the layout, and then try building a bunch of times. You should see that sometimes one of the AL reports 'wins' and sometimes the other, and/or sometimes we get a build error because 2 compiler instances were trying to update the same layout.

**Expected behavior**
This should be a compiler error because it makes no sense to have 2 AL Reports in the same project that will try to update the same layout. Erroring if the developer accidentally let 2 objects target the same layout will avoid unwanted changes from old AL objects breaking production RDL layouts, and avoid developers becoming confused about why that's happening and having to manually search for duplicated layout filenames in AL files.

**5. Versions:**
 - AL Language: 6.1.352568

**Comment by BazookaMusic** [comment]
This is a bug, we should have a deterministic behavior for this. We should either block the use of the layout by two or more reports or create a copy for each object.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.15279.0 and VS Code Extension Version 13.0.924484. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.15812.0 and VS Code Extension Version 13.0.934715. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
