### ISSUE TITLE
Why not add a 4th optional parameter to MODIFYALL keyword

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#6402]
I 've always wondered why the **ModifyAll()** keyword has an optional third Parameter to execute the _OnModiy()_ trigger and does not have another to optionally execute the _OnValidate()_ trigger of the field.

**Actual**:
_procedure ModifyAll(Field: Joker, NewValue: Joker, [RunOnModifyTrigger: Boolean])_

**Suggested**:
_procedure ModifyAll(Field: Joker, NewValue: Joker, **[RunOnValidateTrigger: Boolean]**, [RunOnModifyTrigger: Boolean])_

In some scenarios with a few records like this one, it could dramatically reduce the number of lines of code needed...

**Before (now)**:
```javascript
if TestMethodLine.FindSet( true ) then
repeat
  TestMethodLine.Validate( Result, TestMethodLine.Result::" " );
  TestMethodLine.Validate( Run, NewRunValue );
  TestMethodLine.Modify( true );
until TestMethodLine.Next() = 0;
```

**After**:
```javascript
TestMethodLine.ModifyAll( Result, TestMethodLine.Result::" ", true );      // OnValidate() = true 
TestMethodLine.ModifyAll( Run, NewRunValue, true, true );                  // OnModify() = true , only in last consecutive ModifyAll()
```

**Comment by dtkb** [comment]
I think that's simply because validation and modification are considered two separate events, usually happening in that order - rather than a modification function also being able to trigger validation first.

You also definitely can't change the signature like that, so the 3rd argument now means something totally different, because that would horribly break tonnes of existing code.

**Comment by JavierFuentes** [comment]
Regarding breaking tons of existing code, I think that the third parameter of ModifyAll () has never been so popular, in Navision first, nor now in Business Central ...

The main reason is precisely because it does not execute what is expected of it ... or at least, not everything that is expected of it.

Doing a simple search in VSCode, **in the standard BC17.0 code there are 856 occurrences of that instruction and less than 30 use the third parameter (with value TRUE)... 3.5%**.

**In any case, backward compatibility would simply be ensured by adding it as a fourth parameter instead of a third ...**

Proposing it as a third parameter was simply because it makes more sense for the developer and not keeping that technical debt.

**Comment by dtkb** [comment]
Yeah, adding it as a 4th parameter would enable much shorter/nicer code in various situations where we need to repeat/validate/modify/next on a single field. And it would make `ModifyAll()` actually useful for developers who call `.Validate()` by default to avoid skipping validation logic. I tend to avoid `ModifyAll()` now because I call `Validate()` as much as possible, to avoid things getting missed later, unless I really know what I'm doing (which I'm not sure is possible ;-) )

**Comment by atoader** [comment]
Hi! This issue is beyond the scope of the AL language and development tools. Please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by JavierFuentes** [comment]
Done:

https://experience.dynamics.com/ideas/idea/?ideaid=d0bd0ffd-6889-eb11-8ced-0003ff45a07d
