### ISSUE TITLE
Image previews are missing

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6412]
TSIA really. We used to get previews in the Intellisense completion popup for e.g. `action` `Image` property, but now we don't:

![image](https://user-images.githubusercontent.com/63455896/104312636-cb8ddc00-54ce-11eb-8856-545466e5a83a.png)

AL Language 6.1.396068 but was occurring on some other recent version(s) also, though unsure which specific one(s).

Hovering over an image name after selecting it does show a preview, but the auto-completion does not, and this is a real slowdown when trying to pick a relevant image.

**Comment by qutreson** [comment]
@dtkb what happens if you hover on the suggestion? You should be able to see an arrow that expends the tab where the image is displayed. VS Code then remembers whether it should be expended by default or not. 

![ImageRenderingPanel](https://user-images.githubusercontent.com/31541422/104352600-2a6f4780-5507-11eb-8945-5450242ba5d0.gif)

**Comment by dtkb** [comment]
Thanks! You are right. It looks like somehow I had hidden the extra popup and not realised.

![image](https://user-images.githubusercontent.com/63455896/104352881-23443b80-54ff-11eb-9266-78f6ff555352.png)

![image](https://user-images.githubusercontent.com/63455896/104352895-2808ef80-54ff-11eb-8972-c7a9697017f4.png)
