### ISSUE TITLE
Code like `if FindFirst() then;` gets wrong line-break/indentation within `case` block

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6429]
**Describe the bug**
One-liners like `if FindFirst() then;` are formatted differently/worse when inside a `case` body.

**To Reproduce**
Have an expression like `if FindFirst() then;` - i.e. one where the body is empty, because the point of the statement is only to consume the return value and avoid BC throwing an error.

See how it is formatted conventionally/nicely when on its own, but then when put into a `case` option it goes askew and looks different and worse: the `;` is put on its own line, indented.

**Expected behavior**
No difference in formatting whether or not the statement is within a `case` block. There is notionally no body of such `if` statements, so there's nothing to indent, and just having `;` on a line is not useful and looks ugly.

I guess this might be tripping on a heuristic that exists to put `;` on its own line when used after a `case` label - something that _is_ handy IMO as it clearly states '_I'm doing nothing_' - but we don't need to state that in lines like `if FindFirst() then;`.

**Screenshots**
Good, without `case`:
![image](https://user-images.githubusercontent.com/63455896/105212987-05518900-5b46-11eb-9293-ff344e91c72b.png)

Bad, within `case`:
![image](https://user-images.githubusercontent.com/63455896/105213028-13070e80-5b46-11eb-988e-e299b44c1162.png)

What is expected in the latter situation:
![image](https://user-images.githubusercontent.com/63455896/105213074-21552a80-5b46-11eb-999f-30258d09fe95.png)

**5. Versions:**
 - AL Language: 6.1.397164

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42620 and VS Code Extension Version 10.0.642137. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
