### ISSUE TITLE
ALC 7.0 produces apps that do not run correctly on BC14.10

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6448]
**Describe the bug**
I know this may be early, but still: when using ALC7.0 (from master) to compile an app, the package that is produced is not working correctly on BC14 (tested on CU10 and CU12). I have tested this only by compiling the app through VSCode, but it most probably also applies to ALC.exe running via CLI. The issue is basically:
- Create App "Lib" which contains a Codeunit which contains function with a parameter of type Record.
- Create App "UI" which has a dependency on App "Lib" and executes the aforementioned function
- An error is raised: "The function ID [SomeID] was called. The object of type [CodeunitID] does not have a member with this ID."

This error disappears if I compile the app with ALC3.0 or ALC6.1.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create app "Lib", create a Codeunit, create a function with 1 parameter of type "Cust: Record Customer"
2. Create app "UI" that has a dependency on app "Lib"
3. Create a page extension that adds an action to the customer list and call the function in the Codeunit from app "Lib".

**AL Code to reproduce the issue**
I have placed the code to reproduce this issue on a dropbox folder (see below). My "Lib" app is "ALProject4" and "UI" is "ALProject5". I have also included the compiled version of those apps. `working_v3` was compiled with ALC3.x, `failing_v7` was compild with ALC7.0.

https://www.dropbox.com/sh/3jti86kgc3bftwu/AAA905Ma5242ppS9r6EFa_pha?dl=0

**Expected behavior**
I expect apps compiled with ALC7.0 to fully backward compatible.

**Screenshots**
![image](https://user-images.githubusercontent.com/8897936/106643958-bdd9ec80-658a-11eb-8398-0e4faf42a54d.png)

**5. Versions:**
ALC v7: 7.0.xxxxx (taken from master)
ALC v3: 3.0.193882

**Comment by atoader** [comment]
Thanks for raising this! This is a must-fix.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21804 and VS Code Extension Version 7.0.411812. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
