### ISSUE TITLE
Simply more consequence

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#645]
I think it's time to use " instead of '. The reason is that it's a bit irritating to see JSON and co. and all of a sudden you have to change. As bad as , and ;. In attributes (,) and parameters (;) both should be , . And { and } instead of beginning and end.

Simply more consequence, which people come when you explain it to them the new syntax otherwise really confused.

As already mentioned in Issue #63 and #48.  Just by looking at the likes you can see that it's about time.

**Comment by StanislawStempin** [comment]
To address several things you mentioned here:
1. String literal quoting varies between languages. This is just a matter of choice and for code conversion reasons it's better for us to stick to single quotes. We will not change that part and can close this part of the discussion.

2. Attributes are actually consistent with procedure calls. In attributes you are providing parameter values and not declaring the parameters, therefore the use of comma

3. #48 was already addressed by making semicolon at the end of the procedure optional

4. Replacement of { } would be a cascading language change. For example what to do with var declarations? A natural expectation after we have curly braces would be to move to C# var declaration syntax as well. This then brings a cascading expectation of changing things like case statement and repeat until statements to match C# as well. Let's continue this discussion under #63 instead of opening new issues. As a general comment, an argument of "let's be more similar to C#" is not strong enough in itself to motivate deep language change. 

5.  Usage of semicolon instead of a comma in procedure declaration parameter lists - let's also continue this discussion in #63. As ajkauffmann pointed out such a change would need to be made for all parts of the language that currenly use semicolon as the separator.

**Comment by Gallimathias** [comment]
I'm sorry about the double issue. :/.

We should really put it all together under #63, that was stupid of me.
