### ISSUE TITLE
AA0198 should also observe procedure parameters

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#6488]
**Title**
AA0198 should also observe procedure parameters

**Description**
CodeCop Rule AA0198 helps us to not use identical names for local and global variables. But currently it only observe global and local variables and not the paramters of an procedure.

**Reason for the rule**
If parameters have the same name as global variables, this can lead to the same problems as if local and global variables have the same name.

**Bad code sample**
Example of what bad code the rule should catch:

```AL
codeunit 50100 MyCodeunit
{
    procedure MyProcedure(VarName: Boolean)
    begin
    end;

    var
        VarName: Boolean;
}
```

**Good code sample**
Example of what code should look like:

```AL
codeunit 50100 MyCodeunit
{
    procedure MyProcedure(VarName: Boolean)
    begin
    end;

    var
        AnotherVarName: Boolean;
}
```

**Comment by fvet** [comment]
Seems to be fixed in runtime 9.2 by the new AA0244 rule

**Comment by dnpb** [comment]
AA0244 also catches event publisher arguments though, which IMO aren't helpful to diagnose, as since there cannot be a body of the publisher, we can't possibly get confused and use the wrong local vs global...!

**Comment by dsaveyn** [comment]
> AA0244 also catches event publisher arguments though, which IMO aren't helpful to diagnose, as since there cannot be a body of the publisher, we can't possibly get confused and use the wrong local vs global...!

We are also running into this. For example the following event in a page:
![image](https://user-images.githubusercontent.com/92365904/174039483-c6b07d97-0bb5-4533-aa4e-e7159e5f4538.png)

The only way to solve this is obsolete the event and create a new one...

**Comment by dnpb** [comment]
=> https://github.com/microsoft/AL/issues/7081

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42332 and VS Code Extension Version 10.0.640052. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by NKarolak** [comment]
@JesperSchulz I hope that this will be downgraded into AL Language 9.2.x as well ...?

**Comment by JesperSchulz** [comment]
Yes, it releases with 9.2.639414 as well.
