### ISSUE TITLE
Implement PTE0004 in CodeCop or AppSourceCop

### ISSUE THREAD

**Issue by jwikman** [microsoft/AL#6503]
**Title**
Implement (or move) PTE0004 in other CodeCops than PerTenantExtensionCop

**Description**
Please implement the PerTenantExtensionCop Rule PTE0004, "Table definitions must have a matching permission set", in any other Code Analyzer than PerTenantExtensionCop

**Reason for the rule**
We've had a case where a new table in an AppSource app was not added to any PermissionSets, causing issues when this goes into production.
Manual testing should have caught this, but it didn't for different reasons...
But having this rule available also for AppSource app would make sense, I believe. It does not really matter (for us) if it's moved to CodeCop or if it's duplicated to AppSourceCop.
We cannot enable only PTE0004 for AppSource apps without having all other PerTenantExtensionCop rules as well, giving us a administrative nightmare of disabling rules when they are added to PerTenantExtensionCop...

**Bad code sample**
Example of what bad code the rule should catch:
A table exist that does not exist in any permission set file.

**Good code sample**
Example of what code should look like:
All tables should exist in a permission set file, or the warning should be suppressed with a pragma declaration on those rare cases where the table should not be in a permission set.

**Good and bad practices for fixing the rule**
N/A

**Remarks**
Another, more flexible, solution to this would be to give us the possibility to configure an app to use only selected rules from a Code Analyzer. Eg. I want PTE0004 to be used in our AppSource apps, but no other PTE rules.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36654 and VS Code Extension Version 9.0.587938. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
