### ISSUE TITLE
DeleteAll() and ModifyAll() with RunTrigger=true don't use the record instance's global variables

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6515]
**Describe the bug**
The title says it all. I set a global boolean in a record variable to `true`, and then only allow modification in `OnModify()` if said boolean is `true`. This works if `OnModify()` is invoked via calling `Modify(true)`.

It does **not** work if invoked via calling `ModifyAll(SomeField, SomeValue, true)`. It should, shouldn't it?

**N.B.** This might affect other `*All()` methods. Please check and address those too if required.

**To Reproduce**
1. Set a global variable in a record instance, to a non-zero/non-default value
2. Call `ModifyAll()` with `RunTrigger := true`
3. See that when `OnModify()` fires from `ModifyAll()`, the global variable has its zero/default value, not the one you set.

```al
tableextension 50100 Customer extends Customer
{
    var
        CanModify: Boolean;

    internal procedure SetCanModify(NewCanModify: Boolean)
    begin
        CanModify := NewCanModify;
    end;

    trigger OnModify()
    var
        Err: Label 'Someone set up us the bomb';
    begin
        if not CanModify then
            Error(Err);
    end;
}

pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
    begin
        Customer.FindFirst();
        Customer.SetCanModify(true);

        Customer.Modify(true); // respects above call to SetCanModify()

        Customer.SetRecFilter();
        Customer.ModifyAll(Name, Customer.Name, true); // does not!!!!!
    end;
}
```

**Expected behavior**
I expect that any functions invoked on a particular record variable instance will see the same global variables as each other, set on that instance - not that `*All()` will somehow end up calling triggers on a different instance with its own, different global variable values.

(Even if this were meant to work like pages, where each record row has its own copy of the set of global variables, that doesn't make sense here for tables, and it can't be the case anyway because as you can see I deliberately call to modify the same customer as I found.)

**5. Versions:**
 - AL Language: 6.6.425415
 - Business Central: GB Business Central 17.4 (Platform 17.0.21485.22555 + Application 17.4.21491.21531)

**Comment by dtkb** [comment]
Does anyone think this is likely to get fixed any time soon? It's a pain and means writing less efficient (in terms of SQL and number of lines) code.

I can now confirm it's broken for `DeleteAll()` too:

```al
tableextension 50100 Customer extends Customer
{
    var
        CanDelete: Boolean;

    internal procedure SetCanDelete(NewCanDelete: Boolean)
    begin
        CanDelete := NewCanDelete;
    end;

    trigger OnBeforeDelete()
    var
        Err: Label 'Who ya gonna call?!?';
    begin
        if not CanDelete then
            Error(Err);
    end;
}

pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
    begin
        Customer.FindFirst();
        Customer.SetRecFilter();
        Customer.SetCanDelete(true);
        Customer.DeleteAll(true); // bust.
    end;
}
```

and still as of

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.1.441584
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by db-bc** [comment]
It seems this was always a problem: https://dynamicsuser.net/nav/f/developers/11613/global-variables-on-record

> pdj over 16 years ago
> The problem is use of DELETEALL. It initiates all global variables for each record. Instead you will have to make you own FIND-REPEAT-SetGlobal-DELETE(TRUE)-NEXT loop.

So, is this a bug, or must it be treated as an unfortunate fact of life due to its age? If the latter, can this trap be clearly documented? If the former, can we get an idea of when we might expect global variables to persist through `*All()` calls?

**Comment by dnpb** [comment]
Hello? Is there anyone from MS out there?

**Comment by NKarolak** [comment]
@thloke was very busy here recently ;-)

**Comment by thloke** [comment]
Yes, we're trying to get through our backlog of issues. (: ...we have a lot to get through, unfortunately. ):

Now looking at this issue specifically - it seems like this is an issue on how triggers are handled in the server runtime rather than something we can address from the compiler side. We'll need someone from the runtime team to look at it. This means:

1. We'll need them to pass judgement on if it is a bug or not.
2. I can't give an estimate on when they can fix it.
3. Technically it's also out of scope of this repository.

Your best bet to get attention for this is to raise a support case or collaborate request. Considering the age of the issue, it almost certainly needs some external action to be addressed. 

Sorry that I can't give you a better resolution than "try another avenue". I can raise it with the team internally, but they'll need more input to prioritise an old bug.

As far as documentation goes, that I can do for you. :) ..I will accept this bug on our team with the scope of just fixing the documentation.

**Comment by dnpb** [comment]
I have filed on Partner Center as ticket 2112070040003329

**Comment by NKarolak** [comment]
@dnpb Please keep us updated regarding your support case :-)

**Comment by dnpb** [comment]
Will do! So far I have this:

> Thank you for reporting this, and for providing repro. As development suggest in the Github link, I will take it to them for more analysis. I did repro on BC14 as well, using C/AL, so the behaviour is not new, and I suspect that it may be by design, or if not then high risk to change, as it can affect unknown existing installations. But I will get at least some input from development, and then get back to you,

**Comment by dnpb** [comment]
Here's today's reply from Lars at MS:

> I have some input from development now. This behaviour dates back at least to 2007. To change it now would be a breaking change with unknown consequences. As a workaroud we can use MODIFY instead. I know that a workaroud for MODIFYALL to not use MODIFYALL is a pretty lousy workaroud, but it is a lesser risk than changing platform behaviour.
> Sorry I can't get you a better solution to this but I hope you also understand this view.

and my reply:

> I thought that might be the case, and you might not be able to change it without risking unexpected breakage (or fixing? 😊) in other developers’ code.
> This should definitely be clearly documented for Record.ModifyAll(), Record.DeleteAll() and RecordRef.DeleteAll() though – to avoid other developers getting confused like me, by knowing in advance that their global variables will be ignored/initialised by said methods. 
> At https://github.com/microsoft/AL/issues/6515 Thaddeus said they would accept it on that side to fix the docs, so I guess that’s your side done? 😉

**Comment by NKarolak** [comment]
It has now been documented as "by design" in the docs:
![image](https://user-images.githubusercontent.com/34504100/151553865-7c43680c-33a1-43dc-9dc0-944c01c67b6d.png)

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-deleteall-method#remarks
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-modifyall-method#remarks

**Comment by dnpb** [comment]
Great! Thanks all.
