### ISSUE TITLE
Error al actualizar a la versión 17.2 de Business Central.  Sync-NAVApp -ServerInstance BC170 -Name "Base Application" Sync-NAVApp : Table Customer :: The field 'EORI Number' cannot be located. Removing fields is not allowed.

### ISSUE THREAD

**Issue by Nuevo207** [microsoft/AL#6524]
Buenas.

Llevo varios días atascado en la tarea 4 del punto 8 del manual de docs para actualizar la versión BC14 a la versión BC17. (la 17.2). Esta es la página web: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v17.

Me da errores en los campos eori y en otros muchos campos ya que no se pueden localizar ni tampoco se pueden eliminar. ¿Alguien me puede ayudar con este tema, por favor? Muchas gracias.

Sync-NAVApp : Table Customer :: The field 'EORI Number' cannot be located. Removing fields is not allowed.
Table Vendor :: The field 'EORI Number' cannot be located. Removing fields is not allowed.
Table Intrastat Jnl. Line :: The field 'Location Code' cannot be located. Removing fields is not allowed.
Table VAT Report Header :: The field 'VATGroup Return' cannot be located. Removing fields is not allowed.
Table VAT Report Header :: The field 'VATGroup Status' cannot be located. Removing fields is not allowed.
Table VAT Report Header :: The field 'VATGroup Settlement Posted' cannot be located. Removing fields is not allowed.
Table VAT Statement Report Line :: The field 'RepresentativeAmount' cannot be located. Removing fields is not allowed.
Table VAT Statement Report Line :: The field 'GroupAmount' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'VATGroup Role' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'ApprovedMembers' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'GroupMember ID' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'GroupRepresentative API URL' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'AuthenticationType' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'UserName Key' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'WebService Access Key Key' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'GroupRepresentative Company' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'ClientID Key' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'ClientSecret Key' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'AuthorityURL' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'ResourceURL' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'RedirectURL' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'GroupSettlement Account' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'VATSettlement Account' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'VATDue Box No.' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'GroupSettle. Gen. Jnl. Templ.' cannot be located. Removing fields is not allowed.
Table VAT Report Setup :: The field 'VATGroup BC Version' cannot be located. Removing fields is not allowed.
En línea: 1 Carácter: 1
+ Sync-NAVApp -ServerInstance BC170 -Name "Base Application"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Sync-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC170/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.SyncNavApp

**Comment by thloke** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.  

 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel. 

 

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company. 

 

For more details please read: 

https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 

https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions#i-found-an-issue-on-nav-2018-what-do-i-do
