### ISSUE TITLE
BC2021w1: permissionset(extension)

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#6527]
Hi there, 
I am preparing our VS Code extension that manage object names and IDs across multiple extensions for BC2021w1. I need to update the mapping snippets - object types and add new object types for AL files synchronization.

**Describe the bug**
The snippet for permissionsetextension generates an object type called "permissionset" (the same as permissionset itself). I don't know whether it is intended behaviour (I hope not). It is different from all other object types (unlogical), also more complicated for me to rewrite all the mapping when synchronizing AL objects with our object database...

PermissionSetExtension
``` 
{
    "Snippet: PermissionSetExtension": {
        "prefix": "tpermissionsetextension",
        "body": [
            "permissionset ${1:Id} ${2:MyPermissionSet} extends ${3:MyTargetPermissionSet}",
            "{",
            "\tIncludedPermissionSets = ${4:PermissionSet};",
            "\tPermissions = ",
            "\t\t${5:ObjectType} ${6:ObjectName} = ${7:ObjectPermissions};",
            "}"
        ],
        "description": "Snippet: Permission set extension"
    }
}
```

PermissionSetExtension
``` 
{
    "Snippet: PermissionSet": {
        "prefix": "tpermissionset",
        "body": [
            "permissionset ${1:Id} ${2:MyPermissionSet}",
            "{",
            "\tIncludedPermissionSets = ${3:PermissionSet};",
            "\tPermissions = ",
            "\t\t${4:ObjectType} ${5:ObjectName} = ${6:ObjectPermissions};",
            "}"
        ],
        "description": "Snippet: Permission Set"
    }
}
```

**Expected behavior**
tpermissionsetextension should generate object permissionsetextension not permissionset 

**5. Versions:**
ms-dynamics-smb.al-7.0.419358 
ms-dynamics-smb.al-7.0.426055

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23462 and VS Code Extension Version 7.0.434447. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
