### ISSUE TITLE
ObsoleteState = Removed/Pending don't cause error/warning if used in fieldgroup

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6540]
I have marked this field as Removed:
![image](https://user-images.githubusercontent.com/63455896/111621346-cbb49b80-87df-11eb-906d-84d5f9fc62de.png)

but I didn't yet remove it from the `fieldgroups`, and yet I don't get warned that it should be removed from those:
![image](https://user-images.githubusercontent.com/63455896/111621442-e8e96a00-87df-11eb-84e3-882e10d8f0dd.png)

When the `fieldgroup` is rendered, it seems the `Removed` field is ignored, so OK... but then I'd expect the dev to get an error that they are using a field that (a) is removed and (b) will not be shown anyway.
![image](https://user-images.githubusercontent.com/63455896/111621828-56959600-87e0-11eb-87f0-879565de4bd2.png)

If I change to `ObsoleteState = Pending`, there is still no warning, but I'd expect one, for the obvious reason that we don't want users getting too accustomed to the drop-down showing a field that is deprecated.

**Comment by NKarolak** [comment]
@kalberes @qutreson Could you please give this bug a higher priority? We need to be able to rely on AL0432.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36087 and VS Code Extension Version 3.0.172401. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by NKarolak** [comment]
@JesperSchulz 
> VS Code Extension Version 3.0.172401

What VS Code Extension are you referring to? The current AL Language version is already 8.3.570094.

**Comment by JesperSchulz** [comment]
Yeah, we've got some issues with reporting the right version number at the moment. Please momentarily disregard the version information. We're on it :-)
