### ISSUE TITLE
AA0072 And Query

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/AL#6550]
**1. Describe the bug**
For Query Objects Code Cop Rule AA0072 does not take into account the prefixes from AppSource Cop.  

**2. To Reproduce**
Add Query with a prefix that is in AppSource Cop.  Use the Query as a variable without the AppSource Cop Prefix

**3. Expected behavior**
No Code Cope Warning.  Query Objects should also respect the prefixes.  

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring
![image](https://user-images.githubusercontent.com/32099690/112171174-d8a30780-8bb0-11eb-8777-975d599fbb93.png)

**5. Versions:**

- AL Language: 7.0.429144
- Visual Studio Code: 1.54.3
- Business Central: 
- List of Visual Studio Code extensions that you have installed:

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32935 and VS Code Extension Version 9.0.548258. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
