### ISSUE TITLE
OAuth process with SaaS business central Odata Services.

### ISSUE THREAD

**Issue by srinivasdes** [microsoft/AL#6553]
Hello,

we are Using OAuth to Authorize Business Central Web Services (OData and SOAP). Part of this  we are registering the console application in the Azure AD tenant. We unable to find what redirect url to mention with Azure AD

We found some references with onprem versions but we couldn't find SaaS.  Can someone please help me with example for redirect url.

We have tried with different URl's. But when we try to do the **Grant Consent** in BC getting the following ERROR. Please help on this

**AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '8B036D70-01A5-499F-BC2E-A6781859A647'**

Thanks.

**Comment by qutreson** [comment]
This repository no longer handles general questions and is only dedicated to bug reports for the latest preview version of the AL compiler and developer tools, while this seem to be a runtime issue or question.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

If this turns out to be a bug in the product, we suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
