### ISSUE TITLE
AA0242 wrongly warns that FlowFields might be JIT loaded, but they're unrelated AND calculated!

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6559]
**1. Describe the bug**
I get this warning, but it's wrong, because FlowFields are unaffected by the arrival of partial records, and still need `[SetAuto]CalcFields()`d like they always did. Which... I do in my code! Yet I now get spurious warnings as if I'm doing something wrong, which I'm not, that I'll have to `#pragma warning disable` for a line at a time.

You **could** consider making `SetLoadFields()` one-size-fits-all, and accept FlowFields and act like we called `SetAutoCalcFields()` on them... but it doesn't right now (see https://github.com/microsoft/AL/issues/6480), and if not going to do that, then don't warn about them spuriously.

**2. To Reproduce**
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
        MessageTxt: Label '%1: %2', Comment = '%1 = Name, %2 = Balance';
    begin
        Customer.SetLoadFields(Name);
        Customer.SetAutoCalcFields(Balance);

        if Customer.FindSet() then
            repeat
                Message(MessageTxt, Customer.Name, Customer.Balance);
            until Customer.Next() = 0;
    end;
}
```

**3. Expected behavior**
no warning because my code is correct.

(or, for `SetLoadFields()` to actually cause FlowFields to be loaded, as if by `SetAutoCalcFields()`)

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/63455896/113267227-00d7e800-92ce-11eb-8eec-7ab8a24abb70.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.54.3
- Business Central: 17.5
- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/63455896/113267330-21a03d80-92ce-11eb-9fad-dbc200a44074.png)

**Comment by PhDuck** [comment]
@qutreson assign it to me, we should just not warn on fields that can not cause JIT loads.

Hope the analyzer has access to the field type, if so, this should be relatively easy to fix.

**Comment by PhDuck** [comment]
@atoader this has been fixed, we can close this issue.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24933 and VS Code Extension Version 2.0.49088. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
