### ISSUE TITLE
AA0205 is fired too often

### ISSUE THREAD

**Issue by GenaritoBike** [microsoft/AL#6561]
**1. Describe the bug**
"AA0205 Use of unassigned variable" is fired too often.

**2. To Reproduce**
```
local procedure TestAA0205(): Integer
var
    Var1: Code[50];
begin
    Exit(MaxStrLen(Var1));
end;
```

**3. Expected behavior**
Var1 should not be marked as a problem in the MaxStrLen procedure.

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/9590807/113593922-4a5e6500-9637-11eb-8264-2f7310dcfc2e.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55.0
- Business Central: 17.3

**Comment by PaulIvan** [comment]
I am closing this issue because it has been resolved in the [latest developer preview](https://github.com/microsoft/AL#al-developer-preview-builds) . Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24965 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
