### ISSUE TITLE
Debugger reports "System Error retrieving value" for List that has been Clear()ed

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6563]
**1. Describe the bug**
Calling `Clear(SomeList)` seems to confuse the debugger: instead of showing that the `List` has had all its values removed, it retains the count of elements but shows `<System Error retrieving value>` against each one.

The same might be true for `Dictionary`, so please check whether there is a common cause and if so fix at source; thanks ;-)

**2. To Reproduce**
```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Customer: Record Customer;
        CustomerNoList: List of [Code[20]];
    begin
        Customer.SetLoadFields("No.");
        Customer.FindSet();

        repeat
            CustomerNoList.Add(Customer."No.");
        until Customer.Next() = 0;

        // Put a breakpoint here, then observe the CustomerNoList before and after stepping over it.
        Clear(CustomerNoList);
    end;
}
```

**3. Expected behavior**
The debugger should show that the List is now empty, instead of errors.

**4. Actual behavior**
before `Clear()`:
![image](https://user-images.githubusercontent.com/63455896/113707624-14bd8880-96d8-11eb-8ac1-0e6baf4efca2.png)

after `Clear()`:
![image](https://user-images.githubusercontent.com/63455896/113707643-1b4c0000-96d8-11eb-9b4f-86979706282c.png)

**5. Versions:**

- AL Language: 7.1.441584
- Visual Studio Code: 1.55
- Business Central: 17.5
- List of Visual Studio Code extensions that you have installed:
![image](https://user-images.githubusercontent.com/63455896/113707797-55b59d00-96d8-11eb-90ef-f627b52763a9.png)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28023 and VS Code Extension Version 8.0.491888. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
