### ISSUE TITLE
File.UploadIntoStream(2 parameters) replacement for File.UploadIntoStream(5 parameters) missing filename

### ISSUE THREAD

**Issue by quadfin** [microsoft/AL#6568]
File.UploadIntoStream(5 parameters) is being deprecated in runtime 7.0 and replaced by File.UploadIntoStream(2 parameters).
The replacement function does not return the name of the uploaded file.
This lack of information breaks functionality that depended upon knowing the name of the file.
Please add the filename parameter to the replacement function.

**Comment by pborring** [comment]
We created a new, cleaned function to align with the web client and original intent of using the function, without knowing about the filename being used for archiving. Instead of creating a third method signature now, we will unblock and keep the original signature as well (i.e., remove it being obsoleted), recommending any new uptake to use the new signature unless need for filename storage. At some point in the future we might add a new method supporting filename, but probably not as a parameter, but as the return type instead.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24292 and VS Code Extension Version 8.0.446271. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
