### ISSUE TITLE
Foreach on Text

### ISSUE THREAD

**Issue by Gallimathias** [microsoft/AL#657]
Ok text handling is now as usual, very cool;).

Now it would still be awful cool if you could use Foreach through the text variable.

Scenario is, I want to remove all special characters from a text.

![foreachtext](https://user-images.githubusercontent.com/16351673/30205930-c628fbe4-948a-11e7-8f15-9ee2cf466d30.PNG)

**Comment by StanislawStempin** [comment]
Thanks for the suggestion, we will consider it

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.52547.0 and VS Code Extension Version 11.0.744315. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
