### ISSUE TITLE
 The Active Session does not exist on publishing the AL solution to the server.

### ISSUE THREAD

**Issue by peikba** [microsoft/AL#6588]
Hi Guys,

I have a problem at one of my customers.
It is possible to create a new project and download symbols.
It recognizes all objects to create an extension.
I can build the solution and thereby create the app file.
However, when I try to upload the app file to the server it gives the following error message:

The request for path /Servicetier_Name/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Could not install the extension ALProject4 on tenant default due to the following error: The Active Session does not exist. Identification fields and values: Server Instance ID='22733',Session ID='51'

The active session id is always larger than all other active session ids, and it must therefore be because it is trying to create a new session. 

I does not matter if I upload the app file from VS code or PowerShell, same error.

The customer is running BC 14.0.45365.0

Ant ideas?

**Comment by qutreson** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central.

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
