### ISSUE TITLE
AA0242 is warning about fields that are being assigned to / validated, not read!

### ISSUE THREAD

**Issue by dtkb** [microsoft/AL#6599]
it's warning that fields I'm WRITING to haven't been loaded for READING...

Code I found this in:
![image](https://user-images.githubusercontent.com/63455896/116401641-619e0600-a823-11eb-8d1d-ffd47c4ad181.png)

minimal sample:
```al
codeunit 50100 Test
{
    trigger OnRun()
    var
        GenJournalLine: Record "Gen. Journal Line";
        LineNo: Integer;
    begin
        GenJournalLine.SetLoadFields("Line No.");
        if GenJournalLine.FindLast() then;
        LineNo := GenJournalLine."Line No." + 10000;

        GenJournalLine.Init();
        GenJournalLine.Validate("Account Type", GenJournalLine."Account Type"::"G/L Account");
        GenJournalLine.VAlidate("Account No.", 'BLAH');
    end;
}
```

screenshot thereof:
![image](https://user-images.githubusercontent.com/63455896/116396486-5fd14400-a81d-11eb-9698-c06baf72c2db.png)

AL extension:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.1.453917
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by dtkb** [comment]
It seems that adding a `GenJournalLine.SetLoadFields()` before the `GenJournalLine.Init()` suppresses this, even though that makes no sense because the fields still wouldn't be loaded unless a `Get()` or `Find*()` was done, and again _they are being assigned, not read anyway_...

**Comment by dtkb** [comment]
paging @PhDuck ;-)

**Comment by PhDuck** [comment]
Thanks for you well written issue (as always) and thanks for the continued commitment to making this analyzer better.

On the matter of naked writes (rec.Solution := 42) triggering a JIT load warning it is clearly an error from the analyzer and I have a fix in code review now.

Validate on the other hand is more complex than what you may expect. Calling Validate will in certain situations read out the previous value, which may triggering a JIT load.
  It is not possible for the analyzer to determine if a validate call would trigger a read, since this is first known at runtime.

Warning: The information about Validate is an implementation detail that may change from version to version. So we will not give any guarantees about its behavior. Since this is an implementation detail, this should not be seen as officially documentation.

Therefore, I will leave the Validate causing a warning and fix the writes.

**Comment by dtkb** [comment]
You're welcome, and thanks for all your work on it!

> Validate on the other hand is more complex than what you may expect. Calling Validate will in certain situations read out the previous value, which may triggering a JIT load.

Yes, this did occur to me later. and I suppose you're right that warning by default is best, and we can `#pragma` away AA0242 if we know it really doesn't matter in any specific case.

Saying that - shouldn't an `Init()` cause AA0242 to stop complaining, since that should set all non-PK fields to their `InitValue`s, thus meaning no JIT load should be needed or done?

***

Somewhat related, regarding my 'workaround':

> It seems that adding a GenJournalLine.SetLoadFields() before the GenJournalLine.Init() suppresses this, even though that makes no sense [...]

It seems this shouldn't be a workaround, because resetting `SetLoadFields()` has no effect if the record is not retrieved again from the database, which it wasn't in either of my cases. So is this perhaps a bug also?

**Comment by PhDuck** [comment]
> Saying that - shouldn't an Init() cause AA0242 to stop complaining - including in the case of Validate() - because that should set all non-PK fields to their InitValues, thus meaning no JIT load should be needed or done?

Again, it's a bit more complex than that. Init() just overwrites the written values, not the read values, so inside the record we keep track of these separately. You can discard a written value and get back the read value, so you can again trigger a JIT load.

So Init() has no special treatment from the analyzer's point of view and shouldn't have.

Clear on the other hand should have special treatment but currently doesn't, I will look at it tonight and see how hard it would be to fix that.

**Comment by dtkb** [comment]
> Init() just overwrites the written values, not the read values, so inside the record we keep track of these separately. You can discard a written value and get back the read value, so you can again trigger a JIT load.

Out of interest, how can one "discard a written value and get back the read value"? e.g.: How could a Validate handler of some field see some other `xRec` value than whatever was set with `Init()` before the field was validated?

> Clear on the other hand should have special treatment but currently doesn't, I will look at it tonight and see how hard it would be to fix that.

That's better than nothing anyway, if it can suppress AA0242 warnings on `Validate()` calls. :-P

**Comment by NKarolak** [comment]
When I hit the AA0242 warning earlier in a scenario very similar to the one mentioned in the initial post, I also corrected (or worked around it) using `MyRec.SetLoadFields();` before setting field values.

Would you recommend to remove that line of code again? I'd assume that it does not harm to keep it.

**Comment by PhDuck** [comment]
@NKarolak You should be more active in opening issues then, we could have fixed this long before ;)
To answer your question: No, there should be no difference between setting it before or after the call to SetLoadFields.

Please do remember that if you modify the primary keys and then do an Insert, a JIT load will happen!

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25090 and VS Code Extension Version 8.0.456505. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
