### ISSUE TITLE
Cannot replace a field from a table extension by a table field

### ISSUE THREAD

**Issue by EricBos** [microsoft/AL#6630]
Please include the following with each issue:

**1. Describe the bug**

We have received a table extension from our partner and have deployed this to our environment as this was a custom request.
Now one of the fields has become part of the standard solution coming from the market place.
The column in the Table Extension cannot be marked Obsolete/Removed with a message that the column already exists in the market place solution.
Also cannot simply remove the field from the Table Extension as this is a not supported scenario

**2. To Reproduce**
-

**3. Expected behavior**
Ability to remove a field from a table extension or to specify it is replaced by a table field

**4. Actual behavior**
Error message that the field is already existing

**5. Versions:**

- Business Central: v17

### Final Checklist

Please remember to do the following:

* [ ] Search the issue repository to ensure you are reporting a new issue

* [ ] Reproduce the issue after disabling all extensions except the AL Language extension

* [ ] Simplify your code around the issue to better isolate the problem

**Comment by dtkb** [comment]
> The column in the Table Extension cannot be marked Obsolete/Removed with a message that the column already exists in the market place solution.

Why not? That sounds like exactly how your partner should resolve this.

**Comment by atoader** [comment]
A few notes from an in-progress document 

In AL, all top-level objects are declared in the same global namespace. The extensions installed in an environment cannot have the same top-level object declared multiple times or controls/fields/dataitems with the same name defined multiple times in the same logical object i.e. a table extension cannot add a field with the same name as a field in the extended table.

Example:
Extension A
table 10 MyTable {}

Extension B
table 20 MyTable {}

Extensions A and B cannot be installed in the same environment because the two tables have the same name. An error will be raised when the installation of the second extension is attempted and the installation will fail.

Example:
Extension A
table 10 MyTable 
{
	field(1; MyField; Integer){}
}

Extension B
tableextension 20 MyTableExt  extends MyTable
{
	field(10; MyField; Boolean){}
}

In this case, extension B will fail to compile because the field in the table extension has the same name as the field in the base table. Publishing extension B will fail with a compilation error.

In general, we recommend using affixes for your object and element names to prevent this type of conflicts https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix

To make the issue more concrete, we will use the following example to illustrate how this problem can manifest itself and how to resolve it:

Let us assume we have a Business Central environment running on Business Central Wave 1 2020, Update 16.5 (version 16.5). In our environment, we have a per-tenant extension, named "MyExtension" by "Contoso" version 1.0.0.0 containing the following table extension

tableextension 50100 SalesCreditMemoHeaderExt extends  "Sales Cr.Memo Header"
{
	Fields
	{
		Field(50100; "Shipping Agent Service Code"; Code[10])
		{
		}
	}
}

Which adds the field "Shipping Agent Service Code" to the "Sales Cr.Memo Header" defined in the "Base Application" extension by Microsoft.

In Business Central Wave 2 2020 (version 17.0), Microsoft enhances the table "Sales Cr.Memo Header" by adding the following field

field(5794; "Shipping Agent Service Code"; Code[10]) {}

The service will attempt to upgrade our environment from version 16.5 to version 17.0 of the product. During the upgrade process, our per-tenant extension will be recompiled against the latest version of the "Base Application".
The compilation will fail with an error message similar to "A member of type Field with name "Shipping Agent Service Code" is already defined in Table "Sales Cr.Memo Header" by the extension "Base Application by Microsoft (17.0.0.0)". 

The service will abort the upgrade of our environment and an e-mail will be sent to the administrator registered in the Tenant Administration Center containing the above error message.

Our first reaction is to modify the per-tenant extension, remove the conflicting field, and try to upload version 1.1.0.0 to the service. This will fail with an error message similar to "Per-tenant extension "MyExtension" version 1.0.0.0 by "Contoso" failed to synchronize the database schema."

This error message is raised because the system does not allow implicitly removing/renaming schema elements such as tables, table fields. To upgrade our environment, we must forcefully remove the conflicting field.

	1. Create a sandbox
As the following steps can lead to data-loss, we recommend that the steps are first performed in a sandbox environment created as a copy from the production environment. See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-environments#create-a-sandbox-environment 

	2. Export data using RapidStart
We will start by backing up the data contained in the tables or table extensions declared by our extension using RapidStart. You can use other mechanisms to backup the data, but the main point is to backup data to an external storage system.

	3. Uninstall the extension
Uninstall the extension and select the option to delete the extension's data and schema. Using this option will delete the tables and fields contributed by the table extension and the environment will delete any trace of the extension.

	4. Remove the field from the extension
Create version 2.0.0.0 of the extension that does not contain the field which conflicts with the one from the "Base Application". Deploy this version of the extension to the environment..

	5. Import the data
Import the data that has been backed up from the rapid start package or the external storage system you have used in point 2. 

	6. Upgrade the environment 
At this point, the conflict has been resolved and you should be able to update the environment. Schedule an update for the sandbox and ensure it is successfully updated. If upgrade fails, troubleshoot the issue.

Once our sandbox environment has been successfully updated to the next release, we will replicate steps 2-6 on our production environment. Before we do so, we will ensure that our customer will not be impacted by our changes and we will clearly communicate a maintenance window in which the work will be performed.

**Comment by atoader** [comment]
The ask is outside the scope of this repository, because it does not relate to the development tools per se, but you can work with your partner based on the instructions provided above.
