### ISSUE TITLE
Unable to load Analyzer assembly Microsoft.Dynamics.Nav.CodeCop.dll (insider vsix 8.0.458471)

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6636]
Please include the following with each issue:

**1. Describe the bug**
Tried to install the latest insider vsix, but got errors on the analyzer dlls not found.

**2. To Reproduce**
- Copy the latest vsix: "\bcartifacts.cache\sandbox\19.0.25505.0\platform\ModernDev\program files\Microsoft Dynamics NAV\180\AL Development Environment\ALLanguage.vsix"
- In VSCode, install the extension from VSIX.
- VSIX is updated

![image](https://user-images.githubusercontent.com/25268332/118771823-4737d500-b883-11eb-80eb-23803e9d249b.png)

- Reload VS Code and load AL project
- Errors:

_Unable to load Analyzer assembly c:\Users\fvet\.vscode\extensions\ms-dynamics-smb.al-8.0.458471\bin\win32\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll : File c:\Users\fvet\.vscode\extensions\ms-dynamics-smb.al-8.0.458471\bin\win32\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll was not found._

![image](https://user-images.githubusercontent.com/25268332/118772063-9847c900-b883-11eb-955a-d7e2eed9f6e4.png)

**5. Versions:**

- AL Language: 8.0.458471
- Visual Studio Code: 1.56.2
- Business Central: n/A
- List of Visual Studio Code extensions that you have installed: n/A

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26166 and VS Code Extension Version 8.0.469410. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
