### ISSUE TITLE
alc.exe produces an invalid xml format near Condition

### ISSUE THREAD

**Issue by louagej** [microsoft/AL#6639]
**1. Describe the bug**

alc.exe produces wrong xml format near styles

**2. To Reproduce**

- use alc.exe (C:\Users\\*{username}*\\.vscode\extensions\ms-dynamics-smb.al-7.1.453917\bin) to produce a .dgml file
- open the .dgml file and search for the `/DirectedGraph/Styles/Style[1]/Condition` path
- See that after the closing `>` there is a `\` character

![image](https://user-images.githubusercontent.com/7229592/119517186-b035b600-bd77-11eb-9c9a-44be40fb9050.png)

**3. Expected behavior**

![image](https://user-images.githubusercontent.com/7229592/119517310-cd6a8480-bd77-11eb-8173-2e54a1ec4ccb.png)

**4. Versions:**

- AL Language: v7.1.453917
- Visual Studio Code: 1.56.2
- Business Central: 18.1
- List of Visual Studio Code extensions that you have installed: `AL Language`

### Final Checklist

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26066 and VS Code Extension Version 8.0.468031. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
