### ISSUE TITLE
The identifier XXX could not be found.

### ISSUE THREAD

**Issue by jason1004156** [microsoft/AL#6660]
When I tried to use a varible to control the component on a reportextension, this error message appeared on the page. Is this an bug or did I miss something?
runtime:7.1
![image](https://user-images.githubusercontent.com/32699556/121629049-02cbdd80-caad-11eb-8380-7f7246a09878.png)
![image](https://user-images.githubusercontent.com/32699556/121629175-37d83000-caad-11eb-8c6a-9df2ded6c57b.png)
![image](https://user-images.githubusercontent.com/32699556/121629233-50e0e100-caad-11eb-8852-115c6182bf3e.png)

**Comment by dtkb** [comment]
unrelated, but you'll want to fix that copy-pasted `Caption`, and `SetFilter(Foo, '=%1', Bar)` is better/faster written as `SetRange(Foo, Bar)`

**Comment by jason1004156** [comment]
Is this being processed~?

**Comment by kalberes** [comment]
It is not yet processed. If you would like more urgent escalations than you should probably escalate it for a Request For Hotfix.

**Comment by jason1004156** [comment]
@kalberes  How should i do?
Add a bug label or something?

**Comment by kalberes** [comment]
I can mark it as a bug and then lets see how it goes.
But if you really want something to be fixed than you have to use teh official channels and open a support case :
To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 28335 and VS Code Extension Version 8.0.495603. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
