### ISSUE TITLE
2nd RAD Publish gives unexpected error with DotNet (OnPrem)

### ISSUE THREAD

**Issue by ManneSTE** [microsoft/AL#6665]
**1. Describe the bug**
When using a DotNet variable (declared in same app), only the first "Rapid Application Publish" will succeed, after another, arbitrary change in the same file referencing the dotnet type, a subsequent RadPublish will fail with Error `error AL0185: DotNet 'SomeArbitraryDotNetType' is missing`.

**2. To Reproduce**
Create minimal app (`OnPrem`, no dependencies necessary) with following two files

`arbitraryobject.al`:
``` AL
codeunit 50802 SomeObject
{
    var
        someArbitraryDotNetVariable: DotNet SomeArbitraryDotNetType;
}

```
`dotnet.al`:
``` AL
dotnet
{
    assembly("mscorlib")
    {
        type("System.String"; "SomeArbitraryDotNetType") { }
    }
}
```
sample `app.json` 
```
{
    "id": "c0d890d9-7b02-4a4b-a23d-b7884e170ae0",
    "name": "someapp",
    "publisher": "somepublisher",
    "version": "1.0.0.0",
    "platform": "18.0.0.0",
    "target": "OnPrem",
    "runtime": "7.0"
}
```
   -  Publish Application - OK
   - Arbitrary change in "SomeObject" + RadPublish - OK
   - Another change in "SomeObject" + RadPublish - Error:  
   **The request for path .../dev/apps?...&IsRad=true&... failed with code UnprocessableEntity. Reason: Extension compilation failed ... error AL0185: DotNet 'SomeArbitraryDotNetType' is missing'**
 - Remark: this error does not occur if the two *.al files get combined into a single file (!)

**3. Expected behavior**
Subsequent RADPublish operations should succeed just as the first one.

**4. Actual behavior**
Only first RADPublish succeeds;  
In an OnPrem Scenario with DotNet usage this issue makes  RADPublish not really useful.

**5. Versions:**

- AL Language: v7.2.475273
- Visual Studio Code: 1.57.0
- Business Central: 18.0.22893.23773
- List of Visual Studio Code extensions that you have installed: AL Extension

### Final Checklist

Please remember to do the following:

* [ x] Search the issue repository to ensure you are reporting a new issue

* [ x] Reproduce the issue after disabling all extensions except the AL Language extension

* [ x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.49296.0 and VS Code Extension Version 11.0.708823. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
