### ISSUE TITLE
altpgen error cds0001

### ISSUE THREAD

**Issue by krisc123-jpg** [microsoft/AL#6667]
Please include the following with each issue:

**1. Describe the bug**
We are getting error CDS0001 when authenticating to CDS using altpgen.

**2. To Reproduce**
The command we are running is:
./altpgen.exe -project:"C:\Users\..\Tests\AL Gen2" 
-packagecachepath:"C:\Users\..\Tests\AL Gen2\.alpackages" 
-serviceuri:"https://cronus.crm6.dynamics.com" 
-entities:contact 
-baseid:50101

**3. Expected behavior**
We were expecting it to generate the AL file

**4. Actual behavior**
Output is: 
Microsoft (R) AL Table Proxy Generator version 7.2.7.16535
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating CDS using ServiceUri=https://cronus.crm6.dynamics.com
error CDS0001:
![image](https://user-images.githubusercontent.com/83793910/122310914-61cd9e80-cf54-11eb-94b3-f166fda0cc88.png)

**5. Versions:**

- AL Language: 7.2.475273
- Visual Studio Code: 1.57.0
- Business Central: AU Business Central 18.1 (Platform 18.0.24800.26638 + Application 18.1.24822.24906)
- List of Visual Studio Code extensions that you have installed: AL Language

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by SergioRueda1** [comment]
I had the same error, I changed the versión of my AL language extension to 7.1.453917 and thats worked for me.

**Comment by krisc123-jpg** [comment]
Thank you - your suggestion worked.  We were using version 7.2.475273 and changed to 7.1.453917 and that solved the problem.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26961 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
