### ISSUE TITLE
Partial Records in Pages: allow implicit fields as odata pages or reports

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/AL#6673]
**1. Describe the bug / suggestion**
Nowadays partial records cannot be manually used from pages (see: Partial Records in Pages: setloadfields does not work fine in issue #6672) .
Maybe an alternative to fix this problem is to allow implicit fields as odata pages or reports, as described in documentation of Using Partial Records (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-partial-records#reports-and-odata-pages): *the platform implicitly uses partial records when fetching data for reports and calling pages through OData*.

**Why not allow to use in all pages implicit fields, and select automatically all fields included in layout?**. After that, if we need to add some aditional fields to rec variable,  we wil use rec.addloadfields in OnOpenPage, as it done in pages published as odata webservice.
I think that is a alternative fix to issue #6672, a suggestion for enhacement of Partial Records in pages.
With this change, perfomance will increase a lot on pages from source tables with lots of table extensions in  many apps. 
For example, if table G/L Entry has multiple table extensions.

**5. Versions:**

- AL Language: v7.2.475273
- Visual Studio Code: 1.57.1
- Business Central: BC18.2 ES OnPrem  docker container.
- List of Visual Studio Code extensions that you have installed:

**Comment by PhDuck** [comment]
The long term goal is that opening pages from the web client would indeed use Partial Records implicitly.

The problem is that pages can do anything, it is not unrealistic that a page could write some code in its trigger that would trigger a JIT load failure. These can either occur from deletes or modifies, see below for a contrived example:

page

trigger OnAfterGet()
var
    age : Integer;
begin
    DeleteRecIfNeeded(rec);
    // Notice the record is gone in the DB, so we can no longer perform JIT loads.

    // Trigger a JIT somehow, maybe access a field here, or pass the record 10 times to other functions and codeunits.
    age := rec.SomeNoneLoadedField; // ERROR: JIT load error cause record doesn't exists.
end

procedure DeleteRecIfNeeded(sRec : Record Some)
begin
    if (sRec.IsToBeDeleted) then
        sRec.Delete();
end

 This is essentially the problem we are dealing with, and while it seems unlikely someone would write this code directly, we have seen it written in-directly through tons of nested calls.

We do not want to enable Partial Records on pages implicitly if it ends up breaking a bunch of pages, so we are currently capturing telemetry on how many pages we would break if we enabled it.

**Comment by atoader** [comment]
As this is currently by design and outside the scope of this repository, we recommend that you open an idea on aka.ms/bcideas

**Comment by ti-jalopez** [comment]
I've opened a **new idea** on aka.ms/bcidea: **Partial Records in Pages: allow implicit fields as odata pages or reports in https://experience.dynamics.com/ideas/idea/?ideaid=b779d319-efd3-eb11-ba5e-0003ff45e08a**
