### ISSUE TITLE
AppSourceCop rule AS0011 does not enforce mandatoryAffixes on new enumextension values

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6676]
given `app.json`:
```json
{
  "id": "6613924d-6740-45a3-b07e-94eda29e7fe9",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "platform": "1.0.0.0",
  "application": "18.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "showMyCode": true,
  "runtime": "7.0",
  "features": ["NoImplicitWith"],
  "suppressWarnings": ["AS0013", "AS0015", "AS0051", "AS0052", "AS0084", "AS0092"]
}
```

`settings.json`:
```json
{
	"al.codeAnalyzers": ["${AppSourceCop}","${CodeCop}","${PerTenantExtensionCop}","${UICop}"]
}
```

`AppSourceCop.json`:
```json
{
	"mandatoryAffixes": ["FOO"]
}
```

and finally `PurchaseDocumentTypeFOO.EnumExt.al`:
```al
enumextension 50100 "Purchase Document Type FOO" extends "Purchase Document Type"
{
    value(50100; Bar)
    {
        Caption = 'Bar';
    }
}
```

There is no error that the new value `Bar` has a name without a `mandatoryAffix` - but surely there should be? The point of affixes is to prevent clashes between fields with the same name (but possibly radically different purposes, etc.) between extensions, and surely `enum` values are one of the main places where that is likely to happen given enough time.

![image](https://user-images.githubusercontent.com/63455896/122941677-85864f80-d36d-11eb-9461-710bab00dd17.png)

I would expect the name to be diagnosed as needing renamed to `"Bar FOO"`, and if not the same kind of error on the `value` name as we get for the `enumextension` name if dropping the suffix there:
![image](https://user-images.githubusercontent.com/63455896/122941761-9a62e300-d36d-11eb-9c63-528c66743d0a.png)

AL extension:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.2.475273
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 30045 and VS Code Extension Version 9.0.517327. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
