### ISSUE TITLE
no error AL0450 if table extension still uses field with ObsoleteState = Removed in active key

### ISSUE THREAD

**Issue by db-bc** [microsoft/AL#6680]
This code:

```al
tableextension 50100 CustomerTest extends Customer
{
    fields
    {
        field(50100; RemovedField; Integer)
        {
            ObsoleteState = Removed;
            ObsoleteReason = 'welp';
        }
    }

    keys
    {
        key(RemovedField; RemovedField)
        {
        }
    }
}
```

does not produce any error that it still declares an active `key` containing a `field` that has been `Removed`. Surely it should?

![image](https://user-images.githubusercontent.com/63455896/123297768-c9b15580-d50f-11eb-94e5-71f08ea8ecf4.png)

If the object were a `table`, we **would** get the relevant error. But for a `tableextension`, we sadly do not.

![image](https://user-images.githubusercontent.com/63455896/123298081-0f6e1e00-d510-11eb-96ae-9ea3acf581b4.png)

AL extension:
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 7.2.475273
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 27521 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by db-bc** [comment]
Thank you. I've got an email from Partner Center for an app that suffered this bug and still has a removed field in a key, saying that the next version of BC will diagnose it as a compile error, so I can go and fix it now!
