### ISSUE TITLE
AL0296 "The type or method 'XXX' cannot be used for 'Cloud' development" in permissionset objects

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/AL#6693]
**1. Describe the bug**

When refering to Scope = OnPrem objects (i.e. table) in a permissionset object, AL0296 is raised.
I am wondering if this is not an issue regarding the fact permissionset is not trying to access this object.

The real example I have is the following: I am trying to embed in an app a permissionset for the future Service-to-Service authentication flow. My app is reading table User Property (actually it is not my app, but the standard function that indirectly use this table).
However, the table is on-prem only. If I want to give the best user experience for my customer, I think I should be able to specify this table in my permissionset. 

**2. To Reproduce**

1. Create a permissionset object

``` AL
permissionset 50000 "My PermissionSet"
{
  Assignable = true;

  Permissions = tabledata "User Property" = R;
}
```

**3. Expected behavior**
I think Scope = OnPrem objects should be accessible in permissionset objects.

**4. Actual behavior**
The permissionset is handled like a record / codeunit / ... variable.

**5. Versions:**

- AL Language: 7.3.481747
- Visual Studio Code: 1.57.1
- Business Central: 18.0.27249.0

**Comment by nndobrev** [comment]
Hi @nicolassaleron, please check the app.json file of your app if there is explicitly specified `"target": "OnPrem"` because if there is not the default value is `Cloud` (you can find target setting [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-json-files)) and this means you cannot access application objects with scope specified as `OnPrem`. More on the scope you can find [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-compilation-scope-overview). As long as I specify `"target": "OnPrem"` in my app.json I don't see any problems. Please correct me if I don't understand you right, so I can investigate further.

![image](https://user-images.githubusercontent.com/85873063/124562926-def77f80-de3f-11eb-985e-a32faa77cf2d.png)

**Comment by nicolassaleron** [comment]
Hi, my app.json is explicitely targetting Cloud with ```"target": "Cloud"```.
I totally understand the idea that a Cloud app cannot get access **in the code** to OnPrem objects.

I am meaning here that a permissionset object (more precisely the Permissions property) is not really trying to access the object but to give access to the object to a user.
I think this is especially an issue regarding this feature: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication

If we want to deploy S2S applications we should be able to embed in our app a permissionset that reflects the minimum rights the app requires.

My concern comes from the fact one of my "Cloud" app needs to access **User Property** table which is Scope=OnPrem. Obviously, my code is not accessing this table in the code, Microsoft's code is indirectly trying to access the table.

Today, I see two workarounds:

* We can create a permission set from the web client with the User Property table in it. This is not really a good experience for the customer/deployment team as they have to proceed manual actions for each deployment.
* We can IncludePermissionSets = "D365 READ". This is nice but it gives the AAD App much more read access that it should have.

I see this more as an issue than an idea. But let me know if I should post it to BC Ideas web site.

**Comment by thloke** [comment]
Thanks for the suggestion. We've discussed this internally and have agreed that this is an improvement request that needs to be prioritized. Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
