### ISSUE TITLE
Licensing of tableextension and pageextension objects

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/AL#673]
Since in September there are significantly fewer objects available for testing (only 50 per object type) I asked myself why the object types "tableextension" and "pageextension" count as a new object of their own, when in the old development environment they were only modifications to existing objects. A license extension was therefore not necessary. This is not quite understandable, why this is handled in such a way, because these objects do not even appear to be independent during development. For example, if you only add a few fields to a table extension, you have to specify the original table in the source code anyway. From my point of view, the object name doesn't make much sense because you can't work with inheritance, or it is obviously used somewhere. Is there a change planned here?

**Comment by Gallimathias** [comment]
I had the expectation that it would behave similarly to the extension anywehre of C# 8, so I think the object type makes sense. However, I would simplify the page extension and table extension to extension. The compiler knows from the target which object it is. Since both are classes in the background, this should be problem-free. From these points, the current licensing still makes sense.

**Comment by StanislawStempin** [comment]
Page extensions and table extensions follow the table and page ranges that are available in the license. That means that even on the demo license you can use up to 50 page extensions and up to 50 table extensions. It should be sufficient for demo purposes. Once you have an actual project to work on you can obtain larger dedicated ranges. 
Since extension objects have IDs they have to be included in the licensing ranges at least for the purpose of avoiding ID conflicts.

**Comment by fvet** [comment]
In case the customer license just contains a Starter pack, the object table range 50000..50009 is available. Does this imply that we will only be able to create a maximum of just 10 table extension objects too? (Where in the past we could add fields to almost any table, without any license impact / additional cost for the customer.)

> Once you have an actual project to work on you can obtain larger dedicated ranges.

Can these be obtained / included in the license for free?

**Comment by fvet** [comment]
@StanislawStempin 
Off-topic : Can closed issues be re-opened or should i create a new issue instead?

**Comment by kalberes** [comment]
Please create a new issue
