### ISSUE TITLE
Modified fields on table extension not included in VS Code symbols

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6733]
Open a table extension al file which modifies some fields in the base table. Those fields are not included in the symbols listed by VS Code (Ctrl+Shift+O)

![image](https://user-images.githubusercontent.com/19267298/129224747-07c4b4a0-9f4b-4e7a-882f-0afbb789ba28.png)

**Comment by nndobrev** [comment]
Hi, we really appreciate your idea but currently, this issue is beyond the scope of the AL language and development tools. We will consider it internally but please go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
