### ISSUE TITLE
MaxStrLen does not work correct on VAR parameters

### ISSUE THREAD

**Issue by yurim108** [microsoft/AL#6738]
- AL Extension Version: v7.4.496506
- Server Version: BC 16.4 OnPrem
- AL code sample that triggers the issue

procedure DoTest()
var
       Item: Record Item;
begin
       F1(Item.Description);
end;

procedure F1(var s: Text)
begin
       Message('%1', MaxStrLen(s));  // shows 2147483647, expected result: 100
end;

The same code has worked correctly in NAV 2018 and older versions.

**Comment by db-bc** [comment]
I can confirm this used to print the max length of the passed string in NAV 2018, but prints the max length of a normal `Text` in BC 18.3

**Comment by MortenRa** [comment]
any progress on this issue yet

**Comment by MortenRa** [comment]
This is also a problem in BC19 any news on this

**Comment by MortenRa** [comment]
@qutreson anyone looking into this?

**Comment by MortenRa** [comment]
@qutreson  @JesperSchulz  anyone looking into this bug, seems quite old and we need to rewrite in our app if this will not get solved.

**Comment by JesperSchulz** [comment]
It would seem that the bug is "in progress". A fix should become available, from what I can tell.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 43318 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
