### ISSUE TITLE
Qualifying an enum value through Enum::MyEnum::Value does not work correctly in BC14

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#6752]
Please include the following with each issue:

**1. Describe the bug**
When using the syntax `Enum::MyEnum::MyValue` to reference an enum value inside a code block, the app compiles without issues. When I then try to publish this app to a BC14 (CU10) instancen using Publish-NAVApp I get the following error:

````
[...] (yy,xx): error AL0104: Syntax error, ',' expected"
````

**2. To Reproduce**
1. Define an enum with some values
2. Use that enum anywhere in the code using `Enum::MyEnum::MyValue`
3. Build the app
4. Install the app on a BC14 CU10 instance by using Publish-NAVApp

**3. Expected behavior**
There are two possibilities. The first would be to allow this kind of qualification on BC14 as well (BC17+ does not have any issues here). But I guess that for a number of reasons that is not possible and that's also fine.
The other solution would be to generate a compile-time error when trying this on a runtime that does not support this kind of syntax.

**4. Actual behavior**
Compilation works. Deployment fails.

**5. Versions:**

- AL Language: v7.4.496506
- Visual Studio Code: 1.59.1
- Business Central: Platform 14.0.40464.0 + Application 41204 (W1 14.11)

**Comment by nndobrev** [comment]
Hi @hemisphera,

Thank you for logging the issue, I believe your code looks something like this:
```
enum 50120 MyEnum
{
    Extensible = true;

    value(0; MyFirstValue)
    {
    }

    value(1; MySecondValue)
    {
    }
}

codeunit 50130 MyCodeunit
{
    trigger OnRun()
     var
        myEnumInstance: Enum MyEnum;
    begin
        myEnumInstance := Enum::MyEnum::MyFirstValue;
    end;
}
```

Please, check if either of these workarounds will unblock you and you can continue developing. :)

1. 
```
enum 50120 MyEnum
{
    Extensible = true;

    value(0; MyFirstValue)
    {
    }

    value(1; MySecondValue)
    {
    }
}

codeunit 50130 MyCodeunit
{
    trigger OnRun()
     var
        myEnumInstance: Enum MyEnum;
    begin
        myEnumInstance := MyEnum::MyFirstValue;
    end;
}
```

2. 
```
enum 50120 MyEnum
{
    Extensible = true;

    value(0; MyFirstValue)
    {
    }

    value(1; MySecondValue)
    {
    }
}

codeunit 50130 MyCodeunit
{
    trigger OnRun()
     var
        myEnumInstance: Enum MyEnum;
        myOtherEnumInstance: Enum MyEnum;
    begin
        myEnumInstance := myOtherEnumInstance::MyFirstValue;
    end;
}
```

**Comment by hemisphera** [comment]
Hi @nndobrev ,
sure, they both work fine. And that is exactly what I did to continue working.

But this is clearly a bug of the AL compiler nonetheless. It allows me to compile an app that I cannot install. Why has this issue been closed?

**Comment by hemisphera** [comment]
@nndobrev Any update to why this issue is closed? This workaround can not be the definitive solution.

**Comment by nndobrev** [comment]
Hi @hemisphera, sorry that I have missed your previous comment. 

We respect the community effort and the time you guys spend to log the errors and to show us the right direction we should follow in order to make AL compiler and hence Business Central a better production. However, our resources are not limitless and we have to prioritize our work. 

There is indeed an issue on our side that we don't report the error earlier- in the VSC extension. I tested with an older version of the extension and it seems to be regression. The behaviour should be that even using the latest available extension from the marketplace when you target older runtime (in your case 3.0) you should see it. Considering the fact that the compiler reports the error when you are trying to publish the extension, even though later in the development process and also there is a clear workaround I closed the issue.

**Comment by pri-kise** [comment]
I had this issue, today again with AL Compiler version 9.0.8.15677.
I'm only adding a comment, that I can find this issue more easily, since it looks like it won't be fixed.
Personally I would prefer a prioriziation tag for the issues instead of closing them.
