### ISSUE TITLE
AS0066 gives false positives for internal interfaces

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/AL#6768]
**1. Describe the bug**
When turning on AS0066 we receive errors for a modified interface, which is marked `Access = Internal;`.

**2. To Reproduce**
Create a version 1.0.0.0 of an extension where an internal interface is introduced.
```al
interface IFoo
{
  Access = Internal;
  procedure Foo();
}
```
Use this version for AppSourceCop.json with version 1.0.0.0 and raise the version to 2.0.0.0 while adding a procedure to the interface.
```al
interface IFoo
{
    Access = Internal;
    procedure Foo();
    procedure Bar();
}
```

**3. Expected behavior**
We should be able to modify internal interfaces freely since they're internal and therefor we control which extensions use them.

**4. Actual behavior**
An error is reported by AppSourceCop:
`error AS0066: Procedure 'Bar' has been added in 'Interface IFoo'. A procedure must not be added to a public API.`

**5. Versions:**

- AL Language: v8.0.508407
- Visual Studio Code: 1.60.0
- Business Central: 18,4
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 30339 and VS Code Extension Version 9.0.520686. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
