### ISSUE TITLE
Compiler error for Record.Get(Record) statements

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#6769]
**1. Describe the bug**
According to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-get-method, the Record.Get([**Any**,...]) method can be called with **Any value**.

This is not true if the **value** would be of type **record**.

Doiing so results in a runtime error and should be caught by the compiler.

**2. To Reproduce**

- Create a procedure with code below 

```
procedure Test()
    var
        Customer: record "Customer";
        CustomerCode: code[20];
    begin
        CustomerCode := 'CUSTOMER1';

        Customer.Get(Customer);  // <<<< instead of          Customer.Get(CustomerCode);
    end;

```

- Run code above

![image](https://user-images.githubusercontent.com/25268332/134176583-e4fdd3de-075b-4d87-ac5e-f471761c344f.png)

**3. Expected behavior**
A record.get(**record**) statement should result in a compiler error. (or at least provide a new codecop rule)

**4. Actual behavior**
A record.get(**record**) statement results in a runtime error.

**5. Versions:**

- AL Language: 8.0.508407
- Visual Studio Code: 
- Business Central:  2021 wave 1
- List of Visual Studio Code extensions that you have installed:

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 32086 and VS Code Extension Version 9.0.539949. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
