### ISSUE TITLE
Option variables without options..

### ISSUE THREAD

**Issue by hougaard** [Microsoft/AL#682]
Old NAV supported creating a variable of type option and assigning with 

Gets converted into: (By txt2al)

var
   foo : option;

begin
    foo := 1; // <- this fails in modern dev, works in C/Side
end.

**Comment by StanislawStempin** [comment]
Options got stronger validation in AL, including checks for ordinal value being within the range of declared option members.
Do you have a need for still supporting this construct?

**Comment by hougaard** [comment]
I think at least it would deserve a warning in txt2al since that converts it fine without option values.

**Comment by johndcollins** [comment]
That is going to be an issue for all the places where the pattern of "Source Sub Type" is implemented as an integer. What if you don't know the Option Value, but want to store it as an integer?

**Comment by StanislawStempin** [comment]
@hougaard - since this results in a compiler error anyway, adding a warning to txt2al doesn't seem like a high priority at the moment. We could probably disallow option without members to make the error more explicit. 
@johndcollins - can you use integers for all variables holding the ordinal option value? And only use option assignment when updating the table field?

**Comment by johndcollins** [comment]
@StanislawStempin that would not be generic enough. You might also want to filter on the option as an integer if your code doesn't know the actual value.

**Comment by StanislawStempin** [comment]
This scenario will be enabled as part of #1834. Closing this issue
