### ISSUE TITLE
[AL] Triggers cannot be called directly

### ISSUE THREAD

**Issue by hougaard** [Microsoft/AL#684]
![image](https://user-images.githubusercontent.com/3357237/30453818-07eca986-994f-11e7-8228-41a5fa0ddeda.png)

Why is calling a trigger no longer supported?

**Comment by twityde** [comment]
Ich think ist was never possible. OnAfterGetCurrRecord ist a Special Thing. This Trigger doesn't exists in the first page object in NAV 2009. The Transformation Tool created a function and called it from OnAfterGetRecord. With the Comeback of OnAfterGetRecord nav Looks if a local function Witherspoon the Same Name exists anderen called Thema instead of the Empty Trigger.

But other Question why want you do that? Create a local function and call them in both triggers.

**Comment by StanislawStempin** [comment]
This is by design. It is not possible to call triggers in C/SIDE either.
