### ISSUE TITLE
Problem with package loading for multiple projects

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/AL#6841]
**1. Describe the bug**
Good day,
I have problem with packages in multiple projects (main application and test application) last few months. When I compile second application (test application) I get error message:

error AL1022: A package with publisher 'Microsoft', name 'Library Assert', and a version compatible with '19.0.0.0' could not be found in the package cache folder '**path to first project**\./.alpackages'

Problem is that VSC looking for packages in wrong folder where I do not have mentioned files. VSC should looking for packages in  '**path to second project**\./.alpackages' where all required files are copied.

I found workaround. When I use "Download Symbols" in second project to some server or container (I don't care because I revert app file). Everything is OK and compilation works. It looks like "Download Symbols" write somewhere correct path.

**2. To Reproduce**

1. Create first projects
2. Compile project
3. Add project folder to workspace
4. Copy folder with first projects
5. Change app.json settings to new project and add dependecies on test libraries
6. Change objects in second project
7. Compile second project
8. You should get error about packages
9. Use "Download Symbols" on second project 
10. It should solve package problem

**3. Expected behavior**
VSC shloud take care about folder where is compilation started and VSC should use correct alpackages subfolder

**4. Actual behavior**
VSC raise error during compilation

**5. Versions:**

- AL Language: 8.2.545335
- Visual Studio Code: 1.62.3 
- Business Central: 19.0.29894.30693
- List of Visual Studio Code extensions that you have installed:

**Comment by NKarolak** [comment]
I can confirm this very issue as well (symbols searched in the wrong app), but only since recently. Probably related with one of the lastest AL Language updates?

**Comment by fridrichovsky** [comment]
I am not sure with version exactyl, but I think that it hapens from 8.1 version.

**Comment by thloke** [comment]
@kalberes  - this might be related to the workspace reference loading changes.

**Comment by kalberes** [comment]
Reload window should also solve the problem, instead of downloading symbols.
What does this step mean? "Copy folder with first projects": copy from where to where?

**Comment by fridrichovsky** [comment]
I reloaded window many times and it doesn't help. Only download symbols helps. 
The step mean that you copy whole folder with first project and create new folder first projects copy. Rename it to second projects and set required parameters for new project.

**Comment by kalberes** [comment]
Ok let me try to understand what you did. I am an example person.
a. You have a folder called "foo" somewehere with some AL files. 
b. You have some folder called "bar" with some AL files.
c. You create another folder called "myWorkspace" 
d. You copy "bar" to your workspace folder.
d. In VsCode you create a workspace project based on "bar".
e. You copy "foo" to the workspace folder.
f. You add "foo" as workspace project in VSCode.
g. Things don'T compile.

What is the dependency relationship. Does "bar" has as a project reference "bar"?

**Comment by fridrichovsky** [comment]
I am using one workspace file for more AL project folders:

MyProjectRootFolder
|__ ALProjectFirstFolder
|__ ALProjectSecondFolder - denpends on ALProjectFirst
|__ MyProject.code-workspace - content { "folders": [	{ "path": "ALProjectFirstFolder" },{ "path": "ALProjectSecondFolder" }] }

I am using MyProject.code-workspace to open workspace in VSC where I can see both folders "ALProjectFirstFolder" and "ALProjectSecondFolder".
This settings I used for my projects and everything worked perfectly. Last version of AL Extension raise mentioned error connected with al packages.

**Comment by fridrichovsky** [comment]
and project ALProjectSecondFolder - depends on testing applications.

**Comment by CptBlaubart** [comment]
@kalberes

I have the exact same symptoms but have a more specific way how i got there for you. Because it used to work. My problem is: this is a full blown productive solution I'm working on and simplifying it to a level where I can share it to you without having to provide the full project including all the .alpackages AND still reproducing the Bug will be very, very time consuming. 

So, before i do that, i hope i can already help you with describing the situation thoroughly and i hope this might help you narrow down the problem. Then i can test some stuff for you if you like because i want to help.. i just cant invest that many hours to do a full-fledged "try and error" on that complexity.

**First of all:**

Even with the bug active you can avoid it, if you launch the workspace with the right file open from the last session.
Those are:
- Any file in the project of the highest dependency-hierarchy that triggers workspace loading.
- any json-file of any of the extensions in the workspace.
I guess it must have something to do with the workspace AND which project in the dependency-hierachy is triggering the processing of the workspace... and maybe there is something different about the handling of al-files and json-files triggering the load process. (could also be the folder-structure, we put all our AL-files in module folders)

btw:
 - You can also avoid it by opening the faulty-extensions from folder instead of workspace.
 - You can completely skip the whole issue if you just copy all the missing extensions into the folders the compiler is looking for them (this is probably what actually happend when @fridrichovsky used download symbols)
 - even if you manually set `"al.packageCachePath": "<absolutepathfromroot>/.alpackages",` it gets ignored and the compiler is still searching in the wrong project folder.
 - if the workspace has been loaded in the faulty stage once, it will not recover whatever you try until you do a `Reload Window` with one of the above mentioned files open
 - It's not just the compiler failing to build the package, i already shows in the "Problems" section as an error.

**Now, the full situation:**

Before the change that caused the problem, we already had 3 extensions in one workspace:
  - CustA
  - CustB
  - CustC

dependencies: 
all 3 of them have dependencies on some extensions we built as a Module system for our customers. For simplicity, assume there is a "framework"-extension that all the extensions in the Workspace depend on.

CustB also had a dependency on CustA and on a 3rdParty extension called ForNAV
CustC also had a dependency on CustA and on a 3rdParty extension called MobileNAV

In this situation, everything worked as expected.

In my recent changerequest, I needed to add another dependency: CustB is now dependent on CustC and on the 3rdParty Extension MobileNAV. And this is when the issue got triggered.

Now, when i open the workspace with an AL in the editor from CustB, it's looking for the ForNAV-alpackages in the alpackages folder of CustC.

p.s.: you can make it even worse in this situation by swapping around the order of the projects inside the workspace file. If i set the order to CustA, CustC, CustB; the error can be triggered by opening anything in the CustC project as well. And the dependencies for CustC are expected to be in CustB's folder.

Post notice: I am aware that we can "simply" avoid all the issues by using the workarounds i described myself in this message. The Problem is that we have a lot of automizations programmed that we'd need to completely rebuild to do stuff like copying all the dependencies into all the folders. And reloading the workspace with specific files, specifically for one single project that random developers will have to work on over the years will be a lot of wasted time of instructing. So i really hope my provided information will help you narrow down the problem... or maybe you can just skip the whole issue by looking for the app.json file belonging to the ALs and starting the load-process based on that file.

Don't hesitate to ask any further questions. I don't mind doing the tests for you on this project, I just want to avoid having to recreate it in a simplyfied version because there are - in the actual project - 12 different dependencies and a lot of IP in those two CustB- & CustC-extensions (they are based on templates we use to customize the usage of those 3rd party extensions for our customers).

We can also have a teams-session, if you like. We just need to find a good time. I'm located in switzerland (GMT+1) and i speak german and english fluently.

**Comment by kalberes** [comment]
What if you have a workspace level-based package cache path? Does it work? 
Btw: There is no difference if the app.json or any Al file is opened for a project. That project will be the one that is the startup project and the project, and all its project references should just load. 
I will set it to triage required nevertheless.

**Comment by CptBlaubart** [comment]
> What if you have a workspace level-based package cache path? Does it work?

Yes! Looks like the Workspace level-based package circumvents the problem by overpowering the default folder. This would be the best solution at the moment as we don't have to teach any manual tricks to each developer.
(we usually don't use that for our projects, but I'm not 100% sure why, gotta ask the DevOps-guys)

> There is no difference if the app.json or any Al file is opened for a project.

I'm not so convinced about this one though. - I've tested this back and forth from several different situations. And i can, very reliably, reproduce the problem when reloading the window with an al-file open. and don't get it with a *.json one in the same project. - I've even tested it by moving *.al files into the project's base folder and other stuff we don't usually do.

Thanks for your help so far. I still think it would be a good idea to look further into it. As there clearly is some unwanted behavior somewhere in there. But our problem is resolvable with the settings on workspace level.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.
