### ISSUE TITLE
New AL Version 8.2.545335 broke "implicit with" quick fix

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#6842]
**1. Describe the bug**
The new version does not provide an autofix for "implicit with" usages in pages.

**2. To Reproduce**

1. Just create a new page with "implicit with" problems. (e.g. add a field without using Rec.Field)
2. Set cursor on a page field.
3. No bulb appears

Working in Version 8.1.540594:
![grafik](https://user-images.githubusercontent.com/7450586/142899032-26f2242c-a6b5-498f-8bba-043293ac9f46.png)

Not working in Version 8.2.545335:
![grafik](https://user-images.githubusercontent.com/7450586/142899146-cc0b8b0e-206f-4dba-b3f5-61e8331e7ba1.png)

**3. Expected behavior**
1. Open a page with "implicit with" problems.
2. Set cursor on a page field.
3. Bulb appears with the option to "Qualifiy with 'Rec'"

**4. Actual behavior**
1. Open a page with "implicit with" problems.
2. Set cursor on a page field.
3. No bulb appears

**5. Versions:**

- AL Language: Version: 
  - 8.1.540594 (working)
  - **8.2.545335 (not working)**
- Visual Studio Code: 1.62.3 (user setup)
- List of Visual Studio Code extensions that you have installed:

Extension | Author (truncated) | Version
-- | -- | --
gitlens | eam | 11.7.0
todo-tree | Gru | 0.0.214
al | ms- | 8.1.540594
xliff-sync | rva | 1.2.0
errorlens | use | 3.4.1
vscode-icons | vsc | 11.7.0

**Comment by thloke** [comment]
Heads up that we'll be releasing a new version of the VSIX that addresses this. The fix will be in version v8.2.550913 (or greater).

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 33156 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
