### ISSUE TITLE
Partial Records issue with subscribing to events in posting codeunits

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/AL#6852]
1. Describe the bug

Potential issue with the partial records and appears to be a change in behaviour between BC18 and BC19.

In my case I extended the Warehouse Shipment Line with a new field. I then subscribed to an event that passed the Warehouse Shipment Line in the Post Whse Shipment codeunit and tried to reference the added field and got the following error:

'JIT loading of field(s) <New Field> failed' 
 
What appears to be happening is that it has decided in doesn't need the fields in the extension so that partial record functionality is not loading them in the posting  codeunit. The record that gets passed in the event is therefore missing these fields. The code in my event subscriber is referencing the field so the partial record functionality is trying to load those fields. The kicker is the physical record was deleted just prior to the event and therefore it errors trying to load the fields.

This is a common pattern in the posting routines where the record being processed is loaded into a variable and passed as a parameter in every event in the posting routine both before and after the actual record is deleted. This may well be the intended behaviour with partial records but in my opinion breaks the extensibility model of being able to safely subscribe to an event

2. To Reproduce
Add a new text field to the warehouse shipment line table in an extension. 
Subscribe to the event  OnAfterReleaseSourceForFilterWhseShptLine in Whse.-Post Shipment codeunit.
Reference new field i.e. if WarehouseShipmentLine.NewField <> '' then

3. Expected behaviour
Should be able to successfully execute code triggered by the subscription.

4. Actual behaviour
Error 'JIT loading of field(s) <New Field> failed' 

5. Versions:
AL Language: v8.2.545335

**Comment by thloke** [comment]
@PhDuck - this is for you.

**Comment by PhDuck** [comment]
Hey @GaryFrostick2 

In the below quote, what do you mean by *it*? The runtime never applies Partial Records on records in codeunits.
> What appears to be happening is that it has decided in doesn't need the fields in the extension so that partial record functionality is not loading them in the posting codeunit.

Therefore, I would suspect this is an manual application of Partial Records through calling the SetLoadFields on a given record. If that is the case, then the caller is responsible for selecting the correct fields. Since passing it to an event makes it impossible to foresee what fields are actually needed this should generally not be done.

In your case where the record is deleted from the database it is even worse, cause we know subsequent JIT loads will fail. I'm wondering if the delete happens on another record instance, since a call to Delete on a record with Partial Records applied will do a JIT load for missing fields before doing the delete, to exactly avoid this scenario.
If the event caller is deleting it on another record, I think we have gotten to the case where we can question if the event caller got it right here.
Partial Record's usage [guidelines](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-partial-records#usage-guidelines ) explicitly says not to use it when doing deletes:

> For performance reasons, it's not recommended to use partial records on a record that will do inserts, deletes, renames, transferfields[...]

On the matter of Partial Records and its compatibility with the current extensibility model:
The same problem already exists with CalcFields, if you call CalcFields before and after the delete. While you might not get an error you may get wrong data (arguably worse), or no data in the case of blobs.

Partial Records has always been a performance feature, which is to be used to speed up reading many rows. I don't fully understand the scenario here, but personally I would never call an event in a loop, so I wonder why it was applied here, where an event is called.

@thloke please close this issue.

**Comment by GaryFrostick2** [comment]
@PhDuck 

I'm not sure you are understanding the issue.

This is a subscription to a standard event in a standard codeunit and the record passed as a parameter is a partial record therefore causing the reported error in the subscriber to the event. The subscriber is only reading the record doing nothing more. SetLoadFields is not used in the standard code unit or the subscriber.

The problem can be easily reproduced using the example I gave.
1) Create a Table Extension to Table 'Warehouse Shipment Line' and add a new field (in my case a text field but it does not matter).
2) Create a codeunit and subscribe to event OnAfterReleaseSourceForFilterWhseShptLine in Whse.-Post Shipment codeunit.
This passes the Warehouse Shipment Line as a parameter. In this read the value of the field added in the table extension.
If <NewField> = '' then Message('Ok'); 

This will trigger the error. 

The behaviour has changed between versions of Business Central and in my option makes subscribing to standard events in some cases unsafe therefore I consider this a bug.

**Comment by PhDuck** [comment]
Completely understood your comment and everything I said in my previous message still stands.

The event publisher should consider the repercussions of using Partial Records together with deleting the record. Or at the very least make sure to call delete on the rec they pass to the event.

**Comment by thloke** [comment]
Closing as per @phduck 's comment. Also, this is out of scope for this repository, since it's to do with runtime behaviour rather than the AL language and/or compiler itself.
