### ISSUE TITLE
I cannot unpublish an AppSource extension

### ISSUE THREAD

**Issue by CarloAxians** [microsoft/AL#6854]
I have installed an AppSource extension and want to uninstall and unpublish this.
When I uninstall the AppSource app it is removed from the list and I cannot unpublish it.

When I then try to install the same app, but a newer version in Dev scope I get the error that it is already installed.

**Comment by thloke** [comment]
It's by design that you are unable to unpublish appsource extensions, as they can be used by other tenants on the same SaaS cluster. 

You should be able to publish a dev version of the appsource app, **if there are no appsource apps that depend on that app.** If there are, you'll need to uninstall them first.

The situation we want to avoid is:

App A (Appsource) -- depends on --> App B (DEV)
