### ISSUE TITLE
CodeCop resolving AL0677 leads to AS0022.

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#6867]
**1. Describe the bug**
When a procedure is marked as protected within a codeunit, you'll receive the following:
 warning AL0677: The member 'methodname' in object 'objectname' cannot be declared as protected in object type 'Codeunit'. This warning will become an error when targeting a runtime with version '10.0' or higher.
If this was a published procedure and you try to resolve the warning by marking the procedure local, you'll receive this from appsourcecop:
error AS0022: The external scope in 'methodname' cannot be removed or changed to 'internal' because it will break dependent extensions. Note that adding an access modifier ('local', 'protected', or 'internal') overrides the argument in 'Scope'.

**2. To Reproduce**
Steps to reproduce the behaviour:

1. Create a method with protected in a codeunit.
2. Publish.
3. Create a new version with the access changed to local.
4. Receive AS0022 from appsourcecop

``` AL
codeunit 51234 "objectname"
{
    protected procedure methodname()
    begin
        Message('protected!');
    end;
}
```

**3. Expected behaviour**
Going from protected to local on a codeunit should be permitted behaviour. Protected on a codeunit does not allow dependencies to access the procedure. I believe this is because doing so on a page would break page extensions, however on codeunits this should be permitted.

**4. Actual behaviour**
Cannot build as the access change is not permitted.

**5. Versions:**

- AL Language: 8.2.552672
- Visual Studio Code: newest
- Business Central: 19.0
- List of Visual Studio Code extensions that you have installed: irrelevant

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**6. Current Solution:**
Obsolete procedure, create local version?

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 33780 and VS Code Extension Version 3.0.143328. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by qutreson** [comment]
AL0677 was introduced because the AL compiler allowed you to create protected variables in codeunits. For objects which can be extended like pages, tables or reports, this allows you to expose some methods only to the extension objects. However, since AL doesn't have codeunit extensions, the protected keyword is acting the same way as the local keyword. In order to fix the diagnostic, the procedure should then be made local.
