### ISSUE TITLE
Error on Posted Sales Invoice While Using Send Document Functionality for Multiple Records With Filter 

### ISSUE THREAD

**Issue by Rsaurav001** [microsoft/AL#6868]
Step1: Create Table Extension For “Sales Invoice Header” table  and add 1 Field to it.

![image](https://user-images.githubusercontent.com/92705465/145552428-0f42a5c1-0716-4ee2-ba09-c6236ced4714.png).

Step 2: Create Page Extension For "Posted Sales Invoices" Page and add the extension field to it.
![image](https://user-images.githubusercontent.com/92705465/145552555-f98f7440-0506-49f5-8197-e3189ac05065.png)

Step 3 : Now Publish the Package.

Step 4: Go to Posted Sales Invoice Page ,add filter from global filter Pane , select multiple records from Posted Sales Invoice and the click ‘send’ button under ‘Print/Send’ Group as Shown in screenshot.
![image](https://user-images.githubusercontent.com/92705465/145552644-144fc389-fa3a-4f82-8a75-0ee408b6389b.png).

Step5 : Pop up Window will open by clicking on the send button ,set below values to field and click on ‘OK’.
![image](https://user-images.githubusercontent.com/92705465/145552721-3ee850b0-ada1-41d0-8a7c-9347c129d1b5.png)

Step 6: By Clicking on OK button system will throw below error
![image](https://user-images.githubusercontent.com/92705465/145552773-ce7a0b9f-9286-4403-af84-d4dd3a06449b.png)

**Comment by dnpb** [comment]
So this only happens if that field is added? Does it happen with all field types? Does it happen if the field is in the table but now shown on the page? etc.

Anyway, you should check the Event Log of that service, and it might indicate the problem in there.

**Comment by Rsaurav001** [comment]
it happens with all field type and it only happens when field is added to page. Event log doesn't show anything.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime.
