### ISSUE TITLE
can't Go To Definition of fields used in key

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6872]
TSIA really. Putting a field in the list of those included in a `key` and then trying to Go To Definition on it does not work:

![image](https://user-images.githubusercontent.com/63455896/146181065-bfd9100b-6374-47c7-8d5c-3c572da979b9.png)

It would be expected and useful if it did, so we could quickly jump e.g. from a table extension's key to the field it uses, or even just from a table's own key to its field, potentially a lot further up the file.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.2.552672
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36381 and VS Code Extension Version 9.0.584740. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
