### ISSUE TITLE
AW0007 shows; "The FlowFiter field '<fieldname>' in the repeater control '<control>'cannot be displayed by the Web client. AL(AW0007)

### ISSUE THREAD

**Issue by abc-RKN** [microsoft/AL#6877]
**Problem description**
``` AL
pageextension 50052 pageextension50052 extends "Sales Invoice Subform"
{
    layout
    {
      
        addafter("Line Discount Amount")
        {
            field("Shortcut Dimension 3 Filter"; "Shortcut Dimension 3 Filter")
            {
                ApplicationArea = All;
                Style = Strong;
                StyleExpr = TRUE;
            }
            field("Shortcut Dimension 5 Filter"; "Shortcut Dimension 5 Filter")
            {
                ApplicationArea = All;
                Style = Strong;
                StyleExpr = TRUE;
            }
        }
    }
}
```

**Expected behavior**
Nothing; but if the error is justified:
The FlowFi**L**ter field 'Shortcut Dimension 3 Filter' in the Repeater control 'Control1' cannot be displayed by the Web client.
(so FLOWFILTER instead of FLOWFITER)

**Actual behavior**
Error triggers; "The FlowFiter field 'Shortcut Dimension 3 Filter' in the Repeater control 'Control1' cannot be displayed by the Web client."  

**Versions:**

- AL Language:    8.2.552672
- Visual Studio Code:   1.16.1
- Business Central:  18.1

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 34448 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
