### ISSUE TITLE
FilterGroup(4) is not behaving same as described

### ISSUE THREAD

**Issue by amulaj** [microsoft/AL#6882]
**1. Describe the bug**
FilterGroup(4) is not behaving same as described in the Microsoft documentation: 
https://docs.microsoft.com/en-us/dynamics-nav/filtergroup-function--record-

I am referring to the following text in the documentation: 
"If, for example, a filter has been set on customer numbers 1000 to 2000 in group 4, then the user can set a filter that delimits this selection further, but cannot widen it to include customer numbers outside the range 1000 to 2000."

**2. To Reproduce**
Step 1: Create a new Project with "AL Go"
Step 2: Insert the following code: 
`pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    begin
        Rec.FilterGroup(4);
        Rec.SetFilter(City, '%1|%2', 'Luzern', 'Meggen');
        Rec.FilterGroup(0);
    end;
}

pageextension 50101 VendorListExt extends "Vendor List"
{
    trigger OnOpenPage();
    begin
        Rec.FilterGroup(2);
        Rec.SetFilter(City, '%1|%2', '', 'Fontannen b. Wolhusen');
        Rec.FilterGroup(0);
    end;
}`

Step 3: Publish this App and try to filter the City field in the Customer Table to only one value. For example "Luzern"

Step 4: Sort the Customer List again

You will see that the filter that is added from the user is not anymore working instead the filter that was added with the FilterGroup(4) from the AL Code is applied. 

**3. Expected behavior**
If, for example, a filter has been set on customer city Luzern or Meggen in group 4, then the user can set a filter that delimits this selection further, but cannot widen it to include customer cities outside the range. Even if the user sorts the customer list after he has applied the new filter to delimit the selection further.

**4. Actual behavior**
The actual behavior is that after the user sorts the customer list the applied filter is gone and the filter from FilterGroup(4) is added again. So the list shows again all records. 

**5. Versions:**

- AL Language: v8.2.552672
- Visual Studio Code: 1.58.1
- Business Central: Version: CH Business Central 19.2 (Plattform 19.0.32956.34411 + Anwendung 19.2.32968.34456)

#https://github.com/microsoft/AL/issues/1653

**Comment by thloke** [comment]
Hi, thanks for raising this issue and the detailed reproduction steps. Unfortunately this issue is to do with the runtime behaviour of Business Central, and not the AL language itself, so it is out of scope of this repository. To get this issue to the correct team, please raise this issue as a support case, or post on collaborate. 

To open a support case, you can: 

 

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company 

 
If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using.
