### ISSUE TITLE
Multiple published extensions match the specified parameter values.

### ISSUE THREAD

**Issue by 0Mario0** [microsoft/AL#6886]
Hello everyone,

I having a problem with the designer apps in BC 16.1 and multiple extensions.
If you create accidentally 2 apps with the same name (1 lower- and 1 uppercase) you can't use the Sync-NavApp -Mode clean command. (Not possible in the newer BC versions)

Example:
I design the item page with the "Design" button and add the field decription 2.
Then save the new design with the name: "description2" and publisher: "default". 

This app is accidentally removed and then the app is created again, but with the name: DESCRIPTION2 and publisher: DEFAULT (UpperCase) 

Now the App is no longer needed and we have to remove the app. 

Uninstall and remove is no problem. But when you try to start the Sync-NavApp -mode Clean, you always get the error message: 

"Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use." 

I also tried using a AL-project and recreate the app. (I downloaded the Sourcecode and created a AL-project for this source). I was hoping the "schemaUpdateMode:recreate" remove all other references, but VSC also crashed with the same error -> multiple apps...

Is there a workarround or a way to remove the multiple apps?
Thanks in advance.

**Comment by thloke** [comment]
Hi. This is out of scope for this repository since it concerns an older version of BC. We suggest that you open a support case and work with our customer support team to gather all the information necessary to fix this problem.   

Please read this post on how to file an issue: https://cloudblogs.microsoft.com/dynamics365/it/2019/09/25/new-process-to-submit-support-requests-for-dynamics-365-business-central/
