### ISSUE TITLE
Implementing Interface with Complex Return Type Creates Incorrect Signature

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#6892]
See https://github.com/jimmymcp/interface-implementation-bug for repo. Clone the repo, open the codeunit and choose the "implement interface" quick fix.

A procedure is created but with the wrong signature.

![Implementing Complex Interface Bug](https://user-images.githubusercontent.com/19267298/149805590-a3dd7005-d56d-4efa-91c3-818498f8c870.gif)

AL Language: v8.2.552672

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36347 and VS Code Extension Version 9.0.584205. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
