### ISSUE TITLE
Inconsistent Read Error on Field in Event Handler OnAfterModify

### ISSUE THREAD

**Issue by LNitzsche** [microsoft/AL#6893]
Description:

After installing/publishing an extension you may get an "Inconsistent Read Error" when accessing specific fields in a subscriber to the OnAfterModify event.

This error arises beginning with version 19.0. and is also in 19.2. 
Version 18.0 - 18.8 does not have this error.

To reproduce the error on a standard CRONUS DB:

- Install the example extension using VSCode.
- Open Page "Firm Planned Prod. Orders" (9325)
- Select order 1010005. 
- Select Line/Routing.
- In the Routing page (99000817) change the "Starting Date-Time " or "Ending Date-Time" field.

Result: The event handler in the example crashes when accessing "Ending Date" or "Starting Date" field.
          The page 99000817 is closed.
          
![grafik](https://user-images.githubusercontent.com/41184443/149928691-d3cfcf74-6da1-4174-82b7-edac95e0dea2.png)

This is the error callstack:
CheckEvent(CodeUnit 50100).ProdOrderRtngLineOnAfterModify line 14 - InconsistentRead by Default publisher
"Prod. Order Routing Line"(Table 5409).CalcStartingEndingDates line 14 - Base Application by Microsoft
"Prod. Order Routing Line"(Table 5409)."Starting Time - OnValidate"(Trigger) line 2 - Base Application by Microsoft
"Prod. Order Routing Line"(Table 5409)."Starting Date-Time - OnValidate"(Trigger) line 4 - Base Application by Microsoft
"Prod. Order Line"(Table 5406).ShowRouting line 13 - Base Application by Microsoft
"Firm Planned Prod. Order Lines"(Page 99000830)."Ro&uting - OnAction"(Trigger) line 2 - Base Application by Microsoft

The error is difficult to reproduce because it only occurs directly after installing an extension and only on a very specific page (99000817).
After the first occurrence the error does not come again until you have installed some other extension.

In practice, it is unlikely that a user will receive this error. 
But it points to an internal problem in the publishing process for extensions.

- AL Extension Version: Version: 8.1.540594

- Server Version:  W1 19.2 (Platform 19.0.32956.33475 + Application 19.2.32968.33504)

See attached example.

[InconsistentRead.zip](https://github.com/microsoft/AL/files/7888696/InconsistentRead.zip)

**Comment by PhDuck** [comment]
A bit of background information on errors during Partial Records, read [this](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-partial-records#preventing-inconsistent-read-and-jit-loading-errors)

What is happening here is that you are reading a field "Starting Date-Time" that has changed in the database between your original load and the JIT load that happened. JIT loads only happen when you access a field that wasn't originally loaded.

When I read the code it makes total sense:
1. You load out "Prod. Order Routing Line" without all the fields (this might be automatically done if on a list page) or could be through explicitly.
2. You call Modify on that rec.
3. Modify will make rec -> xrec (so now xrec isn't fully loaded).
4. Database is updated.
5. You access xrec which is missing some field, causing a JIT load to happen. Look at fields accessed in ProdOrderRtngLineOnAfterModify.
6. The field "Starting Date-Time" was changed in the DB, so the JIT load fails since the data else would else be inconsistent.

The concept of inconsistent is very important here:
Lets say record was read as this:
A | B | <unloaded> | 0 | 1

The record is then modified changing B to C
A | C | <unloaded> | 0 | 1

On xrec the it still looks the same as before:
A | B | <unloaded> | 0 | 1

The JIT load the happens on xrec and compares 
A | B | <unloaded> | 0 | 1
A | C | <unloaded> | 0 | 1

Because B changed to C, and error is thrown since one would else get inconsistent data!

We will soon update the error message to make it more clear.

**Comment by LNitzsche** [comment]
Thank you for this explanation.
The remaining question is: why does this happen only after installing or publishing any extension?
After getting this error the first time the error is not raised any more (until next publishing of an extension).
If this is a caching problem there could be readable but outdated values in the xRec.
This may be a bigger problem because this is NOT detected at runtime!

**Comment by LNitzsche** [comment]
One more explanation for clarity:
I am changing the "Starting Date-Time" in the routing line using the BC dialog.
But in the OnAfterModify event handler I try to read the xRec."Ending Date" field which raises this error.
(in the callstack "Starting Date-Time" is blamed for raising the exception, but this is not the (whole) truth).
xRec."Starting Date-Time" and xRec."Starting Date" CAN be read in the event handler without raising an error.
Conclusion for my application is:
- if "Starting Date-Time" was changed don't try to read xRec."Ending Date" because it may be invalid
- if "Ending Date-Time" was changed don't try to read xRec."Starting Date"

**Comment by ajkauffmann** [comment]
Did some investigation as well because I ran into the same error in a different situation.

FIrst of all, it's not related to installing the extension. The subscriber codeunit in the example is a single instance, that's why it didn't refresh until the extension was installed again. Starting a new session or restarting the service is enough to get the same error again.

In order to test it, I've created an event subscriber for the OnBeforeModify event to check if the field "Ending Date" was loaded. The very first time that the event is executed the field is NOT loaded.

By the way, the event executed because of a Modify(true) in procedure CalcStartEndingDates in table Prod. Order Routing Line.

I found a workaround by setting this code in the OnBeforeModify trigger:

```AL
    [EventSubscriber(ObjectType::Table, database::"Prod. Order Routing Line", 'OnBeforeModifyEvent', '', false, false)]
    procedure OnBeforeModify(var Rec: Record "Prod. Order Routing Line"; var xRec: Record "Prod. Order Routing Line"; RunTrigger: Boolean)
    begin
        xRec.AddLoadFields("Ending Date");
        xRec.Find('=');
    end;
```

Remarks:
- Only AddLoadFields was not enough, the Find('=') was required as well
- It's not required to do the same on Rec. This proves that Rec is not passed 1 to 1 to xRec including the state of loaded fields.
- It still smells like a bug that you need to call AddLoadFields on xRec... 😏

**Comment by PhDuck** [comment]
The original comment of mine still stands and this repro exhibits no platform bug.

Let me address the remarks by @ajkauffmann:
1. The reason you need the Find after the AddLoadFields is that the AddLoadFields doesn't actually access the database, it merely changes the record's state in preparation for the next Get/Find*. In a similar manner to SetLoadFields.
2. The relationship between XRec and Rec is a complicated one. I might have to write a blog post on the subject since the behavior is rather surprising. The records state is shared between XRec and Rec, while the data isn't.
2.1 The statement is wrong, since when the OnBeforeModify event is called, the capture and assignment of XRec has already happened.
3. You could also have called rec.SetLoadFields(x0, x1, ..., xn, rec."Ending Date") or rec.AddLoadFields(Rec,"Ending Date") before the initial call to Get/Find. This is again because the record state is shared between XRec and Rec.


Generally passing a rec with Partial Record applied to an event is a bit risky since it isn't known what fields the subscribers will need. This is double risky when reading xrec after a modify call.

@PooyaKharamesh please close this issue.

**Comment by kalberes** [comment]
closing as requested
