### ISSUE TITLE
Report DataItemTableView allows invalid data

### ISSUE THREAD

**Issue by srttel** [microsoft/AL#6898]
**1. Describe the bug**
AL environment and compiler does not give an error when adding an invalid DataItemTableView in a report.
In CAL you are not allowed to enter 0D as for a date field.

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
'0D' is not a valid date.
---------------------------
OK   
---------------------------

 
In AL it is posible, and no error is given when entering this values, packaging or pushing to the system.
The resulting error is only thrown when you run the report that the date is not valid.

**2. To Reproduce**
Add a Date field (My Date Field) as new field to the sales header table.
Create the following report and publish it to the system.

``` AL
report 50103 "Sales Headers"
{
    UsageCategory = Administration;
    ApplicationArea = All;

    dataset
    {
        dataitem(SalesHeader; "Sales Header")
        {
            DataItemTableView = where("My Date Field" = const(0D));
            column(No; "No.")
            {

            }
        }
    }
}```

**3. Expected behavior**
Like in CAL where a compiler error raised that 0D is not allowed I expect AL gives some similar errors,

**4. Actual behavior**
You can publish the report to the system and only getting an error during runtime.

**5. Versions:**
BC 19.2

- AL Language: v8.3.570094
- Visual Studio Code:1.63.2
- Business Central:19.2

**Comment by dnpb** [comment]
I think in those expressions, to filter for value `0D`, you must do `const('')`. Not sure though. Agree it should be an error at build time if it won't work at run time. Sadly, many things aren't...

**Comment by thloke** [comment]
Thanks for raising this, we should definitely block this at runtime. Unfortunately since this is not a (recent) regression but something that has been around since C/AL, it's unlikely that we'll prioritize this soon. I'll keep this issue open in case we do manage to get to it in the next few months, but if it's something that you'd like prioritized faster it would be best to go through customer support as they can create a support request that will give us time to work on this issue specifically.

**Comment by thloke** [comment]
Update - this issue has been raised by our support team and is now in our internal queue. :)

**Comment by dnpb** [comment]
> Thanks for raising this, we should definitely block this at runtime.

or build time, even? ;-)

**Comment by thloke** [comment]
> > Thanks for raising this, we should definitely block this at runtime.
> 
> or build time, even? ;-)

Indeed, I meant at build-time, not runtime. ): ...fingers working on muscle memory too much.

**Comment by lohndorf** [comment]
Hello,

The Runtime error you get, is:
The format of the Date '''' does not match **your device's date settings.**

The al compiler has no idea of the device settings where an app will run. C/AL was an onprem compiler.
This is not a compiler issue. Maybe a report runtime to recognize null dates, but then this is a new feature, since 0D was not valid even in C/AL.

What do you think?

**Comment by jensmpmsft** [comment]
Due to prioritization, we are currently not planning to change the behavior of this. '0D' is syntactically a valid Date, so the compiler accepts it. Having the compiler accept a filter criteria does not guarantee that it is a valid runtime filter - particularly because triggers can modify the filters / table views.

In the future we may change the runtime handling of this - but for now, you cannot rely on the compiler to guarantee that it works at runtime, if it is not a type mismatch
