### ISSUE TITLE
Error when using ShowAsTree property

### ISSUE THREAD

**Issue by petroLubchenko** [microsoft/AL#6900]
**1. Describe the bug**
When the source table of the page contains lots of data (depending on the size and count of shown fields on the page, approximately from 10000 to 100000 records), the last record cannot be selected using the FindLast function or using UI. Instead, the error is shown. No additional information was found in the logs.

**2. To Reproduce**
The issue can be reproduced using page 9900 (**Code Coverage**). When several objects are loaded (for instance, by pressing the Load country objects action), this error is displayed when the last record is selected using the **Ctrl+End** shortcut.

**3. Expected behavior**
The last record is selected on the page.

**4. Actual behavior**
The client hangs for some time (during the data loading) and the following error is shown:
![image](https://user-images.githubusercontent.com/22105115/150361147-f9a474be-54a4-4953-889b-6e6ee4498f97.png)

**5. Versions:**

- AL Language: 8.3.570094
- Visual Studio Code: 1.55.2
- Business Central: 18.0.23013.23795, 19.2.32968.33504

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime.
