### ISSUE TITLE
Publish fails silently #5315

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL#6909]
**Describe the bug**
#5315 
None of the functions that publish the extension complete. They do the compile and stop.
The created extension can be successfully published using the powershell scripts.

**To Reproduce**
Press F5 on a project that was working fine with the previous (v3.x.x) AL extension

``` AL Code to reproduce the issue ```
All projects when publishing with 4.0.182565 AL extension or later

**Expected behavior**
Previous working behaviour.

**Screenshots**

**5. Versions:**

 - AL Language: Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 4.0.182565
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

 - Business Central: Version 15 latest docker image (15.0.36117)

----

@thloke @atoader @kalberes 
BAD Bot.

A trivial test would show that bug is still present.
This still needs to be switched from the Json data-interchange format loader to one suitable for configuration files, for example the loader used for the files  `settings.json`, `launch.json`, `ruleset.json`, `AppSourceCop.json`.

If the JSON interpreter is any good this should be a trivial change to the loader init.

As many people have said, if a file format does not support comments it must NOT be used as a configuration file format.
As Douglas Crockford has said, if you want to use JSON for a config file use JSMIN to allow Javascript comments!

**Comment by kalberes** [comment]
I will re-add the bug state. And let's see where it gets.

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern. 

For this issue, the reason why it happens is (as pointed out) we use a custom parser for the app.json file. We do not plan to change this in the near future.

The best way to get further traction on this issue is to raise it in [BCIdeas](https://aka.ms/BusinessCentralideas). If it gets enough votes, we can then use that as justification to prioritize this issue.
