### ISSUE TITLE
why we are not able to see "Removed" in obsolete state property in code units 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/AL#6915]
Hi All 

 

I have a question here. I have two apps where I have two code units:  with same name & different IDs 

 

one app is having :

   
![image](https://user-images.githubusercontent.com/38460823/152112752-a819f0d0-d0c6-4992-bf65-2f444d5bb632.png)

another is having: 

 
![image](https://user-images.githubusercontent.com/38460823/152112763-e272b134-84a5-4408-87df-473dc1e66cff.png)

 

but i tried to install both apps it gives me error like this 

 

The object name 'BssiTelemetry' can only appear once for the type 'Codeuints'. The same object exists in both extension 

 

that's fine. but now the problem is when i tried to obsolete one of the code unit then it is not giving me the option for "Removed" it gives me error like 

 
![image](https://user-images.githubusercontent.com/38460823/152112790-8d0370be-8b80-47d9-bbcb-09e91b179d8b.png)

 

if Microsoft says that, Obsolete property can be applied to table, pages, fields, Codeuints so we must able to use the both properties. 

 

now we can not delete the object from the app neither we can not use the removed property then how we can resolve this issue.

**Comment by dnpb** [comment]
Yes, the property is applicable to codeunits, but only values No or Pending:
![image](https://user-images.githubusercontent.com/63455896/152137922-e5784cc9-4f78-4c28-98c8-adebb10d08d3.png)

the idea is that because this doesn't change schemas, and hence doesn't have to keep columns around but marked removed etc. - you can first mark as Pending and later just remove outright.

> now we can not delete the object from the app

Why not? What happens when you try?

**Comment by qutreson** [comment]
As explained above, once a codeunit has been marked as Obsolete Pending, it can simply be removed in the next version. The Obsolete Removed state only applies for table and table fields because it isn't possible to remove them from the code (removing would impact the database schema and isn't allowed in SaaS).

I am then closing this issue as it is expected to not have the ability to mark a codeunit as Obsolete Removed.
