### ISSUE TITLE
code within a CASE's ELSE BEGIN block is indented by 1 tab too far

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6920]
'reopening' https://github.com/microsoft/AL/issues/5828

**Describe the bug**
The title says it all.

**To Reproduce**
Type a `case` statement whose `else` block is a compound statement and hence should read `else begin` as per the (outdated but presumably still instructive) [AL Control Statements](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-control-statements) documentation:

![image](https://user-images.githubusercontent.com/63455896/80098720-455aef80-8565-11ea-9ef1-56844f975b06.png)

Let VS Code auto-format this. The lines between the `else begin` and its `end;` are indented 2 tabs. Another example from real code:

![image](https://user-images.githubusercontent.com/63455896/80098847-70ddda00-8565-11ea-81e7-5f214a28a8a4.png)

**Expected behavior**
One would expect the lines between the `else begin` and its `end;` line to be indented only one tab stop further, just as the outdated documentation indicates we should (substituting 2 spaces in C/AL with 1 tab in AL).

Alternatively, one would expect to be guided to put the `else` on a separate line from the `begin`, and indent those just as with the preceding values tested by the `case` statement. But that's not what the documentation indicates we should do.

**5. Versions:**
```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.3.570094
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by BrianThorChristensen** [comment]
This also applies to repeat until blocks. And it is not limited to one tab stop. We get anywhere from one to ten tab stops extra indentation. Makes the code difficult to read. And we have to deal with commits to devops that only contains useless indentations.

**Comment by dnpb** [comment]
There is a new bug on here for that.
In the meantime you can just downgrade the VS Code AL extension, and not deal with this bug in git diffs.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42620 and VS Code Extension Version 10.0.642137. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
