### ISSUE TITLE
OData schema - Missing information about enums in /$metadata

### ISSUE THREAD

**Issue by matkolisiak** [microsoft/AL#6926]
**1. Describe the bug**
I am not able to get information about all options of enums in /$metadata.
All I get is only, that it is string or integer field.

**2. To Reproduce**
Get odata metadata document.

**3. Expected behavior**
I would expect list of all options of enum, like this:
![image](https://user-images.githubusercontent.com/41210405/152635218-6491f402-2be3-46bc-bc9e-ca722f96d5b0.png)
 
**4. Actual behavior**
Actually, I get no information about all options of enums.

**5. Versions:**
all versions

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime.
