### ISSUE TITLE
CalcFields and CalcSums auto-complete/Intellisense stops working after the first two fields, i.e. broken on third onwards

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6930]
Try typing this out. You'll see that the first two fields in each call offer autocomplete suggestions from the table, but the rest don't. Very irksome!

Please check if other functions are affected by this limitation too. Thanks :-)

```al
codeunit 50100 Test
{
    trigger OnRun()
    var
        GLEntry: Record "G/L Entry";
        Customer: Record Customer;
    begin
        GLEntry.CalcSums(Amount, "VAT Amount", "Debit Amount", "Credit Amount");
        GLEntry.CalcSums("Debit Amount", "Credit Amount", Amount, "VAT Amount");

        Customer.CalcFields(Balance, "Balance (LCY)", "Balance Due", "Balance Due (LCY)");
        Customer.CalcFields("Balance Due", "Balance Due (LCY)", Balance, "Balance (LCY)");
    end;
}
```

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.3.570094
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by dnpb** [comment]
@kalberes In what way is this not a bug? Is VS Code the problem, not the AL extension?

**Comment by kalberes** [comment]
In every way it is a "bug" in the AL language server. The only change is that we may not mark issues as bugs.  Rather we would triage them, and if accepted we will fix them.  Nothing has changed but some terminology.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.46839.0 and VS Code Extension Version 11.0.683951. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by dnpb** [comment]
Thanks a mil!
