### ISSUE TITLE
XmlElement.SelectNodes crashes BC if xpath doesn't evaluate to a node set

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6938]
See issue #5747 that was closed without being resolved.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39376 and VS Code Extension Version 10.0.612904. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
