### ISSUE TITLE
XmlElement.SetAttribute, parameter with a space crashes BC

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/AL#6939]
Code to reproduce:

b: XmlElement;

b := XmlElement.Create('fail', '', 'stuff');
b.SetAttribute(' space', 'very fail');

Crashes BC, due to attribute name starting with a space.

Related to #6938 and #5747 that was reported two years ago and still not fixed.

Maybe just surround everything XML-related with try-catch if there's nothing else to be done..?

Server instance: BC
Category: EventSubscription
ClientSessionId: 2928c040-4f41-4bd6-a140-c1475cdb2e5b
ClientActivityId: 45430298-e1e1-ab44-bbc7-35506c5ca793
ServerSessionUniqueId: c38c8e22-c06d-4837-9c14-06a0e7f3a055
ServerActivityId: e273fb58-a185-4878-9e6d-5680f41d3b5e
EventTime: 02/19/2022 13:38:02
Message (XmlException): EventSignature failure: SubScriber assy = Microsoft.Dynamics.Nav.BusinessApplication.Codeunit73003, COD_73003_C2818602170341FC29CA7CFE85DD3E9A3825462E78F36CC6C753A3DBA52E875F, Version=19.0.31889.34410, Culture=neutral, PublicKeyToken=null, target assy = Microsoft.Dynamics.Nav.BusinessApplication.Codeunit7
3003, COD_73003_C2818602170341FC29CA7CFE85DD3E9A3825462E78F36CC6C753A3DBA52E875F, Version=19.0.31889.34410, Culture=neutral, PublicKeyToken=null, Subscriber signature = 'System.Void Microsoft.Dynamics.Nav.BusinessApplication.Codeunit73003.MyProcedure()', target signature = 'Microsoft.Dynamics.Nav.BusinessApplication.Codeunit7300
3Finvoice Common[ID=73003]()'
RootException: XmlException
Name cannot begin with the ' ' character, hexadecimal value 0x20.
ExceptionStackTrace:
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39376 and VS Code Extension Version 10.0.612904. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
