### ISSUE TITLE
MissingTypeSymbol compiling in v20

### ISSUE THREAD

**Issue by oscarfernandezkurago** [microsoft/AL#6942]
**1. Describe the bug**
We´re getting var __MissingTypeSymbol__ compiling our project in v20, in v19 compiles fine.

**2. To Reproduce**
Create 3 projects:

- Project 1: basic dependencies and defines an enum
- Project 2: depends on Project 1 and defines a codeunit with a procedure thar recieves a parameter of the type defined in Project 1
- Project 3; depends on Project 1 and 2, defines a pageextension that tries to call the procedure defined in the Project 2
[Link to gitHub repository](https://github.com/oscarfernandezkurago/BCv20)

**3. Expected behavior**
Compile with out errors.

**4. Actual behavior**
Error AL0133: Argument 1: cannot convert from 'Enum TestEnum' to 'var __MissingTypeSymbol__'

**5. Versions:**

- AL Language: v9.0.578744
- Visual Studio Code: 1.64.2
- Business Central: 20.0.36137.0

**Comment by kalberes** [comment]
I have no repro on this on the latest from v20.
What is your active project that produced teh error? That is the project that gets built. I was building Testv20_2
![image](https://user-images.githubusercontent.com/12760483/154942735-7b07e233-60d5-400b-8f8e-212d8af34f3d.png)
What are your al settings?

**Comment by oscarfernandezkurago** [comment]
I´ve tested the **al.incrementalBuild** set to true and the compilation error has gone. Thanks for your fast response.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 36494 and VS Code Extension Version 9.0.585894. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
