### ISSUE TITLE
AL allows adding chartpart, which can never be rendered by the Web Client

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#6951]
![image](https://user-images.githubusercontent.com/63455896/155332346-f5f49351-1e44-4c7e-8772-21c7c384781f.png)

There is no error, despite

- the made-up `chartparttype`, which isn't defined anywhere
- the fact that the Web Client has never supported `chartpart`s, and now that's the only client there is...

Lack of clarity on this leads to repeated questions, such as
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1619878328786944

and the solution will not be documentation, per
https://github.com/MicrosoftDocs/navdevitpro-content-pr/issues/2028#issuecomment-1048011793

Why does the compiler let this through? Is it reserved for possibly being added back in the future?

Either way, I would expect apps built for runtimes that can't possibly show `chartpart`s to error at build-time if the user tries to add a `chartpart`. Anything else just wastes folks' time.

Cheers :-)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.3.570094
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```
Internal work item: [AB#428828](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/428828)

**Comment by EmilDamsbo** [comment]
Closing this issue as we currently have a lot of open items which have a much higher priority. That is not to say that we will never fix this, but for now this is being down-prioritized and closed as won't fix.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26.0.24500.0 and VS Code Extension Version 15.0.1147073. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
