### ISSUE TITLE
AA0210 should not warn about virtual tables, e.g. "Field does not contain a key with the field FieldName"

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6959]
AA0210 warns if we sort by something that has no key in the table, but the table is virtual, so surely keys don't matter...? and it's system, so we can't add one anyway.

So, e.g. if I want to sort marked fields by name, I have to add 2 ugly lines temporarily `#pragma`ing away this warning:
![image](https://user-images.githubusercontent.com/63455896/156141266-dae87def-7192-4de4-97c5-bc9f55400b7e.png)

Probably the analyser should ignore virtual tables. Mads said this here:
https://github.com/microsoft/AL/issues/6318#issuecomment-735419799

Thanks for considering! 

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.4.586670
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42332 and VS Code Extension Version 10.0.640052. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
