### ISSUE TITLE
Unable to debug files with a forward slash in the name

### ISSUE THREAD

**Issue by cbrandemann** [microsoft/AL#6972]
Please include the following with each issue:

**1. Describe the bug**
Its not possible open or debug files with a forward slash in the file name.

**2. To Reproduce**
1. Open procedure table Job.dal in vscode
2. Goto procedure CreateInvtPutAwayPick()
3. With Goto definition its not possible to open "CreateInvtPutAwayPickMvmt: Report "Create Invt Put-away/Pick/Mvmt";"
    Debugging this object is also not possible

**5. Versions:**

- AL Language: v9.0.587938
- Visual Studio Code: 1.64.2
- Business Central: Microsoft_Base Application_20.0.37145.0

**Comment by tyurm** [comment]
Hello,
I have got the same issue with codeunits that have "Yes/No" in the name, for example "Cancel PstdPurchInv (Yes/No)", and others.

It is not only about debugger, it is impossible to investigate/read code which use procedures from these codeunits.

Let me know if I you need any additional information.

**Comment by dnpb** [comment]
Yes, we can't browse into such objects from the .app file. I get this:

> `cannot open al-preview://allang/project_customer_main/Codeunit/61/Sales-Disc.%20%28Yes/No%29.dal. Detail: Unable to resolve text model content for resource al-preview://allang/project_gritit_main/Codeunit/61/Sales-Disc.%20%28Yes/No%29.dal`

Objects without offending symbols such as `/` work OK.

**Comment by LucVanDyck** [comment]
Any idea when this bug is fixed? Pretty annoying to not be able to debug standard BC code ...

**Comment by dnpb** [comment]
see https://github.com/microsoft/AL/issues/6999#issuecomment-1098874552
> Hopefully the next vsix release will have a fix for it.

**Comment by tyurm** [comment]
@LucVanDyck if you work with BC19, you can roll back AL Language extension to 8.4

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39197 and VS Code Extension Version 10.0.611940. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by jwikman** [comment]
And this will be backported to v9, right @JesperSchulz? 🙂

**Comment by JesperSchulz** [comment]
It was backported to 20.x. Should be out with 9.0.611415

**Comment by jwikman** [comment]
Thanks @JesperSchulz!

**Comment by kalberes** [comment]
Only F12 has fixed with teh vsix version debugging not. Since that is an NST change when fixed will only be backported to 20.x

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 39623 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by kalberes** [comment]
Debugging should also work with this fix
