### ISSUE TITLE
Doc for "Table System fields" says audit fields like SystemCreatedAt can be used in keys, but AL gives errors (AL0306)

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#6977]
[This page](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-system-fields) says

> It's possible to use audit fields in a key. The platform doesn't automatically index these fields in any way.

...but if I want to add a key on `SystemCreatedAt` to avoid an info warning when sorting by that on a page, I can't, as apparently my own table can't find its own 'implicitly available' audit field... and the same goes for the other 3 audit fields too:

![image](https://user-images.githubusercontent.com/63455896/158787451-a784a934-923d-4b5a-9343-7c4393755fb3.png)

Is this in reality intended to work? If so, please let newly declared tables do what the documentation says we can. If not, let's arrange for the documentation to be fixed.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 8.4.586670
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.48153.0 and VS Code Extension Version 11.0.698501. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
