### ISSUE TITLE
BC20 - Pages with Page extensions can only be searched with the Page extension object name

### ISSUE THREAD

**Issue by catadumitru** [microsoft/AL#6983]
In the preview release of BC20 

Pages with Page extensions that do not have the Caption parameter set can only be searched with the Page extension object name.

E.g.  PageExtension <ObjectID> "XXX Item List" extends "Item List"
Can now only be found using the search function as "XXX Item List" even if the caption for the "Item List" page is "Items"

**Comment by catadumitru** [comment]
Hi Thomas,

You are right, we have both feature flags added in the manifest. 

We would like to still use these features, as we always did, without causing issues with searching when PageExtensions are created without a caption. We noticed this issue only in the preview release of BC20.

Thanks

**Comment by dnpb** [comment]
Yes, surely only base objects should have their names used as captions - which seems fine as there's only one base - but it doesn't make sense to use extensions' captions automatically. which one should win? why should extensions only changing visibility or such, get to change the caption to include prefixes/suffixes/etc that users won't care about.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 38670 and VS Code Extension Version 10.0.607554. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by NKarolak** [comment]
@JesperSchulz According to your previos post, it looks like you will release it with BC 21. But this is a bugfix - can you backport it please to BC 20?

**Comment by JesperSchulz** [comment]
Sure thing :-) Fix is released with 9.0.615040.
