### ISSUE TITLE
Caching problem for code fragments in published extension?

### ISSUE THREAD

**Issue by hvogelpohl** [Microsoft/AL#700]
Hi community,

I'm developing on the september release (VM) and connected it to a cloud sandbox (https://*. financials. dynamics. com). Works fine, but now I have the feeling that some pieces of code ~~won't be deployed anymore~~ become not functional in my deployment after a while. 

For example, I have a page extension for the role center, with two actions. One of them I can still change with my AL code, the other one has somehow disappeared from the extension. No matter what I change about the action in AL, it doesn't show up in the extension anymore. I suddenly have this behavior in several places in the code.

I can still increment the extension, it deploys normally.

Is there a way to empty any cache or whatever? Anybody else having this problem?

Thank you :-)

**Comment by StanislawStempin** [comment]
There are a few issues here:
1) Cloud sandboxes are currently on the August Update. Features from September Update will not work there.  (Cloud Sandboxes will always be 1 or 2 updates behind the latest Developer Preview releases due to the nature of our release process)
2) When we're upgrading cloud sandboxes we uninstall all extensions-under-develoment. Is it possible that your extension was removed as part of the upgrade from July Update to August Update?
3) Make sure that all fields and actions have ApplicationArea = All applied to them.
4) If nothing else helps, you can reset your cloud sandbox using the following link: 
https://portal.financials.dynamics.com/reset?env=sandbox&redirectedFromSignup=false
This will give you a completely new tenant, deleting all changes from 

We are also aware of an existing caching issue (see #606) that might be at play here.

**Comment by hvogelpohl** [comment]
**The last point solved it, thank you.** I tried unsuccessfully to reproduce this behavior. But unlike ticket [#606](https://github.com/Microsoft/AL/issues/606), increasing the version number could not fix the "caching". 
But since I am almost finished with the development I will _reset to the end_ :-)

**Comment by StanislawStempin** [comment]
Have you managed to find a repro for it? Do you need to keep resetting the sandbox or was it a one time thing?

**Comment by hvogelpohl** [comment]
I‘ll definitly need it next week but for another reason. Can I still use the link?

**Comment by StanislawStempin** [comment]
Yes, the reset is always available through that link or through Sandbox Environments page on your regular, production tenant.
I just wanted to make sure that we no longer have the original issue that you described.
