### ISSUE TITLE
RDLC report paths in Mac OS vscode

### ISSUE THREAD

**Issue by LoanVision** [microsoft/AL#7000]
Please include the following with each issue:

**1. Describe the bug**
Due to different symbol (backslash/forward slash) used for paths in Mac/Linux vs Windows - system doesn't recognize the path to report layout properly

**2. To Reproduce**
a) Create new extension in Windows environment.
b) Create folder Layouts in root folder
c) Create new report in root folder
d) Add reference to rdl: RDLCLayout = 'Layouts\MySuperReport.rdl';
e) Compile extention so default layout is automatically generated
f) Open same project in MacOS vscode and compile

**3. Expected behavior**
Should recognize path depending on environment and not creating additional layouts in root folder

Thank you

**Comment by SBalslev** [comment]
Use forward slash for directory separator to get cross platform compatibility.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 40066 and VS Code Extension Version 10.0.620088. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
