### ISSUE TITLE
Extension compilation error: "Doesnt exist in the current context" (BC13 on prem)

### ISSUE THREAD

**Issue by txeriff** [microsoft/AL#7005]
Hi All, 

I think this could be a bug, very strange thing:
-BC13 on prem.
-pageextension 50089 UserList extends Users
-I've tried adding the Rec but it doesn't work

                    Clear(R50027);
                    R50027.SetSourceUserID(Rec."User Name", Rec."Full Name");
                    R50027.run;

compiler error, before compiling all is fine

Objects/Page%20Extensions/Pag-Ext50089.UserList.al(17,44): error AL0118: The name 'Rec' does not exist in the current context
Objects/Page%20Extensions/Pag-Ext50089.UserList.al(17,61): error AL0118: The name 'Rec' does not exist in the current context

thanks a lot.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by txeriff** [comment]
> Hi, this issue is out of scope of for this repository. You should do one of the following:
> 
>     * Open a support request to CSS through the PartnerSource portal
> 
>     * Open a bug in Collaborate
> 
>     * Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
> 
> 
> As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

What??? I'm telling you this is a compiler error, is not a code issue. The code is fine before compiling it.

**Comment by thloke** [comment]
It's out of scope because it's for BC13. This repo is only for the latest version of the AL compiler and runtime.

**Comment by txeriff** [comment]
> It's out of scope because it's for BC13. This repo is only for the latest version of the AL compiler and runtime.

I see. Can you try to reproduce it in latest BC?
