### ISSUE TITLE
False AA0001 "There must be exactly one space character on each side" for keyword at end-of-line followed by comment

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7006]
See below warning:

![image](https://user-images.githubusercontent.com/63455896/164213053-c4b24aed-b3e2-494f-aeb3-897a95fecda4.png)

This seems wrong. There **are** exactly 1 space on either side of the `and` keyword, so long as you ignore comments.

Please can the diagnostic ignore comments? end-of-line comments like this one are useful, and this is the logical/tidy place to put it.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.0.605172
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues.

**Comment by thloke** [comment]
Changing our mind on this, we're accepting it.

**Comment by dnpb** [comment]
That was a rollercoaster ;-) Thank you!

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 40039 and VS Code Extension Version 10.0.619721. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 40039 and VS Code Extension Version 10.0.619721. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
