### ISSUE TITLE
service web open page error

### ISSUE THREAD

**Issue by pierreLouise** [microsoft/AL#7008]
Please include the following with each issue:

**1. Describe the bug**
Error in french localisation on service web page

**2. To Reproduce**

1. create  sandbox  French 20.0.37253.38055
2.  use tell me to Open the service web page 
3. notice the error message StringLengthExceeded
4. change language to english
5.  use tell me to Open the service web page 
3. no error

error message
La longueur de la chaîne est 145, mais elle doit être inférieure ou égale à 128 caractères. Valeur : Si vous souhaitez configurer une connexion OData, pour des raisons de performances et de stabilité, envisagez d’utiliser une page API à la place.

Error StringLengthExceeded
"Webservice Notification Mgt."(CodeUnit 810).WebServiceAPINotificationDefault line 5 - Base Application by Microsoft
"Web Services"(Page 810).OnOpenPage(Trigger) line 8 - Base Application by Microsoft

``` AL
AL code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally.
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
open service web page

**4. Actual behavior**
![image](https://user-images.githubusercontent.com/35745909/164336624-99f41154-4ee1-48f5-ad24-6f1a15ac55de.png)

**5. Versions:** Version : FR Business Central 20.0 (plateforme 20.0.37114.39096 + application 20.0.37253.38055)

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed: none

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
