### ISSUE TITLE
Report's DataItem w/ PrintOnlyIfDetail Set to True Will Not Print Data When Not a Parent DataItem

### ISSUE THREAD

**Issue by jklassen** [microsoft/AL#7012]
DataItem's with the attribute PrintOnlyIfDetail will not print even if it is not a parent dataitem. Meaning it has no child dataitem's in the structure of the AL report.

The only reason I am bringing this up is because the [documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-printonlyifdetail-property) states "This property has no effect on a data item that does not have any child data items."

I have tested this on SaaS and a docker with version 19.1.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime.
