### ISSUE TITLE
OnAfterModifyEvent Not fired when using API

### ISSUE THREAD

**Issue by EtienneLeneveu** [microsoft/AL#7013]
Created an event subscriber 'OnAfterModifyEvent' on the "Warehouse Activity Line" table,

This one works fine when updating  "Warehouse Activity Line" from web client,

However when the "Warehouse Activity Line".Modify(true) is done from a buffer table related to an API page the event is not fired?? is this normal behaviour?

Additional info,

This was tested on Sandbox online current version.

Regards

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
