### ISSUE TITLE
Factbox layout not rendered correctly

### ISSUE THREAD

**Issue by tepke22** [microsoft/AL#7014]
**1. Describe the bug**

I created the **FactBox** that just shows some info about an Item and also taking **Location Filter** and **Variant Filter** for **SubPageLink**.

I added the created FactBox to following documents:

- **Purchase Order** (page 50)
- **Purchase Quote** (page 49)
- **Sales Order** (page 42)
- **Sales Quote** (page 41)
- **Service Lines** (page 5905)
- **Service Quote Lines** (page 5966)
- **Service Item Worksheet** (page 5906)
- **Purch. Order From Sales Order** (page 1328) <-- **remember this one**

## **On all documents it works as expected. Like this**

![image](https://user-images.githubusercontent.com/39384168/165524449-c1214918-6256-475e-9e96-4aacf6f5e6b9.png)

## But on page **Purch. Order From Sales Order (page 1328)** the layout is messed up

![image](https://user-images.githubusercontent.com/39384168/165524264-42f840c3-d6f2-4cc6-921e-2b8496107cc6.png)

**2. To Reproduce**

1. Create new FactBox named **"TSRD Item Details - Repl."** that shows info about Items replenishment system
2. Add newly created FactBox to pages listed above using appropriate SubPageLink
``` 
part(TSRDItemRepltDetails; "TSRD Item Details - Repl.")
{
    ApplicationArea = All;
    SubPageLink = "No." = field("No."), "Location Filter" = field("Location Code"), "Variant Filter" = field("Variant Code");
}
```

3. On **Purch. Order From Sales Order** (page 1328) FactBox isn't displayed correctly

**3. Expected behavior**

Information displayed inside FactBox should be properly aligned.

**4. Actual behavior**

Information displayed inside FactBox isn't properly aligned.

![image](https://user-images.githubusercontent.com/39384168/165526842-7da3e211-2c4b-46d3-b6e6-23dcaeceecec.png)

**5. Versions:**

- AL Language: **v9.0.615906**

- Visual Studio Code: 
**Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044**

- Business Central: **Version: DE Business Central 19.5 (Platform 19.0.36528.38789 + Application 19.5.36567.38821)**

- List of Visual Studio Code extensions that you have installed: 

1. AL CodeActions
2. AL Navigator
3. AL Toolbox
4. AL Variable Helper
5. AZ AL Dev Tools/AL Code Outline

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
