### ISSUE TITLE
Rule AA0240 recognizes a GUID as Phone No. or E-Mail

### ISSUE THREAD

**Issue by hemisphera** [microsoft/AL#7035]
**1. Describe the bug**
The code analysis rule AA0240 recognizes a GUID that is defined as label as a phone no. or e-mail and therefore is triggered. I often declare well-known GUIDs that are used in external interfaces as labels, to have them as similar as I can get to constants. This should not trigger AA0240.

**2. To Reproduce**

Declare a label like so:
``` AL
TheLabelOfLifeTok: Label '{8f4ce2e6-4bfa-4c10-a611-972201006156}', Locked = true;
```

**3. Expected behavior**
This declaration should not raise any warnings.

**4. Actual behavior**
CodeCop rule AA0240 is triggered.

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.67.0

**Comment by dnpb** [comment]
Seems already reported and fixed in https://github.com/microsoft/AL/issues/6337 - must have come back?

**Comment by DanielGoehler** [comment]
Have the same issue: `warning AA0240: The Label 'NotificationGuidTxt' must not contain email addresses or phone numbers.`
```
codeunit 50000 "Notification Mgt."
{
    var
        NotificationGuidTxt: Label '42cf998c-b9b6-4799-9752-ad62d4080c4a', Locked = true;
[..]
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42332 and VS Code Extension Version 10.0.640052. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
