### ISSUE TITLE
`Case` inside `"Quoted Identifier"` is syntax-highlighted as `case` keyword and start of block. Ditto `begin`, `end`, etc.?

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7041]
TSIA really:

![image](https://user-images.githubusercontent.com/63455896/168246012-bfaf4a48-1414-451a-b085-821b3728bfc8.png)

![image](https://user-images.githubusercontent.com/63455896/168246074-2973018f-216a-4cf2-b5cc-e03c0f18c65f.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.0.615906
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by NKarolak** [comment]
Try enabling semantic highlighting
https://youtu.be/cTc0kYFsAr0?t=312

**Comment by dnpb** [comment]
It was already enabled:
![image](https://user-images.githubusercontent.com/63455896/168290292-e40467c7-94f4-47b9-9c46-53a9db1148b0.png)

**Comment by NKarolak** [comment]
Not sure whether this may make a difference, but set it up for AL Language only (as shown in the video with time stamp).
And I am assuming that there is no other setting overriding your user setting?

**Comment by dnpb** [comment]
Thanks, adding it in an `"[AL]"` group means I actually get the highlighting, but it doesn't fix the issue with `case`.

Trying a couple more, it looks like some other keywords are affected by this too, e.g. `begin` and `end`. Probably there is just missing code to stop trying to highlight anything specially within identifiers.

![image](https://user-images.githubusercontent.com/63455896/168567960-ef935c82-ad94-4366-8113-6857baeb0dd0.png)

**Comment by meilel** [comment]
I can confirm this issue.
I am having the exact same problem with Quted identifiers like "begin", "end", "case" etc.

**Comment by thpeder** [comment]
It is there because with the latest version of VSCode the setting "editor.bracketPairColorization.enabled" is enabled by default.
As a mitigation you should disable it in settings.

**Comment by dnpb** [comment]
Sure, thanks - but is there a way that `al.configuration.json` can define what a `"quoted identifier"` is and then use `"notIn"` to avoid highlighting such words within identifiers?

**Comment by BazookaMusic** [comment]
Unfortunately, this is a bug in VSCode's bracket colorization feature and AL and we can't fix it on the AL side. VSCode has not considered the case that a bracket keyword may also be a word that is part of a language's syntax.

Begin and end are identified as brackets in al.configuration.json. From what I could figure out the colorization feature considers that only two kinds of code ranges should not have colorization on brackets, comments and strings. AL identifiers inside "" are neither of the two. At the same time, they are defined inside the grammar of the language which is why if you use a keyword inside a quoted identifier it will not appear highlighted.

![image](https://user-images.githubusercontent.com/36576941/203545497-5c962c4a-46b1-436e-a082-49d0c2b05d27.png)

**There is no option to define that brackets should not be recognized in other syntax, so we can't override the behavior.**

Here's a funny example where I've said that {"codeunit", "report"} is a bracket pair. VSCode is not smart enough to figure out that codeunit by itself is a keyword and not a bracket:
![image](https://user-images.githubusercontent.com/36576941/203579451-d2f89e2c-8b3f-43e9-918c-7eeb59678ef0.png)

Thus there are two options:
1) Remove begin/end from brackets and thus remove support for bracket colors for these keywords altogether. 
2) Accept this bug and file a bug on the editor so that they don't highlight syntax elements defined in the language grammar.

Since "begin" and "end" are much more rarely used inside quoted identifier as compared to brackets, I think we can go with #2 and depend on VSCode to make the feature a bit smarter.

**Comment by dnpb** [comment]
@BazookaMusic Thanks for the investigation and write-up! Are the AL team going to file the bug with VSC?

**Comment by BazookaMusic** [comment]
I have created the issue here:
https://github.com/microsoft/vscode/issues/167062

**Comment by dnpb** [comment]
Many thanks!
