### ISSUE TITLE
Evaluate a Datetime in XML Format defaults to UTC.

### ISSUE THREAD

**Issue by meilel** [microsoft/AL#7047]
**1. Describe the bug**
Evaluate a Datetime  in XML Format defaults to UTC, but should not use a timezone (local timezone) instead.
Timezones should only used if specified as described here: https://www.w3.org/TR/xmlschema-2/#dateTime

'2022-04-14T20:05:00' --> Should use no timezone (local timezone), but uses UTC instead
'2022-04-14T20:05:00Z' --> Should use UTC timezone and also does.

**2. To Reproduce**

1. Use the following snipped

``` AL
DateTimeText  := '2022-04-14T20:05:00';
Evaluate(DT, DateTimeText,9);
Message(Fromat(DT));
```

**3. Expected behavior**
Should Result in 14.04.22 20:05:00.

**4. Actual behavior**
This Result in 14.04.22 22:05:00 in my case (UTC+2 Timezone).

**5. Versions:**

- AL Language: v9.0.615906
- Visual Studio Code: 1.67.1
- Business Central: 18.2

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime. We don't handle issues with how AL is run on the server in this repo.
