### ISSUE TITLE
RoleCenter - Section - Groupname -> Visibility fail -> depending from ApplicationArea

### ISSUE THREAD

**Issue by Koepisch** [microsoft/AL#7054]
BC Version 20.0.37253.39047de

I want to hide the module gui element (_group("Modules-AAA")_) using the proper "ApplicationArea" values. In the RoleCenter-Section area is a bug which doesn't hide the parent group name, if there is a child element of type group. So the section name '_AAA_' is still visible, showing no (child) elements. ALL actions (also in the nested group) have the same ApplicationArea value.

If you remove the child group, the section name disappears.

    actions
    {
        area(sections)
        {
            group("Modules")
            {
                Caption = 'Modules';
                Image = Setup;

                group("Modules-AAA")
                {
                    Caption = 'AAA';

                    action(AAA1)
                    {
                        ApplicationArea = AAA;
                        Caption = 'AAA1';
                        RunObject = ...;
                    }
                    action(AAA2)
                    {
                        ApplicationArea = AAA;
                        Caption = 'AAA2';
                        RunObject = ...;
                    }
                    group("Modules-AAA-SETUP")
                    {
                        Caption = 'Setup';

                        action(AAA3)
                        {
                            ApplicationArea = AAA;
                            Caption = 'AAA3';
                            RunObject = ...;
                        }
                        action(AAA4)
                        
                            ApplicationArea = AAA;
                            Caption = 'AAA4';
                            RunObject = ...;
                        }
                    }
                }
            }
        }
    }

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
