### ISSUE TITLE
Upgrade v14 to v15 Cannot find Page 1752

### ISSUE THREAD

**Issue by jiwanovski87** [microsoft/AL#7056]
**1. Describe the bug**
Currently we are trying to upgrade a tenant from version 14 to version 15.
Within there we are getting trouble when executing the cmdlet `Sync-NAVApp` with the custom `Base Application`.
I already have read the issue #5840 where the same error message appears. 

We only have the following extensions published:
**Symbols**
```
Id                  : 8874ed3a-0643-4247-9ced-7a7002f7135d
Name                : System
Version             : 15.0.38951.0
Publisher           : Microsoft
ExtensionType       : ModernDev
Scope               : Global
Brief               : 
Description         : 
Compatibility Id    : 0.0.0.0
Developer Tenant ID : 
Privacy Statement   : 
EULA                : 
Help                : 
Url                 : 
Logo                : 
Screen Shots        : 
Prerequisites       : 
Dependencies        : 
Package Id          : a41dce46-1814-4a35-9aa6-1e96e2a16321
```
**No Symbols**
```
Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
Name          : System Application
Version       : 15.2.39040.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global

Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
Name          : Base Application
Version       : 15.2.39040.1
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global
```

And we are getting the issue `The metadata object Page 1752 was not found`.

Has anybody an idea where the issue is?

**3. Expected behavior**
The cmdlet `Sync-NAVApp` should sync the `Base Application` (customized) with the `tenant`.

**4. Actual behavior**
Retrieving issue:
`The metadata object Page 1752 was not found`.

**5. Versions:**

- Business Central: 15.0.38951

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
