### ISSUE TITLE
AS0098 for report extensions

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#7057]
**1. Describe the bug**
AS0098 requires affixes in report extensions. If the affix contains space, the extension needs to define both affixes with space & with _ instead of space.

**2. To Reproduce**
Use affix with space and create a report extension & a new column for the field with this affix. The name of the column must have an affix but the space must be replaced by _ (or any other character different from space)

For example, our registered affix is "ART " (with space) but for report extensions, we have to add to AppSourceCop also "ART_". Furthermore, we won't probably be able to create any report extension for AppSource as it uses different affixes from our registered one.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42844 and VS Code Extension Version 10.0.644649. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by TKapitan** [comment]
Thanks Jesper. Could you please described how it’s fixed? Spaces in affixes are replaced with some character?

**Comment by JesperSchulz** [comment]
@thloke, can you provide further insights?

**Comment by thloke** [comment]
Yes. Spaces in affix/prefixes will be treated as wildcards and can be replaced with any character.
