### ISSUE TITLE
Error converting value "XXX=sometext;ENU=someengtext" to type 'Microsoft.Dynamics.Nav.Types.Metadata.MultiLanguage'. Path 'ProfileMetadata[0].CaptionML', line 7, position 86

### ISSUE THREAD

**Issue by kine** [microsoft/AL#7063]
**1. Describe the bug**
When installing app into BC v20, we are getting the error:

```
Error converting value "XXX=sometext;ENU=someengtext" to type 'Microsoft.Dynamics.Nav.Types.Metadata.MultiLanguage'. Path 'ProfileMetadata[0].CaptionML', line 7, position 86
```

Where XXX is e.g. CSY, and the texts are names of Profile, which is part of the extension. It means, it is a problem when the system tries to somehow process the Profile CaptionML.

We are noticing this when installing extensions including profile and the text is equal to the profile name:

```AL
profile "our profile name"
{
    Description = 'some description';
    Caption = 'someengtext'; #this is the text from the error, translated to language XXX through xliff file
    RoleCenter = "Rolecenter page name";
}
```

**2. To Reproduce**
1. Publish app with profile, which was compiled for BC v19
2. Install the app within the Extension Management page
Result is error like
```
Error converting value "XXX=sometext;ENU=someengtext" to type 'Microsoft.Dynamics.Nav.Types.Metadata.MultiLanguage'. Path 'ProfileMetadata[0].CaptionML', line 7, position 86
```
Details for the error:
```
Error converting value "CSY=xxx;ENU=yyyy" to type 'Microsoft.Dynamics.Nav.Types.Metadata.MultiLanguage'. Path 'ProfileMetadata[0].CaptionML', line 7, position 86.

Internal session id: 
d1e584b2-30f3-4c59-b2b8-cc2a8b82b023

Application Insights session id: 
06e25d2a-90e9-4772-8235-ed8f97546d40

Client activity id: 
1ca54003-ebbc-462c-44bc-b2f7f676b859

Timestamp: 
2022-05-31T09:39:24.5887140Z

AL call stack: 
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionSilently line 4 - System Application by Microsoft
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionWithConfirmDialog line 28 - System Application by Microsoft
"Extension Details"(Page 2501)."Install - OnAction"(Trigger) line 2 - System Application by Microsoft

```
**3. Expected behavior**
Installed app without error, because the extension is valid and compatible.

**4. Actual behavior**
We are getting error as mentioned.

**5. Versions:**

- AL Language: N/A
- Visual Studio Code: N/A
- Business Central: 20.0.39668.39849 (platform), 20.1.39764.39901 (application)
- List of Visual Studio Code extensions that you have installed: N/A

**Comment by thloke** [comment]
This has also been raised internally on us through another channel, we will be looking into this.

**Comment by pprodoehl** [comment]
Hi there,

we ran into the same obstacle. 

![image](https://user-images.githubusercontent.com/106808339/171828472-474610da-29bc-4982-b373-86dc2bce7cc7.png)

AT Business Central 20.1 (Plattform 20.0.39668.39849 + Anwendung 20.1.39764.39901)

We would be happy about a solution.

Best,
Paul

**Comment by thloke** [comment]
Hi, we've finally looked into this. This will only happen on OnPrem servers, and the fix here is to unpublish and republish the app. We're still evaluating if we will issue a fix for this, and we will update this issue if we do.

**Comment by thloke** [comment]
We've decided to not backport a fix for this. If you run into this issue, you can fix it by:

- Unpublishing and republishing the affected apps or
- Running Repair-NavApp on the affected apps.

**Comment by stanleyg33** [comment]
does any resolve this issue?
i have this error as well from System Application.
i cant install Essential Business Headlines, both are from installer

If requesting support, please provide the following details to help troubleshooting:

Could not install the extension 'Essential Business Headlines' by 'Microsoft' (version '22.2.56969.57617') for tenant 'default' due to the following error: An unexpected error occurred after a database command was cancelled.

Internal session ID: 
d7ba4132-8689-479c-ba5e-35ad033f3eca

Application Insights session ID: 
4e344021-098d-4b19-b707-2dc07b791982

Client activity id: 
4d5b172e-e046-d5ae-0d75-ea00d629f934

Time stamp on error: 
2023-08-08T05:34:16.4792790Z

AL call stack: 
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionSilently line 4 - System Application by Microsoft
"Extension Installation Impl"(CodeUnit 2500).InstallExtensionWithConfirmDialog line 28 - System Application by Microsoft
"Extension Details"(Page 2501)."Install - OnAction"(Trigger) line 2 - System Application by Microsoft
