### ISSUE TITLE
Due Date Modified field is not updated in Sales Header

### ISSUE THREAD

**Issue by ptorres11** [microsoft/AL#7065]
With ES Localization, we are posting a Sales Order where the customer has the day 1 as a Payment Day. The Payment Method used creates bills, and we have a payment term with 10 payments every 30 days. When we check the preview of the posting, the customer entries have a Due Date of the first day of every month. This is OK. If we change the Due Date in the order, and check the customer entries preview of the post, the due date is every 30 days, and not the day 1 of each month.

We can understand this, but we expect that if we set the original Due Date to the order, the Due Date Modified field is set to false, so the created entries after post have the Due Date every first day of the month again.

- AL Language: v9.0.615906
- Visual Studio Code: 1.67.2
- Business Central: 20.1.39764.39901

**Comment by dnpb** [comment]
You probably have to report this via partner support, as it's not on-topic here as it's not about the AL language or compiler itself, but rather a localisation of the Base App.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
