### ISSUE TITLE
2 Sales price worksheet (one is not working)

### ISSUE THREAD

**Issue by wandriesbiqs** [microsoft/AL#7069]
**1. Describe the bug**
2 times of "Verkoopprijsvoorstel" (sales price worksheet) in the search.
1 is not working because I activated the new sales price calculation
![image](https://user-images.githubusercontent.com/88889405/172864033-8bb88eaf-cf7b-471e-8dae-8d6089ea4514.png)
![image](https://user-images.githubusercontent.com/88889405/172864240-0b83bec1-a156-4e0c-97d0-67d587789f9a.png)

I also added the CLEAN19 in the preprocessorSymbols in the app.json.
![image](https://user-images.githubusercontent.com/88889405/172864847-ed9339ac-ca52-4bce-a371-7c309c6662ae.png)
![image](https://user-images.githubusercontent.com/88889405/172864892-6bd2bb25-86fa-47bb-aefb-1161882ff47b.png)

**2. To Reproduce**
1) Activate the new sale price calculation
2) Search for "Verkoopprijsvoorstel"

**3. Expected behavior**
Only one "Verkoopprijsvoorstel" in the search.

**4. Actual behavior**
A clear and concise description of what happened accompanied by images, animations, or a link to a video showing the issue occurring

**5. Versions:**
![image](https://user-images.githubusercontent.com/88889405/172864660-556619ec-6f93-4bc4-8a86-d4600282dc7d.png)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
