### ISSUE TITLE
Incorrect GetUrl return value

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7071]
**1. Describe the bug**
I have a sandbox environment on a local machine in Docker container. It is a multitenant type, created by BcContainerHelper.
Container name (=target server) is 'test', one and only tenant is 'default'.
When I use `GetUrl` AL command, server name and tenant are joined together twice and I get this:
http://test-default/BC/?tenant=test-default

A test on another Docker container (but on a remote machine with public ports) with a sandbox and single tenant type is OK.

Is it a matter of some server configuration or it is a bug?

**2. To Reproduce**
``` AL
Message(GetUrl(ClientType::Web));
```

**3. Expected behavior**
The correct address shoul be:
http://test/BC/?tenant=default

**4. Actual behavior**
http://test-default/BC/?tenant=test-default

**5. Versions:**

- AL Language: 10.0.635892
- Business Central: 21.0.41987.0
- (but same on version 9.0/20.1)

**Comment by dnpb** [comment]
Yes, I think I have seen this with Web Service pages getting that kind of URL, and not loading as a result, e.g. `http://somelocaldocker-default/BC/blah`

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue specifically needs to go to a team that handles the server runtime.
