### ISSUE TITLE
Using RDLCLayout or WordLayout property prevents outline view from displaying symbols

### ISSUE THREAD

**Issue by jorland1** [microsoft/AL#7073]
**1. Describe the bug**
Using the property `RDLCLayout` or `WordLayout` in any report object prevents the outline view in VS Code from displaying any symbols.

**2. To Reproduce**
- Add the property `RDLCLayout` or `WordLayout` to any report object.

Minimal example:
``` AL
report 50101 MyReport
{
    WordLayout = 'MyReport.docx';
}
```

**3. Expected behavior**
Show the symbols in the outline view, just as for this report without a layout:
![image](https://user-images.githubusercontent.com/74199967/173032084-9beac2be-c570-4294-a45b-a15638e68943.png)

Even the minimal example should display something:
![image](https://user-images.githubusercontent.com/74199967/173056728-c4671969-b413-436b-be63-0aa73dc404f0.png)

**4. Actual behavior**
No symbols are shown in the outline view:
![image](https://user-images.githubusercontent.com/74199967/173032212-3a788ff6-8fe3-41f4-acf7-999f4310bb82.png)

**5. Versions:**

- AL Language: v9.2.627606
- Visual Studio Code: 1.67.2
- List of Visual Studio Code extensions that you have installed: AL Language

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21.0.45154.0 and VS Code Extension Version 10.0.667255. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
