### ISSUE TITLE
AL allows/suggests `"Enum Name"::"First Value Name"::"Another Value Name"::"Etc"::"Etc"`

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7077]
Title says it all. Only `"Enum Name"::"First Value Name"` should be valid; the rest make no sense.

I think the last one ends up getting used, but this simply should not build, nor be suggested/autocompleted!

![image](https://user-images.githubusercontent.com/63455896/173333934-d0a5c8d9-2bd9-489d-829b-fa27851b9d03.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.0.615906
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by dnpb** [comment]
Thanks as always!

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.47719.0 and VS Code Extension Version 11.0.693297. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
