### ISSUE TITLE
Unable to create new Area dimension value in a Evaluate Company

### ISSUE THREAD

**Issue by ViggoVll** [microsoft/AL#7078]
Please include the following with each issue:

**1. Describe the bug**
I get the error "There are no allowed dimension values selected." When i try to create a new dimension value with the name AM in a new Evaluate Company.

There are no allowed dimension values selected.

AL call stack: 
DimensionManagement(CodeUnit 408).CheckIfNoAllowedValuesSelected line 4 - Base Application by Microsoft
"Default Dimension"(Table 352).GetFullAllowedValuesFilter line 11 - Base Application by Microsoft
"Default Dimension"(Table 352).GetAllowedValuesFilter line 4 - Base Application by Microsoft
"Default Dimension"(Table 352).UpdateDefaultDimensionAllowedValuesFilter line 5 - Base Application by Microsoft
DimensionManagement(CodeUnit 408).AddDefaultDimensionAllowedDimensionValue line 10 - Base Application by Microsoft
"Dimension Value"(Table 349).OnInsert(Trigger) line 8 - Base Application by Microsoft´

**2. To Reproduce**
I create a new company with the "Evaluation - Sample Data" setting.
![image](https://user-images.githubusercontent.com/82797917/173346980-b47bb2bc-aabd-44d9-b47a-ed2d76ac3f57.png)

I then go into the Dimensions page and navigate to Area Code and go to Dimension Values.
I then try and create a new Dimension Value called AM

**3. Expected behavior**
Being able to create a new Dimension value.

**4. Actual behavior**
I get the error "There are no allowed dimension values selected." When i try to create a new dimension value with the name AM.

**5. Versions:**

- AL Language:
   -9.0.615906
- Business Central:
   - 20 CU1

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
