### ISSUE TITLE
FieldCaption breaks if enum field is passed in 9.2.639332

### ISSUE THREAD

**Issue by deadmouse** [microsoft/AL#7088]
Please include the following with each issue:

**1. Describe the bug**
When using Record.FieldCaption(Field::"Enum Value") this throws error when packaging in the version 9.2.639332.

**2. To Reproduce**
Write a line like this:  Error('Error %1', VATPostingSetup.FieldCaption("VAT Calculation Type"::"Normal VAT"));

**3. Expected behavior**
I expect this to not throw error. **This has been working for me for at least 2 years**.

**4. Actual behavior**
Unable to package. The error thrown is: The name '"VAT Calculation Type"' does not exist in the current context AL(AL0118)

**5. Versions:**

- AL Language: 9.2.639332
- Visual Studio Code: 1.68.1
- Business Central: 20.1
- List of Visual Studio Code extensions that you have installed: AZ AL Dev Tools/AL Code Outline; Create GUID; Explorer Exclude; Git Graph; GitLens - Git supercharged; Mayukai Theme; PowerShell; Switch Git Worktree; TabOut; Todo Tree; vscode-icons; waldo's CRS AL Language Extension

### Final Checklist

Please remember to do the following:

* [X] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [X] Simplify your code around the issue to better isolate the problem

**Comment by dnpb** [comment]
What are you trying to show? The formatted caption of the enum value? then you should just do

    Error('Error %1', Enum::"The Enum Name"::"The Enum Value Name");

**Comment by deadmouse** [comment]
Yep, I am trying to show the formatted caption of the enum value. Thanks for the alternative, but is this going to be considered as a bug or a breaking change? I need to know it in order to refactor or not. I had that code for 2 years without any problem.

**Comment by NKarolak** [comment]
You need to refactor your code, it was wrong from the beginning. The compiler has been improved to work as actually intended. 
See also all posts above this one: https://twitter.com/MVPKine/status/1539521401228517378

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42990 and VS Code Extension Version 10.0.645962. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
