### ISSUE TITLE
Wrong indenting after upgrade to AL Language 9.3.642746

### ISSUE THREAD

**Issue by matuspieger** [microsoft/AL#7091]
Hello, our team is experiencing issues with indenting of the AL code since upgrading to the latest version of the AL Language Extension (version 9.3.642746).

This happens mostly when creating a repeat until structure. The code does not get indented as it should, instead the lines (usually just the first line) jump more to the right like you see on the example below with the line I have marked yellow.

![image](https://user-images.githubusercontent.com/90702018/175538434-5084c992-f215-4d55-b2dc-f9f8c1d2b81b.png)

When downgrading to the previous version, this issue does not occur anymore.

**Comment by markborges** [comment]
> An issue similar to this one was reported here: #6582
> 
> There are a few others... It seems to be a recurring problem.

It seems the original issue was accepted 4 days ago (after having been posted in April of 2021!).... And then they probably did some fix that broke it even more...?

That's my guess, but I'll def use the tip in that thread to disable auto install of extensions. I didn't even know this was enabled on my VS Code. Thanks for the reference, @bernalfr

**Comment by Drakonian** [comment]
Same problem

**Comment by epernst** [comment]
Same problem, very annoying. I practically prevents us from committing any code!

**Comment by thloke** [comment]
We are aware of this and will revert the change that caused this.

**Comment by dannoe** [comment]
This seems to be fixed in version 9.3.646020 (released 2 hrs ago).

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 42990 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
