### ISSUE TITLE
UI Issue on Navigation part of Role Center, acquiring space and hiding pages SAAS

### ISSUE THREAD

**Issue by AvnishP613** [microsoft/AL#7101]
On Navigation we have added a group of Specific Customer navigation menu like Sales which is Fuel and we have added PAGES under this before it was showing all pages correctly but from Release 20 , Navigation has started to hide the additional pages as per page size.
![image](https://user-images.githubusercontent.com/72007996/176648345-677e1b31-711a-4bfc-9ba5-e62b345bfeb2.png)
So Here before Rebate there are other Pages also as Discount Staging
![image](https://user-images.githubusercontent.com/72007996/176647485-9339c141-9c2a-4219-9c14-3cd928a52edd.png)

 System is not giving proper space and is being hidden behind Site Information area

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
