### ISSUE TITLE
[Bug] Use of Protected Var 

### ISSUE THREAD

**Issue by panas78** [microsoft/AL#7102]
Hello, 
we came across a weird bug that leads to client crashing in cases where our code inside an extension table is using a protected var from the original table.

Here is the code to reproduce the problem :
```
tableextension 50000 "Reversal Entry" extends "Reversal Entry"
{
    procedure MyProcedure()
    begin
        GLSetup.get;  //This is a protected var defined in "Reversal Entry"
        Message('Got GLSetup');
    end;
}

page 50000 MyPage
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;

    actions
    {
        area(Processing)
        {
            action(ActionName)
            {
                ApplicationArea = All;
                Caption = 'TestReversalError';

                trigger OnAction()
                var
                    ReversalEntry: Record "Reversal Entry";
                begin

                    ReversalEntry.MyProcedure();

                end;
            }
        }
    }
    
}
```
if you open page 50000 "MyPage" and try to run the TestReversalError action client is crashing with
![Screenshot 2022-06-30 134851](https://user-images.githubusercontent.com/64047553/176659428-45b3fdd5-5c99-4153-a8e5-8ed043518e5c.png)

the same happens whenever we try to use any of the Protected Var declared in "Reversal Entry"
Version is 20.0.37253.38230 w1 onprem

**Comment by SBalslev** [comment]
This is a platform change so it will be in a future update.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 43661 and VS Code Extension Version 10.0.652307. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
