### ISSUE TITLE
AL VSX is not respecting the new vscode telemetry settings 

### ISSUE THREAD

**Issue by dannoe** [microsoft/AL#7104]
**1. Describe the bug**
``"telemetry.enableTelemetry": false`` is the deprecated setting in vscode for disabling the telemetry. The new way is using ``"telemetry.telemetryLevel": "off",``. But the new setting is ignored by the AL editor service process.

**2. To Reproduce**

1. Set ``"telemetry.telemetryLevel": "off",`` in your config
2. Restart vscode
3. Look at the start arguments of the ``Microsoft.Dynamics.Nav.EditorServices.Host.exe`` process
4. Set ``"telemetry.enableTelemetry": false`` in your config
5. Restart vscode
6. Look at the start arguments of the ``Microsoft.Dynamics.Nav.EditorServices.Host.exe`` process

**3. Expected behavior**
Respect the new telemetry setting and also allow the old one, as it is still accepted from vscode itself.

**4. Actual behavior**
Only the old one is accepted.

**5. Versions:**
Name: AL Language
Id: ms-dynamics-smb.al
Version: 9.3.646020

VS Code Version: 1.68.1

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 21.0.44392.0 and VS Code Extension Version 10.0.10.4356. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
