### ISSUE TITLE
Table "CSV Buffer" function "InsertEntry" could remove commas before Insert

### ISSUE THREAD

**Issue by SilviuVirlan** [microsoft/AL#7115]
Rec.Value := DelChr(Rec.Value,'=',',');

**Comment by dnpb** [comment]
As the button you clicked to create this issue said - this is off-topic, as this repo is about the AL language/compiler, and you are asking for a change to base app functionality.

![image](https://user-images.githubusercontent.com/63455896/179236975-1a02a593-51a0-413f-b964-c3f4a1ebf44c.png)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
