### ISSUE TITLE
Page Extension procedure not appearing on with the TestPage type

### ISSUE THREAD

**Issue by nicdiblasiFS** [microsoft/AL#7118]
Hi, 

I've noticed in my test suite app extension I've created, that I can't reference Page extension procedures from a TestPage type. Why is this returning an error from the compiler? 

![image](https://user-images.githubusercontent.com/87403142/179660360-4b00b77f-b656-4d04-8433-8d1f0104606a.png)

![image](https://user-images.githubusercontent.com/87403142/179660373-aae3366a-0feb-4064-beed-50781dc3dd45.png)

Error: 
'procedure ()
TestPage FSG_PAY_NewAccountWizard' does not contain a definition for 'SrcRecordCount'

Regards Nic

**Comment by thloke** [comment]
Great idea! Go ahead and post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

**Comment by NKarolak** [comment]
@thloke Why did you classify that as an enhancement, and not as a bug?

**Comment by thloke** [comment]
Yes, I can clarify. There are two main reasons:

1. This was never supported as far as we know, so it's a feature gap in test pages.
2. Because of 1, there's the possibility that the work required to support this is significant because there might be additional work on the BC server itself that needs to be done. Just adding the ability to refer to members added by extensions in the compiler won't be sufficient if the runtime doesn't support it.

**Comment by NKarolak** [comment]
OK, thanks.
