### ISSUE TITLE
You do not have the following permissions on Table Radio Show: Execute

### ISSUE THREAD

**Issue by DragonPaladin** [microsoft/AL#7121]
I am following the ebook Programming Microsoft Dynamics 365 Business Central examples and hitting a wall on permissions. When I hit ctrl-F5 it gives me this error message: 
![image](https://user-images.githubusercontent.com/109811802/180468451-3a0080a6-8634-456a-92c1-8e9960e23f23.png)
I have super user rights so I am not sure why I am getting this message in my sandbox on premise?
Here is snippet of the code(1st make table, then page) do note **that my ID's are different from the book because I am using a copy of our BC which already had those ID's in use.** --app.json file:
![image](https://user-images.githubusercontent.com/109811802/180469138-e8f3091e-d1f4-4472-a8b7-27c9e3b1dcda.png)
--launch.json file:
![image](https://user-images.githubusercontent.com/109811802/180469275-75250488-b5f6-49a1-bcda-03c49d5696a1.png)
table:
![image](https://user-images.githubusercontent.com/109811802/180469360-a2f994b4-54ac-46c2-8123-79de1c59ec82.png)
page:
![image](https://user-images.githubusercontent.com/109811802/180469512-2d4f2847-8c16-4139-944d-ea0707d4a805.png)

Sorry if this post is in the wrong area; let me know if so. Thanks in advance!

**Comment by dnpb** [comment]
> I have super user rights so I am not sure why I am getting this message in my sandbox on premise?

If your user permissions allow it, then the error means your licence permissions do not. Check that.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. How licenses and permissions work together doesn't come under the scope of this repo.

However, what dnpb says is correct. Effective permissions are a combination of user permissions and license. You should check the Effective Permissions page to see what is actually being applied to your user.
