### ISSUE TITLE
Copy Company unexpected behaviour with Datatyp Media

### ISSUE THREAD

**Issue by Hofschn8** [microsoft/AL#7128]
Hello, 

we have an extension and adding a media field to  company information. 
The uploaded image is printed on various reports. 
When the company will be copied, the Guid from the media field is copied as well and everything seems to be fine so far, BUT the image is not printed on the reports!!
Looking deeper into it, it seems that the record in the tenant media table is not copied/duplicated - there is  only 1 record in it, and it is linked to the original company. 
On the "contact" table with the image (which is also a media datatyp) here we saw a different behaviour. The record here gets copied/duplicated and gets a new guid assigned. 

So looks like the "copy company "function is treating extension fields from typ media not correctly. 

Best regards
David

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
