### ISSUE TITLE
Missing permissions when running tests in NextMajor as Super User

### ISSUE THREAD

**Issue by LeifurPals** [microsoft/AL#7129]
- AL Extension Version: 21.0.4255.0

- Server Version: Version: IS Business Central 21.0 (Platform 21.0.42152.0 + Application 21.0.42550.0)

I am running tests through the AL Test Tool page as a super user with Insert Permission on User Table Data but I get the following error saying I am missing permissions. Are we no longer allowed to create certain data in tests?

Error: 
`Error Message: You do not have the following permissions on TableData User: Insert.

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '124'. - Error Call Stack:

dummyTestCodeunit(CodeUnit 10039657).dummyTestCodeunit line 8 - DummyExtension by Rue de Net
"Test Runner - Mgt"(CodeUnit 130454).RunTests line 19 - Test Runner by Microsoft
"Test Runner - Isol. Codeunit"(CodeUnit 130450).OnRun(Trigger) line 4 - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunTests line 2 - Test Runner by Microsoft
"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests line 35 - Test Runner by Microsoft
"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction"(Trigger) line 7 - Test Runner by Microsoft`

`codeunit 10039657 dummyTestCodeunit
{
    Subtype = Test;

    [Test]
    procedure dummyTestName()
    var
        NewUser: Record User;
    begin
        NewUser.Init();
        NewUser."User Security ID" := CreateGuid();
        NewUser."User Name" := 'TESTAPPROVER';
        NewUser."Full Name" := NewUser."User Name";
        NewUser.Insert();
    end;
}`

**Comment by LeifurPals** [comment]
Are we no longar allowed to create certain data in tests? 
I am getting this error for multiple different tables even though I am running the tests as a super user

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by LeifurPals** [comment]
I am a developer working on updating our products for the upcoming business central 2022 release wave 2. Multiple of our products unit tests are failing on the pre release. I'm just trying to figure out if this is a bug in the pre release or if there are some new permission rules regarding tests.
