### ISSUE TITLE
Order arrangement for fields in ribbon(promoted area).

### ISSUE THREAD

**Issue by DragonPaladin** [microsoft/AL#7130]
I am trying to figure out a way to rearrange the order of two buttons in the ribbon(promoted area). 
(I am not sure what to call it but it seems similar to a ribbon)

Here is the two fields in a screenshot below that I am trying to re-order.
(Using design doesn't allow me to order them correctly at least on my attempts at it)

![image](https://user-images.githubusercontent.com/109811802/183511679-f0ca38d1-d370-4566-88e7-7d39735acee2.png)

Here is part of the raw code from a page extension: 
( I tried to mess around Addfirst( ) with no luck; I am not sure what the PromotedActionCategories area is called to use it.)

actions
    {
        modify(ExportClinVer)
        {
            Promoted = true;
            PromotedCategory = New;
            PromotedOnly = true;
        }
        modify(SewpAddRequest)
        {
            Promoted = true;
            PromotedCategory = New;
            PromotedOnly = true;
        }

Thanks in advance!

**Comment by dnpb** [comment]
Look into `movebefore`, `moveafter`, et al.: [link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object). Anyway I think this is off-topic unless you've found some part of the language or compiler that doesn't work as specified.

**Comment by NKarolak** [comment]
`PromotedIsBig` might be your friend: https://twitter.com/KarolakNatalie/status/1413381389605539842?s=20&t=5diTpZFa7mG7mcPY0vYCag

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
