### ISSUE TITLE
AL0433 does not allow to remove table used in exposed method

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/AL#7135]
Hi,

Analyzer rule AL0433 (from AppSource analyzer) does not allow to mark table with `ObsoleteState = Removed` when it is used in method or event publisher (see analyzer error below).

Obsolete attribute on methods behave similarly to `ObsoleteState = Pending` on objects and does not help (for event publishers you would like to obsolete only "removed" table parameter). Instead, table usage in method should be allowed in parameter list and return value (should show warning for local/internal methods and internal event publishers, but not integration and business event publishers), and the error should be forwarded to the method usages/event subscribers.
For method usages you won't be able to call it anyway and for event subscribers you can remove "removed" table from event subscriber parameters.

Thanks.

Example code:

```al
table 75999999 "MY Table"
{
    ObsoleteState = Removed;
    ObsoleteReason = 'Removed.';

    fields
    {
        field(1; "Primary Key"; Code[10])
        {
            DataClassification = CustomerContent;
        }
    }
}

codeunit 75999999 "MY Functions"
{
    [Obsolete('Removed.')]
    [IntegrationEvent(false, false)]
    local procedure OnEvent(MYTable: Record "MY Table")
    begin
    end;
}

permissionset 75999999 "MY Permissions"
{
    Caption = 'Permissions', Locked = true;
    Assignable = true;
    Access = Internal;
    Permissions =
        tabledata "MY Table" = RIMD,
        table "MY Table" = X,
        codeunit "MY Functions" = X;
}
```

I get the following error:
![image](https://user-images.githubusercontent.com/53167314/183898377-e8e4d1ed-f4d5-43f6-b13b-d9434f53446b.png)

**Versions:**

- AL Language: 9.4.663067
- Visual Studio Code: 1.70.0-insider
- Business Central: 20.3.42673.43026 (OnPrem)
- List of Visual Studio Code extensions that you have installed:
  - AL Language

**Comment by qutreson** [comment]
@ernestasjuska - This behavior is by-design. When a table is marked as Obsolete Removed, it cannot be referenced anywhere except in upgrade codeunits. 

The recommended approach is to do as follows:
1. Mark the table as Obsolete Pending and obsolete all the events/methods referencing it as parameter or as return type.
2. After some time, once dependent extensions had the chance to be updated, mark the table as Obsolete Removed and remove the events/methods referencing it.

Tables have an obsolete removed state, because removing them is a SQL schema breaking change. Events/methods don't have an obsolete removed state, but only have an obsolete pending state since they can be removed from code.
