### ISSUE TITLE
[Bug] TableRelation with or filter "|" creates a wrong LookUp filter

### ISSUE THREAD

**Issue by tinestaric** [microsoft/AL#7136]
Hey,

when a field has a table relation that has an or ("|") filter, it creates a wrong LookUp when the related record fits in the filter that is not in the first place

The below example is taken from BaseApp - BOM Component table:

Field No. has TableRelation with | in the filter
![image](https://user-images.githubusercontent.com/42935028/183906943-0added99-8b91-461d-a178-9767f91a2684.png)

Having an Item that is of type Non-Inventory.
![image](https://user-images.githubusercontent.com/42935028/183907517-1d315fb9-7255-403c-8608-1a3ea0290e5d.png)

Selecting the Item and making the page non-editable so clicking on the No. field brings up the Item Tile:
![image](https://user-images.githubusercontent.com/42935028/183907746-2eaf15b1-4b56-4c8f-a47c-c318c3afec25.png)

The presented LookUp page is for the wrong Item and also Page Inspection shows that the first filter specified in the TableRelation was set:
![image](https://user-images.githubusercontent.com/42935028/183908582-269735f3-fd53-491c-9cb0-0199188c49ab.png)

The whole scenario works fine if the related record would be part of the first filter option.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
