### ISSUE TITLE
AL0432 fails to warn for use of Obsoleted enum values in properties e.g. InitValue, TableRelation, FlowField CalcFormula

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7139]
This code:
```al
enum 50100 Test
{
    value(0; Test)
    {
        ObsoleteState = Pending;
        ObsoleteReason = 'going to go away';
    }
}

table 50100 Test
{
    fields
    {
        field(50100; "Test Real"; Enum Test)
        {
            InitValue = Test; // why no warning?
        }

        field(50101; "Test Flow 1"; Integer)
        {
            TableRelation = Test where("Test Real" = const(Test)); // why no warning?
        }

        field(50102; "Test Flow 2"; Integer)
        {
            FieldClass = FlowField;
            CalcFormula = count(Test where("Test Real" = const(Test))); // why no warning?
        }
    }

    trigger OnInsert()
    begin
        Validate("Test Real", Enum::Test::Test);
    end;
}
```

does not warn for any use of `Obsolete`d enum values within properties:

![image](https://user-images.githubusercontent.com/63455896/185090401-83355834-e884-48ed-8772-4a62fcf7c66d.png)

Please correct so that we will be warned if using obsoleted values in properties for these - and in any other properties I didn't think to check, i.e. please review them all and find a solution that covers all properties.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.4.663067
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.47540.0 and VS Code Extension Version 11.0.691753. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
