### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/AL#7142]
Hello,
We are having memory issues with the client browser and Business Central 2022 Wave 1. For example, when scrolling the list of articles, the memory on the client station up, up to 4Go!!! then crashes the browser displaying ouch, ouch. 

What should I do to purge the memory ?

Cordially.

![image](https://user-images.githubusercontent.com/29279866/186638757-5c14f978-065b-4c06-bb08-33e9ce4a35c9.png)

**Comment by Drakonian** [comment]
Hi,
I would say that the main reason is not quite correct use of temp tables on "Item List", they use RAM. Since there are a lot of them and perhaps because you have so many Items with different Attributes, the system loads it all into RAM. 
If this is a case, you either need to reduce the amount of data (filter data before browsing) or Microsoft can revise the existing Item and Item Attributes functionality(if something wrong with it).

Besides I would disable all third party extensions and try to reproduce this problem, maybe some third party extension is not optimized and writes too much to TemporaryRecords or just to Dictionary/Lists.

**Comment by dnpb** [comment]
The temp tables won't be using RAM in the browser, only in the BC server instance process on the server.

Anyway, this is off-topic, as it's not about the AL language or compiler.

**Comment by Drakonian** [comment]
True, RAM used on server instance, not browser.

**Comment by nndobrev** [comment]
This repository no longer handles general questions and is only dedicated to issue reporting for the latest preview version of the AL compiler and developer tools.

To get help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
