### ISSUE TITLE
Text overflow is not caught at build or runtime if implicitly converting Guid to Text or Code, AND it changes MaxStrLen!

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#7143]
With this code:
```al
pageextension 50100 Test extends "Customer List"
{
    trigger OnAfterGetCurrRecord()
    var
        TestCode: Code[20];
    begin
        TestCode := '';
        Message('MaxStrLen is %1 /  StrLen is %2', MaxStrLen(TestCode), StrLen(TestCode));
        TestCode := Rec.SystemId;
        Message('MaxStrLen is %1 /  StrLen is %2', MaxStrLen(TestCode), StrLen(TestCode));
    end;
}
```

***

The assignment of `Guid` to `TestCode: Code[20]` does an implicit conversion of the `Guid` to `Text`, **but**:
- This is not warned at build time.
- Nor does it cause an overflow error at **run** time! Only if we then use the `Code[20]` in another way, that will overflow, do we get a runtime error.

***

**Worse**... somehow the uncaught overflow of a 38-character string into the `Code[20]` **causes the `MaxStrLen()` of said Code to change/increase to the overflowing length**!!

The first `Message()`, before the offending assignment, shows:
![image](https://user-images.githubusercontent.com/63455896/186682360-97bca812-1e82-428c-88d2-5e633e536258.png)

The second, after the assignment, shows:
![image](https://user-images.githubusercontent.com/63455896/186682302-b66919cd-aff3-4b44-9ab4-f1eb68d6977e.png)

***

Pretty please... please fix so that
- the implicit conversion of Guid causes code analysis warnings if the destination isn't long enough for the textual version;
- said conversion will also cause runtime errors due to the overflow, instead of silently 'working';
- the overflow should not be allowed, and certainly the `MaxStrLen()` of the destination shouldn't be increased to match!!

Thank you!

***

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.4.663067
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10590.0 and VS Code Extension Version 12.0.790342. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
