### ISSUE TITLE
AL0505 errors that 'Pages of type API must have DelayedInsert unless Editable or InsertAllowed is false', when either IS!

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7145]
The error suggests we can fix it by adding either of those properties as `false`, yet it doesn't seem to actually check them at all.

Please fix so that it does. Thanks!

![image](https://user-images.githubusercontent.com/63455896/186888747-350ed44e-f93e-4a0c-bef3-f935bead0c2d.png)

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.4.663067
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by qutreson** [comment]
@dnpb - I cannot reproduce this issue. I get an error when none of the 'Editable' and 'InsertAllowed' properties are set to false, and as soon as one is set, the error disappears.

![image](https://user-images.githubusercontent.com/31541422/193989699-9cb041fe-2cfe-4f11-a83b-e357d3debe25.png)

![image](https://user-images.githubusercontent.com/31541422/193989648-a6c50249-2f3a-40a8-959e-3293d2af3b2f.png)

![image](https://user-images.githubusercontent.com/31541422/193989671-62bb4456-f9e7-4712-9cb6-ddad254b3ff4.png)

Note that allowing to set DelayedInsert to false when Editable or InsertAllowed is also set to false is controlled by a runtime version check (runtime > 7.2) since this behavior was introduced as a fix for github issue #6685 - before that, `DelayedInsert = true` was always mandatory.

![image](https://user-images.githubusercontent.com/31541422/193990054-23fa6901-2efa-4d69-95a7-2ae399ba1caa.png)

![image](https://user-images.githubusercontent.com/31541422/193990080-d6801526-6a42-44eb-a634-61c0a2fcd5a8.png)

**Comment by dnpb** [comment]
So what I'm seeing is that the diagnostic fires wrongly / with the wrong message for runtime <= 7.2, as in those cases neither (nor both) properties suffice to suppress. So, then, as well as the docs - doesn't the logic of the diagnostic/analyser need revised, too?

**Comment by qutreson** [comment]
@dnpb - What do you mean by "doesn't the logic of the diagnostic/analyser need revised, too?"? Is it about remove the runtime version check?

If yes, then we cannot change that because if you publish the extension on an older server (let's say version 14.*), then the server won't have the fix for the other Github issue and the recompilation of the extension on the server will fail.

**Comment by dnpb** [comment]
What I mean is that, against older runtimes, the diagnostic is still issued - saying we should set either property to avoid it - but setting either *or both* does **not** suppress the diagnostic.

So I would think older runtimes should produce a diagnostic 'DelayedInsert must be true for runtimes < FOO', instead of saying developers can add properties to avoid the diagnostic _which do not work_ :-)

**Comment by qutreson** [comment]
We will update the documentation and the diagnostic for it to explicitly mention the runtime.
