### ISSUE TITLE
Sticky Scroll : incomplete outline model

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/AL#7146]
Hi, I am filing a bug concerning AL and the sticky scroll feature in VS Code which I am developing. I talked previously to a person working on the AL team who mentioned precisely this issue through email, and it would seem like the fix is under development. In order to allow other users to track the issue, I will create this one.

The link to the issue filed on the VS Code side is : https://github.com/microsoft/vscode/issues/159335. I tested on Insiders and I find that the return value of VS Code's function OutlineModel.create() (which creates the outline using AL's document symbol provider) has an incomplete structure. I attach here a picture of the outline model printed in the developer tools after the creation, alongside the original code.

![issue](https://user-images.githubusercontent.com/61460952/187153515-5f13c183-4820-4343-8aac-79215d1919f5.png)

I can see several differences with what the input to sticky scroll is expected to be:

1. The key ending with `layout` in the tree should have as a child the scope corresponding to `field`. Currently the children array of the `layout` scope seems to be empty.
2. Both the range and the selection range corresponding to the `layout` scope show that endLineNumber is 6 and not 19, where the actual scope ends. 
3. The selectionRange should show as startLineNumber 4, not 3, as 4 corresponds to the line number where the scope actually starts, independently of the [TEST] decoration placed above it and other comments that could be present before the scope.

Thanks for the help, and I remain at your disposable for answering any questions.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.46878.0 and VS Code Extension Version 11.0.684497. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
