### ISSUE TITLE
Bug: General Ledger Entries - Export to Excel - Wrong data

### ISSUE THREAD

**Issue by vadimnov1** [microsoft/AL#7147]
The following data on General Leger Entries:
![image](https://user-images.githubusercontent.com/34141127/187492496-7feb3ee2-7e40-460c-b7ee-71fedb9ea44e.png)

Go to **Print & Send** -> **Microsoft Excel**.
Excel with empty **Source No.** and **Source Type** fields generated.
![image](https://user-images.githubusercontent.com/34141127/187492392-4ba99c56-3a0a-4dd7-b821-b6dc5056a1c4.png)
(It always takes the first value and fills all columns with it on **Source No.** and **Source Type** fields)

Its works well with other actions (Microsoft Word, Print Page).

Platform: NAV 2018
Build: 48794
Localization: BE

**Comment by dnpb** [comment]
As the template you used told you, this repo isn't for `customer-support`. As this isn't about the AL language or compiler, it's off-topic. It should be raised via Support.

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because this is about the runtime behavior of the BC application and it should go to the team that handles the application.
