### ISSUE TITLE
Debug webservice with OAuth2

### ISSUE THREAD

**Issue by dkorinets** [microsoft/AL#7150]
Hi, 

How to attach the debugger to the webservice session with OAuth2 authorization in the BC SaaS sandbox? 
Appreciate any information.

**Comment by Drakonian** [comment]
I would also ask why it is not possible to debug any system modules in BC?

**Comment by dkorinets** [comment]
Any update?

**Comment by kalberes** [comment]
Only snapshot debugging is supported for now for attach with Ouath2.  There, if you set up correctly postman for example that you are able to get a bearer token for the user who would run the webservice (Authorization OAuth2, Grant type password credentials, correct client id, correct client secret from your app registered with AAD and setup in BC) it is possible to snapshot debug it. 
Normal debugger attach still requires that the user who initiates the attach is the same user on behalf the webservice is run.
If that is the case you should be able to attach the same way, get a bearer token and use that to run your webservice. 

System modules cannot be debugged for now, since it contains sensitive code that was not decoupled from the debug engine.
