### ISSUE TITLE
AA0241 Default Severity

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/AL#7157]
**1. Describe the bug**
On the CodeCop website, it says AA0241 is the default warning, but you have to manually set AA0241 to warning in the ruleset, for the warning to actually show up.  #7156 needs to be fixed before this is fixed.
![image](https://user-images.githubusercontent.com/32099690/188901992-519414d1-4897-4eb6-b177-3bb956a24aeb.png)

**2. To Reproduce**
In the ruleset you have to add AA0241 to have it show up as a warning, instead of it being on be default which is what the website says.  
![image](https://user-images.githubusercontent.com/32099690/188902383-8cf205b3-2783-4e17-ade4-7ad0a390a9fa.png)

**3. Expected behavior**
Without having a ruleset of AA0241 the warning should be showing up after #7156 is fixed.  
**4. Actual behavior**
No warnings show up

**5. Versions:**

- AL Language: 10.0.671764
- Visual Studio Code: 1.69.1

**Comment by thloke** [comment]
In this case, the default severity is by design, and the docs need to be updated. Can you submit this feedback on the docs page? There should be a button at the end of the page to do this.

![image](https://user-images.githubusercontent.com/39045749/192989216-a041f0d8-9382-45f2-b095-1ab7e72fcaa3.png)

**Comment by thloke** [comment]
Actually don't worry about this, I've submitted the change to the docs repo to get it  in.
