### ISSUE TITLE
AA0072 CodeCop Rule - Incorrect warning with TestPage variables

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#7162]
**1. Describe the bug**
In test scenarios, when I declare a **TestPage** variable, this warning is displayed, but with **Record** variables (for example) it works fine and it is not displayed

**2. To Reproduce**
1. Setup CodeCops in `settings.json` file

```json
{
    "al.enableCodeAnalysis": true,
    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${UICop}"
    ]
}
```

2. Setup the app prefix in `appSourceCop.json` file
 
```json
{
    "mandatoryPrefix": "prfx_"
}
```

3. Declare a TestPage variable in a _[Test]_ procedure

![image](https://user-images.githubusercontent.com/5801847/189609003-a5933ff5-b75d-4265-a7bd-654c8d03f0a6.png)

``` AL
codeunit 90000 "prfx_Test IRPF"
{
    Subtype = Test;

    [Test]
    procedure SetupNewIRPFCodeWithANegativePercentageFromUI()
    var
        IRPF: Record "prfx_IRPF";
        IRPFList: TestPage "prfx_IRPF List";  // compiler forces us to name it as "prfx_IRPFList" to be ok
    begin
        // do something here!
    end;
}
```

**3. Expected behavior**
This warning should not be shown with this type of variables used in TESTs.

**4. Actual behavior**
The compiler forces us to add the prefix to the name of the variable of type TestPage

**5. Versions:**

- AL Language: v9.5.674382
- Visual Studio Code: 1.71.0
- Business Central: not related to a BC version
- List of Visual Studio Code extensions that you have installed: none

**Comment by TKapitan** [comment]
I think the same problem is with Report variables...

**Comment by thloke** [comment]
Thanks for reaching out. We’re focused on other things right now, but we’ve added this issue to our backlog. We’re planning to give the CodeCop engine and its rules an overhaul in a future major release. Thanks again!

**Comment by JavierFuentes** [comment]
Hi @thloke,

Any news about this Bug?
Why is this issue Closed?

As @TKapitan said, this bug continues to affect other types of objects such as Reports in latest `10.3.731181 version` of the "AL Language" extension.

**Comment by thloke** [comment]
As mentioned in the previous comment, we don't plan on addressing CodeCop issues right now and don't want to give the impression that the fix will be coming in the near future. So that's why the issue has been closed as not planned, since there's no roadmap for this yet.

**Comment by JavierFuentes** [comment]
@thloke ,
you don't plan on addressing **CodeCop issues**???

CodeCops are the only tool that guarantees to apply the Microsoft's Best Practices for AL...

Did you mean you don't plan on addressing **affixes issues** instead???

**Comment by dnpb** [comment]
No, they literally decided they were going to close all CodeCop related issues because they don't currently have plans and/or resources to address them... instead of keeping them open for everyone's reference but marking as not-planned or something.

This problem is not unique to Microsoft; I've seen multiple projects think this is a valid way to deal with bugs. But all it means for end-users is the closed issues are harder to find, as is any possibly valuable info they contained, and the issue doesn't get fixed unless someone else reports it later (who may or may not have all of said info, etc.)

I get that teams don't want to see Number Go Up forever, but I remain unconvinced that this tactic is ultimately good for anyone, except perhaps managers who want to see Number Go Down.

**Comment by JavierFuentes** [comment]
Managing issues in this way seems irresponsible to me...

Anyone could think that an entire project is going to be discontinued for closing issues with no more explanation than this.

I hope this is not the case for Business Central.
