### ISSUE TITLE
AS0069 - AppSourceCop not respecting EnumExt values when converting Option to Enum

### ISSUE THREAD

**Issue by djohnsoneque2** [microsoft/AL#7163]
Please include the following with each issue:

**1. Describe the bug**
AS0069 is not including enum extensions when checking the number of values an option field is being converted from.

**2. To Reproduce**

- Create table with one field of type Option with 8 option values
- Submit to AppSource and increment your version
- Modify table changing field to type Enum "Sales Document Type"
- Add enum extension to include new enum values
- Build the app

Field before the first submission:
field(1; "Document Type"; Option)
        {
            Caption = 'Document Type';
            DataClassification = CustomerContent;
            OptionCaption = 'Quote,Order,Application,Application Reversal,Certificate,Certificate Reversal,Invoice,Credit Memo';
            OptionMembers = Quote,"Order",Application,"Application Reversal",Certificate,"Certificate Reversal",Invoice,"Credit Memo";
        }

Field after the first submission:
field(1; "Document Type"; Enum "Sales Document Type")
        {
            Caption = 'Document Type';
            DataClassification = CustomerContent;
        }

Enum extension:
enumextension 9016662 SalesDocumentTypeEQ2 extends "Sales Document Type"
{
    value(9016659; "Application") { Caption = 'Application'; }
    value(9016660; "Application Reversal") { Caption = 'Application Reversal'; }
    value(9016661; "Certificate") { Caption = 'Certificate'; }
    value(9016662; "Certificate Reversal") { Caption = 'Certificate Reversal'; }
    value(9016667; "CS Invoice") { Caption = 'CS Invoice'; }
    value(9016668; "CS Certificate") { Caption = 'CS Certificate'; }
    value(9016671; "CS Credit Memo") { Caption = 'CS Credit Memo'; }
    value(9016672; "CS Certificate Reversal") { Caption = 'CS Certificate Reversal'; }
}

**3. Expected behavior**
App file to be created.

**4. Actual behavior**
App file is not created, error AS0069 is thrown.

**5. Versions:**

- AL Language: v9.5.674382
- Visual Studio Code: 1.71.0
- Business Central: 20.4.44313.44365
- List of Visual Studio Code extensions that you have installed: AL Language, Azure Account, Azure Functions, Azure Resources, C#, GitLens

**Comment by RobertJohnstoneEque2** [comment]
Hi,

Is there any update on this please?

Cheers.
Robert

**Comment by qutreson** [comment]
We have investigated this scenario and the proposed solution will not work fully. When considering enum extensions, the number of options and enum values will match, but their names and ordinal values will not be matching (because of the affixes and ID ranges used in AppSource).

If the option in your baseline is defined as follows: 

![image](https://user-images.githubusercontent.com/31541422/211527586-79e695d9-1f7a-477e-87bd-a9fc51ee045a.png)

Then you should use as a replacement, an enum that has the same values and ordinal values as the options previously defined. 

![image](https://user-images.githubusercontent.com/31541422/211527983-23cb138c-8400-47e6-b674-84997bfdf2d1.png)

![image](https://user-images.githubusercontent.com/31541422/211528014-045e884d-3290-4b55-8c5b-06764f5b3dfb.png)

If you change the ordinal value or the nameof one of the enum values (which is very likely for AppSource scenarios), then the conversion is not correct anymore and you get an error from the AppSourceCop:

![image](https://user-images.githubusercontent.com/31541422/211528397-fa86a19a-f0a0-4f47-9557-45918cb9b9ba.png)

![image](https://user-images.githubusercontent.com/31541422/211528350-91401f2b-aba1-4b7d-883c-920b8c83e0f9.png)

Based on this, it seems fine that the AppSourceCop isn't considering enum extensions in this scenario. However, if you see further improvements that could be done in the option/enum conversion experience and we would recommend them to be logged on aka.ms/BCIdeas.
