### ISSUE TITLE
Images that aren't available/usable on given runtime/platform don't warn AL0482 in VS Code, only when built on target server

### ISSUE THREAD

**Issue by dnpb** [microsoft/AL#7181]
For instance, action `Image = Download` against BC15 gives this:

![image](https://user-images.githubusercontent.com/63455896/193269373-cf30fdf4-6d29-4324-8716-0cbe909fb7c0.png)

So until we got that report from a user for [an unrelated, worse problem](https://github.com/microsoft/AL/issues/7180) - we had no idea we were using images that wouldn't work on BC15 and presumably just display the ugly default circle instead. That will look bad!

Please consider having a catalogue of which images are valid for which runtimes/platforms, and warn in VS Code if we don't match up - so that if images are not valid for the given runtime, we can be informed in VS Code and use ones that _are_ OK.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 9.5.674382
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
We have internally discussed this issue and have decided not to accept this issue to be fixed at the moment to prioritize other issues. Thank you for raising this concern.

**Comment by dnpb** [comment]
So, I have to remember to file it again after some arbitrary amount of time, for you to reconsider? Mmph...

I'm sure it's not your policy, but it seems really underwhelming to me, for MS to just close issues they aren't planning to work on. Such issues are still issues, and will continue to exist. Closing the tickets just invites more duplicates and more wasted time.

I understand that teams want to keep lists of issues/tasks relatively uncluttered, but I don't see how just closing them is any good way to do that. But I also know that many projects have decided to use this 'strategy', so I may be fighting a losing battle!

**Comment by thloke** [comment]
I understand that this is frustrating. We've been discussing internally what the best way to keep our github issue queue manageable is, and as you've noticed we've moved to closing issues when we don't see ourselves having the capacity to fix the issue in the foreseeable future. Keeping the issue open sends the message that we *might* fix it in the future, but realistically we won't have the capacity to do so (unless AL development skyrockets and we get the budget to do them all). 

In this case, we decided not to accept it because it's just a warning that will not block deployment even though it might show the default image at runtime. Also because we actually have no way at the moment of versioning the image resources at runtime, the cost of fixing it would include building that system - which given the severity of the bug meant that it didn't make the cut.

We really value the feedback we get on github. We also don't want to send the wrong message if we kept issues open for a long time without action either.

**Comment by dnpb** [comment]
> Keeping the issue open sends the message that we might fix it in the future, but realistically we won't have the capacity to do so

I understand the concern, but I would have thought that something like a label `not-planned` or such would be clearer, while keeping the issues open so that they're searchable and can be revisited later. We could then see that it had been reported, and acknowledged, if not planned-in yet. You could even lock comments while things were unplanned, to avoid all the 'me too!'s ;-)

**Comment by thloke** [comment]
We were going for the same message, but instead of using a specific label we're closing them as not planned, instead of closing them as fixed. I see the point that this will be a problem for people who only search open issues though.
