### ISSUE TITLE
No possibility to detect Cancel Action in Dialog (used as progress dialog)

### ISSUE THREAD

**Issue by LNitzsche** [microsoft/AL#7197]
I know this issue is not only related to the newest preview, but as I can see it has not be mentioned before.

The problem is the "Cancel" button when running a long query with progress dialog.

In earlier versions the users claimed missing the cancel button in the Dialog class.
The button is now available, but there is no documentation about how it works.
When pressing the button, the current running query is canceled and rolled back, but there is
no way to inform my program about the cancel action.
The menu action which started the query and the progress dialog are canceled without any notification.
I did not found any message in the event recorder, which may be used to detect this action.

In case of a normal exception like division by zero or forcing an error() you can catch this by encapsulating
the running task in the OnRun trigger of a code unit. In this case the Run() function or that code unit returns with false if an exception was raised. Here you have the chance to get program control back before leaving the OnAction trigger.

But the Cancel button in Dialog also skips this OnRun call and rolles back the complete execution stack including the OnAction trigger.

We have the need to detect the cancel action so we can reset some internal program variables or temporary tables.

Is it possible to customize the behavior of the cancel button of the Dialog class in any way?

Ordered by priority this would be useful
1. Subscribe to an event which informs me about the cancel action.
2. Override the "Do you want to cancel" message box and replace it by a custom dialog.
3. Hide the cancel button (not recommended, but may be required in some cases)
4. Add custom objects to the Dialog class.

I think the first point is the only one we need to solve out current problems.
Is there any possibility to customize the current Dialog class (I could not find any) or are there plans to extend the functionality of the Dialog class?

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
