### ISSUE TITLE
_ALException is <Out of Scope> in Section "Watch"

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7200]
Please include the following with each issue:

**1. Describe the bug**
You can insert __ALException_ in the Watch section, but instead of the contents of this variable, \<Out of Scope\> will be displayed.

**2. To Reproduce**

1. start the debugger and produce an error.
2. expand **Locals** in the **Variables** section
3. right-click on the variable __ALException_ and select **Add to Watch**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9556549/194761380-6f8ae1dc-f076-4e40-83f1-c811aa20bd8f.png">

**3. Expected behavior**
The value should be the error message as in the **Variables** section.

**4. Actual behavior**
The value is \<Out of Scope\>.

**5. Versions:**

- AL Language: 10.0.687650
- Visual Studio Code: 1.72.0
- Business Central: W1 21.0 (Platform 21.0.46384.46844 + Application 21.0.46256.46853)
- List of Visual Studio Code extensions that you have installed:
- AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.12086.0 and VS Code Extension Version 12.0.859781. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
