### ISSUE TITLE
PageCustomization intellisense not picking up actionref keywords

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/AL#7207]
**1. Describe the bug**
Intellisense does not show addfirst or other add..-keywords
![image](https://user-images.githubusercontent.com/53570297/195344823-42f66c76-d87f-46d5-a034-bf83fe8f6bde.png)

But we can type it on our own and the rest of intellisense is working
![image](https://user-images.githubusercontent.com/53570297/195344932-5449b8c7-1fc7-49f9-97a7-6183a023b588.png)

**5. Versions:**

- AL Language: v10.0.687650
- Visual Studio Code: 1.72.0

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 22.0.50101.0 and VS Code Extension Version 11.0.716839. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
