### ISSUE TITLE
Json Atomic structure

### ISSUE THREAD

**Issue by joshuahiwat** [microsoft/AL#7223]
Hi, 

Currently we can only attach relations into other relations, is it possible to add the atomic pattern to create relations in other relations with one request? 

Or do I need to create a separated extension for it ?

Related feature: https://jsonapi.org/ext/atomic/

**Comment by thloke** [comment]
Since this is an improvement, post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.

This repository only handles bugs in the existing development experience for AL.
