### ISSUE TITLE
The supplied column ID '34' cannot be found in the query.

### ISSUE THREAD

**Issue by gonzaloriosley** [microsoft/AL#7224]
If you run any report with dataitem into G/L Account and add a filter for any of the decimal flowfilters, you get the following error:

The supplied column ID '34' cannot be found in the query.

This error only happens in version 21

**Comment by ConceptCS** [comment]
Hi,
I have not found any issue, I have used Trail balance report, and put GL account's "Balance" field.

**Comment by seanlooby** [comment]
Hi, we also have the same issue

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by AliceThomas23** [comment]
Hi I am facing similar error for Business Central version 21.0 what could be the solution for this ??

**Comment by gonzaloriosley** [comment]
> Hi I am facing similar error for Business Central version 21.0 what could be the solution for this ??

For a temporary solution I would suggest to go to Chart of Account page, put the filter there, copy to Excel and build your filter for your report based on the field "No."

**Comment by thloke** [comment]
If you are having issues with running reports, please open a support case with CSS. We cannot handle the issue through this repo.

**Comment by AliceThomas23** [comment]
Noted Thankyou

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
