### ISSUE TITLE
action property Scope = Repeater does not work on ListPart pages

### ISSUE THREAD

**Issue by KosPav** [microsoft/AL#7235]
Please include the following with each issue:

**1. Describe the bug**
Scope = Repeater property does not work for pages of type ListPart

**2. To Reproduce**

1. Go to Jobs page --> Open any Job in Card page
2. Press "Show more options" on any line on "Tasks" subform

``` AL
page 1001 "Job Task Lines Subform"
{
    Caption = 'Job Task Lines Subform';
    DataCaptionFields = "Job No.";
    PageType = ListPart;
    SaveValues = true;
    SourceTable = "Job Task";
----------------------------------------------------------------
action(JobPlanningLines)
{
    ApplicationArea = Jobs;
    Caption = 'Job &Planning Lines';
    Image = JobLines;
    Scope = Repeater;

    trigger OnAction()
    var
        JobPlanningLine: Record "Job Planning Line";
        JobPlanningLines: Page "Job Planning Lines";
    begin
        TestField("Job No.");
        JobPlanningLine.FilterGroup(2);
        JobPlanningLine.SetRange("Job No.", "Job No.");
        JobPlanningLine.SetRange("Job Task No.", "Job Task No.");
        JobPlanningLine.FilterGroup(0);
        JobPlanningLines.SetTableView(JobPlanningLine);
        JobPlanningLines.Editable := true;
        JobPlanningLines.Run();
    end;
}
```

**3. Expected behavior**
action "Job &Planning Lines" is visible and available from repeater
like in this BC (DK Business Central 17.4 (Platform 17.0.21485.21516 + Application 17.4.21491.21531)):
![Screenshot_4](https://user-images.githubusercontent.com/45877997/200655913-4061cc45-aa01-4c26-a8d5-966b292092ba.png)

**4. Actual behavior**
action "Job &Planning Lines" is absent.
![actual](https://user-images.githubusercontent.com/45877997/200656220-a492a9f1-dd11-4b1a-bd39-8f25d108fea8.png)

**5. Versions:**
- Business Central: US Business Central 21.0 (Platform 21.0.46384.48780 + Application 21.0.46256.46853)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
