### ISSUE TITLE
XmlPort Boolean parsing not well defined or documented

### ISSUE THREAD

**Issue by itsme112358** [microsoft/AL#7243]
- Server Version (1): 18.5.29545.0
- Server Version (2): 18.16.44351.0

We have an XMLPort that exports and imports our Data Model so we can easily report model changes between versions to our customers.
We recently updated our legacy (BaseApp customized) product from 18.5 to 18.16.
The XmlPort seems to behave differently between both platform versions and I couldn't find anything related in the release notes.
In 18.5 boolean fields were serialized in the platform language, no matter which language was selected. (In our case de-de --> "Ja"/"Nein")
In 18.16 booleans seem to always get serialized in en-us. ("Yes"/"No"). Personally I think it always should have behaved that way and I like the change but the change should be documented somewhere.

I now tried importing the xml from one 18.16 database to another 18.16 database and get an error that "Yes" cannot be parsed to boolean. When I set my client language to en-us it gets parsed correctly.
So Import and Export behave differently within the same version. Export is always en-us. Import depends on the client language.

I reproduced in two Cronus Containers. The configurations are attached. Both are default configurations. Output generated by the following script:
```powershell
$containers|%{
Get-BcContainerArtifactUrl $_;
Get-BcContainerOsVersion $_;
Get-BcContainerCountry $_;
Get-BcContainerPlatformVersion $_;
Get-BcContainerServerConfiguration $_;
}|out-file c:\temp\container.cfg
```
Even though I would like to see XmlPorts being completely language agnostic (use en-us), the only thing I really care about is consistent behavior.
At least document the behavior so we know what we're working with. Please.
[container18.5.log](https://github.com/microsoft/AL/files/10030480/container18.5.log)
[container18.16.log](https://github.com/microsoft/AL/files/10030481/container18.16.log)

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because this is about the runtime behavior of XMLPorts and it should go to the team that handles the server runtime.
