### ISSUE TITLE
[Bug] Report Print Preview incorrectly triggers again OnInit and OnOpenPage

### ISSUE THREAD

**Issue by QuintasPedro** [microsoft/AL#7244]
Please fix this issue
We have several clients with BC 16 and older versions and all works fine

After migration to BC 18 and later versions there is now this problem
contrary to what was always the behavior also stated in 
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-triggers

Now when on Print Preview the code goes again incorrectly through triggers OnInit and OnOpenPage 
which makes it impossible to preview when there are some initial values that are set and that the user then changes.

![CodeExample](https://user-images.githubusercontent.com/115721034/201887191-425e3b5f-4ff0-4010-b522-46d1e5bde5c0.PNG)

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because the execution of reports is related to the runtime behaviour of BC, so it needs to go to the team who handles the runtime.
