### ISSUE TITLE
Repeater cannot clone control for type: Microsoft.Dynamics.Framework.UI.FormHostControl because it does not implement the IRepeatable interface or the interface implementation returns a control type that is not valid.

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7250]
Please include the following with each issue:

**1. Describe the bug**
The web client crashes when a page part is placed in the wrong location. In the event log you can find the exception error message `Repeater cannot clone control for type: Microsoft.Dynamics.Framework.UI.FormHostControl because it does not implement the IRepeatable interface or the interface implementation returns a control type that is not valid.`.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/9556549/203256149-0cac8eb5-2b17-486f-9a72-e5e0f3ffffb0.png">

**2. To Reproduce**

1. Publish these to extensions and open the Page 518 (Purchase Lines).

``` AL
pageextension 50100 "Purchase Lines" extends "Purchase Lines"
{
    layout
    {
        addlast(Control1)
        {
            part("Document Comments"; "Purch. Line Comm. Factbox")
            {
                ApplicationArea = All;
                Caption = 'Document Comments';
                SubPageLink = "Document Type" = field("Document Type"),
                              "No." = field("Document No."),
                              "Document Line No." = const(0);
            }
        }
    }
}
```

```AL
page 50100 "Purch. Line Comm. Factbox"
{
    ApplicationArea = All;
    Caption = 'Purchase Line Comments';
    Editable = false;
    PageType = ListPart;
    SourceTable = "Purch. Comment Line";

    layout
    {
        area(Content)
        {
            repeater(Lines)
            {
                field(Date; Rec.Date)
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field(Code; Rec.Code)
                {
                    ApplicationArea = All;
                    Visible = false;
                }
                field(Comment; Rec.Comment)
                {
                    ApplicationArea = All;
                }
            }
        }
    }
}
```

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
The web client should not crash. Prevent this either at publishing and in the AL compiler or do not show this page part.

**4. Actual behavior**
Web Client crashes

**5. Versions:**

- AL Language: 11.0.706681
- Visual Studio Code: 1.73.1
- Business Central: DE Business Central 22.0 (Plattform 22.0.49091.0 + Anwendung 22.0.49695.0)
- List of Visual Studio Code extensions that you have installed:
  - AL Language

We discovered this problem in the current version of BC 21.1 and I tested it with the current next major version.

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Hello, this issue is out of scope for the current repository. I will pass this bug on to the relevant team and close the issue.

The reason why this is out of scope is because it relates to the behaviour of the BC client, so it needs to go to the team who handles the client. This repository only handles issues related to the AL language and compiler.

If it is a critical issue, you can follow the instructions below:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by BazookaMusic** [comment]
For future reference, this issue is covered by this UICop rule: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/uicop-aw0003

This should show a warning when a part is added by mistake to a repeater
