### ISSUE TITLE
Import from a data file throws 65 seconds timeout / on-prem environment

### ISSUE THREAD

**Issue by Iselit** [microsoft/AL#7252]
Hey guys :)

We got the following error on our Business Central on-prem environment:

![image](https://user-images.githubusercontent.com/118813756/203299518-a88ca9e3-9f05-4e5e-97b9-6a2501dadda2.png)

We have done all fixes we found on the internet, including:

https://community.dynamics.com/business/f/dynamics-365-business-central-forum/434741/import-from-a-data-file-throws-65-seconds-timeout-on-prem-environment/1197939

https://community.dynamics.com/business/f/dynamics-365-business-central-forum/370515/business-central-on-prem-unable-to-upload-a-data-file/

- Check IIS for upload limits also, (IIS>>Request Filtering>>Max allowed content)
- Set-NavServerConfiguration BC -KeyName 'ClientServicesMaxUploadSize' -KeyValue '1000'
 
- Increase content length for BC Site 
 
- Increase Request length for BC site

Upload via Powershell works. The file is 480MB. We also have a Ticket at Microsoft Site, but maybe someone here has a solution where this 65 Seconds limit is stored and where it can be increased.

**Comment by dnpb** [comment]
This isn't an event request, and this isn't a support forum ;-)

**Comment by Iselit** [comment]
Can you move my request to the right one?

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You can do one of the following (not sure if the ticket on the microsoft site falls into these):

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because this is about runtime behavior and not related to the compiler.
