### ISSUE TITLE
While importing Excel file not able to import Text Field value more then 250 characters

### ISSUE THREAD

**Issue by Sami401** [microsoft/AL#7254]
Currently the Excel Buffer table ""Cell Value as Text" field length is 250 while the excel sheet cell text can accept more than that. This need to change or need alternative solution for this.

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You can do the following if you want this addressed:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

The reason why this is out of scope is because this is about an application table, which needs to be handled by an application team which owns that table.
