### ISSUE TITLE
Code Action: fix implicit with only available for the warning, not the error in BC21

### ISSUE THREAD

**Issue by lvlaanderen** [microsoft/AL#7260]
Implicit with is now an error in BC21 but we can't use the code action to fix the issue as it only exists for the warning.
To get around it we can remove NoImplicitWith from features in the app.json so it becomes a warning rather than an error, but this adds the risk it isn't put back
Can we have the same actions for the error that we have for the warning?

**Comment by BazookaMusic** [comment]
I believe this was discussed in Yammer and I'll repeat the answer here. The NoImplicitWith flag changes the way we bind objects. This means that we cannot recognize an incorrect identifier from an implicit with, because implicit withs are essentially deleted from the language. Thus the error is a generic error about the identifier not being available. The conversion action cannot be defined on top of that.

The solution if someone wants to convert a project and prevent further additions of implicit with values is to do the following:
1) Remove NoImplicitWith flag
2)  Convert all violations with the rule
3) Add the NoImplicitWith flag
