### ISSUE TITLE
Remove sensitive information from DebuggerServices.log

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7286]
**1. Describe the bug**
I just discovered while working on #7273 that if you enable "al.editorServicesLogLevel" : "Verbose", really sensitive information is stored in **DebuggerServices.log**, such as the environment name, the tenant ID, and the current bearer token. If someone accidentally posts this information in an output without knowing how dangerous it could be, an attacker could hijack the session and do God knows what to the client tenant.

![image](https://user-images.githubusercontent.com/9556549/208178887-ca9a0cf7-117e-40f9-b194-d53151a68eb4.png)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10005.0 and VS Code Extension Version 12.0.762394. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
