### ISSUE TITLE
AL: Publish and open the designer (F6) doesn't work with larger extensions

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#7288]
Please include the following with each issue:

**1. Describe the bug**
If you try to use the Designer from the AL Language Extension (AL: Publish and open the Designer (F6)) with larger AL projects, you get the error message **An error occurred while applying designer changes. Please try again.**

**2. To Reproduce**
I solely use the shopify app as repo example.

1. Open Shopify AL project (https://github.com/StefanMaron/MSDyn365BC.Code.History/tree/master/shopify/app/Shopify%20Connector)
2. Run "AL: Publish and open the designer" (F6)
3. Change something (I moved Balance (LCY) before Name on the Customer Card)
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/9556549/208197687-ae41e748-5b23-4f81-a8bf-5726d9bb2539.png">

**3. Expected behavior**
The designer should work.

**4. Actual behavior**
You get an error message: An error occurred while applying designer changes. Please try again.

**5. Versions:**

- AL Language: 10.2.719883
- Visual Studio Code: 1.74.1
- Business Central: DE Business Central 21.2 (Platform 21.0.49939.50985 + Application 21.2.49946.50997)
- List of Visual Studio Code extensions that you have installed:
  - AL Language

### Final Checklist
Please remember to do the following:
* [x] Search the issue repository to ensure you are reporting a new issue
* [x] Reproduce the issue after disabling all extensions except the AL Language extension
* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

Issues with the designer do not fall under the scope of this repo.
