### ISSUE TITLE
Warn on FlowFilter as Column in Query Object

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/AL#7295]
Please include the following with each issue:

**1. Describe the bug**
When you use a FlowFilter as Column in a Query the Query Object cannot be used. 

**2. To Reproduce**
Add any FlowFilter field to a query object

``` AL
query 50000 MyQuery
{
    QueryType = Normal;
    
    elements
    {
        dataitem(Customer;Customer)
        {
            column(No_;"No.")
            {
                
            }
            filter(Date_Filter;"Date Filter")
            {
                
            }
        }
    }
}
```

**3. Expected behavior**
The compiler should at least warn on a FlowFilter field in the query column. Better would be an error.

**4. Actual behavior**
No warning or error. A runtime Error occurs at executing the query.

**5. Versions:**

- AL Language: v10.2.719883
- Visual Studio Code: 1.74.2
- Business Central: AT Business Central 21.2 (Platform 21.0.49939.51260 + Application 21.2.49946.49990)
- List of Visual Studio Code extensions that you have installed:

**Comment by dnpb** [comment]
What runtime error?

I would think this should work, instead of being a build-time error.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
