### ISSUE TITLE
Creating Keys for Base Application is Essential

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/AL#730]
I have seen the issue #456 (Standard Table Field Keys in Table Extension). Since this issue is closed, but not resolved I would like to raise awareness that for serious data volumes creating keys for base application fields as well as own fields in Table Extensions is really really necessary.

In the last 10 years, I had so many performance issues, which was ether, solved be Microsoft or creating the right key. Please consider enabling the creation of additional keys for us.

**Comment by cmrudolph-msft** [comment]
Thanks for the feedback. We know this is important and are considering alternatives that solve the performance problem without actually requiring changes to the base (shared) table's indexing situation.

**Comment by megel** [comment]
The limit of about 40 keys should also be considered.

**Comment by alanb999** [comment]
What about the fact that the base code does not use the proper key?

**Comment by DanielGoehler** [comment]
Don‘t get my intension wrong. For a NAV Key an SQL Index will be created. E.g. If you have large amounts of entries in a table and no index for a fields, SQL Server has to lookup every entry, which takes longer than using the index.

**Comment by DanielGoehler** [comment]
Just a thought: 

How about enable the possibility of **mixed keys**?

Technical speaking I would split the key for the different tables. For every related table (base table, other extension and my extension) there should be a key, which only contains the fields of its table. 

For creating that SQL Key, I would only create it, if there were no matching key for my **partial key**.

**Comment by cmrudolph-msft** [comment]
Mixed keys has technical merit, but is problematic from the standpoint of multiple tenants living in the same tenant database. We want to avoid alterations to the base/shared table completely. We are more likely to implement something that lets us define the new index completely on the extension's table (like platform-managed field mirroring for fields needed in new indexes).

**Comment by hhfiddelke** [comment]
To add another view to this discussion. There may be also the need to change/extend primary keys (which is currently not possible if i understand the posts above)
Customers may for example need to implement Sales Prices by Responsibilty Center or time dependend (happy our). 
This is curently possible in C/AL by changing the Primary Key and extending the "Sales Price Calc. Mgt."- Codeunit. How can we handle this in AL?
It's just an idea: 
What would happen if we remove the primary key as we know it today and change it internaly to an Entry No, . This would allow any secondary (virtual primary) key. There would be some adminstration effort to ensure that (virtual primary) keys are uniqe by tennant on writing tables, but reading should be easy via Entry No. . Probably Tenant and Master use the same Entry No. as "Master Primary Key"

**Comment by sgiordy** [comment]
> We are more likely to implement something that lets us define the new index completely on the extension's table (like platform-managed field mirroring for fields needed in new indexes).

@cmrudolph-msft any news about this feature? Add mirrored fields to table extension and improve the query generator seems the most quick and right way. Working with extensions in real and huge environment is a big issue without this feature.

Thank you
S.

**Comment by cmrudolph-msft** [comment]
@sgiordy This unfortunately has not made the cut yet. It's on the current priority list, but that list is still being refined. We hear about this often and understand it is a problem.

**Comment by JSebastianN** [comment]
I have a specific example.
I need to Enable a base key, which is disabled by default.

Is this possible, as of now?

**Comment by cmrudolph-msft** [comment]
@JSebastianN No - not supported.

**Comment by sgiordy** [comment]
@cmrudolph-msft remind :D please remember about keys, flowfield and related performance issues ... without these (or similar) functions only  small customers can go on 365BC cloud. Thank you.

**Comment by demiliani** [comment]
Adding custom keys to standard tables is a must to have. There are very high performance issues when you have a huge amount of data in a standard table and you can’t add the key you need. We need a way to create a table extension and add a new key. Modifying existing ones I can agree that could be avoided.

**Comment by Hilbekale** [comment]
We have the same issue. We need specific keys for standard ledger tables. The workaround to mirror the fields in the table extension is not an option for us.

**Comment by lvanvugt** [comment]
How about disabling an existing standard key, by setting **MaintainSQLIndex** to false?

From a performance perspective this is common practice to do every now and then. Especially on big tables like Sales Shipment Line.

Is this considered for the future?

**Comment by hhfiddelke** [comment]
I Think **MaintainSQLIndex** to false is not the solution, because especialy flowfields on Ledger Entries require well adjusted realy existing keys. 

What happens if both keys needed?
What happens if primary key has to be changed?

And as Hilbekale already said. mirroring is not a solution, because other extension may also require the same information (f.e. Sales Pricees)

**Comment by lvanvugt** [comment]
> I Think MaintainSQLIndex to false is not the solution, because especialy flowfields on Ledger Entries require well adjusted realy existing keys.

Agree in general, but tuning your application from a performance perspective it might be needed (and possible in the context of flowfields etc.) to disable an index based on a BC key as the system is maintaining it while it's of no use.

**Comment by gintuoklis** [comment]
Would like to hear about it as well. Is there a plan for supporting custom keys or not?
As far as we can, this is one of the main concerns for moving our on-premise to extensions. 
Due to performance reasons we had to modify quite some keys:
for e.g. 

- disabling standard keys is very common. not all parts of the standard NAV application is used. Therefore there's no point to maintaining the key for them. for e.g. we don't use lots and variants. after key is disabled we often create simplified version of the same key. 
- in addition to that, where are some strange MS decisions when it comes to adding keys on big tables like item ledger entries (MS 2018 CU6). in those case we also like to disable keys, and remove functionality.
- similar case happens with other add-ons. for e.g. we are using LS Retail add-on, where we also modify keys for the biggest table to tackle performance issues.
- change PK for temporary tables. it's common practice to use buffer table for grouping data before posting. you can see this pattern in MS code, and other add-ons. It's very common change to add custom field into the primary key of the table so you would include your custom field into the grouping. 
- for Item table we have we have custom key that combines MS fields, LS fields, and our fields. We use this key as main sorting for the Item list. Since this page is so often used, we made this sorting option as a key. 

what would be other alternatives? 

- we could mingle with indexes on SQL level without NAV even knowing.  On SQL level we can disable keys, or make indexed for combining multiples tables. On the other hand, this approach would lead to management, and deployment problems.

**Comment by AbsolutelyFreeWeb** [comment]
Question, If I understood it correctly, cross keys are possible for fields part of the primary key ([comment by Hunter Feltman](see [post by hunterfeltman](https://github.com/Microsoft/AL/issues/1054#issuecomment-349714153)). But I cannot get it to work. How do you reference fields part of the primary key of the main table in the table extension key ? And could that key replace the original primary key?

**Comment by HunterFeltman-MSFT** [comment]
@AbsolutelyFreeWeb - It seems that this functionality has either been removed since I made the comment that you mention or I was originally mistaken.

In any case, it is not currently possible to refer to the PK fields in your key lists.

**Comment by srikar1405** [comment]
In D365 BC RTM Version Can we add standard fields in keys ?

**Comment by 48010** [comment]
Hello, any update of this?

Many functionalities need their own keys, we need to add the keys we want using standard fields. How could we change the Combine shipments process to create invoices with different conditions from standard?

There are no MS answers since May, please give appropriate importance.

Regards

**Comment by 48010** [comment]
I have found a solution that may be valid for some of you. When you set a SETCURRENKEY or a SORTING on a Page or Report, for example, you can now combine the order of the fields the way you want. I mean, you don´t need to create a Key with the specific fields in a specific order. You can create your new fields as an extension and then put the fields to the SORTING in the way you want.
That´s my example:
I have created a Tableextension with the fields above:
![image](https://user-images.githubusercontent.com/44604388/47720104-629f4e00-dc4d-11e8-9de2-3f20f753d175.png)

And after that have created a Key:
![image](https://user-images.githubusercontent.com/44604388/47719795-81e9ab80-dc4c-11e8-9fc5-a33c949ce140.png)
Finally, I have used those fields in a Report:
![image](https://user-images.githubusercontent.com/44604388/47720193-9ed2ae80-dc4d-11e8-8521-8181df9ae0d2.png)

As you see, no error alerts are in the code, and I have be able to check that this works ok by using that key on a List page.

Hope someone find this interesting.

Regards

**Comment by lvanvugt** [comment]
Maybe I am sleeping, but this was also possible in C/AL, right?

**Comment by Hilbekale** [comment]
This was already working in C/AL. This has nothing to do with performance. This is only for sorting. The only way to achieve this, is the usage of field mirroring, If you need a new key which combines standard fields and new fields. 

The described topic is still a big issue, because you can not create an index in the sql server (cloud) and you don't can add new key especially for SumIndexFields and so on.

**Comment by AbsolutelyFreeWeb** [comment]
@hilbekale please provide a link how field mirroring works. if I try to create fields with same names of tve main table I’d get error. I ended up creating a completely new table for now.

**Comment by Hilbekale** [comment]
@AbsolutelyFreeWeb I think there is not a guide for mirroring fields, but the base concept is to copy the fields into your extension with an different name.

Example: 
Item Ledger Entry - Document No.
Item Ledger Entry Extension - Document No. Extension

You can now create subscriber for the table events (Item Ledger Entry OnInsert / OnModify) and synchronize the standard field "Document No." into your extension table. 

After that, it should be possible to add a key in your extension to all needed fields, because there are part of your table extension. 

As you can see, this solution is horrible, but it can solve this problem with a workaround. There are some cases, which were not covered with this workaround.

**Comment by JulianTillmann** [comment]
@Microsoft: Are there any News regarding Keys? This is an issue for many extensions, what are your plans?

**Comment by marpacca** [comment]
Any News? It's planned for the future.

thx

**Comment by salgiza** [comment]
FWIW, there is an entry related to this in "Microsoft Idea"'s site and Microsoft's answer is that they will only consider it if it receives enough votes (I just gave it my vote):

https://experience.dynamics.com/ideas/idea/?ideaid=5a2cfc87-1f52-e911-b047-0003ff68d113

It wouldn't fit every need (the idea is just to be able to create new keys that don't "mix" fields) but at least it would be a start...

**Comment by ivandjordjevic** [comment]
So should we fully implement key mirroring in case we need key combination of standard + extension fields or there is a solution on the horizon supported by platform?

**Comment by n-conlon** [comment]
Hi, any update on this please?

**Comment by waldo1001** [comment]
Any update? @esbenk

**Comment by KennieNP** [comment]
Unfortunately, no update on this for the 2020 release wave 2

**Comment by waldo1001** [comment]
@KennieNP ,

Well - quite a significant part of performance problems is the lack of keys - developers that forget to create keys.
Not having the ability to create them - and no focus on being able to do so - is quite strange, imho.. :-/

**Comment by Hilbekale** [comment]
This is one of the major reason for me to not update our solution to Extension code. 

I tried it with the complete database and performance is horrible in some cases. Mirroring standard fields and add this to my extension is the only solution, but this is not applicable for every requirement. 

Without having a proper solution, big or highly custom databases will have troubles within BC with AL.

This should be addressed sooner than later.

**Comment by marknitek** [comment]
Maybe a silly question, but i was wondering (with all the performance issues we are facing especially with multiple extensions on key tabkes) why we have extension fields in own sql tables anyway? It seems like the seperation of table extensions into seperate sql tables does more harm then good... 
Is it about max no. of fields? Multi Tenancy? 
Iam just curious about the reasons behind since it has such a large impact. 

Sure we can redesign things to avoid table extensions for key tables but having just one extension on for example ledger entries or posted sales invoices has a serious impact on large customers (upgraded)... With extension fields on the same sql table there would be no issue and keys would work without issue too.

**Comment by waldo1001** [comment]
I think it's most about the flexibility of being to support any combination of apps.  This way, all data of an app is isolated.  In the other case, installing/upgrading/uninstalling would be a table-impact on possibly a "heavy" table.  No way to do that "inline" or at runtime ..

**Comment by Hilbekale** [comment]
also the table has a max size. Therefore you can not have unlimited amount of apps, if you would add the fields into one table.

**Comment by Magicrevette** [comment]
> @AbsolutelyFreeWeb I think there is not a guide for mirroring fields, but the base concept is to copy the fields into your extension with an different name.
> 
> Example:
> Item Ledger Entry - Document No.
> Item Ledger Entry Extension - Document No. Extension
> 
> You can now create subscriber for the table events (Item Ledger Entry OnInsert / OnModify) and synchronize the standard field "Document No." into your extension field.
> 
> After that, it should be possible to add a key in your extension to all needed fields, because there are part of your table extension.
> 
> As you can see, this solution is horrible, but it can solve this problem with a workaround. There are some cases, which were not covered with this workaround.

I am trying this method to add a new key in a table extension, but I'm not sure how I should do this step : 

"synchronize the standard field "Document No." into your extension field."

Could you please give me some details ?

**Comment by dtkb** [comment]
They mean you'd need to create a field in the ext that has the same type/length, and copy from the standard field to your copy whenever the value can change, i.e. on insert/modify.

**Comment by Magicrevette** [comment]
What method in my code should I use to copy the value of the standard field everytime it changes to my own ?

**Comment by hhfiddelke** [comment]
Mirroring fields into an extension is not working well, especialy if sizes or types (option->enum) is changed in main table. This will kill your extension.

**Comment by dtkb** [comment]
Just subscribe to OnAfterModify/OnAfterInsert of the base table and if the value has changed from your copy, copy over the new valid and modify the record.

And yeah, I don't say this is a good idea, but its ugliness is matched by its simplicity.

**Comment by Hilbekale** [comment]
@Magicrevette Yes, synching them with table event subscribers OnAfterModify/OnAfterInsert, but as stated above there are a lot of disadvantages to it. 

In general the workaround is the only possible solution in some cases, but it does not mean that it is really a good idea. We can only hope that Microsoft tackles this problem or you have to rethink your solution and how you approach it from the technical side.

**Comment by Mike-1984** [comment]
Since there is no clear answer from Microsoft, we have decided create our own extension/solution to address this problem.
It will work only with On-Premises installation since direct SQL access is required.

Idea is pretty simple:
Use globally accessed configuration table (similar to Object Metadata) to store "Cross-Table" key and SumIndexFieds configuration.
Create/Maintain indexed SQL Views which combine table and all table extensions.
Create/Maintain indexed VSIFT SQL Views to support SumIndexFields
Create a library codeunit with functions to access the data in the views.

In all performance critical parts, use the provided functions

**Comment by midegoXperit** [comment]
Any updates regarding this request?

**Comment by KennieNP** [comment]
Check the release plan for 2021 wave 1 (when it is released)... :)

**Comment by midegoXperit** [comment]
> Check the release plan for 2021 wave 1 (when it is released)... :)

Cheers :)

**Comment by dtkb** [comment]
> Check the release plan for 2021 wave 1 (when it is released)... :)

Where can we check that? I'd love to tell my colleagues this will be fixed. But I'd need a cite ;-)

**Comment by midegoXperit** [comment]
> > Check the release plan for 2021 wave 1 (when it is released)... :)
> 
> Where can we check that? I'd love to tell my colleagues this will be fixed. But I'd need a cite ;-)

When it is being released you can find them here: https://docs.microsoft.com/en-us/dynamics365/release-plans/

**Comment by KennieNP** [comment]
Unfortunately, this is not available until January 2021 (I think).

**Comment by FranckCovens** [comment]
I cannot believe this issue is not solved yet...
The reason is obvious : Microsoft do not use their own products...
We work on our BC project (on-prem) but I do not want to hack SQL Server using Table triggers to copy data from standard tables to their extensions...

Microsoft : DO YOU JOB!

**Comment by waldo1001** [comment]
I'm happy it's finally on the table, and we have a date: April 2021.  

Looking forward!

**Comment by lvanvugt** [comment]
Indeed, Rome wasn't build in one day.

**Comment by db-bc** [comment]
Sales Price is deprecated, to be replaced with the new Price List functionality. And that has a key consisting simply of a Price List Header No and a Line No. So it will not conflict to enter multiple per customer.

This issue was about _creating_, i.e. new, keys - not modifying PKs, even if that were needed. The former has been released, so I don't see why it's still open.

**Comment by salgiza** [comment]
@JesperMoHansen I don’t think extending primary keys has ever been on the table (and is not what this ticket is about).

Anyway, Microsoft redesigned how prices work a few versions ago, just so that you could do exactly what you want to do: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations

**Comment by JesperMoHansen** [comment]
Sorry to get the wrong opinion on what the original ticket was about. Lost the right point of view reading through the thread.

Thanks db-bc for letting me know about V.16. I'm aware of that. This was just one of the easiest sample on where a possibility to extend the PK was needed.

Could someone redirect me to the right thread on the issue where this is discussed.

@salgiza Thanks for the link.
And then - I have hoped the comment from Waldo was regarding putting this issue to the bench.

**Comment by KennieNP** [comment]
I suggest we close this issue.

In v15, we added telemetry for long running SQL queries so that you can identify queries that might need an index.
In v18, we added the ability to add a key to a base table using a table extension, so that you can add indexes to every table.
In v19, we added support for NCCIs and INCLUDE column in indexes so that you get a lockless edition of SIFT indexes.
In v20, you will have a "missing indexes page" in the app to show you insights from the SQL query optimizer on indexes it would have liked.

I do not see us adding support for indexes that span base and companion tables any time soon.

**Comment by waldo1001** [comment]
May be we could come up with design guidelines concerning these cases?

**Comment by salgiza** [comment]
@waldo1001 That would be a good idea. At the end of the day, with the correct indexes in both the base table and the extended table, the performance hit of doing a join between them should be very low, but I'm not sure that many people understand this, nor how these "correct indexes" should be defined.

@KennieNP Maybe it would be a good idea if the missing indexes page could even take a hint for this and make it clear when an index was required by a join with a table extension? So that when someone sees the recommended index and thinks... "but I didn't make a query using just those fields", can easily understand where that suggestion is coming from (not sure if this is feasible, though)

**Comment by pborring** [comment]
I am closing this based on summary from Kennie. For any additional scope support, please log an idea and vote on https://aka.ms/bcideas

**Comment by KennieNP** [comment]
> @KennieNP Maybe it would be a good idea if the missing indexes page could even take a hint for this and make it clear when an index was required by a join with a table extension? So that when someone sees the recommended index and thinks... "but I didn't make a query using just those fields", can easily understand where that suggestion is coming from (not sure if this is feasible, though)

Unfortunately, this information is not available in the DMV we read from SQL.
