### ISSUE TITLE
All selected rows in WebClient are not recognized as markedonly(true)

### ISSUE THREAD

**Issue by dzakojc** [microsoft/AL#7303]
Issue: 
as user selects all rows records are not marked as Rec.MarkedOnly(true), but if user selects all rows by manually clicking every row, then the code returns true.

**Positive case: Rows are selected using keyboard shortcut CTRL+A -> all rows are marked in the WebClient as expected**
User steps:
+ open any list page (Job Planning Line)
+ mark all rows by key combination CTRL+A -> all rows are marked in the WebClient as expected
![image](https://user-images.githubusercontent.com/82892937/211883737-25a7a679-0b4f-4e9b-8746-766ff078d46f.png)

technical issue: Below code returns false, I expect to return also true.
![image](https://user-images.githubusercontent.com/82892937/211883905-072198d4-0fdb-4b12-ba61-a5f05dbe3712.png)

**Negative case: Rows are selected by the user by holding down CTRL + click with left mouse button on each row.**
User steps:
+ open any list page
+ hold down the CTRL key and click with left mouse button on a row to mark the row
+ repeat for all rows in the list
-> all rows are marked in the WebClient as expected
![image](https://user-images.githubusercontent.com/82892937/211883147-55d3b234-0b79-4804-9f66-a0f68e2eb38b.png)

Below code is executed as expected and returns true as expected
`JobPlanLineRec.MarkedOnly(true)`
![image](https://user-images.githubusercontent.com/82892937/211883382-8f41b185-3be3-455f-b530-c6a1e5d7f2a7.png)

**5. Versions:**
- AL Language: v10.3.731181

- Visual Studio Code:
      Version: 1.74.2 (user setup)
      Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
      Date: 2022-12-20T10:29:14.590Z (3 wks ago)
      Electron: 19.1.8
      Chromium: 102.0.5005.167
      Node.js: 16.14.2
      V8: 10.2.154.15-electron.0
      OS: Windows_NT x64 10.0.19045
      Sandboxed: No

- Business Central: System: BC v21 (SaaS)
+ Platform 21.0.49939.51627 + Application 21.2.49946.49990

- List of Visual Studio Code extensions that you have installed:
+ AL Language
+ AZ AL Dev Tools/AL Code Outline
+ AL XML Documentation

Thank you
BR Damjan

**Comment by JMA1972** [comment]
Your coding is not correct. After Currpage.SetSelectionFilter you work with the record (in your case JobPlanLineRec) without any  markedonly-enquiries exactly because there are no markings if all records are selected or only one record is selected. The user doesn't even have to select a record explicitly if they only want to work with the current record. That means aside from an empty table Currpage.SetSelectionFilter always gives you one or more records back.

**Comment by dnpb** [comment]
Yeah, you don't need to check anything in this case, as YOU are the one doing `SetSelectionFilter()`

In more generic functions receiving a `var` record without indication of source, you may want to check if it has _any_ marks *or* filters, and if not then do `SetRecFilter()` to only work on the passed-in row instead of all... but in this case as mentioned there's no need to. Just count/loop/whatever after `SetSelectionFilter()`.
