### ISSUE TITLE
AS0056 warning for supported country

### ISSUE THREAD

**Issue by TKapitan** [microsoft/AL#7306]
**1. Describe the bug**
Our Next-Major pipelines show a new warning: ##[warning]./c:/sources/App/AppSourceCop.json(1,1): warning AS0056: The code 'cz' is not a valid ISO 3166-1 alpha-2 code for a country/region supported by the product.

We run a Next-Major once a week; the previous run (08.01. - 22.0.51788.0) was without any problems. The Next-Major pipeline that shows the warning is based on "22.0.52078.0"

**2. To Reproduce**
I found a similar problem https://github.com/microsoft/AL/issues/7299 but based on the BC versions, it doesn't look like the same cause...

Version: 22.0.52078.0
Platform: 22.0.52062.0

**Comment by TKapitan** [comment]
Now the same warning started even for the Next-Minor 21.4.52114.0

**Comment by jwikman** [comment]
@TKapitan, You've probably already figured this out - but changing the country code to UPPERCASE should solve the issue. So use 'CZ' instead of 'cz'.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10005.0 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
