### ISSUE TITLE
local procedures in a table cannot be called within that table if using `Rec.` prefix, cause AL0161 error

### ISSUE THREAD

**Issue by dzzzb** [microsoft/AL#7309]
![image](https://user-images.githubusercontent.com/63455896/213448509-33c9cdfe-b626-4ce9-9f9a-47e6e4f76dac.png)

I *do* get it, that local methods aren't accessible via other record instances, and here `Rec.` is not considered special by the language... but since in plenty other places it is *implied* and needn't be typed, and code is the same either way - maybe local methods can be too? So then, code would act the same if someone put `Rec.` there when they didn't strictly need to - e.g. if cutting/pasting from a page.

Thanks!

```none
Name: AL Language
Id: ms-dynamics-smb.al
Description: AL development tools for Dynamics 365 Business Central
Version: 10.3.731181
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

**Comment by thloke** [comment]
We have the same limitation with `CurrPage` on pages, and the limitation extends to local variables too. In general, I think this can be lumped into an improvement around allowing access to `local` procedures/variables through the self-referential variables.

It's not trivial though, I'm pretty sure this will require some refactoring on how we do our emit, since we do not emit the same code for `Proc()` and `Rec.Proc()`. 

Since this is an improvement and not a bug, you can post this to our Ideas forum at https://aka.ms/BusinessCentralideas, or vote up the idea if its already there. We're constantly monitoring top Ideas and will consider them for a future release.
