### ISSUE TITLE
TestField shows error on the wrong field

### ISSUE THREAD

**Issue by MakGM-FORTO** [microsoft/AL#7313]
I have put an event to test field on the Vendor record. The event is called on Vendor No. field validation from the Purchase Invoice card page. The vendor has the field "Fiscal Code" empty.
Expected behavior:
Error is shown on the "Vendor No." field
Actual behavior:
Error is shown on the field with the same name, but which wasn`t tested via the TestField.
Please see the example code and screenshots:
``` al
[EventSubscriber(ObjectType::Table, Database::"Purchase Header", 'OnBeforeValidateBuyFromVendorNo', '', false, false)]
    local procedure OnBeforeValidateBuyFromVendorNo(var PurchaseHeader: Record "Purchase Header")
    begin
        TestVendorInformation(PurchaseHeader."Buy-from Vendor No.");
    end;
    local procedure TestVendorInformation(VendorNo: Code[20])
    var
        Vendor: Record Vendor;
    begin
        Vendor.Get(VendorNo);
        Vendor.TestField("Country/Region Code");
            Vendor.TestField("Fiscal Code");
    end;
```
![image](https://user-images.githubusercontent.com/89254286/214045755-b6dd3ed3-a7f2-44a5-9e4d-1c6a681a128e.png)
![image](https://user-images.githubusercontent.com/89254286/214045836-530e6ba3-b2fb-4824-8af9-81e2fcf863c5.png)

As an example of expected behavior see, Country/Region:
![image](https://user-images.githubusercontent.com/89254286/214045892-efbf7691-482c-4b18-b065-04321084c202.png)
Note that if field is removed from the page code works as expected:
![image](https://user-images.githubusercontent.com/89254286/214046477-16a66a74-64c3-4d85-8e1a-7cf4cc4a589d.png)

Why this is a problem?
The field is hidden deep below and users don`t understand where the "problem" mentioned in the error on the Vendor No field is.
Users try to change values on the Purchase Invoice card instead of the the Vendor Card and still left with an error.

**Comment by dnpb** [comment]
I believe that in order to suppress this questionable behaviour, you can wrap the other `Validate()` in a `TryFunction`, then if an error occurs, rethrow it via `Error('...')`; IIRC for me this 'fixed' it to ensure the error was thrown at the original validated field, not an indirectly validated one.

**Comment by MakGM-FORTO** [comment]
Well, replacing TestField with a simple error actually fixed the problem for me. The issue seems to be with TestField itself, so I am curious about what it is
```al
if Vendor."Fiscal Code" = '' then
   Error(FiscalCodeErr, Vendor.FieldCaption("Fiscal Code"), Vendor."No.");
 ```

**Comment by dnpb** [comment]
I think it is simply that if a page is open, it detects the error from `TestField` or `FieldError` specifically, and tries to be helpful by rearranging/moving the location(s) where the error is reported.

I actually saw this going worse - when a field on the table threw such an error, it was attributed to a control for a *different* field on the page, that just happened to have the same name and/or caption (I can't remember which, guessing the latter) - which goes right out of the realm of 'trying to be helpful', firmly into 'bug'. Unfortunately I only have so much time to file bugs, and that one never made it anywhere more suitable yet :-)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. This needs to go to the team that handles the actual running of AL code on the server. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
