### ISSUE TITLE
Cancel AppSource Extension - Wrong Fork Submitted

### ISSUE THREAD

**Issue by fibbert** [microsoft/AL#7319]
This is probably the wrong forum - but does anyone know where you submit a request to stop the publishing of an AL Extension if you accidentally uploaded the wrong version?  We will have a breaking change if we don't remove this.

**Comment by EmilDamsbo** [comment]
This is out of scope, however...
If your extension version has not been made public, you can still upload a new version without the wrong one being used as the baseline, thus avoiding a breaking change.
Otherwise please refer to this documentation page on who to contact with this: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-checklist-submission-faq#channels-to-ask-questions-or-report-issues
