### ISSUE TITLE
Extension Upload with missing dependency, Needs Better Error Reporting

### ISSUE THREAD

**Issue by fartwhif** [microsoft/AL#7320]
We are uploading an extension to SaaS which is dependent on multiple other extensions, but only some of them are already installed.  Upon extension install attempt the following error is emitted: 

`Deployment failed. Errors: App ID : 90afcb50-1dd9-4159-84a6-d5764aef2364 Message : { The app (or one of its dependencies) does not have a version that is compatible with other installed apps on the tenant. } - Job Id : e16403ea-1a85-4b8f-95ab-7182ba43747e`

The error given is very broad, confusing, and nearly unhelpful.  The error should include the fact that the problem is that one or more of the required extensions are missing, and at least one of their names.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
