### ISSUE TITLE
Error in the OnClosePage doesn't matter in the report BC21.3

### ISSUE THREAD

**Issue by michuanni** [microsoft/AL#7330]
**1. Describe the bug**
When in the report in OnClosePage an error message is placed, then this error don't stop the process.

**2. To Reproduce**
I have created a process only report with the following trigger.

        trigger OnClosePage()
        begin
            Error('Error');
        end;

I have also created a page with the follwing action.

            action(Test)
            {
                Caption = 'Test';
                ApplicationArea = All;
                Image = TestReport;
                trigger OnAction()
                var
                    Rep: Report KVSTestError;
                begin
                    Rep.Run();
                    Message('After Message');
                end;
            }

**3. Expected behavior**
I expect that, if an error message is triggered, then the process should be aborted.

**4. Actual behavior**
The process continues despite an error message.

**5. Versions:**

- AL Language: v10.4.747197
- Visual Studio Code: 1.75.1
- Business Central: 21.3

**Comment by dannoe** [comment]
Was this working in C/AL?

You can throw errors or return false in OnQueryClosePage (see [docs](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/page/devenv-onqueryclosepage-page-trigger)). OnClosePage is called after OnQueryClosePage, so I would assume that it is too late to return to the page.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
