### ISSUE TITLE
Import Excel doesn't work on BC 21

### ISSUE THREAD

**Issue by fgilsc** [microsoft/AL#7334]
Hi,
When I try to import an excel file on BC21 it returns:

![image](https://user-images.githubusercontent.com/15670597/221921089-3ecd9d1d-5980-4f58-b6d2-3585b09ce7b3.png)

It crashes in all Excel Imports methods that they work on previous versions.

What can I do?

Version: W1 21.0 (Platform 21.0.46384.46844 + Application 21.0.46256.46853)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
