### ISSUE TITLE
Report Extension with InDataSet-Variable from extended Report as Visible/Enabled

### ISSUE THREAD

**Issue by SKeiler** [microsoft/AL#7336]
In 20.4. I have to dependend Extensions. Extension B has Extension A as dependency. Extension A has a Report Extension of the BaseApp (bug is also reproducable with a standalone report of Extension A) with a Checkbox on RequestPage. The Checkbox-Variable ist protected (to use it in Extension B) and also has the InDataSet-Property set. In Extension B I also have also a Report Extension for the report extension auf Report A to use the checkbox-Variable to control the enabled-property of an additional field on request page.    

For the Compiler everything is okay, but when I try to start the report I get the following error "The identifier XYZ could not be found" (check the picture).

There are .zips attached which contains 2 .al- Files Please put one into 1 workspace, publish the app and put the second file into another workspace and build a dependency from Extension B to Extension A (Unfortunally the file limit prevent from update the whole worksprace). 

 The picture are the erorr message. Please publish boths Apps to your Environment and open Req. Worksheet and there start the Carry Out Action. Than the error occurs.

See also on Yammer: https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=2157899806728192

![Error](https://user-images.githubusercontent.com/45033081/222212733-07f7ee1a-4ed1-4da7-8bbc-0f7424697b73.jpg)
[SAM1CarryOutActionMsgReq.ReportExt.zip](https://github.com/microsoft/AL/files/10863718/SAM1CarryOutActionMsgReq.ReportExt.zip)
[SAM2CarryOutActionMsgReq.ReportExt.zip](https://github.com/microsoft/AL/files/10863722/SAM2CarryOutActionMsgReq.ReportExt.zip)

**Comment by thloke** [comment]
Does this reproduce in BC22? We've had quite a few bugfixes in this area.

**Comment by SKeiler** [comment]
Doesn't tested it in BC22, only in BC21.4

**Comment by thloke** [comment]
Can you try to see if this repros in BC22?

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.

**Comment by SKeiler** [comment]
Could you please reopen the issue (or should I create a new one)? The problem still existing...

**Comment by thpeder** [comment]
I'll take a second look at this.

**Comment by thpeder** [comment]
Hi @SKeiler,

I just tried to reproduce issue but without luck.
With the latest version of Business Central, and your two objects I first saw that for the SAM2 file it gave me an error in Visual Studio Code, for the line `Enabled = ReleaseOrders;` telling me that the variable doesn't exist.

But since you are able to publish the app, then I thought maybe the issue was that we don't register the variable as being "inDataSet", when they are protected and are declared in another object. That didn't give me an error either, and when looking at the code behind it was handled as expected.

It looks like you have found and issue in and earlier version but this GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.

**Comment by SKeiler** [comment]
Hi @thpeder ,

we tested it in BC23.1 (and I could also test BC23.4). For the current development preview currently I don't have the preparations.

I had also opened a Partner Souce case for it (that I thought was the reason why you reopend the case). 

Is variable "ReleaseOrders" is created in Extension SAM1. There are a dependency-Tree. BaseApp <- SAM1 <- SAM2, where SAM2 uses a protected var from SAM1. So if you get the error, that the variable ReleaseOrders doesn't exist, it seems that you don't have installed SAM1.

**Comment by thpeder** [comment]
I see, I forgot to add the dependency between the two ReportExtension apps.
Now I got the reference to the `ReleaseOrders` variable but the page in the web client shows no error for me. I see that the field is now disabled, but otherwise everything is fine.
![image](https://github.com/microsoft/AL/assets/24276180/79d74a9c-a58f-409d-9acb-fd1261ff9cab)
