### ISSUE TITLE
'Send...' button in purchase order list doesn't attach custom report if you don't print it with 'Print...' before

### ISSUE THREAD

**Issue by rreiul** [microsoft/AL#7340]
We've created a custom report and added it in report selection - purchase.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/91983917/223715100-13e08cd1-5f53-4e9c-8551-99224bfbe3f1.png">

If purchase order list, if we select a record and press 'Send', the custom report we've created won't be added to 'attached files'. But it we press 'Print' before, the custom report will be added to 'attached files'.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/91983917/223716004-dc951cb3-b4cd-48f0-a958-6eafd82609e6.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/91983917/223716401-98e373e5-8238-4374-9e6a-40a68df6afaf.png">

I think that's a bug.

Thank you. :D

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
