### ISSUE TITLE
PowerBI DSA LUX Report Error

### ISSUE THREAD

**Issue by josephpellicano** [microsoft/AL#7341]
Our client has a Power BI report which was working but now is giving the error below. The automatic refresh of the Power BI rapport (LUX) Daily Settlement Advise - Highover analysis gives the following error. {"error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","pbi.error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","parameters":{},"details":[\{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2147467259"}},\{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"An error happened while reading data from the provider: 'Invalid operation. The connection is closed.'"}},\{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2147467259"}},\{"code":"Microsoft.Data.Mashup.ValueError.DataSourceKind","detail":{"type":1,"value":"SQL"}},\{"code":"Microsoft.Data.Mashup.ValueError.DataSourcePath","detail":{"type":1,"value":"tcp:<ip>xx.xxx.xx.xx</ip>,1113;Power BI"}},\{"code":"Microsoft.Data.Mashup.ValueError.Reason","detail":{"type":1,"value":"DataSource.Error"}}],"exceptionCulprit":1}}} Table: DSA - Card Reimbursement G/L Entries. When checking the SQL we think that the table is too big for the refresh, as for another database, we have trimmed the table to only show recent data, and it's working. Can we identify the reason why this happens please?

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
