### ISSUE TITLE
Record of a page loses global boolean during OnValidate event

### ISSUE THREAD

**Issue by EC-Janeck** [microsoft/AL#7345]
**Describe the bug:** When I set a global Boolean on a page and then try to pass that Boolean onto the record through typical setter methods the record of the page “forgets” the Boolean during the OnValidate event on the record field. 

**To Reproduce Steps to reproduce the behavior:**
  - I build a sample extension: https://github.com/EC-Janeck/AL-Table-Issue which boils down the issue.
  - Simply open the page through the page action “Open Test List” on the Sales Order List page
  - Then insert a record and enter the description, which then fires the OnValidate event prompting a message stating if the Boolean     retained its value

**Expected behaviour:** I expect the Boolean to still be set to true during the OnValidate event on the description field of the table. I have pretty much thrown the book at this (InDataset, protected variables, all the triggers of the page, runmodal instead run on the page etc.). While there are crutches to get to the behaviour I want none of them is elegant and addresses the bug at hand.

**Actual behaviour:** The Boolean stays falls despite being correctly set through the page’s triggers on the record, before the OnValidate event. 

**Versions:**
  - AL Language: 10.5.765371
  - Visual Studio Code: 1.76.0
  - Business Central: W1 21.5 (Platform 21.0.53597.53794 + Application 21.5.53619.53819) onPrem as Docker
  - Docker Desktop 4.17.0 (99724)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. This needs to go to the team that handles the runtime behaviour of AL. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
