### ISSUE TITLE
Special Char (&) in Object name makes DocComments.xml invalid

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#7353]
**1. Describe the bug**
Having an Special Char like & in Object Name leads to an invalid DocComments.xml file and will hide inline documentation in intelisense.

**2. To Reproduce**
Create an Object with Special Char and try intelisense
``` AL
codeunit 50100 "PTE A&B"
{
    /// <summary>
    /// Any Documentation
    /// </summary>
    procedure DoSomething()
    begin
    end;
}
```

You can also unpack the compiled app and throw the generated DocComments.xml in an validator. That will fail.
Generated DocXomments.xml:
```xml
<?xml version="1.0"?>
<doc>
    <application>
        <id>e06618b0-cd4f-4a98-a1ea-05327c708fe0</id>
        <name>TechDocTestApp</name>
        <publisher>Default publisher</publisher>
        <version>1.0.0.0</version>
    </application>
    <members>
        <member name="M:Codeunit::PTE A&B.DoSomething">
            <summary>
            Any Documentation
            </summary>
        </member>
    </members>
</doc>
```
Try validation at https://www.xmlvalidation.com/
![image](https://user-images.githubusercontent.com/18051656/227227619-8992603a-3ff0-4d5f-9cb2-18d7129cb093.png)

**3. Expected behavior**
Special Chars should be encoded or something

**4. Actual behavior**
Intelisense do not show inline doc:
With Special Char:
![image](https://user-images.githubusercontent.com/18051656/227226950-ee36b9fd-c2ad-4360-8572-108251a1bfe8.png)
Without Special Char:
![image](https://user-images.githubusercontent.com/18051656/227227123-068eedf8-af5c-4074-af64-3cd1f8765f67.png)

**5. Versions:**

- AL Language:
- Visual Studio Code:
- Business Central:
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10536.0 and VS Code Extension Version 12.0.788495. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
