### ISSUE TITLE
#pragma warning disable AL0432 is ignored when backgroundCodeAnalysis is set to "File"

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/AL#7359]
**1. Describe the bug**
When working with `"al.backgroundCodeAnalysis": "File"`, `#pragma warning disable AL0432` is being ignored: Warning AL0432 is shown (again).

**2. To Reproduce**
Set up `"al.backgroundCodeAnalysis": "File"` in either your user or workspace settings file.
Obsolete an object of your choice, and suppress upcoming AL0432 warnings with `#pragma warning disable AL0432` as usual.
While still being in the edited file, check the warnings in the Problems tab. (Reload Window, if necessary.)

(When setting `"al.backgroundCodeAnalysis": "Project"` and restarting VS Code, AL0432 will vanish as expected.)

**3. Expected behavior**
Warning AL0432 is not shown.

**4. Actual behavior**
Warning AL0432 is still shown.

**5. Versions:**
- AL Language: 11.0.779295
- Visual Studio Code: 1.77.0

**Comment by guidorobben** [comment]
Had the same issue

**Comment by BazookaMusic** [comment]
Found the bug, it is an issue with how we filter some of the diagnostics when in file mode. The next VSIX release will contain the fix.

**Comment by BazookaMusic** [comment]
To add some detail on the impact of this bug, it is annoying but it does not affect compilation. It is only the compilation for displaying the warning on the current file that does the incorrect filtering of diagnostics in the end. The build output will not contain the warning that is being silenced.

Thus it is safe to keep file mode, if the speedup is significant enough, until the fix is deployed.

**Comment by NKarolak** [comment]
Thanks Sotiris :-)
BTW, can you also take a look at that case?
https://www.yammer.com/dynamicsnavdev/threads/2208354471714816
We partners rely on "AL: Package" to find all warnings (unless there aren't too many of them). With v11, we cannot.
