### ISSUE TITLE
Recordref.GetTable does not remember global variables from the parameter table

### ISSUE THREAD

**Issue by Pharrious** [microsoft/AL#7367]
**Issue**
Sometimes you need to call SetHideValidationDialog before running through some FieldRec validations.

```
Job.SetHideValidationDialog(true);
RecRef.GetTable(Job);
```
Sadly the RecRef global variable 'HideValidationDialog' is not true.
Instead of changing the current function, another function could be introduced.
RecordRef.GetTableFromVar(Var Rec: Table)

**Odd alternative - ProcedureRef**
```
if(RecRef.GetProcedureByName(MyProcedureRef, 'SetHideValidationDialog')) then begin
  MyProcedureRef.AddParameter(var parameter : variant);
  MyProcedureRef.Invoke();
end;
```

I know I could PR a event into GetHideValidationDialog.
Setup a singleInstance codeunit with manual binding.
Remember to disable the binding again.
But it just isn't clean, and it isn't dynamic (working for all other functions) like the GetTableFromVar solution.

**Comment by jensmpmsft** [comment]
The RecordRef Data Type exposes all the methods that are shared across all record types. It copies the field contents and the filters - but not type specific variables. So this is currently by design.
I do understand your scenario well - so I would recommend posting this on aka.ms/bcideas - to evaluate the need for this.

Off the top of my head, I would imagine that we would rather allow you to call RecRef.GetTable(Record, bool:shareTable) - which would then not copy it.
