### ISSUE TITLE
Menu of extension app does not appear in Role Explorer

### ISSUE THREAD

**Issue by Loisel21** [microsoft/AL#7379]
**1. Describe the bug**
Menu of extension apps does not appear in Role Explorer

**2. To Reproduce**
Publish a custom extension app with rolecenter actions

**3. Expected behavior**
Rolecenter menu should appear in the Role Explorer. Same Code does work in DE Business Central 21.4 (Platform 21.0.52534.52982 + Application 21.4.52563.52989)
![image](https://user-images.githubusercontent.com/61054888/233616955-04b3f05b-4cca-4210-be63-4972671fa502.png)

**4. Actual behavior**
Rolecenter menu does not appear in the Role Explorer
![image](https://user-images.githubusercontent.com/61054888/233616419-68eefb7c-ed38-4bcc-88cc-2d7ed6a750ee.png)

**5. Versions:**
- AL Language: v11.0.787898
- Visual Studio Code: 1.77.2
- Business Central: DE Business Central 22.0 (Platform 22.0.54512.0 + Application 22.0.54157.54635)
- List of Visual Studio Code extensions that you have installed: AL Language extension for Microsoft Dynamics 365 Business Central

AL code sample that triggers the issue
[ALProject12.zip](https://github.com/microsoft/AL/files/11294975/ALProject12.zip)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
