### ISSUE TITLE
[BUG] trash in tenant media table

### ISSUE THREAD

**Issue by JPicard90** [microsoft/AL#7380]
we notice that Tenant media table (and tenant media thumbnail) is filled with records that have 
"{437DBF0E-84FF-417A-965D-ED2BB9650972}" 
and 
"{C526B3E9-B8CA-4683-81BA-FCD5F6B1472A}"
in description
 if you try to download the content of this records seems to be 2 logos of 2 microsoft extensions (i've attached those files)
seems to happen from 1/1/2023, we are working with Swiss localization in SAAS 

deleting it didn't make any negative changes, everything works fine and our DB release almost 10 GB of data but BC keeps recreating this records every time a user login to BC

![file](https://user-images.githubusercontent.com/20781085/233561901-36656d96-39e9-4c01-ba9a-ac00930554b4.png)
![file (2)](https://user-images.githubusercontent.com/20781085/233561923-dabe0fba-aae5-415c-b07c-93492724c763.png)

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by JPicard90** [comment]
i've opened the issue in ALAppExtension, idk why it has been trasfered here (microsoft support suggest to post the issue there) , however i've opened a similar issue some month ago and actually you have fixed -> https://github.com/microsoft/ALAppExtensions/issues/20403 
so ok if you don't want to fix i will keep delete manually the garbage from table 🤷‍♂️

**Comment by JPicard90** [comment]
> Hi, this issue is out of scope of for this repository. You should do one of the following:
> 
> * Open a support request to CSS through the PartnerSource portal
> * Open a bug in Collaborate
> * Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
> 
> As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

i've opened the issue in ALAppExtension, idk why it has been trasfered here (microsoft support suggest to post the issue there) , however i've opened a similar issue some month ago and actually you have fixed -> https://github.com/microsoft/ALAppExtensions/issues/20403
so ok if you don't want to fix i will keep delete manually the garbage from table 🤷‍♂️
