### ISSUE TITLE
AL Compiler Wrongly Checking Commented Code

### ISSUE THREAD

**Issue by navmihaimarian** [microsoft/AL#7384]
Hi All,
   

     I am using a cloud container having this version:
![image](https://user-images.githubusercontent.com/132066321/235139078-c30cbf22-e63a-4fa1-8db7-a35a72280ac9.png)

In my local AL Project I want to fix this warning AA0210:
![image](https://user-images.githubusercontent.com/132066321/235139284-dcf5c952-5eec-4973-aef3-585c7e4a0daf.png)

If I write the following commented code in the Item Extension table extension:
![image](https://user-images.githubusercontent.com/132066321/235140112-1ef50a60-0344-4ece-b566-256392650383.png)

THEN: The compiler does not see the AA0210 warning anymore. I think it should see it as a warning,  because the above key is commented.
![image](https://user-images.githubusercontent.com/132066321/235140333-ad91fc7a-0ac8-41a6-9515-1d8c804b9304.png)

**Comment by thloke** [comment]
@navmihaimarian - two questions:

1. Does the warning come up when you do a full build?
2. Does the warning appear if you set "al.backgroundCodeAnalysis": "project" in your settings.json?

I suspect this is to do with the optimization around code analyzer running being done per-file instead of per-project. The reason why the error doesn't come up once you comment the file is because the focused-file has changed and so you will get code analysis warnings for that file only. If you switched back to the codeunit and made a change, the diganostics will re-appear.

**Comment by JMA1972** [comment]
I think the real issue here is that he gets a warning in the first place. All 3 fields are flowfilters so it's impossible to build keys with them.

**Comment by thloke** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
