### ISSUE TITLE
Bug in OnAfterGetCurrRecord Subscriber in BC14

### ISSUE THREAD

**Issue by MacGnol** [microsoft/AL#7411]
I made a subscription to Page 95 "Sales Order Subform" - OnAfterGetCurrRecord and first my Subscriber was executed and after my subscriber the Page trigger "OnAfterGetCurrRecord" was executed.

Accordingly to the official documentation, first the Page trigger should be executed, and after that my Subscriber.

I have tested it in BC14.

**Comment by nndobrev** [comment]
This GitHub repository is dedicated to handling issues and feedback for the latest Developer Preview releases of the AL development tools for Dynamics 365 Business Central. 

If you can reproduce the problem on the latest Business Central Developer preview version we will be happy to look further into it. Otherwise please contact the regular support channel.

You can open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also step by step direct you how to open a support request or how to get credentials if this is the first time for you / your company.
