### ISSUE TITLE
The extension package that you are trying to install has a different set of tables and table extensions than the extension package that has been previously synchronized when the 'forceUpgrade' parameter set to true in the launch.json.

### ISSUE THREAD

**Issue by clasalal** [microsoft/AL#7412]
The issue #7364 persists in the latest bc images (22.1) if you have the 'forceUpgrade' parameter set to true in the launch.json file. If this parameter is removed, the error no longer occurs.

**Comment by f4n0** [comment]
same issue here:
BC22 RTM

Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 11.0.787898
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by minaskats** [comment]
+1

**Comment by fvet** [comment]
+1

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.11502.0 and VS Code Extension Version 12.0.834301. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
