### ISSUE TITLE
Error in AssistEdit button in New Security Group

### ISSUE THREAD

**Issue by RodrigoPuelma** [microsoft/AL#7425]
**1. Describe the bug**
I am not sure if this is the place to create a ticket for this error, but the Microsoft support agent could not resolve it for us.

We are trying to test the security groups functionality in a sandbox created at a production trial for a potential customer. When pressing the assist edit button in the New Security Group page to select from existing security groups in AAD, the web client crashes with a "Something went wrong" error (see image below). 

We contacted the Microsoft support and were told that the log states that the error occurs because of the tenant is a production trial. We do not experience this error in our own sandbox and the user account used has SUPER in Business Central and admin in AAD.

We are not sure on how to proceed since the potential customer works extensively with security groups in AAD and wants to be able to test additional custom logic in Business Central with security groups. Any assistance would be appreciated.

![image](https://github.com/microsoft/AL/assets/35121934/fb4d9d00-e005-45de-b6d0-37b66bbb46a1)

**2. To Reproduce**

1. In Business Central, search and select Security Groups list page.
2. In Security Groups, select New.
3. In New Security Group, select AssistEdit for AAD security group name.

**3. Expected behavior**
See available security groups to select from.

**4. Actual behavior**
Web client crashes with "Something went wrong" error.

**5. Versions:**
- AL Language: v11.0.787898
- Visual Studio Code: 1.78.2
- Business Central: 22.1.55890.56216
- List of Visual Studio Code extensions that you have installed: clean Cronus AU company with no extensions installed.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
