### ISSUE TITLE
Wrong xliff Generation for NextMajor (23.0.x) - Property OptionCaption is generated for table fields of type Enum

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7427]
Please include the following with each issue:

**1. Describe the bug**
In our NextMajor Pipeline we check against translations and there we receive wrong xliff files.
We receive a xliff node for Property _OptionCaption_ for fields of type Enum.

**2. To Reproduce**

1. Create a Table Field with type Enum
2. Generate Translations.

it migth be related to the property `GenerateCaptions` that we have enabled in our app.json.

```json
  "features": [
    "TranslationFile",
    "NoImplicitWith",
    "GenerateCaptions"
  ]
```
**3. Expected behavior**
There shouldn't be an entry for OptionCaption Property in the `*g.xlf` File

**5. Versions:**
- AL Compiler: C:\bcartifacts.cache\sandbox\23.0.10941.0\VSIX\extension\bin\win32\alc.exe

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 23.0.10970.0 and VS Code Extension Version 12.0.810454. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
