### ISSUE TITLE
Table field captions are generated even without GenerateCaptions flag

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/AL#7436]
Issue was already reported here https://github.com/microsoft/AL/issues/7415. But I don't agree that it is "bydesign".

Check help: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files

It says "The generated XLIFF file contains the strings that are specified in properties such as Caption, CaptionML, and Tooltip.". In this case none of these properties are specified.

It also says "By setting the GenerateCaptions flag in the app.json file, you specify that you want to generate captions based on the object name for pages, tables, reports, XMLports, request pages, and table fields.". It says that table field caption is generated when this option is selected. So I think it should not be generated when option is not selected.

I think it's a bug...

**Comment by thpeder** [comment]
We will have a hard time changing that right now, since the behaviour of always giving a table field a caption is being relied on, and I don't see a lot of value in changing it right now. but please tell me about the scenario where this is causing problems for you.

For your interest we are updating the docs, to reflect the way it currently works.
