### ISSUE TITLE
Best Practice for creating 2D/3D Barcodes in Extensions?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#744]
What is the Best Practice for creating 2D/3D Barcodes in Extensions without .NET?

Currently we create a Image which will be Stream as Blob to RDLC Report Layout.

**Comment by johndcollins** [comment]
Not sure if there is any best practices yet,  I think the best way to use .net if you have to, is to write your functions in Azure Functions and call them from NAV with Web Service calls.

**Comment by DanielGoehler** [comment]
I read that answer "Azure Functions" very often. Is there any example how to work with files (cf. #739)?

**Comment by johndcollins** [comment]
The reason you read about Azure Functions a lot is probably because it's the only way to accomplish what you want to do in the new version. I'll have to look into file handling myself and find out how to do this, but I don't have any examples yet I can share.

Here is what I would investigate:
There are probably not many examples of how to work with files from NAV yet, but I'm sure there are examples on how to use Azure Blob Storage from Azure Functions. The Azure Function would need to be able to pass files to and from your Azure Functions. The function should then be able to save/retrieve these files using an azure blob storage. Then upload or download the files to an ftp server. This is also how the ISVs who deal with EDI/Bank Files will have to deal with this.

For more NAV/Azure Functions examples:
https://www.youtube.com/watch?v=Wp13-nfVoEg&feature=youtu.be

**Comment by mrabus** [comment]
Have a look at the following blog by Arend-Jan Kauffmann: [http://www.kauffmann.nl/2017/07/18/al-web-service-examples/](url)

There he shows how to utilize a web service to generate a barcode.
