### ISSUE TITLE
Trouble with Codeunit DimensionManagement (Reference to object DimensionManagement is ambiguous)

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/AL#745]
If I reference Codeunit **DimensionManagement** the Pre-Compiler shows the following Error Message:

> Reference to object DimensionManagement is ambiguous. Make sure you are not referencing packages containing objects with the same names.

![ohne titel](https://user-images.githubusercontent.com/9556549/31321309-7464a8e6-ac84-11e7-9e0d-ba305a515ce6.png)

**Comment by StanislawStempin** [comment]
I cannot reproduce this error. Creating a variable of type codeunit DimensionManagement works fine.

Could you double check that you don't have any other symbols in your solution named DimensionManagement? If not, can you try to isolate the issue and provide a code sample that reproduces it?

**Comment by DanielGoehler** [comment]
I found out that the unusable Property **SIFTLevelsToMaintain** in a few **Keys** created that issue (See #756).
Here a sample project which has this error.

[Simple Project.zip](https://github.com/Microsoft/AL/files/1377528/Simple.Project.zip)

**Comment by DanielGoehler** [comment]
I test VsCode with a solution of 2700 objects (1600 are new objects and the rest are object extensions). After converting with txt2al.exe the Pre-Compiler found 1500 Errors. Now I start at the top and go to the bottom of the list to fix these errors in order to get the solution build.

I have the same Error Message with other Codeunits now. I found out, that if you delete the Symbol Files and close and reopen the solution **Go to Definition** brings you to another object. In my case to a Pages which has the same Codeunit in some function as variable, but also a Property ControlAddin, which is not supported and cause an right now. If I comment that out, the ambiguous is gone.

**Comment by qutreson** [comment]
Hi @DanielGoehler, it seems that the error you have here was a side consequence of using ControlAddin as a property as you described above. My guess here is that the parser is facing an unexpected keyword (since in V2 ControlAddin is an application object) which gets the parser confused. The parser then considers the reference to the codeunit DimensionManagement that you have in the variable section as a new declaration of the codeunit and not as a reference. If you look among your 1500 errors, you should then have an error saying "An application object of type 'Codeunit' with name 'DimensionManagement' is already declared". Since the parser thinks that you have multiple declaration of this codeunit, this is why you get an ambiguous reference error. 

You can find here a small snippet that would trigger this behaviour by inserting a unexpected keyword:
![image](https://user-images.githubusercontent.com/31541422/35267970-3357cf0c-0028-11e8-9a60-c79077edb159.png)

If the bogus field is fixed, then all the errors disappear.
![image](https://user-images.githubusercontent.com/31541422/35268118-916dc060-0028-11e8-8a9c-39cffc5843f7.png)

If you are still facing this situation, fixing other errors would then also fix your issue with ambiguous references.
