### ISSUE TITLE
AL Developer Fails To Remember Cached Credentials - Every request needs a new devicelogin

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7453]
**1. Describe the bug**
Since the latest update of the AL Language Extension every time I Download Symbols or I try to publish some app file i have to 
go through the DeviceLogin Process. (Similiar to the issue https://github.com/microsoft/AL/issues/6905, but it's affected on Docker Developement Environments now, too).

> Authenticating...
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxx to authenticate.

This has been working in previous versions of the AL Language Extension.

This is very annoying. 

This has been working in the version: v11.0.810452

**5. Versions:**

- AL Language: v11.0.827766

**Additional Notes:**

We're using docker developement environments with AAD Authentication.

**Comment by DanielGoehler** [comment]
+1

**Comment by pri-boka** [comment]
+1

**Comment by benjaminmillhouse** [comment]
+1

**Comment by rvanbekkum** [comment]
+1

**Comment by jonathanmartinebscomau** [comment]
+1

**Comment by kine** [comment]
We are using primaryTenantDomain property in launch.json. When removed, the AAD auth is working like before. Can someone confirm this?

**Comment by mjmatthiesen** [comment]
I previously created an issue related to this: #6124

**Comment by SBalslev** [comment]
@kine also onpremise or saas?

**Comment by kine** [comment]
@SBalslev the AadTenantId parameter on the tenant on the server is set to the guid.

**Comment by pri-kise** [comment]
@SBalslev 

Our launch.json looks like the following:
```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Docker Container for development",
            "request": "launch",
            "type": "al",
            "server": "", //Server URI 
            "serverInstance": "mydockerdev",
            "port": 443,
            "authentication": "AAD",
            "environmentType": "OnPrem",
            "primaryTenantDomain": "", //our Domain Name (not Guid). e.g. something like "xxxx.de"
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "tenant": "default"
        },
```

When I check the docker (`Get-BcContainerDebugInfo -containerName $myContainerName`) then the `AadTenant` contains the GUID of our tenant.

Can I provide any more details?

Addtional Notes:
We're using a script similiar to the following: 
https://tobiasfenster.io/using-aad-authentication-for-development-against-a-business-central-container
The only difference is that we use the Mircrosoft graph API for setting up the app registration (similiar to the one, that I added for the BcContainerHelper https://github.com/microsoft/navcontainerhelper/pull/2366)

**Comment by djurado-olivia** [comment]
Hello @SBalslev,

My entire team are also encountering this same issue since almost two weeks. 
Tested with versions:

- 11.0.827766
- 11.0.825804
- 11.0.810452
- 11.0.787898
- 11.0.779295

We're using VSCode but, it appeared at the same time as a VS 'Just-in-Time' debugger problem, I don't know if those two issues are related.

We're targeting SaaS OnCloud BC environments. Our launch look like this:

```
{
            "type": "al",
            "request": "launch",
            "name": "Developments",
            "tenant": "myTenant.es",
            "environmentType": "Sandbox",
            "environmentName": "myEnvironment",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "schemaUpdateMode": "Synchronize"
}
``` 

Let me know if I can provide any more information.

Thanks!

**Comment by SBalslev** [comment]
I'm having a challenging time reproducing this on v11.0.827766.

I use this cmd to create a docker instance - perhaps you can tell me if I'm doing it wrong? I'm not a docker super user just yet.
```
$artifactUrl = Get-BCArtifactUrl -country us -select Current -sasToken $sasToken 
new-bccontainer -accept_eula -artifactUrl $artifactUrl -licenseFile $bcLicenseFile -useSSL -container "MyBC3" -auth AAD -authenticationEMail $userEmail -AadTenant dev.mydemo.dk -appid 53e246ee-ca85-4210-944a-c1e88ef1a593 -AadAppId https://localdocker.dev.mydemo.dk -isolation hyperv
```
Trying to isolate the issue.

[√] Sign into the web client using AAD => AAD auth is configured correctly.
[√] Download symbols **with** device login => Dev connection works as expected.
[√] Publish **without** login => Auth cache seems to work fine, and I can see in the output window that it is authenticating with the same email as used to sign in with the device login.
[√] Close VS Code, reopen it and re-download symbols **without** login => Auth cache seems to work fine across sessions.

In the output window I see messages confirming I'm using the right identity and targeting the right tenant.
> Authenticated as user 'UserEmail' in tenant 'bf4ab6d6-cd93-424e-91fa-afe03fa286ac'. Please note that these credentials are cached. Clear the credentials cache to authenticate as another user.
> Targeting Dynamics 365 Business Central environment tenant 'default' and AD tenant 'bf4ab6d6-cd93-424e-91fa-afe03fa286ac'.
> Sending request to https://mybc3:7049/BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default

Looking at the two configs
@kine, see you're using port 443 - default the dev endpoint is on 7049. Sticks out but I assume that's how you configured it.
Leaving the primaryTenantDomain empty should fallback to "common" tenant - ei, the users home tenant. If you're a delegated admin try using the "primaryTenantDomain": "AAD Tenant ID Guid" to see if that helps.

@djurado-olivia, same as above - try using "tenant": "AAD Tenant ID Guid" and let me know if it changes anything. 

Our AAD token cache does not give us mapping functionality to tenant names, only tenant id so that might be part of the challenge, but I was expecting to fall back to the first token in the cache.

Accessing multiple tenants across different VSCode sessions would require you to specify a tenant (or primaryTenantDomain for onprem) or you would need to authenticate all the time (as the first token in the cache would have a high likelihood of being invalid when you switch between tenants).

**Comment by djurado-olivia** [comment]
Hi @SBalslev!

This worked for me,

Changed `"tenant": "myenviornmenturl.es"` to `"tenant": "myenvironmentGUID"`

Thanks for the quick response!

**Comment by pri-kise** [comment]
@SBalslev we are using a Docker Host System where we use Traefik to map the Endpoints. I think that might reason for the 443 port.


I checked our Docker Creation Script and there we use the TenantID (GUID) for the paramter `-AadTenant`.
Can this be a cause for the issue?
I will get in contact with my colleagues of the IT department.
That we can take a deeper look on our side.

**Comment by pri-kise** [comment]
Okay:
I've done the following:
I've changed the `primaryTenantDomain` from our tenant URI to the tenantID that we provided on the creation with the paramter `AadTenant`.
Now it seems to work again.
I still have to verify if this works for my colleagues, too.

And maybe you can provide some insight if this a good approach or if we need to update our script to use the TenantDomain instead of the TenantID for the parameter `-AadTenant`. (Still would have to verify that with this change everything would work fine).

**Comment by SBalslev** [comment]
@pri-kise the challenge is only in the VSCode launch.json as we use the AAD token cache, and we cannot currently match on domain name.
On the server (NST) there is no problem using the domain name.

So right now, it is "only" a developer challenge.

**Comment by pri-kise** [comment]
@SBalslev I guess, I can live with using the TenantID in the setting for the `primaryTenantDomain`.
But if this way is supported too, then at least the tooltip for this property should be updated, to document that the TenandID can be used there too for OnPrem.

![image](https://github.com/microsoft/AL/assets/56249171/958bf3ab-4116-43d7-a4e9-63ebb4f65f48)

Do you have any idea why this still used to work up to  version v11.0.810452 of the AL Language Extension?
Until  this version (Including this version) the domain name did work, too.

**Comment by SBalslev** [comment]
You're totally right, the tooltip is way off - we'll get that fixed.

Previous versions did not work well with multiple environments as it "simply" defaulted to the first token in the cache.
Refactoring to take tenant into account requires a matching on tenant id and this is what broke it.
So, before you would get the right auth tenant but didn't work across AAD environments.
After it works across AAD environments, but then the matching required you to use AAD Tenant id.

So, a little tricky to get right for all but with all the feedback here we might find time to take a second look and perhaps in the future introduce a second mapping cache of domain to AAD tenant id.

**Comment by benjaminmillhouse** [comment]
I can confirm that changing to the Tenant GUID in my launch.json resolved the issue for me

**Comment by SBalslev** [comment]
Added the tenant domain to tenant id map in the next version.

**Comment by pri-kise** [comment]
@SBalslev this sounds perfect. Thanks a lot for the fast answers and support on this specific issue. 
This will really help on productivity.

I will try the Insider Preview in upcoming weeks if this is already included there.


Maybe on small feedback for issues on the AL Language in General.

Maybe you can some tags to them if those get solved in BCXX, then we can easily see when an issue will be fixed or the minium of the AL Language Extension Version for this fix or improvement.

Maybe at least once a month it would be helpful to get some update on the issues, that have the Status "Accepted" or "Requires Triage". 
Then we would know how the progress of current issues is. I don't expect that every issue can fixed right away, but knowing if it is fixed in the upcoming major or maybe in 1 Year would be helpful. Or if you need more details to reproduce some issues. 

(I don't need a answer on my feedback. I only thought it would be a good place to give you and your team this feedback right now, since I'm very happy with communictation on this specific issue)
