### ISSUE TITLE
Missing compiler error on declaring TableNo in an upgrade codeunit

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/AL#7467]
**1. Describe the bug**
I am missing an error, or at least a compiler warning.

**2. To Reproduce**
Create or find a codeunit with `SubType = Upgrade;`,  and declare `TableNo = Item;`

**3. Expected behavior**
An error (or at least a warning) should be thrown on `TableNo = Item;`.
Background: if the codeunit contains a public procedure, and this procedure is called from outside later, this will result in a runtime error:

> You cannot run an upgrade codeunit on a record. Upgrade codeunit ... was called from C/AL with a record of table ... as a parameter.

(Btw, I've submitted the "C/AL" wording already on [Yammer](https://www.yammer.com/dynamicsnavdev/threads/2394105015984128).)

**4. Actual behavior**
No error or warning, just the runtime error later.

**5. Versions:**

- AL Language: 11.5
- Visual Studio Code:
- Business Central: 22.3

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.13240.0 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.13277.0 and VS Code Extension Version 13.0.886883. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
