### ISSUE TITLE
ALDoc: Issues with special chars in filenames (colons)

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/AL#7499]
**1. Describe the bug**
When creating documentation for the Tests-ERM app, there seems to be an issue with colons in the filename.

**2. To Reproduce**
Run ALDoc for Tests-ERM app:

```PowerShell
.\aldoc.exe build -o "C:\Temp\aldoc-new" -s .\aldoc.exe build -o "C:\Temp\aldoc-new" -s "C:\bcartifacts.cache\onprem\22.4.59114.59535\de\Applications\BaseApp\Test\Microsoft_Tests-ERM.app"
```

**3. Expected behavior**
Filenames must be cleaned.

**4. Actual behavior**

```
ERROR writing content yaml for 'Codeunit "No Accounting Periods: Basic"'. Message: The given path's format is not supported.
ERROR writing content yaml for 'Codeunit "No Acc. Periods: Posting"'. Message: The given path's format is not supported.
ERROR writing content yaml for 'Codeunit "Simple UI: Cust. Address Sync"'. Message: The given path's format is not supported.
ERROR writing content yaml for 'Codeunit "Simple UI: Vend. Address Sync"'. Message: The given path's format is not supported.
```

**5. Versions:**

- AL Language: ms-dynamics-smb.al-12.0.858079
- Visual Studio Code: ./.
- Business Central: App from 22.4.59114.59535
- List of Visual Studio Code extensions that you have installed: ./.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.12921.0 and VS Code Extension Version 13.0.878831. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
