### ISSUE TITLE
ALDoc: error ViolateSchema: [/enumValues] type: Value is "null" but should be "array"

### ISSUE THREAD

**Issue by fvet** [microsoft/AL#7503]
Please include the following with each issue:

**1. Describe the bug**
When generating the documentation with ALDoc, i'm faced with below error:

```
1 schema driven document processor plug-in(s) loaded.
C:\Projects\Dynavision\Docs\Output\reference\dynavision-core\Enum\ESCA-Feature-Type.yml: error ViolateSchema: [/enumValues] type: Value is "null" but should be "array"
C:\Projects\Dynavision\Docs\Output\reference\dynavision-core\Enum\ESCA-Message-Format.yml: error ViolateSchema: [/enumValues] type: Value is "null" but should be "array"
```

**2. To Reproduce**

The source files are both enums that have only one value, as the enum is mainly a libary enum that is extended by other apps only and has an empty default implementation.

```
enum 71096626 "ESCA Feature Type"
{
    Access = Public;
    Extensible = true;

    value(0; " ")
    {
        Caption = ' ', Locked = true;
    }
}

```

```
enum 71096606 "ESCA Message Format" implements "ESCA Message Format", "ESCA Message PreProcess", "ESCA Message API", "ESCA Message Request API"
{
    Access = Public;
    DefaultImplementation = "ESCA Message Format" = "ESCA Unknown Message", "ESCA Message PreProcess" = "ESCA Unknown Message", "ESCA Message API" = "ESCA Unknown Message", "ESCA Message Request API" = "ESCA Unknown Message";
    Extensible = true;
    UnknownValueImplementation = "ESCA Message Format" = "ESCA Unknown Message", "ESCA Message PreProcess" = "ESCA Unknown Message", "ESCA Message API" = "ESCA Unknown Message", "ESCA Message Request API" = "ESCA Unknown Message";

    value(0; " ")
    {
        Caption = ' ', Locked = true;
        Implementation = "ESCA Message Format" = "ESCA Unknown Message";
    }
}
```

**3. Expected behavior**
ALDoc should not fail on enum having only one (empty) value.

**5. Versions:**

- AL Language: 13.0.864697

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.12921.0 and VS Code Extension Version 13.0.878831. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
