### ISSUE TITLE
AL extension doesn't work on macOS

### ISSUE THREAD

**Issue by duyvtfit** [microsoft/AL#7506]
**1. Describe the bug**
The AL extension encountered some errors and functions stopped working completely.

**2. To Reproduce**
Open an AL project.

**3. Expected behavior**
All functions are available, such as publishing, debugging,...

**4. Actual behavior**
All functions are not working and .app files cannot be viewed.

**5. Versions:**

- AL Language: latest - v11.7.863928
- Visual Studio Code: latest - 1.82.2 (Universal)
- Business Central: W1 22.0 (Platform 22.0.55180.0 + Application 22.0.54157.55195)
- List of Visual Studio Code extensions that you have installed: only AL Language extension for Microsoft Dynamics 365 Business Central.
- OS: macOS Ventura 13.5.2, macOS Sonoma 14.0 (beta), darwin arm64 23.0.0, 
- Device: Macbook Air M1.

<img width="2040" alt="Screenshot 2023-09-17 at 14 16 38" src="https://github.com/microsoft/AL/assets/80388078/a3cfa92c-c8e4-4188-8f54-db5f2a031c3f">

**Comment by esbenk** [comment]
We are currently only shipping an x64 version for MacOS. Running x64 is supported on the M1/M2 using [Rosetta](https://support.apple.com/en-us/HT211861) 

The article describes how to set it up. It should automatically install when needed, but since we are invoking the AL language server from with the vsix extension the install dialog may be swallowed.

You should be able to force Rosetta to install running the AL language server from a terminal.

Open a terminal and navigate to `$HOME/.vscode/extensions/ms-dynamics-smb.al-13.0.0/bin/darwin/`. The version number will be different. Try to run `./Microsoft.Dynamics.Nav.EditorServices.Host` to trigger the installation of Rosetta.

**Comment by duyvtfit** [comment]
Hello @esbenk,

I want to express my gratitude for your assistance in resolving my issue. Your explanation clarified that the AL language extension currently supports only the x64 version on MacOS, and running it with Rosetta is the way to go on M1/M2 Macs. 

I followed your advice, and everything's running smoothly now. I really appreciate your quick response and guidance.

Your expertise is a lifesaver. Thanks again for your help!

**Comment by munkhbayarbr** [comment]
Hello @esbenk, 

I am facing exactly same issue as mentioned and tried to follow all the steps you suggested. 

But when I try to run "./Microsoft.Dynamics.Nav.EditorServices.Host". it says "Bad CPU type in executable". 

I wonder how can I fix it.
