### ISSUE TITLE
aldoc : IntegrationEvents that are flagged as Obsolete will cause unrelated events to also be flagged as obsolete in the resulting html

### ISSUE THREAD

**Issue by coffeecup007** [Microsoft/AL#7511]
**1. Describe the bug**
With ms-dynamics-smb.al-13.0.864697\bin\win32\aldoc it seems like if you have an "Obsolete" decorator in your codeunit, then aldoc will incorrectly flag subsequent events as obsolete.

**2. To Reproduce**
Create a codeunit.
Add an integration event and add the Obsolete decorator on it.
Add a second integration event, and do not add the Obsolete decorate on it.
Successfully compile the app.
Use aldoc 'build'
Use aldoc 'init'
Use docfx 'build'
View the results 

```
    [Obsolete('No longer used', 'Legacy')]
    [IntegrationEvent(false, false)]
    procedure OnNoLongerUsed()
    begin
    end;


    [IntegrationEvent(false, false)]
    procedure OnThisIsStillUsedAndHasNoObsoleteFlag()
    begin 
    end;
```

**3. Expected behavior**
In the example 'OnNoLongerUsed' should be flagged in the resulting documentation as obsolete, and OnThisIsStillUsedAndHasNoObsoleteFlag should not.

**4. Actual behavior**
Both OnNoLongerUsed and OnThisIsStillUsedAndHasNoObsoleteFlag have flags in the resulting HTML documentatin

**5. Versions:**

- AL Language: 13.0.864697
- Visual Studio Code: 1.82.1
- Business Central: 22.5
- List of Visual Studio Code extensions that you have installed: None.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.12921.0 and VS Code Extension Version 13.0.878831. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
