### ISSUE TITLE
Git on Preview Machine

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#752]
It would be cool if you could pre-install git with bash on the preview machine. ;)

**Comment by freddydk** [comment]
Pre-installing things requires LCA approval and I am not sure I want to go there.
What I can do however is to add a script, which the user can run in order to install Git.
October preview comes with a install-VS2017Community.ps1 script - right-click and say run with powershell - and then you will have Visual Studio 2017 Community.
What git client did would you prefer?

**Comment by tfenster** [comment]
I would like https://desktop.github.com/

**Comment by Gallimathias** [comment]
@freddydk When you can add Git to this script it would be very great.

I would like the GitBash or SourceTree. My first choice is always the GitBash.
