### ISSUE TITLE
Unexpected value 'BadExpression' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/AL#7525]
My project compiles successfully with compiler v13.0.13.12755

I can publish my app to a BC22 container but when I try to publish the same code to a BC23 container I get the following error.

The request for path /BC/dev/apps?tenant=default&SchemaUpdateMode=forcesync&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: One or more errors occurred. (Failure while emitting method. Object:'Codeunit CalcRuleFilterSetFilters105FDW' Method:'CalcIncludeFilters(var Record SourceBuffer105FDW)' (Unexpected value 'BadExpression' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'))
Failure while emitting method. Object:'Codeunit CalcRuleFilterSetFilters105FDW' Method:'CalcIncludeFilters(var Record SourceBuffer105FDW)' (Unexpected value 'BadExpression' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind')
Unexpected value 'BadExpression' of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundKind'

This is the signature of the method mentioned in the error:

internal procedure CalcIncludeFilters(var SourceBuffer: Record SourceBuffer105FDW) Filters: Dictionary of [Integer, Text]

**Comment by jimmymcp** [comment]
Update: it seems like it was to do with foreaching through the ordinals of an enum.

This compiles but does not publish in BC23 (but does publish in BC22)

```
var
    MyEnum: Enum "My Enum";
begin
    foreach MyEnum in Enum::"My Enum".Ordinals do
        ...
end;
```

using the variable does work i.e.

```
var
    MyEnum: Enum "My Enum";
begin
    foreach MyEnum in MyEnum.Ordinals do
        ...
end;
```

**Comment by BazookaMusic** [comment]
Looks like an issue with the binding logic and should be fixed asap

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.13320.0 and VS Code Extension Version 13.0.887907. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
