### ISSUE TITLE
Hide sensitive information on fieldgroups Brick, exampe customer or vendor

### ISSUE THREAD

**Issue by HendraSikmawan82** [microsoft/AL#7528]
Hi Mr/Mrs.

I just want to address some issue regarding Business Central SAAS. 
I think need to be able to disable/replace fieldgroups Brick in extensions.
Reason is because on most of our clients complains that some sensitive information on Brick should not seen on some user.
For exampe warehouse user can see Customer/Vendor Balance on brick. See attached pic.

Please provide a way to disable this Brick view on page. or remove those fields from Brick.

Thank You.

![AAA](https://github.com/microsoft/ALAppExtensions/assets/56532733/a68a7294-9d3b-4bba-a8be-bdf0b88b9561)

**Comment by BazookaMusic** [comment]
Unfortunately, this is not an issue with fieldgroups but a consequence of how the business central permission system works. This is because fieldgroups are not a security feature.

Access to data is limited via pernissions and permission sets. Furthermore, BC only supports row-level and table-level permissions and not column level. 

The fact that the user can see the vendor balance on the brick means that they have access to the vendor table. This access means that there are multiple ways to view this data, including other pages, viewing table data, reports etc. Even if access to these pages was blocked entirely. Microsoft may also add the vendor balance in other places in the future as part of new functionality.

Thus if one wants to limit access to specific data, they should  assign proper permissions to the user so that they cannot access the vendor table directly.
