### ISSUE TITLE
Turning on ServicesUseNTLMAuthentication on BC23, brakes running NavAdminTool scripts.

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/AL#7541]
Enabling ServicesUseNTLMAuthentication property on a newly installed, CRONUS based BC23 instance, makes NavAdminTool based scripts, like Export-NAVServerLicenseInformation, unusable. 

The following message comes:
Export-NAVServerLicenseInformation : There was no endpoint listening at http://localhost:7086/BC230/ManagementServicePs/Service.svc that could accept the message. This is often c
aused by an incorrect address or SOAP action. See InnerException, if present, for more details.

It is working with disabled ServicesUseNTLMAuthentication property and also working in all previous versions (including BC22) with enabled property.

Is it a bug or is it a limitation in BC23?

**Comment by ralf-escher** [comment]
I have the same issue. 
Only solution currently is to create a new service with NTLM Authentication enabled right from the beginning.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
