### ISSUE TITLE
Intellisense doesn't work when using global object enum for enum

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#7545]
Please include the following with each issue:

**1. Describe the bug**
When using intellisense on an enum with the global object prefix, it won't show any suggestions. This worked in previous versions.

**2. To Reproduce**
Steps to reproduce the behaviour:

1. Use the code below, move cursor to period, press ctrl+space after the period.

``` AL
    local procedure Example()
    begin
        Enum::"Sales Comment Document Type".
    end;
```

**3. Expected behaviour**
Show suggestions as it does when not using the object enum.
![image](https://github.com/microsoft/AL/assets/16603906/692dc8fe-8382-4bf0-b934-b209b1a74e3a)

**4. Actual behaviour**
No suggestions are shown.

![image](https://github.com/microsoft/AL/assets/16603906/ebb42c66-ed84-4222-b7ce-3a4d0c1fc8a4)

**5. Versions:**

- AL Language: v12.1.883011
- Visual Studio Code:Version: 1.83.1 (system setup)
- Business Central: irrelevant
- List of Visual Studio Code extensions that you have installed: All of them

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [X] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.15279.0 and VS Code Extension Version 13.0.924484. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
