### ISSUE TITLE
New PTE Rule: Table Extension fields should be in app id ranges (expand PTE0002)

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/AL#7547]
Please include the following with each issue:

**1. Describe the bug**
Create a new app. Make your range 71100-71200. Create a table extension. Add a field. Make the id anything within the 50k-99k range.

**2. To Reproduce**

``` AL
tableextension 71100 "Sales Header Ext." extends "Sales Header"
{
    fields
    {
        field(51100; "New Field"; Code[50]) { }
    }
}
```

**3. Expected behavior**
This should produce a warning as you are outside of the specific apps range. This is bad practise.

**4. Actual behavior**
No warning, builds fine, no feedback to dev that they have messed up.

**5. Versions:**

- AL Language: v12.1.883011
- Visual Studio Code:Version: 1.83.1 (system setup)
- Business Central: irrelevant
- List of Visual Studio Code extensions that you have installed: All of them

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by EmilDamsbo** [comment]
Agreed, this should behave in line with [AppSource Cop rule AS0013](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0013). However, it would also be a breaking change for existing AL code to make it an error. I think a new rule is required which by default is a warning.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 15401 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
