### ISSUE TITLE
Code 'BO' is not a valid ISO 3166-1 alpha-2 code

### ISSUE THREAD

**Issue by SantiagoMasramon** [microsoft/AL#7576]
**1. Describe the bug**
Building an app for AppSource, in the AppSourceCop.json, we specify:
`"supportedCountries": ["AR", "CL", "BO", "CO", "CR", "EC", "GT", "NI", "PA", "PY", "PE", "DO", "UY"]"`

I understand that this country should be supported
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations

**2. To Reproduce**
1. add `"supportedCountries": ["BO"]` in AppSourceCop.json.
2. Compile the app.

**3. Expected behavior**
Warning should not appear.
the same problem has been solved for other countries, like #7299 and #6888 

**4. Actual behavior**
When compiling our extension for AppSource, we receive the following warning:
`warning AS0056: The code 'BO' is not a valid ISO 3166-1 alpha-2 code for a country/region supported by the product.`

**5. Versions:**

- AL Language: v13.0.887907
- Visual Studio Code: 1.84.1
- Business Central: 23.0

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 24.0.13973.0 and VS Code Extension Version 13.0.900196. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
