### ISSUE TITLE
Increasing field showing as AL0432

### ISSUE THREAD

**Issue by KrunoslavPipic** [microsoft/AL#7594]
**1. Describe the bug**
Why is field increasing treated as AL4032 rule? When the field retains the same ID, only the field is increased.

**2. To Reproduce**

Execute the code that triggers Rule AS0086.
e.g. add field(35; "Home Page"; Text[80]) from table 79 "Company Information" to some report
e.g. add ffield(106; "Package Tracking No."; Text[30]) from table table 36 "Sales Header" to some report

**3. Expected behavior**
There should be another rule to inform of increasing field. For example AS0086

**4. Actual behavior**
The rule is incorrectly showing the warning as AL0432.

**5. Versions:**
latest insider build:
https://bcinsider.azureedge.net/sandbox/24.0.14083.0/w1](https://bcinsider.azureedge.net/sandbox/24.0.14083.0/w1
AL language: v13.0
Base app version: 24.0.14088.0

![image](https://github.com/microsoft/AL/assets/150338832/0e2c571a-d1fb-429b-8812-4a972c036321)
![image](https://github.com/microsoft/AL/assets/150338832/6dfd1bb9-adfb-40b4-a4c2-632234373a95)
![image](https://github.com/microsoft/AL/assets/150338832/82c63cdd-38f1-4e22-abcf-c3e50a369529)
![image](https://github.com/microsoft/AL/assets/150338832/5afae81b-c0d5-4138-a1f5-36b6dd4ab4be)

We can add in ruleset file to ignore AL4032 warning, but then we will not have information of real obsolete fields.

**Comment by dannoe** [comment]
It is marked this way so that the developer knows they need to increment the field BEFORE the change is released in BC24.
Example:

```al
   local procedure DoSomething();
    var
        CompanyInformation: Record "Company Information";
        MyHomepage: Text[80];
    begin
        CompanyInformation.Get();
        MyHomePage := CompanyInformation."Home Page"; // this code will create runtime errors in BC24 and a warning in BC24
        ...
    end;
```

If you want to get rid of the warning and not get errors in BC24: increase the field length of the variables now and add a pragma to the line.
Remember to remove the pragma with BC24 so that you will be notified of future increases. 
If you instead assign values to this table field in ``Company Information``, you must use ``CopyStr`` with ``MaxStrLen``. This will "automatically" increase the assignable length with BC24 (AFAIK this doesn't work for runtime packages).

**Comment by qutreson** [comment]
@KrunoslavPipic - As mentioned in the comment above, obsolete properties are currently used to give a notice on future breaking changes so that you can update your code accordingly. We do not have a mechanism for giving you such notices without obsolete properties, but this could be a new feature to propose on aka.ms/BCIdeas.

**Comment by KrunoslavPipic** [comment]
Implemented a temporary workaround:
![image](https://github.com/microsoft/AL/assets/150338832/81d72f9f-8342-41b1-8a9d-598ae949cc79)

to capture information about obsolete/increasing fields while allowing the compilation in pipeline to pass.

INFO can be easily ignored during coding, and with each new version, we'll review the rules:
![image](https://github.com/microsoft/AL/assets/150338832/01de100a-9fce-4378-bed1-511b0bbc2619)

**Comment by KrunoslavPipic** [comment]
I agree, but having a bunch of pragma lines and adding/removing them with each new version is not the happiest solution.

We are not ignoring the rule; we're just showing it as info :) and with each new version, the info needs to be reviewed.
![image](https://github.com/microsoft/AL/assets/150338832/d49fd688-ef55-446a-9b51-64a712c2b817)

Also, the AL-pipeline will fail with insider artifacts (current version 24.0.) if the field removal has indeed become obsolete, and we have enough time to rewrite the logic

**Comment by dannoe** [comment]
> ... but this could be a new feature to propose on aka.ms/BCIdeas.

Here is the idea
https://experience.dynamics.com/ideas/idea/?ideaid=56aea189-0ab5-ee11-92bd-000d3a0f8799
