### ISSUE TITLE
Region folding does not work when pragma is inside region and indentations are different

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/AL#7602]
When the region is defined and there is a pragma inside it and indentations of them are different, then it is not possible to fold the region or neither pragma itself. There are no folding icons or they are misplaced:

![image](https://github.com/microsoft/AL/assets/40537575/37207f58-5a8a-4d8d-98d7-5eed71efb20c)

If I match the indentations, the region folding works:

![image](https://github.com/microsoft/AL/assets/40537575/ee812c5f-1335-4e5b-8575-aff1f7461a78)
![image](https://github.com/microsoft/AL/assets/40537575/8e6e130e-f589-4d1a-a2b8-45294e431e12)

But it is unable to fix it this way because "Format Document" command (manual or automatic during the save) updates indentations to initial state.

The behaviour is the same inside a code or inside an area like `fields` in `table` object...

**Versions:**

- AL Language: v13.0.903630 (also the same issue in v12.)
- Visual Studio Code: 1.84.2

**Comment by thpeder** [comment]
Thanks for raising awareness of this issue.
We will not have a solution for this in the near future, but in the next pre-release of the extension, you will be able to have Visual Studio Code to provide folding bases on their generic strategies, instead of getting them from the AL Language Extension.
