### ISSUE TITLE
Azure DevOps Syntax Highlithing - Wrong Highliting of KeyWords like Separator in procedures parameters

### ISSUE THREAD

**Issue by pri-kise** [Microsoft/AL#7617]
**1. Describe the bug**
Create a procedure with ParameterName with Name `Separator` and view this file in Azure Devops

**2. To Reproduce**

``` AL
procedure CreateString(Separator: Text)  //Wrong Hightlithing in Azure DevOps
begin
end;
```

**3. Expected behavior**
KeyWords in parameter Names should be ignored similiar to VS-Code:
![image](https://github.com/microsoft/AL/assets/56249171/0e8789a8-178e-4712-a838-9156a0b8298d)

**4. Versions:**
- AL Language Syntax Highlights for Microsoft Dynamics 365 Business Central: 12.1.886884 (Latest)

**Comment by mjmatthiesen** [comment]
What are you using for highlighting within Azure DevOps?

**Comment by dannoe** [comment]
> What are you using for highlighting within Azure DevOps?

Probably https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.allanghighlights

**Comment by EmilDamsbo** [comment]
Hello, this difference is due to the presence of *semantic* highlighting in the Visual Studio Code extension. To illustrate:
![image](https://github.com/microsoft/AL/assets/67266681/229e3162-88da-4a16-898b-14cefaf82645)
![image](https://github.com/microsoft/AL/assets/67266681/5ab6250c-f84f-4199-b2c7-6e3bedbb14d7)

We strive to make the Azure DevOps extension have parity with VS Code extension syntax highlighting, Unfortunately Azure DevOps doesn't support semantic highlighting, this the gap you are experiencing. Hope this helped. 

Thank you for reporting the issue, but as we cannot solve it so I am closing as not planned. Have a nice day!
