### ISSUE TITLE
No AppSourceCop rule for breaking changes in report dataset

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7619]
**1. Describe the bug**
Report extensions allow other apps to add columns to existing report data items, or to add new data items. 
Even though we can obsolete data items and columns, there is no AppSourceCop rule preventing us from just deleting data items or columns without further `ObsoleteState = Pending`. This breaks dependent apps.

**2. To Reproduce**
While the AppSourceCop is activated and set up for comparing with the previous version, delete a report data item or column inside the dataset.

**3. Expected behavior**
An AppSourceCop rule should throw an error.

**4. Actual behavior**
No error, no warning.

**5. Versions:**

- AL Language: 12.3.900902

**Comment by NKarolak** [comment]
@qutreson This might be for you.

**Comment by qutreson** [comment]
@NKarolak - Thanks for reporting it. This is something we have in our long term backlog for AppSourceCop, but that isn't being prioritized at the moment. Since this is more of a feature request than a bug, I would recommend logging the idea on aka.ms/BCIdeas so that it can gather votes and help us prioritize it accordingly as we are monitoring top ideas and considering them for the next waves. I checked briefly and it seems that we have a similar idea posted for [query objects](https://experience.dynamics.com/ideas/idea/?ideaid=6293833c-1847-ee11-a81c-6045bdb4a556), but I couldn't find one for reports.

**Comment by NKarolak** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=317c1baa-209b-ee11-a81c-0022484dd027
