### ISSUE TITLE
No Warning for area creation on document pages

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7651]
Please include the following with each issue:

**1. Describe the bug**
Currently I'm able to create actions and add them to the area creation on document pages.
The problem is that the actions aren't shown in the UI.

**2. To Reproduce**

1. Create a Page or Page Extension for a Page with PageType Document
2. Add actions to the area creation
3. Publish the App
4. Verify that no actions are shown.

You can use this repository as show case: https://github.com/pri-kise/msdyn365bc-area-creation-test

**3. Expected behavior**
I would expect that the area creation is working on pages with PageType Document, too.
Or at least if this is intended then give us a warning in VS Code.

**4. Actual behavior**
Currently the actions aren't shown and there is no warning that this area isn't supported on pages of PageType Document.

**5. Versions:**
- AL Language: v13.0.921843
- Visual Studio Code: Version: 1.85.2 (user setup)
- Business Central: 23.3
- List of Visual Studio Code extensions that you have installed:

** Additional Notes**
Yammer Post: https://www.yammer.com/dynamicsnavdev/threads/2626019772710912
There is no documentation for the usage of this area on document pages: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-actions-overview -> Could be improved, too.

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.18082.0 and VS Code Extension Version <None>. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
