### ISSUE TITLE
Output path linking is broken if Learn Authoring Pack is installed.

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7667]
**1. Describe the bug**
When AL compiler warnings appear in the OUTPUT tab of VS Code, then they are not linked anymore.

**2. To Reproduce**
1. Change AL code to provoke any kind of "OUTPUT", and run `AL: Package`: At least one file will be listed, and the path to the file is linked.
2. Install the Microsoft [Learn Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) extension for VS Code. The pack includes multiple other extensions, whereas the [learn-validation](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-build) extension will cause the issue.

**3. Expected behavior**
The file paths should still be linked.

**4. Actual behavior**
File paths are not linked.

**5. Versions:**

- AL Language: 12.6
- Visual Studio Code: 1.86.1
- Learn Authoring Pack: 1.0.1
- learn-validation: 0.4.2

**Comment by thloke** [comment]
This looks like `learn-validation` is adding markdown to output which is breaking the automatic linking of filepaths. We're not doing anything special to link the filepath from the output. I'm going to transfer this over to their repo to see if there's anything they can do about it (but I'm not too hopeful since the repo hasn't been active in two years).

**Comment by thloke** [comment]
Ah, I can't transfer this issue there. You could try re-raising it with them: https://github.com/docascode/vscode-docs-build

Sorry that we can't do much more on our end. If it's really blocking, I could try pinging internally but I expect the turnaround time for that to also be slow.
