### ISSUE TITLE
Query Object - SqlJoinType is not respected when a DataItemTableFilter is added to the data item.

### ISSUE THREAD

**Issue by avaanr** [microsoft/AL#7694]
**1. Describe the bug**
SqlJoinType is not respected when a DataItemTableFilter is added to the data item.

**2. To Reproduce**

``` AL
query 77000 MyQuery
{
    QueryType = Normal;

    elements
    {
        dataitem(customer; Customer)
        {
            column(systemId; SystemId)
            {
                Caption = 'Id', Locked = true;
            }
            column(customerNumber; "No.")
            {
                Caption = 'Customer No.', Locked = true;
            }
            dataitem(custLedgEntry; "Cust. Ledger Entry")
            {
                DataItemLink = "Customer No." = Customer."No.";
                DataItemTableFilter = "Document Type" = filter(Invoice | "Credit Memo");
                SqlJoinType = LeftOuterJoin;

                column(totalSalesAmount; "Sales (LCY)")
                {
                    Caption = 'TotalSalesAmount', Locked = true;
                    Method = Sum;
                }
                filter(dateFilter; "Posting Date")
                {
                    Caption = 'DateFilter', Locked = true;
                }
            }
        }
    }

}
```

**3. Expected behavior**
Displays a list of all customers, even those with zero sales.

**4. Actual behavior**
Display a list of customers who have made sales. This behavior only occurs when the DataItemTableFilter property is set. The expected behavior occurs if the mentioned property is not added.

**5. Versions:**

- AL Language: v13.0.964488
- Visual Studio Code: 1.87.2
- Business Central: US Business Central 23.4 (Platform 23.0.16370.0 + Application 23.4.15643.16407
- List of Visual Studio Code extensions that you have installed:

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by BazookaMusic** [comment]
Could be a runtime bug or a generated code issue

**Comment by thloke** [comment]
Checked, this is a runtime issue so the bug cannot be handled through github and should go through CSS.

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
