### ISSUE TITLE
Command „AL: Publish with Debugging“ does not open browser when incognito Edge is explicitly specified in settings.json

### ISSUE THREAD

**Issue by zabcik** [microsoft/AL#7697]
**1. Describe the bug**
Command „AL: Publish with Debugging“ does not open browser when **incognito Edge** is explicitly specified in "settings.json".
This error is repeatable for my and my colleagues.

**2. To Reproduce**

1. Configure **Edge (incognito)** in settings.json.

```json
{
    "al.browser": "Edge",
    "al.incognito": true
}
```

3. Run command „AL: Publish with Debugging“.

5. Wait for error – see screen capture bellow.

Original (cs-CZ): „Systém windows nemůže najít položku "shell:AppsFolder\Microsoft.MicrosoftEdge…". Ujištěte se, zda je název zadán správně, a akci zopakujte.“

Translated by Translator (en-US): „Windows cannot find the entry "shell:AppsFolder\Microsoft.MicrosoftEdge…". Make sure the name is entered correctly and try again.”

![image](https://github.com/microsoft/AL/assets/19779185/9dcc2b15-4ebd-4893-b482-818384d7ddfd)

**5. Versions:**

AL Language Version: 13.0.971907
VS Code Version:  1.87.2
Edge Version: 122.0.2365.92
Windows Version: Windows 10 22H2 (Czech)

**Comment by thloke** [comment]
Looks like we forgot to update some things back when we switched to chromium edge. Can you try `"al.browser": "EdgeBeta"` instead? That should work.

**Comment by zabcik** [comment]
Hello,

I confirm that ```"al.browser": "EdgeBeta"``` works with Incognito.
Thank you.

There is result of my tests with current AL Language Version: 13.0.971907:

| Browser  | Incognito | Status  |
|----------|-----------|---------|
| Edge     | false     | Success |
| Edge     | true      | Fail    |
| EdgeBeta | false     | Success |
| EdgeBeta | true      | Success |
| Chrome   | false     | Success |
| Chrome   | true      | Success |
| Firefox  | false     | Success |
| Firefox  | true      | Success |

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.18370.0 and VS Code Extension Version 14.0.985779. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
