### ISSUE TITLE
Sorting on Flowfields return nothing to show 

### ISSUE THREAD

**Issue by RajasekharRS** [microsoft/AL#7707]
Version: W1 21.0 (Platform 21.0.46384.46844 + Application 21.0.46256.46853)

Issue: Attempting to sort on a Flowfield, but the view is empty, displaying the message "There is nothing to show in this view."

<img width="921" alt="image" src="https://github.com/microsoft/AL/assets/149217098/db903906-94aa-4092-b881-61ad06be8a0f">

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
