### ISSUE TITLE
The SSL connection could not be established (RevocationStatusUnknown or altered verification) when download symbols from HTTPS source

### ISSUE THREAD

**Issue by Yaowenjie** [microsoft/AL#7719]
I always got the following errors when I try to download symbols  from our https server under windows 11 enterprise OS, and `this https server link is directly accessible from browser`:

error 1:
```
Error: The SSL connection could not be established, see inner exception.
Authentication failed, see inner exception.
The message or signature supplied for verification has been altered
```

error2:
```
Error: The SSL connection could not be established, see inner exception.
The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
```

The error is sometimes like error1, sometimes like error2. I checked the license for this https server link is under TLS1.2, and I also changed the regedit value to disable protocol SSL 3.0, TLS 1.0 and TLS 1.1, and only keep TLS 1.2 enabled. But it's still not working, I also checked the issue #7618 and #3274, which might be related to this issue, but there is no clue with my scenario, still no option to turn CRL validation off, and I am not able to change any config in the BC server side.

Could anyone can help me with it? Appreciate a lot in advance!

Versions:
- AL Extension: 12.0.875970
- VS Code: 1.88.1
- OS: win 11 enterprise 22H2

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
