### ISSUE TITLE
Custom Filter Token do not work for GUID Fields

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/AL#7728]
Please include the following with each issue:

**1. Describe the bug**
Custom Filter Token do not work for GUID Fields

**2. To Reproduce**

1. Implement an Custom Filter for a GUID Field.
``` AL
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Filter Tokens", 'OnResolveTextFilterToken', '', true, true)]
    local procedure OnResolveTextFilterToken2(TextToken: Text; var TextFilter: Text; var Handled: Boolean)
    begin
        if StrLen(TextToken) < 5 then
            exit;
        if StrPos(UpperCase('MYFILTER'), UpperCase(TextToken)) = 0 then
            exit;
        Handled := true;
        TextFilter := '{00000000-0000-0000-0000-000000000001}'
    end;
```
2. Test the custom filter token on the modified by field on customer card.
![image](https://github.com/microsoft/AL/assets/18051656/97f3a13d-7a99-4944-8036-f2e3c01e38a3)

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
I Expect the custom filter tokens to work for guid fields like any other data type

**4. Actual behavior**
An Error Message is shown:
![image](https://github.com/microsoft/AL/assets/18051656/f5789e91-5957-49ba-83b0-7b3bc601f7ae)
The filter "%MYFILTER" is not valid for the Modified By field on the Customer table. The variable "%MYFILTER" was not understood.

**5. Versions:**

- AL Language: v13.0.971907
- Visual Studio Code: 1.88.1
- Business Central: 24.0 
- List of Visual Studio Code extensions that you have installed: none

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
