### ISSUE TITLE
Your license does not grant you the following permissions

### ISSUE THREAD

**Issue by syedAGT** [microsoft/AL#7733]
**1. Describe the bug**
I am the Super User and i have all the permissions.

error : 
Reason: Your license does not grant you the following permissions on TableData 2000000206 Published Application: IndirectRead for company CRONUS USA, Inc..

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '46951'.
[2024-04-29 11:57:21.19] The request for path /v2.0/Sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=23.0.0.0&appId=00000000-0000-0000-0000-000000000000&tenant=xyz failed with code Forbidden. Reason: Your license does not grant you the following permissions on TableData 2000000206 Published Application: IndirectRead for company CRONUS USA, Inc..

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '46952'.
[2024-04-29 11:57:21.19] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**2. To Reproduce**
While Downloading the Symbols

**3. Versions:**

- BC - Application: "23.0.0.0",
- runtime: "12.0",

**Comment by syedAGT** [comment]
> Do you have the permission for all Companies (Company Name empty on permissions)?

Yes, I have the permission for all companies.

**Comment by BazookaMusic** [comment]
This message could also be due to the user not having a valid license to publish applications. Make sure a valid license is assigned.

However, this issue is also out of scope for this repository. Please do the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
