### ISSUE TITLE
Error while trying to  "Undo Receipt" a "Posted Purchase Receipt" that is bind with a cancelled "Posted Purchased Invoice"

### ISSUE THREAD

**Issue by filipposlekkas** [microsoft/AL#7736]
Hello.
I have create a Purchase Order with 1 item with quantity 1 and posted this with choice Receipt. After I create and post a Purchase invoice for this receipt and finally cancel this posted purchase invoice. When I'm trying to "Undo Receipt" from the lines of the "Posted Purchase Receipt" getting this error 
"You cannot post these lines because you have not entered a quantity on one or more of the lines.".
![error](https://github.com/microsoft/AL/assets/78608153/55b0e51b-a0dd-4a80-b4a1-e6b81e56acba)

I also notice that after canceling this particular "Posted Purchase Invoice" the fields value of "Qty. Rcd. Not Invoiced", "Quantity Invoiced" and "Qty. Invoiced (Base)" in the "Posted Purchase Receipt" is not affected/updated. ​

**Versions:**
- AL Language
  Description: Development tools for Dynamics 365 Business Central
  Version: 13.0.971907

- Business Central:
   Version: W1 24.0 (Platform 24.0.18959.0 + Application 24.0.16410.17628)

**Comment by BazookaMusic** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

Open a support request to CSS through the PartnerSource portal
Open a bug in Collaborate
Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL. This issue is on the application.
