### ISSUE TITLE
Misleading ToolTip on RunTime in App.Json

### ISSUE THREAD

**Issue by tinestaric** [microsoft/AL#7746]
**1. Describe the bug**
The Tooltip on the "runtime" property in app.json is wrong and misleading. 

The tooltip states:
The version of the runtime that the project is targeting. The project can be published to the server with an earlier or the same runtime version.
13.0: Business Central 2024 release wave 1

Which implies that I can publish this extension on a server running a runtime 12. It reads as if the requirement is <=13, when it's actually >=13.

![image](https://github.com/microsoft/AL/assets/42935028/2b972cc3-dfa0-4f3f-b6ef-2911069caeab)

**3. Expected behavior**
A clearer message indicating that server runtime must be higher, or that the project must be earlier or same as the server runtime

**5. Versions:**

- AL Language: 13.0.1007491

Internal work item: [AB#548302](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548302)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26.0.25537.0 and VS Code Extension Version 15.0.1179579. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
