### ISSUE TITLE
[AL Language Syntax Highlights Devops] Missing Keyword Highltighing for protected modifier on procedures

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL#7747]
Please include the following with each issue:

**1. Describe the bug**
The protected modifier on procedures isn't highlighted as keywor in azure devops.

**2. To Reproduce**
- Create a procedure with the access modifier `protected`.

``` AL
    protected procedure IsReportInPreviewMode(): Boolean
    var
        MailManagement: Codeunit "Mail Management";
    begin
        exit(CurrReport.Preview() or MailManagement.IsHandlingGetEmailBody());
    end;
```
**3. Expected behavior**
Keyword protected should be highlighted as keyword.

**4. Actual behavior**
Currently `protected` keyword is ignored.
![image](https://github.com/microsoft/AL/assets/56249171/ac972a57-ba74-424d-ad3a-c4f731a61c96)

**5. Versions:**

- AL Language Syntax Highlights for Microsoft Dynamics 365 Business Central: 12.7.944946 (Latest)
Internal work item: [AB#536607](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536607)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.21785.0 and VS Code Extension Version 14.0.1075828. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
