### ISSUE TITLE
ToolTips added to a TableExtension field are not displayed if they have Locked = true (runtime 13.0)

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/AL#7752]
**1. Describe the bug**
In a new extension configured with **runtime 13.0**, ToolTips can be added at the Table/TableExt Field level instead of at the Page/PageExt level.

However, after installing the extension on a **BC v24.0**, the ToolTip is not displayed in the web client if the **Locked** property is set to **true**

**2. To Reproduce**
Add a ToolTip at the Table/TableExt Field level with Locked = true and publish

``` AL
// extension with runtime = 13.0
tableextension 50000 "Customer EXT" extends Customer
{
    fields
    {
        field(50000; "Contact 2 EXT"; Text[30])
        {
            Caption = 'Contacto 2', Locked = true;  // This works
            DataClassification = CustomerContent;
            ToolTip = 'Especifica el valor del campo Contacto 2.', Locked = true;  // This doesn't work
        }
    }
}

pageextension 50000 "CustomerList EXT" extends "Customer List"
{
    layout
    {
        addafter("No.")
        {
            field("Contact 2 EXT"; Rec."Contact 2 EXT")
            {
                ApplicationArea = All;
            }
        }
    }
}
```

**3. Expected behavior**
The ToolTip is expected to be displayed in the web client even when it has Locked = true

**4. Actual behavior**
No ToolTip is showed

**5. Versions:**

- AL Language: 13.1
- Visual Studio Code:
Versión: 1.89.1 (user setup)
Confirmar: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Fecha: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
SO: Windows_NT x64 10.0.22631
- Business Central: ES Business Central 24.0 (Plataforma 24.0.19566.0 + Aplicación 24.0.16410.17628)
- List of Visual Studio Code extensions that you have installed: None

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. It's out of scope because it's to do with the runtime and client behaviour of the extension, rather than the AL language itself. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.

**Comment by JavierFuentes** [comment]
Hi @thloke ,
in that case the compiler or VSCode should at least raise a warning until the web client development team fixes it.
