### ISSUE TITLE
IN operator not working in OdataV4 BC SaaS

### ISSUE THREAD

**Issue by mishof** [microsoft/AL#7761]
According to these instructions:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris

We are able to filter our published OdataV4 queries with the IN operator. f.i.:
$filter=GDM1_FilterOnly eq 'ADM' and DATE_FilterOnly ge 2021-01-01 and DATE_FilterOnly le 2022-05-31 and GLACC_FilterOnly in ('7200','7250','7251','7300','7400','7401','7600','7711','7712','7730')

but the part
"in ('7200','7250','7251','7300','7400','7401','7600','7711','7712','7730')"
is not working in all of our BC SaaS versions.
There is no error, but BC just ignores the IN operator and it's array of values.

General availability was announced for Apr 2, 2024:
https://learn.microsoft.com/en-us/dynamics365/release-plan/2024wave1/smb/dynamics365-business-central/use-odata-v4-operator-web-service-queries

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
