### ISSUE TITLE
Intellisense in Query- Objects

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/AL#7764]
**1. Describe the bug**
Intellisense does not show the trigger "OnBeforeOpen"

**2. To Reproduce**
1. Create a new query
2. Try to add the onbeforeopen trigger with intellisense.

**3. Expected behavior**
The trigger should be shown.

**4. Actual behavior**
Intellisense does not show the trigger name.

**5. Versions:**
- AL Language: Version 13.1
- Visual Studio Code: 1.90.0
- Business Central: 24.1
- List of Visual Studio Code extensions that you have installed:

**Comment by stephanweidmann** [comment]
Please also have a look at intellisense and query objects when setting filters.
The columns are not suggested after SetRange/Setfilter
![image](https://github.com/microsoft/AL/assets/36635930/8af3470d-1146-4a49-b476-3ceade2bc86f)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.21334.0 and VS Code Extension Version 14.0.1063057. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
