### ISSUE TITLE
Rule AA0234 implemented inconsistently?

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7787]
Please include the following with each issue:

**1. Describe the bug**
Rule AA0234 is not activated the way we know it from other rules, inconsistently. Bug or feature for all new rules to come?

**2. To Reproduce**
By default, rule AA0234 is set to action Warning, as we can see in the [docs](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0234?WT.mc_id=MVP_382921), and in the AZ AL DevTools Code Analyzers view:
![image](https://github.com/microsoft/AL/assets/34504100/b4f7f211-825d-4fdb-9347-9568ac950a2d)

This _usually_ means, that this rule is active. But it isn't. Steps to reproduce the behavior:

1. In your app without any tooltips on table label fields, update your app.json to runtime 13.0. No warning AA0234.
2. Add the rule to your project ruleset file. Only after that, warnings AA0234 appear as expected.

I know that this is by design as per [docs](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-tooltips?WT.mc_id=MVP_382921#adding-tooltips-to-table-fields-2024-release-wave-1-or-later):
![image](https://github.com/microsoft/AL/assets/34504100/c2936525-c527-472b-9532-b4c6c35a3d69)
But when you instruct to "enable the rule", I'd assume to find it first in disabled state - not in state "Warning", but for some weird reasons not working :-/

**3. Expected behavior**
The rule should be simply action = Hidden by default.

**4. Actual behavior**
The rule is Warning by default, but is in fact not active until we add it to a ruleset. I don't understand why it was solved that way.

**5. Versions:**
- AL Language: 13.1.1065068 / runtime 13.0
- AZ AL Dev Tools/AL Code Outline 13.67.0
Internal work item: [AB#540883](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540883)

**Comment by thpeder** [comment]
Hi @NKarolak,

Thanks for the issue. 
We will make sure it is aligned with the other rules

**Comment by NKarolak** [comment]
@thpeder Any news on this?

**Comment by krupybalu** [comment]
Hi @NKarolak,

We have aligned the rule with the other similar ones (that is DefaultSeverity=Info and IsEnabledByDefault=false).

Please note that we distinguish between a rule being disabled or having its default severity set to Hidden. This distinction can be influenced by several factors, such as performance considerations (since Hidden diagnostics are computed while disabled ones are not) or the diagnostic serving as an entry point for a code action (as Hidden diagnostics still show up on hover).

Please open a new case for the AA0234 problem and any further issues that you encounter. Thank you!

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26.0.23829.0 and VS Code Extension Version 15.0.1128421. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by NKarolak** [comment]
> I've just found out that AA0234 also fires on missing table field tooltips even if a _table object or table field_ are
> 
> * `ObsoleteState = Removed`
> * `Access = Internal`
> * `AllowInCustomizations = Never`
> 
> Could you please fix that as well?

@krupybalu Did you also fix the false positives mentioned above? And will your fix be downgraded to AL Language 14.x?

**Comment by krupybalu** [comment]
> I've just found out that AA0234 also fires on missing table field tooltips even if a _table object or table field_ are
> 
> * `ObsoleteState = Removed`
> * `Access = Internal`
> * `AllowInCustomizations = Never`
> 
> Could you please fix that as well?

@NKarolak For better trackability, could you please open a new case for the above issue? Thank you in advance!
