### ISSUE TITLE
Error AS0036 rised when modifing a tooltip at table level

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/AL#7788]
**1. Describe the bug**
When modifing a tooltip on table level that as been already published on AppSource an error AS0036 is rised.
I think that tooltips should be editable like the caption.

**2. To Reproduce**
Create an extension with tooltips on table level.
Use the AppSourceCop.json properties to check breaking changes.
Modify a tooltips in a table.

**3. Expected behavior**
Tooltips edition should not be a breaking change, as the caption edition is.

**4. Versions:**

- AL Language: v13.1.1065068
- Visual Studio Code: 1.91.0
- Business Central: 24.2
- List of Visual Studio Code extensions that you have installed:

Internal work item: [AB#548401](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548401)

**Comment by BazookaMusic** [comment]
Agree that they should be editable, marking for triage

**Comment by stephanweidmann** [comment]
Any update on this?

**Comment by Tsmprintvis** [comment]
any update on this?, 
we also just encountered this error

**Comment by devgar** [comment]
Same here, we tried marking table fields as obsolete in a previous publish to pass validation but it didn´t work.

**Comment by thpeder** [comment]
I'll make a fix that is included in an upcoming release.

**Comment by Avanti05** [comment]
Any ETA on the fix?

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 26.0.24150.0 and VS Code Extension Version 15.0.1136405. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/

**Comment by NKarolak** [comment]
@JesperSchulz Thanks. What about the downgrade into AL Language 14.x?

**Comment by stephanweidmann** [comment]
build number 26.0.24150.0? so half a year until it is available?

**Comment by Avanti05** [comment]
@JesperSchulz will there be a temporary solution for app source applications? We already changed  some tooltips to tables, and it is not a viable solution not being able to update them until April next year. 
Will we have to move them back to pages or will the AS0036 validation rule be disabled until BC 26 is released?

**Comment by BazookaMusic** [comment]
The backport was stuck due to process reasons, this will go to 25 and app source will get it
