### ISSUE TITLE
Spelling mistake: "ErrorBehavior::Collect" tooltip

### ISSUE THREAD

**Issue by Christoph-wq** [microsoft/AL#7798]
**1. Describe the bug**
Hovering over the selection "Collect" as an scope-value from "ErrorBehavior" will show this tooltip:

> Collectible errors will be gathered and code execution will be continued until the end of the ErrorBehvior scope. If errors are left unhandled at the **_nd_** of the ErrorBehavior scope, execution will stop with an aggregated error.

**2. To Reproduce**

1. Go to anywhere you can code in al

``` AL
namespace ChristophHeer.ALProject518;

using Microsoft.Sales.Customer;

pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage()
    begin
        ErrorBehavior::Collect
    end;
}
```
2. Hover Over the keyword "Collect"

**3. Expected behavior**
I would have expected this text to show up

> Collectible errors will be gathered and code execution will be continued until the end of the ErrorBehvior scope. If errors are left unhandled at the **_and_** of the ErrorBehavior scope, execution will stop with an aggregated error.

**4. Actual behavior**
This text is shown

> Collectible errors will be gathered and code execution will be continued until the end of the ErrorBehvior scope. If errors are left unhandled at the **_nd_** of the ErrorBehavior scope, execution will stop with an aggregated error.

**5. Versions:**

- AL Language: 13.1.1065068
- Visual Studio Code: 1.91.0
- Business Central: None.

Internal work item: [AB#542457](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542457)

**Comment by JesperSchulz** [comment]
The fix for this issue has been checked in to the master branch. It will be available in the bcinsider.azurecr.io/bcsandbox-master Docker image starting from platform build number 25.0.22430.0 and VS Code Extension Version 14.0.1093063. 
 
 If you don’t have access to these images you need to become part of the Ready2Go program: aka.ms/readytogo 
 
 For more details on code branches and docker images please read: 
 https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ 
 https://freddysblog.com/2020/06/25/working-with-artifacts/
