### ISSUE TITLE
Page.Run with a empty ListPlus-Page

### ISSUE THREAD

**Issue by SKeiler** [microsoft/AL#7806]
Please include the following with each issue:

**1. Describe the bug**

If you start a ListPlus-Page from a Page.Run and the ListPlus-Page has page fields which are connected to global variables above the repeater, the field values are empty is the page has no records. If the Page has records, the field values are shown correctly.

**2. To Reproduce**
1. Set the Item Reclass. Journal Page (or a similar one) temporary to ListPlus
2. Go to the Warehouse Worker-Rolecenter
3. Open the Edit Item Reclass. Journal from the RoleCenter
4. If there are no lines in the page, the batch name on the page header is empty. If there are lines on the page, the batch name is filled.

![image](https://github.com/user-attachments/assets/3a5df91d-2a85-4d97-8574-6ebcf26f69a6)

![image](https://github.com/user-attachments/assets/f88bbf4b-6dde-4748-a6ff-d401c40c6685)

**3. Expected behavior**

In every case the header fields (assigned to global variables) should be filled.

**4. Actual behavior**

In some cases the header fields (assigned to global variables) are empty if the page has no records to show.

**5. Versions:**

- Business Central: 23.4

**Comment by thloke** [comment]
Hi, this issue is out of scope of for this repository. You should do one of the following:

- Open a support request to CSS through the PartnerSource portal
- Open a bug in Collaborate
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

As a reminder, this repository only handles issues to do with the compiler or VSCode development experience for AL.
