### ISSUE TITLE
RunTrigger Parameter gets ignored when using Custom API

### ISSUE THREAD

**Issue by SaschaM-Dev** [microsoft/AL#7855]
**1. Describe the bug**
When inserting a record into a table through a custom API, a different Record (in a completely different table) should be deleted. The OnDelete trigger gets executed, even when using `Rec.Delete(false)`.

**2. To Reproduce**
1. Create Custom API
2. Insert following Code in "OnInsertRecord" Trigger:

``` AL

    var
        ProductionBOMHeader: Record "Production BOM Header";
    begin
        if ProductionBOMHeader.Get(Rec."No.") then
            ProductionBOMHeader.Delete(false);
    end;

```

Try to run the code. The API will give warnings about "Production BOM Version" entries that cannot be deleted (if the status is set to certified). This error should never occur, when setting the RunTrigger to false.

**3. Expected behavior**
Deletion of the record without executing the code in the OnDelete Trigger in the affected table.

**4. Actual behavior**
OnDelete Trigger gets executed, despite setting RunTrigger to false.

**5. Versions:**

- AL Language: Latest
- Visual Studio Code: Latest
- Business Central: Latest
- List of Visual Studio Code extensions that you have installed: AL Extension.

**Comment by EmilDamsbo** [comment]
Hello, thank you for reporting this issue. It seems this issue is not related to the AL compiler or language, but rather with runtime behaviour of your AL code.

This type of issue is out of scope for this repository. We recommend you instead open up a support request via the Business Central Admin Center, and they will make sure your issue is handled.
