### ISSUE TITLE
False positives for warning AA0234

### ISSUE THREAD

**Issue by NKarolak** [microsoft/AL#7873]
@krupybalu, this is the follow-up for #7787

**1. Describe the bug**
Once activated, [AA0234](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0234) (You must write a tooltip in the Tooltip property for all fields on table objects.) fires too often.

**2. To Reproduce**
In a table field without any tooltip, use **one of the following** properties:
```
ObsoleteState = Removed;
Access = Internal;
AllowInCustomizations = Never;
```

**3. Expected behavior**
No warning, as none of these fields will ever appear in the UI to display a tooltip.

**4. Actual behavior**
Warning AA0234.

**5. Versions:**
- AL Language: 14.0.1161190
Internal work item: [AB#555928](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555928)

**Comment by krupybalu** [comment]
Hi @NKarolak,

Thank you for the suggestion.

After looking into it we believe that the warning is necessary in some of these cases. This is due to the fact that a field might get exposed in the future (except for the ObsoleteState removed scenario). A developer can write an API and expose the field from the table (or maybe even a new UI / some future concept). If the warning is a big issue it is always possible to turn it off with a pragma. However, we would strongly recommend to document all fields.

**Comment by NKarolak** [comment]
@krupybalu As you agree with the **ObsoleteState removed scenario**, why do you refuse to fix at least that? Please reconsider your decision to close this issue completely only because you disagree partly.
