### ISSUE TITLE
Controladdin compilation fails if two files in different folders have the same name

### ISSUE THREAD

**Issue by IridiumWasTaken** [microsoft/AL#7925]
**1. Describe the bug**
If two files of the same name in different folders are referenced in the 'Images' property part of a controladdin, the code won't compile because it does not recognize that the two files are not the same.

**2. To Reproduce**
Create a controladdin in which you add the following:

```
controladdin 10000 "TestControlAddin"
{
     Images = 'js/include/calcunit.js/calcunit.js',
                'js/include/calcunit.js/js/calcunit.js'
}
```

Try to compile the code.
js/include/calcunit.js is a folder, which contains the folder 'js' and the file 'calcunit.js'. The folder 'js' also contains a file called 'calcunit.js'.

**3. Expected behavior**
Compilation is possible.

**4. Actual behavior**
Compilation fails with error 'The identifier 'js/include/calcunit.js/js/calcunit.js' can only be specified in the list once.'.

**5. Versions:**

- AL Language: v14.1.1180850
- Visual Studio Code: 1.95.3
- Business Central: Version 25
- List of Visual Studio Code extensions that you have installed: AL Language extension for Microsoft Dynamics Business 365 Business Central
- Operating System:
  * Windows 11

**Comment by dannoe** [comment]
I can not reproduce this on my machine.

**Comment by krupybalu** [comment]
Thank you for reporting this issue.
It is caused by the calcunit.js file being searched not only in the top folder (js/include/calcunit.js), but also in all of its sub-directories as well. Thus both files are loaded already by the first path, which causes an error when the file in the subfolder is matched again by the second path.

As you mentioned, an easy workaround is to rename one of the files not to share the same name. As of now we will not be able to prioritize this.
