### ISSUE TITLE
Debugging JS based Control AddIns

### ISSUE THREAD

**Issue by PeterSchade1306** [Microsoft/AL#820]
Hello,

today I successfully tested the first JavaScript based control add-in with AL on Dynamics 365.
The implementation of my existing add-ins works without any problems - GOOD WORK!! :)

But is there a possibility to debug the control add-in directly in VS Code? 
If I try to set a breakpoint inside my js files there appears a warning message "file is not part of the current workspace".

It is possible to debug the control add-in js files in VS Code? 

At the moment, I only can debug in browsers.

Thank you!

**Comment by dennisfrostlander** [comment]
This is already possible using VSCode chrome debugger.

- Install [Chrome debugger extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
- Make sure Chrome has [remote debugging](https://github.com/Microsoft/vscode-chrome-debug#attach) enabled. 
- In `launch.json`, add a new configuration for attaching to Chrome:
```Json
{
  "type": "chrome",
  "request": "attach",
  "name": "Attach to Chrome",
  "port": 9222,
  "webRoot": "${workspaceRoot}"
}
```
- Click F5 to start AL debugger.
- In VSCode Debug panel, choose "Attach to chrome" and run it as well. At this point we are running two debuggers - AL debugger connected to the server and Chrome debugger connected to the browser.

![image](https://user-images.githubusercontent.com/16953692/31886635-7930a40c-b7f5-11e7-8be7-7b088059b48b.png)
- Hit some JavaScript code. I think it could be a bit problematic to debug StartupScript, since it is embedded directly in HTML code. I couldn't do it from the first try, but maybe Chrome debugger can be configured to debug JS inside HTML as well. Other scripts work fine though.

See attached sample project.
[ControlAddIn.zip](https://github.com/Microsoft/AL/files/1406879/ControlAddIn.zip)

JS breakpoint when clicking a button in the control add-in:
![image](https://user-images.githubusercontent.com/16953692/31886352-3d6cbd30-b7f4-11e7-85c1-edb831fd0bc2.png)
