### ISSUE TITLE
October Preview: Global Variables in properties

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/AL#828]
Hi all,

I have the problem that I cannot access any global variable in a property of a field. 
I tried following properties:
- Source of a field
- visible property

I already tried property InDataSet.

I have also one really strange object where VS Code raises an error for a global variable:
**Codeline 78:** DataMigrationSettingsVisible := TRUE; **Error Message:** The name DataMigrationSettingsVisible does not exists in the current context.

**Codeline 108:** Visible=DataMigrationSettingsVisible; **Error Message:** The name DataMigrationSettingsVisible does not exists in the current context.

**Codeline 360:** Visible=DataMigrationSettingsVisible AND (Step = Step::Import); **NO Error message**

**Codeline 567 / 568:** [InDataSet] DataMigrationSettingsVisible : Boolean;

Do anybody have a similar problem?

**Comment by jiwanovski87** [comment]
I have the error:

I had a wrong conversion from the txtConverter which was not highlighted. 
Wrong text line: TableRelation="G/L Account".No.;
Corrected text line: TableRelation="G/L Account"."No.";

After changing this line the compiler was able to find my variables.

**Comment by qutreson** [comment]
We made changes on the Txt2al converter (especially related to the conversion of the property TableRelation) over the last updates. It seems that this wrong conversion has been fixed since I couldn't reproduce it anymore. When using it, also don't forget to export the files from C/SIDE to new syntax since this can also be the origin of missing quotes in the converted AL files.
