### ISSUE TITLE
Style & StyleExpr Property in page not working

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#836]
Hi,

In page i have given the style properties as below 

![image](https://user-images.githubusercontent.com/26792519/31928266-1ba15cc6-b8b5-11e7-875e-211dc92b21d5.png)

but this is not showing the blue colour  with bold which it should show as below

![image](https://user-images.githubusercontent.com/26792519/31928350-78165f2e-b8b5-11e7-9edc-c1af636af73e.png)

Thanks & Regards
Varun Reddy

**Comment by DominikDitoIvosevic** [comment]
I'll investigate. Thank you for  the clear repro

**Comment by DominikDitoIvosevic** [comment]
The style is only for the value in the text box, not the label. The same behavior is in CSIDE. This is not a bug.

**Comment by bachii1010** [comment]
Hi Dominik,

As it is shown in my screen above it is text box only.
it works in cside so it should work in AL also.

Please suggest

Thanks & Regards
Varun Reddy

**Comment by DominikDitoIvosevic** [comment]
Hi @bachii1010 
I'm afraid I do not understand the issue you are reporting.

![image](https://user-images.githubusercontent.com/6378638/33938698-bdf55610-e008-11e7-83f3-bea2ee95d0a6.png)

![image](https://user-images.githubusercontent.com/6378638/33938713-c95c7a9c-e008-11e7-9f52-acc7b7619c4e.png)

![image](https://user-images.githubusercontent.com/6378638/33938722-d0b639cc-e008-11e7-9c91-37d6a35110fc.png)

I get the same behaviour from CSIDE and from Modern Dev.

I may have misunderstood what you are complaining about?
Could you please send me the 2 screenshots. 1 which is a result from CSIDE changes and 1 from Modern Dev so that I can see what you are complaining about.

Are you saying the label text on the **left** should be bold and blue?
The style only applies to the value text on the **right**

**Comment by bachii1010** [comment]
Hi 

Here are the screen shots you have requested
![image](https://user-images.githubusercontent.com/26792519/34036798-67cc9a50-e1ac-11e7-9061-21e9a96db5eb.png)

![image](https://user-images.githubusercontent.com/26792519/34036845-8f81734a-e1ac-11e7-813a-7b5124f98784.png)

**Comment by DominikDitoIvosevic** [comment]
Hi @bachii1010 . I finally figured out what the issue was. The fix is on the way.
