### ISSUE TITLE
'The Package Could Not Be Created' Microsoft / System package not found.

### ISSUE THREAD

**Issue by awcowan** [Microsoft/AL#844]
Hi,

We are struggling to build our project even though the symbols downloaded correctly. Any ideas what we are doing wrong? 

![image](https://user-images.githubusercontent.com/4295396/32053657-e25a3a96-ba53-11e7-904a-352919b34f7b.png)

Thanks
Andy

**Comment by dennisfrostlander** [comment]
You might have a problem in compatibility between the version of AL extension in VSCode and the version of the server. The symbol reference packages have been renamed to .app files instead of .navx (some time ago already), but the .alpackages folder still contains the .navx files.
Could you please check if you are using the latest versions (or at least versions coming from the same update) of the AL extension and server?
