### ISSUE TITLE
OnInstallAppPerCompany integration event in C1 vs Codeunit of type Install

### ISSUE THREAD

**Issue by jcooper01** [Microsoft/AL#898]
Just a question. I see that there are now a bunch of Integration Events in Codeunit 1 that look like they are for app install/upgrade management. When should we use these vs Install-type Codeunits with triggers? Can you please define when the integration events in C1 are called?

**Comment by ShaylaG-MSFT** [comment]
The recommendation is to **always use the Install-type and Upgrade-type codeunits** for executing install/upgrade logic, rather than the integration events from Codeunit 1. We feel it is more maintainable to isolate all install/upgrade logic in these dedicated codeunit types. Furthermore, the documentation and examples provided for support will likely use these codeunit types, rather than the integration events. Additionally, there is a chance that the integration events from Codeunit 1 may be removed in the near future (in favor of only allowing upgrade and install logic in the dedicated codeunit types) and you may need to modify your extension at that time to use the triggers. That said, you currently are able to subscribe to the integration events from Codeunit 1. Those events will fire during an install/upgrade (in the same order and manner that the triggers from the Install/Upgrade codeunits do). However, **the official recommendation is to use the Install-type and Upgrade-type codeunits**.
