### ISSUE TITLE
Error after unpublishing the app

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/AL#905]
Hi,

We are getting the below error when we are importing  and then compiling the object in NAV database which is used in the app after the unpublish of the app.
![image](https://user-images.githubusercontent.com/26792519/32601389-7296d1a4-c568-11e7-91ef-7cda002062c1.png)

Please suggest.

Thanks & regards
Varun Reddy

**Comment by Nagaraju17** [comment]
Can any one help on this  issue..

**Comment by HunterFeltman-MSFT** [comment]
From the looks of it, you're doing this stuff locally using the management cmdlets? (e.g. Publish-NavApp)

After you 'unpublished' your extension, did you clean the schema?
For V2 extensions there is a 'Sync' process that must be done after publish before you can install a package. This is the process that adds the tables/table extensions you developed to SQL and can be performed using the 'Sync-NavApp' cmdlet.

The tables that are created during this process 'live on' even after you've unpublished your extension, and I think that might be the problem you're running into.

In order to 'remove' them and bring your DB schema back to what is was before the extension, you need to use the 'clean' mode of the sync cmdlet.

`Sync-NavApp -Name <ext name> -Mode Clean
`

This will remove any tables/fields added by **EVERY VERSION** of the extension.
As a result of this, you will also **LOSE ALL OF THE DATA** that was in those tables.

**Comment by bachii1010** [comment]
Hi,

We are not using cmdlets to publish or unpublish the app.

We do Ctrl + F5 to publish the app and from the extension management page we click unpublish to  unpublish the app. 

Please suggest still we have to do sync.

It should do  automatically?

**Comment by HunterFeltman-MSFT** [comment]
Yes, you will still have to do a sync in this scenario. The 'unpublish' action on the extension management page does not do this automatically.

**Comment by bachii1010** [comment]
Hi,

Can this be automated in future updates so that when the unpublish action is clicked the sync happens automamtically.

It would be a nice feature.

**Comment by Nagaraju17** [comment]
Hi,
Still am facing some other issue. After i followed the above steps and later i merge the changes into standard object and compiling ...getting below error.
![image](https://user-images.githubusercontent.com/30176345/33823692-fc9af704-de81-11e7-883a-e3a56be8763e.png)

**Comment by HunterFeltman-MSFT** [comment]
This error should only occur if your table definition contains multiple fields with the same 'name' property. Since this is happening during compilation of the table in C\SIDE, I would first just double check that the 'Sales Header' table doesn't have duplicate fields. 

Additionally, I would double check that it isn't another installed extension that is adding this field by uninstalling any/all extensions. Since C\SIDE (the development environment) cannot 'see' fields added by extensions, this could occur if an extension were installed that added a field to the Sales Header table, and then a developer went into C\SIDE and added that field again to the Sales Header table.
