### ISSUE TITLE
Downloading symbols and deployment

### ISSUE THREAD

**Issue by anzwdev** [Microsoft/AL#932]
This issue is related to issue #920, but it is about a different case.

I am trying to learn what can be done with the new AL compiler and Roslyn based libraries by integrating them with big Visual Studio. I have to say that they are awesome, I can easily use them to add intellisense, quick infos, signature help and "find all references" functionality to code editor.
I was also able to integrate al compiler with MSBuild and Visual Studio, but I have problems with Microsoft.Dynamics.Nav.Deployment library. 

I would like to be able to invoke symbol downloading from project context menu and to be able to upload compiled extensions to my local docker Nav service to test it. Unfortunately all classes in that library are internal and there is no way of passing user name and password to them without storing that information in encrypted file. Could you make these classes public and add password and user name properties to them? Could you also modify webdeploy.exe to support these 2 parameters?

**Comment by StanislawStempin** [comment]
While we appreciate the community effort on this topic, we currently do not target enabling integration with Visual Studio. 

Since Visual Studio is a Microsoft product, if we were to have AL Language integration we would like to make sure it's complete and fully supported by us. 
Therefore we will not expose more APIs and any effort to integrate with Visual Studio should be treated as experimental and not for production use.
