### ISSUE TITLE
Rename Symbol Missing Some Uses

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/AL#949]
Using Rename Symbol to rename a field doesn't rename their use in:

- Event subscribers e.g. OnAfterFieldValidate subscription
- Field properties (at least the Enabled property - haven't tested with others, see below).

field(50100;"My other field";Text[50])
{
  Enabled = "My field" <> "My field"::"Some option value"
}

Renaming "My field" didn't rename these uses.

VS Code extension 0.11.15001

**Comment by esbenk** [comment]
The current subscriber syntax (inherited from .txt) is using a string literal which causes some headaches when it comes to rename. We are investigating other options for specifying subscriber that will also work better with intellisense - e.g. a dotted syntax for specifying the target.

In the second case the syntax is invalid. The Enabled property on fields expects a literal true/false and not an expression. Since the rename functionality is based on symbolic information it will not change invalid syntax. The power of that is of course that you only change the places that is actually references that symbol.
