### ISSUE TITLE
Search Pattern in Script Property

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/AL#958]
It would be cool if you could specify not only specific scripts but also folders or search patterns for a Control AddIn in the Script property.

![scripts](https://user-images.githubusercontent.com/16351673/33016395-ab4d0836-cdee-11e7-9a3f-b2a1c561b90f.png)

**Comment by dennisfrostlander** [comment]
It's not that simple :) The order of scripts matters - for example, jquery plugins go after jquery, etc. 
With a wildcard we'd start relying on alphabetical order of file names, so you would need to make sure that the script files have "correct" names, e.g. 1-jquery.js, 2-jquery.plugin.js, etc.

P.S. If you have a large javascript solution with many scripts, you might simply use a bundler like [webpack](https://webpack.js.org/) which will produce a single script which could be referenced in the control add-in. And it all can live in the same AL folder.

**Comment by Gallimathias** [comment]
That means you sort the scripts on the server or in the archive of the extension?

So if I have 3 scripts e. g:
Projectfolder:
* js/field.js
* js/brackerts.js.
* game.js

How are they split?

When game.js using jquery, it automatically lands in a jquery folder?? 

e.g.:
Server:
* js/field.js
* js/brackerts.js.
* jquery/game.js

**Comment by dennisfrostlander** [comment]
As of now, we don't sort anything ourselves. We use exactly the same order that is specified in the `Scripts` property. Sorting _will_ become a problem if we allow wildcards (search patterns) like 'js/*.js'.

**Comment by Gallimathias** [comment]
I don't seem to understand the problem. 

If I have a lot of scripts, why is it important for me to have a Sorting?

**Comment by dennisfrostlander** [comment]
The scripts in JavaScripts _may_ require a specific order in which they are added to the html.
For example:
- jquery.js defines a global variable `$`, e.g. `window.$ = { ... }`
- jquery.plugin.js uses the `$` variable to register its functionality, for example, `window.$.fn.myPlugin = function() {}`

If in your html you add `<script src="jquery.plugin.js"></script>` before `jquery.js` it will fail to load since `$` variable is not defined yet.

This is not always the case, some scripts may require specific order in the html doc, others don't.

Currently, the `Scripts` property requires a developer to list each script file, defining this way a specific order of loading scripts. Even though a developer might not need the order.

P.S. If the control add-in solution grows large and it becomes hard to maintain all those script references, you might consider using a bunlder like [webpack](https://webpack.js.org/). It will combine all scripts into a single script file by following dependencies (should there be any), etc. It will also be faster to load a single script instead of many separate files.

**Comment by Gallimathias** [comment]
Ok thanks dennis, I understand the problem now and like JS even less than before. 

I still like my idea with RegEx support. It just doesn't feel right to make the load order depend on how I write it into the script property.
