### ISSUE TITLE
use scope/context rather than startupobjectid

### ISSUE THREAD

**Issue by johanemilsson** [Microsoft/AL#960]
Before logging a new issue please make sure to:
1) Read the [FAQ](https://github.com/Microsoft/AL/wiki/Frequently-Asked-Questions)
2) Search if there is an existing issue for what you want to log. If it's closed you can reopen it and add your comments.
3) Use the latest Developer Preview release both the server part and the AL Language extension in VS Code (listed on the [repository home page](https://github.com/Microsoft/AL))
4) If you're not using the latest released version (or are using a private build drop that is newer) please provide the version number in the issue

To help us reproduce the issue and find the root please try to:
A) Attach a minimal set of AL code that causes the issue
B) If the error occurs on the server - copy/paste the server stack trace from the Event Viewer

**Comment by tfenster** [comment]
some shameless self-advertising: [This](https://marketplace.visualstudio.com/items?itemName=tfenster.alrunner) should help you with exactly that. But you should also look at [this](https://marketplace.visualstudio.com/items?itemName=waldo.crs-al-language-extension) because it offers something very similar and also loads more (by @waldo1001)

**Comment by Gallimathias** [comment]
@johanemilsson Please edit your issue again so that your message is not completely in the headline ;).

This makes it easier for us :D
