### ISSUE TITLE
Errors during publishing / installing an extension in VS Code: "A task was canceled"

### ISSUE THREAD

**Issue by MaKnauer** [Microsoft/AL#985]
In some cases, although the compiler in VS Code shows no error, an extension can not be published or installed.
Currently there is only a generic error message "A Task was canceled".
When you take a look in the event log, or use the publish / install powershell methods, a more precise error is shown.
E.g license issues, or callstacks...

It would be nice if you could show these errors in VS Code as well.

**Comment by pmohanakrishna** [comment]
@StanislawStempin any update on this?

**Comment by StanislawStempin** [comment]
We believe that this should have been fixed on the latest version of AL Language (0.15) and recent VS Code versions (1.21+). Please comment on this issue if you are still running into a problem

You will still not see call stacks in VS Code but errors about duplicate IDs, duplicate extension, license problems etc. will all be shown in VS Code.

**Comment by GreatScott000** [comment]
I am receiving the same error message but there are no events in the application event log related to it AL.
I start a my extension in VS Code (F5 or Ctrl+F5, doesn't matter) and after an extended period of time (several minutes), the `Error: A task was canceled.` message appears.

The default AL Project (Hello World) works so that implies that it is a problem my extension but I have no where to start looking without some feedback from the system.

This is on premise using AL version 0.12.17720 (NAV 2018 CU04 build 21441).

Thoughts?

**Comment by StanislawStempin** [comment]
For NAV 2018 issues please contact our Support team.

**Comment by GreatScott000** [comment]
So how do I do this without using up my support incidents or having to pay for one?
